[CmdletBinding(SupportsShouldProcess=$true,ConfirmImpact='High')]
param([switch]$ConfirmProductionDeployment,[string]$ServerInstance='localhost',[string]$DatabaseName='SOODAL_LIFE_DEV',[string]$AppsRoot='D:\SOODALLIFE\apps',[string]$ReleaseRoot='D:\SOODALLIFE\releases',[string]$DatabaseBackupRoot='D:\SOODALLIFE\DB\Backup')
$ErrorActionPreference='Stop'
if(-not $ConfirmProductionDeployment){throw 'Safety stop: rerun with -ConfirmProductionDeployment after reviewing the package and target settings.'}
$identity=[Security.Principal.WindowsIdentity]::GetCurrent();$principal=[Security.Principal.WindowsPrincipal]::new($identity);if(-not $principal.IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)){throw 'Run this script from an elevated Administrator PowerShell.'}
$zip=Join-Path $PSScriptRoot 'SoodalLife-HelpRoomPhotoSafety-20260830-v165.zip';if(-not(Test-Path -LiteralPath $zip -PathType Leaf)){throw "V165 ZIP is missing beside this script: $zip"}
$expected='__ZIP_SHA256__';$actual=(Get-FileHash -LiteralPath $zip -Algorithm SHA256).Hash;if($actual-ne$expected){throw "V165 ZIP integrity check failed. Expected=$expected Actual=$actual"};Write-Host '1/4 ZIP integrity check passed.' -ForegroundColor Green
$stamp=Get-Date -Format 'yyyyMMdd-HHmmss';$extractParent=Join-Path $ReleaseRoot "help-room-photo-safety-v165-$stamp";New-Item -ItemType Directory -Force -Path $extractParent|Out-Null;Expand-Archive -LiteralPath $zip -DestinationPath $extractParent
$release=Join-Path $extractParent 'help-room-photo-safety-v165-final';$required=@('api\SoodalLife.Api.dll','api\web.config','frontend\customer\index.html','frontend\partner\index.html','frontend\admin\index.html','deployment\Apply-HelpRoomPhotoSafetyV165.sql','deployment\Verify-HelpRoomPhotoSafetyV165.sql','Publish-Production.ps1','RELEASE-MANIFEST.txt');foreach($relative in $required){if(-not(Test-Path -LiteralPath (Join-Path $release $relative) -PathType Leaf)){throw "Required V165 release file is missing: $relative"}}
$apply=Get-Content -LiteralPath (Join-Path $release 'deployment\Apply-HelpRoomPhotoSafetyV165.sql') -Raw;if($apply-notmatch 'HELP_ROOM_PHOTO' -or $apply-notmatch '20260830090402_AddHelpRoomPhotoSafetyV165'){throw 'V165 database migration marker is missing.'};Write-Host "2/4 Extracted V165 deployment validated: $release" -ForegroundColor Green
if(-not $PSCmdlet.ShouldProcess("API, customer, partner and admin apps at $AppsRoot plus database $DatabaseName",'Deploy V165 local help room photo safety')){return};Write-Host '3/4 Running protected database, API and frontend backup followed by IIS deployment.' -ForegroundColor Yellow
& (Join-Path $release 'Publish-Production.ps1') -ConfirmProductionDeployment -ServerInstance $ServerInstance -DatabaseName $DatabaseName -AppsRoot $AppsRoot -BackupParent $ReleaseRoot -DatabaseBackupRoot $DatabaseBackupRoot -Confirm:$false
if(-not $?){throw 'V165 protected deployment script failed.'};Write-Host '4/4 V165 local help room photo safety deployment completed.' -ForegroundColor Green;Write-Host "Extracted release path: $release" -ForegroundColor Yellow
