using System.Security.Claims;
using System.Text.Json;
using Microsoft.EntityFrameworkCore;
using SoodalLife.Api.Domain.Entities;
using SoodalLife.Api.Features.Authentication;
using SoodalLife.Api.Infrastructure.Persistence;

namespace SoodalLife.Api.Features.Reviews;

public sealed class ReviewConversationService(SoodalLifeDbContext db)
{
    public async Task<IReadOnlyList<ReviewConversationResponse>> CustomerList(ClaimsPrincipal principal,CancellationToken token)
    {
        var identity=await Customer(principal,token);var ids=await db.Reviews.AsNoTracking().Where(x=>x.CustomerProfileId==identity.ProfileId).Select(x=>x.Id).ToListAsync(token);var result=new List<ReviewConversationResponse>();foreach(var id in ids)result.Add(await Build(id,false,identity.UserId,token));return result.OrderByDescending(x=>x.LatestActivityAt).ToArray();
    }

    public async Task<IReadOnlyList<ReviewConversationResponse>> ProviderList(ClaimsPrincipal principal,CancellationToken token)
    {
        var identity=await Provider(principal,token);var ids=await db.Reviews.AsNoTracking().Where(x=>x.ProviderProfileId==identity.ProfileId).Select(x=>x.Id).ToListAsync(token);var result=new List<ReviewConversationResponse>();foreach(var id in ids)result.Add(await Build(id,true,identity.UserId,token));return result.OrderByDescending(x=>x.LatestActivityAt).ToArray();
    }

    public async Task<ReviewConversationUnreadCountResponse> CustomerUnread(ClaimsPrincipal principal,CancellationToken token){var identity=await Customer(principal,token);return new(await Unread(identity.UserId,token));}
    public async Task<ReviewConversationUnreadCountResponse> ProviderUnread(ClaimsPrincipal principal,CancellationToken token){var identity=await Provider(principal,token);return new(await Unread(identity.UserId,token));}
    public async Task CustomerReadAll(ClaimsPrincipal principal,CancellationToken token){var identity=await Customer(principal,token);await MarkRead(identity.UserId,token);}
    public async Task ProviderReadAll(ClaimsPrincipal principal,CancellationToken token){var identity=await Provider(principal,token);await MarkRead(identity.UserId,token);}

    public async Task<ReviewCommentResponse> CustomerPost(ClaimsPrincipal principal,Guid reviewId,CreateReviewCommentRequest input,CancellationToken token)
    {
        var identity=await Customer(principal,token);var review=await db.Reviews.SingleOrDefaultAsync(x=>x.PublicId==reviewId&&x.CustomerProfileId==identity.ProfileId,token)??throw NotFound();var name=await db.CustomerProfiles.Where(x=>x.Id==identity.ProfileId).Select(x=>x.DisplayName).SingleAsync(token);return await Post(review,identity.UserId,RoleCodes.Customer,MaskName(name),input,token);
    }

    public async Task<ReviewCommentResponse> ProviderPost(ClaimsPrincipal principal,Guid reviewId,CreateReviewCommentRequest input,CancellationToken token)
    {
        var identity=await Provider(principal,token);var review=await db.Reviews.SingleOrDefaultAsync(x=>x.PublicId==reviewId&&x.ProviderProfileId==identity.ProfileId,token)??throw NotFound();var name=await db.ProviderProfiles.Where(x=>x.Id==identity.ProfileId).Select(x=>x.BusinessName).SingleAsync(token);return await Post(review,identity.UserId,RoleCodes.Provider,name,input,token);
    }

    public async Task<IReadOnlyList<ReviewCommentResponse>> AdminList(Guid reviewId,CancellationToken token)
    {
        var review=await db.Reviews.AsNoTracking().SingleOrDefaultAsync(x=>x.PublicId==reviewId,token)??throw NotFound();return await Comments(review.Id,true,token);
    }

    public async Task<ReviewCommentResponse> Moderate(ClaimsPrincipal principal,Guid reviewId,Guid commentId,ModerateReviewCommentRequest input,CancellationToken token)
    {
        var actor=await Admin(principal,token);var target=input.TargetStatus?.Trim().ToUpperInvariant();if(target is not("ACTIVE" or "HIDDEN"))throw Invalid("REVIEW_COMMENT_STATUS_INVALID","댓글 상태를 확인해 주세요.");var reason=input.Reason?.Trim();if(string.IsNullOrWhiteSpace(reason)||reason.Length>1000)throw Invalid("REVIEW_COMMENT_REASON_REQUIRED","숨김 또는 복원 사유를 입력해 주세요.");var comment=await(from value in db.ReviewComments join review in db.Reviews on value.ReviewId equals review.Id where review.PublicId==reviewId&&value.PublicId==commentId select value).SingleOrDefaultAsync(token)??throw new ReviewBusinessException(404,"REVIEW_COMMENT_NOT_FOUND","댓글을 찾을 수 없습니다.");ApplyVersion(comment,input.RowVersion);var before=comment.StatusCode;if(before!=target){comment.StatusCode=target;comment.HiddenAt=target=="HIDDEN"?DateTime.UtcNow:null;comment.HiddenByUserId=target=="HIDDEN"?actor:null;comment.HiddenReason=target=="HIDDEN"?reason:null;comment.UpdatedAt=DateTime.UtcNow;db.AuditLogs.Add(new AuditLog{OccurredAt=DateTime.UtcNow,ActorUserId=actor,ActorRoleCode=RoleCodes.Admin,ActionCode=target=="HIDDEN"?"REVIEW_COMMENT_HIDE":"REVIEW_COMMENT_RESTORE",EntityType="REVIEW_COMMENT",EntityPublicId=comment.PublicId,ResultCode="SUCCESS",Reason=reason,BeforeJson=JsonSerializer.Serialize(new{status=before}),AfterJson=JsonSerializer.Serialize(new{status=target})});try{await db.SaveChangesAsync(token);}catch(DbUpdateConcurrencyException){throw new ReviewBusinessException(409,"REVIEW_COMMENT_CONFLICT","다른 관리자가 댓글 상태를 변경했습니다.");}}return Map(comment,true,await Depth(comment,token),await ParentPublicId(comment,token));
    }

    private async Task<ReviewCommentResponse> Post(Review review,long userId,string role,string displayName,CreateReviewCommentRequest input,CancellationToken token)
    {
        if(review.VisibilityStatusCode!="PUBLIC")throw new ReviewBusinessException(409,"REVIEW_COMMENT_REVIEW_HIDDEN","숨김 처리된 리뷰에는 댓글을 작성할 수 없습니다.");var body=Required(input.BodyText,2000);var key=Required(input.IdempotencyKey,150);var existing=await db.ReviewComments.AsNoTracking().SingleOrDefaultAsync(x=>x.IdempotencyKey==key,token);if(existing is not null){if(existing.AuthorUserId!=userId)throw new ReviewBusinessException(409,"IDEMPOTENCY_KEY_CONFLICT","이미 다른 댓글에 사용된 키입니다.");return Map(existing,false,await Depth(existing,token),await ParentPublicId(existing,token));}var own=await db.ReviewComments.AsNoTracking().Where(x=>x.ReviewId==review.Id&&x.AuthorUserId==userId&&x.StatusCode=="ACTIVE").Select(x=>new{x.BodyText,x.SubmittedAt}).ToListAsync(token);var normalized=Normalize(body);if(own.Any(x=>Normalize(x.BodyText)==normalized))throw new ReviewBusinessException(409,"REVIEW_COMMENT_DUPLICATE","같은 내용의 댓글은 다시 등록할 수 없습니다.");var now=DateTime.UtcNow;var latest=await db.ReviewComments.AsNoTracking().Where(x=>x.ReviewId==review.Id&&x.StatusCode=="ACTIVE").OrderByDescending(x=>x.SubmittedAt).Select(x=>new{x.AuthorUserId,x.SubmittedAt}).FirstOrDefaultAsync(token);if(latest?.AuthorUserId==userId&&latest.SubmittedAt>now.AddMinutes(-1))throw new ReviewBusinessException(429,"REVIEW_COMMENT_COOLDOWN","연속 댓글은 1분 간격으로 등록할 수 있습니다.");long? parentId=null;if(input.ParentCommentId.HasValue){var parent=await db.ReviewComments.AsNoTracking().SingleOrDefaultAsync(x=>x.PublicId==input.ParentCommentId&&x.ReviewId==review.Id&&x.StatusCode=="ACTIVE",token)??throw Invalid("REVIEW_COMMENT_PARENT_INVALID","답글 대상 댓글을 찾을 수 없습니다.");if(await Depth(parent,token)>=5)throw Invalid("REVIEW_COMMENT_DEPTH_LIMIT","답글은 5단계까지만 등록할 수 있습니다.");parentId=parent.Id;}var value=new ReviewComment{ReviewId=review.Id,ParentCommentId=parentId,AuthorUserId=userId,AuthorRoleCode=role,AuthorDisplayName=displayName,BodyText=body,StatusCode="ACTIVE",IdempotencyKey=key,SubmittedAt=now,CreatedAt=now,UpdatedAt=now};db.ReviewComments.Add(value);await db.SaveChangesAsync(token);await Notify(review,value,userId,role,token);return Map(value,false,await Depth(value,token),input.ParentCommentId);
    }

    private async Task<ReviewConversationResponse> Build(long reviewId,bool providerView,long viewerUserId,CancellationToken token)
    {
        var row=await(from review in db.Reviews.AsNoTracking() join provider in db.ProviderProfiles.AsNoTracking() on review.ProviderProfileId equals provider.Id join customer in db.CustomerProfiles.AsNoTracking() on review.CustomerProfileId equals customer.Id where review.Id==reviewId select new{review,provider,customer}).SingleAsync(token);Guid? transactionId=null;string sourceLabel;if(row.review.TransactionId.HasValue){transactionId=await db.Transactions.Where(x=>x.Id==row.review.TransactionId).Select(x=>(Guid?)x.PublicId).SingleAsync(token);sourceLabel=$"거래 리뷰 · RV-{row.review.Id:D8}";}else sourceLabel=$"수달 케어 리뷰 · RV-{row.review.Id:D8}";var comments=await Comments(row.review.Id,false,token);var latest=comments.Count==0?row.review.SubmittedAt:comments.Max(x=>x.SubmittedAt);var unread=await(from recipient in db.NotificationRecipients.AsNoTracking() join notification in db.Notifications.AsNoTracking() on recipient.NotificationId equals notification.Id where recipient.UserId==viewerUserId&&recipient.ReadAt==null&&recipient.ArchivedAt==null&&notification.TypeCode=="REVIEW_COMMENT_ADDED"&&notification.ReviewId==row.review.Id select recipient.Id).CountAsync(token);return new(row.review.PublicId,transactionId,sourceLabel,row.provider.PublicId,row.provider.BusinessName,providerView?MaskName(row.customer.DisplayName):row.customer.DisplayName,row.review.BodyText,row.review.VisibilityStatusCode,row.review.SubmittedAt,latest,unread,comments);
    }

    private async Task<int> Unread(long userId,CancellationToken token)=>await(from recipient in db.NotificationRecipients.AsNoTracking() join notification in db.Notifications.AsNoTracking() on recipient.NotificationId equals notification.Id where recipient.UserId==userId&&recipient.ReadAt==null&&recipient.ArchivedAt==null&&notification.TypeCode=="REVIEW_COMMENT_ADDED" select recipient.Id).CountAsync(token);
    private async Task MarkRead(long userId,CancellationToken token){var rows=await(from recipient in db.NotificationRecipients join notification in db.Notifications on recipient.NotificationId equals notification.Id where recipient.UserId==userId&&recipient.ReadAt==null&&recipient.ArchivedAt==null&&notification.TypeCode=="REVIEW_COMMENT_ADDED" select recipient).ToListAsync(token);if(rows.Count==0)return;var now=DateTime.UtcNow;foreach(var row in rows)row.ReadAt=now;await db.SaveChangesAsync(token);}
    private async Task Notify(Review review,ReviewComment comment,long actorUserId,string actorRole,CancellationToken token){var target=actorRole==RoleCodes.Customer?await db.ProviderProfiles.Where(x=>x.Id==review.ProviderProfileId).Select(x=>new{x.UserId,Role=RoleCodes.Provider}).SingleAsync(token):await db.CustomerProfiles.Where(x=>x.Id==review.CustomerProfileId).Select(x=>new{x.UserId,Role=RoleCodes.Customer}).SingleAsync(token);var now=DateTime.UtcNow;var route=target.Role==RoleCodes.Provider?$"/provider/reviews?review={review.PublicId}":$"/customer/reviews?review={review.PublicId}";var notification=new Notification{RecipientUserId=target.UserId,ReviewId=review.Id,TypeCode="REVIEW_COMMENT_ADDED",PriorityCode="NORMAL",SourceTypeCode="ReviewComment",SourcePublicId=comment.PublicId,TargetTypeCode="Review",TargetPublicId=review.PublicId,StatusCode="RECORDED",Title="리뷰에 새 댓글이 등록되었습니다.",Body=$"{comment.AuthorDisplayName}님이 리뷰 대화에 새 글을 남겼습니다.",DataJson=JsonSerializer.Serialize(new{route,reviewId=review.PublicId}),RecordedAt=now,IdempotencyKey=$"review-comment:{comment.PublicId:N}:{target.UserId}",CreatedByUserId=actorUserId};db.Notifications.Add(notification);await db.SaveChangesAsync(token);var recipient=new NotificationRecipient{NotificationId=notification.Id,UserId=target.UserId,RecipientRoleCode=target.Role,CreatedAt=now};db.NotificationRecipients.Add(recipient);await db.SaveChangesAsync(token);db.NotificationDeliveries.Add(new NotificationDelivery{NotificationId=notification.Id,NotificationRecipientId=recipient.Id,ChannelCode="WEB",AttemptNo=1,StatusCode="DELIVERED",AttemptedAt=now,CompletedAt=now,DeliveredAt=now,RetryCount=0,CreatedAt=now,UpdatedAt=now});await db.SaveChangesAsync(token);}

    private async Task<IReadOnlyList<ReviewCommentResponse>> Comments(long reviewId,bool admin,CancellationToken token)
    {
        var rows=await db.ReviewComments.AsNoTracking().Where(x=>x.ReviewId==reviewId).OrderBy(x=>x.SubmittedAt).ToListAsync(token);var result=new List<ReviewCommentResponse>(rows.Count);foreach(var row in rows)result.Add(Map(row,admin,Depth(row,rows),row.ParentCommentId.HasValue?rows.FirstOrDefault(x=>x.Id==row.ParentCommentId.Value)?.PublicId:null));return result;
    }
    private static int Depth(ReviewComment value,IReadOnlyList<ReviewComment> rows){var depth=0;var parent=value.ParentCommentId;var visited=new HashSet<long>();while(parent.HasValue&&visited.Add(parent.Value)){var item=rows.FirstOrDefault(x=>x.Id==parent.Value);if(item is null)break;depth++;parent=item.ParentCommentId;}return depth;}
    private async Task<int> Depth(ReviewComment value,CancellationToken token){var rows=await db.ReviewComments.AsNoTracking().Where(x=>x.ReviewId==value.ReviewId).ToListAsync(token);return Depth(value,rows);}
    private Task<Guid?> ParentPublicId(ReviewComment value,CancellationToken token)=>value.ParentCommentId.HasValue?db.ReviewComments.AsNoTracking().Where(x=>x.Id==value.ParentCommentId.Value).Select(x=>(Guid?)x.PublicId).SingleOrDefaultAsync(token):Task.FromResult<Guid?>(null);
    private static ReviewCommentResponse Map(ReviewComment value,bool admin,int depth,Guid? parentPublicId)=>new(value.PublicId,parentPublicId,value.AuthorRoleCode,value.AuthorDisplayName,value.StatusCode=="HIDDEN"&&!admin?"관리자에 의해 숨김 처리된 댓글입니다.":value.BodyText,value.StatusCode,value.SubmittedAt,depth,Convert.ToBase64String(value.RowVersion));
    private async Task<(long UserId,long ProfileId)> Customer(ClaimsPrincipal p,CancellationToken t){var id=Subject(p);return await(from u in db.Users where u.PublicId==id&&u.StatusCode=="ACTIVE" join c in db.CustomerProfiles on u.Id equals c.UserId select new ValueTuple<long,long>(u.Id,c.Id)).SingleOrDefaultAsync(t) is var x&&x.Item1!=0?x:throw new ReviewBusinessException(403,"CUSTOMER_PROFILE_REQUIRED","고객 프로필이 필요합니다.");}
    private async Task<(long UserId,long ProfileId)> Provider(ClaimsPrincipal p,CancellationToken t){var id=Subject(p);return await(from u in db.Users where u.PublicId==id&&u.StatusCode=="ACTIVE" join c in db.ProviderProfiles on u.Id equals c.UserId select new ValueTuple<long,long>(u.Id,c.Id)).SingleOrDefaultAsync(t) is var x&&x.Item1!=0?x:throw new ReviewBusinessException(403,"PROVIDER_PROFILE_REQUIRED","전문가 프로필이 필요합니다.");}
    private async Task<long> Admin(ClaimsPrincipal p,CancellationToken t){var id=Subject(p);return await(from u in db.Users join ur in db.UserRoles on u.Id equals ur.UserId join r in db.Roles on ur.RoleId equals r.Id where u.PublicId==id&&u.StatusCode=="ACTIVE"&&ur.RevokedAt==null&&r.Code==RoleCodes.Admin select(long?)u.Id).SingleOrDefaultAsync(t)??throw new ReviewBusinessException(403,"ADMIN_REQUIRED","관리자 권한이 필요합니다.");}
    private static Guid Subject(ClaimsPrincipal p)=>Guid.TryParse(p.FindFirstValue(ClaimTypes.NameIdentifier),out var id)?id:throw new ReviewBusinessException(403,"AUTH_REQUIRED","로그인이 필요합니다.");
    private static string Required(string? value,int max){var text=value?.Trim();if(string.IsNullOrWhiteSpace(text)||text.Length>max)throw Invalid("REVIEW_COMMENT_INPUT_INVALID",$"댓글은 1자 이상 {max:N0}자 이하로 입력해 주세요.");return text;}
    private static string Normalize(string value)=>string.Join(' ',value.Trim().Split((char[]?)null,StringSplitOptions.RemoveEmptyEntries)).ToUpperInvariant();
    private static void ApplyVersion(ReviewComment value,string token){byte[] version;try{version=Convert.FromBase64String(token);}catch{throw Invalid("REVIEW_COMMENT_VERSION_INVALID","댓글 버전정보를 확인해 주세요.");}if(!value.RowVersion.SequenceEqual(version))throw new ReviewBusinessException(409,"REVIEW_COMMENT_CONFLICT","다른 화면에서 댓글 상태가 변경되었습니다.");}
    private static string MaskName(string value)=>string.IsNullOrWhiteSpace(value)?"고객":value.Length==1?$"{value}*":$"{value[0]}*{value[^1]}";
    private static ReviewBusinessException NotFound()=>new(404,"REVIEW_NOT_FOUND","리뷰를 찾을 수 없습니다.");
    private static ReviewBusinessException Invalid(string code,string message)=>new(400,code,message);
}
