using System.Data;
using System.Security.Claims;
using System.Security.Cryptography;
using System.Text;
using System.Text.Json;
using Microsoft.EntityFrameworkCore;
using SoodalLife.Api.Domain.Entities;
using SoodalLife.Api.Features.Authentication;
using SoodalLife.Api.Features.Work;
using SoodalLife.Api.Infrastructure.Persistence;

namespace SoodalLife.Api.Features.HelpRoom;

public sealed class SuggestionService(SoodalLifeDbContext db)
{
    private static readonly string[] Types=["BUG","MISSING","UX","FEATURE","SECURITY","OTHER"];
    private static readonly string[] Statuses=["RECEIVED","REVIEWING","PLANNED","FIXED","CLOSED"];
    public async Task<IReadOnlyList<SuggestionResponse>> Mine(ClaimsPrincipal p,CancellationToken token){var user=await User(p,token);var rows=await Query().Where(x=>x.UserId==user.Id).OrderByDescending(x=>x.CreatedAt).ToListAsync(token);return rows.Select(Map).ToList();}
    public async Task<SuggestionResponse> Detail(ClaimsPrincipal p,Guid id,CancellationToken token){var user=await User(p,token);var row=await Query().SingleOrDefaultAsync(x=>x.PublicId==id&&(x.UserId==user.Id||user.IsAdmin),token)??throw Error("SUGGESTION_NOT_FOUND","제안을 찾을 수 없습니다.",404);return Map(row);}
    public async Task<SuggestionResponse> Create(ClaimsPrincipal p,CreateSuggestionInput input,CancellationToken token)
    {
        var user=await User(p,token);var type=input.TypeCode.Trim().ToUpperInvariant();if(!Types.Contains(type))throw Error("SUGGESTION_TYPE_INVALID","제안 유형을 확인해 주세요.");var title=Required(input.Title,5,200);var body=Required(input.Body,10,5000);var key=Required(input.IdempotencyKey,8,100);var hash=SHA256.HashData(Encoding.UTF8.GetBytes($"{type}|{Normalize(title)}|{Normalize(body)}"));
        await using var transaction=db.Database.IsRelational()?await db.Database.BeginTransactionAsync(IsolationLevel.Serializable,token):null;
        var existing=await db.UserSuggestions.AsNoTracking().SingleOrDefaultAsync(x=>x.IdempotencyKey==key,token);if(existing is not null)return existing.UserId==user.Id?await Detail(p,existing.PublicId,token):throw Error("SUGGESTION_IDEMPOTENCY_CONFLICT","이미 사용된 중복 방지 키입니다.",409);
        var now=DateTime.UtcNow;var seoul=now.AddHours(9).Date;var start=DateTime.SpecifyKind(seoul.AddHours(-9),DateTimeKind.Utc);var end=start.AddDays(1);
        if(await db.UserSuggestions.CountAsync(x=>x.UserId==user.Id&&x.CreatedAt>=start&&x.CreatedAt<end,token)>=5)throw Error("SUGGESTION_DAILY_LIMIT","제안함은 계정당 하루 5건까지 등록할 수 있습니다.",429);
        if(await db.UserSuggestions.AnyAsync(x=>x.UserId==user.Id&&x.CreatedAt>now.AddSeconds(-60),token))throw Error("SUGGESTION_COOLDOWN","연속 등록은 1분 후 다시 시도해 주세요.",429);
        if(await db.UserSuggestions.AnyAsync(x=>x.UserId==user.Id&&x.ContentHash==hash&&x.CreatedAt>now.AddDays(-30),token))throw Error("SUGGESTION_DUPLICATE","같은 내용은 30일 안에 다시 등록할 수 없습니다.",409);
        var row=new UserSuggestion{UserId=user.Id,TypeCode=type,VisibilityCode="PRIVATE",StatusCode="RECEIVED",Title=title,Body=body,PageUrl=Limit(input.PageUrl,1000),DeviceInfo=Limit(input.DeviceInfo,1000),AppVersion=Limit(input.AppVersion,100),ContentHash=hash,IdempotencyKey=key,CreatedAt=now,CreatedByUserId=user.Id,UpdatedAt=now,UpdatedByUserId=user.Id};db.UserSuggestions.Add(row);await db.SaveChangesAsync(token);db.UserSuggestionEvents.Add(new UserSuggestionEvent{UserSuggestionId=row.Id,ActorUserId=user.Id,ActionCode="CREATED",ToStatusCode="RECEIVED",OccurredAt=now,CreatedAt=now});await db.SaveChangesAsync(token);if(transaction is not null)await transaction.CommitAsync(token);return await Detail(p,row.PublicId,token);
    }
    public async Task<IReadOnlyList<SuggestionResponse>> AdminList(ClaimsPrincipal p,string? status,CancellationToken token){var admin=await User(p,token);if(!admin.IsAdmin)throw Error("ADMIN_REQUIRED","관리자 권한이 필요합니다.",403);var q=Query();if(!string.IsNullOrWhiteSpace(status))q=q.Where(x=>x.StatusCode==status.ToUpper());var rows=await q.OrderByDescending(x=>x.CreatedAt).Take(500).ToListAsync(token);return rows.Select(Map).ToList();}
    public async Task<SuggestionResponse> AdminUpdate(ClaimsPrincipal p,Guid id,UpdateSuggestionInput input,CancellationToken token){var admin=await User(p,token);if(!admin.IsAdmin)throw Error("ADMIN_REQUIRED","관리자 권한이 필요합니다.",403);var row=await db.UserSuggestions.SingleOrDefaultAsync(x=>x.PublicId==id,token)??throw Error("SUGGESTION_NOT_FOUND","제안을 찾을 수 없습니다.",404);var status=input.StatusCode.Trim().ToUpperInvariant();if(!Statuses.Contains(status))throw Error("SUGGESTION_STATUS_INVALID","처리 상태를 확인해 주세요.");long? assignee=null;if(input.AssignedAdminId.HasValue)assignee=await db.Users.Where(x=>x.PublicId==input.AssignedAdminId&&x.StatusCode=="ACTIVE").Select(x=>(long?)x.Id).SingleOrDefaultAsync(token)??throw Error("SUGGESTION_ASSIGNEE_INVALID","담당 관리자를 찾을 수 없습니다.");var before=row.StatusCode;var beforeReply=row.AdminReply;var now=DateTime.UtcNow;row.StatusCode=status;row.AssignedAdminUserId=assignee;row.AdminReply=Limit(input.AdminReply,5000);row.ReleaseVersion=Limit(input.ReleaseVersion,100);row.UpdatedAt=now;row.UpdatedByUserId=admin.Id;db.UserSuggestionEvents.Add(new UserSuggestionEvent{UserSuggestionId=row.Id,ActorUserId=admin.Id,ActionCode="ADMIN_UPDATED",FromStatusCode=before,ToStatusCode=status,Note=Limit(input.Note,2000),OccurredAt=now,CreatedAt=now});if(!string.IsNullOrWhiteSpace(row.AdminReply)&&!string.Equals(beforeReply,row.AdminReply,StringComparison.Ordinal)){var notification=new Notification{RecipientUserId=row.UserId,TypeCode="SUGGESTION_ADMIN_REPLIED",PriorityCode="NORMAL",SourceTypeCode="USER_SUGGESTION",SourcePublicId=row.PublicId,TargetTypeCode="SUGGESTION",TargetPublicId=row.PublicId,StatusCode="RECORDED",Title="제안에 본사 답변이 등록되었습니다.",Body=$"{row.Title} 제안의 답변을 내 제안에서 확인해 주세요.",DataJson=JsonSerializer.Serialize(new{route="/suggestions",suggestionId=row.PublicId}),RecordedAt=now,IdempotencyKey=$"suggestion-reply:{row.PublicId:N}:{now.Ticks}",CreatedByUserId=admin.Id};db.Notifications.Add(notification);await db.SaveChangesAsync(token);var recipient=new NotificationRecipient{NotificationId=notification.Id,UserId=row.UserId,RecipientRoleCode=SuggestionRole(row.PageUrl),CreatedAt=now};db.NotificationRecipients.Add(recipient);await db.SaveChangesAsync(token);db.NotificationDeliveries.Add(new NotificationDelivery{NotificationId=notification.Id,NotificationRecipientId=recipient.Id,ChannelCode="WEB",AttemptNo=1,StatusCode="DELIVERED",AttemptedAt=now,CompletedAt=now,DeliveredAt=now,RetryCount=0,CreatedAt=now,UpdatedAt=now});}await db.SaveChangesAsync(token);return await Detail(p,id,token);}
    private IQueryable<UserSuggestion> Query()=>db.UserSuggestions.AsNoTracking();private static SuggestionResponse Map(UserSuggestion x)=>new(x.PublicId,x.TypeCode,x.StatusCode,x.Title,x.Body,x.PageUrl,x.DeviceInfo,x.AppVersion,x.AdminReply,x.ReleaseVersion,x.CreatedAt,x.UpdatedAt,Convert.ToBase64String(x.RowVersion));
    private async Task<(long Id,bool IsAdmin)> User(ClaimsPrincipal p,CancellationToken token){if(!Guid.TryParse(p.FindFirstValue(ClaimTypes.NameIdentifier),out var id))throw Error("AUTH_REQUIRED","로그인이 필요합니다.",401);var user=await db.Users.AsNoTracking().SingleOrDefaultAsync(x=>x.PublicId==id&&x.StatusCode=="ACTIVE",token)??throw Error("AUTH_REQUIRED","로그인이 필요합니다.",401);return(user.Id,p.IsInRole("ADMIN"));}
    private static string SuggestionRole(string? pageUrl)=>Uri.TryCreate(pageUrl,UriKind.Absolute,out var uri)&&uri.Host.StartsWith("partner.",StringComparison.OrdinalIgnoreCase)?RoleCodes.Provider:RoleCodes.Customer;
    private static string Required(string? value,int min,int max){var clean=value?.Trim();if(string.IsNullOrWhiteSpace(clean)||clean.Length<min||clean.Length>max)throw Error("SUGGESTION_INPUT_INVALID",$"입력값은 {min}~{max}자로 작성해 주세요.");return clean;}private static string Normalize(string value)=>string.Join(' ',value.Trim().ToLowerInvariant().Split((char[]?)null,StringSplitOptions.RemoveEmptyEntries));private static string? Limit(string? value,int max){var clean=value?.Trim();if(string.IsNullOrWhiteSpace(clean))return null;if(clean.Length>max)throw Error("SUGGESTION_INPUT_TOO_LONG","입력값이 너무 깁니다.");return clean;}private static WorkBusinessException Error(string code,string message,int status=400)=>new(code,message,status);
}
public sealed record CreateSuggestionInput(string TypeCode,string Title,string Body,string? PageUrl,string? DeviceInfo,string? AppVersion,string IdempotencyKey);
public sealed record UpdateSuggestionInput(string StatusCode,Guid? AssignedAdminId,string? AdminReply,string? ReleaseVersion,string? Note,string? RowVersion);
public sealed record SuggestionResponse(Guid Id,string TypeCode,string StatusCode,string Title,string Body,string? PageUrl,string? DeviceInfo,string? AppVersion,string? AdminReply,string? ReleaseVersion,DateTime CreatedAt,DateTime UpdatedAt,string RowVersion);
