import {useEffect,useState,type FormEvent} from 'react'
import {navigate} from '../auth/routing'
import {CustomerAppLayout} from '../customer/CustomerAppLayout'
import * as api from '../work/api'
import type {CustomerAfterService,CustomerReport,CustomerReportType,ServiceHistoryDetail,ServiceHistoryItem,WorkTransactionListItem} from '../work/types'
import './customerAftercare.css'

const date=(value:string|null|undefined)=>value?new Intl.DateTimeFormat('ko-KR',{dateStyle:'medium'}).format(new Date(value)):'확인 필요'
const dateTime=(value:string|null|undefined)=>value?new Intl.DateTimeFormat('ko-KR',{dateStyle:'medium',timeStyle:'short'}).format(new Date(value)):'-'
const money=(value:number|null,currency='KRW')=>value===null?'확인 필요':new Intl.NumberFormat('ko-KR',{style:'currency',currency:currency||'KRW',maximumFractionDigits:0}).format(value)
const errorMessage=(reason:unknown)=>reason instanceof Error?reason.message:'요청을 처리하지 못했습니다.'

function Heading({title,description}:{title:string;description:string}){return <section className="aftercareHeading"><p>MY SOODAL</p><h1>{title}</h1><span>{description}</span></section>}
function Empty({children}:{children:string}){return <p className="aftercareEmpty">{children}</p>}

export function ServiceHistoryPage({id}:{id?:string}){
 const[items,setItems]=useState<ServiceHistoryItem[]>([]),[detail,setDetail]=useState<ServiceHistoryDetail|null>(null),[error,setError]=useState('')
 useEffect(()=>{(id?api.getServiceHistoryDetail(id).then(setDetail):api.getServiceHistory().then(setItems)).catch(reason=>setError(errorMessage(reason)))},[id])
 return <CustomerAppLayout><Heading title="서비스 이력" description="완료된 서비스의 금액, 증빙, 보증과 사후처리를 한곳에서 확인하세요."/>{error&&<div className="aftercareError">{error}</div>}{detail?<HistoryDetail value={detail}/>:<section className="aftercareList">{items.map(item=><button key={item.id} onClick={()=>navigate(`/customer/service-history/${item.id}`)}><div className="aftercareCardTop"><span>{date(item.completedAt)}</span><b>{item.warrantyDisplay}</b></div><h2>{item.serviceName}</h2><p>{item.providerName}</p><strong>{money(item.finalAmount,item.currencyCode??'KRW')}</strong><div className="aftercareTags"><span className={item.hasReview?'done':''}>리뷰 {item.hasReview?'완료':'미작성'}</span><span className={item.hasAfterService?'active':''}>A/S {item.hasAfterService?'진행 이력':'없음'}</span><span className={item.hasDispute?'warn':''}>분쟁 {item.hasDispute?'있음':'없음'}</span></div></button>)}</section>}{!id&&!items.length&&!error&&<Empty>완료된 서비스 이력이 없습니다.</Empty>}</CustomerAppLayout>
}
function HistoryDetail({value}:{value:ServiceHistoryDetail}){return <><button className="aftercareBack" onClick={()=>navigate('/customer/service-history')}>← 서비스 이력</button><div className="aftercareDetailGrid"><main><section className="aftercarePanel aftercareHero"><span>{date(value.completedAt)} 완료</span><h2>{value.serviceName}</h2><p>{value.summary}</p><dl><div><dt>공급자</dt><dd>{value.providerName}</dd></div><div><dt>최종 작업금액</dt><dd>{money(value.finalAmount,value.currencyCode??'KRW')}</dd></div><div><dt>보증 안내</dt><dd>{value.warrantyDisplay}</dd></div></dl></section><section className="aftercarePanel"><h2>작업 항목</h2>{value.items.map(item=><div className="aftercareLine" key={item.lineNo}><div><strong>{item.itemName}</strong><small>{item.description}</small></div><span>{money(item.amount,item.currencyCode??'KRW')}</span></div>)}</section><section className="aftercarePanel"><h2>완료 증빙</h2>{value.completionEvidence.map(file=><a className="aftercareFile" href={file.downloadUrl} key={file.fileId}><span>{file.role}</span><strong>{file.fileName}</strong></a>)}{!value.completionEvidence.length&&<p>등록된 완료 증빙이 없습니다.</p>}</section></main><aside><section className="aftercarePanel"><h2>후속 지원</h2>{value.afterService?<button onClick={()=>navigate(`/customer/after-services/${value.afterService?.id}`)}>A/S {value.afterService.displayStatus}</button>:<button className="primary" onClick={()=>navigate(`/customer/after-services/new?transaction=${value.transactionId}`)}>A/S 신청</button>}{value.dispute&&<button onClick={()=>navigate(`/customer/disputes/${value.dispute?.id}`)}>분쟁 {value.dispute.displayStatus}</button>}<p className="aftercareNotice">보증기간이 지나도 A/S 신청은 가능합니다. 비용 발생 여부는 접수 후 확인합니다.</p></section>{value.assets.length>0&&<section className="aftercarePanel"><h2>연결된 시설·제품</h2>{value.assets.map(asset=><div key={asset.id}><strong>{asset.name}</strong><p>{[asset.manufacturer,asset.modelName].filter(Boolean).join(' · ')}</p></div>)}</section>}</aside></div></>}

export function AfterServicesPage({id,mode}:{id?:string;mode?:'new'}){
 const[items,setItems]=useState<CustomerAfterService[]>([]),[detail,setDetail]=useState<CustomerAfterService|null>(null),[error,setError]=useState('')
 useEffect(()=>{if(mode)return;(id?api.getAfterService(id).then(setDetail):api.getAfterServices().then(setItems)).catch(reason=>setError(errorMessage(reason)))},[id,mode])
 return <CustomerAppLayout><Heading title={mode?'A/S 신청':'A/S 관리'} description="접수부터 일정, 조치 결과와 분쟁 전환까지 진행상태를 확인할 수 있습니다."/>{error&&<div className="aftercareError">{error}</div>}{mode?<AfterServiceForm/>:detail?<AfterServiceDetail value={detail} reload={()=>api.getAfterService(detail.id).then(setDetail)} />:<section className="aftercareList">{items.map(item=><button key={item.id} onClick={()=>navigate(`/customer/after-services/${item.id}`)}><div className="aftercareCardTop"><span>{date(item.receivedAt)}</span><b>{item.displayStatus}</b></div><h2>{item.subject}</h2><p>{item.description}</p><small>{item.warrantyDisplay}</small></button>)}</section>}{!mode&&!id&&!items.length&&!error&&<Empty>접수된 A/S가 없습니다. 완료 서비스 이력에서 신청할 수 있습니다.</Empty>}</CustomerAppLayout>
}
function AfterServiceForm(){const transactionId=new URLSearchParams(window.location.search).get('transaction')??'';const[form,setForm]=useState({subject:'',description:'',requestDetails:'',desiredVisitAt:''}),[error,setError]=useState(''),[busy,setBusy]=useState(false);const submit=async(event:FormEvent)=>{event.preventDefault();if(!transactionId)return setError('완료된 거래에서 A/S를 신청해 주세요.');setBusy(true);try{const item=await api.createAfterService(transactionId,{subject:form.subject,description:form.description,requestDetails:form.requestDetails||null,desiredVisitAt:form.desiredVisitAt?new Date(form.desiredVisitAt).toISOString():null});navigate(`/customer/after-services/${item.id}`)}catch(reason){setError(errorMessage(reason));setBusy(false)}};return <form className="aftercareForm" onSubmit={event=>void submit(event)}><label>제목<input required maxLength={200} value={form.subject} onChange={event=>setForm({...form,subject:event.target.value})} placeholder="예: 수리 후 동일 증상이 다시 발생했어요"/></label><label>증상·문제 내용<textarea required maxLength={4000} value={form.description} onChange={event=>setForm({...form,description:event.target.value})}/></label><label>고객 요청사항<textarea maxLength={2000} value={form.requestDetails} onChange={event=>setForm({...form,requestDetails:event.target.value})} placeholder="확인이나 재방문이 필요한 내용을 적어 주세요."/></label><label>희망 방문일시 <small>(선택)</small><input type="datetime-local" value={form.desiredVisitAt} onChange={event=>setForm({...form,desiredVisitAt:event.target.value})}/></label><p className="aftercareNotice">희망일시는 확정 일정이 아닙니다. 공급자 확인 후 조율됩니다.</p>{error&&<div className="aftercareError">{error}</div>}<button className="primary" disabled={busy}>{busy?'접수 중':'A/S 접수'}</button></form>}
function AfterServiceDetail({value,reload}:{value:CustomerAfterService;reload:()=>Promise<unknown>}){const[file,setFile]=useState<File|null>(null),[description,setDescription]=useState(''),[error,setError]=useState('');const upload=async()=>{if(!file)return;try{await api.uploadAfterServiceEvidence(value.id,file,description);setFile(null);setDescription('');await reload()}catch(reason){setError(errorMessage(reason))}};return <><button className="aftercareBack" onClick={()=>navigate('/customer/after-services')}>← A/S 목록</button><div className="aftercareDetailGrid"><main><section className="aftercarePanel aftercareHero"><div className="aftercareCardTop"><span>{dateTime(value.receivedAt)}</span><b>{value.displayStatus}</b></div><h2>{value.subject}</h2><p>{value.description}</p><strong>{value.warrantyDisplay}</strong>{value.providerResponse&&<div className="aftercarePublicResult"><b>공급자 안내</b><p>{value.providerResponse}</p></div>}</section><section className="aftercarePanel"><h2>진행 타임라인</h2><ol className="aftercareTimeline">{value.timeline.map((item,index)=><li key={`${item.occurredAt}-${index}`}><b>{item.displayStatus}</b><span>{dateTime(item.occurredAt)}</span>{item.scheduledAt&&<p>예정: {dateTime(item.scheduledAt)}</p>}{item.publicNote&&<p>{item.publicNote}</p>}</li>)}</ol></section><section className="aftercarePanel"><h2>처리 결과</h2><p>{value.resolutionSummary??value.unresolvedReason??'아직 처리 중입니다.'}</p>{value.recurrenceOccurred!==null&&<p>재발 기록: {value.recurrenceOccurred?'있음':'없음'}</p>}</section></main><aside><section className="aftercarePanel"><h2>증빙</h2>{value.evidence.map(item=><a className="aftercareFile" href={item.downloadUrl} key={item.fileId}>{item.description??item.fileName}</a>)}<label className="aftercareUpload">사진·PDF 추가<input type="file" accept="image/jpeg,image/png,application/pdf" onChange={event=>setFile(event.target.files?.[0]??null)}/></label><input value={description} onChange={event=>setDescription(event.target.value)} placeholder="증빙 설명"/><button disabled={!file} onClick={()=>void upload()}>증빙 추가</button></section>{value.disputeId?<section className="aftercarePanel"><h2>분쟁 전환됨</h2><button onClick={()=>navigate(`/customer/disputes/${value.disputeId}`)}>분쟁 진행상태 확인</button></section>:<section className="aftercarePanel"><h2>해결되지 않았나요?</h2><p>분쟁 접수는 공급자 귀책 확정이나 자동 제재를 의미하지 않습니다.</p><button className="danger" onClick={()=>navigate(`/customer/after-services/${value.id}/dispute`)}>분쟁으로 전환</button></section>}<section className="aftercarePanel"><h2>신고가 필요한가요?</h2><button onClick={()=>navigate(`/customer/reports/new?targetType=AFTER_SERVICE&targetId=${value.id}`)}>이 A/S 신고</button></section>{error&&<div className="aftercareError">{error}</div>}</aside></div></>}

export function AfterServiceDisputeFormPage({id}:{id:string}){const[form,setForm]=useState({subject:'A/S 미해결 분쟁',reason:'',requestedResolution:''}),[error,setError]=useState(''),[busy,setBusy]=useState(false);const submit=async(event:FormEvent)=>{event.preventDefault();setBusy(true);try{const dispute=await api.convertAfterServiceToDispute(id,form);navigate(`/customer/disputes/${dispute.id}`)}catch(reason){setError(errorMessage(reason));setBusy(false)}};return <CustomerAppLayout><Heading title="A/S 분쟁 전환" description="A/S가 해결되지 않은 경우 기존 사건과 연결된 분쟁을 접수합니다."/><form className="aftercareForm" onSubmit={event=>void submit(event)}><label>제목<input required value={form.subject} onChange={event=>setForm({...form,subject:event.target.value})}/></label><label>분쟁 사유<textarea required value={form.reason} onChange={event=>setForm({...form,reason:event.target.value})}/></label><label>요청사항<textarea required value={form.requestedResolution} onChange={event=>setForm({...form,requestedResolution:event.target.value})}/></label><p className="aftercareNotice">접수만으로 공급자 귀책, 제재 또는 신뢰점수 변경이 발생하지 않습니다.</p>{error&&<div className="aftercareError">{error}</div>}<button className="danger" disabled={busy}>{busy?'접수 중':'분쟁 접수'}</button></form></CustomerAppLayout>}

export function CustomerReportsPage({id,mode}:{id?:string;mode?:'new'}){const[items,setItems]=useState<CustomerReport[]>([]),[detail,setDetail]=useState<CustomerReport|null>(null),[error,setError]=useState('');useEffect(()=>{if(mode)return;(id?api.getReport(id).then(setDetail):api.getReports().then(setItems)).catch(reason=>setError(errorMessage(reason)))},[id,mode]);return <CustomerAppLayout><Heading title={mode?'신고 접수':'신고 내역'} description="신고와 제재는 별도 절차입니다. 검토 상태와 공개 가능한 결과만 안내합니다."/>{error&&<div className="aftercareError">{error}</div>}{mode?<ReportForm/>:detail?<ReportDetail value={detail} reload={()=>api.getReport(detail.id).then(setDetail)}/>:<><button className="aftercareNew" onClick={()=>navigate('/customer/reports/new')}>신고 접수</button><section className="aftercareList">{items.map(item=><button key={item.id} onClick={()=>navigate(`/customer/reports/${item.id}`)}><div className="aftercareCardTop"><span>{item.reportNumber}</span><b>{item.displayStatus}</b></div><h2>{item.reportTypeName}</h2><p>{item.targetDisplay} · {date(item.receivedAt)}</p></button>)}</section></>}{!mode&&!id&&!items.length&&!error&&<Empty>접수된 신고가 없습니다.</Empty>}</CustomerAppLayout>}
function ReportForm(){const query=new URLSearchParams(window.location.search),fixedTargetId=query.get('targetId')??'';const[types,setTypes]=useState<CustomerReportType[]>([]),[targets,setTargets]=useState<WorkTransactionListItem[]>([]),[form,setForm]=useState({targetType:query.get('targetType')??'TRANSACTION',targetId:fixedTargetId,reportTypeId:'',description:''}),[error,setError]=useState(''),[busy,setBusy]=useState(false);useEffect(()=>{api.getReportTypes().then(value=>{setTypes(value);if(value[0])setForm(current=>({...current,reportTypeId:current.reportTypeId||value[0].id}))}).catch(reason=>setError(errorMessage(reason)));if(!fixedTargetId)api.getCustomerTransactions().then(value=>{setTargets(value);if(value[0])setForm(current=>({...current,targetType:'TRANSACTION',targetId:value[0].id}))}).catch(reason=>setError(errorMessage(reason)))},[fixedTargetId]);const submit=async(event:FormEvent)=>{event.preventDefault();setBusy(true);try{const report=await api.createReport(form);navigate(`/customer/reports/${report.id}`)}catch(reason){setError(errorMessage(reason));setBusy(false)}};return <form className="aftercareForm" onSubmit={event=>void submit(event)}>{fixedTargetId?<p className="aftercareNotice">현재 보고 있던 {form.targetType==='AFTER_SERVICE'?'A/S':form.targetType==='DISPUTE'?'분쟁':'거래'} 건을 신고 대상으로 연결합니다.</p>:<label>신고 대상 거래<select required value={form.targetId} onChange={event=>setForm({...form,targetId:event.target.value})}><option value="">거래를 선택해 주세요</option>{targets.map(target=><option value={target.id} key={target.id}>{target.requestSummary} · {target.categoryPath}</option>)}</select></label>}<label>신고 유형<select required value={form.reportTypeId} onChange={event=>setForm({...form,reportTypeId:event.target.value})}>{types.map(type=><option value={type.id} key={type.id}>{type.name}</option>)}</select></label><label>신고 내용<textarea required maxLength={4000} value={form.description} onChange={event=>setForm({...form,description:event.target.value})}/></label>{!types.length&&<p className="aftercareNotice">활성화된 신고 유형이 없어 접수할 수 없습니다. 고객센터에 문의해 주세요.</p>}{!fixedTargetId&&!targets.length&&<p className="aftercareNotice">신고할 거래가 없습니다. 관련 A/S나 분쟁 상세에서도 신고할 수 있습니다.</p>}<p className="aftercareNotice">신고 접수만으로 상대방 정지, 제재, 신뢰점수 또는 Wallet 변경이 발생하지 않습니다.</p>{error&&<div className="aftercareError">{error}</div>}<button className="danger" disabled={busy||!types.length||!form.targetId}>{busy?'접수 중':'신고 접수'}</button></form>}
function ReportDetail({value,reload}:{value:CustomerReport;reload:()=>Promise<unknown>}){const[file,setFile]=useState<File|null>(null),[description,setDescription]=useState(''),[error,setError]=useState('');const upload=async()=>{if(!file)return;try{await api.uploadReportEvidence(value.id,file,description);setFile(null);setDescription('');await reload()}catch(reason){setError(errorMessage(reason))}};return <><button className="aftercareBack" onClick={()=>navigate('/customer/reports')}>← 신고 목록</button><div className="aftercareDetailGrid"><main><section className="aftercarePanel aftercareHero"><div className="aftercareCardTop"><span>{value.reportNumber}</span><b>{value.displayStatus}</b></div><h2>{value.reportTypeName}</h2><p>{value.description}</p><dl><div><dt>대상</dt><dd>{value.targetDisplay}</dd></div><div><dt>접수일</dt><dd>{dateTime(value.receivedAt)}</dd></div></dl></section><section className="aftercarePanel"><h2>처리 결과</h2><p>{value.publicResult??'검토가 완료되면 공개 가능한 범위에서 결과를 안내합니다.'}</p></section></main><aside><section className="aftercarePanel"><h2>증빙</h2>{value.evidence.map(item=><a className="aftercareFile" href={item.downloadUrl} key={item.fileId}>{item.description??item.fileName}</a>)}<label className="aftercareUpload">사진·PDF 추가<input type="file" accept="image/jpeg,image/png,application/pdf" onChange={event=>setFile(event.target.files?.[0]??null)}/></label><input value={description} onChange={event=>setDescription(event.target.value)} placeholder="증빙 설명"/><button disabled={!file} onClick={()=>void upload()}>증빙 추가</button>{error&&<div className="aftercareError">{error}</div>}</section></aside></div></>}
