import {useEffect,useState} from 'react'
import {navigate} from '../auth/routing'
import {CustomerAppLayout} from '../customer/CustomerAppLayout'
import * as api from '../work/api'
import type {CustomerDispute} from '../work/types'
import {CustomerReviewConversationPage} from '../reviews/ReviewConversationPages'
import './workFlow.css'
import './customerAftercare.css'

export function MyReviewsPage(){return <CustomerReviewConversationPage/>}

export function CustomerDisputesPage({id}:{id?:string}){const[list,setList]=useState<CustomerDispute[]>([]),[detail,setDetail]=useState<CustomerDispute|null>(null),[error,setError]=useState('');const load=()=>id?api.getDispute(id).then(setDetail):api.getDisputes().then(setList);useEffect(()=>{(id?api.getDispute(id).then(setDetail):api.getDisputes().then(setList)).catch((e:Error)=>setError(e.message))},[id]);return <CustomerAppLayout><section className="workHeading soodalHeroHeading"><p>나의 수달</p><h1>분쟁 진행상태</h1><span>분쟁 접수와 귀책 판단은 별개이며, 공개 가능한 처리 단계와 최종 결과만 안내합니다.</span></section>{error&&<div className="errorBanner">{error}</div>}{detail?<DisputeDetail value={detail} reload={load}/>:<section className="workList">{list.map(x=><button onClick={()=>navigate(`/customer/disputes/${x.id}`)} key={x.id}><span className="workStatus">{x.displayStatus}</span><h2>{x.subject}</h2><p>{x.reason}</p><small>{date(x.receivedAt)}</small></button>)}</section>}{!id&&!list.length&&!error&&<p className="workEmpty">접수된 분쟁이 없습니다.</p>}</CustomerAppLayout>}

function DisputeDetail({value,reload}:{value:CustomerDispute;reload:()=>Promise<unknown>}){const[file,setFile]=useState<File|null>(null),[description,setDescription]=useState(''),[error,setError]=useState('');const upload=async()=>{if(!file)return;try{await api.uploadDisputeEvidence(value.id,file,description);setFile(null);setDescription('');await reload()}catch(reason){setError(reason instanceof Error?reason.message:'증빙을 추가하지 못했습니다.')}};return <><button className="workBack" onClick={()=>navigate('/customer/disputes')}>← 분쟁 목록</button><div className="aftercareDetailGrid"><main><section className="workPanel"><span className="workStatus">{value.displayStatus}</span><h2>{value.subject}</h2><h3>접수 사유</h3><p>{value.reason}</p><h3>요청사항</h3><p>{value.requestedResolution||'별도 요청사항 없음'}</p><h3>처리 결과</h3><p>{value.resultSummary??'운영 검토 중입니다.'}</p>{value.followUpAction&&<p>{value.followUpAction}</p>}</section><section className="aftercarePanel"><h2>처리 단계</h2><ol className="aftercareTimeline">{value.publicUpdates.map((item,index)=><li key={`${item.occurredAt}-${index}`}><b>{item.displayStatus}</b><span>{date(item.occurredAt)}</span></li>)}</ol><p className="aftercareNotice">분쟁 접수만으로 전문가 귀책이나 제재가 확정되지 않습니다.</p></section></main><aside><section className="workPanel"><h2>증빙</h2>{value.evidence.map(x=><p key={x.id}>{x.downloadUrl?<a href={x.downloadUrl}>{x.description??'첨부 파일 보기'}</a>:x.publicationMessage??x.description??'안전 확인 전에는 공개되지 않습니다.'}</p>)}<label className="aftercareUpload">사진·PDF 추가<input type="file" accept="image/jpeg,image/png,application/pdf" onChange={event=>setFile(event.target.files?.[0]??null)}/></label><input value={description} onChange={event=>setDescription(event.target.value)} placeholder="증빙 설명"/><button disabled={!file} onClick={()=>void upload()}>증빙 추가</button>{error&&<p className="aftercareError">{error}</p>}</section><section className="aftercarePanel"><h2>신고가 필요한가요?</h2><button onClick={()=>navigate(`/customer/reports/new?targetType=DISPUTE&targetId=${value.id}`)}>이 분쟁 신고</button></section></aside></div></>}
const date=(value:string)=>new Intl.DateTimeFormat('ko-KR',{dateStyle:'medium',timeStyle:'short'}).format(new Date(value))
