import { useCallback, useEffect, useRef, useState } from 'react'
import { navigate } from '../auth/routing'
import { CustomerAppLayout } from '../customer/CustomerAppLayout'
import { customerAccountApi } from '../customer/accountApi'
import { publicCatalogApi } from '../customer/api'
import type { CustomerAddress } from '../customer/accountTypes'
import * as requestApi from '../requests/api'
import { DynamicFieldInput } from '../requests/DynamicFieldInput'
import type { DynamicValue } from '../requests/DynamicFieldInput'
import type { AdministrativeArea, Category, RequestField, RequestFile, ServiceRequestDetail, ServiceRequestListItem } from '../requests/types'
import { CustomerQuotesPanel } from '../quotes/QuotePanels'
import './customerRequestFlow.css'

const steps = ['서비스', '요청 정보', '주소', '일정', '사진·파일', '확인', '공개']

export function NewCustomerRequestPage() {
  const [step, setStep] = useState(0), [draftId, setDraftId] = useState<string | null>(null)
  const [majors, setMajors] = useState<Category[]>([]), [middles, setMiddles] = useState<Category[]>([]), [services, setServices] = useState<Category[]>([])
  const [areas, setAreas] = useState<AdministrativeArea[]>([]), [savedAddresses, setSavedAddresses] = useState<CustomerAddress[]>([]), [fields, setFields] = useState<RequestField[]>([])
  const [majorId, setMajorId] = useState(''), [middleId, setMiddleId] = useState(''), [serviceId, setServiceId] = useState(''), [areaId, setAreaId] = useState('')
  const [title, setTitle] = useState(''), [description, setDescription] = useState(''), [detailAddress, setDetailAddress] = useState('')
  const [isUrgent, setIsUrgent] = useState(false), [answers, setAnswers] = useState<Record<string, DynamicValue>>({}), [files, setFiles] = useState<RequestFile[]>([])
  const [error, setError] = useState(''), [notice, setNotice] = useState(''), [busy, setBusy] = useState(false)
  const idempotencyKey = useRef(crypto.randomUUID())

  useEffect(() => { const selectedId = new URLSearchParams(window.location.search).get('service'); Promise.all([requestApi.getMajorCategories(), requestApi.getAdministrativeAreas(), customerAccountApi.addresses(), selectedId ? publicCatalogApi.detail(selectedId) : Promise.resolve(null)]).then(async ([a, b, c, selected]) => { setMajors(a); setAreas(b); setSavedAddresses(c); if (selected) { setMajorId(selected.majorId); setMiddleId(selected.middleId); setServiceId(selected.id); const [middleItems, serviceItems, fieldItems] = await Promise.all([requestApi.getMiddleCategories(selected.majorId), requestApi.getServiceCategories(selected.middleId), requestApi.getRequestFields(selected.id)]); setMiddles(middleItems); setServices(serviceItems); setFields(fieldItems) } }).catch((reason: Error) => setError(reason.message)) }, [])
  useEffect(() => { const resumeId = new URLSearchParams(window.location.search).get('draft'); if (!resumeId) return; requestApi.getMyRequest(resumeId).then(async draft => { if (!draft.canEdit) throw new Error('수정할 수 없는 요청입니다.'); const [middleItems, serviceItems, fieldItems] = await Promise.all([requestApi.getMiddleCategories(draft.majorCategoryId), requestApi.getServiceCategories(draft.middleCategoryId), requestApi.getRequestFields(draft.serviceCategoryId)]); setDraftId(draft.id); setMajorId(draft.majorCategoryId); setMiddleId(draft.middleCategoryId); setServiceId(draft.serviceCategoryId); setMiddles(middleItems); setServices(serviceItems); setFields(fieldItems); setAreaId(draft.administrativeAreaId ?? ''); setTitle(draft.title === '작성 중인 요청' ? '' : draft.title); setDescription(draft.description ?? ''); setDetailAddress(draft.detailAddress ?? ''); setIsUrgent(draft.isUrgent); setAnswers(Object.fromEntries(draft.answers.map(answer => [answer.fieldId, answer.value as DynamicValue]))); setFiles(draft.files); setNotice('임시저장한 요청을 이어서 작성합니다.') }).catch((reason: Error) => setError(reason.message)) }, [])
  const chooseMajor = async (id: string) => { setMajorId(id); setMiddleId(''); setServiceId(''); setMiddles(id ? await requestApi.getMiddleCategories(id) : []); setServices([]); setFields([]) }
  const chooseMiddle = async (id: string) => { setMiddleId(id); setServiceId(''); setServices(id ? await requestApi.getServiceCategories(id) : []); setFields([]) }
  const chooseService = async (id: string) => { setServiceId(id); setFields(id ? await requestApi.getRequestFields(id) : []); setAnswers({}) }
  const valueAnswers = () => fields.filter(field => field.inputType !== 'FILE' && answers[field.id] !== undefined && answers[field.id] !== '').map(field => ({ fieldId: field.id, value: field.inputType === 'NUMBER' || field.inputType === 'MONEY' ? Number(answers[field.id]) : field.inputType === 'DATETIME' ? new Date(String(answers[field.id])).toISOString() : answers[field.id] }))
  const draftPayload = () => ({ administrativeAreaId: areaId || null, title: title.trim() || null, description: description.trim() || null, detailAddress: detailAddress.trim() || null, isUrgent, answers: valueAnswers() })
  const saveDraft = async () => { if (!serviceId) throw new Error('서비스를 먼저 선택해 주세요.'); const id = draftId ?? (await requestApi.createServiceRequest({ categoryId: serviceId, idempotencyKey: idempotencyKey.current, ...draftPayload() })).id; if (!draftId) setDraftId(id); await requestApi.updateServiceRequest(id, draftPayload()); setNotice('현재 단계까지 안전하게 임시저장했습니다.'); return id }
  const next = async () => { setBusy(true); setError(''); setNotice(''); try { await saveDraft(); setStep(value => Math.min(value + 1, steps.length - 1)) } catch (reason) { setError(reason instanceof Error ? reason.message : '임시저장하지 못했습니다.') } finally { setBusy(false) } }
  const upload = async (selected: FileList | null, requestFieldId?: string) => { if (!selected) return; setBusy(true); setError(''); try { const id = await saveDraft(); for (const file of Array.from(selected)) { const uploaded = await requestApi.uploadRequestFile(id, file, requestFieldId); setFiles(current => [...current, uploaded]) } setNotice('파일을 비공개 저장소에 업로드했습니다. 악성코드 검사는 아직 연동되지 않았습니다.') } catch (reason) { setError(reason instanceof Error ? reason.message : '파일을 업로드하지 못했습니다.') } finally { setBusy(false) } }
  const removeFile = async (file: RequestFile) => { if (!draftId) return; await requestApi.deleteRequestFile(draftId, file.id); setFiles(current => current.filter(item => item.id !== file.id)) }
  const publish = async () => { if (!draftId) return; setBusy(true); setError(''); try { await saveDraft(); const result = await requestApi.publishServiceRequest(draftId); setNotice(result.customerMessage); setTimeout(() => navigate(`/customer/requests/${draftId}`, true), 500) } catch (reason) { setError(reason instanceof Error ? reason.message : '요청을 공개하지 못했습니다.') } finally { setBusy(false) } }
  const scheduleFields = fields.filter(field => ['DATETIME', 'PERIOD', 'RECURRENCE'].includes(field.inputType))
  const detailFields = fields.filter(field => !['DATETIME', 'PERIOD', 'RECURRENCE', 'FILE'].includes(field.inputType))
  const fileFields = fields.filter(field => field.inputType === 'FILE')
  const selectedService = services.find(item => item.id === serviceId)?.name

  return <CustomerAppLayout><div className="requestJourney"><header className="journeyHeader"><p className="eyebrow">SERVICE REQUEST</p><h1>서비스 요청하기</h1><p>필요한 내용만 단계별로 묻고, 매 단계 서버에 임시저장합니다.</p></header><ol className="journeySteps">{steps.map((label, index) => <li key={label} className={index === step ? 'active' : index < step ? 'done' : ''}><span>{index + 1}</span><small>{label}</small></li>)}</ol>
  {error && <div className="errorBanner" role="alert">{error}</div>}{notice && <div className="successBanner" role="status">{notice}</div>}
  <section className="journeyCard">
    {step === 0 && <><h2>어떤 서비스가 필요하세요?</h2><div className="formGrid threeColumns"><SelectField label="대분류" value={majorId} items={majors} onChange={chooseMajor}/><SelectField label="중분류" value={middleId} items={middles} onChange={chooseMiddle} disabled={!majorId}/><SelectField label="하위 서비스" value={serviceId} items={services} onChange={chooseService} disabled={!middleId}/></div></>}
    {step === 1 && <><h2>{selectedService} 요청을 알려주세요</h2><div className="formGrid"><div className="formField fullWidth"><label>요청 제목 *</label><input maxLength={200} value={title} onChange={event => setTitle(event.target.value)} placeholder="예: 거실 에어컨 청소가 필요해요"/></div>{detailFields.map(field => <DynamicFieldInput key={field.id} field={field} value={answers[field.id]} onChange={value => setAnswers(current => ({ ...current, [field.id]: value }))}/>) }<div className="formField fullWidth"><label>추가 설명</label><textarea rows={5} value={description} onChange={event => setDescription(event.target.value)}/></div><label className="booleanField fullWidth"><input type="checkbox" checked={isUrgent} onChange={event => setIsUrgent(event.target.checked)}/> 긴급 요청</label></div></>}
    {step === 2 && <><h2>서비스 받을 주소를 선택하세요</h2>{savedAddresses.length > 0 && <div className="savedAddressGrid">{savedAddresses.map(address => <button type="button" key={address.id} onClick={() => { setAreaId(address.administrativeAreaId ?? ''); setDetailAddress(`${address.roadAddress} ${address.detailAddress}`.trim()) }}><strong>{address.addressName}{address.isDefault && ' · 기본'}</strong><span>{address.roadAddress} {address.detailAddress}</span></button>)}</div>}<div className="formGrid"><div className="formField"><label>시·군·구 *</label><select value={areaId} onChange={event => setAreaId(event.target.value)}><option value="">선택하세요</option>{areas.map(area => <option key={area.id} value={area.id}>{area.parentName ? `${area.parentName} ` : ''}{area.name}</option>)}</select></div><div className="formField"><label>상세주소 *</label><input value={detailAddress} onChange={event => setDetailAddress(event.target.value)} autoComplete="street-address"/></div></div><p className="privacyNote">채택 전에는 공급자에게 전화번호와 상세주소를 공개하지 않습니다.</p></>}
    {step === 3 && <><h2>희망 일정을 알려주세요</h2>{scheduleFields.length ? <div className="formGrid">{scheduleFields.map(field => <DynamicFieldInput key={field.id} field={field} value={answers[field.id]} onChange={value => setAnswers(current => ({ ...current, [field.id]: value }))}/>)}</div> : <p className="emptyState">이 서비스에는 별도 일정 질문이 없습니다. 공급자와 견적 단계에서 조율할 수 있습니다.</p>}</>}
    {step === 4 && <><h2>현장 사진이나 참고 파일이 있나요?</h2><p>JPG, JPEG, PNG, PDF 파일을 각 10MB까지 올릴 수 있습니다. 웹 파일 선택은 향후 카메라·사진 네이티브 어댑터와 분리되어 있습니다.</p>{fileFields.map(field => <label className="fileDrop" key={field.id}><input type="file" required={field.required} accept=".jpg,.jpeg,.png,.pdf,image/jpeg,image/png,application/pdf" multiple onChange={event => void upload(event.target.files, field.id)}/><span>{field.label}{field.required ? ' *' : ''}</span></label>)}<label className="fileDrop"><input type="file" accept=".jpg,.jpeg,.png,.pdf,image/jpeg,image/png,application/pdf" multiple onChange={event => void upload(event.target.files)}/><span>추가 사진·PDF 선택</span></label><ul className="uploadedFiles">{files.map(file => <li key={file.id}><span>{file.fileName} · {(file.sizeBytes / 1024 / 1024).toFixed(1)}MB</span><button type="button" onClick={() => void removeFile(file)}>삭제</button></li>)}</ul></>}
    {step === 5 && <><h2>요청 내용을 확인하세요</h2><dl className="reviewList"><dt>서비스</dt><dd>{selectedService}</dd><dt>제목</dt><dd>{title || '미입력'}</dd><dt>지역</dt><dd>{areas.find(item => item.id === areaId)?.name ?? '미입력'}</dd><dt>상세주소</dt><dd>{detailAddress || '미입력'}</dd><dt>첨부파일</dt><dd>{files.length}개</dd></dl><p className="privacyNote">공개 후 조건이 맞는 승인 공급자에게만 요청이 전달됩니다. 상세주소와 연락처는 채택 전까지 보호됩니다.</p></>}
    {step === 6 && <><h2>공급자에게 요청을 공개할까요?</h2><p>공개하면 승인 상태, 서비스 분야, 활동지역, 필수 자격요건을 모두 충족한 공급자만 견적을 보낼 수 있습니다.</p><button className="primaryButton publishButton" type="button" disabled={busy} onClick={() => void publish()}>{busy ? '공개 중…' : '요청 공개하기'}</button></>}
  </section><div className="journeyActions"><button className="secondaryButton" type="button" disabled={busy} onClick={() => step === 0 ? navigate('/services') : setStep(value => value - 1)}>이전</button>{step < 6 && <button className="primaryButton" type="button" disabled={busy || (step === 0 && !serviceId)} onClick={() => void next()}>{busy ? '저장 중…' : '저장하고 다음'}</button>}</div></div></CustomerAppLayout>
}

export function CustomerRequestListPage() { const [items, setItems] = useState<ServiceRequestListItem[]>([]), [error, setError] = useState(''), [loading, setLoading] = useState(true); useEffect(() => { requestApi.getMyRequests().then(setItems).catch((reason: Error) => setError(reason.message)).finally(() => setLoading(false)) }, []); return <CustomerAppLayout><div className="requestJourney"><header className="journeyHeader"><p className="eyebrow">MY REQUESTS</p><h1>요청·견적</h1><button className="primaryButton inlineButton" onClick={() => navigate('/customer/requests/new')}>새 요청</button></header>{error && <div className="errorBanner">{error}</div>}{loading ? <p className="emptyState">불러오는 중…</p> : items.length === 0 ? <p className="emptyState">등록한 요청이 없습니다.</p> : <section className="requestList">{items.map(item => <button key={item.id} className="requestListItem" onClick={() => navigate(`/customer/requests/${item.id}`)}><div><span className="statusBadge">{item.displayStatus}</span><h2>{item.title}</h2><p>{item.categoryPath}</p></div><div className="requestMeta"><strong>견적 {item.quoteCount}건</strong><span>{formatDate(item.createdAt)}</span></div></button>)}</section>}</div></CustomerAppLayout> }

export function CustomerRequestDetailPage({ requestId }: { requestId: string }) { const [item, setItem] = useState<ServiceRequestDetail | null>(null), [error, setError] = useState(''); const load = useCallback(() => requestApi.getMyRequest(requestId).then(setItem).catch((reason: Error) => setError(reason.message)), [requestId]); useEffect(() => { void load() }, [load]); const cancel = async () => { if (!item || !window.confirm('이 요청을 취소할까요?')) return; await requestApi.cancelServiceRequest(item.id, '고객 요청 취소'); await load() }; return <CustomerAppLayout><div className="requestJourney">{error ? <div className="errorBanner">{error}</div> : !item ? <p className="emptyState">요청을 불러오는 중…</p> : <><header className="journeyHeader"><span className="statusBadge">{item.displayStatus}</span><h1>{item.title}</h1><p>{item.categoryPath} · 견적 {item.quoteCount}건</p></header><section className="detailCard"><dl><dt>등록일</dt><dd>{formatDate(item.createdAt)}</dd><dt>지역</dt><dd>{item.administrativeAreaName ?? '미입력'}</dd><dt>상세주소</dt><dd>{item.detailAddress || '미입력'}<small className="privateTag"> 채택 전 비공개</small></dd><dt>선택 공급자</dt><dd>{item.selectedProviderName ?? '아직 선택하지 않음'}</dd><dt>추가 설명</dt><dd>{item.description || '입력 없음'}</dd></dl></section>{item.answers.length > 0 && <section className="detailCard"><h2>요청 답변</h2><dl>{item.answers.map(answer => <div key={answer.fieldId} className="answerRow"><dt>{answer.label}</dt><dd>{formatAnswer(answer.value)}</dd></div>)}</dl></section>}{item.files.length > 0 && <section className="detailCard"><h2>첨부파일</h2><ul className="uploadedFiles">{item.files.map(file => <li key={file.id}><a href={file.downloadUrl}>{file.fileName}</a><span>{file.scanStatus}</span></li>)}</ul></section>}<CustomerQuotesPanel requestId={requestId}/><div className="formActions"><button className="secondaryButton" onClick={() => navigate('/customer/requests')}>목록</button>{item.canEdit && <button className="primaryButton" onClick={() => navigate(`/customer/requests/new?draft=${item.id}`)}>이어서 작성</button>}{item.canCancel && <button className="dangerButton" onClick={() => void cancel()}>요청 취소</button>}</div></>}</div></CustomerAppLayout> }

function SelectField({ label, value, items, onChange, disabled = false }: { label: string; value: string; items: Category[]; onChange: (id: string) => void; disabled?: boolean }) { return <div className="formField"><label>{label} *</label><select disabled={disabled} value={value} onChange={event => void onChange(event.target.value)}><option value="">선택하세요</option>{items.map(item => <option key={item.id} value={item.id}>{item.name}</option>)}</select></div> }
function formatDate(value: string) { return new Intl.DateTimeFormat('ko-KR', { dateStyle: 'medium', timeStyle: 'short' }).format(new Date(value)) }
function formatAnswer(value: unknown) { if (value === null || value === undefined || value === '') return '입력 없음'; if (Array.isArray(value)) return value.join(', '); if (typeof value === 'object') return JSON.stringify(value); if (typeof value === 'boolean') return value ? '예' : '아니오'; return String(value) }
