import {useEffect,useState} from 'react'
import {navigate} from '../auth/routing'
import {CustomerAppLayout} from '../customer/CustomerAppLayout'
import * as api from '../work/api'
import type {CustomerDispute,ReviewResponse} from '../work/types'
import './workFlow.css'

export function MyReviewsPage(){const[items,setItems]=useState<ReviewResponse[]>([]),[error,setError]=useState('');useEffect(()=>{api.getMyReviews().then(setItems).catch((e:Error)=>setError(e.message))},[]);return <CustomerAppLayout><section className="workHeading"><p>MY SOODAL</p><h1>내가 작성한 리뷰</h1><span>완료 거래에 남긴 항목별 평가와 후기를 확인합니다.</span></section>{error&&<div className="errorBanner">{error}</div>}<section className="workList">{items.map(x=><article className="workPanel" key={x.id}><span className="workStatus">{x.visibilityStatusCode==='PUBLIC'?'공개':'비공개'}</span><h2>{x.providerName}</h2><p>{x.bodyText}</p>{x.ratings.map(r=><div className="workLine" key={r.itemId}><span>{r.itemName}</span><strong>{r.ratingValue}</strong></div>)}<small>{date(x.submittedAt)}</small></article>)}</section>{!items.length&&!error&&<p className="workEmpty">작성한 리뷰가 없습니다.</p>}</CustomerAppLayout>}
export function CustomerDisputesPage({id}:{id?:string}){const[list,setList]=useState<CustomerDispute[]>([]),[detail,setDetail]=useState<CustomerDispute|null>(null),[error,setError]=useState('');useEffect(()=>{(id?api.getDispute(id).then(setDetail):api.getDisputes().then(setList)).catch((e:Error)=>setError(e.message))},[id]);return <CustomerAppLayout><section className="workHeading"><p>MY SOODAL</p><h1>분쟁 진행상태</h1><span>접수만으로 공급자 귀책을 의미하지 않으며 운영 검토 결과를 확인할 수 있습니다.</span></section>{error&&<div className="errorBanner">{error}</div>}{detail?<DisputeDetail value={detail}/>:<section className="workList">{list.map(x=><button onClick={()=>navigate(`/customer/disputes/${x.id}`)} key={x.id}><span className="workStatus">{x.displayStatus}</span><h2>{x.subject}</h2><p>{x.reason}</p><small>{date(x.receivedAt)}</small></button>)}</section>}</CustomerAppLayout>}
function DisputeDetail({value}:{value:CustomerDispute}){return <><button className="workBack" onClick={()=>navigate('/customer/disputes')}>← 분쟁 목록</button><section className="workPanel"><span className="workStatus">{value.displayStatus}</span><h2>{value.subject}</h2><h3>접수 사유</h3><p>{value.reason}</p><h3>요구사항</h3><p>{value.requestedResolution||'별도 요구사항 없음'}</p><h3>처리 결과</h3><p>{value.resultSummary??'운영팀 검토 중입니다.'}</p>{value.followUpAction&&<p>{value.followUpAction}</p>}</section><section className="workPanel"><h2>증빙</h2>{value.evidence.map(x=><p key={x.id}>{x.downloadUrl?<a href={x.downloadUrl}>{x.description??'첨부파일 보기'}</a>:x.description??x.sourceType}</p>)}</section></>}
const date=(v:string)=>new Intl.DateTimeFormat('ko-KR',{dateStyle:'medium',timeStyle:'short'}).format(new Date(v))
