import { useEffect, useMemo, useState } from 'react'
import { navigate } from '../auth/routing'
import { AuthenticatedLayout } from '../components/AuthenticatedLayout'
import * as providerApi from '../providers/api'
import type { MatchedRequestDetail, MatchedRequestListItem, ProviderProfile, ProviderServiceArea, ProviderServiceCategory } from '../providers/types'
import * as requestApi from '../requests/api'
import type { AdministrativeArea, Category } from '../requests/types'
import { ProviderQuotePanel } from '../quotes/QuotePanels'

function Header({ eyebrow, title, description }: { eyebrow: string; title: string; description: string }) {
  return <section className="heroCard compactHero"><p className="eyebrow">{eyebrow}</p><h1>{title}</h1><p>{description}</p></section>
}

export function ProviderServiceSettingsPage() {
  const [profile, setProfile] = useState<ProviderProfile | null>(null), [majors, setMajors] = useState<Category[]>([])
  const [middles, setMiddles] = useState<Category[]>([]), [services, setServices] = useState<Category[]>([])
  const [selected, setSelected] = useState<ProviderServiceCategory[]>([]), [majorId, setMajorId] = useState(''), [middleId, setMiddleId] = useState(''), [serviceId, setServiceId] = useState('')
  const [error, setError] = useState(''), [saved, setSaved] = useState(''), [loading, setLoading] = useState(true)
  useEffect(() => { Promise.all([providerApi.getProviderProfile(), providerApi.getProviderServices(), requestApi.getMajorCategories()]).then(([p, current, m]) => { setProfile(p); setSelected(current); setMajors(m) }).catch((reason: Error) => setError(reason.message)).finally(() => setLoading(false)) }, [])
  const chooseMajor = async (id: string) => { setMajorId(id); setMiddleId(''); setServiceId(''); setServices([]); setMiddles(id ? await requestApi.getMiddleCategories(id) : []) }
  const chooseMiddle = async (id: string) => { setMiddleId(id); setServiceId(''); setServices(id ? await requestApi.getServiceCategories(id) : []) }
  const add = () => { const service = services.find((item) => item.id === serviceId); if (!service || selected.some((item) => item.categoryId === service.id)) return; const major = majors.find((item) => item.id === majorId), middle = middles.find((item) => item.id === middleId); setSelected((items) => [...items, { categoryId: service.id, categoryPath: `${major?.name} > ${middle?.name} > ${service.name}`, status: 'ACTIVE', approvalStatus: 'PENDING', decisionReason: null, requiredRequirementCount: 0, approvedRequirementCount: 0 }]); setServiceId('') }
  const save = async () => { setError(''); setSaved(''); try { setSelected(await providerApi.replaceProviderServices(selected.map((item) => item.categoryId))); setSaved('제공 서비스가 저장되었습니다.') } catch (reason) { setError(reason instanceof Error ? reason.message : '저장하지 못했습니다.') } }
  return <AuthenticatedLayout><Header eyebrow="PROVIDER SERVICES" title="서비스 설정" description="실제로 제공할 하위 서비스를 복수 선택합니다." />{error && <div className="errorBanner">{error}</div>}{saved && <div className="successBanner">{saved}</div>}{loading ? <p className="emptyState">불러오는 중...</p> : <><section className="formSection"><div className="providerStatus"><strong>{profile?.businessName}</strong><span>{profile?.approvalStatus} · {profile?.activityStatus}</span></div><div className="formGrid threeColumns"><CategorySelect label="대분류" value={majorId} items={majors} onChange={chooseMajor} /><CategorySelect label="중분류" value={middleId} items={middles} onChange={chooseMiddle} disabled={!majorId} /><CategorySelect label="하위 서비스" value={serviceId} items={services} onChange={(id) => setServiceId(id)} disabled={!middleId} /></div><button className="secondaryButton addSelectionButton" type="button" disabled={!serviceId} onClick={add}>선택 서비스 추가</button></section><section className="formSection"><h2>선택한 서비스</h2>{selected.length === 0 ? <p className="emptyState">선택한 서비스가 없습니다.</p> : <div className="selectionList">{selected.map((item) => <div key={item.categoryId}><span>{item.categoryPath}</span><button type="button" onClick={() => setSelected((items) => items.filter((candidate) => candidate.categoryId !== item.categoryId))}>제거</button></div>)}</div>}</section><div className="formActions"><button className="secondaryButton" onClick={() => navigate('/provider')}>취소</button><button className="primaryButton" onClick={() => void save()}>저장</button></div></>}</AuthenticatedLayout>
}

export function ProviderAreaSettingsPage() {
  const [services, setServices] = useState<ProviderServiceArea[]>([]), [sidos, setSidos] = useState<AdministrativeArea[]>([]), [areas, setAreas] = useState<AdministrativeArea[]>([])
  const [selectedSido, setSelectedSido] = useState(''), [selection, setSelection] = useState<Record<string, string[]>>({}), [error, setError] = useState(''), [saved, setSaved] = useState('')
  useEffect(() => { Promise.all([providerApi.getProviderAreas(), requestApi.getSidoAreas(), requestApi.getAdministrativeAreas()]).then(([groups, sidoItems, areaItems]) => { setServices(groups); setSidos(sidoItems); setAreas(areaItems); setSelectedSido(sidoItems[0]?.id ?? ''); setSelection(Object.fromEntries(groups.map((group) => [group.serviceCategoryId, group.areas.map((area) => area.id)]))) }).catch((reason: Error) => setError(reason.message)) }, [])
  const visibleAreas = areas.filter((area) => !selectedSido || area.parentId === selectedSido)
  const toggle = (serviceId: string, areaId: string) => setSelection((current) => { const values = current[serviceId] ?? []; return { ...current, [serviceId]: values.includes(areaId) ? values.filter((id) => id !== areaId) : [...values, areaId] } })
  const save = async () => { setError(''); setSaved(''); try { const result = await providerApi.replaceProviderAreas(services.map((service) => ({ serviceCategoryId: service.serviceCategoryId, administrativeAreaIds: selection[service.serviceCategoryId] ?? [] }))); setServices(result); setSaved('출장지역이 저장되었습니다.') } catch (reason) { setError(reason instanceof Error ? reason.message : '저장하지 못했습니다.') } }
  return <AuthenticatedLayout><Header eyebrow="SERVICE AREAS" title="출장지역 설정" description="서비스별 출장 가능한 시·군·구를 선택합니다." />{error && <div className="errorBanner">{error}</div>}{saved && <div className="successBanner">{saved}</div>}<section className="formSection"><div className="formField"><label>시·도</label><select value={selectedSido} onChange={(event) => setSelectedSido(event.target.value)}>{sidos.map((sido) => <option key={sido.id} value={sido.id}>{sido.name}</option>)}</select></div></section>{services.length === 0 ? <p className="emptyState">먼저 제공 서비스를 설정해 주세요.</p> : services.map((service) => <section className="formSection" key={service.serviceCategoryId}><h2>{service.categoryPath}</h2><div className="areaChoiceGrid">{visibleAreas.map((area) => <label key={area.id}><input type="checkbox" checked={(selection[service.serviceCategoryId] ?? []).includes(area.id)} onChange={() => toggle(service.serviceCategoryId, area.id)} />{area.name}</label>)}</div></section>)}<div className="formActions"><button className="secondaryButton" onClick={() => navigate('/provider')}>취소</button><button className="primaryButton" onClick={() => void save()} disabled={services.length === 0}>저장</button></div></AuthenticatedLayout>
}

export function ProviderMatchedRequestListPage() {
  const [items, setItems] = useState<MatchedRequestListItem[]>([]), [error, setError] = useState(''), [loading, setLoading] = useState(true), [query, setQuery] = useState(''), [status, setStatus] = useState('')
  useEffect(() => { providerApi.getMatchedRequests().then(setItems).catch((reason: Error) => setError(reason.message)).finally(() => setLoading(false)) }, [])
  const visible = items.filter(item => (!status || item.dispatchStatus === status) && (!query || `${item.summary} ${item.categoryPath} ${item.areaName} ${item.requestId}`.toLowerCase().includes(query.toLowerCase())))
  return <AuthenticatedLayout><Header eyebrow="MATCHED REQUESTS" title="받은 요청" description="기존 Matching Domain이 내 서비스 승인·활동지역·필수요건을 검증해 배포한 요청입니다." /><section className="formSection"><div className="formGrid"><label className="formField">요청 검색<input value={query} onChange={event => setQuery(event.target.value)} placeholder="서비스, 지역, 요청번호" /></label><label className="formField">응답 상태<select value={status} onChange={event => setStatus(event.target.value)}><option value="">전체</option><option value="AVAILABLE">신규</option><option value="VIEWED">확인</option><option value="RESPONDED">견적 제출</option></select></label></div></section>{error && <div className="errorBanner">{error}</div>}{loading ? <p className="emptyState">불러오는 중...</p> : visible.length === 0 ? <p className="emptyState">조건에 맞는 받은 요청이 없습니다.</p> : <section className="requestList">{visible.map((item) => <button className="requestListItem" key={item.requestId} onClick={() => navigate(`/provider/matched-requests/${item.requestId}`)}><div><span className="statusBadge">{item.dispatchStatus}</span><h2>{item.summary}</h2><p>{item.categoryPath} · {item.areaName}</p></div><div className="requestMeta"><span>배포 {formatDate(item.dispatchedAt)}</span>{item.desiredAt && <span>희망 {formatDate(item.desiredAt)}</span>}</div></button>)}</section>}</AuthenticatedLayout>
}

export function ProviderMatchedRequestDetailPage({ requestId }: { requestId: string }) {
  const [item, setItem] = useState<MatchedRequestDetail | null>(null), [error, setError] = useState('')
  useEffect(() => { providerApi.getMatchedRequest(requestId).then(setItem).catch((reason: Error) => setError(reason.message)) }, [requestId])
  const visibleAnswers = useMemo(() => item?.answers ?? [], [item])
  return <AuthenticatedLayout>{error ? <div className="errorBanner">{error}</div> : !item ? <p className="emptyState">불러오는 중...</p> : <><Header eyebrow={item.dispatchStatus} title={item.title} description={item.categoryPath} /><section className="detailCard"><dl><dt>요청번호</dt><dd>{item.requestId}</dd><dt>지역</dt><dd>{item.areaName}</dd><dt>희망일</dt><dd>{item.desiredAt ? formatDate(item.desiredAt) : '입력 없음'}</dd><dt>요청 요약</dt><dd>{item.description || '입력 없음'}</dd><dt>배포일</dt><dd>{formatDate(item.dispatchedAt)}</dd><dt>마감일</dt><dd>{formatDate(item.expiresAt)}</dd></dl><p className="privacyNote">채택 전에는 고객 전화번호·이메일·상세주소를 서버 DTO에서 제공하지 않습니다.</p></section><section className="detailCard"><h2>고객 답변</h2><dl>{visibleAnswers.map((answer) => <div className="answerRow" key={answer.fieldId}><dt>{answer.label}</dt><dd>{answer.isMasked ? '개인정보 보호를 위해 비공개' : formatValue(answer.value)}</dd></div>)}</dl></section><section className="detailCard"><h2>요청 첨부파일</h2>{item.files.length===0 ? <p className="emptyState">현재 공급자에게 공개 가능한 첨부파일이 없습니다.</p> : item.files.map(file => <article className="providerRequirement" key={file.id}><div><strong>{file.fileName}</strong><p>Privacy {file.privacyInspectionStatus} · Malware {file.malwareScanStatus} · {file.publicationMode}</p></div><a className="secondaryButton" href={file.downloadUrl}>안전 파일 열기</a></article>)}<p className="privacyNote">검사 미연동·대기·실패 파일은 Fail Closed 규칙으로 공개되지 않습니다.</p></section><ProviderQuotePanel requestId={requestId} requestExpiresAt={item.expiresAt} /><div className="formActions"><button className="secondaryButton" onClick={() => navigate('/provider/matched-requests')}>목록으로</button></div></>}</AuthenticatedLayout>
}

function CategorySelect({ label, value, items, onChange, disabled = false }: { label: string; value: string; items: Category[]; onChange: (id: string) => void | Promise<void>; disabled?: boolean }) { return <div className="formField"><label>{label}</label><select value={value} disabled={disabled} onChange={(event) => void onChange(event.target.value)}><option value="">선택하세요</option>{items.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></div> }
function formatDate(value: string) { return new Intl.DateTimeFormat('ko-KR', { dateStyle: 'medium', timeStyle: 'short' }).format(new Date(value)) }
function formatValue(value: unknown) { if (value === null || value === undefined || value === '') return '입력 없음'; if (Array.isArray(value)) return value.map((item) => typeof item === 'object' && item && 'name' in item ? String(item.name) : String(item)).join(', '); if (typeof value === 'object') return JSON.stringify(value); if (typeof value === 'boolean') return value ? '예' : '아니오'; return String(value) }
