import { useEffect, useMemo, useState } from 'react'
import { navigate } from '../auth/routing'
import { AuthenticatedLayout } from '../components/AuthenticatedLayout'
import { AuthenticatedFilePreview } from '../components/AuthenticatedFilePreview'
import * as providerApi from '../providers/api'
import type { MatchedRequestDetail, MatchedRequestListItem, ProviderProfile, ProviderServiceArea, ProviderServiceCategory } from '../providers/types'
import * as requestApi from '../requests/api'
import type { AdministrativeArea, Category } from '../requests/types'
import { formatRequestAnswer, formatRequestAnswerLabel, isZeroRequestAnswer } from '../requests/formatRequestAnswer'
import { ProviderQuotePanel } from '../quotes/QuotePanels'
import { ProviderSiteVisitPanel } from '../siteVisits/SiteVisitPanels'
import * as emergencyApi from '../emergency/api'
import { soodalConfirm } from '../components/soodalDialog'
import { careApi } from '../customer/careApi'
import type { SubscriptionService } from '../customer/careTypes'
import { providerCareApi } from '../providers/careApi'
import type { CareRequest } from '../providers/careTypes'
import { ServiceThumbnail, serviceNameFromPath } from '../serviceVisuals/ServiceVisual'

function Header({ eyebrow, title, description }: { eyebrow: string; title: string; description: string }) {
  return <section className="heroCard compactHero"><p className="eyebrow">{eyebrow}</p><h1>{title}</h1><p>{description}</p></section>
}

type ProviderMiddleAreaGroup = { id: string; name: string; path: string; services: ProviderServiceArea[]; savedAreaIds: string[]; inconsistent: boolean }
const groupProviderAreasByMiddle = (items: ProviderServiceArea[]): ProviderMiddleAreaGroup[] => {
  const groups = new Map<string, ProviderMiddleAreaGroup>()
  items.forEach(item => {
    const group = groups.get(item.middleCategoryId) ?? { id: item.middleCategoryId, name: item.middleCategoryName, path: item.middleCategoryPath, services: [], savedAreaIds: [], inconsistent: false }
    group.services.push(item); group.savedAreaIds = Array.from(new Set([...group.savedAreaIds, ...item.areas.map(area => area.id)])); groups.set(group.id, group)
  })
  return Array.from(groups.values()).map(group => { const signatures = new Set(group.services.map(service => service.areas.map(area => area.id).sort().join(','))); return { ...group, savedAreaIds: group.savedAreaIds.sort(), inconsistent: signatures.size > 1 } })
}
const areaSelectionSignature = (selection: Record<string, string[]>, nationwide: string[]) => JSON.stringify({ areas: Object.entries(selection).sort(([left], [right]) => left.localeCompare(right)).map(([id, areaIds]) => [id, [...areaIds].sort()]), nationwide: [...nationwide].sort() })
const emergencyAreaStatus = (available: boolean, reason: string) => available ? '현재 긴급출동 가능' : ({ NOT_CONFIGURED: '긴급출동 설정 필요', NO_ENABLED_SERVICE: '설정된 긴급출동 서비스 없음', AREA_NOT_CONFIGURED: '긴급출동 활동지역 필요', EMERGENCY_DISABLED: '전체 긴급출동 꺼짐', EMERGENCY_SERVICE_DISABLED: '서비스 긴급출동 미설정', EMERGENCY_TEMPORARILY_UNAVAILABLE: '임시 출동 중지 중', EMERGENCY_EXCEPTION_ACTIVE: '예외 휴무 기간', OUTSIDE_EMERGENCY_HOURS: '현재 가능시간 아님', AVAILABLE: '현재 긴급출동 가능' }[reason] ?? '상태 확인 중')
const koreanCompare = (left: string, right: string) => left.localeCompare(right, 'ko-KR')
const sortCategories = (items: Category[]) => [...items].sort((left, right) => (left.externalCode??'ZZZZ').localeCompare(right.externalCode??'ZZZZ') || left.sortOrder-right.sortOrder || koreanCompare(left.name, right.name))
const sortSubscriptionServices = (items: SubscriptionService[]) => [...items].sort((left, right) => koreanCompare(left.majorName, right.majorName) || koreanCompare(left.middleName, right.middleName) || koreanCompare(left.serviceName, right.serviceName))
const providerStatusLabel = (value: string | undefined) => ({ APPROVED: '승인 완료', PENDING: '승인 심사 중', REJECTED: '승인 반려', ACTIVE: '활동 중', INACTIVE: '활동 중지', SUSPENDED: '활동 정지' } as Record<string,string>)[value ?? ''] ?? '상태 확인 중'

export function ProviderServiceSettingsPage() {
  const [profile, setProfile] = useState<ProviderProfile | null>(null), [majors, setMajors] = useState<Category[]>([])
  const [middles, setMiddles] = useState<Category[]>([]), [services, setServices] = useState<Category[]>([])
  const [selected, setSelected] = useState<ProviderServiceCategory[]>([]), [majorId, setMajorId] = useState(''), [middleId, setMiddleId] = useState(''), [serviceId, setServiceId] = useState('')
  const [selectionMode, setSelectionMode] = useState<'SUBSCRIPTION' | 'EMERGENCY' | 'ALL'>('ALL'), [subscriptionServices, setSubscriptionServices] = useState<SubscriptionService[]>([]), [subscriptionServiceId, setSubscriptionServiceId] = useState('')
  const [error, setError] = useState(''), [saved, setSaved] = useState(''), [loading, setLoading] = useState(true), [saving, setSaving] = useState(false)
  useEffect(() => { Promise.all([providerApi.getProviderProfile(), providerApi.getProviderServices(), requestApi.getMajorCategories(false, false), careApi.services()]).then(([p, current, m, recurring]) => { setProfile(p); setSelected(current); setMajors(sortCategories(m)); setSubscriptionServices(sortSubscriptionServices(recurring)) }).catch((reason: Error) => setError(reason.message)).finally(() => setLoading(false)) }, [])
  const chooseMode = async (mode:'SUBSCRIPTION'|'EMERGENCY'|'ALL') => { setSelectionMode(mode); setMajorId(''); setMiddleId(''); setServiceId(''); setMiddles([]); setServices([]); setError(''); if(mode!=='SUBSCRIPTION')try{setMajors(sortCategories(await requestApi.getMajorCategories(mode==='EMERGENCY',false)))}catch(reason){setError(reason instanceof Error?reason.message:'서비스 분류를 불러오지 못했습니다.')} }
  const chooseMajor = async (id: string) => { setMajorId(id); setMiddleId(''); setServiceId(''); setServices([]); setMiddles(id ? sortCategories(await requestApi.getMiddleCategories(id, selectionMode==='EMERGENCY', false)) : []) }
  const chooseMiddle = async (id: string) => { setMiddleId(id); setServiceId(''); setServices(id ? sortCategories(await requestApi.getServiceCategories(id, selectionMode==='EMERGENCY', false)) : []) }
  const toSelection = (service: Category): ProviderServiceCategory => { const major = majors.find((item) => item.id === majorId), middle = middles.find((item) => item.id === middleId); return { categoryId: service.id, categoryPath: `${major?.name} > ${middle?.name} > ${service.name}`, status: 'ACTIVE', approvalStatus: 'PENDING', decisionReason: null, requiredRequirementCount: 0, approvedRequirementCount: 0 } }
  const toSubscriptionSelection = (service: SubscriptionService): ProviderServiceCategory => ({ categoryId: service.id, categoryPath: service.categoryPath, status: 'ACTIVE', approvalStatus: 'PENDING', decisionReason: null, requiredRequirementCount: 0, approvedRequirementCount: 0 })
  const persist = async (next:ProviderServiceCategory[], notice:string):Promise<boolean> => { if(saving)return false; setSaving(true); setError(''); setSaved(''); try { setSelected(await providerApi.replaceProviderServices(next.map(item=>item.categoryId))); setSaved(notice); return true } catch (reason) { setError(reason instanceof Error ? reason.message : '서비스 설정을 저장하지 못했습니다.'); return false } finally { setSaving(false) } }
  const add = async () => { const service=services.find(item=>item.id===serviceId); if(!service||selected.some(item=>item.categoryId===service.id))return; if(await persist([...selected,toSelection(service)],`${service.name} 서비스를 추가하고 저장했습니다.`))setServiceId('') }
  const addSubscription = async () => { const service=subscriptionServices.find(item=>item.id===subscriptionServiceId); if(!service||selected.some(item=>item.categoryId===service.id))return; if(await persist([...selected,toSubscriptionSelection(service)],`${service.serviceName} 정기구독 서비스를 추가하고 저장했습니다.`))setSubscriptionServiceId('') }
  const addAll = async () => { const additions=services.filter(service=>!selected.some(item=>item.categoryId===service.id)); if(!additions.length)return; if(await persist([...selected,...additions.map(toSelection)],`하위 서비스 ${additions.length}개를 추가하고 저장했습니다.`))setServiceId('') }
  const remove = async (categoryId:string) => { const target=selected.find(item=>item.categoryId===categoryId); if(!target)return; await persist(selected.filter(item=>item.categoryId!==categoryId),`${target.categoryPath} 서비스를 제거하고 저장했습니다.`) }
  return <AuthenticatedLayout>
    <Header eyebrow="전문가 제공 서비스" title="서비스 설정" description="추가하거나 제거하면 선택 내용이 즉시 저장됩니다." />
    {error && <div className="errorBanner" role="alert">{error}</div>}{saved && <div className="successBanner" role="status">{saved}</div>}
    {loading ? <p className="emptyState">불러오는 중...</p> : <>
      <section className="formSection"><div className="providerStatus"><strong>{profile?.businessName}</strong><span>{providerStatusLabel(profile?.approvalStatus)} · {providerStatusLabel(profile?.activityStatus)}</span></div><div className="providerSelectionActions providerSelectionModeButtons"><button className={selectionMode==='ALL'?'primaryButton':'secondaryButton'} type="button" disabled={saving} onClick={()=>void chooseMode('ALL')}>일반 서비스</button><button className={selectionMode==='SUBSCRIPTION'?'primaryButton':'secondaryButton'} type="button" disabled={saving} onClick={()=>void chooseMode('SUBSCRIPTION')}>정기구독 서비스</button><button className={selectionMode==='EMERGENCY'?'primaryButton':'secondaryButton'} type="button" disabled={saving} onClick={()=>void chooseMode('EMERGENCY')}>긴급출동 서비스</button></div>{selectionMode==='SUBSCRIPTION'?<><p className="privacyNote">고객용 맞춤케어에 표시되는 목록과 동일합니다. 추가 버튼을 누르면 즉시 저장됩니다.</p><div className="formField"><label>고객 맞춤케어와 동일한 정기구독 서비스</label><select value={subscriptionServiceId} onChange={event=>setSubscriptionServiceId(event.target.value)}><option value="">선택하세요</option>{subscriptionServices.map(item=><option key={item.id} value={item.id}>{item.categoryPath}</option>)}</select></div><div className="providerSelectionActions"><button className="secondaryButton addSelectionButton" type="button" disabled={!subscriptionServiceId||saving} onClick={()=>void addSubscription()}>정기구독 서비스 추가</button></div></>:<><p className="privacyNote">{selectionMode==='EMERGENCY'?'고객용 긴급출동과 동일한 긴급출동 가능 분류에서 선택합니다.':'정기구독과 긴급출동을 제외한 일반 서비스에서 선택합니다.'} 추가 버튼을 누르면 즉시 저장됩니다.</p><div className="formGrid threeColumns"><CategorySelect label="대분류" value={majorId} items={majors} onChange={chooseMajor} /><CategorySelect label="중분류" value={middleId} items={middles} onChange={chooseMiddle} disabled={!majorId} /><CategorySelect label="하위 서비스" value={serviceId} items={services} onChange={(id) => setServiceId(id)} disabled={!middleId} /></div><div className="providerSelectionActions"><button className="secondaryButton addSelectionButton" type="button" disabled={!serviceId||saving} onClick={()=>void add()}>{selectionMode==='EMERGENCY'?'긴급출동 서비스 추가':'선택 하위 서비스 추가'}</button><button className="secondaryButton addSelectionButton" type="button" disabled={saving||!middleId || services.length === 0 || services.every((service) => selected.some((item) => item.categoryId === service.id))} onClick={()=>void addAll()}>{selectionMode==='EMERGENCY'?'긴급출동 서비스 전체 추가':'전체 하위 서비스 추가'}</button></div></>}</section>
      <section className="formSection"><h2>선택한 서비스</h2><p className="privacyNote">제거 버튼을 누르면 즉시 저장 목록에서 삭제됩니다.</p>{selected.length === 0 ? <p className="emptyState">선택한 서비스가 없습니다.</p> : <div className="selectionList">{[...selected].sort((left,right)=>koreanCompare(left.categoryPath,right.categoryPath)).map((item) => <div key={item.categoryId}><ServiceThumbnail name={serviceNameFromPath(item.categoryPath)} /><span>{item.categoryPath}</span><button type="button" disabled={saving} onClick={()=>void remove(item.categoryId)}>제거</button></div>)}</div>}</section>
      <div className="formActions"><button className="primaryButton" disabled={saving} onClick={() => navigate('/provider')}>{saving ? '저장 중…' : '설정 완료'}</button></div>
    </>}
  </AuthenticatedLayout>
}

export function ProviderAreaSettingsPage() {
  const [services, setServices] = useState<ProviderServiceArea[]>([]), [sidos, setSidos] = useState<AdministrativeArea[]>([]), [areas, setAreas] = useState<AdministrativeArea[]>([])
  const [selectedSido, setSelectedSido] = useState(''), [selectedAreaIds, setSelectedAreaIds] = useState<string[]>([]), [selection, setSelection] = useState<Record<string, string[]>>({}), [error, setError] = useState(''), [saved, setSaved] = useState(''), [loading, setLoading] = useState(true), [saving, setSaving] = useState(false)
  const [expandedMiddleId, setExpandedMiddleId] = useState<string | null>(null), [nationwide, setNationwide] = useState<string[]>([]), [persistedSignature, setPersistedSignature] = useState(''), [emergencyStatus, setEmergencyStatus] = useState('')
  const middleGroups = useMemo(() => groupProviderAreasByMiddle(services), [services])
  const areaById = useMemo(() => new Map(areas.map(area => [area.id, area])), [areas])
  const sidoNameById = useMemo(() => new Map(sidos.map(sido => [sido.id, sido.name])), [sidos])
  useEffect(() => { Promise.all([providerApi.getProviderAreas(), requestApi.getSidoAreas(), requestApi.getAdministrativeAreas()]).then(([groups, sidoItems, areaItems]) => { const grouped = groupProviderAreasByMiddle(groups), savedAreaId = grouped.flatMap(group => group.savedAreaIds)[0], nextNationwide = groups.filter(service => service.isNationwide).map(service => service.serviceCategoryId), nextSelection = Object.fromEntries(grouped.map(group => [group.id, group.savedAreaIds])); setServices(groups); setNationwide(nextNationwide); setSidos(sidoItems); setAreas(areaItems); setSelectedSido(areaItems.find(area => area.id === savedAreaId)?.parentId ?? sidoItems[0]?.id ?? ''); setSelection(nextSelection); setPersistedSignature(areaSelectionSignature(nextSelection, nextNationwide)) }).catch((reason: Error) => setError(reason.message)).finally(() => setLoading(false)) }, [])
  const currentSignature = useMemo(() => areaSelectionSignature(selection, nationwide), [selection, nationwide])
  const hasChanges = currentSignature !== persistedSignature
  const visibleAreas = areas.filter((area) => !selectedSido || area.parentId === selectedSido)
  const toggleArea = (areaId: string) => { setSaved(''); setSelectedAreaIds(current => current.includes(areaId) ? current.filter(id => id !== areaId) : [...current, areaId]) }
  const setVisibleAreas = (selected: boolean) => { setSaved(''); const visibleIds = new Set(visibleAreas.map(area => area.id)); setSelectedAreaIds(current => selected ? Array.from(new Set([...current, ...visibleIds])) : current.filter(id => !visibleIds.has(id))) }
  const toggleMiddle = (middleId: string) => { if (selectedAreaIds.length === 0) return; setSaved(''); setEmergencyStatus(''); setSelection(current => { const values = current[middleId] ?? [], assignedToAll = selectedAreaIds.every(id => values.includes(id)); return { ...current, [middleId]: assignedToAll ? values.filter(id => !selectedAreaIds.includes(id)) : Array.from(new Set([...values, ...selectedAreaIds])) } }) }
  const save = async () => { setSaving(true); setError(''); setSaved(''); setEmergencyStatus(''); try { const direct = middleGroups.flatMap(group => group.services.map(service => ({ serviceCategoryId: service.serviceCategoryId, administrativeAreaIds: nationwide.includes(service.serviceCategoryId) ? [] : selection[group.id] ?? [] }))); const result = await providerApi.replaceProviderAreas(direct, nationwide); const grouped = groupProviderAreasByMiddle(result), nextNationwide = result.filter(service => service.isNationwide).map(service => service.serviceCategoryId), nextSelection = Object.fromEntries(grouped.map(group => [group.id, group.savedAreaIds])); setServices(result); setNationwide(nextNationwide); setSelection(nextSelection); setPersistedSignature(areaSelectionSignature(nextSelection, nextNationwide)); let status = '긴급출동 상태는 긴급출동 화면에서 확인해 주세요.'; try { const availability = await emergencyApi.availability(); status = emergencyAreaStatus(availability.isCurrentlyAvailable, availability.currentAvailabilityReason) } catch { /* activity areas were already saved; status lookup is supplementary */ } setEmergencyStatus(status); setSaved('활동지역이 서버에 저장되었습니다. 새로고침 후에도 동일하게 유지됩니다.'); window.scrollTo({ top: 0, behavior: 'smooth' }) } catch (reason) { setError(reason instanceof Error ? reason.message : '저장하지 못했습니다.') } finally { setSaving(false) } }
  const configuredMiddleCount = middleGroups.filter(group => (selection[group.id] ?? []).length > 0).length
  return <AuthenticatedLayout>
    <Header eyebrow="서비스 지역" title="서비스 제공범위 설정" description="지역 방문 서비스는 활동지역을, 원격·배송·전국 방문망 서비스는 전국 제공 여부를 전문가가 직접 설정합니다." />
    {error && <div className="errorBanner" role="alert">{error}</div>}{saved && <div className="successBanner" role="status">{saved}</div>}
    {loading ? <p className="emptyState">서비스 분야와 활동지역을 불러오는 중입니다.</p> : middleGroups.length === 0 ? <section className="formSection areaServiceRequired"><h2>서비스 분야를 먼저 설정해 주세요.</h2><p>등록된 서비스 분야가 없으면 활동지역을 설정할 수 없습니다.</p><button className="primaryButton" type="button" onClick={() => navigate('/provider/services')}>서비스 분야 설정하기</button></section> : <>
      <section className="formSection providerAreaSelector"><div className="formField"><label>1. 시·도 선택</label><select value={selectedSido} onChange={event => { setSelectedSido(event.target.value); setSelectedAreaIds([]) }}>{sidos.map(sido => <option key={sido.id} value={sido.id}>{sido.name}</option>)}</select></div><div><div className="areaSelectionHeading"><div><h2>2. 시·군·구 선택</h2><p>출장지역으로 연결할 시·군·구를 먼저 선택해 주세요.</p></div><div><button className="secondaryButton" type="button" onClick={() => setVisibleAreas(true)}>전체 선택</button><button className="secondaryButton" type="button" onClick={() => setVisibleAreas(false)}>선택 해제</button></div></div><div className="areaChoiceGrid">{visibleAreas.map(area => <label key={area.id}><input type="checkbox" checked={selectedAreaIds.includes(area.id)} onChange={() => toggleArea(area.id)} />{area.name}</label>)}</div></div></section>
      <section className="formSection"><h2>3. 적용할 서비스 분야 선택</h2><p className="areaServiceHint">위에서 선택한 시·군·구를 적용할 중분류 서비스 분야를 체크해 주세요. 체크를 해제하면 선택한 지역 연결이 해제됩니다.</p>{selectedAreaIds.length === 0 && <div className="areaSelectionNotice">먼저 위에서 시·군·구를 한 곳 이상 선택해 주세요.</div>}<div className="middleAreaChecklist">{middleGroups.map(group => { const assignedCount = selectedAreaIds.filter(id => (selection[group.id] ?? []).includes(id)).length, checked = selectedAreaIds.length > 0 && assignedCount === selectedAreaIds.length; return <label className={selectedAreaIds.length === 0 ? 'disabled' : ''} key={group.id}><input type="checkbox" disabled={selectedAreaIds.length === 0} checked={checked} onChange={() => toggleMiddle(group.id)} /><span><strong>{group.path}</strong><small>하위 서비스 {group.services.length}개 · 전체 저장 지역 {(selection[group.id] ?? []).length}개{assignedCount > 0 && !checked ? ` · 현재 선택 중 ${assignedCount}/${selectedAreaIds.length}개 연결` : ''}</small>{group.inconsistent && <em>기존 하위 서비스별 설정은 저장 시 중분류 기준으로 통일됩니다.</em>}</span></label> })}</div></section>
      <section className="formSection"><h2>{hasChanges ? '저장 예정 현황' : '현재 저장된 제공범위'}</h2><p className="areaServiceHint">서비스 분야를 클릭하면 제공유형과 지역을 확인할 수 있습니다. 전국 방문망도 증빙이나 본사 승인 없이 직접 선택합니다.</p><div className="middleAreaSummary">{middleGroups.map(group => { const expanded = expandedMiddleId === group.id, selectedAreas = (selection[group.id] ?? []).map(id => areaById.get(id)).filter((area): area is AdministrativeArea => Boolean(area)), areasBySido = Array.from(selectedAreas.reduce((result, area) => { const sidoId = area.parentId ?? '', current = result.get(sidoId) ?? []; current.push(area.name); result.set(sidoId, current); return result }, new Map<string, string[]>())); return <article className={expanded ? 'expanded' : ''} key={group.id}><button type="button" aria-expanded={expanded} aria-controls={`middle-area-detail-${group.id}`} onClick={() => setExpandedMiddleId(expanded ? null : group.id)}><span><strong>{group.path}</strong><small>하위 서비스 {group.services.length}개 · 출장지역 {selectedAreas.length}개</small></span><b>{expanded ? '접기' : '세부내역'}</b></button>{expanded && <div className="middleAreaDetail" id={`middle-area-detail-${group.id}`}><section><h3>하위 서비스</h3><ul>{group.services.map(service => <li key={service.serviceCategoryId}><span>{service.categoryPath.split(' > ').at(-1) ?? service.categoryPath}<small>{service.coverageTypeName}</small></span>{service.nationwideAllowed && <label><input type="checkbox" checked={nationwide.includes(service.serviceCategoryId)} onChange={() => { setSaved(''); setEmergencyStatus(''); setNationwide(current => current.includes(service.serviceCategoryId) ? current.filter(id => id !== service.serviceCategoryId) : [...current, service.serviceCategoryId]) }}/> 전국 제공</label>}</li>)}</ul></section><section><h3>출장지역</h3>{areasBySido.length === 0 ? <p>선택한 출장지역이 없습니다.</p> : <div className="middleAreaRegions">{areasBySido.map(([sidoId, districtNames]) => <div key={sidoId}><strong>{sidoNameById.get(sidoId) ?? '기타 지역'}</strong><span>{districtNames.sort((left, right) => left.localeCompare(right, 'ko')).join(', ')}</span></div>)}</div>}</section></div>}</article> })}</div></section>
      <div className="areaSaveFeedback" aria-live="polite">{saved && <strong>{saved}</strong>}{emergencyStatus && <span>긴급출동 상태: {emergencyStatus}</span>}{!hasChanges && !saved && <span>현재 화면은 서버에서 불러온 저장 상태입니다.</span>}</div>
      <div className="formActions"><button className="secondaryButton" disabled={saving} onClick={() => navigate('/provider')}>취소</button><button className="primaryButton" onClick={() => void save()} disabled={saving || !hasChanges || (configuredMiddleCount === 0 && nationwide.length === 0)}>{saving ? '저장 중…' : saved && !hasChanges ? '저장 완료' : '선택 서비스 분야 활동지역 저장'}</button></div>
    </>}
  </AuthenticatedLayout>
}

export function ProviderMatchedRequestListPage() {
  const pageSize=20
  const [items, setItems] = useState<MatchedRequestListItem[]>([]), [careItems,setCareItems]=useState<CareRequest[]>([]), [error, setError] = useState(''), [loading, setLoading] = useState(true), [query, setQuery] = useState(''), [status, setStatus] = useState('ACTIVE'), [page,setPage]=useState(1)
  useEffect(() => { Promise.all([providerApi.getMatchedRequests(),providerCareApi.requests()]).then(([matched,care])=>{setItems(matched);setCareItems(care)}).catch((reason: Error) => setError(reason.message)).finally(() => setLoading(false)) }, [])
  const isClosed = (item: MatchedRequestListItem) => item.dispatchStatus === 'EXPIRED' || item.dispatchStatus === 'DECLINED' || item.requestStatus !== 'OPEN' || new Date(item.expiresAt).getTime() <= Date.now()
  const standardAvailable = items.filter(item => !isClosed(item) && item.dispatchStatus !== 'RESPONDED')
  const closedItems = items.filter(isClosed)
  const available:UnifiedReceivedRequest[]=[...standardAvailable.map(toStandardRequest),...careItems.filter(item=>item.canApply&&!item.hasApplied).map(toCareRequest)]
  const source:UnifiedReceivedRequest[]=status==='CLOSED'?closedItems.map(toStandardRequest):available
  const filtered=source.filter(item=>!query||`${item.title} ${item.categoryPath} ${item.areaName} ${item.id}`.toLowerCase().includes(query.toLowerCase())).sort((a,b)=>Date.parse(b.createdAt)-Date.parse(a.createdAt))
  const pageCount=Math.max(1,Math.ceil(filtered.length/pageSize)),currentPage=Math.min(page,pageCount),visible=filtered.slice((currentPage-1)*pageSize,currentPage*pageSize)
  const changeStatus=(value:string)=>{setStatus(value);setPage(1)}
  return <AuthenticatedLayout><section className="heroCard compactHero providerReceivedHero"><p className="eyebrow">받은 견적 요청</p><h1>받은 요청</h1><p>일반 서비스·수달 케어·수달 인테리어·긴급출동 요청을 최신순으로 확인합니다.</p><button className="providerPrimary" onClick={()=>navigate('/provider/quotes')}>내 견적 결과</button></section><section className="formSection providerReceivedFilters"><div className="formGrid"><label className="formField">요청 검색<input value={query} onChange={event=>{setQuery(event.target.value);setPage(1)}} placeholder="서비스, 지역, 요청번호" /></label><label className="formField">요청 상태<select value={status} onChange={event=>changeStatus(event.target.value)}><option value="ACTIVE">제출 가능 {available.length}건</option><option value="CLOSED">마감·종료 {closedItems.length}건</option></select></label></div></section>{error&&<div className="errorBanner">{error}</div>}{loading?<p className="emptyState">불러오는 중...</p>:visible.length===0?<p className="emptyState">선택한 조건에 해당하는 받은 요청이 없습니다.</p>:<section className="requestList providerRequestGrid">{visible.map(item=><button className={`requestListItem${item.closed?' requestListItemClosed':''}`} key={`${item.domain}-${item.id}`} onClick={()=>navigate(item.route)}><div className="serviceVisualTitle"><ServiceThumbnail name={serviceNameFromPath(item.categoryPath)} /><div><span className={`requestDomainBadge domain-${item.domain.toLowerCase()}`}>{requestDomainLabel(item.domain)}</span><span className="statusBadge">{item.statusLabel}</span><h2>{item.title}</h2><p>{item.categoryPath} · {item.areaName}</p></div></div><div className="requestMeta"><span>요청일시 {formatDate(item.createdAt)}</span>{item.desiredAt&&<span>희망일시 {formatDate(item.desiredAt)}</span>}{item.expiresAt&&<span>응답마감 {formatDate(item.expiresAt)}</span>}</div></button>)}</section>}{filtered.length>pageSize&&<nav className="quotePagination" aria-label="받은 요청 페이지"><button disabled={currentPage<=1} onClick={()=>setPage(value=>Math.max(1,value-1))}>이전</button><span>{currentPage} / {pageCount} · {filtered.length}건</span><button disabled={currentPage>=pageCount} onClick={()=>setPage(value=>Math.min(pageCount,value+1))}>다음</button></nav>}</AuthenticatedLayout>
}

type RequestDomain='GENERAL'|'CARE'|'INTERIOR'|'EMERGENCY'
type UnifiedReceivedRequest={id:string;title:string;categoryPath:string;areaName:string;createdAt:string;desiredAt:string|null;expiresAt:string|null;domain:RequestDomain;statusLabel:string;closed:boolean;route:string}
const requestDomainLabel=(domain:RequestDomain)=>({GENERAL:'일반 서비스',CARE:'수달 케어',INTERIOR:'수달 인테리어',EMERGENCY:'긴급출동'}[domain])
const toStandardRequest=(item:MatchedRequestListItem):UnifiedReceivedRequest=>({id:item.requestId,title:item.summary,categoryPath:item.categoryPath,areaName:item.areaName,createdAt:item.dispatchedAt,desiredAt:item.desiredAt,expiresAt:item.expiresAt,domain:item.domain,statusLabel:matchedRequestStatusLabel(item,item.dispatchStatus==='EXPIRED'||item.dispatchStatus==='DECLINED'||item.requestStatus!=='OPEN'||new Date(item.expiresAt).getTime()<=Date.now()),closed:item.dispatchStatus==='EXPIRED'||item.dispatchStatus==='DECLINED'||item.requestStatus!=='OPEN'||new Date(item.expiresAt).getTime()<=Date.now(),route:`/provider/matched-requests/${item.requestId}`})
const toCareRequest=(item:CareRequest):UnifiedReceivedRequest=>({id:item.id,title:item.requestedScope||item.serviceName,categoryPath:item.serviceName,areaName:item.areaName,createdAt:item.createdAt,desiredAt:item.preferredStartDate,expiresAt:null,domain:'CARE',statusLabel:item.hasApplied?'지원 완료':'모집 중',closed:false,route:`/provider/care/requests?requestId=${encodeURIComponent(item.id)}`})

function matchedRequestStatusLabel(item: MatchedRequestListItem, closed: boolean) {
  if (item.dispatchStatus === 'DECLINED') return '제출하지 않음'
  if (item.dispatchStatus === 'EXPIRED' || (closed && item.requestStatus === 'OPEN')) return '모집 마감'
  if (item.requestStatus !== 'OPEN') return '요청 종료'
  if (item.dispatchStatus === 'RESPONDED') return '견적 제출'
  if (item.dispatchStatus === 'VIEWED') return '확인'
  return '신규'
}

export function ProviderMatchedRequestDetailPage({ requestId }: { requestId: string }) {
  const [item, setItem] = useState<MatchedRequestDetail | null>(null), [error, setError] = useState(''), [distanceConfirmed, setDistanceConfirmed] = useState(false), [declining, setDeclining] = useState(false)
  useEffect(() => { providerApi.getMatchedRequest(requestId).then(setItem).catch((reason: Error) => setError(reason.message)) }, [requestId])
  const visibleAnswers = useMemo(() => (item?.answers ?? []).filter(answer => answer.inputType.toUpperCase() !== 'DATETIME'), [item])
  const decline = async () => { if (!await soodalConfirm('이 요청은 이동거리가 멀어 견적을 제출하지 않으시겠습니까?')) return; setDeclining(true); setError(''); try { await providerApi.declineMatchedRequest(requestId); navigate('/provider/matched-requests', true) } catch (reason) { setError(reason instanceof Error ? reason.message : '요청을 건너뛰지 못했습니다.') } finally { setDeclining(false) } }
  const requestClosed = item ? item.dispatchStatus === 'EXPIRED' || item.dispatchStatus === 'DECLINED' || item.requestStatus !== 'OPEN' || new Date(item.expiresAt).getTime() <= Date.now() : false
  const mayWriteQuote = !requestClosed && (item?.dispatchStatus === 'RESPONDED' || distanceConfirmed)
  const showEstimateForm = () => { setDistanceConfirmed(true); window.requestAnimationFrame(() => window.requestAnimationFrame(() => { const target=document.getElementById('provider-quote-form'); target?.scrollIntoView({behavior:'smooth',block:'start'}); target?.focus({preventScroll:true}) })) }
  if (item && !item.requiresServiceAddress) return <AuthenticatedLayout>{error && <div className="errorBanner">{error}</div>}<Header eyebrow={item.dispatchStatus} title={item.title} description={item.categoryPath} />{requestClosed && <div className="infoBanner">마감·종료된 요청입니다. 요청 내용은 이력으로 계속 확인할 수 있지만 새 견적은 작성할 수 없습니다.</div>}<RequestOverview item={item} online /><CustomerRequestAnswers answers={visibleAnswers}/><RequestFiles item={item}/>{!requestClosed && <ProviderQuotePanel requestId={requestId} requestExpiresAt={item.expiresAt} categoryPath={item.categoryPath}/>}<div className="formActions"><button className="secondaryButton" onClick={() => navigate('/provider/matched-requests')}>목록으로</button></div></AuthenticatedLayout>
  return <AuthenticatedLayout>{error && <div className="errorBanner">{error}</div>}{!item ? !error && <p className="emptyState">불러오는 중...</p> : <><Header eyebrow={item.dispatchStatus} title={item.title} description={item.categoryPath} />{requestClosed && <div className="infoBanner">마감·종료된 요청입니다. 채택된 견적의 방문 업무만 계속할 수 있으며, 미채택 견적에는 방문 버튼이 표시되지 않습니다.</div>}<RequestOverview item={item}/>{!requestClosed && <section className="detailCard providerDistanceDecision"><h2>출장거리 확인</h2>{item.approximateDistanceKm !== null ? <p><strong>등록 기본주소 기준 약 {item.approximateDistanceKm.toLocaleString('ko-KR')}km</strong>입니다. 실제 도로 이동거리와 시간은 지도에서 다시 확인해 주세요.</p> : <p>양쪽 저장주소에 좌표가 없어 자동 거리를 계산하지 못했습니다. 위 지역 또는 공개된 상세주소까지의 이동거리와 소요시간을 직접 확인해 주세요.</p>}<div className="formActions"><button className="secondaryButton" disabled={declining || item.dispatchStatus === 'RESPONDED'} onClick={() => void decline()}>{declining ? '처리 중…' : '거리가 멀어 제출하지 않기'}</button><button className="primaryButton" disabled={declining} onClick={showEstimateForm}>거리 확인 완료 · 견적 작성</button></div></section>}<CustomerRequestAnswers answers={visibleAnswers}/><RequestFiles item={item}/><ProviderSiteVisitPanel requestId={requestId} requestExpiresAt={item.expiresAt} allowNewProposal={!requestClosed}/>{requestClosed ? null : mayWriteQuote ? <ProviderQuotePanel requestId={requestId} requestExpiresAt={item.expiresAt} categoryPath={item.categoryPath}/> : <p className="emptyState">출장거리를 확인하면 견적 작성란이 열립니다.</p>}<div className="formActions"><button className="secondaryButton" onClick={() => navigate('/provider/matched-requests')}>목록으로</button></div></>}</AuthenticatedLayout>
}

function RequestOverview({item,online=false}:{item:MatchedRequestDetail;online?:boolean}) { return <section className="detailCard providerRequestOverview"><dl><dt>요청번호</dt><dd>{item.requestId}</dd>{online?<><dt>진행 방식</dt><dd>전국 온라인 진행 · 방문 주소 없음</dd></>:<><dt>지역</dt><dd>{item.areaName}</dd><dt>상세주소</dt><dd>{item.detailAddress ?? '고객이 견적 채택 후 공개하도록 선택했습니다.'}</dd></>}<dt>희망일시 1순위</dt><dd>{item.desiredAt ? formatDate(item.desiredAt) : '입력 없음'}</dd><dt>희망일시 2순위</dt><dd>{item.desiredAtSecond ? formatDate(item.desiredAtSecond) : '입력 없음'}</dd><dt>요청 추가 내용</dt><dd className="requestAdditionalContent">{item.description || '입력 없음'}</dd><dt>요청일시</dt><dd>{formatDate(item.dispatchedAt)}</dd><dt>요청 마감 일시</dt><dd>{formatDate(item.expiresAt)}</dd></dl><p className="privacyNote">{online?'주소와 출장거리 확인 없이 비공개 업무 채팅으로 자료·계정 전달 방법을 협의하세요.':item.detailAddressDisclosureCode === 'BEFORE_QUOTE' ? '고객이 견적 제출 전 주소 공개를 선택했습니다. 이 요청을 받은 승인 전문가에게만 표시됩니다.' : '상세주소는 채택 전까지 비공개이며 시·군·구를 기준으로 이동 가능 여부를 판단해 주세요.'} 요청 마감 일시는 전문가가 제안서를 제출할 수 있는 기한입니다.</p></section> }
function CustomerRequestAnswers({answers}:{answers:MatchedRequestDetail['answers']}) { return <section className="detailCard"><h2>고객 요청</h2><dl>{answers.map(answer => <div className="answerRow" key={answer.fieldId}><dt>{formatRequestAnswerLabel(answers, answer)}</dt><dd>{answer.isMasked ? '개인정보 보호를 위해 비공개' : providerAnswer(answer)}</dd></div>)}</dl></section> }
function providerAnswer(answer:MatchedRequestDetail['answers'][number]) {
  if (!/희망\s*(비용|예산)/.test(answer.label)) return formatRequestAnswer(answer.value,answer.inputType)
  if (isZeroRequestAnswer(answer.value)) return '견적상담 후 결정'
  const raw=String(answer.value??'').replaceAll(',','').replace(/원$/,'').trim(), amount=Number(raw)
  return Number.isFinite(amount) ? `${amount.toLocaleString('ko-KR')}원` : formatRequestAnswer(answer.value,answer.inputType)
}
function RequestFiles({item}:{item:MatchedRequestDetail}) { return <section className="detailCard"><h2>요청 첨부파일</h2>{item.files.length===0?<p className="emptyState">등록된 이미지가 없습니다.</p>:<div className="authenticatedFilePreviewGrid">{item.files.map(file=><AuthenticatedFilePreview key={file.id} file={file} statusText={file.publicationMode==='VALIDATED_UPLOAD_ORIGINAL'?'업로드 형식 검증 완료 · 외부 검사 미연동':`악성코드 ${file.malwareScanStatus} · 개인정보 ${file.privacyInspectionStatus}`}/>)}</div>}<p className="privacyNote">이미지는 썸네일을 누르면 팝업에서 확대됩니다.</p></section> }

function CategorySelect({ label, value, items, onChange, disabled = false }: { label: string; value: string; items: Category[]; onChange: (id: string) => void | Promise<void>; disabled?: boolean }) { return <div className="formField"><label>{label}</label><select value={value} disabled={disabled} onChange={(event) => void onChange(event.target.value)}><option value="">선택하세요</option>{items.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></div> }
function formatDate(value: string) { return new Intl.DateTimeFormat('ko-KR', { dateStyle: 'medium', timeStyle: 'short' }).format(new Date(value)) }
