import { useCallback, useEffect, useRef, useState } from 'react'
import { navigate } from '../auth/routing'
import { AuthenticatedLayout } from '../components/AuthenticatedLayout'
import * as api from '../work/api'
import type { WorkTransactionDetail, WorkTransactionListItem } from '../work/types'

function Header({ title, description }: { title: string; description: string }) { return <section className="heroCard compactHero"><p className="eyebrow">WORK</p><h1>{title}</h1><p>{description}</p></section> }

export function WorkTransactionListPage({ audience }: { audience: 'provider' | 'customer' }) {
  const [items, setItems] = useState<WorkTransactionListItem[]>([]), [error, setError] = useState('')
  useEffect(() => { (audience === 'provider' ? api.getProviderTransactions() : api.getCustomerTransactions()).then(setItems).catch((e: Error) => setError(e.message)) }, [audience])
  const base = audience === 'provider' ? '/provider/work' : '/customer/transactions'
  return <AuthenticatedLayout><Header title={audience === 'provider' ? '내 작업' : '내 거래'} description="견적 선택 이후의 거래와 작업완료 상태를 확인합니다." />{error && <div className="errorBanner">{error}</div>}<section className="requestList">{items.map(item => <button className="requestListItem" key={item.id} onClick={() => navigate(`${base}/${item.id}`)}><div><span className="statusBadge">{item.status}</span><h2>{item.requestSummary}</h2><p>{item.categoryPath} · {item.areaName}</p></div><div className="requestMeta"><strong>{money(item.agreedAmount)}</strong><span>{date(item.createdAt)}</span></div></button>)}</section>{items.length === 0 && <p className="emptyState">거래가 없습니다.</p>}</AuthenticatedLayout>
}

export function ProviderWorkDetailPage({ transactionId }: { transactionId: string }) {
  const [item, setItem] = useState<WorkTransactionDetail | null>(null), [summary, setSummary] = useState(''), [amount, setAmount] = useState(0), [reason, setReason] = useState('')
  const [role, setRole] = useState(''), [description, setDescription] = useState(''), [file, setFile] = useState<File | null>(null), [error, setError] = useState(''), [message, setMessage] = useState('')
  const key = useRef(crypto.randomUUID())
  const load = useCallback(() => api.getProviderTransaction(transactionId).then(value => { setItem(value); if (value.completion) { setSummary(value.completion.workSummary); setAmount(value.completion.actualAmount) }; setRole(current => current || value.availablePhotoRoles[0]?.code || '') }).catch((e: Error) => setError(e.message)), [transactionId])
  useEffect(() => { void load() }, [load])
  const run = async (action: () => Promise<unknown>, success: string) => { setError(''); try { await action(); setMessage(success); await load() } catch (e) { setError(e instanceof Error ? e.message : '처리하지 못했습니다.') } }
  if (!item) return <AuthenticatedLayout>{error ? <div className="errorBanner">{error}</div> : <p className="emptyState">불러오는 중...</p>}</AuthenticatedLayout>
  const editable = item.status === 'IN_PROGRESS' || item.status === 'REVISION_REQUESTED'
  return <AuthenticatedLayout><Header title={item.requestTitle} description={item.categoryPath} />{error && <div className="errorBanner">{error}</div>}{message && <div className="successBanner">{message}</div>}<Summary item={item} /><WorkContext item={item} />{item.status === 'CREATED' && <div className="formActions"><button className="primaryButton" onClick={() => void run(() => api.startTransaction(item.id), '작업을 시작했습니다.')}>작업 시작</button></div>}{editable && <><section className="formSection"><h2>작업완료 초안</h2><div className="formGrid"><div className="formField fullWidth"><label>실제 작업 내용</label><textarea rows={5} value={summary} onChange={e => setSummary(e.target.value)} /></div><div className="formField"><label>실제 작업금액</label><input type="number" min="0" value={amount} onChange={e => setAmount(Number(e.target.value))} /></div><div className="formField"><label>revision 사유</label><input value={reason} onChange={e => setReason(e.target.value)} /></div></div><div className="formActions"><button className="secondaryButton" onClick={() => void run(async () => { await api.saveCompletionDraft(item.id, summary, amount, reason || null, key.current); key.current = crypto.randomUUID() }, '완료 초안을 저장했습니다.')}>초안 저장</button></div></section>{item.completion && <section className="formSection"><h2>완료 증빙 사진</h2><Policy item={item} /><div className="formGrid"><div className="formField"><label>사진 역할</label><select value={role} onChange={e => setRole(e.target.value)}>{item.availablePhotoRoles.map(r => <option key={r.code} value={r.code}>{r.name} ({r.code})</option>)}</select></div><div className="formField"><label>사진</label><input type="file" accept="image/jpeg,image/png,image/webp" onChange={e => setFile(e.target.files?.[0] ?? null)} /></div><div className="formField fullWidth"><label>설명</label><input maxLength={500} value={description} onChange={e => setDescription(e.target.value)} /></div></div><div className="formActions"><button className="secondaryButton" disabled={!file || !role} onClick={() => file && void run(() => api.uploadEvidence(item.id, role, description, file), '증빙을 추가했습니다.')}>사진 업로드</button><button className="primaryButton" onClick={() => void run(() => api.submitCompletion(item.id), '작업완료를 고객에게 제출했습니다.')}>완료 제출</button></div></section>}</>}<Evidence item={item} /><div className="formActions"><button className="secondaryButton" onClick={() => navigate('/provider/work')}>목록</button></div></AuthenticatedLayout>
}

export function CustomerWorkDetailPage({ transactionId }: { transactionId: string }) {
  const [item, setItem] = useState<WorkTransactionDetail | null>(null), [comment, setComment] = useState(''), [error, setError] = useState(''), [message, setMessage] = useState('')
  const load = useCallback(() => api.getCustomerTransaction(transactionId).then(setItem).catch((e: Error) => setError(e.message)), [transactionId]); useEffect(() => { void load() }, [load])
  const confirm = async (result: string) => { if (!item?.completion) return; setError(''); try { const response = await api.confirmCompletion(item.id, item.completion.id, result, comment || null, crypto.randomUUID()); setMessage(`처리 결과: ${response.result}`); await load() } catch (e) { setError(e instanceof Error ? e.message : '처리하지 못했습니다.') } }
  if (!item) return <AuthenticatedLayout>{error ? <div className="errorBanner">{error}</div> : <p className="emptyState">불러오는 중...</p>}</AuthenticatedLayout>
  return <AuthenticatedLayout><Header title={item.requestTitle} description={item.categoryPath} />{error && <div className="errorBanner">{error}</div>}{message && <div className="successBanner">{message}</div>}<Summary item={item} /><WorkContext item={item} /><Evidence item={item} />{item.status === 'COMPLETION_SUBMITTED' && item.completion && <section className="formSection"><h2>작업완료 확인</h2><div className="formField"><label>보완 요청 또는 이의 제기 사유</label><textarea rows={3} value={comment} onChange={e => setComment(e.target.value)} /></div><div className="formActions"><button className="secondaryButton" disabled={!comment.trim()} onClick={() => void confirm('REVISION_REQUESTED')}>보완 요청</button><button className="secondaryButton" disabled={!comment.trim()} onClick={() => void confirm('DISPUTED')}>이의 제기</button><button className="primaryButton" onClick={() => void confirm('COMPLETED')}>완료 확인</button></div></section>}<div className="formActions"><button className="secondaryButton" onClick={() => navigate('/customer/transactions')}>목록</button></div></AuthenticatedLayout>
}

function Summary({ item }: { item: WorkTransactionDetail }) { return <section className="detailCard"><dl><dt>상태</dt><dd>{item.status}</dd><dt>지역</dt><dd>{item.areaName}</dd><dt>공급자</dt><dd>{item.providerName}</dd><dt>계약금액</dt><dd>{money(item.agreedAmount)}</dd><dt>요청내용</dt><dd>{item.requestDescription || '-'}</dd></dl></section> }
function WorkContext({ item }: { item: WorkTransactionDetail }) { return <><section className="detailCard"><h2>선택 견적 항목</h2><div className="quoteItemTable">{item.quoteItems.map(q => <div key={q.lineNo}><span>{q.itemName}</span><span>{q.quantity} {q.unitText || ''}</span><span>{money(q.unitPriceAmount)}</span><strong>{money(q.lineTotalAmount)}</strong></div>)}</div></section><section className="detailCard"><h2>고객 요청 답변</h2><dl>{item.requestAnswers.map((a, index) => <div className="answerRow" key={`${a.label}-${index}`}><dt>{a.label}</dt><dd>{a.isMasked ? '비공개 정보' : display(a.value)}</dd></div>)}</dl></section></> }
function Policy({ item }: { item: WorkTransactionDetail }) { const p = item.completion?.policy ?? item.completionPolicy; return <div className="policyBox"><strong>사진 정책 {p.policyVersion}: 총 {p.uploadedPhotoCount}/{p.requiredPhotoCount}</strong>{p.roles.map(r => <span key={r.roleCode}>{r.roleName} {r.uploadedCount}/{r.requiredCount}</span>)}</div> }
function Evidence({ item }: { item: WorkTransactionDetail }) { if (!item.completion) return null; return <section className="detailCard"><h2>작업완료 REV {item.completion.revisionNo} · {item.completion.status}</h2><p>{item.completion.workSummary}</p><p>제출/기록일 {date(item.completion.recordedAt)}</p><p><strong>실제 작업금액 {money(item.completion.actualAmount)}</strong></p><Policy item={item} /><div className="evidenceGrid">{item.completion.evidence.map(e => <figure key={e.fileId}><img src={e.downloadUrl} alt={e.description || e.roleName} /><figcaption>{e.roleName} · {e.originalFileName}</figcaption></figure>)}</div></section> }
const money = (value: number) => new Intl.NumberFormat('ko-KR', { style: 'currency', currency: 'KRW', maximumFractionDigits: 4 }).format(value)
const date = (value: string) => new Intl.DateTimeFormat('ko-KR', { dateStyle: 'medium', timeStyle: 'short' }).format(new Date(value))
const display = (value: unknown) => value === null || value === undefined ? '-' : typeof value === 'object' ? JSON.stringify(value) : String(value)
