using System.Security.Claims;
using System.Security.Cryptography;
using System.Text;
using Microsoft.EntityFrameworkCore;
using SoodalLife.Api.Domain.Entities;
using SoodalLife.Api.Features.Wallet;
using SoodalLife.Api.Infrastructure.Persistence;

namespace SoodalLife.Api.Features.Advertising;

public sealed class ProviderAdvertisingService(SoodalLifeDbContext db, ProviderWalletService wallets)
{
    public Task<List<ProviderAdvertisingRateResponse>> GetRatesAsync(bool admin, CancellationToken token)
    {
        var today=DateOnly.FromDateTime(DateTime.UtcNow);var query=from rate in db.ProviderAdvertisingRatePolicies.AsNoTracking() join placement in db.AdvertisingPlacements.AsNoTracking() on rate.PlacementId equals placement.Id select new{rate,placement};
        if(!admin)query=query.Where(x=>x.rate.IsActive&&x.placement.IsActive&&x.rate.EffectiveFrom<=today&&(!x.rate.EffectiveTo.HasValue||x.rate.EffectiveTo>=today));
        return query.OrderBy(x=>x.placement.Id).ThenBy(x=>x.rate.DurationDays).Select(x=>new ProviderAdvertisingRateResponse(x.rate.PublicId,x.placement.PublicId,x.placement.Code,x.placement.Name,x.placement.Description,x.rate.DurationDays,x.rate.FixedAmount,x.rate.ProvinceUnitAmount,x.rate.DistrictUnitAmount,x.rate.RegionalFeeCapAmount,x.rate.CurrencyCode,x.rate.EffectiveFrom,x.rate.EffectiveTo,x.rate.IsActive)).ToListAsync(token);
    }

    public async Task<IReadOnlyList<ProviderAdvertisingAreaResponse>> GetAreasAsync(CancellationToken token)
    {
        var provinces=await db.AdministrativeAreas.AsNoTracking().Where(x=>x.IsActive&&x.AreaLevelCode=="SIDO").OrderBy(x=>x.AreaName).ToListAsync(token);
        var provinceIds=provinces.Select(x=>x.Id).ToArray();var districts=await db.AdministrativeAreas.AsNoTracking().Where(x=>x.IsActive&&x.AreaLevelCode=="SIGUNGU"&&x.ParentAreaId.HasValue&&provinceIds.Contains(x.ParentAreaId.Value)).OrderBy(x=>x.AreaName).ToListAsync(token);
        return provinces.Select(x=>new ProviderAdvertisingAreaResponse(x.PublicId,x.AreaName,districts.Where(d=>d.ParentAreaId==x.Id).Select(d=>new ProviderAdvertisingDistrictResponse(d.PublicId,d.AreaName)).ToArray())).ToArray();
    }

    public static ProviderAdvertisingPolicyGuideResponse Guide()=>new("노출 위치·기간 기본 정액 + 선택 지역 수 정액제","자동검사를 통과하면 광고비를 확정하고 즉시 게시하며 위험 신호가 있는 광고만 관리자 검토","표시 금액은 부가가치세 포함",["노출 위치·기간 선택","시·도 또는 시·군·구 선택","전문가 신청","자동 안전검사","통과 시 자동 게시·위험 신호 시 예외검토"],["시·도 전체는 1개 시·도 단가, 시·군·구는 선택 개수별 단가 적용","같은 시·도를 전체 선택하면 그 아래 시·군·구는 중복 과금하지 않음","초기 입점 지원을 위해 지역 가산액은 정책 상한까지만 부과","예외검토 반려 또는 게시 전 취소 시 예약금 전액 해제","게시 후에는 실제 광고비로 확정되어 자동 환급되지 않음"]);

    public async Task<ProviderAdvertisingApplicationListResponse> ProviderListAsync(ClaimsPrincipal principal,CancellationToken token){var p=await Provider(principal,token);var ids=await db.ProviderAdvertisingApplications.AsNoTracking().Where(x=>x.ProviderProfileId==p.Profile.Id).OrderByDescending(x=>x.SubmittedAt).Select(x=>x.Id).ToListAsync(token);return new(await BuildMany(ids,token));}
    public async Task<ProviderAdvertisingApplicationListResponse> AdminListAsync(string? status,string? search,CancellationToken token){var query=from app in db.ProviderAdvertisingApplications.AsNoTracking() join campaign in db.AdvertisingCampaigns.AsNoTracking() on app.CampaignId equals campaign.Id join provider in db.ProviderProfiles.AsNoTracking() on app.ProviderProfileId equals provider.Id select new{app,campaign,provider};if(!string.IsNullOrWhiteSpace(status))query=query.Where(x=>x.app.StatusCode==status.Trim().ToUpper());if(!string.IsNullOrWhiteSpace(search)){var q=search.Trim();query=query.Where(x=>x.campaign.CampaignName.Contains(q)||x.provider.BusinessName.Contains(q));}var ids=await query.OrderByDescending(x=>x.app.SubmittedAt).Select(x=>x.app.Id).Take(200).ToListAsync(token);return new(await BuildMany(ids,token));}
    public async Task<ProviderAdvertisingApplicationResponse?> ProviderDetailAsync(ClaimsPrincipal principal,Guid id,CancellationToken token){var p=await Provider(principal,token);var internalId=await db.ProviderAdvertisingApplications.Where(x=>x.PublicId==id&&x.ProviderProfileId==p.Profile.Id).Select(x=>(long?)x.Id).SingleOrDefaultAsync(token);return internalId.HasValue?await Build(internalId.Value,token):null;}
    public async Task<ProviderAdvertisingApplicationResponse?> AdminDetailAsync(Guid id,CancellationToken token){var internalId=await db.ProviderAdvertisingApplications.Where(x=>x.PublicId==id).Select(x=>(long?)x.Id).SingleOrDefaultAsync(token);return internalId.HasValue?await Build(internalId.Value,token):null;}

    public async Task<ProviderAdvertisingApplicationResponse> ApplyAsync(ClaimsPrincipal principal,SaveProviderAdvertisingApplicationRequest input,CancellationToken token)
    {
        var identity=await Provider(principal,token);if(identity.Profile.ApprovalStatusCode!="APPROVED"||identity.Profile.ActivityStatusCode!="ACTIVE")throw Error("PROVIDER_NOT_APPROVED_ACTIVE","전체 승인되고 활동 중인 전문가만 광고를 신청할 수 있습니다.",409);
        var rate=await ActiveRate(input.RatePolicyId,token);Validate(input);var region=await RegionQuote(input.AreaIds,rate.Rate,token);var total=rate.Rate.FixedAmount+region.Fee;var wallet=await db.ProviderWallets.SingleOrDefaultAsync(x=>x.ProviderProfileId==identity.Profile.Id&&x.CurrencyCode==rate.Rate.CurrencyCode,token)??throw Error("PROVIDER_WALLET_NOT_FOUND","이용료 계정을 찾을 수 없습니다.",404);EnsureFunds(wallet,total);
        await using var tx=await wallets.BeginTransactionAsync(token);var now=DateTime.UtcNow;var start=input.StartAt.ToUniversalTime();if(start<now.AddMinutes(-5))throw Error("AD_START_AT_PAST","광고 시작일시는 현재 이후로 입력해 주세요.");var destinationCode=Destination(input.DestinationTypeCode,input.DestinationValue);var destinationValue=destinationCode=="NONE"?null:Clean(input.DestinationValue);var manualReview=RequiresManualReview(input,destinationCode);
        var campaign=new AdvertisingCampaign{CampaignName=Required(input.CampaignName),CampaignTypeCode="ADVERTISEMENT",AudienceTypeCode=rate.Placement.Code=="PROVIDER_HOME"?"PROVIDER":"CUSTOMER",OwnerTypeCode="PROVIDER",OwnerDisplayName=identity.Profile.BusinessName,StartAt=start,EndAt=start.AddDays(rate.Rate.DurationDays),StatusCode="DRAFT",Priority=0,DestinationTypeCode=destinationCode,DestinationValue=destinationValue,ReviewStatusCode=manualReview?"PENDING":"APPROVED",ApprovedAt=manualReview?null:now,ApprovedByUserId=manualReview?null:identity.UserId,CreatedAt=now,CreatedByUserId=identity.UserId,UpdatedAt=now,UpdatedByUserId=identity.UserId};if(destinationCode=="INTERNAL_PATH")campaign.DestinationValue=ProviderProfilePath(identity.Profile.PublicId,campaign.PublicId);db.AdvertisingCampaigns.Add(campaign);await db.SaveChangesAsync(token);
        await ReplaceTargets(campaign,input,region.AreaIds,rate.Placement.Id,identity.UserId,now,token);var creative=new AdvertisingCreative{CampaignId=campaign.Id,Title=Required(input.Title),Subtitle=Clean(input.Subtitle),BodyText=Clean(input.BodyText),AltText=TemplateMetadata(input.TemplateCode),ButtonText=destinationCode=="NONE"?null:Clean(input.ButtonText),DestinationTypeCode=campaign.DestinationTypeCode,DestinationValue=campaign.DestinationValue,DisplayOrder=1,StatusCode="ACTIVE",CreatedAt=now,CreatedByUserId=identity.UserId,UpdatedAt=now,UpdatedByUserId=identity.UserId};db.AdvertisingCreatives.Add(creative);
        if(input.AutoRenewEnabled&&rate.Rate.DurationDays!=30)throw Error("PROVIDER_AD_AUTO_RENEW_30_DAYS_REQUIRED","매월 자동 갱신은 30일 광고에서만 선택할 수 있습니다.");var app=new ProviderAdvertisingApplication{CampaignId=campaign.Id,ProviderProfileId=identity.Profile.Id,RatePolicyId=rate.Rate.Id,WalletId=wallet.Id,DurationDays=rate.Rate.DurationDays,BaseFeeAmount=rate.Rate.FixedAmount,RegionalFeeAmount=region.Fee,FeeAmount=total,ProvinceTargetCount=region.ProvinceCount,DistrictTargetCount=region.DistrictCount,AutoRenewEnabled=input.AutoRenewEnabled,AutoRenewStatusCode=input.AutoRenewEnabled?"PENDING_PUBLICATION":"OFF",RenewalConsentAt=input.AutoRenewEnabled?now:null,RenewalConsentFeeAmount=input.AutoRenewEnabled?total:null,RenewalConsentPolicyFingerprint=input.AutoRenewEnabled?Fingerprint(rate.Rate,region.AreaIds):null,CurrencyCode=rate.Rate.CurrencyCode,StatusCode=manualReview?"SUBMITTED":"APPROVED",FeeStatusCode="RESERVED",SupplementNote=Clean(input.SupplementNote),SubmittedAt=now,ApprovedAt=manualReview?null:now,CreatedAt=now,CreatedByUserId=identity.UserId,UpdatedAt=now,UpdatedByUserId=identity.UserId};
        wallet.AvailableBalance-=app.FeeAmount;wallet.ReservedBalance+=app.FeeAmount;wallet.UpdatedAt=now;wallet.UpdatedByUserId=identity.UserId;var ledger=wallets.AddLedger(wallet,null,"RESERVE",-app.FeeAmount,$"provider-ad-reserve:{app.PublicId:N}","전문가 광고 신청 정액 광고비 예약","PROVIDER_ADVERTISING_APPLICATION",app.PublicId,null,now,identity.UserId);await wallets.SaveWithConcurrencyAsync(token);app.ReserveLedgerEntryId=ledger.Id;db.ProviderAdvertisingApplications.Add(app);await wallets.SaveWithConcurrencyAsync(token);if(!manualReview)await CaptureAndPublish(app,campaign,wallet,identity.UserId,now,token);if(tx is not null)await tx.CommitAsync(token);return await Build(app.Id,token);
    }

    public async Task<ProviderAdvertisingApplicationResponse> ResubmitAsync(ClaimsPrincipal principal,Guid id,SaveProviderAdvertisingApplicationRequest input,CancellationToken token)
    {
        var identity=await Provider(principal,token);var app=await db.ProviderAdvertisingApplications.SingleOrDefaultAsync(x=>x.PublicId==id&&x.ProviderProfileId==identity.Profile.Id,token)??throw Error("PROVIDER_AD_APPLICATION_NOT_FOUND","광고 신청을 찾을 수 없습니다.",404);if(app.StatusCode!="REJECTED"||app.FeeStatusCode!="RELEASED")throw Error("PROVIDER_AD_NOT_REJECTED","반려된 광고만 보완 제출할 수 있습니다.",409);if(string.IsNullOrWhiteSpace(input.SupplementNote))throw Error("PROVIDER_AD_SUPPLEMENT_REQUIRED","보완 내용을 입력해 주세요.");var rate=await ActiveRate(input.RatePolicyId,token);Validate(input);var region=await RegionQuote(input.AreaIds,rate.Rate,token);var total=rate.Rate.FixedAmount+region.Fee;var wallet=await db.ProviderWallets.SingleAsync(x=>x.Id==app.WalletId,token);EnsureFunds(wallet,total);var campaign=await db.AdvertisingCampaigns.SingleAsync(x=>x.Id==app.CampaignId,token);var creative=await db.AdvertisingCreatives.SingleAsync(x=>x.CampaignId==campaign.Id,token);var now=DateTime.UtcNow;var start=input.StartAt.ToUniversalTime();if(start<now.AddMinutes(-5))throw Error("AD_START_AT_PAST","광고 시작일시는 현재 이후로 입력해 주세요.");campaign.CampaignName=Required(input.CampaignName);campaign.StartAt=start;campaign.EndAt=start.AddDays(rate.Rate.DurationDays);campaign.AudienceTypeCode=rate.Placement.Code=="PROVIDER_HOME"?"PROVIDER":"CUSTOMER";campaign.DestinationTypeCode=Destination(input.DestinationTypeCode,input.DestinationValue);campaign.DestinationValue=campaign.DestinationTypeCode=="NONE"?null:campaign.DestinationTypeCode=="INTERNAL_PATH"?ProviderProfilePath(identity.Profile.PublicId,campaign.PublicId):Clean(input.DestinationValue);campaign.ReviewStatusCode="PENDING";campaign.RejectionReason=null;campaign.UpdatedAt=now;campaign.UpdatedByUserId=identity.UserId;creative.Title=Required(input.Title);creative.Subtitle=Clean(input.Subtitle);creative.BodyText=Clean(input.BodyText);creative.AltText=TemplateMetadata(input.TemplateCode);creative.ButtonText=campaign.DestinationTypeCode=="NONE"?null:Clean(input.ButtonText);creative.DestinationTypeCode=campaign.DestinationTypeCode;creative.DestinationValue=campaign.DestinationValue;creative.UpdatedAt=now;creative.UpdatedByUserId=identity.UserId;await ReplaceTargets(campaign,input,region.AreaIds,rate.Placement.Id,identity.UserId,now,token);
        if(input.AutoRenewEnabled&&rate.Rate.DurationDays!=30)throw Error("PROVIDER_AD_AUTO_RENEW_30_DAYS_REQUIRED","매월 자동 갱신은 30일 광고에서만 선택할 수 있습니다.");wallet.AvailableBalance-=total;wallet.ReservedBalance+=total;wallet.UpdatedAt=now;var ledger=wallets.AddLedger(wallet,null,"RESERVE",-total,$"provider-ad-resubmit:{app.PublicId:N}:{now.Ticks}","반려 광고 보완 제출 지역 포함 정액 광고비 재예약","PROVIDER_ADVERTISING_APPLICATION",app.PublicId,null,now,identity.UserId);await wallets.SaveWithConcurrencyAsync(token);app.RatePolicyId=rate.Rate.Id;app.DurationDays=rate.Rate.DurationDays;app.BaseFeeAmount=rate.Rate.FixedAmount;app.RegionalFeeAmount=region.Fee;app.FeeAmount=total;app.ProvinceTargetCount=region.ProvinceCount;app.DistrictTargetCount=region.DistrictCount;app.AutoRenewEnabled=input.AutoRenewEnabled;app.AutoRenewStatusCode=input.AutoRenewEnabled?"PENDING_PUBLICATION":"OFF";app.RenewalConsentAt=input.AutoRenewEnabled?now:null;app.RenewalConsentFeeAmount=input.AutoRenewEnabled?total:null;app.RenewalConsentPolicyFingerprint=input.AutoRenewEnabled?Fingerprint(rate.Rate,region.AreaIds):null;app.StatusCode="RESUBMITTED";app.FeeStatusCode="RESERVED";app.ReserveLedgerEntryId=ledger.Id;app.SupplementNote=input.SupplementNote.Trim();app.RejectionReason=null;app.ResubmittedAt=now;app.UpdatedAt=now;app.UpdatedByUserId=identity.UserId;await wallets.SaveWithConcurrencyAsync(token);return await Build(app.Id,token);
    }

    public async Task<ProviderAdvertisingApplicationResponse> CancelAsync(ClaimsPrincipal principal,Guid id,CancellationToken token){var identity=await Provider(principal,token);var app=await db.ProviderAdvertisingApplications.SingleOrDefaultAsync(x=>x.PublicId==id&&x.ProviderProfileId==identity.Profile.Id,token)??throw Error("PROVIDER_AD_APPLICATION_NOT_FOUND","광고 신청을 찾을 수 없습니다.",404);if(app.StatusCode is "PUBLISHED" or "CANCELLED")throw Error("PROVIDER_AD_CANNOT_CANCEL","게시 전 신청만 취소할 수 있습니다.",409);await Release(app,"전문가가 게시 전 광고 신청을 취소",identity.UserId,token);var campaign=await db.AdvertisingCampaigns.SingleAsync(x=>x.Id==app.CampaignId,token);campaign.StatusCode="ARCHIVED";campaign.UpdatedAt=DateTime.UtcNow;app.StatusCode="CANCELLED";app.CancelledAt=DateTime.UtcNow;app.UpdatedAt=DateTime.UtcNow;await db.SaveChangesAsync(token);return await Build(app.Id,token);}

    public async Task<ProviderAdvertisingApplicationResponse> ReviewAsync(Guid actorPublicId,Guid id,ProviderAdvertisingReviewRequest input,CancellationToken token){var actor=await Actor(actorPublicId,token);var app=await db.ProviderAdvertisingApplications.SingleOrDefaultAsync(x=>x.PublicId==id,token)??throw Error("PROVIDER_AD_APPLICATION_NOT_FOUND","광고 신청을 찾을 수 없습니다.",404);if(app.StatusCode is not ("SUBMITTED" or "RESUBMITTED"))throw Error("PROVIDER_AD_NOT_REVIEWABLE","검토 대기 또는 보완 제출 광고만 심사할 수 있습니다.",409);var campaign=await db.AdvertisingCampaigns.SingleAsync(x=>x.Id==app.CampaignId,token);var action=input.ActionCode.Trim().ToUpper();var now=DateTime.UtcNow;if(action=="REJECT"){if(string.IsNullOrWhiteSpace(input.Reason))throw Error("PROVIDER_AD_REJECTION_REASON_REQUIRED","반려 사유를 입력해 주세요.");await Release(app,"관리자 광고 심사 반려",actor,token);app.StatusCode="REJECTED";app.RejectionReason=input.Reason.Trim();campaign.ReviewStatusCode="REJECTED";campaign.RejectionReason=app.RejectionReason;campaign.StatusCode="DRAFT";}else if(action=="APPROVE"){app.StatusCode="APPROVED";app.ApprovedAt=now;campaign.ReviewStatusCode="APPROVED";campaign.ApprovedAt=now;campaign.ApprovedByUserId=actor;campaign.RejectionReason=null;}else throw Error("PROVIDER_AD_REVIEW_ACTION_INVALID","승인 또는 반려를 선택해 주세요.");app.UpdatedAt=now;app.UpdatedByUserId=actor;campaign.UpdatedAt=now;campaign.UpdatedByUserId=actor;await db.SaveChangesAsync(token);return await Build(app.Id,token);}

    public async Task<ProviderAdvertisingApplicationResponse> PublishAsync(Guid actorPublicId,Guid id,ProviderAdvertisingPublishRequest input,CancellationToken token){var actor=await Actor(actorPublicId,token);var app=await db.ProviderAdvertisingApplications.SingleOrDefaultAsync(x=>x.PublicId==id,token)??throw Error("PROVIDER_AD_APPLICATION_NOT_FOUND","광고 신청을 찾을 수 없습니다.",404);if(app.StatusCode!="APPROVED"||app.FeeStatusCode!="RESERVED")throw Error("PROVIDER_AD_NOT_PUBLISHABLE","승인되고 광고비가 예약된 캠페인만 게시할 수 있습니다.",409);var wallet=await db.ProviderWallets.SingleAsync(x=>x.Id==app.WalletId,token);if(wallet.ReservedBalance<app.FeeAmount)throw Error("WALLET_RESERVED_BALANCE_INVALID","예약 광고비를 확인할 수 없습니다.",409);var campaign=await db.AdvertisingCampaigns.SingleAsync(x=>x.Id==app.CampaignId,token);await using var tx=await wallets.BeginTransactionAsync(token);var now=DateTime.UtcNow;wallet.ReservedBalance-=app.FeeAmount;wallet.AvailableBalance+=app.FeeAmount;wallets.AddLedger(wallet,null,"RELEASE",app.FeeAmount,$"provider-ad-capture-release:{app.PublicId:N}","예약 광고비를 게시 확정 차감으로 전환","PROVIDER_ADVERTISING_APPLICATION",app.PublicId,null,now,actor);wallet.AvailableBalance-=app.FeeAmount;var use=wallets.AddLedger(wallet,null,"USE",-app.FeeAmount,$"provider-ad-capture:{app.PublicId:N}","전문가 광고 캠페인 게시 정액 광고비 확정","PROVIDER_ADVERTISING_APPLICATION",app.PublicId,null,now,actor);wallet.UpdatedAt=now;wallet.UpdatedByUserId=actor;await wallets.SaveWithConcurrencyAsync(token);app.StatusCode="PUBLISHED";app.FeeStatusCode="CAPTURED";app.CaptureLedgerEntryId=use.Id;app.PublishedAt=now;if(app.AutoRenewEnabled){app.AutoRenewStatusCode="ACTIVE";app.NextRenewalAt=campaign.EndAt;app.RenewalNoticeSentAt=null;}app.UpdatedAt=now;app.UpdatedByUserId=actor;campaign.StatusCode="ACTIVE";campaign.UpdatedAt=now;campaign.UpdatedByUserId=actor;await wallets.SaveWithConcurrencyAsync(token);if(tx is not null)await tx.CommitAsync(token);return await Build(app.Id,token);}

    private async Task CaptureAndPublish(ProviderAdvertisingApplication app,AdvertisingCampaign campaign,ProviderWallet wallet,long actor,DateTime now,CancellationToken token)
    {
        if(wallet.ReservedBalance<app.FeeAmount)throw Error("WALLET_RESERVED_BALANCE_INVALID","예약 광고비를 확인할 수 없습니다.",409);
        wallet.ReservedBalance-=app.FeeAmount;wallet.AvailableBalance+=app.FeeAmount;
        wallets.AddLedger(wallet,null,"RELEASE",app.FeeAmount,$"provider-ad-auto-capture-release:{app.PublicId:N}","자동검사 통과 광고의 예약금 확정 전환","PROVIDER_ADVERTISING_APPLICATION",app.PublicId,null,now,actor);
        wallet.AvailableBalance-=app.FeeAmount;var use=wallets.AddLedger(wallet,null,"USE",-app.FeeAmount,$"provider-ad-auto-capture:{app.PublicId:N}","자동검사 통과 광고비 확정","PROVIDER_ADVERTISING_APPLICATION",app.PublicId,null,now,actor);
        wallet.UpdatedAt=now;wallet.UpdatedByUserId=actor;app.StatusCode="PUBLISHED";app.FeeStatusCode="CAPTURED";app.CaptureLedgerEntryId=use.Id;app.PublishedAt=now;
        if(app.AutoRenewEnabled){app.AutoRenewStatusCode="ACTIVE";app.NextRenewalAt=campaign.EndAt;app.RenewalNoticeSentAt=null;}
        campaign.StatusCode="ACTIVE";campaign.UpdatedAt=now;campaign.UpdatedByUserId=actor;app.UpdatedAt=now;app.UpdatedByUserId=actor;await wallets.SaveWithConcurrencyAsync(token);
    }

    public async Task<ProviderAdvertisingRateResponse> UpdateRateAsync(Guid id,UpdateProviderAdvertisingRateRequest input,CancellationToken token){if(input.FixedAmount<=0||input.ProvinceUnitAmount<0||input.DistrictUnitAmount<0||input.RegionalFeeCapAmount<0)throw Error("PROVIDER_AD_RATE_AMOUNT_INVALID","광고 요금은 0원 이상이며 기본 정액 광고비는 0원보다 커야 합니다.");if(input.EffectiveTo.HasValue&&input.EffectiveTo<input.EffectiveFrom)throw Error("PROVIDER_AD_RATE_PERIOD_INVALID","적용 종료일을 확인해 주세요.");var row=await db.ProviderAdvertisingRatePolicies.SingleOrDefaultAsync(x=>x.PublicId==id,token)??throw Error("PROVIDER_AD_RATE_NOT_FOUND","광고 요금 정책을 찾을 수 없습니다.",404);row.FixedAmount=input.FixedAmount;row.ProvinceUnitAmount=input.ProvinceUnitAmount;row.DistrictUnitAmount=input.DistrictUnitAmount;row.RegionalFeeCapAmount=input.RegionalFeeCapAmount;row.IsActive=input.IsActive;row.EffectiveFrom=input.EffectiveFrom;row.EffectiveTo=input.EffectiveTo;row.UpdatedAt=DateTime.UtcNow;await db.SaveChangesAsync(token);return (await GetRatesAsync(true,token)).Single(x=>x.Id==id);}

    private async Task Release(ProviderAdvertisingApplication app,string reason,long actor,CancellationToken token){if(app.FeeStatusCode!="RESERVED")return;var wallet=await db.ProviderWallets.SingleAsync(x=>x.Id==app.WalletId,token);if(wallet.ReservedBalance<app.FeeAmount)throw Error("WALLET_RESERVED_BALANCE_INVALID","예약 광고비를 확인할 수 없습니다.",409);var now=DateTime.UtcNow;wallet.ReservedBalance-=app.FeeAmount;wallet.AvailableBalance+=app.FeeAmount;wallet.UpdatedAt=now;wallet.UpdatedByUserId=actor;var ledger=wallets.AddLedger(wallet,null,"RELEASE",app.FeeAmount,$"provider-ad-release:{app.PublicId:N}:{now.Ticks}",reason,"PROVIDER_ADVERTISING_APPLICATION",app.PublicId,null,now,actor);await wallets.SaveWithConcurrencyAsync(token);app.FeeStatusCode="RELEASED";app.ReleaseLedgerEntryId=ledger.Id;app.UpdatedAt=now;app.UpdatedByUserId=actor;await wallets.SaveWithConcurrencyAsync(token);}
    private async Task ReplaceTargets(AdvertisingCampaign campaign,SaveProviderAdvertisingApplicationRequest input,IReadOnlyList<long> areas,long placementId,long actor,DateTime now,CancellationToken token){var categories=await db.ServiceCategories.Where(x=>input.CategoryIds.Contains(x.PublicId)&&x.StatusCode=="ACTIVE").Select(x=>x.Id).Distinct().ToListAsync(token);if(categories.Count!=input.CategoryIds.Distinct().Count())throw Error("PROVIDER_AD_CATEGORY_INVALID","선택한 서비스 분야를 확인해 주세요.");db.AdvertisingCampaignPlacements.RemoveRange(db.AdvertisingCampaignPlacements.Where(x=>x.CampaignId==campaign.Id));db.AdvertisingCampaignCategories.RemoveRange(db.AdvertisingCampaignCategories.Where(x=>x.CampaignId==campaign.Id));db.AdvertisingCampaignAreas.RemoveRange(db.AdvertisingCampaignAreas.Where(x=>x.CampaignId==campaign.Id));db.AdvertisingCampaignPlacements.Add(new(){CampaignId=campaign.Id,PlacementId=placementId,CreatedAt=now,CreatedByUserId=actor});db.AdvertisingCampaignCategories.AddRange(categories.Select(x=>new AdvertisingCampaignCategory{CampaignId=campaign.Id,CategoryId=x,CreatedAt=now,CreatedByUserId=actor}));db.AdvertisingCampaignAreas.AddRange(areas.Select(x=>new AdvertisingCampaignArea{CampaignId=campaign.Id,AdministrativeAreaId=x,CreatedAt=now,CreatedByUserId=actor}));}
    private async Task<(ProviderAdvertisingRatePolicy Rate,AdvertisingPlacement Placement)> ActiveRate(Guid id,CancellationToken token){var today=DateOnly.FromDateTime(DateTime.UtcNow);var row=await(from rate in db.ProviderAdvertisingRatePolicies join placement in db.AdvertisingPlacements on rate.PlacementId equals placement.Id where rate.PublicId==id&&rate.IsActive&&placement.IsActive&&rate.EffectiveFrom<=today&&(!rate.EffectiveTo.HasValue||rate.EffectiveTo>=today) select new{rate,placement}).SingleOrDefaultAsync(token)??throw Error("PROVIDER_AD_RATE_NOT_ACTIVE","현재 신청 가능한 광고 요금이 아닙니다.",409);return(row.rate,row.placement);}
    private async Task<(long UserId,ProviderProfile Profile)> Provider(ClaimsPrincipal principal,CancellationToken token){if(!Guid.TryParse(principal.FindFirstValue(ClaimTypes.NameIdentifier),out var id))throw Error("AUTH_REQUIRED","로그인이 필요합니다.",401);var row=await(from user in db.Users where user.PublicId==id&&user.StatusCode=="ACTIVE" join profile in db.ProviderProfiles on user.Id equals profile.UserId select new{user.Id,profile}).SingleOrDefaultAsync(token)??throw Error("PROVIDER_PROFILE_REQUIRED","전문가 프로필이 필요합니다.",403);return(row.Id,row.profile);}
    private async Task<long> Actor(Guid id,CancellationToken token)=>await db.Users.Where(x=>x.PublicId==id&&x.StatusCode=="ACTIVE").Select(x=>(long?)x.Id).SingleOrDefaultAsync(token)??throw Error("ADMIN_REQUIRED","관리자 로그인이 필요합니다.",403);
    private async Task<List<ProviderAdvertisingApplicationResponse>> BuildMany(IReadOnlyList<long> ids,CancellationToken token){var result=new List<ProviderAdvertisingApplicationResponse>();foreach(var id in ids)result.Add(await Build(id,token));return result;}
    private async Task<ProviderAdvertisingApplicationResponse> Build(long id,CancellationToken token){var row=await(from app in db.ProviderAdvertisingApplications.AsNoTracking() join campaign in db.AdvertisingCampaigns.AsNoTracking() on app.CampaignId equals campaign.Id join provider in db.ProviderProfiles.AsNoTracking() on app.ProviderProfileId equals provider.Id join rate in db.ProviderAdvertisingRatePolicies.AsNoTracking() on app.RatePolicyId equals rate.Id join placement in db.AdvertisingPlacements.AsNoTracking() on rate.PlacementId equals placement.Id join creative in db.AdvertisingCreatives.AsNoTracking() on campaign.Id equals creative.CampaignId where app.Id==id select new{app,campaign,provider,placement,creative}).SingleAsync(token);var categories=await(from link in db.AdvertisingCampaignCategories.AsNoTracking() join x in db.ServiceCategories.AsNoTracking() on link.CategoryId equals x.Id where link.CampaignId==row.campaign.Id select new ProviderAdvertisingTargetResponse(x.PublicId,x.Name,"SERVICE",null)).ToListAsync(token);var areas=await(from link in db.AdvertisingCampaignAreas.AsNoTracking() join x in db.AdministrativeAreas.AsNoTracking() on link.AdministrativeAreaId equals x.Id join parent in db.AdministrativeAreas.AsNoTracking() on x.ParentAreaId equals parent.Id into parents from parent in parents.DefaultIfEmpty() where link.CampaignId==row.campaign.Id orderby parent.AreaName,x.AreaName select new ProviderAdvertisingTargetResponse(x.PublicId,x.AreaName,x.AreaLevelCode,parent==null?null:parent.AreaName)).ToListAsync(token);return new(row.app.PublicId,row.campaign.PublicId,row.campaign.CampaignName,row.provider.BusinessName,row.placement.Code,row.placement.Name,row.app.DurationDays,row.app.BaseFeeAmount,row.app.RegionalFeeAmount,row.app.FeeAmount,row.app.ProvinceTargetCount,row.app.DistrictTargetCount,row.app.CurrencyCode,row.app.StatusCode,row.app.FeeStatusCode,row.app.AutoRenewEnabled,row.app.AutoRenewStatusCode,row.app.NextRenewalAt,row.app.RenewalConsentRequired,row.app.RenewalConsentFeeAmount,row.app.RenewalCycleNo,row.app.LastRenewedAt,row.campaign.StartAt,row.campaign.EndAt!.Value,row.creative.Title,row.creative.Subtitle,row.creative.BodyText,TemplateCode(row.creative.AltText),row.creative.ButtonText,row.campaign.DestinationTypeCode,row.campaign.DestinationValue,row.app.SupplementNote,row.app.RejectionReason,row.app.SubmittedAt,row.app.ResubmittedAt,row.app.ApprovedAt,row.app.PublishedAt,categories,areas);}
    private async Task<RegionPriceQuote> RegionQuote(IReadOnlyList<Guid> ids,ProviderAdvertisingRatePolicy rate,CancellationToken token){var distinct=ids.Distinct().ToArray();var rows=await db.AdministrativeAreas.AsNoTracking().Where(x=>distinct.Contains(x.PublicId)&&x.IsActive).Select(x=>new{x.Id,x.PublicId,x.AreaLevelCode,x.ParentAreaId}).ToListAsync(token);if(rows.Count!=distinct.Length||rows.Any(x=>x.AreaLevelCode is not("SIDO" or "SIGUNGU")))throw Error("PROVIDER_AD_AREA_INVALID","시·도 또는 시·군·구 노출 지역만 선택해 주세요.");var provinces=rows.Where(x=>x.AreaLevelCode=="SIDO").ToArray();var provinceIds=provinces.Select(x=>x.Id).ToHashSet();var districts=rows.Where(x=>x.AreaLevelCode=="SIGUNGU"&&(!x.ParentAreaId.HasValue||!provinceIds.Contains(x.ParentAreaId.Value))).ToArray();var selected=provinces.Select(x=>x.Id).Concat(districts.Select(x=>x.Id)).Distinct().ToArray();var raw=provinces.Length*rate.ProvinceUnitAmount+districts.Length*rate.DistrictUnitAmount;var fee=rate.RegionalFeeCapAmount==0?raw:Math.Min(raw,rate.RegionalFeeCapAmount);return new(selected,provinces.Length,districts.Length,fee);}
    private static void EnsureFunds(ProviderWallet wallet,decimal amount){if(wallet.StatusCode!="ACTIVE")throw Error("WALLET_NOT_ACTIVE","사용할 수 없는 이용료 계정입니다.",409);if(wallet.AvailableBalance<amount)throw Error("WALLET_INSUFFICIENT_BALANCE","정액 광고비보다 이용료 잔액이 부족합니다.",409);}
    private static void Validate(SaveProviderAdvertisingApplicationRequest x){if(x.CategoryIds.Count==0)throw Error("PROVIDER_AD_CATEGORY_REQUIRED","광고할 서비스 분야를 한 개 이상 선택해 주세요.");if(x.AreaIds.Count==0)throw Error("PROVIDER_AD_AREA_REQUIRED","노출 지역을 한 개 이상 선택해 주세요.");if(!string.IsNullOrWhiteSpace(x.TemplateCode)&&!TemplateCodes.Contains(x.TemplateCode.Trim()))throw Error("PROVIDER_AD_TEMPLATE_INVALID","광고 배너 템플릿을 확인해 주세요.");if(!string.Equals(x.DestinationTypeCode,"NONE",StringComparison.OrdinalIgnoreCase)&&string.IsNullOrWhiteSpace(x.ButtonText))throw Error("PROVIDER_AD_BUTTON_REQUIRED","연결 화면이 있는 광고는 자세히 보기 버튼 문구를 입력해 주세요.");}
    private static bool RequiresManualReview(SaveProviderAdvertisingApplicationRequest x,string destinationCode)
    {
        if(destinationCode=="EXTERNAL_URL")return true;
        var text=$"{x.CampaignName} {x.Title} {x.Subtitle} {x.BodyText}".ToLowerInvariant();
        string[] riskTerms=["불법","도박","대출","무조건 보장","100% 보장","성인","의약품 판매"];
        return riskTerms.Any(text.Contains);
    }
    private static string Required(string? value)=>string.IsNullOrWhiteSpace(value)?throw Error("PROVIDER_AD_REQUIRED","필수 입력값을 확인해 주세요."):value.Trim();
    private static string? Clean(string? value)=>string.IsNullOrWhiteSpace(value)?null:value.Trim();
    private static string Destination(string value,string? destination){var code=value.Trim().ToUpper();if(code is not("NONE" or "INTERNAL_PATH" or "EXTERNAL_URL"))throw Error("PROVIDER_AD_DESTINATION_INVALID","광고 이동 방식을 확인해 주세요.");if(code=="NONE")return code;if(string.IsNullOrWhiteSpace(destination))throw Error("PROVIDER_AD_DESTINATION_REQUIRED","광고 연결 주소를 입력해 주세요.");var target=destination.Trim();if(code=="INTERNAL_PATH"&&!PublicInternalDestinations.Contains(target))throw Error("PROVIDER_AD_DESTINATION_UNSAFE","수달 라이프에서 광고 연결을 허용한 공개 화면을 선택해 주세요.");if(code=="EXTERNAL_URL"&&(!Uri.TryCreate(target,UriKind.Absolute,out var uri)||uri.Scheme is not("http" or "https")))throw Error("PROVIDER_AD_DESTINATION_UNSAFE","외부 주소는 안전한 http 또는 https 주소만 사용할 수 있습니다.");return code;}
    private static readonly HashSet<string> PublicInternalDestinations=["/provider-profile"];
    private static readonly HashSet<string> TemplateCodes=["general-service","cleaning-care","plumbing-repair","electrical-lighting","interior-remodeling","moving-assembly","aircon-care","lesson-education","pet-care","emergency-night"];
    private static string TemplateMetadata(string? value){var code=string.IsNullOrWhiteSpace(value)?"general-service":value.Trim();if(!TemplateCodes.Contains(code))throw Error("PROVIDER_AD_TEMPLATE_INVALID","광고 배너 템플릿을 확인해 주세요.");return $"template:{code};수달 라이프 광고 배너";}
    private static string TemplateCode(string? value){if(!string.IsNullOrWhiteSpace(value)&&value.StartsWith("template:",StringComparison.OrdinalIgnoreCase)){var code=value[9..].Split(';',2)[0];if(TemplateCodes.Contains(code))return code;}return "general-service";}
    private static string ProviderProfilePath(Guid providerId,Guid campaignId)=>$"/providers/{providerId}?campaign={campaignId}";
    private static ProviderAdvertisingException Error(string code,string message,int status=400)=>new(code,message,status);
    private static string Fingerprint(ProviderAdvertisingRatePolicy rate,IReadOnlyList<long> areas)=>Convert.ToHexString(SHA256.HashData(Encoding.UTF8.GetBytes($"{rate.PublicId:N}|{rate.FixedAmount}|{rate.ProvinceUnitAmount}|{rate.DistrictUnitAmount}|{rate.RegionalFeeCapAmount}|{string.Join(',',areas.Order())}")));
    private sealed record RegionPriceQuote(IReadOnlyList<long> AreaIds,int ProvinceCount,int DistrictCount,decimal Fee);
}
