using System.Data;
using System.Security.Claims;
using System.Text.Json;
using Microsoft.EntityFrameworkCore;
using SoodalLife.Api.Domain.Entities;
using SoodalLife.Api.Features.Authentication;
using SoodalLife.Api.Features.Matching;
using SoodalLife.Api.Infrastructure.Persistence;
using SoodalLife.Api.Infrastructure.Security;

namespace SoodalLife.Api.Features.Subscriptions;

public sealed class CareSubscriptionService(SoodalLifeDbContext db,ProviderTradingEligibilityService eligibility,ISubscriptionVisitVerificationAdapter visitVerification,IPrivacyContract privacyContract)
{
    private const int RollingWindowDays=90;
    private static readonly string[] Frequencies=["WEEKLY","BIWEEKLY","MONTHLY","QUARTERLY","HALF_YEARLY"];

    public async Task<IReadOnlyList<SubscriptionServiceItem>> GetEligibleServices(CancellationToken token)
    {
        var today=DateOnly.FromDateTime(DateTime.UtcNow);
        return await (from service in db.ServiceCategories.AsNoTracking()
                      join middle in db.ServiceCategories.AsNoTracking() on service.ParentId equals middle.Id
                      join major in db.ServiceCategories.AsNoTracking() on middle.ParentId equals major.Id
                      where service.LevelCode=="SERVICE"&&service.StatusCode=="ACTIVE"&&
                            db.CategoryOperationPolicies.Any(p=>p.CategoryId==service.Id&&p.IsActive&&p.EffectiveFrom<=today&&(p.EffectiveTo==null||p.EffectiveTo>today)&&p.SubscriptionOptionText=="허용")
                      orderby major.SortOrder,middle.SortOrder,service.SortOrder
                      select new SubscriptionServiceItem(service.PublicId,major.Name,middle.Name,service.Name,$"{major.Name} > {middle.Name} > {service.Name}")).ToListAsync(token);
    }

    public async Task<CareProductResponse> CreateProduct(CreateCareProductRequest input,Guid actorPublicId,CancellationToken token)
    {
        if(input.StandardMonthlyAmount<0||input.StandardVisitAmount<0)throw Bad("SUBSCRIPTION_AMOUNT_INVALID","금액은 0원 이상이어야 합니다."); if(input.EffectiveTo<=input.EffectiveFrom)throw Bad("PRODUCT_PERIOD_INVALID","상품 적용기간을 확인해 주세요.");
        var actor=await AdminId(actorPublicId,token);var category=await EligibleCategory(input.ServiceCategoryId,token);var now=DateTime.UtcNow;
        var item=new CareProduct{ServiceCategoryId=category.Id,ProductName=input.ProductName.Trim(),Description=Clean(input.Description),ServiceScopeText=input.ServiceScopeText.Trim(),VisitsPerPeriod=input.VisitsPerPeriod,ExpectedDurationMinutes=input.ExpectedDurationMinutes,BillingPeriodCode=Code(input.BillingPeriodCode),StandardMonthlyAmount=input.StandardMonthlyAmount,StandardVisitAmount=input.StandardVisitAmount,IsActive=input.IsActive,EffectiveFrom=input.EffectiveFrom,EffectiveTo=input.EffectiveTo,CreatedAt=now,CreatedByUserId=actor,UpdatedAt=now,UpdatedByUserId=actor};
        db.CareProducts.Add(item);await db.SaveChangesAsync(token);return MapProduct(item,category.PublicId,category.Name);
    }

    public async Task<IReadOnlyList<CareProductResponse>> GetProducts(CancellationToken token)
    {
        var rows=await(from item in db.CareProducts.AsNoTracking()join category in db.ServiceCategories.AsNoTracking()on item.ServiceCategoryId equals category.Id orderby item.IsActive descending,item.ProductName select new{item,category.PublicId,category.Name}).ToListAsync(token);
        return rows.Select(x=>MapProduct(x.item,x.PublicId,x.Name)).ToArray();
    }

    public async Task<CareProductResponse> UpdateProduct(Guid id,CreateCareProductRequest input,Guid actorPublicId,CancellationToken token)
    {
        if(input.StandardMonthlyAmount<0||input.StandardVisitAmount<0)throw Bad("SUBSCRIPTION_AMOUNT_INVALID","금액은 0원 이상이어야 합니다.");if(input.EffectiveTo<=input.EffectiveFrom)throw Bad("PRODUCT_PERIOD_INVALID","상품 적용기간을 확인해 주세요.");var actor=await AdminId(actorPublicId,token);var item=await db.CareProducts.SingleOrDefaultAsync(x=>x.PublicId==id,token)??throw NotFound("CARE_PRODUCT_NOT_FOUND","구독상품을 찾을 수 없습니다.");var category=await EligibleCategory(input.ServiceCategoryId,token);item.ServiceCategoryId=category.Id;item.ProductName=input.ProductName.Trim();item.Description=Clean(input.Description);item.ServiceScopeText=input.ServiceScopeText.Trim();item.VisitsPerPeriod=input.VisitsPerPeriod;item.ExpectedDurationMinutes=input.ExpectedDurationMinutes;item.BillingPeriodCode=Code(input.BillingPeriodCode);item.StandardMonthlyAmount=input.StandardMonthlyAmount;item.StandardVisitAmount=input.StandardVisitAmount;item.EffectiveFrom=input.EffectiveFrom;item.EffectiveTo=input.EffectiveTo;item.IsActive=input.IsActive;item.UpdatedAt=DateTime.UtcNow;item.UpdatedByUserId=actor;await db.SaveChangesAsync(token);return MapProduct(item,category.PublicId,category.Name);
    }

    public async Task<SubscriptionRequestResponse> CreateRequest(CreateSubscriptionRequest input,ClaimsPrincipal principal,CancellationToken token)
    {
        ValidateRecurrence(input.Recurrence);var identity=await Customer(principal,token);var category=await EligibleCategory(input.ServiceCategoryId,token);
        var requestKey=Clean(input.IdempotencyKey);if(requestKey is not null){var prior=await db.SubscriptionEvents.AsNoTracking().Where(x=>x.IdempotencyKey==requestKey&&x.EventTypeCode=="REQUEST_CREATED"&&x.SubscriptionRequestId!=null).Select(x=>x.SubscriptionRequestId).SingleOrDefaultAsync(token);if(prior.HasValue&&await db.SubscriptionRequests.AnyAsync(x=>x.Id==prior&&x.CustomerProfileId==identity.ProfileId,token))return await BuildRequest(prior.Value,true,token);}
        CustomerAddress? savedAddress=null;if(input.CustomerAddressId.HasValue)savedAddress=await db.CustomerAddresses.AsNoTracking().SingleOrDefaultAsync(x=>x.PublicId==input.CustomerAddressId&&x.CustomerProfileId==identity.ProfileId&&x.IsActive,token)??throw NotFound("CUSTOMER_ADDRESS_NOT_FOUND","사용할 수 있는 저장주소를 찾을 수 없습니다.");
        var areaPublicId=savedAddress is null?input.AdministrativeAreaId:await db.AdministrativeAreas.Where(x=>x.Id==savedAddress.AdministrativeAreaId).Select(x=>x.PublicId).SingleAsync(token);var area=await db.AdministrativeAreas.SingleOrDefaultAsync(x=>x.PublicId==areaPublicId&&x.IsActive,token)??throw NotFound("AREA_NOT_FOUND","활성 행정구역을 찾을 수 없습니다.");
        var type=Code(input.RequestTypeCode);if(type is not("STANDARD" or "CUSTOM"))throw Bad("SUBSCRIPTION_REQUEST_TYPE_INVALID","구독 요청유형을 확인해 주세요.");
        CareProduct? product=null;if(type=="STANDARD"){if(!input.CareProductId.HasValue)throw Bad("CARE_PRODUCT_REQUIRED","표준상품을 선택해 주세요.");product=await db.CareProducts.SingleOrDefaultAsync(x=>x.PublicId==input.CareProductId&&x.ServiceCategoryId==category.Id&&x.IsActive,token)??throw NotFound("CARE_PRODUCT_NOT_FOUND","사용 가능한 구독상품을 찾을 수 없습니다.");}
        var address=savedAddress is null?Clean(input.DetailAddress):$"{savedAddress.RoadAddress} {savedAddress.DetailAddress}".Trim();var now=DateTime.UtcNow;var item=new SubscriptionRequest{CustomerProfileId=identity.ProfileId,ServiceCategoryId=category.Id,CareProductId=product?.Id,AdministrativeAreaId=area.Id,RequestTypeCode=type,RequestedScopeText=input.RequestedScopeText.Trim(),PreferredStartDate=input.PreferredStartDate,DetailAddress=address,StatusCode="OPEN",CreatedAt=now,CreatedByUserId=identity.UserId,UpdatedAt=now,UpdatedByUserId=identity.UserId};db.SubscriptionRequests.Add(item);await db.SaveChangesAsync(token);
        var rule=NewRule(item.Id,input.Recurrence,identity.UserId,now);db.SubscriptionRecurrenceRules.Add(rule);AddEvent(item.Id,null,null,"REQUEST_CREATED",new{item.PublicId,type,addressSource=savedAddress is null?"DIRECT":"SAVED_ADDRESS"},identity.UserId,requestKey??$"subscription-request:{item.PublicId:N}:created",now);await db.SaveChangesAsync(token);return await BuildRequest(item.Id,true,token);
    }

    public async Task<SubscriptionApplicationResponse> Apply(Guid requestId,SubmitSubscriptionApplicationRequest input,ClaimsPrincipal principal,CancellationToken token)
    {
        ValidateAmounts(input.ProposedMonthlyAmount,input.ProposedVisitAmount);var identity=await Provider(principal,token);var request=await db.SubscriptionRequests.SingleOrDefaultAsync(x=>x.PublicId==requestId,token)??throw NotFound("SUBSCRIPTION_REQUEST_NOT_FOUND","구독 요청을 찾을 수 없습니다.");if(request.StatusCode!="OPEN")throw Conflict("SUBSCRIPTION_REQUEST_NOT_OPEN","신청 가능한 구독 요청이 아닙니다.");
        var existingByKey=await db.SubscriptionApplications.SingleOrDefaultAsync(x=>x.IdempotencyKey==input.IdempotencyKey,token);if(existingByKey is not null)return await MapApplication(existingByKey,token);
        if(await db.SubscriptionApplications.AnyAsync(x=>x.SubscriptionRequestId==request.Id&&x.ProviderProfileId==identity.ProfileId,token))throw Conflict("SUBSCRIPTION_APPLICATION_DUPLICATED","이미 신청한 구독 요청입니다.");
        var result=await eligibility.EvaluateAsync(identity.ProfileId,request.ServiceCategoryId,request.AdministrativeAreaId,token);if(!result.IsEligible)throw Forbidden(result.ReasonCode??"PROVIDER_NOT_ELIGIBLE",EligibilityMessage(result.ReasonCode));
        var now=DateTime.UtcNow;var item=new SubscriptionApplication{SubscriptionRequestId=request.Id,ProviderProfileId=identity.ProfileId,ProposedScopeText=input.ProposedScopeText.Trim(),ProposedMonthlyAmount=input.ProposedMonthlyAmount,ProposedVisitAmount=input.ProposedVisitAmount,AvailableScheduleText=Clean(input.AvailableScheduleText),StatusCode="SUBMITTED",SubmittedAt=now,IdempotencyKey=input.IdempotencyKey.Trim(),CreatedAt=now,CreatedByUserId=identity.UserId,UpdatedAt=now,UpdatedByUserId=identity.UserId};db.SubscriptionApplications.Add(item);await db.SaveChangesAsync(token);AddEvent(request.Id,null,null,"APPLICATION_SUBMITTED",new{item.PublicId,providerId=identity.PublicId},identity.UserId,$"subscription-application:{item.PublicId:N}:submitted",now);await db.SaveChangesAsync(token);return await MapApplication(item,token);
    }

    public async Task<IReadOnlyList<SubscriptionApplicationResponse>> GetApplications(Guid requestId,ClaimsPrincipal principal,CancellationToken token)
    {
        var customer=await Customer(principal,token);var request=await db.SubscriptionRequests.AsNoTracking().SingleOrDefaultAsync(x=>x.PublicId==requestId&&x.CustomerProfileId==customer.ProfileId,token)??throw NotFound("SUBSCRIPTION_REQUEST_NOT_FOUND","구독 요청을 찾을 수 없습니다.");var rows=await db.SubscriptionApplications.AsNoTracking().Where(x=>x.SubscriptionRequestId==request.Id).OrderBy(x=>x.SubmittedAt).ToListAsync(token);var list=new List<SubscriptionApplicationResponse>();foreach(var row in rows)list.Add(await MapApplication(row,token));return list;
    }

    public async Task<SubscriptionContractResponse> SelectProvider(Guid requestId,SelectSubscriptionProviderRequest input,ClaimsPrincipal principal,CancellationToken token)
    {
        var customer=await Customer(principal,token);await using var tx=db.Database.IsRelational()?await db.Database.BeginTransactionAsync(IsolationLevel.Serializable,token):null;
        var request=await db.SubscriptionRequests.SingleOrDefaultAsync(x=>x.PublicId==requestId&&x.CustomerProfileId==customer.ProfileId,token)??throw NotFound("SUBSCRIPTION_REQUEST_NOT_FOUND","구독 요청을 찾을 수 없습니다.");
        var prior=await db.SubscriptionEvents.AsNoTracking().SingleOrDefaultAsync(x=>x.IdempotencyKey==input.IdempotencyKey,token);if(prior?.SubscriptionContractId is long priorContract)return await BuildContract(priorContract,token);
        if(request.SelectedApplicationId.HasValue||request.StatusCode!="OPEN")throw Conflict("SUBSCRIPTION_PROVIDER_ALREADY_SELECTED","이미 공급자가 선택된 요청입니다.");
        var application=await db.SubscriptionApplications.SingleOrDefaultAsync(x=>x.PublicId==input.ApplicationId&&x.SubscriptionRequestId==request.Id&&x.StatusCode=="SUBMITTED",token)??throw NotFound("SUBSCRIPTION_APPLICATION_NOT_FOUND","선택할 공급자 신청을 찾을 수 없습니다.");
        var eligible=await eligibility.EvaluateAsync(application.ProviderProfileId,request.ServiceCategoryId,request.AdministrativeAreaId,token);if(!eligible.IsEligible)throw Conflict(eligible.ReasonCode??"PROVIDER_NOT_ELIGIBLE",EligibilityMessage(eligible.ReasonCode));
        var rule=await db.SubscriptionRecurrenceRules.SingleAsync(x=>x.SubscriptionRequestId==request.Id,token);var provider=await db.ProviderProfiles.SingleAsync(x=>x.Id==application.ProviderProfileId,token);var product=request.CareProductId.HasValue?await db.CareProducts.SingleAsync(x=>x.Id==request.CareProductId,token):null;var now=DateTime.UtcNow;
        var operationPolicy=await db.CategoryOperationPolicies.AsNoTracking().Where(x=>x.CategoryId==request.ServiceCategoryId&&x.IsActive).OrderByDescending(x=>x.EffectiveFrom).FirstOrDefaultAsync(token);
        var completionPolicy=JsonSerializer.Serialize(new{source="CATEGORY_OPERATION_POLICY",policyId=operationPolicy?.PublicId,policyVersion=operationPolicy?.PolicyVersion,requiredPhotoCount=operationPolicy?.RequiredCompletionPhotoCount??0,requiresChecklist=false,requiresVisitVerification=false,evidenceRule=operationPolicy?.CompletionEvidenceRuleText});
        var contract=new SubscriptionContract{SubscriptionRequestId=request.Id,CustomerProfileId=request.CustomerProfileId,ProviderProfileId=provider.Id,ServiceCategoryId=request.ServiceCategoryId,CareProductId=request.CareProductId,SubscriptionApplicationId=application.Id,StatusCode="ACTIVE",StartedAt=now,PriceSnapshotJson=JsonSerializer.Serialize(new{monthlyAmount=application.ProposedMonthlyAmount??product?.StandardMonthlyAmount,visitAmount=application.ProposedVisitAmount??product?.StandardVisitAmount,currency="KRW",source=product is null?"PROVIDER_PROPOSAL":"STANDARD_PRODUCT_AND_PROPOSAL"}),FeePolicySnapshotJson=null,ServiceScopeSnapshotJson=JsonSerializer.Serialize(new{requested=request.RequestedScopeText,proposed=application.ProposedScopeText,product=product?.ServiceScopeText}),RecurrenceSnapshotJson=RecurrenceJson(rule),CompletionPolicySnapshotJson=completionPolicy,ProviderTrustScoreSnapshot=await db.ProviderTrustScoreCurrent.Where(x=>x.ProviderProfileId==provider.Id).Select(x=>x.Score).SingleOrDefaultAsync(token)??provider.TrustScore,CurrencyCode="KRW",CreatedAt=now,CreatedByUserId=customer.UserId,UpdatedAt=now,UpdatedByUserId=customer.UserId};
        db.SubscriptionContracts.Add(contract);application.StatusCode="SELECTED";application.UpdatedAt=now;application.UpdatedByUserId=customer.UserId;var others=await db.SubscriptionApplications.Where(x=>x.SubscriptionRequestId==request.Id&&x.Id!=application.Id&&x.StatusCode=="SUBMITTED").ToListAsync(token);foreach(var other in others){other.StatusCode="NOT_SELECTED";other.UpdatedAt=now;other.UpdatedByUserId=customer.UserId;}request.SelectedApplicationId=application.Id;request.StatusCode="CONTRACTED";request.UpdatedAt=now;request.UpdatedByUserId=customer.UserId;await db.SaveChangesAsync(token);
        AddEvent(request.Id,contract.Id,null,"PROVIDER_SELECTED",new{applicationId=application.PublicId,providerId=provider.PublicId},customer.UserId,input.IdempotencyKey.Trim(),now);AddEvent(request.Id,contract.Id,null,"CONTRACT_CREATED",new{contract.PublicId,feePolicy="POLICY_UNCONFIRMED"},customer.UserId,$"subscription-contract:{contract.PublicId:N}:created",now);AddEvent(request.Id,contract.Id,null,"CONTRACT_ACTIVATED",null,customer.UserId,$"subscription-contract:{contract.PublicId:N}:activated",now);await GenerateVisits(contract,rule,customer.UserId,now,token);await db.SaveChangesAsync(token);if(tx is not null)await tx.CommitAsync(token);return await BuildContract(contract.Id,token);
    }

    public async Task<SubscriptionContractResponse> ChangeState(Guid id,string action,ChangeContractStateRequest input,Guid actorPublicId,CancellationToken token)
    {
        var actor=await AdminId(actorPublicId,token);var item=await Contract(id,token);var now=DateTime.UtcNow;var code=Code(action);
        if(await db.SubscriptionEvents.AnyAsync(x=>x.IdempotencyKey==input.IdempotencyKey,token))return await BuildContract(item.Id,token);
        switch(code){case "PAUSE":if(item.StatusCode!="ACTIVE")throw Conflict("CONTRACT_STATE_INVALID","활성 계약만 일시정지할 수 있습니다.");item.StatusCode="PAUSED";item.PauseStartedAt=now;item.ResumePlannedAt=input.ResumePlannedAt;foreach(var visit in await FutureVisits(item.Id,now,token))visit.StatusCode="PAUSED";break;case "RESUME":if(item.StatusCode!="PAUSED")throw Conflict("CONTRACT_STATE_INVALID","일시정지 계약만 재개할 수 있습니다.");item.StatusCode="ACTIVE";item.PauseStartedAt=null;item.ResumePlannedAt=null;var rule=await db.SubscriptionRecurrenceRules.SingleAsync(x=>x.SubscriptionRequestId==item.SubscriptionRequestId,token);await GenerateVisits(item,rule,actor,now,token,true);break;case "TERMINATE":if(item.StatusCode=="TERMINATED")throw Conflict("CONTRACT_STATE_INVALID","이미 해지된 계약입니다.");item.StatusCode="TERMINATED";item.TerminationRequestedAt??=now;item.TerminatedAt=now;item.EndedAt=now;item.TerminationReason=Clean(input.Reason);foreach(var visit in await FutureVisits(item.Id,now,token))visit.StatusCode="CANCELLED";break;default:throw Bad("CONTRACT_ACTION_INVALID","계약 처리유형을 확인해 주세요.");}
        item.UpdatedAt=now;item.UpdatedByUserId=actor;AddEvent(item.SubscriptionRequestId,item.Id,null,code switch{"PAUSE"=>"PAUSED","RESUME"=>"RESUMED",_=>"TERMINATED"},new{input.Reason,input.ResumePlannedAt},actor,input.IdempotencyKey.Trim(),now);await db.SaveChangesAsync(token);return await BuildContract(item.Id,token);
    }

    public async Task<ProviderSubscriptionContractDetail> GetProviderContract(Guid id,ClaimsPrincipal principal,CancellationToken token)
    {
        var identity=await Provider(principal,token);var row=await(from contract in db.SubscriptionContracts.AsNoTracking()join request in db.SubscriptionRequests.AsNoTracking()on contract.SubscriptionRequestId equals request.Id join customer in db.CustomerProfiles.AsNoTracking()on contract.CustomerProfileId equals customer.Id join user in db.Users.AsNoTracking()on customer.UserId equals user.Id join area in db.AdministrativeAreas.AsNoTracking()on request.AdministrativeAreaId equals area.Id join service in db.ServiceCategories.AsNoTracking()on contract.ServiceCategoryId equals service.Id where contract.PublicId==id&&contract.ProviderProfileId==identity.ProfileId select new{contract,request,customer,user,area,service}).SingleOrDefaultAsync(token)??throw NotFound("SUBSCRIPTION_CONTRACT_NOT_FOUND","구독 계약을 찾을 수 없습니다.");
        var activeAssignment=row.contract.StatusCode=="ACTIVE"&&await db.SubscriptionVisitSchedules.AsNoTracking().AnyAsync(v=>v.SubscriptionContractId==row.contract.Id&&v.ProviderProfileId==identity.ProfileId&&v.StatusCode!="SKIPPED"&&v.StatusCode!="CANCELLED"&&v.StatusCode!="COMPLETED"&&v.StatusCode!="DISPUTED",token);
        var phone=privacyContract.Decide(PrivacyAudience.AssignedProvider,PrivacyField.Phone,activeAssignment);var address=privacyContract.Decide(PrivacyAudience.AssignedProvider,PrivacyField.DetailAddress,activeAssignment);
        if(!phone.CanAccess||!address.CanAccess)throw NotFound("SUBSCRIPTION_CONTRACT_CONTACT_NOT_AVAILABLE","현재 배정된 유효 회차의 업무 연락처만 조회할 수 있습니다.");
        var next=await db.SubscriptionVisitSchedules.Where(v=>v.SubscriptionContractId==row.contract.Id&&v.ProviderProfileId==identity.ProfileId&&v.ScheduledStartAt>=DateTime.UtcNow&&v.StatusCode!="CANCELLED"&&v.StatusCode!="SKIPPED").OrderBy(v=>v.ScheduledStartAt).Select(v=>(DateTime?)v.ScheduledStartAt).FirstOrDefaultAsync(token);
        return new(row.contract.PublicId,Number("SC",row.contract.PublicId),row.customer.DisplayName,row.user.Phone,row.request.DetailAddress,row.area.AreaName,row.service.Name,row.contract.ServiceScopeSnapshotJson,row.contract.RecurrenceSnapshotJson,row.contract.StatusCode,next);
    }

    public async Task<SubscriptionContractResponse> ReplaceProvider(Guid id,ReplaceSubscriptionProviderRequest input,Guid actorPublicId,CancellationToken token)
    {
        var actor=await AdminId(actorPublicId,token);var contract=await Contract(id,token);if(contract.StatusCode is not("ACTIVE" or "PAUSED"))throw Conflict("CONTRACT_STATE_INVALID","운영 중인 계약만 공급자를 교체할 수 있습니다.");if(await db.SubscriptionEvents.AnyAsync(x=>x.IdempotencyKey==input.IdempotencyKey,token))return await BuildContract(contract.Id,token);
        var provider=await db.ProviderProfiles.SingleOrDefaultAsync(x=>x.PublicId==input.ProviderId,token)??throw NotFound("PROVIDER_NOT_FOUND","공급자를 찾을 수 없습니다.");var request=await db.SubscriptionRequests.SingleAsync(x=>x.Id==contract.SubscriptionRequestId,token);var valid=await eligibility.EvaluateAsync(provider.Id,contract.ServiceCategoryId,request.AdministrativeAreaId,token);if(!valid.IsEligible)throw Conflict(valid.ReasonCode??"PROVIDER_NOT_ELIGIBLE",EligibilityMessage(valid.ReasonCode));
        var now=DateTime.UtcNow;var old=contract.ProviderProfileId;contract.ProviderProfileId=provider.Id;contract.UpdatedAt=now;contract.UpdatedByUserId=actor;foreach(var visit in await FutureVisits(contract.Id,now,token))visit.ProviderProfileId=provider.Id;AddEvent(contract.SubscriptionRequestId,contract.Id,null,"PROVIDER_REPLACED",new{oldProviderId=old,newProviderId=provider.Id,input.Reason},actor,input.IdempotencyKey.Trim(),now);await db.SaveChangesAsync(token);return await BuildContract(contract.Id,token);
    }

    public async Task<SubscriptionScheduleChangeResponse> RequestScheduleChange(Guid visitId,RequestScheduleChangeRequest input,ClaimsPrincipal principal,CancellationToken token)
    {
        var requestingUser=await UserId(principal,token);var targetVisit=await Visit(visitId,token);var authorized=await db.SubscriptionContracts.AnyAsync(contract=>contract.Id==targetVisit.SubscriptionContractId&&(db.CustomerProfiles.Any(customer=>customer.Id==contract.CustomerProfileId&&customer.UserId==requestingUser)||db.ProviderProfiles.Any(provider=>provider.Id==contract.ProviderProfileId&&provider.UserId==requestingUser)),token);if(!authorized)throw NotFound("SUBSCRIPTION_VISIT_NOT_FOUND","구독 회차를 찾을 수 없습니다.");
        var user=await UserId(principal,token);var visit=await Visit(visitId,token);if(visit.ScheduledStartAt<=DateTime.UtcNow)throw Conflict("PAST_VISIT_IMMUTABLE","과거 회차 일정은 변경할 수 없습니다.");var existing=await db.SubscriptionScheduleChanges.SingleOrDefaultAsync(x=>x.IdempotencyKey==input.IdempotencyKey,token);if(existing is not null)return MapChange(existing);
        var now=DateTime.UtcNow;var item=new SubscriptionScheduleChange{SubscriptionVisitScheduleId=visit.Id,RequestedByUserId=user,OldScheduleJson=JsonSerializer.Serialize(new{start=visit.ScheduledStartAt,end=visit.ScheduledEndAt}),NewScheduleJson=JsonSerializer.Serialize(new{start=input.ScheduledStartAt,end=input.ScheduledEndAt}),Reason=input.Reason.Trim(),StatusCode="REQUESTED",RequestedAt=now,IdempotencyKey=input.IdempotencyKey.Trim(),CreatedAt=now,UpdatedAt=now};db.SubscriptionScheduleChanges.Add(item);var contract=await db.SubscriptionContracts.SingleAsync(x=>x.Id==visit.SubscriptionContractId,token);AddEvent(contract.SubscriptionRequestId,contract.Id,visit.Id,"SCHEDULE_CHANGE_REQUESTED",new{item.PublicId,input.ScheduledStartAt,input.ScheduledEndAt},user,input.IdempotencyKey.Trim(),now);Audit(user,"SCHEDULE_CHANGE_REQUESTED","SUBSCRIPTION_SCHEDULE_CHANGE",item.PublicId,null,new{item.StatusCode},input.Reason,principal.IsInRole(RoleCodes.Customer)?RoleCodes.Customer:RoleCodes.Provider);await db.SaveChangesAsync(token);return MapChange(item);
    }

    public async Task<SubscriptionScheduleChangeResponse> DecideScheduleChange(Guid changeId,DecideScheduleChangeRequest input,ClaimsPrincipal principal,CancellationToken token)
    {
        var actor=await IdentityUser(principal,token);var item=await db.SubscriptionScheduleChanges.SingleOrDefaultAsync(x=>x.PublicId==changeId,token)??throw NotFound("SCHEDULE_CHANGE_NOT_FOUND","일정 변경 요청을 찾을 수 없습니다.");var visit=await db.SubscriptionVisitSchedules.SingleAsync(x=>x.Id==item.SubscriptionVisitScheduleId,token);var contract=await db.SubscriptionContracts.SingleAsync(x=>x.Id==visit.SubscriptionContractId,token);var customerUser=await db.CustomerProfiles.Where(x=>x.Id==contract.CustomerProfileId).Select(x=>x.UserId).SingleAsync(token);var providerUser=await db.ProviderProfiles.Where(x=>x.Id==contract.ProviderProfileId).Select(x=>x.UserId).SingleAsync(token);var expected=item.RequestedByUserId==customerUser?providerUser:item.RequestedByUserId==providerUser?customerUser:0;if(actor.Id!=expected)throw NotFound("SCHEDULE_CHANGE_NOT_FOUND","상대방에게 요청된 일정 변경만 결정할 수 있습니다.");return await DecideScheduleChangeCore(item,visit,contract,input.Approve,input.IdempotencyKey,input.RowVersion,actor.Id,false,null,actor.Id==customerUser?RoleCodes.Customer:RoleCodes.Provider,token);
    }

    public async Task<SubscriptionScheduleChangeResponse> ForceScheduleChange(Guid changeId,ForceScheduleChangeDecisionRequest input,Guid actorPublicId,CancellationToken token)
    {
        if(string.IsNullOrWhiteSpace(input.Reason))throw Bad("ADMIN_FORCE_REASON_REQUIRED","관리자 강제결정 사유가 필요합니다.");var actor=await AdminId(actorPublicId,token);var item=await db.SubscriptionScheduleChanges.SingleOrDefaultAsync(x=>x.PublicId==changeId,token)??throw NotFound("SCHEDULE_CHANGE_NOT_FOUND","일정 변경 요청을 찾을 수 없습니다.");var visit=await db.SubscriptionVisitSchedules.SingleAsync(x=>x.Id==item.SubscriptionVisitScheduleId,token);var contract=await db.SubscriptionContracts.SingleAsync(x=>x.Id==visit.SubscriptionContractId,token);return await DecideScheduleChangeCore(item,visit,contract,input.Approve,input.IdempotencyKey,input.RowVersion,actor,true,input.Reason.Trim(),RoleCodes.Admin,token);
    }

    public async Task<SubscriptionVisitResponse> SkipVisit(Guid id,string idempotencyKey,Guid actorPublicId,CancellationToken token)
    {
        if(string.IsNullOrWhiteSpace(idempotencyKey))throw Bad("IDEMPOTENCY_KEY_REQUIRED","중복 처리 방지 키가 필요합니다.");
        var actor=await AdminId(actorPublicId,token);var visit=await Visit(id,token);if(visit.ScheduledStartAt<=DateTime.UtcNow||visit.StatusCode is "COMPLETED" or "CANCELLED")throw Conflict("VISIT_SKIP_INVALID","건너뛸 수 없는 회차입니다.");if(await db.SubscriptionEvents.AnyAsync(x=>x.IdempotencyKey==idempotencyKey,token))return await BuildVisit(visit.Id,token);visit.StatusCode="SKIPPED";visit.UpdatedAt=DateTime.UtcNow;visit.UpdatedByUserId=actor;var contract=await db.SubscriptionContracts.SingleAsync(x=>x.Id==visit.SubscriptionContractId,token);AddEvent(contract.SubscriptionRequestId,contract.Id,visit.Id,"VISIT_SKIPPED",new{feeAction="NONE_POLICY_UNCONFIRMED"},actor,idempotencyKey,DateTime.UtcNow);await db.SaveChangesAsync(token);return await BuildVisit(visit.Id,token);
    }

    public async Task<SubscriptionVisitResponse> CompleteVisit(Guid id,CompleteSubscriptionVisitRequest input,ClaimsPrincipal principal,CancellationToken token)
    {
        var provider=await Provider(principal,token);var visit=await Visit(id,token);if(visit.ProviderProfileId!=provider.ProfileId)throw NotFound("SUBSCRIPTION_VISIT_NOT_FOUND","회차를 찾을 수 없습니다.");if(await db.SubscriptionEvents.AnyAsync(x=>x.IdempotencyKey==input.IdempotencyKey,token))return await BuildVisit(visit.Id,token);if(visit.StatusCode!="IN_PROGRESS")throw Conflict("VISIT_COMPLETION_INVALID","진행 중인 회차만 완료보고할 수 있습니다.");var contract=await db.SubscriptionContracts.SingleAsync(x=>x.Id==visit.SubscriptionContractId,token);if(contract.StatusCode!="ACTIVE")throw Conflict("SUBSCRIPTION_CONTRACT_NOT_ACTIVE","활성 구독 계약의 회차만 완료보고할 수 있습니다.");
        var files=await ResolveFiles(input.FileIds,provider.UserId,token);var policy=CompletionPolicy(contract.CompletionPolicySnapshotJson);if(files.Count<policy.RequiredPhotoCount)throw Conflict("SUBSCRIPTION_COMPLETION_PHOTO_REQUIRED",$"완료 사진 {policy.RequiredPhotoCount}개가 필요합니다.");if(policy.RequiresChecklist&&string.IsNullOrWhiteSpace(input.ChecklistJson))throw Conflict("SUBSCRIPTION_COMPLETION_CHECKLIST_REQUIRED","완료 체크리스트가 필요합니다.");var overridden=visit.VisitVerificationStatusCode=="OVERRIDE_APPROVED"&&visit.VerificationOverrideAt.HasValue;var verification=overridden?new SubscriptionVisitVerificationResult(visit.GpsVerificationStatusCode,visit.PossessionVerificationStatusCode,"OVERRIDE_APPROVED","ADMIN_OVERRIDE"):await visitVerification.VerifyAsync(new(input.GpsEvidence,input.VerificationMethodCode,input.PossessionEvidence??input.VerificationResultCode),token);visit.GpsVerificationStatusCode=verification.GpsStatusCode;visit.PossessionVerificationStatusCode=verification.PossessionStatusCode;visit.VisitVerificationStatusCode=verification.OverallStatusCode;if(policy.RequiresVisitVerification&&verification.OverallStatusCode!="VERIFIED"&&verification.OverallStatusCode!="OVERRIDE_APPROVED")throw Conflict("SUBSCRIPTION_VISIT_VERIFICATION_REQUIRED","방문 인증이 완료되지 않았습니다.");
        var now=DateTime.UtcNow;visit.VisitVerificationMethodCode=Clean(input.VerificationMethodCode)?.ToUpperInvariant();visit.VisitVerificationResultCode=verification.ReasonCode;if(verification.OverallStatusCode=="VERIFIED")visit.VisitVerifiedAt=now;visit.WorkCompletedAt=now;visit.ProviderCompletionSubmittedAt=now;visit.CompletionChecklistJson=Clean(input.ChecklistJson);visit.CompletionNote=Clean(input.CompletionNote);visit.StatusCode="PROVIDER_COMPLETED";visit.UpdatedAt=now;visit.UpdatedByUserId=provider.UserId;var order=0;foreach(var file in files)db.SubscriptionVisitFiles.Add(new SubscriptionVisitFile{SubscriptionVisitScheduleId=visit.Id,FileId=file.Id,DisplayOrder=++order,CreatedAt=now,CreatedByUserId=provider.UserId});AddEvent(contract.SubscriptionRequestId,contract.Id,visit.Id,"VISIT_COMPLETION_SUBMITTED",new{fileCount=files.Count,verification=visit.VisitVerificationStatusCode},provider.UserId,input.IdempotencyKey.Trim(),now);Audit(provider.UserId,"VISIT_COMPLETION_SUBMITTED","SUBSCRIPTION_VISIT",visit.PublicId,null,new{visit.StatusCode,fileCount=files.Count,verification=visit.VisitVerificationStatusCode},null,RoleCodes.Provider);await db.SaveChangesAsync(token);return await BuildVisit(visit.Id,token);
    }

    public async Task<SubscriptionVisitResponse> OverrideVisitVerification(Guid id,OverrideSubscriptionVisitVerificationRequest input,Guid actorPublicId,CancellationToken token){if(string.IsNullOrWhiteSpace(input.Reason))throw Bad("VISIT_VERIFICATION_OVERRIDE_REASON_REQUIRED","방문인증 예외승인 사유가 필요합니다.");var actor=await AdminId(actorPublicId,token);var visit=await Visit(id,token);if(visit.StatusCode!="IN_PROGRESS")throw Conflict("VISIT_VERIFICATION_OVERRIDE_INVALID","진행 중인 회차만 예외승인할 수 있습니다.");ApplyVersion(visit,input.RowVersion);var now=DateTime.UtcNow;visit.VisitVerificationStatusCode="OVERRIDE_APPROVED";visit.VerificationOverrideAt=now;visit.VerificationOverrideByUserId=actor;visit.VerificationOverrideReason=input.Reason.Trim();visit.VisitVerifiedAt=now;var contract=await db.SubscriptionContracts.SingleAsync(x=>x.Id==visit.SubscriptionContractId,token);AddEvent(contract.SubscriptionRequestId,contract.Id,visit.Id,"VISIT_VERIFICATION_OVERRIDE_APPROVED",new{reason=input.Reason},actor,input.IdempotencyKey.Trim(),now);Audit(actor,"SUBSCRIPTION_VISIT_VERIFICATION_OVERRIDE_APPROVED","SUBSCRIPTION_VISIT",visit.PublicId,new{Status="NOT_VERIFIED"},new{Status=visit.VisitVerificationStatusCode},input.Reason);await db.SaveChangesAsync(token);return await BuildVisit(visit.Id,token);}

    public async Task<SubscriptionVisitResponse> ConfirmVisit(Guid id,ConfirmSubscriptionVisitRequest input,ClaimsPrincipal principal,CancellationToken token)
    {
        var customer=await Customer(principal,token);var visit=await Visit(id,token);var contract=await db.SubscriptionContracts.SingleAsync(x=>x.Id==visit.SubscriptionContractId,token);if(contract.CustomerProfileId!=customer.ProfileId)throw NotFound("SUBSCRIPTION_VISIT_NOT_FOUND","회차를 찾을 수 없습니다.");if(await db.SubscriptionEvents.AnyAsync(x=>x.IdempotencyKey==input.IdempotencyKey,token))return await BuildVisit(visit.Id,token);if(visit.StatusCode!="PROVIDER_COMPLETED")throw Conflict("PROVIDER_COMPLETION_REQUIRED","공급자 완료보고 후 확인할 수 있습니다.");var now=DateTime.UtcNow;visit.CustomerConfirmedAt=now;visit.StatusCode="COMPLETED";visit.SettlementStatusCode="READY";visit.UpdatedAt=now;visit.UpdatedByUserId=customer.UserId;AddEvent(contract.SubscriptionRequestId,contract.Id,visit.Id,"CUSTOMER_CONFIRMED",null,customer.UserId,input.IdempotencyKey.Trim(),now);await EnsureHistory(contract,visit,customer.UserId,now,token);await db.SaveChangesAsync(token);return await BuildVisit(visit.Id,token);
    }

    public async Task<Guid> CreateReview(Guid visitId,CreateSubscriptionReviewRequest input,ClaimsPrincipal principal,CancellationToken token)
    {var customer=await Customer(principal,token);var pair=await CustomerVisit(visitId,customer.ProfileId,token);if(pair.Visit.StatusCode!="COMPLETED")throw Conflict("SUBSCRIPTION_VISIT_NOT_COMPLETED","완료한 회차만 리뷰를 등록할 수 있습니다.");var old=await db.Reviews.SingleOrDefaultAsync(x=>x.IdempotencyKey==input.IdempotencyKey,token);if(old is not null)return old.PublicId;if(await db.Reviews.AnyAsync(x=>x.SubscriptionVisitScheduleId==pair.Visit.Id,token))throw Conflict("REVIEW_ALREADY_EXISTS","이미 리뷰가 등록된 회차입니다.");if(input.OverallRating is <1 or >5)throw Bad("REVIEW_RATING_INVALID","평점은 1점부터 5점까지 입력해 주세요.");var now=DateTime.UtcNow;var review=new Review{TransactionId=null,SubscriptionVisitScheduleId=pair.Visit.Id,CustomerProfileId=customer.ProfileId,ProviderProfileId=pair.Contract.ProviderProfileId,BodyText=input.BodyText.Trim(),OverallRating=input.OverallRating,VerificationStatusCode="VERIFIED_SUBSCRIPTION_VISIT",VisibilityStatusCode="PUBLIC",IdempotencyKey=input.IdempotencyKey.Trim(),SubmittedAt=now,PublishedAt=now,CreatedAt=now,UpdatedAt=now};db.Reviews.Add(review);await db.SaveChangesAsync(token);return review.PublicId;}

    public async Task<Guid> CreateAfterService(Guid visitId,CreateSubscriptionCaseRequest input,ClaimsPrincipal principal,CancellationToken token)
    {var customer=await Customer(principal,token);var pair=await CustomerVisit(visitId,customer.ProfileId,token);var prior=await db.AfterServiceCases.SingleOrDefaultAsync(x=>x.IdempotencyKey==input.IdempotencyKey,token);if(prior is not null)return prior.PublicId;var now=DateTime.UtcNow;var item=new AfterServiceCase{TransactionId=null,SubscriptionVisitScheduleId=pair.Visit.Id,CustomerProfileId=customer.ProfileId,ProviderProfileId=pair.Contract.ProviderProfileId,ReportedByUserId=customer.UserId,StatusCode="RECEIVED",Subject=input.Subject.Trim(),Description=input.Description.Trim(),ReceivedAt=now,IdempotencyKey=input.IdempotencyKey.Trim(),CreatedAt=now,CreatedByUserId=customer.UserId,UpdatedAt=now,UpdatedByUserId=customer.UserId};db.AfterServiceCases.Add(item);await db.SaveChangesAsync(token);return item.PublicId;}

    public async Task<Guid> CreateDispute(Guid visitId,CreateSubscriptionCaseRequest input,ClaimsPrincipal principal,CancellationToken token)
    {var customer=await Customer(principal,token);var pair=await CustomerVisit(visitId,customer.ProfileId,token);var prior=await db.DisputeActions.Where(x=>x.IdempotencyKey==input.IdempotencyKey).Select(x=>(long?)x.DisputeCaseId).SingleOrDefaultAsync(token);if(prior.HasValue)return await db.DisputeCases.Where(x=>x.Id==prior).Select(x=>x.PublicId).SingleAsync(token);var providerUser=await db.ProviderProfiles.Where(x=>x.Id==pair.Contract.ProviderProfileId).Select(x=>x.UserId).SingleAsync(token);var now=DateTime.UtcNow;var item=new DisputeCase{TransactionId=null,SubscriptionVisitScheduleId=pair.Visit.Id,ApplicantUserId=customer.UserId,CounterpartyUserId=providerUser,Subject=input.Subject.Trim(),Description=input.Description.Trim(),StatusCode="OPEN",ReceivedAt=now,LastActionAt=now,CreatedAt=now,CreatedByUserId=customer.UserId,UpdatedAt=now,UpdatedByUserId=customer.UserId};db.DisputeCases.Add(item);pair.Visit.StatusCode="DISPUTED";pair.Visit.SettlementStatusCode="HOLD";var settlementItem=await db.SubscriptionSettlementItems.SingleOrDefaultAsync(x=>x.SubscriptionVisitScheduleId==pair.Visit.Id,token);if(settlementItem is not null&&settlementItem.StatusCode!="SETTLED"){settlementItem.StatusCode="HOLD";settlementItem.HoldReason="구독 회차 분쟁 접수";settlementItem.UpdatedAt=now;settlementItem.UpdatedByUserId=customer.UserId;}await db.SaveChangesAsync(token);db.DisputeActions.Add(new DisputeAction{DisputeCaseId=item.Id,ActionTypeCode="CREATED",ToStatusCode="OPEN",ActionNote=input.Description.Trim(),OccurredAt=now,ActorUserId=customer.UserId,IdempotencyKey=input.IdempotencyKey.Trim()});await db.SaveChangesAsync(token);return item.PublicId;}

    public Task<List<SubscriptionRequestResponse>> AdminRequests(CancellationToken token)=>BuildRequests(token);
    public async Task<List<AdminSubscriptionApplicationResponse>> AdminApplications(CancellationToken token)=>await(from app in db.SubscriptionApplications.AsNoTracking()join request in db.SubscriptionRequests.AsNoTracking()on app.SubscriptionRequestId equals request.Id join customer in db.CustomerProfiles.AsNoTracking()on request.CustomerProfileId equals customer.Id join service in db.ServiceCategories.AsNoTracking()on request.ServiceCategoryId equals service.Id join provider in db.ProviderProfiles.AsNoTracking()on app.ProviderProfileId equals provider.Id join trust0 in db.ProviderTrustScoreCurrent.AsNoTracking()on provider.Id equals trust0.ProviderProfileId into trusts from trust in trusts.DefaultIfEmpty() orderby app.SubmittedAt descending select new AdminSubscriptionApplicationResponse(app.PublicId,request.PublicId,Number("SR",request.PublicId),customer.DisplayName,service.Name,provider.PublicId,provider.BusinessName,app.ProposedMonthlyAmount,app.ProposedVisitAmount,app.AvailableScheduleText,trust==null?provider.TrustScore:trust.Score,app.StatusCode,app.SubmittedAt)).ToListAsync(token);
    public Task<List<SubscriptionContractResponse>> AdminContracts(CancellationToken token)=>BuildContracts(token);
    public async Task<List<SubscriptionVisitResponse>> AdminVisits(DateOnly? from,DateOnly? to,string? status,CancellationToken token){var query=db.SubscriptionVisitSchedules.AsNoTracking().AsQueryable();if(from.HasValue)query=query.Where(x=>x.ScheduledStartAt>=from.Value.ToDateTime(TimeOnly.MinValue));if(to.HasValue)query=query.Where(x=>x.ScheduledStartAt<to.Value.AddDays(1).ToDateTime(TimeOnly.MinValue));if(!string.IsNullOrWhiteSpace(status))query=query.Where(x=>x.StatusCode==status.ToUpper());var ids=await query.OrderBy(x=>x.ScheduledStartAt).Select(x=>x.Id).ToListAsync(token);var result=new List<SubscriptionVisitResponse>();foreach(var id in ids)result.Add(await BuildVisit(id,token));return result;}
    public async Task<List<SubscriptionScheduleChangeResponse>> AdminScheduleChanges(CancellationToken token){var rows=await db.SubscriptionScheduleChanges.AsNoTracking().OrderByDescending(x=>x.RequestedAt).ToListAsync(token);return rows.Select(MapChange).ToList();}
    public async Task<IReadOnlyList<SubscriptionEventResponse>> Events(Guid contractId,CancellationToken token){var id=await db.SubscriptionContracts.Where(x=>x.PublicId==contractId).Select(x=>(long?)x.Id).SingleOrDefaultAsync(token)??throw NotFound("SUBSCRIPTION_CONTRACT_NOT_FOUND","구독 계약을 찾을 수 없습니다.");return await db.SubscriptionEvents.AsNoTracking().Where(x=>x.SubscriptionContractId==id).OrderByDescending(x=>x.OccurredAt).Select(x=>new SubscriptionEventResponse(x.PublicId,x.EventTypeCode,x.OccurredAt,x.EventDataJson)).ToListAsync(token);}

    private async Task<List<SubscriptionRequestResponse>> BuildRequests(CancellationToken token){var ids=await db.SubscriptionRequests.AsNoTracking().OrderByDescending(x=>x.CreatedAt).Select(x=>x.Id).ToListAsync(token);var result=new List<SubscriptionRequestResponse>();foreach(var id in ids)result.Add(await BuildRequest(id,false,token));return result;}
    private async Task<List<SubscriptionContractResponse>> BuildContracts(CancellationToken token){var ids=await db.SubscriptionContracts.AsNoTracking().OrderByDescending(x=>x.CreatedAt).Select(x=>x.Id).ToListAsync(token);var result=new List<SubscriptionContractResponse>();foreach(var id in ids)result.Add(await BuildContract(id,token));return result;}
    private async Task<SubscriptionRequestResponse> BuildRequest(long id,bool includeOwner,CancellationToken token){var row=await(from item in db.SubscriptionRequests.AsNoTracking()join customer in db.CustomerProfiles.AsNoTracking()on item.CustomerProfileId equals customer.Id join category in db.ServiceCategories.AsNoTracking()on item.ServiceCategoryId equals category.Id join area in db.AdministrativeAreas.AsNoTracking()on item.AdministrativeAreaId equals area.Id join rule in db.SubscriptionRecurrenceRules.AsNoTracking()on item.Id equals rule.SubscriptionRequestId where item.Id==id select new{item,customer,category,area,rule}).SingleAsync(token);return new(row.item.PublicId,Number("SR",row.item.PublicId),row.customer.PublicId,row.customer.DisplayName,row.category.PublicId,row.category.Name,row.item.CareProductId.HasValue?await db.CareProducts.Where(x=>x.Id==row.item.CareProductId).Select(x=>(Guid?)x.PublicId).SingleAsync(token):null,row.item.RequestTypeCode,row.item.RequestedScopeText,row.item.PreferredStartDate,row.area.PublicId,row.area.AreaName,row.item.StatusCode,await db.SubscriptionApplications.CountAsync(x=>x.SubscriptionRequestId==id,token),row.item.SelectedApplicationId.HasValue,MapRule(row.rule),Version(row.item.RowVersion));}
    private async Task<SubscriptionApplicationResponse> MapApplication(SubscriptionApplication item,CancellationToken token){var provider=await db.ProviderProfiles.AsNoTracking().SingleAsync(x=>x.Id==item.ProviderProfileId,token);var trust=await db.ProviderTrustScoreCurrent.AsNoTracking().Where(x=>x.ProviderProfileId==provider.Id).Select(x=>x.Score).SingleOrDefaultAsync(token)??provider.TrustScore;return new(item.PublicId,provider.PublicId,provider.BusinessName,item.ProposedScopeText,item.ProposedMonthlyAmount,item.ProposedVisitAmount,item.AvailableScheduleText,trust,item.StatusCode,item.SubmittedAt,Version(item.RowVersion));}
    private async Task<SubscriptionContractResponse> BuildContract(long id,CancellationToken token){var row=await(from item in db.SubscriptionContracts.AsNoTracking()join request in db.SubscriptionRequests.AsNoTracking()on item.SubscriptionRequestId equals request.Id join customer in db.CustomerProfiles.AsNoTracking()on item.CustomerProfileId equals customer.Id join provider in db.ProviderProfiles.AsNoTracking()on item.ProviderProfileId equals provider.Id join category in db.ServiceCategories.AsNoTracking()on item.ServiceCategoryId equals category.Id join app in db.SubscriptionApplications.AsNoTracking()on item.SubscriptionApplicationId equals app.Id where item.Id==id select new{item,request,customer,provider,category,app}).SingleAsync(token);var next=await db.SubscriptionVisitSchedules.AsNoTracking().Where(x=>x.SubscriptionContractId==id&&x.ScheduledStartAt>=DateTime.UtcNow&&x.StatusCode!="CANCELLED"&&x.StatusCode!="SKIPPED").OrderBy(x=>x.ScheduledStartAt).Select(x=>(DateTime?)x.ScheduledStartAt).FirstOrDefaultAsync(token);return new(row.item.PublicId,Number("SC",row.item.PublicId),row.request.PublicId,row.customer.DisplayName,row.provider.BusinessName,row.category.Name,row.item.StatusCode,row.item.StartedAt,row.item.EndedAt,row.item.PauseStartedAt,row.item.ResumePlannedAt,row.item.TerminationRequestedAt,row.item.TerminatedAt,row.app.ProposedMonthlyAmount,row.app.ProposedVisitAmount,row.item.CurrencyCode,next,row.item.PriceSnapshotJson,row.item.FeePolicySnapshotJson,row.item.ServiceScopeSnapshotJson,row.item.RecurrenceSnapshotJson,row.item.ProviderTrustScoreSnapshot,Version(row.item.RowVersion));}
    private async Task<SubscriptionVisitResponse> BuildVisit(long id,CancellationToken token){var row=await(from visit in db.SubscriptionVisitSchedules.AsNoTracking()join contract in db.SubscriptionContracts.AsNoTracking()on visit.SubscriptionContractId equals contract.Id join provider in db.ProviderProfiles.AsNoTracking()on visit.ProviderProfileId equals provider.Id where visit.Id==id select new{visit,contract,provider}).SingleAsync(token);return new(row.visit.PublicId,row.contract.PublicId,Number("SC",row.contract.PublicId),row.visit.VisitNo,row.provider.PublicId,row.provider.BusinessName,row.visit.ScheduledStartAt,row.visit.ScheduledEndAt,row.visit.StatusCode,row.visit.VisitVerifiedAt,row.visit.VisitVerificationMethodCode,row.visit.ProviderCompletionSubmittedAt,row.visit.CustomerConfirmedAt,row.visit.SettlementStatusCode,Version(row.visit.RowVersion));}
    private SubscriptionScheduleChangeResponse MapChange(SubscriptionScheduleChange x){var old=JsonSerializer.Deserialize<ScheduleValue>(x.OldScheduleJson)!;var next=JsonSerializer.Deserialize<ScheduleValue>(x.NewScheduleJson)!;var visitId=db.SubscriptionVisitSchedules.Where(v=>v.Id==x.SubscriptionVisitScheduleId).Select(v=>v.PublicId).Single();return new(x.PublicId,visitId,old.start,old.end,next.start,next.end,x.Reason,x.StatusCode,x.RequestedAt,x.DecidedAt,Version(x.RowVersion));}

    private async Task GenerateVisits(SubscriptionContract contract,SubscriptionRecurrenceRule rule,long actor,DateTime now,CancellationToken token,bool replacePaused=false){var existing=await db.SubscriptionVisitSchedules.Where(x=>x.SubscriptionContractId==contract.Id).ToListAsync(token);if(replacePaused){foreach(var old in existing.Where(x=>x.ScheduledStartAt>=now&&x.StatusCode=="PAUSED"))old.StatusCode="CANCELLED";}var maxNo=existing.Count==0?0:existing.Max(x=>x.VisitNo);var last=existing.Where(x=>x.StatusCode!="CANCELLED").OrderByDescending(x=>x.ScheduledStartAt).FirstOrDefault()?.ScheduledStartAt;var end=DateOnly.FromDateTime(now.AddDays(RollingWindowDays));if(rule.EndDate.HasValue&&rule.EndDate<end)end=rule.EndDate.Value;foreach(var date in Occurrences(rule,last.HasValue?DateOnly.FromDateTime(last.Value).AddDays(1):rule.StartDate,end)){var start=date.ToDateTime(rule.PreferredTimeFrom);if(start<now)continue;var visit=new SubscriptionVisitSchedule{SubscriptionContractId=contract.Id,VisitNo=++maxNo,ProviderProfileId=contract.ProviderProfileId,ScheduledStartAt=start,ScheduledEndAt=start.AddMinutes(rule.ExpectedDurationMinutes),StatusCode="SCHEDULED",SettlementStatusCode="NOT_READY",CreatedAt=now,CreatedByUserId=actor,UpdatedAt=now,UpdatedByUserId=actor};db.SubscriptionVisitSchedules.Add(visit);await db.SaveChangesAsync(token);AddEvent(contract.SubscriptionRequestId,contract.Id,visit.Id,"VISIT_CREATED",new{visit.VisitNo,visit.ScheduledStartAt},actor,$"subscription-visit:{contract.PublicId:N}:{visit.VisitNo}:created",now);}}
    private static IEnumerable<DateOnly> Occurrences(SubscriptionRecurrenceRule rule,DateOnly from,DateOnly to){if(rule.FrequencyTypeCode is "WEEKLY" or "BIWEEKLY"){var days=ParseWeekdays(rule.WeekdaysJson);if(days.Count==0)days=[(int)rule.StartDate.DayOfWeek];for(var d=from;d<=to;d=d.AddDays(1)){var weeks=(d.DayNumber-rule.StartDate.DayNumber)/7;if(d>=rule.StartDate&&weeks%(rule.FrequencyTypeCode=="BIWEEKLY"?2*rule.IntervalValue:rule.IntervalValue)==0&&days.Contains((int)d.DayOfWeek))yield return d;}yield break;}var months=rule.FrequencyTypeCode switch{"MONTHLY"=>rule.IntervalValue,"QUARTERLY"=>3*rule.IntervalValue,"HALF_YEARLY"=>6*rule.IntervalValue,_=>1};for(var d=rule.StartDate;d<=to;d=d.AddMonths(months))if(d>=from)yield return d;}
    private static List<int> ParseWeekdays(string? json){try{return string.IsNullOrWhiteSpace(json)?[]:JsonSerializer.Deserialize<List<int>>(json)??[];}catch{return [];}}
    private static SubscriptionRecurrenceRule NewRule(long requestId,RecurrenceRuleRequest input,long actor,DateTime now)=>new(){SubscriptionRequestId=requestId,FrequencyTypeCode=Code(input.FrequencyTypeCode),IntervalValue=input.IntervalValue,VisitsPerPeriod=input.VisitsPerPeriod,WeekdaysJson=input.Weekdays is null?null:JsonSerializer.Serialize(input.Weekdays.Distinct().Order()),PreferredTimeFrom=input.PreferredTimeFrom,PreferredTimeTo=input.PreferredTimeTo,ExpectedDurationMinutes=input.ExpectedDurationMinutes,StartDate=input.StartDate,EndDate=input.EndDate,CreatedAt=now,CreatedByUserId=actor,UpdatedAt=now,UpdatedByUserId=actor};
    private static void ValidateRecurrence(RecurrenceRuleRequest x){var code=Code(x.FrequencyTypeCode);if(!Frequencies.Contains(code))throw Bad("RECURRENCE_FREQUENCY_INVALID","반복주기를 확인해 주세요.");if(x.IntervalValue<1||x.ExpectedDurationMinutes<1||x.EndDate<x.StartDate)throw Bad("RECURRENCE_RULE_INVALID","반복규칙을 확인해 주세요.");if(x.Weekdays?.Any(d=>d<0||d>6)==true)throw Bad("RECURRENCE_WEEKDAY_INVALID","요일 값은 0부터 6까지 입력해 주세요.");if(x.PreferredTimeTo.HasValue&&x.PreferredTimeTo<=x.PreferredTimeFrom)throw Bad("RECURRENCE_TIME_INVALID","희망시간 범위를 확인해 주세요.");}
    private static void ValidateAmounts(decimal? monthly,decimal? visit){if(monthly<0||visit<0)throw Bad("SUBSCRIPTION_AMOUNT_INVALID","금액은 0원 이상이어야 합니다.");if(!monthly.HasValue&&!visit.HasValue)throw Bad("SUBSCRIPTION_AMOUNT_REQUIRED","월 금액 또는 회차 금액을 입력해 주세요.");}
    private async Task<ServiceCategory> EligibleCategory(Guid id,CancellationToken token){var today=DateOnly.FromDateTime(DateTime.UtcNow);return await db.ServiceCategories.SingleOrDefaultAsync(x=>x.PublicId==id&&x.LevelCode=="SERVICE"&&x.StatusCode=="ACTIVE"&&db.CategoryOperationPolicies.Any(p=>p.CategoryId==x.Id&&p.IsActive&&p.EffectiveFrom<=today&&(p.EffectiveTo==null||p.EffectiveTo>today)&&p.SubscriptionOptionText=="허용"),token)??throw NotFound("SUBSCRIPTION_SERVICE_NOT_FOUND","정기구독 대상 서비스를 찾을 수 없습니다.");}
    private async Task<SubscriptionContract> Contract(Guid id,CancellationToken token)=>await db.SubscriptionContracts.SingleOrDefaultAsync(x=>x.PublicId==id,token)??throw NotFound("SUBSCRIPTION_CONTRACT_NOT_FOUND","구독 계약을 찾을 수 없습니다.");
    private async Task<SubscriptionVisitSchedule> Visit(Guid id,CancellationToken token)=>await db.SubscriptionVisitSchedules.SingleOrDefaultAsync(x=>x.PublicId==id,token)??throw NotFound("SUBSCRIPTION_VISIT_NOT_FOUND","구독 회차를 찾을 수 없습니다.");
    private Task<List<SubscriptionVisitSchedule>> FutureVisits(long contractId,DateTime now,CancellationToken token)=>db.SubscriptionVisitSchedules.Where(x=>x.SubscriptionContractId==contractId&&x.ScheduledStartAt>=now&&x.StatusCode!="COMPLETED"&&x.StatusCode!="CANCELLED").ToListAsync(token);
    private async Task<(SubscriptionVisitSchedule Visit,SubscriptionContract Contract)> CustomerVisit(Guid id,long customerId,CancellationToken token){var row=await(from visit in db.SubscriptionVisitSchedules join contract in db.SubscriptionContracts on visit.SubscriptionContractId equals contract.Id where visit.PublicId==id&&contract.CustomerProfileId==customerId select new{visit,contract}).SingleOrDefaultAsync(token)??throw NotFound("SUBSCRIPTION_VISIT_NOT_FOUND","구독 회차를 찾을 수 없습니다.");return(row.visit,row.contract);}
    private async Task<List<StoredFile>> ResolveFiles(IReadOnlyList<Guid>? ids,long userId,CancellationToken token){if(ids is null||ids.Count==0)return[];var values=await db.Files.Where(x=>ids.Contains(x.PublicId)&&x.UploadedByUserId==userId&&x.StatusCode=="ACTIVE"&&(x.PurposeCode=="SUBSCRIPTION_COMPLETION"||x.PurposeCode=="COMPLETION_EVIDENCE")).ToListAsync(token);if(values.Count!=ids.Distinct().Count())throw Bad("SUBSCRIPTION_COMPLETION_FILE_INVALID","본인이 등록한 사용 가능한 완료 파일만 연결할 수 있습니다.");return values;}
    private async Task EnsureHistory(SubscriptionContract contract,SubscriptionVisitSchedule visit,long actor,DateTime now,CancellationToken token){var key=$"subscription-visit:{visit.PublicId:N}:completed";if(await db.ServiceHistoryEntries.AnyAsync(x=>x.IdempotencyKey==key,token))return;var customer=await db.CustomerProfiles.SingleAsync(x=>x.Id==contract.CustomerProfileId,token);var provider=await db.ProviderProfiles.SingleAsync(x=>x.Id==contract.ProviderProfileId,token);var category=await db.ServiceCategories.SingleAsync(x=>x.Id==contract.ServiceCategoryId,token);db.ServiceHistoryEntries.Add(new ServiceHistoryEntry{CustomerProfileId=customer.Id,SubscriptionVisitScheduleId=visit.Id,EventTypeCode="SUBSCRIPTION_VISIT_COMPLETED",Title=$"{category.Name} 정기 방문 완료",Summary=visit.CompletionNote??"고객이 정기구독 회차 완료를 확인했습니다.",ProviderNameSnapshot=provider.BusinessName,CategoryNameSnapshot=category.Name,CompletedAtSnapshot=visit.CustomerConfirmedAt,SnapshotJson=JsonSerializer.Serialize(new{contractId=contract.PublicId,visitId=visit.PublicId,visit.VisitNo}),OccurredAt=now,IdempotencyKey=key,CreatedAt=now,CreatedByUserId=actor});}
    private async Task<SubscriptionScheduleChangeResponse> DecideScheduleChangeCore(SubscriptionScheduleChange item,SubscriptionVisitSchedule visit,SubscriptionContract contract,bool approve,string idempotencyKey,string? rowVersion,long actor,bool forced,string? reason,string actorRole,CancellationToken token){if(await db.SubscriptionEvents.AnyAsync(x=>x.IdempotencyKey==idempotencyKey,token))return MapChange(item);if(item.StatusCode!="REQUESTED")throw Conflict("SCHEDULE_CHANGE_ALREADY_DECIDED","이미 처리된 일정 변경입니다.");ApplyVersion(item,rowVersion);var now=DateTime.UtcNow;item.StatusCode=approve?"APPROVED":"REJECTED";item.DecidedAt=now;item.DecidedByUserId=actor;item.UpdatedAt=now;if(approve){var value=JsonSerializer.Deserialize<ScheduleValue>(item.NewScheduleJson)!;visit.ScheduledStartAt=value.start;visit.ScheduledEndAt=value.end;visit.StatusCode="RESCHEDULED";visit.UpdatedAt=now;visit.UpdatedByUserId=actor;}var type=forced?(approve?"SCHEDULE_CHANGE_FORCE_APPROVED":"SCHEDULE_CHANGE_FORCE_REJECTED"):(approve?"SCHEDULE_CHANGE_APPROVED":"SCHEDULE_CHANGE_REJECTED");AddEvent(contract.SubscriptionRequestId,contract.Id,visit.Id,type,new{item.PublicId,forced,reason},actor,idempotencyKey.Trim(),now);Audit(actor,type,"SUBSCRIPTION_SCHEDULE_CHANGE",item.PublicId,null,new{item.StatusCode},reason,actorRole);await db.SaveChangesAsync(token);return MapChange(item);}
    private static CompletionPolicyValue CompletionPolicy(string json){try{using var document=JsonDocument.Parse(json);var root=document.RootElement;return new(root.TryGetProperty("requiredPhotoCount",out var photos)?photos.GetInt32():0,root.TryGetProperty("requiresChecklist",out var checklist)&&checklist.GetBoolean(),root.TryGetProperty("requiresVisitVerification",out var verification)&&verification.GetBoolean());}catch{return new(0,false,false);}}
    private void ApplyVersion(object entity,string? value){if(!string.IsNullOrWhiteSpace(value))db.Entry(entity).Property("RowVersion").OriginalValue=Convert.FromBase64String(value);}
    private void Audit(long actor,string action,string entity,Guid id,object? before,object? after,string? reason=null,string actorRole=RoleCodes.Admin)=>db.AuditLogs.Add(new AuditLog{OccurredAt=DateTime.UtcNow,ActorUserId=actor,ActorRoleCode=actorRole,ActionCode=action,EntityType=entity,EntityPublicId=id,ResultCode="SUCCESS",Reason=reason,BeforeJson=before is null?null:JsonSerializer.Serialize(before),AfterJson=after is null?null:JsonSerializer.Serialize(after)});
    private void AddEvent(long? request,long? contract,long? visit,string type,object? data,long? actor,string key,DateTime now){if(db.SubscriptionEvents.Local.Any(x=>x.IdempotencyKey==key))return;db.SubscriptionEvents.Add(new SubscriptionEvent{SubscriptionRequestId=request,SubscriptionContractId=contract,SubscriptionVisitScheduleId=visit,EventTypeCode=type,EventDataJson=data is null?null:JsonSerializer.Serialize(data),OccurredAt=now,ActorUserId=actor,IdempotencyKey=key});}
    private async Task<long> AdminId(Guid id,CancellationToken token)=>await(from user in db.Users join link in db.UserRoles on user.Id equals link.UserId join role in db.Roles on link.RoleId equals role.Id where user.PublicId==id&&user.StatusCode=="ACTIVE"&&link.RevokedAt==null&&role.Code==RoleCodes.Admin select(long?)user.Id).SingleOrDefaultAsync(token)??throw Forbidden("ADMIN_REQUIRED","관리자 계정을 확인할 수 없습니다.");
    private async Task<Identity> Customer(ClaimsPrincipal p,CancellationToken token){var user=await IdentityUser(p,token);var id=await db.CustomerProfiles.Where(x=>x.UserId==user.Id).Select(x=>(long?)x.Id).SingleOrDefaultAsync(token)??throw Forbidden("CUSTOMER_PROFILE_REQUIRED","고객 프로필이 필요합니다.");return new(user.Id,id,user.PublicId);}
    private async Task<Identity> Provider(ClaimsPrincipal p,CancellationToken token){var user=await IdentityUser(p,token);var id=await db.ProviderProfiles.Where(x=>x.UserId==user.Id).Select(x=>(long?)x.Id).SingleOrDefaultAsync(token)??throw Forbidden("PROVIDER_PROFILE_REQUIRED","공급자 프로필이 필요합니다.");return new(user.Id,id,user.PublicId);}
    private async Task<long> UserId(ClaimsPrincipal p,CancellationToken token)=>(await IdentityUser(p,token)).Id;
    private async Task<User> IdentityUser(ClaimsPrincipal p,CancellationToken token){if(!Guid.TryParse(p.FindFirstValue(ClaimTypes.NameIdentifier),out var id))throw Forbidden("AUTHENTICATED_USER_REQUIRED","로그인이 필요합니다.");return await db.Users.SingleOrDefaultAsync(x=>x.PublicId==id&&x.StatusCode=="ACTIVE",token)??throw Forbidden("ACTIVE_USER_REQUIRED","활성 계정을 확인할 수 없습니다.");}
    private static CareProductResponse MapProduct(CareProduct x,Guid categoryId,string service)=>new(x.PublicId,categoryId,service,x.ProductName,x.Description,x.ServiceScopeText,x.VisitsPerPeriod,x.ExpectedDurationMinutes,x.BillingPeriodCode,x.StandardMonthlyAmount,x.StandardVisitAmount,x.IsActive,x.EffectiveFrom,x.EffectiveTo,Version(x.RowVersion));
    private static SubscriptionRecurrenceResponse MapRule(SubscriptionRecurrenceRule x)=>new(x.FrequencyTypeCode,x.IntervalValue,x.VisitsPerPeriod,ParseWeekdays(x.WeekdaysJson),x.PreferredTimeFrom,x.PreferredTimeTo,x.ExpectedDurationMinutes,x.StartDate,x.EndDate);
    private static string RecurrenceJson(SubscriptionRecurrenceRule x)=>JsonSerializer.Serialize(MapRule(x));
    private static string EligibilityMessage(string? code)=>code switch{"PROVIDER_USER_OR_ROLE_INACTIVE"=>"활성 공급자 계정만 신청할 수 있습니다.","PROVIDER_NOT_APPROVED_ACTIVE"=>"전체 승인된 활동 공급자만 신청할 수 있습니다.","SERVICE_CATEGORY_MISMATCH"=>"등록한 서비스가 아닙니다.","SERVICE_NOT_APPROVED"=>"서비스별 승인이 완료되지 않았습니다.","SERVICE_AREA_MISMATCH"=>"활동지역이 요청지역과 일치하지 않습니다.","STRUCTURED_REQUIREMENTS_NOT_CONFIGURED"=>"구조화 공급자 요건이 설정되지 않았습니다.","REQUIRED_EVIDENCE_INVALID"=>"필수 요건 또는 증빙 검증이 완료되지 않았습니다.",_=>"구독 요청에 신청할 수 없습니다."};
    private static string Number(string prefix,Guid id)=>$"{prefix}-{id:N}"[..Math.Min(prefix.Length+1+12,prefix.Length+1+32)].ToUpperInvariant();
    private static string Version(byte[] value)=>value.Length==0?string.Empty:Convert.ToBase64String(value);
    private static string Code(string value)=>value.Trim().ToUpperInvariant();private static string? Clean(string? value)=>string.IsNullOrWhiteSpace(value)?null:value.Trim();
    private static SubscriptionBusinessException Bad(string code,string message)=>new(400,code,message);private static SubscriptionBusinessException Forbidden(string code,string message)=>new(403,code,message);private static SubscriptionBusinessException NotFound(string code,string message)=>new(404,code,message);private static SubscriptionBusinessException Conflict(string code,string message)=>new(409,code,message);
    private sealed record Identity(long UserId,long ProfileId,Guid PublicId);private sealed record ScheduleValue(DateTime start,DateTime? end);private sealed record CompletionPolicyValue(int RequiredPhotoCount,bool RequiresChecklist,bool RequiresVisitVerification);
}
