using System.Text.Json;
using System.Text.RegularExpressions;
using Microsoft.AspNetCore.Http;
using Microsoft.EntityFrameworkCore;
using SoodalLife.Api.Domain.Entities;
using SoodalLife.Api.Features.Authentication;
using SoodalLife.Api.Infrastructure.Persistence;

namespace SoodalLife.Api.Features.Subscriptions;

public sealed class SubscriptionBillingService(
    SoodalLifeDbContext db,
    IWebHostEnvironment environment,
    ISubscriptionSettlementFeeCalculator feeCalculator,
    ISubscriptionPaymentTokenProtector? tokenProtector=null,
    CareSubscriptionService? careService=null,
    SubscriptionPaymentProcessor? paymentProcessor=null)
{
    private bool SimulationAvailable=>environment.IsDevelopment()||environment.IsEnvironment("Testing");

    public async Task<SubscriptionAccountingDashboard> Dashboard(CancellationToken token)=>new(
        await db.SubscriptionPaymentRequests.CountAsync(token),
        await db.SubscriptionPaymentRequests.CountAsync(x=>x.StatusCode=="FAILED",token),
        await db.SubscriptionSettlementItems.CountAsync(x=>x.StatusCode=="READY",token),
        await db.SubscriptionSettlementItems.CountAsync(x=>x.StatusCode=="POLICY_PENDING"||x.StatusCode=="CALCULATION_PENDING",token),
        await db.MonthlySettlements.CountAsync(token),
        await db.SubscriptionPayouts.CountAsync(x=>x.StatusCode!="COMPLETED"&&x.StatusCode!="CANCELLED"&&x.StatusCode!="FAILED",token),
        await db.SubscriptionRefundAdjustments.CountAsync(x=>x.StatusCode!="COMPLETED"&&x.StatusCode!="CANCELLED"&&x.StatusCode!="REJECTED"&&x.StatusCode!="FAILED",token),
        SimulationAvailable);

    public async Task<List<SubscriptionPaymentMethodResponse>> PaymentMethods(CancellationToken token)=>await(
        from method in db.SubscriptionPaymentMethods.AsNoTracking()
        join customer in db.CustomerProfiles.AsNoTracking() on method.CustomerProfileId equals customer.Id
        orderby method.RegisteredAt descending
        select new SubscriptionPaymentMethodResponse(method.PublicId,customer.PublicId,customer.DisplayName,method.PaymentMethodTypeCode,method.ProviderCode,method.MaskedDisplayText,method.StatusCode,method.IsDefault,method.RegisteredAt,Version(method.RowVersion))).ToListAsync(token);

    public async Task<SubscriptionPaymentMethodResponse> RegisterPaymentMethod(RegisterSubscriptionPaymentMethodRequest input,Guid actorPublicId,CancellationToken token)
    {
        ValidatePaymentMethod(input);
        var actor=await AdminId(actorPublicId,token);
        var customer=await db.CustomerProfiles.SingleOrDefaultAsync(x=>x.PublicId==input.CustomerId,token)??throw NotFound("SUBSCRIPTION_CUSTOMER_NOT_FOUND","고객을 찾을 수 없습니다.");
        if(input.IsDefault)
        {
            var defaults=await db.SubscriptionPaymentMethods.Where(x=>x.CustomerProfileId==customer.Id&&x.IsDefault).ToListAsync(token);
            foreach(var item in defaults)item.IsDefault=false;
        }
        var now=DateTime.UtcNow;
        var rawToken=Trim(input.ExternalTokenReference);var protectedToken=rawToken is null?null:(tokenProtector??throw new InvalidOperationException("결제 토큰 보호기가 등록되지 않았습니다.")).Protect(rawToken);var method=new SubscriptionPaymentMethod{CustomerProfileId=customer.Id,ProviderCode=Trim(input.ProviderCode),PaymentMethodTypeCode=input.PaymentMethodTypeCode.Trim().ToUpperInvariant(),ExternalTokenReference=protectedToken,MaskedDisplayText=Trim(input.MaskedDisplayText),StatusCode="ACTIVE",IsDefault=input.IsDefault,RegisteredAt=now,CreatedAt=now,CreatedByUserId=actor,UpdatedAt=now,UpdatedByUserId=actor};
        db.SubscriptionPaymentMethods.Add(method); Audit(actor,"SUBSCRIPTION_PAYMENT_METHOD_REGISTERED","SUBSCRIPTION_PAYMENT_METHOD",method.PublicId,null,new{method.PaymentMethodTypeCode,method.ProviderCode,method.MaskedDisplayText}); await db.SaveChangesAsync(token);
        return new(method.PublicId,customer.PublicId,customer.DisplayName,method.PaymentMethodTypeCode,method.ProviderCode,method.MaskedDisplayText,method.StatusCode,method.IsDefault,method.RegisteredAt,Version(method.RowVersion));
    }

    public async Task<List<SubscriptionPaymentResponse>> Payments(CancellationToken token)=>await PaymentQuery().ToListAsync(token);

    public async Task<SubscriptionPaymentResponse> CreatePayment(CreateSubscriptionPaymentRequest input,Guid actorPublicId,CancellationToken token)
    {
        RequiredKey(input.IdempotencyKey); if(input.RequestedAmount<=0||input.RequestedAmount!=decimal.Truncate(input.RequestedAmount))throw Bad("SUBSCRIPTION_PAYMENT_AMOUNT_INVALID","결제 요청 금액은 1원 단위의 양의 정수여야 합니다."); if(input.BillingPeriodEnd<input.BillingPeriodStart)throw Bad("SUBSCRIPTION_BILLING_PERIOD_INVALID","청구기간을 확인해 주세요.");
        var existing=await db.SubscriptionPaymentRequests.AsNoTracking().SingleOrDefaultAsync(x=>x.IdempotencyKey==input.IdempotencyKey.Trim(),token); if(existing is not null)return await Payment(existing.PublicId,token);
        var actor=await AdminId(actorPublicId,token); var contract=await db.SubscriptionContracts.SingleOrDefaultAsync(x=>x.PublicId==input.ContractId,token)??throw NotFound("SUBSCRIPTION_CONTRACT_NOT_FOUND","구독 계약을 찾을 수 없습니다.");
        SubscriptionPaymentMethod? method=null;
        if(input.PaymentMethodId.HasValue){method=await db.SubscriptionPaymentMethods.SingleOrDefaultAsync(x=>x.PublicId==input.PaymentMethodId&&x.CustomerProfileId==contract.CustomerProfileId,token)??throw Bad("SUBSCRIPTION_PAYMENT_METHOD_INVALID","고객의 결제수단을 확인해 주세요.");if(method.StatusCode!="ACTIVE")throw Conflict("SUBSCRIPTION_PAYMENT_METHOD_DISABLED","사용 중인 결제수단만 선택할 수 있습니다.");}
        var now=DateTime.UtcNow; var request=new SubscriptionPaymentRequest{SubscriptionContractId=contract.Id,CustomerProfileId=contract.CustomerProfileId,PaymentMethodId=method?.Id,BillingPeriodStart=input.BillingPeriodStart,BillingPeriodEnd=input.BillingPeriodEnd,RequestedAmount=input.RequestedAmount,CurrencyCode=contract.CurrencyCode,StatusCode="REQUESTED",RequestedAt=now,IdempotencyKey=input.IdempotencyKey.Trim(),CreatedAt=now,CreatedByUserId=actor,UpdatedAt=now,UpdatedByUserId=actor};
        db.SubscriptionPaymentRequests.Add(request); Audit(actor,"SUBSCRIPTION_PAYMENT_REQUESTED","SUBSCRIPTION_PAYMENT_REQUEST",request.PublicId,null,new{input.RequestedAmount,input.BillingPeriodStart,input.BillingPeriodEnd}); await db.SaveChangesAsync(token); return await Payment(request.PublicId,token);
    }

    public async Task<SubscriptionPaymentResponse> ConfirmPayment(Guid id,DevelopmentPaymentConfirmationRequest input,Guid actorPublicId,CancellationToken token)
    {
        EnsureSimulation("SUBSCRIPTION_PAYMENT_CONFIRMATION_DISABLED","개발용 결제 성공 확인은 운영환경에서 사용할 수 없습니다."); RequiredKey(input.IdempotencyKey); var actor=await AdminId(actorPublicId,token);
        var request=await db.SubscriptionPaymentRequests.SingleOrDefaultAsync(x=>x.PublicId==id,token)??throw NotFound("SUBSCRIPTION_PAYMENT_NOT_FOUND","결제 요청을 찾을 수 없습니다.");
        var prior=await db.SubscriptionPaymentLedger.AsNoTracking().AnyAsync(x=>x.IdempotencyKey==input.IdempotencyKey.Trim(),token); if(prior)return await Payment(id,token);
        EnsureVersion(request.RowVersion,input.RowVersion); if(request.StatusCode=="COMPLETED")return await Payment(id,token); if(request.StatusCode is not ("REQUESTED" or "PROCESSING"))throw Conflict("SUBSCRIPTION_PAYMENT_STATE_INVALID","결제 대기 상태에서만 성공 확인할 수 있습니다.");
        var now=DateTime.UtcNow; request.StatusCode="COMPLETED";request.AuthorizedAt=now;request.CompletedAt=now;request.ExternalPaymentReference=Trim(input.ExternalPaymentReference);request.UpdatedAt=now;request.UpdatedByUserId=actor;
        db.SubscriptionPaymentLedger.Add(new SubscriptionPaymentLedgerEntry{SubscriptionContractId=request.SubscriptionContractId,PaymentRequestId=request.Id,EntryTypeCode="PAYMENT",Amount=request.RequestedAmount,CurrencyCode=request.CurrencyCode,ReferenceType="PAYMENT_REQUEST",ReferencePublicId=request.PublicId,OccurredAt=now,ProcessedByUserId=actor,IdempotencyKey=input.IdempotencyKey.Trim(),CreatedAt=now});
        var contract=await db.SubscriptionContracts.SingleAsync(x=>x.Id==request.SubscriptionContractId,token);var recoveringOverdue=contract.BillingStatusCode=="OVERDUE";
        contract.BillingStatusCode="ACTIVE";contract.NextBillingAt=request.BillingPeriodEnd.AddDays(1).ToDateTime(TimeOnly.MinValue,DateTimeKind.Utc);contract.UpdatedAt=now;contract.UpdatedByUserId=actor;
        if(recoveringOverdue&&contract.StatusCode=="PAUSED"){contract.StatusCode="ACTIVE";contract.PauseStartedAt=null;foreach(var visit in await db.SubscriptionVisitSchedules.Where(x=>x.SubscriptionContractId==contract.Id&&x.ScheduledStartAt>=now&&x.StatusCode=="PAUSED").ToListAsync(token))visit.StatusCode="SCHEDULED";}
        Audit(actor,"SUBSCRIPTION_PAYMENT_CONFIRMED","SUBSCRIPTION_PAYMENT_REQUEST",request.PublicId,new{Status="REQUESTED"},new{Status="COMPLETED",request.RequestedAmount}); await db.SaveChangesAsync(token);
        if(careService is not null)await careService.ActivateAfterPayment(request.SubscriptionContractId,actor,now,token);
        return await Payment(id,token);
    }

    public async Task<SubscriptionPaymentResponse> FailPayment(Guid id,PaymentStateRequest input,Guid actorPublicId,CancellationToken token)
    {
        RequiredKey(input.IdempotencyKey);var actor=await AdminId(actorPublicId,token);var request=await db.SubscriptionPaymentRequests.SingleOrDefaultAsync(x=>x.PublicId==id,token)??throw NotFound("SUBSCRIPTION_PAYMENT_NOT_FOUND","결제 요청을 찾을 수 없습니다.");EnsureVersion(request.RowVersion,input.RowVersion);if(request.StatusCode is not("REQUESTED" or "PROCESSING"))throw Conflict("SUBSCRIPTION_PAYMENT_STATE_INVALID","결제 요청 또는 처리 중 상태에서만 실패 처리할 수 있습니다.");
        var now=DateTime.UtcNow;request.StatusCode="FAILED";request.FailedAt=now;request.FailureCode="PAYMENT_FAILED";request.FailureReason=input.Reason.Trim();request.UpdatedAt=now;request.UpdatedByUserId=actor;
        var contract=await db.SubscriptionContracts.SingleAsync(x=>x.Id==request.SubscriptionContractId,token);contract.BillingStatusCode="OVERDUE";contract.UpdatedAt=now;contract.UpdatedByUserId=actor;
        if(contract.StatusCode=="ACTIVE"){contract.StatusCode="PAUSED";contract.PauseStartedAt=now;foreach(var visit in await db.SubscriptionVisitSchedules.Where(x=>x.SubscriptionContractId==contract.Id&&x.ScheduledStartAt>=now&&x.StatusCode=="SCHEDULED").ToListAsync(token))visit.StatusCode="PAUSED";}
        Audit(actor,"SUBSCRIPTION_PAYMENT_FAILED","SUBSCRIPTION_PAYMENT_REQUEST",request.PublicId,null,new{request.FailureCode,request.FailureReason});await db.SaveChangesAsync(token);return await Payment(id,token);
    }

    public async Task<int> GenerateRecurringPaymentRequests(CancellationToken token)
    {
        var now=DateTime.UtcNow;var created=0;
        var staleIds=await db.SubscriptionPaymentRequests.AsNoTracking().Where(x=>x.StatusCode=="PROCESSING"&&x.AuthorizedAt<=now.AddMinutes(-10)).Select(x=>x.PublicId).ToListAsync(token);if(paymentProcessor is not null)foreach(var id in staleIds)await paymentProcessor.ReconcileByOrderIdAsync(id,token);var stale=await db.SubscriptionPaymentRequests.Where(x=>x.StatusCode=="PROCESSING"&&x.AuthorizedAt<=now.AddMinutes(-10)).ToListAsync(token);foreach(var payment in stale){payment.StatusCode="REQUESTED";payment.FailureCode="PG_RECONCILIATION_RETRY";payment.FailureReason="주문번호 결과 확인 후 같은 PG 시도키로 재시도합니다.";payment.UpdatedAt=now;created++;}
        var retries=await(from payment in db.SubscriptionPaymentRequests join contract in db.SubscriptionContracts on payment.SubscriptionContractId equals contract.Id where payment.StatusCode=="FAILED"&&payment.FailedAt<=now.AddDays(-1)&&payment.CreatedAt>=now.AddDays(-7)&&(contract.StatusCode=="PAUSED"||contract.StatusCode=="PAYMENT_PENDING")&&contract.BillingStatusCode=="OVERDUE" select new{payment,contract}).ToListAsync(token);
        foreach(var row in retries){var method=row.contract.PaymentMethodId.HasValue?await db.SubscriptionPaymentMethods.SingleOrDefaultAsync(x=>x.Id==row.contract.PaymentMethodId&&x.CustomerProfileId==row.contract.CustomerProfileId&&x.StatusCode=="ACTIVE",token):null;if(method is null)continue;row.payment.PaymentMethodId=method.Id;row.payment.GatewayAttemptNo++;row.payment.StatusCode="REQUESTED";row.payment.FailedAt=null;row.payment.FailureCode=null;row.payment.FailureReason=null;row.payment.RequestedAt=now;row.payment.UpdatedAt=now;row.contract.BillingStatusCode="PAYMENT_PROCESSING";row.contract.UpdatedAt=now;created++;}
        var due=await db.SubscriptionContracts.Where(x=>x.StatusCode=="ACTIVE"&&x.BillingStatusCode=="ACTIVE"&&x.NextBillingAt.HasValue&&x.NextBillingAt<=now).ToListAsync(token);
        foreach(var contract in due)
        {
            var start=DateOnly.FromDateTime(contract.NextBillingAt!.Value);var end=start.AddMonths(1).AddDays(-1);
            if(await db.SubscriptionPaymentRequests.AnyAsync(x=>x.SubscriptionContractId==contract.Id&&x.BillingPeriodStart==start&&x.BillingPeriodEnd==end,token))continue;
            var amount=BillingAmount(contract.PriceSnapshotJson);if(!amount.HasValue||amount<=0){contract.BillingStatusCode="AMOUNT_REVIEW_REQUIRED";continue;}
            var method=contract.PaymentMethodId.HasValue?await db.SubscriptionPaymentMethods.SingleOrDefaultAsync(x=>x.Id==contract.PaymentMethodId&&x.CustomerProfileId==contract.CustomerProfileId&&x.StatusCode=="ACTIVE",token):null;
            var payment=new SubscriptionPaymentRequest{SubscriptionContractId=contract.Id,CustomerProfileId=contract.CustomerProfileId,PaymentMethodId=method?.Id,BillingPeriodStart=start,BillingPeriodEnd=end,RequestedAmount=amount.Value,CurrencyCode=contract.CurrencyCode,StatusCode=method is null?"FAILED":"REQUESTED",RequestedAt=now,FailedAt=method is null?now:null,FailureCode=method is null?"PAYMENT_METHOD_REQUIRED":null,FailureReason=method is null?"자동결제에 사용할 결제수단이 등록되지 않았습니다.":null,IdempotencyKey=$"subscription-contract:{contract.PublicId:N}:billing:{start:yyyyMMdd}",CreatedAt=now,CreatedByUserId=contract.CreatedByUserId,UpdatedAt=now,UpdatedByUserId=contract.UpdatedByUserId};
            db.SubscriptionPaymentRequests.Add(payment);contract.BillingStatusCode=method is null?"OVERDUE":"PAYMENT_PROCESSING";contract.UpdatedAt=now;if(method is null){contract.StatusCode="PAUSED";contract.PauseStartedAt=now;foreach(var visit in await db.SubscriptionVisitSchedules.Where(x=>x.SubscriptionContractId==contract.Id&&x.ScheduledStartAt>=now&&x.StatusCode=="SCHEDULED").ToListAsync(token))visit.StatusCode="PAUSED";}created++;
        }
        await db.SaveChangesAsync(token);if(paymentProcessor is not null)await paymentProcessor.ProcessPendingAsync(token);return created;
    }

    public async Task<int> ProcessAutonomousSettlements(CancellationToken token)
    {
        var now=DateTime.UtcNow;var processed=0;
        var visits=await db.SubscriptionVisitSchedules.Where(x=>x.StatusCode=="COMPLETED"&&x.SettlementStatusCode=="READY"&&!db.SubscriptionSettlementItems.Any(i=>i.SubscriptionVisitScheduleId==x.Id)).ToListAsync(token);
        foreach(var visit in visits)
        {
            var contract=await db.SubscriptionContracts.SingleAsync(x=>x.Id==visit.SubscriptionContractId,token);var visitDate=DateOnly.FromDateTime(visit.ScheduledStartAt);
            var paid=await IsSettlementPaymentClear(contract.Id,visitDate,token);
            var gross=VisitAmount(contract.PriceSnapshotJson);var fee=feeCalculator.Calculate(contract.FeePolicySnapshotJson,gross);var ready=paid&&gross.HasValue&&fee.Calculable;
            db.SubscriptionSettlementItems.Add(new SubscriptionSettlementItem{SubscriptionVisitScheduleId=visit.Id,SubscriptionContractId=contract.Id,ProviderProfileId=visit.ProviderProfileId,SettlementMonth=new DateOnly(visitDate.Year,visitDate.Month,1),GrossAmount=gross,FeePolicyCode=fee.PolicyCode,FeePolicySnapshotJson=contract.FeePolicySnapshotJson,CalculatedFeeAmount=fee.FeeAmount,AdjustmentAmount=0,NetAmount=ready?gross-fee.FeeAmount:null,StatusCode=ready?"READY":!paid?"HOLD":!gross.HasValue?"CALCULATION_PENDING":"POLICY_PENDING",HoldReason=!paid?"결제 미완료 또는 환불·조정 검토 중이어서 자동 정산을 보류했습니다.":fee.Calculable?null:fee.Reason,IdempotencyKey=$"auto-settlement-item:{visit.PublicId:N}",CreatedAt=now,UpdatedAt=now});
            processed++;
        }
        if(visits.Count>0)await db.SaveChangesAsync(token);

        var readyItems=await db.SubscriptionSettlementItems.Where(x=>x.StatusCode=="READY"&&!x.MonthlySettlementId.HasValue&&x.GrossAmount.HasValue&&x.CalculatedFeeAmount.HasValue&&x.NetAmount.HasValue).ToListAsync(token);
        foreach(var group in readyItems.GroupBy(x=>new{x.ProviderProfileId,x.SettlementMonth.Year,x.SettlementMonth.Month}))
        {
            var key=$"auto-monthly-settlement:{group.Key.ProviderProfileId}:{group.Key.Year:D4}{group.Key.Month:D2}";
            var rows=group.ToList();var header=await db.MonthlySettlements.SingleOrDefaultAsync(x=>x.ProviderProfileId==group.Key.ProviderProfileId&&x.SettlementYear==group.Key.Year&&x.SettlementMonth==group.Key.Month,token);
            if(header is not null&&header.StatusCode is not ("DRAFT" or "REVIEW")){foreach(var item in rows){item.StatusCode="HOLD";item.HoldReason="이미 확정된 월 정산 이후 확인된 회차입니다. 관리자가 추가 정산 여부를 검토해 주세요.";item.UpdatedAt=now;}await db.SaveChangesAsync(token);continue;}
            if(header is null){header=new MonthlySettlement{ProviderProfileId=group.Key.ProviderProfileId,SettlementYear=group.Key.Year,SettlementMonth=group.Key.Month,StatusCode="DRAFT",IdempotencyKey=key,CreatedAt=now,PreparedAt=now,UpdatedAt=now};db.MonthlySettlements.Add(header);await db.SaveChangesAsync(token);}
            foreach(var item in rows)item.MonthlySettlementId=header.Id;
            await db.SaveChangesAsync(token);
            var attached=await db.SubscriptionSettlementItems.Where(x=>x.MonthlySettlementId==header.Id).ToListAsync(token);
            header.GrossTotal=attached.Sum(x=>x.GrossAmount??0);header.FeeTotal=attached.Sum(x=>x.CalculatedFeeAmount??0);header.AdjustmentTotal=attached.Sum(x=>x.AdjustmentAmount);header.NetTotal=attached.Sum(x=>x.NetAmount??0);header.ItemCount=attached.Count;header.UpdatedAt=now;
            db.AuditLogs.Add(new AuditLog{OccurredAt=now,ActorRoleCode="SYSTEM",ActionCode="SUBSCRIPTION_SETTLEMENT_DRAFT_PREPARED",EntityType="MONTHLY_SETTLEMENT",EntityPublicId=header.PublicId,ResultCode="SUCCESS",AfterJson=JsonSerializer.Serialize(new{header.NetTotal,header.ItemCount,approvalRequired=true})});await db.SaveChangesAsync(token);processed+=rows.Count;
        }
        return processed;
    }

    public async Task<SubscriptionPaymentResponse> CancelPayment(Guid id,PaymentStateRequest input,Guid actorPublicId,CancellationToken token)
    {
        RequiredKey(input.IdempotencyKey);var actor=await AdminId(actorPublicId,token);var request=await db.SubscriptionPaymentRequests.SingleOrDefaultAsync(x=>x.PublicId==id,token)??throw NotFound("SUBSCRIPTION_PAYMENT_NOT_FOUND","결제 요청을 찾을 수 없습니다.");EnsureVersion(request.RowVersion,input.RowVersion);if(request.StatusCode is not ("REQUESTED" or "PROCESSING" or "FAILED"))throw Conflict("SUBSCRIPTION_PAYMENT_STATE_INVALID","완료되지 않은 결제만 취소할 수 있습니다.");var before=request.StatusCode;request.StatusCode="CANCELLED";request.CancelledAt=DateTime.UtcNow;request.UpdatedAt=DateTime.UtcNow;request.UpdatedByUserId=actor;Audit(actor,"SUBSCRIPTION_PAYMENT_CANCELLED","SUBSCRIPTION_PAYMENT_REQUEST",request.PublicId,new{Status=before},new{Status=request.StatusCode},input.Reason);await db.SaveChangesAsync(token);return await Payment(id,token);
    }

    public async Task<List<SubscriptionPaymentLedgerResponse>> PaymentLedger(CancellationToken token)=>await db.SubscriptionPaymentLedger.AsNoTracking().OrderByDescending(x=>x.OccurredAt).Select(x=>new SubscriptionPaymentLedgerResponse(x.PublicId,db.SubscriptionContracts.Where(c=>c.Id==x.SubscriptionContractId).Select(c=>c.PublicId).First(),x.PaymentRequestId==null?null:db.SubscriptionPaymentRequests.Where(p=>p.Id==x.PaymentRequestId).Select(p=>(Guid?)p.PublicId).FirstOrDefault(),x.EntryTypeCode,x.Amount,x.CurrencyCode,x.ReferenceType,x.ReferencePublicId,x.ReasonText,x.OccurredAt)).ToListAsync(token);

    public async Task<List<SubscriptionSettlementItemResponse>> PrepareSettlementItems(PrepareSettlementItemsRequest input,Guid actorPublicId,CancellationToken token)
    {
        ValidateMonth(input.Year,input.Month);RequiredKey(input.IdempotencyKey);var actor=await AdminId(actorPublicId,token);var start=new DateTime(input.Year,input.Month,1);var end=start.AddMonths(1);var visits=await db.SubscriptionVisitSchedules.Where(x=>x.ScheduledStartAt>=start&&x.ScheduledStartAt<end&&x.StatusCode=="COMPLETED"&&x.SettlementStatusCode=="READY"&&!db.SubscriptionSettlementItems.Any(i=>i.SubscriptionVisitScheduleId==x.Id)).ToListAsync(token);var now=DateTime.UtcNow;
        foreach(var visit in visits)
        {
            var contract=await db.SubscriptionContracts.SingleAsync(x=>x.Id==visit.SubscriptionContractId,token);var visitDate=DateOnly.FromDateTime(visit.ScheduledStartAt);var paid=await IsSettlementPaymentClear(contract.Id,visitDate,token);var gross=VisitAmount(contract.PriceSnapshotJson);var fee=feeCalculator.Calculate(contract.FeePolicySnapshotJson,gross);var status=!paid?"HOLD":!gross.HasValue?"CALCULATION_PENDING":!fee.Calculable?"POLICY_PENDING":"READY";var reason=!paid?"결제 미완료 또는 환불·조정 검토 중이어서 정산할 수 없습니다.":fee.Calculable?null:fee.Reason;var item=new SubscriptionSettlementItem{SubscriptionVisitScheduleId=visit.Id,SubscriptionContractId=contract.Id,ProviderProfileId=visit.ProviderProfileId,SettlementMonth=new DateOnly(input.Year,input.Month,1),GrossAmount=gross,FeePolicyCode=fee.PolicyCode,FeePolicySnapshotJson=contract.FeePolicySnapshotJson,CalculatedFeeAmount=fee.FeeAmount,AdjustmentAmount=0,NetAmount=paid&&fee.Calculable&&gross.HasValue?gross-fee.FeeAmount:null,StatusCode=status,HoldReason=reason,IdempotencyKey=$"{input.IdempotencyKey.Trim()}:{visit.PublicId:N}",CreatedAt=now,CreatedByUserId=actor,UpdatedAt=now,UpdatedByUserId=actor};db.SubscriptionSettlementItems.Add(item);
        }
        Audit(actor,"SUBSCRIPTION_SETTLEMENT_ITEMS_PREPARED","SUBSCRIPTION_SETTLEMENT_BATCH",null,null,new{input.Year,input.Month,Created=visits.Count});await db.SaveChangesAsync(token);return await SettlementItems(input.Year,input.Month,token);
    }

    public async Task<List<SubscriptionSettlementItemResponse>> SettlementItems(int? year,int? month,CancellationToken token)
    {
        var query=SettlementItemQuery();if(year.HasValue)query=query.Where(x=>x.ScheduledStartAt.Year==year);if(month.HasValue)query=query.Where(x=>x.ScheduledStartAt.Month==month);return await query.OrderByDescending(x=>x.ScheduledStartAt).ToListAsync(token);
    }

    public async Task<SubscriptionSettlementItemResponse> HoldSettlementItem(Guid id,SettlementDecisionRequest input,bool release,Guid actorPublicId,CancellationToken token)
    {
        RequiredKey(input.IdempotencyKey);var actor=await AdminId(actorPublicId,token);var item=await db.SubscriptionSettlementItems.SingleOrDefaultAsync(x=>x.PublicId==id,token)??throw NotFound("SUBSCRIPTION_SETTLEMENT_ITEM_NOT_FOUND","정산 항목을 찾을 수 없습니다.");EnsureVersion(item.RowVersion,input.RowVersion);if(item.MonthlySettlementId.HasValue)throw Conflict("SUBSCRIPTION_SETTLEMENT_ITEM_ATTACHED","월 정산에 포함된 항목은 상태를 변경할 수 없습니다.");var before=item.StatusCode;if(release){if(item.StatusCode!="HOLD")throw Conflict("SUBSCRIPTION_SETTLEMENT_ITEM_STATE_INVALID","보류 중인 항목만 해제할 수 있습니다.");var fee=feeCalculator.Calculate(item.FeePolicySnapshotJson,item.GrossAmount);item.StatusCode=!item.GrossAmount.HasValue?"CALCULATION_PENDING":!fee.Calculable?"POLICY_PENDING":"READY";item.CalculatedFeeAmount=fee.FeeAmount;item.NetAmount=fee.Calculable&&item.GrossAmount.HasValue?item.GrossAmount-fee.FeeAmount+item.AdjustmentAmount:null;item.HoldReason=fee.Calculable?null:fee.Reason;}else{item.StatusCode="HOLD";item.HoldReason=string.IsNullOrWhiteSpace(input.Reason)?"관리자 정산 보류":input.Reason.Trim();}item.UpdatedAt=DateTime.UtcNow;item.UpdatedByUserId=actor;Audit(actor,release?"SUBSCRIPTION_SETTLEMENT_HOLD_RELEASED":"SUBSCRIPTION_SETTLEMENT_HELD","SUBSCRIPTION_SETTLEMENT_ITEM",item.PublicId,new{Status=before},new{item.StatusCode,item.HoldReason},input.Reason);await db.SaveChangesAsync(token);return await SettlementItem(id,token);
    }

    public async Task<List<MonthlySettlementResponse>> MonthlySettlements(CancellationToken token)=>await MonthlyQuery().OrderByDescending(x=>x.Year).ThenByDescending(x=>x.Month).ToListAsync(token);

    public async Task<MonthlySettlementResponse> CreateMonthlySettlement(CreateMonthlySettlementRequest input,Guid actorPublicId,CancellationToken token)
    {
        ValidateMonth(input.Year,input.Month);RequiredKey(input.IdempotencyKey);var existing=await db.MonthlySettlements.AsNoTracking().SingleOrDefaultAsync(x=>x.IdempotencyKey==input.IdempotencyKey.Trim(),token);if(existing is not null)return await Monthly(existing.PublicId,token);var actor=await AdminId(actorPublicId,token);var provider=await db.ProviderProfiles.SingleOrDefaultAsync(x=>x.PublicId==input.ProviderId,token)??throw NotFound("SUBSCRIPTION_PROVIDER_NOT_FOUND","전문가를 찾을 수 없습니다.");var settlementMonth=new DateOnly(input.Year,input.Month,1);var items=await db.SubscriptionSettlementItems.Where(x=>x.ProviderProfileId==provider.Id&&x.SettlementMonth==settlementMonth&&!x.MonthlySettlementId.HasValue&&x.StatusCode!="HOLD"&&x.StatusCode!="CANCELLED").ToListAsync(token);if(items.Count==0)throw Conflict("SUBSCRIPTION_SETTLEMENT_ITEMS_EMPTY","월 정산에 포함할 회차가 없습니다.");var now=DateTime.UtcNow;var header=new MonthlySettlement{ProviderProfileId=provider.Id,SettlementYear=input.Year,SettlementMonth=input.Month,StatusCode="DRAFT",GrossTotal=items.Sum(x=>x.GrossAmount??0),FeeTotal=items.Sum(x=>x.CalculatedFeeAmount??0),AdjustmentTotal=items.Sum(x=>x.AdjustmentAmount),NetTotal=items.Sum(x=>x.NetAmount??0),ItemCount=items.Count,IdempotencyKey=input.IdempotencyKey.Trim(),CreatedAt=now,PreparedAt=now,UpdatedAt=now,UpdatedByUserId=actor};db.MonthlySettlements.Add(header);await db.SaveChangesAsync(token);foreach(var item in items)item.MonthlySettlementId=header.Id;Audit(actor,"SUBSCRIPTION_MONTHLY_SETTLEMENT_CREATED","MONTHLY_SETTLEMENT",header.PublicId,null,new{input.Year,input.Month,header.ItemCount});await db.SaveChangesAsync(token);return await Monthly(header.PublicId,token);
    }

    public async Task<MonthlySettlementResponse> ApproveMonthlySettlement(Guid id,SettlementDecisionRequest input,Guid actorPublicId,CancellationToken token)
    {
        RequiredKey(input.IdempotencyKey);var actor=await AdminId(actorPublicId,token);var header=await db.MonthlySettlements.SingleOrDefaultAsync(x=>x.PublicId==id,token)??throw NotFound("SUBSCRIPTION_MONTHLY_SETTLEMENT_NOT_FOUND","월 정산을 찾을 수 없습니다.");EnsureVersion(header.RowVersion,input.RowVersion);if(header.StatusCode is not ("DRAFT" or "REVIEW"))throw Conflict("SUBSCRIPTION_MONTHLY_SETTLEMENT_STATE_INVALID","검토 중인 정산만 승인할 수 있습니다.");var items=await db.SubscriptionSettlementItems.Where(x=>x.MonthlySettlementId==header.Id).ToListAsync(token);if(items.Any(x=>x.StatusCode!="READY"||!x.GrossAmount.HasValue||!x.CalculatedFeeAmount.HasValue||!x.NetAmount.HasValue))throw Conflict("SUBSCRIPTION_SETTLEMENT_POLICY_PENDING","금액 또는 수수료정책이 확정되지 않은 회차가 있어 승인할 수 없습니다.");var before=header.StatusCode;header.StatusCode="APPROVED";header.ApprovedAt=DateTime.UtcNow;header.ApprovedByUserId=actor;header.UpdatedAt=DateTime.UtcNow;header.UpdatedByUserId=actor;Audit(actor,"SUBSCRIPTION_MONTHLY_SETTLEMENT_APPROVED","MONTHLY_SETTLEMENT",header.PublicId,new{Status=before},new{header.StatusCode,header.NetTotal});await db.SaveChangesAsync(token);return await Monthly(id,token);
    }

    public async Task<List<SubscriptionPayoutResponse>> Payouts(CancellationToken token)=>await PayoutQuery().OrderByDescending(x=>x.RequestedAt).ToListAsync(token);

    public async Task<SubscriptionPayoutResponse> CreatePayout(CreateSubscriptionPayoutRequest input,Guid actorPublicId,CancellationToken token)
    {
        RequiredKey(input.IdempotencyKey);var existing=await db.SubscriptionPayouts.AsNoTracking().SingleOrDefaultAsync(x=>x.IdempotencyKey==input.IdempotencyKey.Trim(),token);if(existing is not null)return await Payout(existing.PublicId,token);var actor=await AdminId(actorPublicId,token);var header=await db.MonthlySettlements.SingleOrDefaultAsync(x=>x.PublicId==input.MonthlySettlementId,token)??throw NotFound("SUBSCRIPTION_MONTHLY_SETTLEMENT_NOT_FOUND","월 정산을 찾을 수 없습니다.");if(header.StatusCode!="APPROVED")throw Conflict("SUBSCRIPTION_PAYOUT_SETTLEMENT_NOT_APPROVED","승인된 월 정산만 지급 요청할 수 있습니다.");var now=DateTime.UtcNow;var payout=new SubscriptionPayout{MonthlySettlementId=header.Id,ProviderProfileId=header.ProviderProfileId,RequestedAmount=header.NetTotal,StatusCode="REQUESTED",RequestedAt=now,IdempotencyKey=input.IdempotencyKey.Trim(),CreatedAt=now,CreatedByUserId=actor,UpdatedAt=now,UpdatedByUserId=actor};db.SubscriptionPayouts.Add(payout);header.StatusCode="PAYMENT_PENDING";header.UpdatedAt=now;header.UpdatedByUserId=actor;AddPayoutEvent(payout,"REQUESTED",new{payout.RequestedAmount},actor,$"{input.IdempotencyKey.Trim()}:event",now);Audit(actor,"SUBSCRIPTION_PAYOUT_REQUESTED","SUBSCRIPTION_PAYOUT",payout.PublicId,null,new{payout.RequestedAmount});await db.SaveChangesAsync(token);return await Payout(payout.PublicId,token);
    }

    public async Task<SubscriptionPayoutResponse> ApprovePayout(Guid id,PayoutDecisionRequest input,Guid actorPublicId,CancellationToken token)
    {
        RequiredKey(input.IdempotencyKey);var actor=await AdminId(actorPublicId,token);var payout=await db.SubscriptionPayouts.SingleOrDefaultAsync(x=>x.PublicId==id,token)??throw NotFound("SUBSCRIPTION_PAYOUT_NOT_FOUND","지급 요청을 찾을 수 없습니다.");if(await db.SubscriptionPayoutEvents.AnyAsync(x=>x.IdempotencyKey==input.IdempotencyKey.Trim(),token))return await Payout(id,token);EnsureVersion(payout.RowVersion,input.RowVersion);if(payout.StatusCode!="REQUESTED")throw Conflict("SUBSCRIPTION_PAYOUT_STATE_INVALID","지급 요청 상태에서만 승인할 수 있습니다.");var amount=input.ApprovedAmount??payout.RequestedAmount;if(amount<0||amount>payout.RequestedAmount)throw Bad("SUBSCRIPTION_PAYOUT_AMOUNT_INVALID","승인 금액을 확인해 주세요.");var now=DateTime.UtcNow;payout.ApprovedAmount=amount;payout.StatusCode="APPROVED";payout.ApprovedAt=now;payout.UpdatedAt=now;payout.UpdatedByUserId=actor;AddPayoutEvent(payout,"APPROVED",new{Amount=amount},actor,input.IdempotencyKey.Trim(),now);Audit(actor,"SUBSCRIPTION_PAYOUT_APPROVED","SUBSCRIPTION_PAYOUT",payout.PublicId,null,new{Amount=amount});await db.SaveChangesAsync(token);return await Payout(id,token);
    }

    public async Task<SubscriptionPayoutResponse> CompletePayout(Guid id,PayoutDecisionRequest input,Guid actorPublicId,CancellationToken token)
    {
        EnsureSimulation("SUBSCRIPTION_PAYOUT_CONFIRMATION_DISABLED","개발용 지급 완료 확인은 운영환경에서 사용할 수 없습니다.");RequiredKey(input.IdempotencyKey);var actor=await AdminId(actorPublicId,token);var payout=await db.SubscriptionPayouts.SingleOrDefaultAsync(x=>x.PublicId==id,token)??throw NotFound("SUBSCRIPTION_PAYOUT_NOT_FOUND","지급 요청을 찾을 수 없습니다.");if(await db.SubscriptionPayoutEvents.AnyAsync(x=>x.IdempotencyKey==input.IdempotencyKey.Trim(),token))return await Payout(id,token);EnsureVersion(payout.RowVersion,input.RowVersion);if(payout.StatusCode!="APPROVED")throw Conflict("SUBSCRIPTION_PAYOUT_STATE_INVALID","승인된 지급만 완료 확인할 수 있습니다.");var now=DateTime.UtcNow;payout.StatusCode="COMPLETED";payout.CompletedAt=now;payout.ExternalPayoutReference=Trim(input.ExternalPayoutReference);payout.UpdatedAt=now;payout.UpdatedByUserId=actor;var header=await db.MonthlySettlements.SingleAsync(x=>x.Id==payout.MonthlySettlementId,token);header.StatusCode="PAID";header.PaidAt=now;header.UpdatedAt=now;header.UpdatedByUserId=actor;var items=await db.SubscriptionSettlementItems.Where(x=>x.MonthlySettlementId==header.Id).ToListAsync(token);foreach(var item in items)item.StatusCode="SETTLED";AddPayoutEvent(payout,"COMPLETED",new{payout.ApprovedAmount,payout.ExternalPayoutReference},actor,input.IdempotencyKey.Trim(),now);Audit(actor,"SUBSCRIPTION_PAYOUT_COMPLETED_SIMULATION","SUBSCRIPTION_PAYOUT",payout.PublicId,null,new{payout.ApprovedAmount});await db.SaveChangesAsync(token);return await Payout(id,token);
    }

    public async Task<SubscriptionPayoutResponse> CompleteBankTransferPayout(Guid id,CompleteBankTransferPayoutRequest input,Guid actorPublicId,CancellationToken token)
    {
        RequiredKey(input.IdempotencyKey);if(string.IsNullOrWhiteSpace(input.BankTransferReference))throw Bad("SUBSCRIPTION_BANK_TRANSFER_REFERENCE_REQUIRED","은행 송금 확인번호를 입력해 주세요.");var actor=await AdminId(actorPublicId,token);var payout=await db.SubscriptionPayouts.SingleOrDefaultAsync(x=>x.PublicId==id,token)??throw NotFound("SUBSCRIPTION_PAYOUT_NOT_FOUND","지급 요청을 찾을 수 없습니다.");if(await db.SubscriptionPayoutEvents.AnyAsync(x=>x.IdempotencyKey==input.IdempotencyKey.Trim(),token))return await Payout(id,token);EnsureVersion(payout.RowVersion,input.RowVersion);if(payout.StatusCode!="APPROVED")throw Conflict("SUBSCRIPTION_PAYOUT_STATE_INVALID","승인된 지급만 송금 완료 처리할 수 있습니다.");var now=DateTime.UtcNow;payout.StatusCode="COMPLETED";payout.CompletedAt=now;payout.ExternalPayoutReference=input.BankTransferReference.Trim();payout.UpdatedAt=now;payout.UpdatedByUserId=actor;var header=await db.MonthlySettlements.SingleAsync(x=>x.Id==payout.MonthlySettlementId,token);header.StatusCode="PAID";header.PaidAt=now;header.UpdatedAt=now;header.UpdatedByUserId=actor;foreach(var item in await db.SubscriptionSettlementItems.Where(x=>x.MonthlySettlementId==header.Id).ToListAsync(token))item.StatusCode="SETTLED";AddPayoutEvent(payout,"BANK_TRANSFER_COMPLETED",new{Reference=payout.ExternalPayoutReference,Amount=payout.ApprovedAmount},actor,input.IdempotencyKey.Trim(),now);Audit(actor,"SUBSCRIPTION_PAYOUT_BANK_TRANSFER_COMPLETED","SUBSCRIPTION_PAYOUT",payout.PublicId,null,new{payout.ApprovedAmount,payout.ExternalPayoutReference},input.Reason);await db.SaveChangesAsync(token);return await Payout(id,token);
    }

    public async Task<List<SubscriptionRefundAdjustmentResponse>> Refunds(CancellationToken token)=>await RefundQuery().OrderByDescending(x=>x.RequestedAt).ToListAsync(token);

    public async Task<SubscriptionRefundAdjustmentResponse> CreateRefund(CreateRefundAdjustmentRequest input,Guid actorPublicId,CancellationToken token)
    {
        RequiredKey(input.IdempotencyKey);if(input.RequestedAmount<=0)throw Bad("SUBSCRIPTION_REFUND_AMOUNT_INVALID","요청 금액은 0원보다 커야 합니다.");var type=input.TypeCode.Trim().ToUpperInvariant();if(type is not ("REFUND" or "ADJUSTMENT"))throw Bad("SUBSCRIPTION_REFUND_TYPE_INVALID","환불 또는 조정 유형을 선택해 주세요.");var existing=await db.SubscriptionRefundAdjustments.AsNoTracking().SingleOrDefaultAsync(x=>x.IdempotencyKey==input.IdempotencyKey.Trim(),token);if(existing is not null)return await Refund(existing.PublicId,token);var actor=await AdminId(actorPublicId,token);var contract=await db.SubscriptionContracts.SingleOrDefaultAsync(x=>x.PublicId==input.ContractId,token)??throw NotFound("SUBSCRIPTION_CONTRACT_NOT_FOUND","구독 계약을 찾을 수 없습니다.");var payment=input.PaymentRequestId.HasValue?await db.SubscriptionPaymentRequests.SingleOrDefaultAsync(x=>x.PublicId==input.PaymentRequestId&&x.SubscriptionContractId==contract.Id,token):null;if(input.PaymentRequestId.HasValue&&payment is null)throw Bad("SUBSCRIPTION_REFUND_PAYMENT_INVALID","계약의 결제내역을 확인해 주세요.");var visit=input.VisitId.HasValue?await db.SubscriptionVisitSchedules.SingleOrDefaultAsync(x=>x.PublicId==input.VisitId&&x.SubscriptionContractId==contract.Id,token):null;if(input.VisitId.HasValue&&visit is null)throw Bad("SUBSCRIPTION_REFUND_VISIT_INVALID","계약의 회차를 확인해 주세요.");var now=DateTime.UtcNow;var item=new SubscriptionRefundAdjustment{SubscriptionContractId=contract.Id,PaymentRequestId=payment?.Id,VisitScheduleId=visit?.Id,TypeCode=type,RequestedAmount=input.RequestedAmount,Reason=input.Reason.Trim(),StatusCode="REQUESTED",RequestedAt=now,IdempotencyKey=input.IdempotencyKey.Trim(),CreatedAt=now,CreatedByUserId=actor,UpdatedAt=now,UpdatedByUserId=actor};db.SubscriptionRefundAdjustments.Add(item);Audit(actor,"SUBSCRIPTION_REFUND_ADJUSTMENT_REQUESTED","SUBSCRIPTION_REFUND_ADJUSTMENT",item.PublicId,null,new{item.TypeCode,item.RequestedAmount},item.Reason);await db.SaveChangesAsync(token);return await Refund(item.PublicId,token);
    }

    public async Task<SubscriptionRefundAdjustmentResponse> ApproveRefund(Guid id,RefundAdjustmentDecisionRequest input,Guid actorPublicId,CancellationToken token)
    {
        RequiredKey(input.IdempotencyKey);var actor=await AdminId(actorPublicId,token);var item=await db.SubscriptionRefundAdjustments.SingleOrDefaultAsync(x=>x.PublicId==id,token)??throw NotFound("SUBSCRIPTION_REFUND_NOT_FOUND","환불·조정 요청을 찾을 수 없습니다.");EnsureVersion(item.RowVersion,input.RowVersion);if(item.StatusCode!="REQUESTED")throw Conflict("SUBSCRIPTION_REFUND_STATE_INVALID","요청 상태에서만 승인할 수 있습니다.");var amount=input.ApprovedAmount??item.RequestedAmount;if(amount<0||amount>item.RequestedAmount)throw Bad("SUBSCRIPTION_REFUND_AMOUNT_INVALID","승인 금액을 확인해 주세요.");item.ApprovedAmount=amount;item.StatusCode="APPROVED";item.ApprovedAt=DateTime.UtcNow;item.ProcessedByUserId=actor;item.UpdatedAt=DateTime.UtcNow;item.UpdatedByUserId=actor;Audit(actor,"SUBSCRIPTION_REFUND_ADJUSTMENT_APPROVED","SUBSCRIPTION_REFUND_ADJUSTMENT",item.PublicId,null,new{item.TypeCode,Amount=amount},input.Reason);await db.SaveChangesAsync(token);return await Refund(id,token);
    }

    public async Task<SubscriptionRefundAdjustmentResponse> CompleteRefund(Guid id,RefundAdjustmentDecisionRequest input,Guid actorPublicId,CancellationToken token)
    {
        EnsureSimulation("SUBSCRIPTION_REFUND_CONFIRMATION_DISABLED","개발용 환불 완료 확인은 운영환경에서 사용할 수 없습니다.");RequiredKey(input.IdempotencyKey);var actor=await AdminId(actorPublicId,token);var item=await db.SubscriptionRefundAdjustments.SingleOrDefaultAsync(x=>x.PublicId==id,token)??throw NotFound("SUBSCRIPTION_REFUND_NOT_FOUND","환불·조정 요청을 찾을 수 없습니다.");if(await db.SubscriptionPaymentLedger.AnyAsync(x=>x.IdempotencyKey==input.IdempotencyKey.Trim(),token))return await Refund(id,token);EnsureVersion(item.RowVersion,input.RowVersion);if(item.StatusCode!="APPROVED"||!item.ApprovedAmount.HasValue)throw Conflict("SUBSCRIPTION_REFUND_STATE_INVALID","승인된 요청만 완료 확인할 수 있습니다.");var contract=await db.SubscriptionContracts.SingleAsync(x=>x.Id==item.SubscriptionContractId,token);var now=DateTime.UtcNow;item.StatusCode="COMPLETED";item.CompletedAt=now;item.ProcessedByUserId=actor;item.UpdatedAt=now;item.UpdatedByUserId=actor;db.SubscriptionPaymentLedger.Add(new SubscriptionPaymentLedgerEntry{SubscriptionContractId=item.SubscriptionContractId,PaymentRequestId=item.PaymentRequestId,EntryTypeCode=item.TypeCode=="REFUND"?"REFUND":"ADJUSTMENT",Amount=-item.ApprovedAmount.Value,CurrencyCode=contract.CurrencyCode,ReferenceType="REFUND_ADJUSTMENT",ReferencePublicId=item.PublicId,ReasonText=item.Reason,OccurredAt=now,ProcessedByUserId=actor,IdempotencyKey=input.IdempotencyKey.Trim(),CreatedAt=now});if(item.PaymentRequestId.HasValue){var payment=await db.SubscriptionPaymentRequests.SingleAsync(x=>x.Id==item.PaymentRequestId,token);var refunded=await db.SubscriptionRefundAdjustments.Where(x=>x.PaymentRequestId==payment.Id&&x.TypeCode=="REFUND"&&x.StatusCode=="COMPLETED").SumAsync(x=>x.ApprovedAmount??0,token)+item.ApprovedAmount.Value;payment.StatusCode=refunded>=payment.RequestedAmount?"REFUNDED":"PARTIALLY_REFUNDED";payment.UpdatedAt=now;payment.UpdatedByUserId=actor;}if(contract.StatusCode=="TERMINATION_REQUESTED"&&!await db.SubscriptionRefundAdjustments.AnyAsync(x=>x.SubscriptionContractId==contract.Id&&x.Id!=item.Id&&(x.StatusCode=="REQUESTED"||x.StatusCode=="APPROVED"),token)&&!await db.SubscriptionVisitSchedules.AnyAsync(x=>x.SubscriptionContractId==contract.Id&&(x.StatusCode=="IN_PROGRESS"||x.StatusCode=="PROVIDER_COMPLETED"||x.StatusCode=="DISPUTED"),token)){contract.StatusCode="TERMINATED";contract.TerminatedAt=now;contract.EndedAt=now;contract.UpdatedAt=now;contract.UpdatedByUserId=actor;}Audit(actor,"SUBSCRIPTION_REFUND_ADJUSTMENT_COMPLETED_SIMULATION","SUBSCRIPTION_REFUND_ADJUSTMENT",item.PublicId,null,new{item.TypeCode,item.ApprovedAmount});await db.SaveChangesAsync(token);return await Refund(id,token);
    }

    private IQueryable<SubscriptionPaymentResponse> PaymentQuery()=>from payment in db.SubscriptionPaymentRequests.AsNoTracking() join contract in db.SubscriptionContracts.AsNoTracking() on payment.SubscriptionContractId equals contract.Id join customer in db.CustomerProfiles.AsNoTracking() on payment.CustomerProfileId equals customer.Id join service in db.ServiceCategories.AsNoTracking() on contract.ServiceCategoryId equals service.Id join method0 in db.SubscriptionPaymentMethods.AsNoTracking() on payment.PaymentMethodId equals method0.Id into methods from method in methods.DefaultIfEmpty() orderby payment.RequestedAt descending select new SubscriptionPaymentResponse(payment.PublicId,contract.PublicId,Number("SC",contract.PublicId),customer.DisplayName,service.Name,payment.BillingPeriodStart,payment.BillingPeriodEnd,payment.RequestedAmount,payment.CurrencyCode,payment.StatusCode,method==null?null:method.MaskedDisplayText,payment.RequestedAt,payment.CompletedAt,payment.FailureReason,Version(payment.RowVersion));
    private Task<SubscriptionPaymentResponse> Payment(Guid id,CancellationToken token)=>PaymentQuery().SingleAsync(x=>x.Id==id,token);
    private IQueryable<SubscriptionSettlementItemResponse> SettlementItemQuery()=>from item in db.SubscriptionSettlementItems.AsNoTracking() join visit in db.SubscriptionVisitSchedules.AsNoTracking() on item.SubscriptionVisitScheduleId equals visit.Id join contract in db.SubscriptionContracts.AsNoTracking() on item.SubscriptionContractId equals contract.Id join provider in db.ProviderProfiles.AsNoTracking() on item.ProviderProfileId equals provider.Id join service in db.ServiceCategories.AsNoTracking() on contract.ServiceCategoryId equals service.Id select new SubscriptionSettlementItemResponse(item.PublicId,visit.PublicId,contract.PublicId,Number("SC",contract.PublicId),provider.PublicId,provider.BusinessName,service.Name,visit.VisitNo,visit.ScheduledStartAt,item.GrossAmount,item.FeePolicyCode,item.CalculatedFeeAmount,item.AdjustmentAmount,item.NetAmount,item.StatusCode,item.HoldReason,item.MonthlySettlementId==null?null:db.MonthlySettlements.Where(x=>x.Id==item.MonthlySettlementId).Select(x=>(Guid?)x.PublicId).FirstOrDefault(),Version(item.RowVersion));
    private Task<SubscriptionSettlementItemResponse> SettlementItem(Guid id,CancellationToken token)=>SettlementItemQuery().SingleAsync(x=>x.Id==id,token);
    private IQueryable<MonthlySettlementResponse> MonthlyQuery()=>from settlement in db.MonthlySettlements.AsNoTracking() join provider in db.ProviderProfiles.AsNoTracking() on settlement.ProviderProfileId equals provider.Id select new MonthlySettlementResponse(settlement.PublicId,provider.PublicId,provider.BusinessName,settlement.SettlementYear,settlement.SettlementMonth,settlement.StatusCode,settlement.GrossTotal,settlement.FeeTotal,settlement.AdjustmentTotal,settlement.NetTotal,settlement.ItemCount,settlement.ApprovedAt,settlement.PaidAt,Version(settlement.RowVersion));
    private Task<MonthlySettlementResponse> Monthly(Guid id,CancellationToken token)=>MonthlyQuery().SingleAsync(x=>x.Id==id,token);
    private IQueryable<SubscriptionPayoutResponse> PayoutQuery()=>from payout in db.SubscriptionPayouts.AsNoTracking() join settlement in db.MonthlySettlements.AsNoTracking() on payout.MonthlySettlementId equals settlement.Id join provider in db.ProviderProfiles.AsNoTracking() on payout.ProviderProfileId equals provider.Id select new SubscriptionPayoutResponse(payout.PublicId,settlement.PublicId,provider.PublicId,provider.BusinessName,payout.RequestedAmount,payout.ApprovedAmount,payout.StatusCode,payout.RequestedAt,payout.CompletedAt,payout.ExternalPayoutReference,Version(payout.RowVersion));
    private Task<SubscriptionPayoutResponse> Payout(Guid id,CancellationToken token)=>PayoutQuery().SingleAsync(x=>x.Id==id,token);
    private IQueryable<SubscriptionRefundAdjustmentResponse> RefundQuery()=>from item in db.SubscriptionRefundAdjustments.AsNoTracking() join contract in db.SubscriptionContracts.AsNoTracking() on item.SubscriptionContractId equals contract.Id join customer in db.CustomerProfiles.AsNoTracking() on contract.CustomerProfileId equals customer.Id select new SubscriptionRefundAdjustmentResponse(item.PublicId,contract.PublicId,item.PaymentRequestId==null?null:db.SubscriptionPaymentRequests.Where(x=>x.Id==item.PaymentRequestId).Select(x=>(Guid?)x.PublicId).FirstOrDefault(),item.VisitScheduleId==null?null:db.SubscriptionVisitSchedules.Where(x=>x.Id==item.VisitScheduleId).Select(x=>(Guid?)x.PublicId).FirstOrDefault(),customer.DisplayName,item.TypeCode,item.RequestedAmount,item.ApprovedAmount,item.Reason,item.StatusCode,item.RequestedAt,item.CompletedAt,Version(item.RowVersion));
    private Task<SubscriptionRefundAdjustmentResponse> Refund(Guid id,CancellationToken token)=>RefundQuery().SingleAsync(x=>x.Id==id,token);
    private void AddPayoutEvent(SubscriptionPayout payout,string type,object data,long? actor,string key,DateTime now)=>db.SubscriptionPayoutEvents.Add(new SubscriptionPayoutEvent{SubscriptionPayoutId=payout.Id,EventTypeCode=type,EventDataJson=JsonSerializer.Serialize(data),OccurredAt=now,ActorUserId=actor,IdempotencyKey=key});
    private void Audit(long actor,string action,string entity,Guid? id,object? before,object? after,string? reason=null)=>db.AuditLogs.Add(new AuditLog{OccurredAt=DateTime.UtcNow,ActorUserId=actor,ActorRoleCode=RoleCodes.Admin,ActionCode=action,EntityType=entity,EntityPublicId=id,ResultCode="SUCCESS",Reason=reason,BeforeJson=before is null?null:JsonSerializer.Serialize(before),AfterJson=after is null?null:JsonSerializer.Serialize(after)});
    private async Task<long> AdminId(Guid id,CancellationToken token)=>await(from user in db.Users join link in db.UserRoles on user.Id equals link.UserId join role in db.Roles on link.RoleId equals role.Id where user.PublicId==id&&user.StatusCode=="ACTIVE"&&link.RevokedAt==null&&role.Code==RoleCodes.Admin select(long?)user.Id).SingleOrDefaultAsync(token)??throw Forbidden("ADMIN_REQUIRED","관리자 계정을 확인할 수 없습니다.");
    private async Task<bool> IsSettlementPaymentClear(long contractId,DateOnly visitDate,CancellationToken token){var paymentId=await db.SubscriptionPaymentRequests.AsNoTracking().Where(x=>x.SubscriptionContractId==contractId&&x.StatusCode=="COMPLETED"&&x.BillingPeriodStart<=visitDate&&x.BillingPeriodEnd>=visitDate).OrderByDescending(x=>x.CompletedAt).Select(x=>(long?)x.Id).FirstOrDefaultAsync(token);if(!paymentId.HasValue)return false;return !await db.SubscriptionRefundAdjustments.AsNoTracking().AnyAsync(x=>x.PaymentRequestId==paymentId&&(x.StatusCode=="REQUESTED"||x.StatusCode=="APPROVED"||x.StatusCode=="PROCESSING"||x.StatusCode=="COMPLETED"),token);}
    private static decimal? VisitAmount(string json){try{using var doc=JsonDocument.Parse(json);return doc.RootElement.TryGetProperty("visitAmount",out var value)&&value.TryGetDecimal(out var amount)?amount:null;}catch(JsonException){return null;}}
    private static decimal? BillingAmount(string json){try{using var doc=JsonDocument.Parse(json);var root=doc.RootElement;if(root.TryGetProperty("monthlyAmount",out var monthly)&&monthly.ValueKind!=JsonValueKind.Null&&monthly.TryGetDecimal(out var monthlyAmount))return monthlyAmount;if(root.TryGetProperty("visitAmount",out var visit)&&visit.ValueKind!=JsonValueKind.Null&&visit.TryGetDecimal(out var visitAmount))return visitAmount;return null;}catch(JsonException){return null;}}
    private static void ValidatePaymentMethod(RegisterSubscriptionPaymentMethodRequest input){var type=input.PaymentMethodTypeCode.Trim().ToUpperInvariant();if(type is not ("CARD" or "BANK" or "EASY_PAY" or "OTHER"))throw Bad("SUBSCRIPTION_PAYMENT_METHOD_TYPE_INVALID","결제수단 유형을 확인해 주세요.");var reference=input.ExternalTokenReference??string.Empty;if(Regex.IsMatch(reference,@"(?:\d[ -]?){12,19}")||reference.Contains("cvc",StringComparison.OrdinalIgnoreCase)||reference.Contains("cvv",StringComparison.OrdinalIgnoreCase))throw Bad("SUBSCRIPTION_PAYMENT_SENSITIVE_DATA_REJECTED","카드번호·CVC·계좌 비밀번호 등 민감 결제정보는 저장할 수 없습니다.");}
    private void EnsureSimulation(string code,string message){if(!SimulationAvailable)throw new SubscriptionBusinessException(StatusCodes.Status404NotFound,code,message);}
    private static void EnsureVersion(byte[] current,string supplied){try{if(!current.SequenceEqual(Convert.FromBase64String(supplied)))throw new FormatException();}catch{throw Conflict("SUBSCRIPTION_CONCURRENCY_CONFLICT","다른 작업이 먼저 처리했습니다. 최신 상태를 다시 확인해 주세요.");}}
    private static void RequiredKey(string key){if(string.IsNullOrWhiteSpace(key))throw Bad("SUBSCRIPTION_IDEMPOTENCY_KEY_REQUIRED","중복 처리 방지 키가 필요합니다.");}
    private static void ValidateMonth(int year,int month){if(year<2000||year>2200||month<1||month>12)throw Bad("SUBSCRIPTION_SETTLEMENT_MONTH_INVALID","정산 연월을 확인해 주세요.");}
    private static string? Trim(string? value)=>string.IsNullOrWhiteSpace(value)?null:value.Trim();
    private static string Version(byte[] value)=>Convert.ToBase64String(value);
    private static string Number(string prefix,Guid id)=>$"{prefix}-{id.ToString("N")[..10].ToUpperInvariant()}";
    private static SubscriptionBusinessException Bad(string code,string message)=>new(StatusCodes.Status400BadRequest,code,message);
    private static SubscriptionBusinessException Forbidden(string code,string message)=>new(StatusCodes.Status403Forbidden,code,message);
    private static SubscriptionBusinessException NotFound(string code,string message)=>new(StatusCodes.Status404NotFound,code,message);
    private static SubscriptionBusinessException Conflict(string code,string message)=>new(StatusCodes.Status409Conflict,code,message);
}
