[CmdletBinding()]
param([string]$ServerInstance='localhost',[string]$DatabaseName='SOODAL_LIFE_DEV')
$ErrorActionPreference='Stop';Import-Module WebAdministration
$releaseRoot=$PSScriptRoot;$appsRoot='D:\SOODALLIFE\apps';$backupParent='D:\SOODALLIFE\releases';$databaseBackupRoot='D:\SOODALLIFE\DB\Backup';$stamp=Get-Date -Format 'yyyyMMdd-HHmmss'
$backupRoot=Join-Path $backupParent "backup-before-provider-advertising-regional-v105-$stamp";$iisBackupName="Before_ProviderAdvertisingRegionalV105_$stamp";$databaseBackupPath=Join-Path $databaseBackupRoot "${DatabaseName}_PreProviderAdvertisingRegionalV105_$stamp.bak"
$applySql=Join-Path $releaseRoot 'deployment\Apply-ProviderAdvertisingRegionalV105.sql';$verifySql=Join-Path $releaseRoot 'deployment\Verify-ProviderAdvertisingRegionalV105.sql'
$sources=[ordered]@{API=Join-Path $releaseRoot 'api';Customer=Join-Path $releaseRoot 'frontend\customer';Partner=Join-Path $releaseRoot 'frontend\partner';Admin=Join-Path $releaseRoot 'frontend\admin'};$targets=[ordered]@{API=Join-Path $appsRoot 'api';Customer=Join-Path $appsRoot 'customer';Partner=Join-Path $appsRoot 'partner';Admin=Join-Path $appsRoot 'admin'}
$required=@((Join-Path $sources.API 'SoodalLife.Api.dll'),(Join-Path $sources.API 'web.config'),(Join-Path $sources.Customer 'index.html'),(Join-Path $sources.Partner 'index.html'),(Join-Path $sources.Admin 'index.html'),$applySql,$verifySql);foreach($file in $required){if(-not(Test-Path -LiteralPath $file -PathType Leaf)){throw "Required release file is missing: $file"}}
if(-not(Get-Command sqlcmd.exe -ErrorAction SilentlyContinue)){throw 'sqlcmd.exe is required.'}
New-Item -ItemType Directory -Force -Path $backupRoot,$databaseBackupRoot|Out-Null
function Copy-Checked([string]$Source,[string]$Destination,[switch]$PreserveAppData){New-Item -ItemType Directory -Force -Path $Destination|Out-Null;$args=@($Source,$Destination,'/MIR','/R:2','/W:2','/NFL','/NDL','/NJH','/NJS','/NP');if($PreserveAppData){$args+=@('/XD','App_Data')};& robocopy.exe @args;if($LASTEXITCODE -gt 7){throw "Robocopy failed ($LASTEXITCODE): $Source -> $Destination"}}
function Stop-Pool([string]$Name){if((Get-WebAppPoolState -Name $Name).Value -eq 'Stopped'){return};Stop-WebAppPool -Name $Name;for($i=0;$i -lt 30;$i++){Start-Sleep -Milliseconds 500;if((Get-WebAppPoolState -Name $Name).Value -eq 'Stopped'){return}};throw "Application pool did not stop: $Name"}
function Start-Pool([string]$Name){if((Get-WebAppPoolState -Name $Name).Value -ne 'Started'){Start-WebAppPool -Name $Name}}
& "$env:windir\System32\inetsrv\appcmd.exe" add backup $iisBackupName;if($LASTEXITCODE -ne 0){throw 'IIS configuration backup failed.'};foreach($name in $targets.Keys){if(Test-Path -LiteralPath $targets[$name]){New-Item -ItemType Directory -Force -Path (Join-Path $backupRoot $name)|Out-Null;& robocopy.exe $targets[$name] (Join-Path $backupRoot $name) /E /R:2 /W:2 /NFL /NDL /NJH /NJS /NP;if($LASTEXITCODE -gt 7){throw "Backup failed: $name"}}}
$escaped=$databaseBackupPath.Replace("'","''");& sqlcmd.exe -S $ServerInstance -E -C -b -Q "BACKUP DATABASE [$DatabaseName] TO DISK=N'$escaped' WITH COPY_ONLY, CHECKSUM, COMPRESSION, INIT; RESTORE VERIFYONLY FROM DISK=N'$escaped' WITH CHECKSUM;";if($LASTEXITCODE -ne 0){throw 'Database backup verification failed.'}
$pools=@('SoodalLife.Api','soodallife.kr','SoodalLife.Static');try{foreach($pool in $pools){Stop-Pool $pool};& sqlcmd.exe -S $ServerInstance -E -C -I -b -f 65001 -d $DatabaseName -i $applySql;if($LASTEXITCODE -ne 0){throw 'V105 database preflight failed.'};foreach($name in $sources.Keys){Copy-Checked $sources[$name] $targets[$name] -PreserveAppData:($name -eq 'API')};New-Item -ItemType Directory -Force -Path (Join-Path $targets.API 'App_Data')|Out-Null}finally{foreach($pool in $pools){try{Start-Pool $pool}catch{Write-Warning $_.Exception.Message}}}
& sqlcmd.exe -S $ServerInstance -E -C -I -b -f 65001 -d $DatabaseName -i $verifySql;if($LASTEXITCODE -ne 0){throw 'V105 database verification failed.'}
$health=Invoke-RestMethod -Uri 'https://api.soodallife.kr/api/v1/system/health' -TimeoutSec 30;$ready=Invoke-RestMethod -Uri 'https://api.soodallife.kr/api/v1/system/ready' -TimeoutSec 30;if($health.status -ne 'ok' -or $ready.status -ne 'ready'){throw 'Post-deployment API health/readiness failed.'}
[PSCustomObject]@{DeploymentSucceeded=$true;IisBackup=$iisBackupName;FileBackup=$backupRoot;DatabaseBackup=$databaseBackupPath;DatabaseChanged=$true;Health=$health.status;Readiness=$ready.status}|Format-List
Write-Host 'V105 provider advertising regional pricing deployment completed.' -ForegroundColor Green
