using System.Security.Claims;
using System.Security.Cryptography;
using System.Text;
using System.Text.Json;
using Microsoft.EntityFrameworkCore;
using SoodalLife.Api.Domain.Entities;
using SoodalLife.Api.Infrastructure.Persistence;

namespace SoodalLife.Api.Features.Work;

public sealed class CustomerDisputeService(SoodalLifeDbContext db, IPrivateFileStorage storage)
{
    public async Task<IReadOnlyList<CustomerDisputeResponse>> List(ClaimsPrincipal principal, CancellationToken token) { var identity = await Customer(principal, token); var ids = await db.DisputeCases.AsNoTracking().Where(x => x.ApplicantUserId == identity.UserId).OrderByDescending(x => x.ReceivedAt).Select(x => x.Id).ToListAsync(token); var result = new List<CustomerDisputeResponse>(); foreach (var id in ids) result.Add(await Build(id, identity.UserId, token)); return result; }
    public async Task<CustomerDisputeResponse> Detail(ClaimsPrincipal principal, Guid id, CancellationToken token) { var identity = await Customer(principal, token); var disputeId = await db.DisputeCases.AsNoTracking().Where(x => x.PublicId == id && x.ApplicantUserId == identity.UserId).Select(x => x.Id).SingleOrDefaultAsync(token); if (disputeId == 0) throw NotFound(); return await Build(disputeId, identity.UserId, token); }
    public async Task<CustomerDisputeResponse> Create(ClaimsPrincipal principal, Guid transactionId, CreateCustomerDisputeInput input, CancellationToken token)
    {
        var identity = await Customer(principal, token); var subject = Required(input.Subject, 200); var reason = Required(input.Reason, 3000); var requested = Required(input.RequestedResolution, 2000); var key = Required(input.IdempotencyKey, 100);
        var transaction = await db.Transactions.SingleOrDefaultAsync(x => x.PublicId == transactionId && x.CustomerProfileId == identity.ProfileId, token) ?? throw NotFound();
        var existing = await db.DisputeActions.AsNoTracking().Where(x => x.IdempotencyKey == key).Select(x => x.DisputeCaseId).SingleOrDefaultAsync(token); if (existing != 0) return await Build(existing, identity.UserId, token);
        var providerUser = await db.ProviderProfiles.Where(x => x.Id == transaction.ProviderProfileId).Select(x => x.UserId).SingleAsync(token); var now = DateTime.UtcNow;
        var dispute = new DisputeCase { TransactionId = transaction.Id, ApplicantUserId = identity.UserId, CounterpartyUserId = providerUser, Subject = subject, Description = $"{reason}\n\n[요구사항]\n{requested}", StatusCode = "OPEN", ReceivedAt = now, LastActionAt = now, CreatedAt = now, CreatedByUserId = identity.UserId, UpdatedAt = now, UpdatedByUserId = identity.UserId }; db.DisputeCases.Add(dispute); await db.SaveChangesAsync(token);
        db.DisputeActions.Add(new DisputeAction { DisputeCaseId = dispute.Id, ActionTypeCode = "CREATED", ToStatusCode = "OPEN", ActionNote = "고객 직접 접수", Reason = reason, OccurredAt = now, ActorUserId = identity.UserId, IdempotencyKey = key });
        if (transaction.StatusCode == "COMPLETION_SUBMITTED") transaction.StatusCode = "DISPUTED";
        db.OutboxEvents.Add(new OutboxEvent { AggregateType = "Dispute", AggregatePublicId = dispute.PublicId, EventType = "DISPUTE_OPENED", PayloadJson = JsonSerializer.Serialize(new { disputeId = dispute.PublicId, transactionId }), StatusCode = "PENDING", OccurredAt = now, AvailableAt = now, IdempotencyKey = $"dispute-opened:{dispute.PublicId:N}", CreatedByUserId = identity.UserId }); await db.SaveChangesAsync(token); return await Build(dispute.Id, identity.UserId, token);
    }
    public async Task<CustomerDisputeEvidenceResponse> Upload(ClaimsPrincipal principal, Guid disputeId, string? description, IFormFile upload, CancellationToken token)
    {
        var identity = await Customer(principal, token); var dispute = await db.DisputeCases.SingleOrDefaultAsync(x => x.PublicId == disputeId && x.ApplicantUserId == identity.UserId, token) ?? throw NotFound();
        if (upload.Length <= 0 || upload.Length > 10 * 1024 * 1024) throw Invalid("DISPUTE_FILE_SIZE_INVALID", "파일은 10MB 이하여야 합니다."); var rules = new Dictionary<string, (string, byte[])>(StringComparer.OrdinalIgnoreCase) { { "image/jpeg", (".jpg", [0xff, 0xd8, 0xff]) }, { "image/png", (".png", [0x89, 0x50, 0x4e, 0x47]) }, { "application/pdf", (".pdf", Encoding.ASCII.GetBytes("%PDF")) } }; if (!rules.TryGetValue(upload.ContentType, out var rule)) throw Invalid("DISPUTE_FILE_TYPE_INVALID", "JPEG, PNG, PDF만 첨부할 수 있습니다.");
        var name = Path.GetFileName(upload.FileName); if (name != upload.FileName || string.IsNullOrWhiteSpace(name)) throw Invalid("DISPUTE_FILE_NAME_INVALID", "안전한 파일명을 사용해 주세요."); await using var source = upload.OpenReadStream(); using var memory = new MemoryStream(); await source.CopyToAsync(memory, token); var bytes = memory.ToArray(); if (!bytes.AsSpan().StartsWith(rule.Item2)) throw Invalid("DISPUTE_FILE_SIGNATURE_INVALID", "파일 형식이 일치하지 않습니다.");
        var now = DateTime.UtcNow; var key = $"dispute/{dispute.PublicId:N}/{Guid.NewGuid():N}{rule.Item1}"; var file = new StoredFile { PurposeCode = "DISPUTE_EVIDENCE", StorageContainer = "development-private", StorageKey = key, StorageKeyHash = SHA256.HashData(Encoding.UTF8.GetBytes(key)), OriginalFileName = name, ContentType = upload.ContentType, SizeBytes = bytes.Length, Sha256Hex = Convert.ToHexString(SHA256.HashData(bytes)).ToLowerInvariant(), StatusCode = "PENDING", UploadedByUserId = identity.UserId, CreatedAt = now }; db.Files.Add(file); await db.SaveChangesAsync(token); try { await using var content = new MemoryStream(bytes); await storage.SaveAsync(key, content, token); file.StatusCode = "ACTIVE"; file.ActivatedAt = now; file.ScanResultText = "NOT_INTEGRATED"; var evidence = new DisputeEvidence { DisputeCaseId = dispute.Id, FileId = file.Id, SubmittedByUserId = identity.UserId, SourceTypeCode = "CUSTOMER_UPLOAD", Description = Clean(description), StatusCode = "ACTIVE", SubmittedAt = now, CreatedAt = now, CreatedByUserId = identity.UserId }; db.DisputeEvidence.Add(evidence); await db.SaveChangesAsync(token); return new(evidence.PublicId, file.PublicId, evidence.SourceTypeCode, evidence.Description, evidence.SubmittedAt, $"/api/v1/customers/me/dispute-files/{file.PublicId}"); } catch { await storage.DeleteIfExistsAsync(key, token); throw; }
    }
    public async Task<(Stream, string, string)> Open(ClaimsPrincipal principal, Guid fileId, CancellationToken token) { var identity = await Customer(principal, token); var file = await (from f in db.Files.AsNoTracking() join e in db.DisputeEvidence.AsNoTracking() on f.Id equals e.FileId join d in db.DisputeCases.AsNoTracking() on e.DisputeCaseId equals d.Id where f.PublicId == fileId && d.ApplicantUserId == identity.UserId && f.StatusCode == "ACTIVE" select f).SingleOrDefaultAsync(token) ?? throw NotFound(); return (await storage.OpenReadAsync(file.StorageKey, token), file.ContentType, file.OriginalFileName); }
    private async Task<CustomerDisputeResponse> Build(long id, long customerUserId, CancellationToken token)
    {
        var row = await db.DisputeCases.AsNoTracking().SingleAsync(x => x.Id == id && x.ApplicantUserId == customerUserId, token);
        var transactionId = await db.Transactions.AsNoTracking().Where(x => x.Id == row.TransactionId).Select(x => (Guid?)x.PublicId).SingleOrDefaultAsync(token);
        var interiorProjectId = await db.InteriorProjects.AsNoTracking().Where(x => x.Id == row.InteriorProjectId).Select(x => (Guid?)x.PublicId).SingleOrDefaultAsync(token);
        var split = row.Description.Split("\n\n[요구사항]\n", 2);
        var evidence = await (from e in db.DisputeEvidence.AsNoTracking() join f0 in db.Files.AsNoTracking() on e.FileId equals f0.Id into files from f in files.DefaultIfEmpty() where e.DisputeCaseId == id && e.StatusCode == "ACTIVE" orderby e.SubmittedAt select new CustomerDisputeEvidenceResponse(e.PublicId, f == null ? null : f.PublicId, e.SourceTypeCode, e.Description, e.SubmittedAt, f == null ? null : "/api/v1/customers/me/dispute-files/" + f.PublicId)).ToListAsync(token);
        var resolution = await db.DisputeResolutions.AsNoTracking().Where(x => x.DisputeCaseId == id && x.IsCurrent).Select(x => new { x.ResultSummary, x.FollowUpAction }).SingleOrDefaultAsync(token);
        var updates = await db.DisputeActions.AsNoTracking().Where(x => x.DisputeCaseId == id && x.ToStatusCode != null && (x.ActionTypeCode == "CREATED" || x.ActionTypeCode == "STATUS_CHANGE" || x.ActionTypeCode == "RESOLUTION")).OrderBy(x => x.OccurredAt).Select(x => new CustomerDisputeUpdate(Display(x.ToStatusCode!), x.OccurredAt)).ToListAsync(token);
        return new(row.PublicId, transactionId, interiorProjectId, row.Subject, split[0], split.Length > 1 ? split[1] : "", row.StatusCode, Display(row.StatusCode), row.ReceivedAt, row.ResolvedAt, resolution?.ResultSummary, resolution?.FollowUpAction, evidence, updates);
    }
    private async Task<(long UserId, long ProfileId)> Customer(ClaimsPrincipal p, CancellationToken t) { var id = Guid.Parse(p.FindFirstValue(ClaimTypes.NameIdentifier)!); var value = await (from u in db.Users where u.PublicId == id && u.StatusCode == "ACTIVE" join c in db.CustomerProfiles on u.Id equals c.UserId select new { u.Id, Profile = c.Id }).SingleOrDefaultAsync(t); return value is null ? throw new WorkBusinessException("CUSTOMER_PROFILE_REQUIRED", "고객 프로필이 필요합니다.", 403) : (value.Id, value.Profile); }
    private static string Required(string? v, int max) { var x = v?.Trim(); if (string.IsNullOrWhiteSpace(x) || x.Length > max) throw Invalid("DISPUTE_INPUT_INVALID", "필수 입력값을 확인해 주세요."); return x; }
    private static string? Clean(string? v) => string.IsNullOrWhiteSpace(v) ? null : v.Trim(); private static string Display(string s) => s switch { "OPEN" => "접수", "UNDER_REVIEW" => "검토 중", "WAITING_CUSTOMER" => "고객 확인 대기", "WAITING_PROVIDER" => "공급자 확인 대기", "RESOLVED" => "처리 완료", "CLOSED" => "종료", _ => "진행 중" }; private static WorkBusinessException NotFound() => new("DISPUTE_NOT_FOUND", "분쟁을 찾을 수 없습니다.", 404); private static WorkBusinessException Invalid(string c, string m) => new(c, m, 400);
}
