import { useCallback,useEffect,useMemo,useRef,useState } from 'react'
import { createPortal } from 'react-dom'
import { HubConnectionBuilder,LogLevel } from '@microsoft/signalr'
import { navigate } from '../auth/routing'
import { apiUrl } from '../config/apiEndpoint'
import { getProviderRequestStatus } from './api'
import { providerRoute } from './providerDisplay'
import type { ProviderHubWorkItem,ProviderRequestStatus } from './types'
import { getQuoteSubmissionReadiness } from '../quotes/api'
import type { QuoteSubmissionReadiness } from '../quotes/types'
import './providerRequestPopup.css'

const requestTypes=new Set(['GENERAL_REQUEST','CARE_REQUEST','INTERIOR_REQUEST','EMERGENCY_REQUEST'])
const tabs=[['','전체'],['GENERAL','견적'],['CARE','케어'],['INTERIOR','인테리어'],['EMERGENCY','긴급']] as const
const cacheKey='soodal-provider-request-popup'

export function ProviderRequestStatusPopup(){
  const [open,setOpen]=useState(false),[filter,setFilter]=useState(''),[loading,setLoading]=useState(true),[error,setError]=useState('')
  const [hub,setHub]=useState<ProviderRequestStatus|null>(null),[selected,setSelected]=useState<ProviderHubWorkItem|null>(null),[live,setLive]=useState(false),[hasNew,setHasNew]=useState(false)
  const knownIds=useRef(new Set<string>()),hubRef=useRef<ProviderRequestStatus|null>(null),liveRef=useRef(false)
  const load=useCallback(async(announce=false)=>{try{const next=await getProviderRequestStatus();const incoming=next.items.filter(item=>requestTypes.has(item.type));if(announce&&knownIds.current.size>0&&incoming.some(item=>!knownIds.current.has(`${item.type}:${item.publicId}`)))setHasNew(true);knownIds.current=new Set(incoming.map(item=>`${item.type}:${item.publicId}`));hubRef.current=next;setHub(next);setError('');localStorage.setItem(cacheKey,JSON.stringify(next))}catch(reason){setError(reason instanceof Error?reason.message:'요청현황을 불러오지 못했습니다.');if(!hubRef.current){const cached=localStorage.getItem(cacheKey);if(cached)try{const value=JSON.parse(cached) as ProviderRequestStatus;hubRef.current=value;setHub(value)}catch{/* invalid cache */}}}finally{setLoading(false)}},[])
  useEffect(()=>{void load();const refresh=()=>{if(document.visibilityState==='visible'&&navigator.onLine)void load(true)};const timer=window.setInterval(()=>{if(!liveRef.current)refresh()},60000);window.addEventListener('focus',refresh);window.addEventListener('online',refresh);document.addEventListener('visibilitychange',refresh);return()=>{window.clearInterval(timer);window.removeEventListener('focus',refresh);window.removeEventListener('online',refresh);document.removeEventListener('visibilitychange',refresh)}},[load])
  useEffect(()=>{const setConnection=(value:boolean)=>{liveRef.current=value;setLive(value)};const realtime=new HubConnectionBuilder().withUrl(apiUrl('/hubs/provider-work-inbox'),{withCredentials:true}).withAutomaticReconnect([0,2000,5000,10000]).configureLogging(LogLevel.Warning).build();realtime.on('InboxChanged',()=>void load(true));realtime.onreconnecting(()=>setConnection(false));realtime.onreconnected(()=>{setConnection(true);void load(true)});realtime.onclose(()=>setConnection(false));void realtime.start().then(()=>setConnection(true)).catch(()=>setConnection(false));return()=>{void realtime.stop().catch(()=>undefined)}},[load])
  useEffect(()=>{if(!open)return;const close=(event:KeyboardEvent)=>{if(event.key==='Escape'){setOpen(false);setSelected(null)}};document.addEventListener('keydown',close);document.body.classList.add('providerRequestPopupOpen');return()=>{document.removeEventListener('keydown',close);document.body.classList.remove('providerRequestPopupOpen')}},[open])
  const requests=useMemo(()=>(hub?.items??[]).filter(item=>requestTypes.has(item.type)),[hub]),visible=useMemo(()=>requests.filter(item=>!filter||item.domain===filter),[filter,requests]),urgent=requests.filter(item=>item.domain==='EMERGENCY').length
  const show=()=>{setOpen(true);setHasNew(false);setSelected(null);void load()},close=()=>{setOpen(false);setSelected(null)},go=(item:ProviderHubWorkItem)=>{const route=providerRoute(item.route);close();navigate(item.type==='CARE_REQUEST'?`${route}?requestId=${encodeURIComponent(item.publicId)}`:route)}
  return <><button type="button" className={`providerRequestStatusButton${hasNew?' hasNew':''}${urgent?' hasUrgent':''}`} onClick={show} aria-haspopup="dialog" aria-label={`실시간 요청현황 ${requests.length}건${urgent?`, 긴급 ${urgent}건`:''}`}><span>요청현황</span><b>{requests.length>99?'99+':requests.length}</b></button>{open&&createPortal(<div className="providerRequestPopupLayer"><button className="providerRequestPopupBackdrop" type="button" aria-label="요청현황 닫기" onClick={close}/><section className="providerRequestPopup" role="dialog" aria-modal="true" aria-labelledby="provider-request-popup-title"><header><div><small>수달 실시간</small><h2 id="provider-request-popup-title">{selected?'요청 상세':'실시간 요청현황'}</h2></div><div className={`providerRequestLive ${live?'connected':''}`}><i/>{live?'실시간':'자동 확인'}</div><button type="button" aria-label="닫기" onClick={close}>×</button></header>{selected?<RequestDetail item={selected} onBack={()=>setSelected(null)} onSubmit={()=>go(selected)}/>:<><p className="providerRequestPopupIntro">설정한 서비스 분야·활동지역·승인 조건과 일치하는 요청만 표시됩니다.</p>{hub&&<button type="button" className={`providerRequestWalletStrip${hub.wallet.requiresAttention?' warning':''}`} onClick={()=>{close();navigate('/provider/wallet')}}><span>사용 가능 이용료 <b>{formatMoney(hub.wallet.availableBalance)}</b></span><small>예약 중 {formatMoney(hub.wallet.reservedBalance)} · 이용료 관리 ›</small></button>}<nav aria-label="요청 종류">{tabs.map(([code,label])=><button type="button" className={filter===code?'active':''} key={code} onClick={()=>setFilter(code)}>{label}<b>{code?requests.filter(item=>item.domain===code).length:requests.length}</b></button>)}</nav>{error&&<div className="providerRequestPopupError"><span>{error}</span><button type="button" onClick={()=>void load()}>다시 확인</button></div>}<div className="providerRequestPopupList" aria-live="polite">{visible.map(item=><button type="button" className={`providerRequestCall domain-${item.domain.toLowerCase()}`} key={`${item.type}-${item.publicId}`} onClick={()=>setSelected(item)}><span className="providerRequestCallTop"><b>{domainLabel(item.domain)}</b><time>{when(item.scheduledAt,hub?.generatedAt)}</time></span><strong>{item.title}</strong><small>{item.description}</small><span className="providerRequestCallBottom"><em>{item.badge}</em><b>수수료·요청 확인 ›</b></span></button>)}{!visible.length&&!loading&&<div className="providerRequestPopupEmpty"><strong>현재 조건에 맞는 새 요청이 없습니다.</strong><span>새 요청이 배정되면 목록과 상단 숫자가 자동으로 갱신됩니다.</span></div>}{loading&&!hub&&<div className="providerRequestPopupEmpty"><strong>요청을 확인하고 있습니다.</strong></div>}</div><footer><span>최근 갱신 {when(hub?.generatedAt??null)}</span><button type="button" onClick={()=>{close();navigate('/provider/inbox')}}>전체 업무 보기</button></footer></>}</section></div>,document.body)}</>
}
function RequestDetail({item,onBack,onSubmit}:{item:ProviderHubWorkItem;onBack:()=>void;onSubmit:()=>void}){const[readiness,setReadiness]=useState<QuoteSubmissionReadiness|null>(null),[feeError,setFeeError]=useState('');const supportsQuote=item.type==='GENERAL_REQUEST'||item.type==='INTERIOR_REQUEST';useEffect(()=>{if(!supportsQuote)return;getQuoteSubmissionReadiness(item.publicId).then(value=>{setReadiness(value);setFeeError('')}).catch(reason=>setFeeError(reason instanceof Error?reason.message:'예상 수수료를 확인하지 못했습니다.'))},[item.publicId,supportsQuote]);const prepareCharge=()=>{if(!readiness)return;const shortfall=Math.max(0,readiness.expectedAcceptanceFee-readiness.availableWalletBalance);navigate(`/provider/wallet?returnUrl=${encodeURIComponent(providerRoute(item.route))}&requestId=${encodeURIComponent(item.publicId)}&expectedFee=${readiness.expectedAcceptanceFee}&shortfall=${shortfall}`)};return <div className="providerRequestDetail"><button type="button" className="providerRequestBack" onClick={onBack}>‹ 목록으로</button><div className={`providerRequestDetailHero domain-${item.domain.toLowerCase()}`}><span>{domainLabel(item.domain)}</span><b>{item.badge}</b><h3>{item.title}</h3><p>{item.description}</p></div><dl><div><dt>요청 상태</dt><dd>{item.badge}</dd></div><div><dt>희망 일정</dt><dd>{when(item.scheduledAt)}</dd></div><div><dt>응답기한</dt><dd>{when(item.actionDueAt)}</dd></div><div><dt>다음 처리</dt><dd>{item.nextAction}</dd></div></dl>{readiness&&<section className={`providerRequestFeeStatus${readiness.canSubmit?' ready':' warning'}`}><div><span>예상 수수료</span><b>{formatMoney(readiness.expectedAcceptanceFee)}</b></div><div><span>사용 가능 이용료</span><b>{formatMoney(readiness.availableWalletBalance)}</b></div><div><span>제출 후 예상 잔액</span><b>{formatMoney(Math.max(0,readiness.availableWalletBalance-readiness.expectedAcceptanceFee))}</b></div><p>{readiness.canSubmit?'제출할 수 있습니다. 수수료는 채택 전까지 일시 예약됩니다.':`이용료 잔액이 ${formatMoney(Math.max(0,readiness.expectedAcceptanceFee-readiness.availableWalletBalance))} 부족합니다.`}</p></section>}{feeError&&<div className="providerRequestPopupError"><span>{feeError}</span></div>}<div className="providerRequestPrivacy">고객이 전문가를 선택하기 전에는 정확한 주소와 전화번호가 공개되지 않습니다.</div>{readiness?.unavailableReason==='WALLET_INSUFFICIENT_BALANCE'?<button type="button" className="providerRequestSubmit" onClick={prepareCharge}>이용료 결제하기</button>:<button type="button" className="providerRequestSubmit" onClick={onSubmit}>{actionLabel(item.domain)}</button>}</div>}
const domainLabel=(domain:string)=>domain==='EMERGENCY'?'긴급출동':domain==='CARE'?'수달 케어':domain==='INTERIOR'?'수달 인테리어':'일반 서비스'
const actionLabel=(domain:string)=>domain==='EMERGENCY'?'출동 가능 응답하기':domain==='CARE'?'케어 조건 제안하기':domain==='INTERIOR'?'인테리어 제안하기':'견적 제출하기'
const when=(value:string|null,fallback?:string)=>{const source=value??fallback;return source?new Intl.DateTimeFormat('ko-KR',{month:'short',day:'numeric',hour:'2-digit',minute:'2-digit'}).format(new Date(source)):'일정 협의'}
const formatMoney=(value:number)=>new Intl.NumberFormat('ko-KR',{style:'currency',currency:'KRW',maximumFractionDigits:0}).format(value)
