import { useEffect, useMemo, useState } from 'react'
import { navigate } from '../auth/routing'
import { ProviderAppLayout } from './ProviderAppLayout'
import { getProviderWallet, type ProviderWalletDashboard } from './walletApi'

const money=(value:number,currency='KRW')=>new Intl.NumberFormat('ko-KR',{style:'currency',currency,maximumFractionDigits:0}).format(value)
const date=(value:string|null)=>value?new Date(value).toLocaleString('ko-KR'):'-'
const labels:Record<string,string>={CHARGE:'충전',USE:'수수료 차감',RESTORE:'수수료 복원',REFUND:'잔액 환불',ADJUST:'관리자 조정',REQUESTED:'요청',APPROVED:'승인',PROCESSING:'처리 중',COMPLETED:'완료',SUCCEEDED:'완료',FAILED:'실패',CANCELLED:'취소',REJECTED:'반려',NOT_RESTORED:'미복원',RESTORED:'복원'}
type Tab='ALL'|'CHARGE'|'USE'|'RESTORE'|'REFUND'|'ADJUST'

export function ProviderWalletPage(){
 const[data,setData]=useState<ProviderWalletDashboard|null>(null),[tab,setTab]=useState<Tab>('ALL'),[error,setError]=useState('')
 useEffect(()=>{getProviderWallet().then(setData).catch(reason=>setError(reason instanceof Error?reason.message:'충전금 정보를 불러오지 못했습니다.'))},[])
 const ledger=useMemo(()=>data?.recentLedger.filter(item=>tab==='ALL'||item.entryTypeCode===tab)??[],[data,tab])
 return <ProviderAppLayout><section className="providerWalletHero"><div><p>PREPAID WALLET</p><h1>충전금·수수료</h1><span>견적 채택 수수료와 모든 잔액 변동을 실제 원장 기준으로 확인합니다.</span></div><div><small>현재 가용잔액</small><strong>{money(data?.availableBalance??0,data?.currencyCode)}</strong><span>{labels[data?.statusCode??'']??data?.statusCode??'확인 중'}</span></div></section>
 {error&&<div className="providerAlert error">{error}</div>}{!data&&!error?<p className="emptyState">Wallet을 불러오는 중입니다.</p>:data&&<>
 <section className="providerWalletSummary"><article><span>총 충전</span><strong>{money(data.totalCharged)}</strong></article><article><span>총 사용</span><strong>{money(data.totalUsed)}</strong></article><article><span>총 복원</span><strong>{money(data.totalRestored)}</strong></article><article><span>총 환불</span><strong>{money(data.totalRefunded)}</strong></article><article><span>보류잔액</span><strong>{money(data.reservedBalance)}</strong></article></section>
 <section className="providerPanel providerWalletPolicy" aria-labelledby="wallet-fee-policy-title"><div className="sectionHeading"><div><p className="eyebrow">FEE POLICY</p><h2 id="wallet-fee-policy-title">수수료는 이렇게 차감돼요</h2></div><span>본사 정책 자동 반영</span></div><p className="providerWalletPolicyIntro">견적을 보내는 것만으로는 충전금이 차감되지 않습니다. 아래 기준에 따라 실제 거래원장에 기록됩니다.</p><ul><li><strong>카테고리별 정책 금액 적용</strong><span>수수료와 차감금액은 서비스 카테고리별 본사 관리자 정책값을 기준으로 자동 결정되며, 화면에 고정된 금액을 사용하지 않습니다.</span></li><li><strong>견적 채택 시 차감</strong><span>기본 차감 시점은 고객이 해당 공급자의 견적을 채택하는 시점입니다.</span></li><li><strong>미채택 견적은 차감 없음</strong><span>고객이 채택하지 않은 견적에는 충전금이 차감되지 않습니다.</span></li><li><strong>취소·환불·조정도 원장 기록</strong><span>거래 취소, 수수료 환불·복원 또는 관리자 조정이 발생하면 처리 내용과 처리 후 잔액이 거래원장에 기록됩니다.</span></li></ul></section>
 <section className="providerPanel providerWalletNotice"><h2>충전 안내</h2><p>{data.chargeGuidance}</p><b>{data.actualPaymentIntegrated?'실제 결제 연동':'실제 PG 미연동'}</b></section>
 <div className="providerWalletLayout"><main><section className="providerPanel"><div className="sectionHeading"><div><p className="eyebrow">LEDGER</p><h2>거래원장</h2></div><span>최근 100건</span></div><nav className="walletFilter" aria-label="원장 유형">{([['ALL','전체'],['CHARGE','충전'],['USE','사용·차감'],['RESTORE','취소·복원'],['REFUND','환불'],['ADJUST','조정']] as const).map(([code,name])=><button className={tab===code?'active':''} key={code} onClick={()=>setTab(code)}>{name}</button>)}</nav><div className="providerWalletRows">{ledger.map(item=><article key={item.id}><div><b>{labels[item.entryTypeCode]??item.entryTypeCode}</b><strong className={item.amount<0?'out':'in'}>{item.amount>0?'+':''}{money(item.amount)}</strong></div><p>{item.reason}</p><span>{date(item.occurredAt)} · 처리 후 {money(item.balanceAfter)}</span>{item.transactionId&&<button onClick={()=>navigate(`/provider/work/${item.transactionId}`)}>관련 거래</button>}</article>)}{!ledger.length&&<p className="emptyState">해당 원장 내역이 없습니다.</p>}</div></section>
 <section className="providerPanel"><h2>거래별 수수료</h2><div className="providerWalletRows">{data.feeCharges.map(item=><article key={item.id}><div><b>{item.serviceName}</b><strong>{money(item.feeAmount)}</strong></div><span>{date(item.chargedAt)} · {labels[item.restoreStatusCode]??item.restoreStatusCode}</span><button onClick={()=>navigate(`/provider/work/${item.transactionId}`)}>거래 상세</button></article>)}{!data.feeCharges.length&&<p className="emptyState">차감된 거래 수수료가 없습니다.</p>}</div></section></main>
 <aside><section className="providerPanel"><h2>충전 처리내역</h2>{data.charges.map(item=><article className="providerWalletCompact" key={item.id}><b>{money(item.requestedAmount)}</b><span>{labels[item.statusCode]??item.statusCode} · {date(item.requestedAt)}</span><small>{item.paymentMethodCode==='DEVELOPMENT_MANUAL'?'개발용 수동 확인':item.paymentMethodCode}</small></article>)}{!data.charges.length&&<p className="emptyState">충전 처리내역이 없습니다.</p>}</section><section className="providerPanel"><h2>환불·탈퇴 잔액</h2><p>{data.refundGuidance}</p>{data.withdrawalRefundRequired&&<b className="providerWalletWarning">탈퇴 완료 전 잔액·진행업무 검토 필요</b>}{data.refunds.map(item=><article className="providerWalletCompact" key={item.id}><b>{money(item.requestedAmount)}</b><span>{labels[item.statusCode]??item.statusCode} · {date(item.requestedAt)}</span><small>{item.requestReason}</small></article>)}</section></aside></div></>}</ProviderAppLayout>
}
