import { useEffect, useMemo, useState } from 'react'
import { isSafeInternalReturnUrl, navigate } from '../auth/routing'
import { ProviderAppLayout } from './ProviderAppLayout'
import { confirmWalletTopUp, getProviderWallet, prepareWalletTopUp, type ProviderWalletDashboard } from './walletApi'

const money=(value:number,currency='KRW')=>new Intl.NumberFormat('ko-KR',{style:'currency',currency,maximumFractionDigits:0}).format(value)
const date=(value:string|null)=>value?new Date(value).toLocaleString('ko-KR'):'-'
const labels=new Proxy<Record<string,string>>({CHARGE:'결제',RESERVE:'예상 수수료 예약',RELEASE:'예약 해제',USE:'수수료 차감',RESTORE:'수수료 복원',REFUND:'잔액 환불',ADJUST:'관리자 조정',REQUESTED:'요청',APPROVED:'승인',PROCESSING:'처리 중',COMPLETED:'완료',SUCCEEDED:'완료',FAILED:'실패',CANCELLED:'취소',REJECTED:'반려',NOT_RESTORED:'미복원',RESTORED:'복원'},{get:(target,key:string)=>target[key]??'상태 확인 중'})
const taxLabels=new Proxy<Record<string,string>>({DEPOSIT:'예치금(매출 아님)',EXPECTED_VAT_INCLUDED:'예상 수수료(부가세 포함)',EXPECTED_REVERSED:'예약 해제',TAXABLE_VAT_INCLUDED:'과세 수수료(부가세 포함)',TAX_REVERSED:'수수료 취소',NON_TAXABLE:'비과세 조정',LEGACY_UNSPLIT:'기존 미분리 내역'},{get:(target,key:string)=>target[key]??'과세 구분 확인 중'})
const paymentMethod=(value:string)=>value==='DEVELOPMENT_MANUAL'?'개발용 수동 확인':'결제수단 확인 중'
type Tab='ALL'|'CHARGE'|'USE'|'RESTORE'|'REFUND'|'ADJUST'
type PaymentResult={kind:'confirming'|'success'|'failure';amount?:number;balance?:number;message?:string}

export function ProviderWalletPage(){
 const[data,setData]=useState<ProviderWalletDashboard|null>(null),[tab,setTab]=useState<Tab>('ALL'),[error,setError]=useState(''),[topUpBusy,setTopUpBusy]=useState(false),[refundPolicyAccepted,setRefundPolicyAccepted]=useState(false),[paymentResult,setPaymentResult]=useState<PaymentResult|null>(()=>{const query=new URLSearchParams(window.location.search);return query.get('topUp')==='success'?{kind:'confirming'}:query.get('topUp')==='fail'?{kind:'failure',message:query.get('message')??'결제가 완료되지 않았습니다.'}:null})
 const context=useMemo(()=>{const query=new URLSearchParams(window.location.search),returnUrl=query.get('returnUrl'),expectedFee=Number(query.get('expectedFee')??0),shortfall=Number(query.get('shortfall')??0);return{requestId:query.get('requestId'),returnUrl:isSafeInternalReturnUrl(returnUrl)?returnUrl:null,expectedFee:Number.isFinite(expectedFee)&&expectedFee>0?expectedFee:0,shortfall:Number.isFinite(shortfall)&&shortfall>0?shortfall:0}},[])
 const load=()=>getProviderWallet().then(setData).catch(reason=>setError(reason instanceof Error?reason.message:'이용료 정보를 불러오지 못했습니다.'))
 useEffect(()=>{void load();const query=new URLSearchParams(window.location.search);if(query.get('topUp')==='success'){const paymentKey=query.get('paymentKey'),orderId=query.get('orderId'),amount=Number(query.get('amount'));if(paymentKey&&orderId&&Number.isFinite(amount)&&amount>0){setTopUpBusy(true);confirmWalletTopUp(paymentKey,orderId,amount).then(result=>{setPaymentResult({kind:'success',amount:result.amount,balance:result.availableBalance});window.history.replaceState({},'',window.location.pathname);return load()}).catch(reason=>setPaymentResult({kind:'failure',message:reason instanceof Error?reason.message:'결제 승인을 확인하지 못했습니다.'})).finally(()=>setTopUpBusy(false))}else{setPaymentResult({kind:'failure',message:'결제 승인 정보가 올바르지 않습니다.'})}}else if(query.get('topUp')==='fail'){window.history.replaceState({},'',window.location.pathname)}},[])
 const topUp=async(amount:number)=>{if(!refundPolicyAccepted){setError('결제 전에 일반결제 취소·환불정책을 확인해 주세요.');return}setTopUpBusy(true);setError('');setPaymentResult(null);try{const prepared=await prepareWalletTopUp(amount);const successUrl=new URL(prepared.successPath,window.location.origin),failUrl=new URL(prepared.failPath,window.location.origin);if(context.returnUrl){successUrl.searchParams.set('returnUrl',context.returnUrl);failUrl.searchParams.set('returnUrl',context.returnUrl)}const factory=await loadWalletTossPayments();await factory(prepared.clientKey).payment({customerKey:prepared.customerKey}).requestPayment({method:'CARD',amount:{currency:'KRW',value:prepared.amount},orderId:prepared.orderId,orderName:`${prepared.orderName} ${money(prepared.amount)}`,successUrl:successUrl.toString(),failUrl:failUrl.toString()})}catch(reason){setError(reason instanceof Error?reason.message:'결제를 시작하지 못했습니다.');setTopUpBusy(false)}}
 const ledger=useMemo(()=>data?.recentLedger.filter(item=>tab==='ALL'||item.entryTypeCode===tab)??[],[data,tab])
 return <ProviderAppLayout><section className="providerWalletHero"><div><p>선결제 이용료</p><h1>이용료·수수료</h1><span>견적 채택 수수료와 모든 잔액 변동을 실제 원장 기준으로 확인합니다.</span></div><div><small>현재 가용잔액</small><strong>{money(data?.availableBalance??0,data?.currencyCode)}</strong><span>{data?labels[data.statusCode]:'상태 확인 중'}</span></div></section>
 {paymentResult&&<section className={`providerPaymentResult ${paymentResult.kind}`} role="status" aria-live="polite"><div className="providerPaymentResultIcon" aria-hidden="true">{paymentResult.kind==='confirming'?'…':paymentResult.kind==='success'?'✓':'!'}</div><div><p>{paymentResult.kind==='confirming'?'결제 승인 확인 중':paymentResult.kind==='success'?'결제 완료':'결제 미완료'}</p><h2>{paymentResult.kind==='confirming'?'토스 결제를 안전하게 승인하고 있어요.':paymentResult.kind==='success'?`${money(paymentResult.amount??0)} 이용료가 반영되었습니다.`:paymentResult.message}</h2>{paymentResult.kind==='success'&&<span>현재 사용 가능 잔액 {money(paymentResult.balance??0)}</span>}{paymentResult.kind==='failure'&&<span>잔액은 변경되지 않았습니다. 다시 시도하거나 고객센터로 문의해 주세요.</span>}<div>{paymentResult.kind!=='confirming'&&<button type="button" onClick={()=>setPaymentResult(null)}>{paymentResult.kind==='success'?'결제내역 확인':'다시 결제'}</button>}{context.returnUrl&&paymentResult.kind==='success'&&<button type="button" className="secondary" onClick={()=>navigate(context.returnUrl!)}>작성 중인 견적으로 돌아가기</button>}</div></div></section>}
 {error&&<div className="providerAlert error">{error}</div>}{!data&&!error?<p className="emptyState">이용료 정보를 불러오는 중입니다.</p>:data&&<>
 <section className="providerWalletSummary"><article><span>총 결제</span><strong>{money(data.totalCharged)}</strong></article><article><span>총 사용</span><strong>{money(data.totalUsed)}</strong></article><article><span>총 복원</span><strong>{money(data.totalRestored)}</strong></article><article><span>총 환불</span><strong>{money(data.totalRefunded)}</strong></article><article><span>보류잔액</span><strong>{money(data.reservedBalance)}</strong></article></section>
 {context.expectedFee>0&&<section className="providerPanel providerWalletChargeContext"><div><p className="eyebrow">견적 이용료 잔액</p><h2>견적 제출을 위한 이용료</h2><span>예상 수수료 {money(context.expectedFee)} · 현재 부족금액 {money(Math.max(0,context.expectedFee-data.availableBalance))}</span></div><div className="providerWalletEstimate"><strong>현재 잔액으로 약 {Math.floor(data.availableBalance/context.expectedFee)}건</strong><span>동일한 예상 수수료의 견적을 제출할 수 있습니다.</span></div>{context.returnUrl&&<button type="button" className="providerWalletReturn" onClick={()=>navigate(context.returnUrl!)}>작성 중인 견적으로 돌아가기</button>}</section>}
 <section className="providerPanel providerWalletTopUp" id="wallet-top-up-products"><div className="sectionHeading"><div><p className="eyebrow">토스 일반결제</p><h2>이용료 선결제</h2></div><span className={data.paymentMode==='TEST'?'test':'live'}>{data.paymentMode==='TEST'?'심사용 테스트':data.paymentMode==='PRODUCTION'?'실제 결제':'결제 준비 중'}</span></div><p>상품을 선택하면 토스페이먼츠 카드·간편결제창으로 이동합니다. 1회 최대 500,000원, 월 누적 {money(data.monthlyPurchaseLimit)}까지 결제할 수 있습니다.</p><div className="providerWalletMonthly"><span>이번 달 결제</span><strong>{money(data.monthlyPurchasedAmount)}</strong><small>남은 한도 {money(Math.max(0,data.monthlyPurchaseLimit-data.monthlyPurchasedAmount))}</small></div><div className="providerWalletProducts">{data.topUpProducts.map(amount=><article key={amount}><small>1회 일반결제</small><strong>{money(amount)}</strong><span>토스 카드·간편결제</span><button type="button" disabled={!data.actualPaymentIntegrated||topUpBusy||data.monthlyPurchasedAmount+amount>data.monthlyPurchaseLimit} onClick={()=>void topUp(amount)}>{topUpBusy?'결제 준비 중…':`${money(amount)} 결제`}</button></article>)}</div><label className="providerWalletRefundConsent"><input type="checkbox" checked={refundPolicyAccepted} onChange={event=>setRefundPolicyAccepted(event.target.checked)}/><span><a href="/policies/general-payment-refund" target="_blank" rel="noreferrer">일반결제 취소·환불정책</a>을 확인했습니다.</span></label><p className="providerWalletChargePending">{data.chargeGuidance} 결제창을 닫거나 승인이 실패하면 잔액은 바뀌지 않습니다.</p></section>
 <section className="providerPanel providerWalletPolicy" aria-labelledby="wallet-fee-policy-title"><div className="sectionHeading"><div><p className="eyebrow">수수료 정책</p><h2 id="wallet-fee-policy-title">수수료는 이렇게 차감돼요</h2></div><span>본사 정책 자동 반영</span></div><p className="providerWalletPolicyIntro">견적 제출 시 예상 수수료가 예약되어 사용 가능 잔액에서 일시 보류됩니다. 고객이 견적을 채택하면 실제 수수료로 확정되며, 미채택·만료 시 자동으로 반환됩니다.</p><ul><li><strong>카테고리별 정책 금액 적용</strong><span>수수료와 예약금액은 서비스 카테고리별 본사 관리자 정책값을 기준으로 자동 결정되며, 화면에 고정된 금액을 사용하지 않습니다.</span></li><li><strong>견적 제출 시 일시 예약</strong><span>예상 수수료가 보류잔액으로 이동하며 다른 견적이나 광고비에 중복 사용되지 않습니다.</span></li><li><strong>견적 채택 시 확정 차감</strong><span>고객이 해당 전문가의 견적을 채택하는 시점에 예약금이 실제 수수료로 확정됩니다.</span></li><li><strong>미채택·만료 시 자동 반환</strong><span>채택되지 않았거나 견적이 만료되면 예약금이 사용 가능 잔액으로 자동 반환됩니다.</span></li></ul><a className="providerWalletPolicyLink" href="/policies/general-payment-refund" target="_blank" rel="noreferrer">일반결제 취소·환불정책 확인</a></section>
 <section className="providerPanel providerWalletNotice"><h2>결제·세금 안내</h2><p>{data.chargeGuidance}</p><p>선결제한 이용료는 이용료 잔액으로 기록하며 결제 시점에는 선수금으로 관리합니다. 실제 수수료가 차감될 때 차감액을 부가세 포함 금액으로 공급가액과 부가세로 나누어 기록합니다.</p><b>{data.actualPaymentIntegrated?'실제 결제 연동':'실제 결제 미연동'}</b></section>
 <div className="providerWalletLayout"><main><section className="providerPanel"><div className="sectionHeading"><div><p className="eyebrow">이용료 내역</p><h2>거래원장</h2></div><span>최근 100건</span></div><nav className="walletFilter" aria-label="원장 유형">{([['ALL','전체'],['CHARGE','결제'],['USE','사용·차감'],['RESTORE','취소·복원'],['REFUND','환불'],['ADJUST','조정']] as const).map(([code,name])=><button className={tab===code?'active':''} key={code} onClick={()=>setTab(code)}>{name}</button>)}</nav><div className="providerWalletRows">{ledger.map(item=><article key={item.id}><div><b>{labels[item.entryTypeCode]}</b><strong className={item.amount<0?'out':'in'}>{item.amount>0?'+':''}{money(item.amount)}</strong></div><p>{item.reason}</p><span>{date(item.occurredAt)} · 처리 후 {money(item.balanceAfter)}</span><small>{taxLabels[item.taxTreatmentCode]}{item.vatAmount>0?` · 공급가액 ${money(item.supplyAmount)} + 부가세 ${money(item.vatAmount)}`:''}</small>{item.transactionId&&<button onClick={()=>navigate(`/provider/work/${item.transactionId}`)}>관련 거래</button>}</article>)}{!ledger.length&&<p className="emptyState">해당 원장 내역이 없습니다.</p>}</div></section>
 <section className="providerPanel"><h2>거래별 수수료</h2><div className="providerWalletRows">{data.feeCharges.map(item=><article key={item.id}><div><b>{item.serviceName}</b><strong>{money(item.feeAmount)}</strong></div><span>{date(item.chargedAt)} · {labels[item.restoreStatusCode]}</span><small>{item.isVatIncluded?`부가세 포함 · 공급가액 ${money(item.supplyAmount)} + 부가세 ${money(item.vatAmount)}`:'부가세 별도 또는 비과세'}</small><button onClick={()=>navigate(`/provider/work/${item.transactionId}`)}>거래 상세</button></article>)}{!data.feeCharges.length&&<p className="emptyState">차감된 거래 수수료가 없습니다.</p>}</div></section></main>
 <aside><section className="providerPanel"><h2>이용료 결제내역</h2>{data.charges.map(item=><article className="providerWalletCompact" key={item.id}><b>{money(item.requestedAmount)}</b><span>{labels[item.statusCode]} · {date(item.requestedAt)}</span><small>{paymentMethod(item.paymentMethodCode)}</small></article>)}{!data.charges.length&&<p className="emptyState">이용료 결제내역이 없습니다.</p>}</section><section className="providerPanel"><h2>환불·탈퇴 잔액</h2><p>{data.refundGuidance}</p>{data.withdrawalRefundRequired&&<WithdrawalReadiness data={data}/>} {data.refunds.map(item=><article className="providerWalletCompact" key={item.id}><b>{money(item.requestedAmount)}</b><span>{labels[item.statusCode]} · {date(item.requestedAt)}</span><small>{item.requestReason}</small></article>)}</section></aside></div></>}</ProviderAppLayout>
}

function WithdrawalReadiness({data}:{data:ProviderWalletDashboard}){
 const reasons:string[]=[]
 if(data.availableBalance>0)reasons.push(`남은 이용료 ${money(data.availableBalance)} 환불 필요`)
 if(data.reservedBalance>0)reasons.push(`예약 금액 ${money(data.reservedBalance)} 정리 필요`)
 if(data.refunds.some(item=>['REQUESTED','APPROVED','PROCESSING'].includes(item.statusCode)))reasons.push('환불 요청 처리 중')
 return <div className="providerWalletWarning"><b>탈퇴 전 확인이 필요합니다</b><span>{reasons.join(' · ')}</span><button type="button" onClick={()=>navigate('/provider/exit')}>탈퇴 준비상태 확인</button></div>
}

type WalletTossFactory=(clientKey:string)=>{payment:(options:{customerKey:string})=>{requestPayment:(options:unknown)=>Promise<void>}}
let tossScript:Promise<void>|null=null
async function loadWalletTossPayments(){const read=()=>((window as unknown as {TossPayments?:WalletTossFactory}).TossPayments);if(read())return read()!;if(!tossScript)tossScript=new Promise((resolve,reject)=>{const script=document.createElement('script');script.src='https://js.tosspayments.com/v2/standard';script.onload=()=>resolve();script.onerror=()=>reject(new Error('토스 결제 모듈을 불러오지 못했습니다.'));document.head.appendChild(script)});await tossScript;const factory=read();if(!factory)throw new Error('토스 결제창을 초기화하지 못했습니다.');return factory}
