import { useEffect, useState, type FormEvent, type PropsWithChildren } from 'react'
import { navigate } from '../auth/routing'
import { ProviderAppLayout } from './ProviderAppLayout'
import { providerInteriorApi as api } from './interiorApi'
import type { InteriorDashboard, InteriorDetail, InteriorProject, InteriorStage } from './interiorTypes'
import './providerInterior.css'
import { userRole, userStatus } from '../shared/userDisplay'

const date = (value?: string | null) => value ? new Date(value).toLocaleString('ko-KR') : '미정'
const money = (value: number) => `${new Intl.NumberFormat('ko-KR').format(value)}원`

function Layout({ children }: PropsWithChildren) {
  const path = window.location.pathname
  const links = [['/provider/interior', '대시보드'], ['/provider/interior/projects', '내 프로젝트'], ['/provider/after-services', '하자·사후관리'], ['/provider/disputes', '분쟁']]
  return <ProviderAppLayout><section className="interiorHero"><p>수달 인테리어</p><h1>수달 인테리어</h1><span>배정된 역할 범위에서 실측·설계·시공·검사 업무를 처리합니다.</span></section><nav className="interiorTabs">{links.map(([to, label]) => <button className={path === to ? 'active' : ''} key={to} onClick={() => navigate(to)}>{label}</button>)}</nav>{children}</ProviderAppLayout>
}
function Empty({ children }: PropsWithChildren) { return <p className="interiorEmpty">{children}</p> }

export function ProviderInteriorHomePage() {
  const [value, setValue] = useState<InteriorDashboard | null>(null)
  useEffect(() => { api.home().then(setValue).catch(() => setValue(null)) }, [])
  const cards: Array<[keyof InteriorDashboard, string, string]> = [['siteVisitCount', '실측 일정', 'SITE_SURVEY'], ['siteVisitResultPendingCount', '실측 결과 대기', 'SITE_SURVEY'], ['designCount', '설계 업무', 'DESIGN'], ['contractCount', '계약 진행', 'PRIMARY_CONTRACTOR'], ['activeProjectCount', '진행 프로젝트', ''], ['todayStageCount', '오늘 공정', 'TRADE_CONTRACTOR'], ['inspectionCount', '검사 업무', 'INSPECTION'], ['completionPendingCount', '완료보고 대기', 'PRIMARY_CONTRACTOR'], ['afterServiceCount', '하자·사후관리', 'AFTER_SERVICE'], ['disputeCount', '분쟁', '']]
  return <Layout><section className="interiorGrid">{cards.map(([key, label, role]) => <button key={key} onClick={() => navigate(`/provider/interior/projects${role ? `?role=${role}` : ''}`)}><span>{label}</span><strong>{value?.[key] ?? 0}건</strong></button>)}</section><section className="interiorPanel"><h2>권한 안내</h2><p>프로젝트 참여만으로 전체 정보가 열리지 않습니다. 현재 역할, 배정 공정, 유효기간과 프로젝트 상태를 함께 확인합니다.</p></section></Layout>
}

export function ProviderInteriorProjectsPage({ id }: { id?: string }) {
  const role = new URLSearchParams(location.search).get('role') ?? ''
  const [items, setItems] = useState<InteriorProject[]>([]), [detail, setDetail] = useState<InteriorDetail | null>(null), [error, setError] = useState('')
  useEffect(() => { if (id) api.detail(id).then(setDetail).catch((e: Error) => setError(e.message)); else api.projects(role).then(setItems).catch((e: Error) => setError(e.message)) }, [id, role])
  if (id) return <Layout>{error && <p className="interiorError">{error}</p>}{detail ? <ProjectDetail value={detail} reload={() => api.detail(id).then(setDetail)} /> : !error && <Empty>프로젝트를 불러오는 중입니다.</Empty>}</Layout>
  return <Layout><section className="interiorPanel"><h2>내 인테리어 프로젝트</h2>{items.map(item => <button className="interiorProjectCard" key={item.id} onClick={() => navigate(`/provider/interior/projects/${item.id}`)}><span><small>{item.roles.map(userRole).join(' · ')||'담당 역할 확인 중'}</small><b>{item.serviceName}</b><em>{item.areaName} · {userStatus(item.statusCode)}</em>{item.isFinalProvider&&<mark>고객 최종 선택</mark>}</span><span><strong>{item.nextAction}</strong><small>미처리 {item.pendingActionCount}건</small></span></button>)}{!items.length && <Empty>배정된 프로젝트가 없습니다.</Empty>}</section></Layout>
}

function ProjectDetail({ value, reload }: { value: InteriorDetail; reload: () => Promise<void> }) {
  const [error, setError] = useState('')
  const run = async (action: () => Promise<unknown>) => { try { setError(''); await action(); await reload() } catch (reason) { setError((reason as Error).message) } }
  const upload = async (file: File) => (await api.upload(value.project.id, file)).fileId
  return <>{error && <p className="interiorError">{error}</p>}<section className="interiorSummary"><div><small>{value.project.roles.map(userRole).join(' · ')||'담당 역할 확인 중'}</small><h2>{value.project.serviceName}</h2><p>{value.project.projectNumber} · {value.project.areaName}</p>{value.project.isFinalProvider&&<mark>고객이 최종 시공 전문가로 선택했습니다.</mark>}</div><strong>{userStatus(value.project.statusCode)}</strong></section><div className="interiorColumns">
    <div><Contact value={value} />{!value.project.isFinalProvider&&!value.project.roles.length&&<SiteVisitProposal value={value} run={run}/>} {value.siteVisits.map(visit => <section className="interiorPanel" key={visit.id}><h3>실측 · {userStatus(visit.statusCode)}</h3><p>{date(visit.scheduledStartAt)}</p><p>{visit.measurementSummary ?? '측정 결과 미등록'}</p><Files files={visit.files} /><div className="interiorActions">{!visit.visitedAt && <button onClick={() => void run(() => api.startVisit(visit))}>실측 시작</button>}{!visit.completedAt && <FileAction label="결과·증빙 제출" onSubmit={async file => { const fileIds = file ? [await upload(file)] : []; await run(() => api.completeVisit(visit, { measurementSummary: '현장 실측 결과 등록', constraint: '', riskNote: '', fileIds })) }} />}</div></section>)}
      {value.quotes.map(quote => <section className="interiorPanel" key={quote.id}><h3>내 견적 {quote.revisionNo}차</h3><p>{quote.summary}</p><strong>{money(quote.totalAmount)}</strong>{quote.items.map(item => <small key={item}>{item}</small>)}</section>)}
      {value.designs.map(design => <section className="interiorPanel" key={design.id}><h3>설계 {design.versionNo}차 · {userStatus(design.statusCode)}</h3><p>{design.title}</p><p>{design.description}</p><Files files={design.files} /></section>)}
      {value.project.roles.includes('DESIGN') && <FileAction label="새 설계 버전 제출" onSubmit={async file => { const fileIds = file ? [await upload(file)] : []; await run(() => api.design(value.project.id, { title: `설계 버전 ${value.designs.length + 1}`, description: '전문가 설계 제출', fileIds })) }} />}
    </div>
    <div>{value.project.isFinalProvider && (!value.contract || value.contract.statusCode === 'CORRECTION_REQUIRED') && <ContractRegistration value={value} run={run} upload={upload} />}<Contract value={value} run={run} />{value.project.roles.includes('PRIMARY_CONTRACTOR')&&value.contract?.effectiveAt&&<StageRegistration value={value} run={run}/>} {value.stages.map(stage => <StageCard key={stage.id} stage={stage} run={run} upload={upload} />)}
      {value.inspections.map(item => <section className="interiorPanel" key={item.id}><h3>검사 · {userStatus(item.statusCode)}</h3><p>{item.result}</p><p>{item.correction}</p><span>{item.customerAcknowledged ? '고객 결과 확인 완료' : '고객 결과 확인 대기'}</span><Files files={item.files} /></section>)}
      {(value.project.roles.includes('INSPECTION')||value.project.roles.includes('PRIMARY_CONTRACTOR')) && value.stages[0] && <FileAction label="검사·완료 확인 결과 제출" onSubmit={async file => { const fileIds = file ? [await upload(file)] : []; await run(() => api.inspect(value.stages[0], 'PASSED', '당사자 검사 결과 등록', '', fileIds)) }} />}
      {value.changes.map(change => <section className="interiorPanel" key={change.id}><h3>변경 {change.changeNo}차 · {userStatus(change.statusCode)}</h3><p>{change.reason}</p><p>{change.scopeChange} · {money(change.amountDelta)}</p><Files files={change.files} /></section>)}
      {value.contract && value.project.roles.includes('PRIMARY_CONTRACTOR') && <FileAction label="추가공사·계약변경 요청" onSubmit={async file => { const fileIds = file ? [await upload(file)] : []; await run(() => api.change(value.contract!.id, { reason: '현장 변경 요청', scopeChange: '변경 범위 확인 필요', amountDelta: 0, scheduleImpactDays: null, fileIds })) }} />}
    </div><Side value={value} run={run} /></div></>
}

function Contact({ value }: { value: InteriorDetail }) { return <section className="interiorPanel"><h3>고객 업무정보</h3>{value.contactAvailable ? <><p>{value.customerPhone ?? '전화번호 비공개'}</p><p>{value.detailAddress ?? '상세주소 비공개'}</p></> : <p className="interiorPrivacy">{value.contactPolicy}</p>}</section> }
function SiteVisitProposal({value,run}:{value:InteriorDetail;run:(a:()=>Promise<unknown>)=>Promise<void>}) { const [start,setStart]=useState(''),[end,setEnd]=useState(''),[fee,setFee]=useState(0),[terms,setTerms]=useState(''); return <section className="interiorPanel"><h3>실측 일정·비용 제안</h3><p>견적을 제출한 전문가가 고객에게 직접 제안합니다. 고객이 선택하기 전에는 연락처와 상세주소가 공개되지 않습니다.</p><form className="interiorForm" onSubmit={e=>{e.preventDefault();void run(()=>api.proposeVisit(value.project.id,{scheduledStartAt:new Date(start).toISOString(),scheduledEndAt:end?new Date(end).toISOString():null,proposedVisitFee:fee,proposalTerms:terms}))}}><label>시작일시<input type="datetime-local" required value={start} onChange={e=>setStart(e.target.value)}/></label><label>종료일시<input type="datetime-local" value={end} onChange={e=>setEnd(e.target.value)}/></label><label>실측비(무료는 0원)<input type="number" min="0" value={fee} onChange={e=>setFee(Number(e.target.value))}/></label><label>제안 조건<textarea value={terms} onChange={e=>setTerms(e.target.value)} placeholder="방문 범위와 비용 조건을 적어 주세요."/></label><button>고객에게 실측 제안</button></form></section> }
function StageRegistration({value,run}:{value:InteriorDetail;run:(a:()=>Promise<unknown>)=>Promise<void>}) { const today=new Date().toISOString().slice(0,10);const [name,setName]=useState(''),[start,setStart]=useState(today),[end,setEnd]=useState(today);return <section className="interiorPanel"><h3>공정 직접 등록</h3><p>복잡한 공사만 공정을 나누어 관리하세요. 간단한 공사는 공정 등록 없이 완료보고할 수 있습니다.</p><form className="interiorForm" onSubmit={e=>{e.preventDefault();void run(()=>api.createStage(value.project.id,{sequenceNo:value.stages.length+1,name,plannedStartDate:start,plannedEndDate:end}))}}><label>공정명<input required value={name} onChange={e=>setName(e.target.value)}/></label><label>시작일<input type="date" required value={start} onChange={e=>setStart(e.target.value)}/></label><label>종료일<input type="date" required value={end} onChange={e=>setEnd(e.target.value)}/></label><button>공정 저장</button></form></section> }
function ContractRegistration({ value, run, upload }: { value: InteriorDetail; run: (a: () => Promise<unknown>) => Promise<void>; upload: (f: File) => Promise<string> }) {
  const quote=value.quotes[0], today=new Date().toISOString().slice(0,10)
  const amount=quote?.totalAmount??0
  const [start,setStart]=useState(today),[end,setEnd]=useState(today),[signed,setSigned]=useState(today),[scope,setScope]=useState(''),[warranty,setWarranty]=useState(''),[file,setFile]=useState<File>(),[busy,setBusy]=useState(false)
  const [deposit,setDeposit]=useState(Math.floor(amount*.1)),[interim,setInterim]=useState(Math.floor(amount*.4)),[balance,setBalance]=useState(amount-Math.floor(amount*.1)-Math.floor(amount*.4))
  if(!quote)return <section className="interiorPanel"><h3>계약자료 등록</h3><p>고객이 채택한 최신 견적을 확인할 수 없습니다.</p></section>
  const submit=async(e:FormEvent)=>{e.preventDefault();if(!file)return;if(deposit+interim+balance!==amount)throw new Error('지급계획 합계를 채택 견적금액과 일치시켜 주세요.');setBusy(true);try{const fileId=await upload(file);await run(()=>api.registerContract(value.project.id,{contractAmount:amount,currencyCode:quote.currencyCode,scopeSnapshotJson:JSON.stringify({scope}),scheduleSnapshotJson:JSON.stringify({plannedStartDate:start,plannedCompletionDate:end}),warrantySnapshotJson:JSON.stringify({warranty}),contractSignedDate:signed,plannedStartDate:start,plannedCompletionDate:end,paymentPlans:[{sequenceNo:1,name:'계약금',amount:deposit,dueDate:signed,condition:'계약 체결 시 직접 지급'},{sequenceNo:2,name:'중도금',amount:interim,dueDate:start,condition:'공사 진행 조건에 따라 직접 지급'},{sequenceNo:3,name:'잔금',amount:balance,dueDate:end,condition:'완료 확인 후 직접 지급'}],contractFileIds:[fileId]}))}finally{setBusy(false)}}
  const correction=value.contract?.statusCode==='CORRECTION_REQUIRED'
  return <section className="interiorPanel"><h3>{correction?'계약자료 보완 재등록':'고객과 체결한 계약자료 등록'}</h3>{correction&&<p className="interiorError">고객 요청: {value.contract?.customerMismatchReason}</p>}<p>수달 라이프는 계약 당사자가 아닙니다. 고객과 직접 체결한 최종 서명본과 일치하는 관리정보를 등록해 주세요.</p><form className="interiorForm" onSubmit={e=>void submit(e)}><label>채택 견적금액<input type="number" readOnly value={amount}/></label><label>계약 체결일<input type="date" required value={signed} onChange={e=>setSigned(e.target.value)}/></label><label>공사 시작일<input type="date" required value={start} onChange={e=>setStart(e.target.value)}/></label><label>완료 예정일<input type="date" required value={end} onChange={e=>setEnd(e.target.value)}/></label><label>계약 공사범위<textarea required value={scope} onChange={e=>setScope(e.target.value)}/></label><label>보증·A/S 조건<textarea required value={warranty} onChange={e=>setWarranty(e.target.value)}/></label><fieldset><legend>계약서 지급계획</legend><label>계약금<input type="number" min="0" value={deposit} onChange={e=>setDeposit(Number(e.target.value))}/></label><label>중도금<input type="number" min="0" value={interim} onChange={e=>setInterim(Number(e.target.value))}/></label><label>잔금<input type="number" min="0" value={balance} onChange={e=>setBalance(Number(e.target.value))}/></label><small>합계 {money(deposit+interim+balance)} / 계약금액 {money(amount)}</small></fieldset><label>고객·전문가 서명 계약서<input type="file" accept=".pdf,.jpg,.jpeg,.png" required onChange={e=>setFile(e.target.files?.[0])}/></label><button disabled={busy}>{busy?'등록 중…':correction?'보완 계약자료 재등록':'계약자료 등록·전문가 확인'}</button></form></section>
}
function Contract({ value, run }: { value: InteriorDetail; run: (a: () => Promise<unknown>) => Promise<void> }) {
  if (!value.contract) return null
  const contract = value.contract
  return <section className="interiorPanel"><h3>당사자 계약자료 {contract.version}차</h3><p>{money(contract.amount)} · {userStatus(contract.statusCode)}</p><p>체결일 {contract.contractSignedDate} · 공사 {contract.plannedStartDate} ~ {contract.plannedCompletionDate}</p>{contract.customerMismatchReason&&<p className="interiorError">고객 재등록 요청: {contract.customerMismatchReason}</p>}<Files files={contract.documents}/><p>전문가 확인 {date(contract.providerAgreedAt)} · 고객 일치 확인 {date(contract.customerAgreedAt)}</p><h4>직접 지급 계획</h4>{contract.paymentPlans.map(plan => <div key={plan.id}><p>{plan.sequenceNo}. {plan.name} · {money(plan.amount)} · 확인 {plan.confirmationCount}건</p><button onClick={() => void run(() => api.payment(plan))}>직접 지급 수령 확인</button></div>)}<small>본사는 계약을 생성·승인하지 않습니다. 실제 결제대행·보증결제·송금 기능이 아닙니다.</small></section>
}
function StageCard({ stage, run, upload }: { stage: InteriorStage; run: (a: () => Promise<unknown>) => Promise<void>; upload: (f: File) => Promise<string> }) { return <section className="interiorPanel"><h3>{stage.sequenceNo}. {stage.name}</h3><p>{stage.plannedStartDate} ~ {stage.plannedEndDate}</p><progress value={stage.progressPercent} max="100" /><span>{stage.progressPercent}% · {userStatus(stage.statusCode)}</span><Files files={stage.files} /><FileAction label="공정 업데이트" onSubmit={async file => { const ids = file ? [await upload(file)] : []; await run(() => api.stage(stage, Math.min(100, stage.progressPercent + 10), '현장 공정 업데이트', ids)) }} /></section> }
function Side({ value, run }: { value: InteriorDetail; run: (a: () => Promise<unknown>) => Promise<void> }) { return <aside><section className="interiorPanel"><h3>완료 상태</h3><p>전문가 완료보고: {value.adminCompleted || value.customerCompletionAcknowledged ? '완료' : '대기'}</p><p>고객 최종 확인: {value.customerCompletionAcknowledged ? '완료·프로젝트 종료' : '대기'}</p>{value.project.roles.includes('PRIMARY_CONTRACTOR') && !value.customerCompletionAcknowledged && <button onClick={() => void run(() => api.completion(value.project, '전문가 공사 완료보고'))}>완료보고</button>}</section><section className="interiorPanel"><h3>하자·사후관리·분쟁</h3>{value.afterServiceIds.map(id => <button key={id} onClick={() => navigate(`/provider/after-services/${id}`)}>사후관리 상세</button>)}{value.disputeIds.map(id => <button key={id} onClick={() => navigate(`/provider/disputes/${id}`)}>분쟁 상세</button>)}{!value.afterServiceIds.length && !value.disputeIds.length && <Empty>연결된 업무가 없습니다.</Empty>}</section><section className="interiorPanel interiorTimeline"><h3>진행 이력</h3>{value.timeline.map(item => <p key={item.id}><b>{userStatus(item.eventTypeCode)}</b><small>{date(item.occurredAt)}</small></p>)}</section></aside> }
function Files({ files }: { files: Array<{ id: string; fileName: string; downloadUrl: string|null; publicationMessage:string|null }> }) { return <div>{files.map(file => file.downloadUrl?<a className="interiorFile" key={file.id} href={file.downloadUrl}>{file.fileName}</a>:<span className="interiorFile" key={file.id}>{file.publicationMessage??"안전 확인 전에는 공개되지 않습니다."}</span>)}</div> }
function FileAction({ label, onSubmit }: { label: string; onSubmit: (file?: File) => Promise<void> }) { const [file, setFile] = useState<File>(); return <div className="interiorFileAction"><input aria-label={`${label} 파일`} type="file" accept=".jpg,.jpeg,.png,.pdf" onChange={event => setFile(event.target.files?.[0])} /><button onClick={() => void onSubmit(file)}>{label}</button></div> }
