export interface ProviderWalletLedger { id:string; occurredAt:string; entryTypeCode:string; amount:number; supplyAmount:number; vatAmount:number; taxTreatmentCode:string; balanceAfter:number; reason:string; referenceType:string|null; referenceId:string|null; transactionId:string|null; paymentMethodCode:string|null }
export interface ProviderWalletCharge { id:string; requestedAmount:number; paymentMethodCode:string; statusCode:string; requestedAt:string; completedAt:string|null; failureReason:string|null }
export interface ProviderWalletFee { id:string; transactionId:string; serviceName:string; feeAmount:number; supplyAmount:number; vatAmount:number; isVatIncluded:boolean; chargedAt:string; restoreStatusCode:string }
export interface ProviderWalletRefund { id:string; requestedAmount:number; statusCode:string; requestReason:string; requestedAt:string; reviewedAt:string|null; completedAt:string|null; failureReason:string|null }
export interface ProviderWalletDashboard { walletId:string; providerId:string; currencyCode:string; availableBalance:number; reservedBalance:number; statusCode:string; totalCharged:number; totalUsed:number; totalRestored:number; totalRefunded:number; recentLedger:ProviderWalletLedger[]; charges:ProviderWalletCharge[]; feeCharges:ProviderWalletFee[]; refunds:ProviderWalletRefund[]; actualPaymentIntegrated:boolean; paymentMode:'DISABLED'|'TEST'|'PRODUCTION'; topUpProducts:number[]; monthlyPurchaseLimit:number; monthlyPurchasedAmount:number; providerRefundRequestSupported:boolean; withdrawalRefundRequired:boolean; chargeGuidance:string; refundGuidance:string; rowVersion:string }
export interface WalletTopUpPreparation { orderId:string; amount:number; clientKey:string; customerKey:string; orderName:string; successPath:string; failPath:string; mode:string }
export interface WalletTopUpConfirmation { chargeId:string; statusCode:string; amount:number; availableBalance:number; ledgerEntryId:string|null }

async function read<T>(response:Response):Promise<T>{if(response.ok)return response.json() as Promise<T>;const body=await response.json().catch(()=>null) as {message?:string}|null;throw new Error(body?.message??'이용료 정보를 불러오지 못했습니다.')}
export const getProviderWallet=()=>fetch('/api/v1/providers/me/wallet',{credentials:'include'}).then(read<ProviderWalletDashboard>)
const post=<T,>(path:string,value:unknown)=>fetch(path,{method:'POST',credentials:'include',headers:{'Content-Type':'application/json'},body:JSON.stringify(value)}).then(read<T>)
export const prepareWalletTopUp=(amount:number)=>post<WalletTopUpPreparation>('/api/v1/providers/me/wallet/top-ups/prepare',{amount})
export const confirmWalletTopUp=(paymentKey:string,orderId:string,amount:number)=>post<WalletTopUpConfirmation>('/api/v1/providers/me/wallet/top-ups/confirm',{paymentKey,orderId,amount})
