import { useEffect,useMemo,useState } from 'react'
import { ProviderAppLayout } from './ProviderAppLayout'
import { getProviderProfile,getProviderServices } from './api'
import { serviceDomains } from '../config/serviceCompany'
import { applyProviderAdvertising,cancelProviderAdvertising,consentProviderAdvertisingRenewal,getProviderAdvertisingApplications,getProviderAdvertisingAreas,getProviderAdvertisingGuide,getProviderAdvertisingRates,getProviderAdvertisingRenewals,resubmitProviderAdvertising,setProviderAdvertisingAutoRenew,type AdvertisingApplication,type AdvertisingApplicationPayload,type AdvertisingAreaGroup,type AdvertisingPolicyGuide,type AdvertisingRate,type AdvertisingRenewalHistory } from '../advertising/providerAdvertisingApi'
import './providerAdvertising.css'
import { soodalConfirm } from '../components/soodalDialog'

const labels=new Proxy<Record<string,string>>({SUBMITTED:'검토 대기',RESUBMITTED:'보완 제출',REJECTED:'반려',APPROVED:'승인·게시 대기',PUBLISHED:'게시 중',CANCELLED:'취소',RESERVED:'광고비 예약',RELEASED:'예약 해제',CAPTURED:'광고비 차감 완료'},{get:(target,key:string)=>target[key]??'상태 확인 중'})
const providerProfileDestination='/provider-profile'
const advertisingTemplates=[['general-service','홈 서비스'],['cleaning-care','청소·케어'],['plumbing-repair','배관·수리'],['electrical-lighting','전기·조명'],['interior-remodeling','인테리어'],['moving-assembly','이사·조립'],['aircon-care','에어컨 관리'],['lesson-education','교육·레슨'],['pet-care','반려동물 케어'],['emergency-night','긴급출동'],['bathroom-renovation','욕실 리모델링'],['kitchen-renovation','주방 리모델링'],['appliance-repair','가전제품 수리'],['boiler-heating','보일러·난방'],['window-screen','창호·방충망'],['pest-control','방역·해충 관리'],['moving-cleaning','입주·이사 청소'],['office-cleaning','사무실 청소'],['car-detailing','자동차 세차·관리'],['locksmith-security','열쇠·보안'],['furniture-repair','가구 수리'],['garden-landscaping','정원·조경'],['childcare-sitter','아이 돌봄'],['senior-care','어르신 돌봄'],['beauty-wellness','뷰티·웰니스'],['photography-event','사진·행사'],['tax-accounting','세무·회계'],['computer-repair','컴퓨터 수리'],['delivery-logistics','배송·운송'],['furniture-assembly','가구 조립']] as const
const templatePath=(code:string)=>`/advertising/templates/${code}.webp`
const initial=():AdvertisingApplicationPayload=>({ratePolicyId:'',campaignName:'',startAt:local(new Date(Date.now()+86400000)),title:'',subtitle:null,bodyText:null,templateCode:'general-service',buttonText:'자세히 보기',destinationTypeCode:'INTERNAL_PATH',destinationValue:providerProfileDestination,categoryIds:[],areaIds:[],autoRenewEnabled:false,supplementNote:null})

export function ProviderAdvertisingPage(){
 const[rates,setRates]=useState<AdvertisingRate[]>([]),[apps,setApps]=useState<AdvertisingApplication[]>([]),[guide,setGuide]=useState<AdvertisingPolicyGuide|null>(null),[services,setServices]=useState<{id:string;name:string}[]>([]),[areas,setAreas]=useState<AdvertisingAreaGroup[]>([]),[providerId,setProviderId]=useState(''),[form,setForm]=useState(initial),[editing,setEditing]=useState<AdvertisingApplication|null>(null),[renewals,setRenewals]=useState<Record<string,AdvertisingRenewalHistory[]>>({}),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[error,setError]=useState(''),[previewConfirmed,setPreviewConfirmed]=useState(false)
 const load=()=>Promise.all([getProviderAdvertisingRates(),getProviderAdvertisingApplications(),getProviderAdvertisingGuide(),getProviderServices(),getProviderAdvertisingAreas(),getProviderProfile()]).then(([r,a,g,s,areaGroups,profile])=>{setRates(r);setApps(a.items);setGuide(g);setServices(s.filter(x=>x.status==='ACTIVE').map(x=>({id:x.categoryId,name:x.categoryPath})));setAreas(areaGroups);setProviderId(profile.id);setForm(v=>({...v,ratePolicyId:v.ratePolicyId||r[0]?.id||''}))}).catch(e=>setError(e.message))
 useEffect(()=>{void load()},[])
 const selected=useMemo(()=>rates.find(x=>x.id===form.ratePolicyId),[rates,form.ratePolicyId]),region=useMemo(()=>regionPrice(areas,form.areaIds,selected),[areas,form.areaIds,selected]),endAt=useMemo(()=>selected&&form.startAt?new Date(new Date(form.startAt).getTime()+selected.durationDays*86400000):null,[selected,form.startAt]),destinationValid=useMemo(()=>validDestination(form.destinationTypeCode,form.destinationValue)&& (form.destinationTypeCode==='NONE'||Boolean(form.buttonText?.trim())),[form.destinationTypeCode,form.destinationValue,form.buttonText])
 useEffect(()=>setPreviewConfirmed(false),[form])
 const submit=async()=>{if(!previewConfirmed){setError('광고 미리보기와 연결 화면을 확인한 뒤 확인 항목에 체크해 주세요.');return}setBusy(true);setError('');setMessage('');try{if(editing)await resubmitProviderAdvertising(editing.id,form);else await applyProviderAdvertising(form);setMessage(editing?'보완 내용을 제출했습니다. 관리자가 다시 검토합니다.':'광고 캠페인을 신청했습니다. 지역 요금을 포함한 광고비는 게시 전까지 예약 상태입니다.');setEditing(null);setForm({...initial(),ratePolicyId:rates[0]?.id||''});await load()}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 const edit=(x:AdvertisingApplication)=>{setEditing(x);setForm({ratePolicyId:rates.find(r=>r.placementCode===x.placementCode&&r.durationDays===x.durationDays)?.id||'',campaignName:x.campaignName,startAt:local(new Date(Math.max(Date.parse(x.startAt),Date.now()+3600000))),title:x.title,subtitle:x.subtitle,bodyText:x.bodyText,templateCode:x.templateCode||'general-service',buttonText:x.buttonText,destinationTypeCode:x.destinationTypeCode,destinationValue:x.destinationTypeCode==='INTERNAL_PATH'?providerProfileDestination:x.destinationValue,categoryIds:x.categories.map(v=>v.id),areaIds:x.areas.map(v=>v.id),autoRenewEnabled:x.autoRenewEnabled,supplementNote:''});window.scrollTo({top:0,behavior:'smooth'})}
 const renewalAction=async(action:()=>Promise<unknown>,success:string)=>{setBusy(true);setError('');try{await action();setMessage(success);await load()}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 return <ProviderAppLayout><div className="providerAdPage"><header className="providerAdHero"><span>전문가 광고</span><h1>광고 캠페인 신청</h1><p>노출 위치·기간과 시·도/시·군·구를 고르면 지역 수에 따른 정액요금을 미리 확인할 수 있습니다.</p></header>{error&&<div className="providerAdError">{error}</div>}{message&&<div className="providerAdSuccess">{message}</div>}
 <Policy guide={guide}/>
<section className="providerAdPanel"><div className="providerAdHeading"><div><small>1단계</small><h2>노출 위치·기간 선택</h2></div><strong>{selected?money(region.total,selected.currencyCode):'요금을 선택해 주세요'}</strong></div><div className="providerAdRates">{rates.map(x=><button type="button" className={form.ratePolicyId===x.id?'selected':''} key={x.id} onClick={()=>setForm(v=>({...v,ratePolicyId:x.id,autoRenewEnabled:x.durationDays===30?v.autoRenewEnabled:false}))}><b>{x.placementName}</b><span>{x.durationDays}일</span><strong>{money(x.fixedAmount,x.currencyCode)}</strong><small>지역요금 별도 · 부가세 포함</small></button>)}</div></section>
 <section className="providerAdPanel"><div className="providerAdHeading"><div><small>2단계</small><h2>{editing?'반려 캠페인 보완':'캠페인·소재 작성'}</h2></div>{editing&&<button type="button" onClick={()=>{setEditing(null);setForm({...initial(),ratePolicyId:rates[0]?.id||''})}}>새 신청으로 전환</button>}</div><div className="providerAdForm"><label>캠페인명 *<input value={form.campaignName} onChange={e=>setForm(v=>({...v,campaignName:e.target.value}))}/></label><label>게시 시작일시 *<input type="datetime-local" value={form.startAt} onChange={e=>setForm(v=>({...v,startAt:e.target.value}))}/></label><label>게시 종료일시<output className="providerAdReadonly" aria-describedby="ad-end-help">{endAt?displayDateTime(endAt):'기간을 선택해 주세요.'}</output><small id="ad-end-help">선택한 {selected?.durationDays??'-'}일 요금제에 따라 자동 계산됩니다.</small></label><label className="wide">광고 제목 *<input value={form.title} onChange={e=>setForm(v=>({...v,title:e.target.value}))}/></label><label className="wide">보조 문구<input value={form.subtitle??''} onChange={e=>setForm(v=>({...v,subtitle:e.target.value||null}))}/></label><label className="wide">상세 설명<textarea value={form.bodyText??''} onChange={e=>setForm(v=>({...v,bodyText:e.target.value||null}))}/></label><DestinationEditor form={form} change={setForm}/>{editing&&<label className="wide">보완 내용 *<textarea placeholder="반려 사유를 어떻게 보완했는지 적어 주세요." value={form.supplementNote??''} onChange={e=>setForm(v=>({...v,supplementNote:e.target.value||null}))}/></label>}</div>
 <TemplatePicker selected={form.templateCode} change={templateCode=>setForm(v=>({...v,templateCode}))}/><Choice title="광고할 서비스 분야 *" items={services} selected={form.categoryIds} change={categoryIds=>setForm(v=>({...v,categoryIds}))}/><AreaChoice groups={areas} selected={form.areaIds} change={areaIds=>setForm(v=>({...v,areaIds}))}/>{selected?.durationDays===30&&<label className="providerAdAutoRenew"><input type="checkbox" checked={form.autoRenewEnabled} onChange={e=>setForm(v=>({...v,autoRenewEnabled:e.target.checked}))}/><span><b>매월 자동 갱신</b><small>갱신 7일 전에 다음 달 광고비를 안내하고, 갱신일에 이용료 잔액에서 예약·차감합니다.</small></span></label>}<div className="providerAdFeeSummary"><span>기본 {selected?money(selected.fixedAmount):'-'}</span><span>지역 {selected?money(region.fee):'-'} ({region.provinces}개 시·도 · {region.districts}개 시·군·구)</span><strong>총 {selected?money(region.total):'-'}</strong></div><CreativePreview form={form} providerId={providerId} placement={selected?.placementName} startAt={form.startAt} endAt={endAt}/><label className="providerAdPreviewConfirm"><input type="checkbox" checked={previewConfirmed} onChange={e=>setPreviewConfirmed(e.target.checked)}/><span><b>광고 내용·기간·연결 화면을 확인했습니다.</b><small>신청 후에는 관리자 검토 전까지 소재를 직접 변경할 수 없습니다.</small></span></label><div className="providerAdSubmit"><span>신청 시 총 {selected?money(region.total,selected.currencyCode):'선택 요금'}이 이용료 잔액에서 예약됩니다.</span><button disabled={busy||!selected||!form.campaignName||!form.title||!form.templateCode||!form.categoryIds.length||!form.areaIds.length||!destinationValid||!previewConfirmed} onClick={()=>void submit()}>{busy?'처리 중':editing?'보완 제출':'광고 신청'}</button></div></section>
 <section className="providerAdPanel"><div className="providerAdHeading"><div><small>내 광고 신청</small><h2>신청 현황</h2></div><span>{apps.length}건</span></div><div className="providerAdApplications">{apps.map(x=><article key={x.id}><div className="providerAdCardTop"><div><span className={`providerAdStatus s-${x.statusCode.toLowerCase()}`}>{labels[x.statusCode]}</span><h3>{x.campaignName}</h3></div><strong>{money(x.feeAmount,x.currencyCode)}</strong></div><p>{x.placementName} · {x.durationDays}일 · {date(x.startAt)} ~ {date(x.endAt)}</p><p>노출 지역: {x.areas.map(a=>a.parentName?`${a.parentName} ${a.name}`:`${a.name} 전체`).join(', ')}</p><p>광고비: 기본 {money(x.baseFeeAmount)} + 지역 {money(x.regionalFeeAmount)} · {labels[x.feeStatusCode]}</p><RenewalPanel app={x} busy={busy} rows={renewals[x.id]} run={renewalAction} setRows={rows=>setRenewals(v=>({...v,[x.id]:rows}))}/>{x.rejectionReason&&<div className="providerAdReject"><b>반려 사유</b>{x.rejectionReason}</div>}<div className="providerAdCardActions">{x.statusCode==='REJECTED'&&<button onClick={()=>edit(x)}>보완 작성</button>}{['SUBMITTED','RESUBMITTED','APPROVED'].includes(x.statusCode)&&<button className="danger" onClick={async ()=>{if(await soodalConfirm('게시 전 신청을 취소하고 예약 광고비를 돌려받을까요?'))void cancelProviderAdvertising(x.id).then(load).catch(e=>setError(e.message))}}>신청 취소</button>}</div></article>)}{!apps.length&&<p className="providerAdEmpty">신청한 광고 캠페인이 없습니다.</p>}</div></section></div></ProviderAppLayout>
}

function RenewalPanel({app,busy,rows,run,setRows}:{app:AdvertisingApplication;busy:boolean;rows:AdvertisingRenewalHistory[]|undefined;run:(action:()=>Promise<unknown>,success:string)=>Promise<void>;setRows:(rows:AdvertisingRenewalHistory[])=>void}){if(app.statusCode!=='PUBLISHED'||app.durationDays!==30)return null;const status=new Proxy<Record<string,string>>({OFF:'자동 갱신 안 함',ACTIVE:'자동 갱신 중',CONSENT_REQUIRED:'변경 정책 재동의 필요',PAUSED_INSUFFICIENT:'잔액 부족으로 게시 중지',CANCELLED:'자동 갱신 해지'},{get:(target,key:string)=>target[key]??'상태 확인 중'});return <div className="providerAdRenewal"><div><b>{status[app.autoRenewStatusCode]}</b><span>{app.nextRenewalAt?`다음 갱신 ${date(app.nextRenewalAt)}`:'다음 갱신 없음'}</span></div>{app.renewalConsentRequired&&<button disabled={busy} onClick={()=>void run(()=>consentProviderAdvertisingRenewal(app.id),`변경된 월 광고비 ${money(app.renewalConsentFeeAmount??app.feeAmount)}에 동의했습니다.`)}>변경 요금 재동의</button>}<button disabled={busy} className={app.autoRenewEnabled?'danger':''} onClick={async ()=>{const enabled=!app.autoRenewEnabled;if(!enabled&&!await soodalConfirm('자동 갱신을 해지할까요? 현재 게시 기간은 유지됩니다.'))return;void run(()=>setProviderAdvertisingAutoRenew(app.id,enabled),enabled?'매월 자동 갱신을 신청했습니다.':'자동 갱신을 해지했습니다.')}}>{app.autoRenewEnabled?'자동 갱신 해지':'자동 갱신 신청'}</button><button disabled={busy} onClick={()=>void getProviderAdvertisingRenewals(app.id).then(setRows)}>월별 광고비·갱신 이력</button>{rows&&<div className="providerAdRenewalHistory">{rows.length?rows.map(x=><p key={x.id}><b>{x.cycleNo}회차 · {renewalStatus(x.statusCode)}</b><span>{date(x.dueAt)} · 기본 {money(x.baseFeeAmount)} + 지역 {money(x.regionalFeeAmount)} = {money(x.feeAmount)}</span>{x.failureReason&&<small>{x.failureReason}</small>}</p>):<p>아직 갱신 이력이 없습니다.</p>}</div>}</div>}

function Policy({guide}:{guide:AdvertisingPolicyGuide|null}){if(!guide)return null;return <details className="providerAdPolicy" open><summary>초기 광고비 정책</summary><div><p><b>{guide.billingModel}</b> · {guide.vatTreatment}</p><ol>{guide.workflow.map(x=><li key={x}>{x}</li>)}</ol>{guide.refundRules.map(x=><p key={x}>• {x}</p>)}</div></details>}
function DestinationEditor({form,change}:{form:AdvertisingApplicationPayload;change:(updater:(value:AdvertisingApplicationPayload)=>AdvertisingApplicationPayload)=>void}){const linked=form.destinationTypeCode!=='NONE';const switchType=(type:string)=>change(v=>({...v,destinationTypeCode:type,destinationValue:type==='INTERNAL_PATH'?providerProfileDestination:type==='EXTERNAL_URL'?'https://':null,buttonText:type==='NONE'?null:(v.buttonText||'자세히 보기')}));return <><label>연결 방식<select value={form.destinationTypeCode} onChange={e=>switchType(e.target.value)}><option value="INTERNAL_PATH">전문가 소개 화면</option><option value="EXTERNAL_URL">외부 웹사이트</option><option value="NONE">연결 없음</option></select><small>{form.destinationTypeCode==='INTERNAL_PATH'?'수달 라이프 고객 사이트의 전문가 소개 화면으로 이동합니다. 기본정보·완료 실적·신뢰도·공개 리뷰와 광고 상세 설명을 보여줍니다.':form.destinationTypeCode==='EXTERNAL_URL'?'전문가 홈페이지·예약 페이지 등 https 주소를 새 창으로 엽니다.':'광고는 보이지만 이동 버튼은 표시하지 않습니다.'}</small></label>{linked&&<label>이동 버튼 문구 *<input value={form.buttonText??''} maxLength={50} onChange={e=>change(v=>({...v,buttonText:e.target.value||null}))} placeholder="예: 자세히 보기"/><small>광고에서 전문가 소개 화면이나 외부 사이트로 이동할 때 고객이 누르는 버튼입니다.</small></label>}{form.destinationTypeCode==='INTERNAL_PATH'&&<label className="wide">연결 화면<output className="providerAdReadonly">전문가 소개 화면 · 자동 연결</output><small>신청한 전문가의 공개 프로필로 자동 연결되므로 별도 주소를 입력하지 않습니다.</small></label>}{form.destinationTypeCode==='EXTERNAL_URL'&&<label className="wide">외부 사이트 주소 *<input type="url" inputMode="url" value={form.destinationValue??''} onChange={e=>change(v=>({...v,destinationValue:e.target.value||null}))} placeholder="https://www.example.com/service"/><small>http 또는 https 전체 주소를 입력해 주세요. 게시 후 이동 버튼을 누르면 새 창으로 이동합니다.</small></label>}</>}
function TemplatePicker({selected,change}:{selected:string;change:(value:string)=>void}){return <fieldset className="providerAdTemplatePicker"><legend>광고 배너 템플릿 *</legend><p>서비스와 가장 잘 맞는 배너를 선택하세요. 제목과 보조 문구는 이미지 왼쪽 여백에 자동 배치됩니다.</p><div>{advertisingTemplates.map(([code,label])=><label className={selected===code?'selected':''} key={code}><input type="radio" name="advertising-template" value={code} checked={selected===code} onChange={()=>change(code)}/><img src={templatePath(code)} alt=""/><span>{label}</span></label>)}</div></fieldset>}
function CreativePreview({form,providerId,placement,startAt,endAt}:{form:AdvertisingApplicationPayload;providerId:string;placement?:string;startAt:string;endAt:Date|null}){const linked=form.destinationTypeCode!=='NONE'&&validDestination(form.destinationTypeCode,form.destinationValue);const profileUrl=providerId?`${serviceDomains.customer}/providers/${providerId}`:'전문가 소개 주소 확인 중',destination=form.destinationTypeCode==='INTERNAL_PATH'?'전문가 소개 화면':form.destinationTypeCode==='EXTERNAL_URL'?form.destinationValue:'연결 없음',actualUrl=form.destinationTypeCode==='INTERNAL_PATH'?profileUrl:form.destinationValue,bannerStyle={backgroundImage:`linear-gradient(90deg,rgba(4,72,67,.96),rgba(4,72,67,.78) 48%,rgba(4,72,67,.08) 78%),url('${templatePath(form.templateCode)}')`};return <section className="providerAdApplicantPreview"><header><div><small>3단계 · 신청 전 확인</small><h3>고객에게 보이는 광고 미리보기</h3></div><span>{placement??'노출 위치 미선택'}</span></header><article className="hasTemplate" style={bannerStyle}><small>프로모션</small><strong>{form.title.trim()||'광고 제목을 입력해 주세요.'}</strong><p>{form.subtitle?.trim()||'보조 문구가 여기에 표시됩니다.'}</p>{linked&&<button type="button" onClick={()=>openDestination(form.destinationTypeCode,form.destinationValue,providerId)}>{form.buttonText?.trim()||'자세히 보기'}</button>}</article><div className="providerAdBodyPreview"><b>상세 설명</b><p>{form.bodyText?.trim()||'상세 설명을 입력하면 전문가 소개 화면의 광고 상세 설명 영역에 전체 내용이 표시됩니다.'}</p></div><dl><div><dt>게시 기간</dt><dd>{startAt&&endAt?`${date(new Date(startAt).toISOString())} ~ ${date(endAt.toISOString())}`:'기간을 선택해 주세요.'}</dd></div><div><dt>버튼 연결</dt><dd>{destination||'선택하지 않음'}{linked&&<small>{actualUrl}</small>}</dd></div></dl>{!validDestination(form.destinationTypeCode,form.destinationValue)&&<p className="providerAdPreviewWarning">연결 주소를 확인해 주세요.</p>}</section>}
function Choice({title,items,selected,change}:{title:string;items:{id:string;name:string}[];selected:string[];change:(v:string[])=>void}){return <fieldset className="providerAdChoice"><legend>{title}</legend><p>선택한 분야에 관심 있는 고객에게 광고를 연결하고, 광고 결과를 서비스별로 집계하는 데 사용합니다. 승인된 서비스만 선택할 수 있습니다.</p>{items.map(x=><label key={x.id}><input type="checkbox" checked={selected.includes(x.id)} onChange={e=>change(e.target.checked?[...selected,x.id]:selected.filter(id=>id!==x.id))}/>{x.name}</label>)}{!items.length&&<p>먼저 마이수달에서 해당 정보를 설정해 주세요.</p>}</fieldset>}
function AreaChoice({groups,selected,change}:{groups:AdvertisingAreaGroup[];selected:string[];change:(v:string[])=>void}){const toggleProvince=(g:AdvertisingAreaGroup,on:boolean)=>change(on?[...selected.filter(x=>!g.districts.some(d=>d.id===x)),g.id]:selected.filter(x=>x!==g.id)),toggleDistrict=(g:AdvertisingAreaGroup,id:string,on:boolean)=>change(on?[...selected.filter(x=>x!==g.id),id]:selected.filter(x=>x!==id));return <fieldset className="providerAdAreaChoice"><legend>노출 지역 * <small>시·도 전체 또는 필요한 시·군·구를 선택하세요.</small></legend>{groups.map(g=><details key={g.id} open={selected.includes(g.id)||g.districts.some(d=>selected.includes(d.id))}><summary><label><input type="checkbox" checked={selected.includes(g.id)} onChange={e=>toggleProvince(g,e.target.checked)}/><b>{g.name} 전체</b></label><span>{selected.includes(g.id)?'전체 선택':`${g.districts.filter(d=>selected.includes(d.id)).length}곳 선택`}</span></summary><div>{g.districts.map(d=><label key={d.id}><input type="checkbox" disabled={selected.includes(g.id)} checked={selected.includes(g.id)||selected.includes(d.id)} onChange={e=>toggleDistrict(g,d.id,e.target.checked)}/>{d.name}</label>)}</div></details>)}</fieldset>}
function regionPrice(groups:AdvertisingAreaGroup[],selectedIds:string[],rate:AdvertisingRate|undefined){if(!rate)return{provinces:0,districts:0,fee:0,total:0};const selected=new Set(selectedIds),provinces=groups.filter(g=>selected.has(g.id)).length,districts=groups.reduce((sum,g)=>sum+(selected.has(g.id)?0:g.districts.filter(d=>selected.has(d.id)).length),0),raw=provinces*rate.provinceUnitAmount+districts*rate.districtUnitAmount,fee=rate.regionalFeeCapAmount>0?Math.min(raw,rate.regionalFeeCapAmount):raw;return{provinces,districts,fee,total:rate.fixedAmount+fee}}
const money=(v:number,c='KRW')=>new Intl.NumberFormat('ko-KR',{style:'currency',currency:c,maximumFractionDigits:0}).format(v),date=(v:string)=>new Intl.DateTimeFormat('ko-KR',{dateStyle:'medium',timeStyle:'short'}).format(new Date(v)),local=(d:Date)=>{const x=new Date(d.getTime()-d.getTimezoneOffset()*60000);return x.toISOString().slice(0,16)}
const displayDateTime=(value:Date)=>new Intl.DateTimeFormat('ko-KR',{year:'numeric',month:'long',day:'numeric',weekday:'short',hour:'numeric',minute:'2-digit',hour12:true}).format(value)
const validDestination=(type:string,value:string|null)=>{if(type==='NONE')return true;if(type==='INTERNAL_PATH')return value===providerProfileDestination;if(type==='EXTERNAL_URL'){try{const url=new URL(value??'');return url.protocol==='https:'||url.protocol==='http:'}catch{return false}}return false}
const openDestination=(type:string,value:string|null,providerId:string)=>{if(!validDestination(type,value)||!value)return;if(type==='INTERNAL_PATH'){if(providerId)window.open(`${serviceDomains.customer}/providers/${providerId}`,'_blank','noopener,noreferrer')}else window.open(value,'_blank','noopener,noreferrer')}
const renewalStatus=(v:string)=>({PENDING:'갱신 예정',NOTICE_SENT:'다음 달 광고비 안내',RENEWED:'갱신·차감 완료',PAUSED_INSUFFICIENT:'잔액 부족 게시 중지',CONSENT_REQUIRED:'요금 정책 재동의 필요',CANCELLED:'자동 갱신 해지'}[v]??'상태 확인 중')
