[CmdletBinding(SupportsShouldProcess=$true,ConfirmImpact='High')]
param([switch]$ConfirmProductionDeployment,[string]$ServerInstance='localhost',[string]$DatabaseName='SOODAL_LIFE_DEV',[string]$AppsRoot='D:\SOODALLIFE\apps',[string]$BackupParent='D:\SOODALLIFE\releases',[string]$DatabaseBackupRoot='D:\SOODALLIFE\DB\Backup')
$ErrorActionPreference='Stop'
if(-not $ConfirmProductionDeployment){throw 'Safety stop: add -ConfirmProductionDeployment after checking targets.'}
if(-not $PSCmdlet.ShouldProcess("API, customer, partner and admin apps at $AppsRoot plus database $DatabaseName",'Deploy V180 autonomous service coverage')){return}
$identity=[Security.Principal.WindowsIdentity]::GetCurrent();$principal=[Security.Principal.WindowsPrincipal]::new($identity);if(-not $principal.IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)){throw 'Run PowerShell as Administrator.'}
Import-Module WebAdministration;if(-not(Get-Command sqlcmd.exe -ErrorAction SilentlyContinue)){throw 'sqlcmd.exe is required.'}
$root=$PSScriptRoot;$stamp=Get-Date -Format 'yyyyMMdd-HHmmss';$backupRoot=Join-Path $BackupParent "backup-before-autonomous-service-coverage-v180-$stamp";$iisBackup="Before_AutonomousServiceCoverageV180_$stamp";$dbBackup=Join-Path $DatabaseBackupRoot "${DatabaseName}_PreAutonomousServiceCoverageV180_$stamp.bak"
$apply=Join-Path $root 'Apply-AutonomousServiceCoverageV180.sql';$verify=Join-Path $root 'Verify-AutonomousServiceCoverageV180.sql';$sources=[ordered]@{API=Join-Path $root 'api';Customer=Join-Path $root 'frontend\customer';Partner=Join-Path $root 'frontend\partner';Admin=Join-Path $root 'frontend\admin'};$targets=[ordered]@{API=Join-Path $AppsRoot 'api';Customer=Join-Path $AppsRoot 'customer';Partner=Join-Path $AppsRoot 'partner';Admin=Join-Path $AppsRoot 'admin'}
$required=@((Join-Path $sources.API 'SoodalLife.Api.dll'),(Join-Path $sources.API 'web.config'),(Join-Path $sources.Customer 'index.html'),(Join-Path $sources.Partner 'index.html'),(Join-Path $sources.Admin 'index.html'),$apply,$verify);foreach($file in $required){if(-not(Test-Path -LiteralPath $file -PathType Leaf)){throw "Required V180 file missing: $file"}};if(Test-Path (Join-Path $sources.API 'appsettings.json')){throw 'Package must not contain appsettings.json.'}
function Copy-Checked([string]$Source,[string]$Destination,[switch]$Mirror,[switch]$PreserveApiData){New-Item -ItemType Directory -Force -Path $Destination|Out-Null;$args=@($Source,$Destination,($(if($Mirror){'/MIR'}else{'/E'})),'/R:2','/W:2','/NFL','/NDL','/NJH','/NJS','/NP');if($PreserveApiData){$args+=@('/XD','App_Data','/XF','appsettings.json','appsettings.Production.json','appsettings.Development.json')};& robocopy.exe @args;if($LASTEXITCODE-gt 7){throw "Robocopy failed: $Source"}}
function PoolState($name){try{(Get-WebAppPoolState -Name $name -ErrorAction Stop).Value}catch{$null}};function Stop-PoolSafe($name){if(Test-Path "IIS:\AppPools\$name"){if((PoolState $name)-ne'Stopped'){Stop-WebAppPool $name};for($i=0;$i-lt40;$i++){if((PoolState $name)-eq'Stopped'){return};Start-Sleep -Milliseconds 500};throw "Pool stop timeout: $name"}};function Start-PoolSafe($name){if(Test-Path "IIS:\AppPools\$name"){for($i=0;$i-lt40;$i++){if((PoolState $name)-eq'Started'){return};try{Start-WebAppPool $name}catch{};Start-Sleep -Milliseconds 750};throw "Pool start timeout: $name"}}
New-Item -ItemType Directory -Force -Path $backupRoot,$DatabaseBackupRoot|Out-Null;& "$env:windir\System32\inetsrv\appcmd.exe" add backup $iisBackup;if($LASTEXITCODE-ne0){throw 'IIS backup failed.'};foreach($name in $targets.Keys){if(Test-Path $targets[$name]){Copy-Checked $targets[$name] (Join-Path $backupRoot $name)}};$escaped=$dbBackup.Replace("'","''");& sqlcmd.exe -S $ServerInstance -E -C -b -Q "BACKUP DATABASE [$DatabaseName] TO DISK=N'$escaped' WITH COPY_ONLY,CHECKSUM,COMPRESSION,INIT; RESTORE VERIFYONLY FROM DISK=N'$escaped' WITH CHECKSUM;";if($LASTEXITCODE-ne0){throw 'Database backup failed.'}
$pools=@('SoodalLife.Api','soodallife.kr','SoodalLife.Static');$failure=$null;try{foreach($pool in $pools){Stop-PoolSafe $pool};& sqlcmd.exe -S $ServerInstance -E -C -I -b -f 65001 -d $DatabaseName -i $apply;if($LASTEXITCODE-ne0){throw 'V180 database apply failed.'};foreach($name in $targets.Keys){Copy-Checked $sources[$name] $targets[$name] -Mirror -PreserveApiData:($name-eq'API')};New-Item -ItemType Directory -Force -Path (Join-Path $targets.API 'App_Data')|Out-Null}catch{$failure=$_;Write-Warning "Deployment stopped. Backups: $backupRoot / $dbBackup";foreach($name in $targets.Keys){$saved=Join-Path $backupRoot $name;if(Test-Path $saved){Copy-Checked $saved $targets[$name] -Mirror -PreserveApiData:($name-eq'API')}}}finally{foreach($pool in $pools){try{Start-PoolSafe $pool}catch{Write-Warning $_.Exception.Message}}};if($failure){throw $failure}
& sqlcmd.exe -S $ServerInstance -E -C -I -b -f 65001 -d $DatabaseName -i $verify;if($LASTEXITCODE-ne0){throw 'V180 database verify failed.'};$health=Invoke-RestMethod 'https://api.soodallife.kr/api/v1/system/health' -TimeoutSec 30;$ready=Invoke-RestMethod 'https://api.soodallife.kr/api/v1/system/ready' -TimeoutSec 30;if($health.status-ne'ok'-or$ready.status-ne'ready'){throw 'Health verification failed.'}
[PSCustomObject]@{DeploymentSucceeded=$true;IisBackup=$iisBackup;FileBackup=$backupRoot;DatabaseBackup=$dbBackup;AppDataPreserved=$true;AppSettingsPreserved=$true;DatabaseChanged=$true;ApiChanged=$true;Health=$health.status;Readiness=$ready.status;ProjectServices='enabled';NationwideNetwork='provider-self-managed';CoverageApproval='not-required';CoverageEvidence='not-required';CustomerApp='ok';PartnerApp='ok';AdminApp='ok'}|Format-List
Write-Host 'V180 autonomous service coverage deployment completed.' -ForegroundColor Green
