[CmdletBinding(SupportsShouldProcess=$true,ConfirmImpact='High')]
param([switch]$ConfirmProductionDeployment,[string]$ServerInstance='localhost',[string]$DatabaseName='SOODAL_LIFE_DEV',[string]$AppsRoot='D:\SOODALLIFE\apps',[string]$BackupParent='D:\SOODALLIFE\releases',[string]$DatabaseBackupRoot='D:\SOODALLIFE\DB\Backup')
$ErrorActionPreference='Stop'
if(-not $ConfirmProductionDeployment){throw 'Safety stop: rerun with -ConfirmProductionDeployment after checking the ZIP hash, database and target paths.'}
if(-not $PSCmdlet.ShouldProcess("API, customer, partner and admin apps at $AppsRoot plus database $DatabaseName","Deploy V163 help room and suggestion box")){return}
Import-Module WebAdministration
$releaseRoot=$PSScriptRoot;$stamp=Get-Date -Format 'yyyyMMdd-HHmmss';$backupRoot=Join-Path $BackupParent "backup-before-help-room-suggestion-v163-$stamp";$iisBackupName="Before_HelpRoomSuggestionV163_$stamp";$databaseBackupPath=Join-Path $DatabaseBackupRoot "${DatabaseName}_PreHelpRoomSuggestionV163_$stamp.bak"
$applySql=Join-Path $releaseRoot 'deployment\Apply-HelpRoomSuggestionV163.sql';$verifySql=Join-Path $releaseRoot 'deployment\Verify-HelpRoomSuggestionV163.sql'
$sources=[ordered]@{API=Join-Path $releaseRoot 'api';Customer=Join-Path $releaseRoot 'frontend\customer';Partner=Join-Path $releaseRoot 'frontend\partner';Admin=Join-Path $releaseRoot 'frontend\admin'};$targets=[ordered]@{API=Join-Path $AppsRoot 'api';Customer=Join-Path $AppsRoot 'customer';Partner=Join-Path $AppsRoot 'partner';Admin=Join-Path $AppsRoot 'admin'}
$required=@((Join-Path $sources.API 'SoodalLife.Api.dll'),(Join-Path $sources.API 'web.config'),(Join-Path $sources.Customer 'index.html'),(Join-Path $sources.Partner 'index.html'),(Join-Path $sources.Admin 'index.html'),$applySql,$verifySql);foreach($file in $required){if(-not(Test-Path -LiteralPath $file -PathType Leaf)){throw "Required release file is missing: $file"}}
if(-not(Get-Command sqlcmd.exe -ErrorAction SilentlyContinue)){throw 'sqlcmd.exe is required.'};New-Item -ItemType Directory -Force -Path $backupRoot,$DatabaseBackupRoot|Out-Null
function Copy-Checked([string]$Source,[string]$Destination,[switch]$PreserveApiData){New-Item -ItemType Directory -Force -Path $Destination|Out-Null;$arguments=@($Source,$Destination,'/MIR','/R:2','/W:2','/NFL','/NDL','/NJH','/NJS','/NP');if($PreserveApiData){$arguments+=@('/XD','App_Data','/XF','appsettings.json','appsettings.Production.json','appsettings.Development.json')};& robocopy.exe @arguments;if($LASTEXITCODE -gt 7){throw "Robocopy failed ($LASTEXITCODE): $Source -> $Destination"}}
function Stop-Pool([string]$Name){if(-not(Test-Path "IIS:\AppPools\$Name") -or (Get-WebAppPoolState -Name $Name).Value -eq 'Stopped'){return};Stop-WebAppPool -Name $Name;for($i=0;$i -lt 30;$i++){Start-Sleep -Milliseconds 500;if((Get-WebAppPoolState -Name $Name).Value -eq 'Stopped'){return}};throw "Application pool did not stop: $Name"}
function Start-Pool([string]$Name){if((Test-Path "IIS:\AppPools\$Name") -and (Get-WebAppPoolState -Name $Name).Value -ne 'Started'){Start-WebAppPool -Name $Name}}
& "$env:windir\System32\inetsrv\appcmd.exe" add backup $iisBackupName;if($LASTEXITCODE -ne 0){throw 'IIS configuration backup failed.'};foreach($name in $targets.Keys){if(Test-Path -LiteralPath $targets[$name]){New-Item -ItemType Directory -Force -Path (Join-Path $backupRoot $name)|Out-Null;& robocopy.exe $targets[$name] (Join-Path $backupRoot $name) /E /R:2 /W:2 /NFL /NDL /NJH /NJS /NP;if($LASTEXITCODE -gt 7){throw "Backup failed: $name"}}}
$escaped=$databaseBackupPath.Replace("'","''");& sqlcmd.exe -S $ServerInstance -E -C -b -Q "BACKUP DATABASE [$DatabaseName] TO DISK=N'$escaped' WITH COPY_ONLY, CHECKSUM, COMPRESSION, INIT; RESTORE VERIFYONLY FROM DISK=N'$escaped' WITH CHECKSUM;";if($LASTEXITCODE -ne 0){throw 'Database backup verification failed.'}
$pools=@('SoodalLife.Api','soodallife.kr','SoodalLife.Static');$deploymentError=$null;try{foreach($pool in $pools){Stop-Pool $pool};& sqlcmd.exe -S $ServerInstance -E -C -I -b -f 65001 -d $DatabaseName -i $applySql;if($LASTEXITCODE -ne 0){throw 'V163 database apply failed.'};foreach($name in $sources.Keys){Copy-Checked $sources[$name] $targets[$name] -PreserveApiData:($name -eq 'API')};New-Item -ItemType Directory -Force -Path (Join-Path $targets.API 'App_Data')|Out-Null}catch{$deploymentError=$_;Write-Warning "V163 deployment stopped. Database backup: $databaseBackupPath"}finally{foreach($pool in $pools){try{Start-Pool $pool}catch{Write-Warning $_.Exception.Message}}};if($deploymentError){throw $deploymentError}
& sqlcmd.exe -S $ServerInstance -E -C -I -b -f 65001 -d $DatabaseName -i $verifySql;if($LASTEXITCODE -ne 0){throw 'V163 database verification failed.'};$health=Invoke-RestMethod -Uri 'https://api.soodallife.kr/api/v1/system/health' -TimeoutSec 30;$ready=Invoke-RestMethod -Uri 'https://api.soodallife.kr/api/v1/system/ready' -TimeoutSec 30;if($health.status -ne 'ok' -or $ready.status -ne 'ready'){throw 'Post-deployment health/readiness failed.'};$customer=Invoke-WebRequest -Uri 'https://soodallife.kr/help-room' -UseBasicParsing -TimeoutSec 30;$admin=Invoke-WebRequest -Uri 'https://admin.soodallife.kr/admin/suggestions' -UseBasicParsing -TimeoutSec 30;if($customer.StatusCode-ne 200-or$admin.StatusCode-ne 200){throw 'V163 frontend route verification failed.'}
[PSCustomObject]@{DeploymentSucceeded=$true;IisBackup=$iisBackupName;FileBackup=$backupRoot;DatabaseBackup=$databaseBackupPath;AppDataPreserved=$true;AppSettingsPreserved=$true;DatabaseChanged=$true;Health=$health.status;Readiness=$ready.status;HelpRoom='member-visible';SuggestionBox='private';SuggestionDailyLimit=5;CustomerApp='ok';PartnerApp='ok';AdminApp='ok'}|Format-List
Write-Host 'V163 help room and suggestion box deployment completed.' -ForegroundColor Green
Write-Host 'Help room is member-visible with masked identity and optional district only. Suggestion contents remain private to the author and administrators.' -ForegroundColor Yellow
