using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using SoodalLife.Api.Domain.Entities;

namespace SoodalLife.Api.Infrastructure.Persistence.Configurations;

internal sealed class AdvertisingPlacementConfiguration() : EntityConfiguration<AdvertisingPlacement>("advertising_placements")
{
    protected override void ConfigureEntity(EntityTypeBuilder<AdvertisingPlacement> b)
    {
        Mapping.PublicId(b); Mapping.String(b, nameof(AdvertisingPlacement.Code), "code", 50, unicode: false);
        Mapping.String(b, nameof(AdvertisingPlacement.Name), "name", 100); Mapping.String(b, nameof(AdvertisingPlacement.Description), "description", 500, nullable: true);
        Mapping.String(b, nameof(AdvertisingPlacement.RouteHint), "route_hint", 200, nullable: true, unicode: false); Mapping.Bool(b, nameof(AdvertisingPlacement.IsActive), "is_active", true); Mapping.FullAudit(b);
        b.HasIndex(x => x.Code).IsUnique(); b.HasIndex(x => new { x.IsActive, x.Name });
        var seededAt = new DateTime(2026, 8, 10, 0, 0, 0, DateTimeKind.Utc);
        b.HasData(
            new AdvertisingPlacement { Id = 1, PublicId = Guid.Parse("11a10000-0000-0000-0000-000000000001"), Code = "CUSTOMER_HOME", Name = "고객 홈", Description = "고객 역할 홈 화면", RouteHint = "/customer", IsActive = true, CreatedAt = seededAt, UpdatedAt = seededAt },
            new AdvertisingPlacement { Id = 2, PublicId = Guid.Parse("11a10000-0000-0000-0000-000000000002"), Code = "PROVIDER_HOME", Name = "전문가 홈", Description = "전문가 역할 홈 화면", RouteHint = "/provider", IsActive = true, CreatedAt = seededAt, UpdatedAt = seededAt },
            new AdvertisingPlacement { Id = 3, PublicId = Guid.Parse("11a10000-0000-0000-0000-000000000003"), Code = "CUSTOMER_LIVE_ACTIVITY_FEED", Name = "고객 실시간 서비스 목록", Description = "전국에서 지금 진행 중인 서비스 목록 사이에 광고임을 명확히 표시하여 노출", RouteHint = "/customer#live-activity", IsActive = true, CreatedAt = seededAt, UpdatedAt = seededAt });
    }
}

internal sealed class AdvertisingCampaignConfiguration() : EntityConfiguration<AdvertisingCampaign>("advertising_campaigns")
{
    protected override void ConfigureEntity(EntityTypeBuilder<AdvertisingCampaign> b)
    {
        Mapping.PublicId(b); Mapping.String(b, nameof(AdvertisingCampaign.CampaignName), "campaign_name", 200); Mapping.String(b, nameof(AdvertisingCampaign.CampaignTypeCode), "campaign_type_code", 30, unicode: false);
        Mapping.String(b, nameof(AdvertisingCampaign.AudienceTypeCode), "audience_type_code", 20, unicode: false); Mapping.String(b, nameof(AdvertisingCampaign.OwnerTypeCode), "owner_type_code", 30, unicode: false);
        Mapping.String(b, nameof(AdvertisingCampaign.OwnerDisplayName), "owner_display_name", 200, nullable: true); Mapping.DateTime(b, nameof(AdvertisingCampaign.StartAt), "start_at"); Mapping.DateTime(b, nameof(AdvertisingCampaign.EndAt), "end_at", nullable: true);
        Mapping.String(b, nameof(AdvertisingCampaign.StatusCode), "status_code", 20, unicode: false); Mapping.Int(b, nameof(AdvertisingCampaign.Priority), "priority", 0);
        Mapping.String(b, nameof(AdvertisingCampaign.DestinationTypeCode), "destination_type_code", 30, unicode: false); Mapping.String(b, nameof(AdvertisingCampaign.DestinationValue), "destination_value", 2000, nullable: true, unicode: false);
        Mapping.String(b, nameof(AdvertisingCampaign.ReviewStatusCode), "review_status_code", 20, unicode: false); Mapping.NullableLong(b, nameof(AdvertisingCampaign.ApprovedByUserId), "approved_by_user_id");
        Mapping.DateTime(b, nameof(AdvertisingCampaign.ApprovedAt), "approved_at", nullable: true); Mapping.String(b, nameof(AdvertisingCampaign.RejectionReason), "rejection_reason", 1000, nullable: true); Mapping.FullAudit(b);
        Mapping.Fk<AdvertisingCampaign, User>(b, nameof(AdvertisingCampaign.ApprovedByUserId));
        b.HasIndex(x => new { x.StatusCode, x.ReviewStatusCode, x.StartAt, x.EndAt }); b.HasIndex(x => new { x.AudienceTypeCode, x.StartAt }); b.HasIndex(x => x.CampaignName);
        b.ToTable("advertising_campaigns", t => { t.HasCheckConstraint("CK_advertising_campaigns_type", "[campaign_type_code] IN ('ADVERTISEMENT','PROMOTION','BANNER','POPUP')"); t.HasCheckConstraint("CK_advertising_campaigns_audience", "[audience_type_code] IN ('ALL','CUSTOMER','PROVIDER')"); t.HasCheckConstraint("CK_advertising_campaigns_owner", "[owner_type_code] IN ('HEAD_OFFICE','PLATFORM','EXTERNAL','PROVIDER')"); t.HasCheckConstraint("CK_advertising_campaigns_status", "[status_code] IN ('DRAFT','ACTIVE','PAUSED','ARCHIVED')"); t.HasCheckConstraint("CK_advertising_campaigns_review", "[review_status_code] IN ('DRAFT','PENDING','APPROVED','REJECTED')"); t.HasCheckConstraint("CK_advertising_campaigns_destination", "[destination_type_code] IN ('NONE','INTERNAL_PATH','EXTERNAL_URL')"); t.HasCheckConstraint("CK_advertising_campaigns_period", "[end_at] IS NULL OR [end_at] > [start_at]"); t.HasCheckConstraint("CK_advertising_campaigns_priority", "[priority] >= 0"); });
    }
}

internal sealed class AdvertisingCampaignPlacementConfiguration() : EntityConfiguration<AdvertisingCampaignPlacement>("advertising_campaign_placements")
{ protected override void ConfigureEntity(EntityTypeBuilder<AdvertisingCampaignPlacement> b) { Mapping.Long(b, nameof(AdvertisingCampaignPlacement.CampaignId), "campaign_id"); Mapping.Long(b, nameof(AdvertisingCampaignPlacement.PlacementId), "placement_id"); Mapping.CreatedAudit(b); Mapping.Fk<AdvertisingCampaignPlacement, AdvertisingCampaign>(b, nameof(AdvertisingCampaignPlacement.CampaignId)); Mapping.Fk<AdvertisingCampaignPlacement, AdvertisingPlacement>(b, nameof(AdvertisingCampaignPlacement.PlacementId)); b.HasIndex(x => new { x.CampaignId, x.PlacementId }).IsUnique(); } }
internal sealed class AdvertisingCampaignCategoryConfiguration() : EntityConfiguration<AdvertisingCampaignCategory>("advertising_campaign_categories")
{ protected override void ConfigureEntity(EntityTypeBuilder<AdvertisingCampaignCategory> b) { Mapping.Long(b, nameof(AdvertisingCampaignCategory.CampaignId), "campaign_id"); Mapping.Long(b, nameof(AdvertisingCampaignCategory.CategoryId), "category_id"); Mapping.CreatedAudit(b); Mapping.Fk<AdvertisingCampaignCategory, AdvertisingCampaign>(b, nameof(AdvertisingCampaignCategory.CampaignId)); Mapping.Fk<AdvertisingCampaignCategory, ServiceCategory>(b, nameof(AdvertisingCampaignCategory.CategoryId)); b.HasIndex(x => new { x.CampaignId, x.CategoryId }).IsUnique(); b.HasIndex(x => x.CategoryId); } }
internal sealed class AdvertisingCampaignAreaConfiguration() : EntityConfiguration<AdvertisingCampaignArea>("advertising_campaign_areas")
{ protected override void ConfigureEntity(EntityTypeBuilder<AdvertisingCampaignArea> b) { Mapping.Long(b, nameof(AdvertisingCampaignArea.CampaignId), "campaign_id"); Mapping.Long(b, nameof(AdvertisingCampaignArea.AdministrativeAreaId), "administrative_area_id"); Mapping.CreatedAudit(b); Mapping.Fk<AdvertisingCampaignArea, AdvertisingCampaign>(b, nameof(AdvertisingCampaignArea.CampaignId)); Mapping.Fk<AdvertisingCampaignArea, AdministrativeArea>(b, nameof(AdvertisingCampaignArea.AdministrativeAreaId)); b.HasIndex(x => new { x.CampaignId, x.AdministrativeAreaId }).IsUnique(); b.HasIndex(x => x.AdministrativeAreaId); } }

internal sealed class AdvertisingCreativeConfiguration() : EntityConfiguration<AdvertisingCreative>("advertising_creatives")
{
    protected override void ConfigureEntity(EntityTypeBuilder<AdvertisingCreative> b)
    {
        Mapping.PublicId(b); Mapping.Long(b, nameof(AdvertisingCreative.CampaignId), "campaign_id"); Mapping.String(b, nameof(AdvertisingCreative.Title), "title", 200); Mapping.String(b, nameof(AdvertisingCreative.Subtitle), "subtitle", 300, nullable: true);
        Mapping.String(b, nameof(AdvertisingCreative.BodyText), "body_text", 4000, nullable: true); Mapping.NullableLong(b, nameof(AdvertisingCreative.FileId), "file_id"); Mapping.String(b, nameof(AdvertisingCreative.AltText), "alt_text", 300, nullable: true);
        Mapping.String(b, nameof(AdvertisingCreative.ButtonText), "button_text", 50, nullable: true); Mapping.String(b, nameof(AdvertisingCreative.DestinationTypeCode), "destination_type_code", 30, nullable: true, unicode: false); Mapping.String(b, nameof(AdvertisingCreative.DestinationValue), "destination_value", 2000, nullable: true, unicode: false);
        Mapping.Int(b, nameof(AdvertisingCreative.DisplayOrder), "display_order", 0); Mapping.String(b, nameof(AdvertisingCreative.StatusCode), "status_code", 20, unicode: false); Mapping.FullAudit(b);
        Mapping.Fk<AdvertisingCreative, AdvertisingCampaign>(b, nameof(AdvertisingCreative.CampaignId)); Mapping.Fk<AdvertisingCreative, StoredFile>(b, nameof(AdvertisingCreative.FileId)); b.HasIndex(x => new { x.CampaignId, x.DisplayOrder }); b.HasIndex(x => x.FileId);
        b.ToTable("advertising_creatives", t => { t.HasCheckConstraint("CK_advertising_creatives_status", "[status_code] IN ('ACTIVE','INACTIVE')"); t.HasCheckConstraint("CK_advertising_creatives_destination", "[destination_type_code] IS NULL OR [destination_type_code] IN ('NONE','INTERNAL_PATH','EXTERNAL_URL')"); t.HasCheckConstraint("CK_advertising_creatives_order", "[display_order] >= 0"); });
    }
}

internal sealed class AdvertisingEventConfiguration() : EntityConfiguration<AdvertisingEvent>("advertising_events")
{ protected override void ConfigureEntity(EntityTypeBuilder<AdvertisingEvent> b) { Mapping.Long(b, nameof(AdvertisingEvent.CreativeId), "creative_id"); Mapping.Long(b, nameof(AdvertisingEvent.PlacementId), "placement_id"); Mapping.String(b, nameof(AdvertisingEvent.EventTypeCode), "event_type_code", 20, unicode: false); Mapping.DateTime(b, nameof(AdvertisingEvent.OccurredAt), "occurred_at", utcDefault: true); Mapping.Fk<AdvertisingEvent, AdvertisingCreative>(b, nameof(AdvertisingEvent.CreativeId)); Mapping.Fk<AdvertisingEvent, AdvertisingPlacement>(b, nameof(AdvertisingEvent.PlacementId)); b.HasIndex(x => new { x.CreativeId, x.PlacementId, x.EventTypeCode, x.OccurredAt }); b.ToTable("advertising_events", t => t.HasCheckConstraint("CK_advertising_events_type", "[event_type_code] IN ('IMPRESSION','CLICK')")); } }

internal sealed class ProviderAdvertisingRatePolicyConfiguration() : EntityConfiguration<ProviderAdvertisingRatePolicy>("provider_advertising_rate_policies")
{
    protected override void ConfigureEntity(EntityTypeBuilder<ProviderAdvertisingRatePolicy> b)
    {
        Mapping.PublicId(b); Mapping.Long(b, nameof(ProviderAdvertisingRatePolicy.PlacementId), "placement_id"); Mapping.Int(b, nameof(ProviderAdvertisingRatePolicy.DurationDays), "duration_days");
        Mapping.Decimal(b, nameof(ProviderAdvertisingRatePolicy.FixedAmount), "fixed_amount"); Mapping.Decimal(b, nameof(ProviderAdvertisingRatePolicy.ProvinceUnitAmount), "province_unit_amount", defaultValue: 10000); Mapping.Decimal(b, nameof(ProviderAdvertisingRatePolicy.DistrictUnitAmount), "district_unit_amount", defaultValue: 2000); Mapping.Decimal(b, nameof(ProviderAdvertisingRatePolicy.RegionalFeeCapAmount), "regional_fee_cap_amount", defaultValue: 30000); Mapping.String(b, nameof(ProviderAdvertisingRatePolicy.CurrencyCode), "currency_code", 3, unicode: false, fixedLength: true);
        Mapping.Date(b, nameof(ProviderAdvertisingRatePolicy.EffectiveFrom), "effective_from"); Mapping.Date(b, nameof(ProviderAdvertisingRatePolicy.EffectiveTo), "effective_to", nullable: true); Mapping.Bool(b, nameof(ProviderAdvertisingRatePolicy.IsActive), "is_active", true); Mapping.FullAudit(b);
        Mapping.Fk<ProviderAdvertisingRatePolicy, AdvertisingPlacement>(b, nameof(ProviderAdvertisingRatePolicy.PlacementId)); b.HasIndex(x => new { x.PlacementId, x.DurationDays, x.EffectiveFrom }).IsUnique(); b.HasIndex(x => new { x.IsActive, x.EffectiveFrom, x.EffectiveTo });
        b.ToTable("provider_advertising_rate_policies", t => { t.HasCheckConstraint("CK_provider_ad_rate_duration", "[duration_days] IN (7,14,30)"); t.HasCheckConstraint("CK_provider_ad_rate_amount", "[fixed_amount] > 0 AND [province_unit_amount] >= 0 AND [district_unit_amount] >= 0 AND [regional_fee_cap_amount] >= 0"); t.HasCheckConstraint("CK_provider_ad_rate_period", "[effective_to] IS NULL OR [effective_to] >= [effective_from]"); });
        var at = new DateTime(2026, 8, 19, 0, 0, 0, DateTimeKind.Utc); var from = new DateOnly(2026, 8, 19);
        b.HasData(
            new ProviderAdvertisingRatePolicy { Id=1, PublicId=Guid.Parse("11a20000-0000-0000-0000-000000000001"), PlacementId=1, DurationDays=7, FixedAmount=35000, CurrencyCode="KRW", EffectiveFrom=from, IsActive=true, CreatedAt=at, UpdatedAt=at },
            new ProviderAdvertisingRatePolicy { Id=2, PublicId=Guid.Parse("11a20000-0000-0000-0000-000000000002"), PlacementId=1, DurationDays=14, FixedAmount=60000, CurrencyCode="KRW", EffectiveFrom=from, IsActive=true, CreatedAt=at, UpdatedAt=at },
            new ProviderAdvertisingRatePolicy { Id=3, PublicId=Guid.Parse("11a20000-0000-0000-0000-000000000003"), PlacementId=1, DurationDays=30, FixedAmount=110000, CurrencyCode="KRW", EffectiveFrom=from, IsActive=true, CreatedAt=at, UpdatedAt=at },
            new ProviderAdvertisingRatePolicy { Id=4, PublicId=Guid.Parse("11a20000-0000-0000-0000-000000000004"), PlacementId=2, DurationDays=7, FixedAmount=21000, CurrencyCode="KRW", EffectiveFrom=from, IsActive=true, CreatedAt=at, UpdatedAt=at },
            new ProviderAdvertisingRatePolicy { Id=5, PublicId=Guid.Parse("11a20000-0000-0000-0000-000000000005"), PlacementId=2, DurationDays=14, FixedAmount=36000, CurrencyCode="KRW", EffectiveFrom=from, IsActive=true, CreatedAt=at, UpdatedAt=at },
            new ProviderAdvertisingRatePolicy { Id=6, PublicId=Guid.Parse("11a20000-0000-0000-0000-000000000006"), PlacementId=2, DurationDays=30, FixedAmount=66000, CurrencyCode="KRW", EffectiveFrom=from, IsActive=true, CreatedAt=at, UpdatedAt=at },
            new ProviderAdvertisingRatePolicy { Id=7, PublicId=Guid.Parse("11a20000-0000-0000-0000-000000000007"), PlacementId=3, DurationDays=7, FixedAmount=28000, CurrencyCode="KRW", EffectiveFrom=from, IsActive=true, CreatedAt=at, UpdatedAt=at },
            new ProviderAdvertisingRatePolicy { Id=8, PublicId=Guid.Parse("11a20000-0000-0000-0000-000000000008"), PlacementId=3, DurationDays=14, FixedAmount=48000, CurrencyCode="KRW", EffectiveFrom=from, IsActive=true, CreatedAt=at, UpdatedAt=at },
            new ProviderAdvertisingRatePolicy { Id=9, PublicId=Guid.Parse("11a20000-0000-0000-0000-000000000009"), PlacementId=3, DurationDays=30, FixedAmount=88000, CurrencyCode="KRW", EffectiveFrom=from, IsActive=true, CreatedAt=at, UpdatedAt=at });
    }
}

internal sealed class ProviderAdvertisingApplicationConfiguration() : EntityConfiguration<ProviderAdvertisingApplication>("provider_advertising_applications")
{
    protected override void ConfigureEntity(EntityTypeBuilder<ProviderAdvertisingApplication> b)
    {
        Mapping.PublicId(b); Mapping.Long(b, nameof(ProviderAdvertisingApplication.CampaignId), "campaign_id"); Mapping.Long(b, nameof(ProviderAdvertisingApplication.ProviderProfileId), "provider_profile_id"); Mapping.Long(b, nameof(ProviderAdvertisingApplication.RatePolicyId), "rate_policy_id"); Mapping.Long(b, nameof(ProviderAdvertisingApplication.WalletId), "wallet_id");
        Mapping.Int(b, nameof(ProviderAdvertisingApplication.DurationDays), "duration_days"); Mapping.Decimal(b, nameof(ProviderAdvertisingApplication.FeeAmount), "fee_amount"); Mapping.Decimal(b, nameof(ProviderAdvertisingApplication.BaseFeeAmount), "base_fee_amount"); Mapping.Decimal(b, nameof(ProviderAdvertisingApplication.RegionalFeeAmount), "regional_fee_amount"); Mapping.Int(b, nameof(ProviderAdvertisingApplication.ProvinceTargetCount), "province_target_count"); Mapping.Int(b, nameof(ProviderAdvertisingApplication.DistrictTargetCount), "district_target_count"); Mapping.String(b, nameof(ProviderAdvertisingApplication.CurrencyCode), "currency_code", 3, unicode:false, fixedLength:true);
        Mapping.String(b, nameof(ProviderAdvertisingApplication.StatusCode), "status_code", 20, unicode:false); Mapping.String(b, nameof(ProviderAdvertisingApplication.FeeStatusCode), "fee_status_code", 20, unicode:false);
        Mapping.Bool(b,nameof(ProviderAdvertisingApplication.AutoRenewEnabled),"auto_renew_enabled",false); Mapping.String(b,nameof(ProviderAdvertisingApplication.AutoRenewStatusCode),"auto_renew_status_code",30,unicode:false,defaultValue:"OFF"); Mapping.DateTime(b,nameof(ProviderAdvertisingApplication.NextRenewalAt),"next_renewal_at",nullable:true); Mapping.DateTime(b,nameof(ProviderAdvertisingApplication.RenewalNoticeSentAt),"renewal_notice_sent_at",nullable:true); Mapping.Bool(b,nameof(ProviderAdvertisingApplication.RenewalConsentRequired),"renewal_consent_required",false); Mapping.DateTime(b,nameof(ProviderAdvertisingApplication.RenewalConsentAt),"renewal_consent_at",nullable:true); Mapping.Decimal(b,nameof(ProviderAdvertisingApplication.RenewalConsentFeeAmount),"renewal_consent_fee_amount",nullable:true); Mapping.String(b,nameof(ProviderAdvertisingApplication.RenewalConsentPolicyFingerprint),"renewal_consent_policy_fingerprint",128,nullable:true,unicode:false); Mapping.Int(b,nameof(ProviderAdvertisingApplication.RenewalCycleNo),"renewal_cycle_no",0); Mapping.DateTime(b,nameof(ProviderAdvertisingApplication.LastRenewedAt),"last_renewed_at",nullable:true); Mapping.DateTime(b,nameof(ProviderAdvertisingApplication.AutoRenewDisabledAt),"auto_renew_disabled_at",nullable:true);
        Mapping.Long(b, nameof(ProviderAdvertisingApplication.ReserveLedgerEntryId), "reserve_ledger_entry_id"); Mapping.NullableLong(b, nameof(ProviderAdvertisingApplication.CaptureLedgerEntryId), "capture_ledger_entry_id"); Mapping.NullableLong(b, nameof(ProviderAdvertisingApplication.ReleaseLedgerEntryId), "release_ledger_entry_id");
        Mapping.String(b, nameof(ProviderAdvertisingApplication.SupplementNote), "supplement_note", 2000, nullable:true); Mapping.String(b, nameof(ProviderAdvertisingApplication.RejectionReason), "rejection_reason", 2000, nullable:true);
        Mapping.DateTime(b, nameof(ProviderAdvertisingApplication.SubmittedAt), "submitted_at"); Mapping.DateTime(b, nameof(ProviderAdvertisingApplication.ResubmittedAt), "resubmitted_at", nullable:true); Mapping.DateTime(b, nameof(ProviderAdvertisingApplication.ApprovedAt), "approved_at", nullable:true); Mapping.DateTime(b, nameof(ProviderAdvertisingApplication.PublishedAt), "published_at", nullable:true); Mapping.DateTime(b, nameof(ProviderAdvertisingApplication.CancelledAt), "cancelled_at", nullable:true); Mapping.FullAudit(b);
        Mapping.Fk<ProviderAdvertisingApplication, AdvertisingCampaign>(b, nameof(ProviderAdvertisingApplication.CampaignId)); Mapping.Fk<ProviderAdvertisingApplication, ProviderProfile>(b, nameof(ProviderAdvertisingApplication.ProviderProfileId)); Mapping.Fk<ProviderAdvertisingApplication, ProviderAdvertisingRatePolicy>(b, nameof(ProviderAdvertisingApplication.RatePolicyId)); Mapping.Fk<ProviderAdvertisingApplication, ProviderWallet>(b, nameof(ProviderAdvertisingApplication.WalletId)); Mapping.Fk<ProviderAdvertisingApplication, WalletLedgerEntry>(b, nameof(ProviderAdvertisingApplication.ReserveLedgerEntryId)); Mapping.Fk<ProviderAdvertisingApplication, WalletLedgerEntry>(b, nameof(ProviderAdvertisingApplication.CaptureLedgerEntryId)); Mapping.Fk<ProviderAdvertisingApplication, WalletLedgerEntry>(b, nameof(ProviderAdvertisingApplication.ReleaseLedgerEntryId));
        b.HasIndex(x=>x.CampaignId).IsUnique(); b.HasIndex(x=>new{x.ProviderProfileId,x.StatusCode,x.SubmittedAt}); b.HasIndex(x=>new{x.StatusCode,x.UpdatedAt});
        b.HasIndex(x=>new{x.AutoRenewEnabled,x.AutoRenewStatusCode,x.NextRenewalAt});
        b.ToTable("provider_advertising_applications", t=>{t.HasCheckConstraint("CK_provider_ad_app_status", "[status_code] IN ('SUBMITTED','REJECTED','RESUBMITTED','APPROVED','PUBLISHED','CANCELLED')");t.HasCheckConstraint("CK_provider_ad_app_fee_status", "[fee_status_code] IN ('RESERVED','CAPTURED','RELEASED')");t.HasCheckConstraint("CK_provider_ad_app_amount", "[fee_amount] > 0 AND [base_fee_amount] >= 0 AND [regional_fee_amount] >= 0 AND [province_target_count] >= 0 AND [district_target_count] >= 0");t.HasCheckConstraint("CK_provider_ad_app_auto_renew_status","[auto_renew_status_code] IN ('OFF','PENDING_PUBLICATION','ACTIVE','CONSENT_REQUIRED','PAUSED_INSUFFICIENT','CANCELLED')");t.HasCheckConstraint("CK_provider_ad_app_renewal_cycle","[renewal_cycle_no] >= 0");});
    }
}

internal sealed class ProviderAdvertisingRenewalHistoryConfiguration() : EntityConfiguration<ProviderAdvertisingRenewalHistory>("provider_advertising_renewal_history")
{
    protected override void ConfigureEntity(EntityTypeBuilder<ProviderAdvertisingRenewalHistory> b)
    {
        Mapping.PublicId(b);Mapping.Long(b,nameof(ProviderAdvertisingRenewalHistory.ProviderAdvertisingApplicationId),"provider_advertising_application_id");Mapping.Int(b,nameof(ProviderAdvertisingRenewalHistory.CycleNo),"cycle_no");Mapping.DateTime(b,nameof(ProviderAdvertisingRenewalHistory.DueAt),"due_at");Mapping.Decimal(b,nameof(ProviderAdvertisingRenewalHistory.BaseFeeAmount),"base_fee_amount");Mapping.Decimal(b,nameof(ProviderAdvertisingRenewalHistory.RegionalFeeAmount),"regional_fee_amount");Mapping.Decimal(b,nameof(ProviderAdvertisingRenewalHistory.FeeAmount),"fee_amount");Mapping.String(b,nameof(ProviderAdvertisingRenewalHistory.CurrencyCode),"currency_code",3,unicode:false,fixedLength:true);Mapping.String(b,nameof(ProviderAdvertisingRenewalHistory.StatusCode),"status_code",30,unicode:false);Mapping.NullableLong(b,nameof(ProviderAdvertisingRenewalHistory.ReserveLedgerEntryId),"reserve_ledger_entry_id");Mapping.NullableLong(b,nameof(ProviderAdvertisingRenewalHistory.CaptureLedgerEntryId),"capture_ledger_entry_id");Mapping.DateTime(b,nameof(ProviderAdvertisingRenewalHistory.NoticeSentAt),"notice_sent_at",nullable:true);Mapping.DateTime(b,nameof(ProviderAdvertisingRenewalHistory.ProcessedAt),"processed_at",nullable:true);Mapping.String(b,nameof(ProviderAdvertisingRenewalHistory.FailureReason),"failure_reason",1000,nullable:true);Mapping.String(b,nameof(ProviderAdvertisingRenewalHistory.PolicyFingerprint),"policy_fingerprint",128,unicode:false);Mapping.FullAudit(b);Mapping.Fk<ProviderAdvertisingRenewalHistory,ProviderAdvertisingApplication>(b,nameof(ProviderAdvertisingRenewalHistory.ProviderAdvertisingApplicationId));Mapping.Fk<ProviderAdvertisingRenewalHistory,WalletLedgerEntry>(b,nameof(ProviderAdvertisingRenewalHistory.ReserveLedgerEntryId));Mapping.Fk<ProviderAdvertisingRenewalHistory,WalletLedgerEntry>(b,nameof(ProviderAdvertisingRenewalHistory.CaptureLedgerEntryId));b.HasIndex(x=>new{x.ProviderAdvertisingApplicationId,x.CycleNo}).IsUnique();b.HasIndex(x=>new{x.StatusCode,x.DueAt});b.ToTable("provider_advertising_renewal_history",t=>{t.HasCheckConstraint("CK_provider_ad_renewal_status","[status_code] IN ('PENDING','NOTICE_SENT','RENEWED','PAUSED_INSUFFICIENT','CONSENT_REQUIRED','CANCELLED')");t.HasCheckConstraint("CK_provider_ad_renewal_amount","[fee_amount] > 0 AND [base_fee_amount] >= 0 AND [regional_fee_amount] >= 0");t.HasCheckConstraint("CK_provider_ad_renewal_cycle","[cycle_no] > 0");});
    }
}

internal sealed class ManagedContentConfiguration() : EntityConfiguration<ManagedContent>("managed_contents")
{
    protected override void ConfigureEntity(EntityTypeBuilder<ManagedContent> b)
    {
        Mapping.PublicId(b); Mapping.String(b, nameof(ManagedContent.ContentTypeCode), "content_type_code", 30, unicode: false); Mapping.String(b, nameof(ManagedContent.AudienceTypeCode), "audience_type_code", 20, unicode: false);
        Mapping.String(b, nameof(ManagedContent.StatusCode), "status_code", 20, unicode: false); Mapping.String(b, nameof(ManagedContent.ReviewStatusCode), "review_status_code", 20, unicode: false); Mapping.Int(b, nameof(ManagedContent.CurrentVersionNo), "current_version_no", 1); Mapping.Int(b, nameof(ManagedContent.DisplayOrder), "display_order", 0);
        Mapping.DateTime(b, nameof(ManagedContent.StartAt), "start_at"); Mapping.DateTime(b, nameof(ManagedContent.EndAt), "end_at", nullable: true); Mapping.NullableLong(b, nameof(ManagedContent.ApprovedByUserId), "approved_by_user_id"); Mapping.DateTime(b, nameof(ManagedContent.ApprovedAt), "approved_at", nullable: true); Mapping.String(b, nameof(ManagedContent.RejectionReason), "rejection_reason", 1000, nullable: true); Mapping.FullAudit(b); Mapping.Fk<ManagedContent, User>(b, nameof(ManagedContent.ApprovedByUserId));
        b.HasIndex(x => new { x.ContentTypeCode, x.StatusCode, x.ReviewStatusCode, x.StartAt, x.EndAt }); b.HasIndex(x => new { x.AudienceTypeCode, x.StartAt });
        b.ToTable("managed_contents", t => { t.HasCheckConstraint("CK_managed_contents_type", "[content_type_code] IN ('NOTICE','FAQ','SAFETY_GUIDE','CATEGORY_GUIDE','PRICE_REFERENCE')"); t.HasCheckConstraint("CK_managed_contents_audience", "[audience_type_code] IN ('ALL','CUSTOMER','PROVIDER')"); t.HasCheckConstraint("CK_managed_contents_status", "[status_code] IN ('DRAFT','ACTIVE','PAUSED','ARCHIVED')"); t.HasCheckConstraint("CK_managed_contents_review", "[review_status_code] IN ('DRAFT','PENDING','APPROVED','REJECTED')"); t.HasCheckConstraint("CK_managed_contents_period", "[end_at] IS NULL OR [end_at] > [start_at]"); t.HasCheckConstraint("CK_managed_contents_version", "[current_version_no] > 0"); t.HasCheckConstraint("CK_managed_contents_order", "[display_order] >= 0"); });
    }
}

internal sealed class ManagedContentVersionConfiguration() : EntityConfiguration<ManagedContentVersion>("managed_content_versions")
{
    protected override void ConfigureEntity(EntityTypeBuilder<ManagedContentVersion> b)
    {
        Mapping.PublicId(b); Mapping.Long(b, nameof(ManagedContentVersion.ContentId), "content_id"); Mapping.Int(b, nameof(ManagedContentVersion.VersionNo), "version_no"); Mapping.String(b, nameof(ManagedContentVersion.Title), "title", 300); Mapping.String(b, nameof(ManagedContentVersion.BodyText), "body_text", null, nullable: true); Mapping.String(b, nameof(ManagedContentVersion.QuestionText), "question_text", 1000, nullable: true); Mapping.String(b, nameof(ManagedContentVersion.AnswerText), "answer_text", null, nullable: true); Mapping.NullableLong(b, nameof(ManagedContentVersion.FileId), "file_id"); Mapping.String(b, nameof(ManagedContentVersion.LinkText), "link_text", 100, nullable: true); Mapping.String(b, nameof(ManagedContentVersion.DestinationTypeCode), "destination_type_code", 30, unicode: false); Mapping.String(b, nameof(ManagedContentVersion.DestinationValue), "destination_value", 2000, nullable: true, unicode: false); Mapping.String(b, nameof(ManagedContentVersion.ChangeReason), "change_reason", 1000, nullable: true); Mapping.CreatedAudit(b); Mapping.Fk<ManagedContentVersion, ManagedContent>(b, nameof(ManagedContentVersion.ContentId)); Mapping.Fk<ManagedContentVersion, StoredFile>(b, nameof(ManagedContentVersion.FileId)); b.HasIndex(x => new { x.ContentId, x.VersionNo }).IsUnique(); b.HasIndex(x => x.FileId); b.ToTable("managed_content_versions", t => { t.HasCheckConstraint("CK_managed_content_versions_version", "[version_no] > 0"); t.HasCheckConstraint("CK_managed_content_versions_destination", "[destination_type_code] IN ('NONE','INTERNAL_PATH','EXTERNAL_URL')"); });
    }
}

internal sealed class ManagedContentCategoryConfiguration() : EntityConfiguration<ManagedContentCategory>("managed_content_categories")
{ protected override void ConfigureEntity(EntityTypeBuilder<ManagedContentCategory> b) { Mapping.Long(b, nameof(ManagedContentCategory.ContentId), "content_id"); Mapping.Long(b, nameof(ManagedContentCategory.CategoryId), "category_id"); Mapping.CreatedAudit(b); Mapping.Fk<ManagedContentCategory, ManagedContent>(b, nameof(ManagedContentCategory.ContentId)); Mapping.Fk<ManagedContentCategory, ServiceCategory>(b, nameof(ManagedContentCategory.CategoryId)); b.HasIndex(x => new { x.ContentId, x.CategoryId }).IsUnique(); b.HasIndex(x => x.CategoryId); } }
internal sealed class ManagedContentAreaConfiguration() : EntityConfiguration<ManagedContentArea>("managed_content_areas")
{ protected override void ConfigureEntity(EntityTypeBuilder<ManagedContentArea> b) { Mapping.Long(b, nameof(ManagedContentArea.ContentId), "content_id"); Mapping.Long(b, nameof(ManagedContentArea.AdministrativeAreaId), "administrative_area_id"); Mapping.CreatedAudit(b); Mapping.Fk<ManagedContentArea, ManagedContent>(b, nameof(ManagedContentArea.ContentId)); Mapping.Fk<ManagedContentArea, AdministrativeArea>(b, nameof(ManagedContentArea.AdministrativeAreaId)); b.HasIndex(x => new { x.ContentId, x.AdministrativeAreaId }).IsUnique(); b.HasIndex(x => x.AdministrativeAreaId); } }
