using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using SoodalLife.Api.Domain.Entities;

namespace SoodalLife.Api.Infrastructure.Persistence.Configurations;

internal sealed class InteriorProjectConfiguration() : EntityConfiguration<InteriorProject>("interior_projects")
{
    protected override void ConfigureEntity(EntityTypeBuilder<InteriorProject> b)
    {
        Mapping.PublicId(b); Mapping.Long(b,nameof(InteriorProject.ServiceRequestId),"service_request_id"); Mapping.Long(b,nameof(InteriorProject.CustomerProfileId),"customer_profile_id"); Mapping.Long(b,nameof(InteriorProject.ServiceCategoryId),"service_category_id"); Mapping.String(b,nameof(InteriorProject.StatusCode),"status_code",40,unicode:false);
        Mapping.NullableLong(b,nameof(InteriorProject.SelectedSiteVisitProviderId),"selected_site_visit_provider_id"); Mapping.NullableLong(b,nameof(InteriorProject.SelectedContractorProviderId),"selected_contractor_provider_id"); Mapping.DateTime(b,nameof(InteriorProject.SiteVisitSelectedAt),"site_visit_selected_at",nullable:true); Mapping.DateTime(b,nameof(InteriorProject.ContractorSelectedAt),"contractor_selected_at",nullable:true); Mapping.NullableLong(b,nameof(InteriorProject.CurrentQuoteRevisionId),"current_quote_revision_id"); Mapping.NullableLong(b,nameof(InteriorProject.CurrentContractId),"current_contract_id");
        Mapping.Decimal(b,nameof(InteriorProject.SiteVisitProviderTrustScoreSnapshot),"site_visit_provider_trust_score_snapshot",nullable:true,precision:9,scale:4); Mapping.Decimal(b,nameof(InteriorProject.ContractorTrustScoreSnapshot),"contractor_trust_score_snapshot",nullable:true,precision:9,scale:4); Mapping.String(b,nameof(InteriorProject.FeeAssessmentStatusCode),"fee_assessment_status_code",30,unicode:false,defaultValue:"POLICY_PENDING"); Mapping.Date(b,nameof(InteriorProject.ProjectStartDate),"project_start_date",nullable:true); Mapping.Date(b,nameof(InteriorProject.ExpectedCompletionDate),"expected_completion_date",nullable:true); Mapping.Date(b,nameof(InteriorProject.ActualCompletionDate),"actual_completion_date",nullable:true); Mapping.DateTime(b,nameof(InteriorProject.ProviderCompletionSubmittedAt),"provider_completion_submitted_at",true); Mapping.NullableLong(b,nameof(InteriorProject.ProviderCompletionSubmittedByUserId),"provider_completion_submitted_by_user_id"); Mapping.String(b,nameof(InteriorProject.ProviderCompletionSummary),"provider_completion_summary",4000,true); Mapping.String(b,nameof(InteriorProject.ProviderFinalChecklistJson),"provider_final_checklist_json",null,true); Mapping.DateTime(b,nameof(InteriorProject.CustomerCompletionAcknowledgedAt),"customer_completion_acknowledged_at",true); Mapping.NullableLong(b,nameof(InteriorProject.CustomerCompletionAcknowledgedByUserId),"customer_completion_acknowledged_by_user_id"); Mapping.String(b,nameof(InteriorProject.CustomerCompletionComment),"customer_completion_comment",2000,true); Mapping.DateTime(b,nameof(InteriorProject.AdminCompletedAt),"admin_completed_at",true); Mapping.NullableLong(b,nameof(InteriorProject.AdminCompletedByUserId),"admin_completed_by_user_id"); Mapping.FullAudit(b);
        Mapping.Fk<InteriorProject,ServiceRequest>(b,nameof(InteriorProject.ServiceRequestId)); Mapping.Fk<InteriorProject,CustomerProfile>(b,nameof(InteriorProject.CustomerProfileId)); Mapping.Fk<InteriorProject,ServiceCategory>(b,nameof(InteriorProject.ServiceCategoryId)); Mapping.Fk<InteriorProject,ProviderProfile>(b,nameof(InteriorProject.SelectedSiteVisitProviderId)); Mapping.Fk<InteriorProject,ProviderProfile>(b,nameof(InteriorProject.SelectedContractorProviderId)); Mapping.Fk<InteriorProject,QuoteRevision>(b,nameof(InteriorProject.CurrentQuoteRevisionId)); Mapping.Fk<InteriorProject,InteriorContract>(b,nameof(InteriorProject.CurrentContractId)); Mapping.Fk<InteriorProject,User>(b,nameof(InteriorProject.ProviderCompletionSubmittedByUserId)); Mapping.Fk<InteriorProject,User>(b,nameof(InteriorProject.CustomerCompletionAcknowledgedByUserId)); Mapping.Fk<InteriorProject,User>(b,nameof(InteriorProject.AdminCompletedByUserId));
        b.HasIndex(x=>x.ServiceRequestId).IsUnique(); b.HasIndex(x=>new{x.StatusCode,x.UpdatedAt}); b.HasIndex(x=>x.SelectedSiteVisitProviderId); b.HasIndex(x=>x.SelectedContractorProviderId);
        b.ToTable("interior_projects",t=>{t.HasCheckConstraint("CK_interior_projects_status","[status_code] IN ('CONSULTATION','SITE_VISIT_SELECTION','SITE_VISIT_SCHEDULED','SITE_VISIT_COMPLETED','ESTIMATE_IN_PROGRESS','ESTIMATE_READY','CONTRACT_PENDING','CONTRACTED','CONSTRUCTION','INSPECTION','COMPLETED','DEFECT_MANAGEMENT','CANCELLED')");t.HasCheckConstraint("CK_interior_projects_fee","[fee_assessment_status_code] IN ('POLICY_PENDING','NOT_APPLICABLE','ASSESSED')");});
    }
}

internal sealed class InteriorProjectParticipantConfiguration() : EntityConfiguration<InteriorProjectParticipant>("interior_project_participants")
{
    protected override void ConfigureEntity(EntityTypeBuilder<InteriorProjectParticipant> b){Mapping.PublicId(b);Mapping.Long(b,nameof(InteriorProjectParticipant.InteriorProjectId),"interior_project_id");Mapping.Long(b,nameof(InteriorProjectParticipant.ProviderProfileId),"provider_profile_id");Mapping.String(b,nameof(InteriorProjectParticipant.RoleCode),"role_code",40,unicode:false);Mapping.DateTime(b,nameof(InteriorProjectParticipant.EffectiveFrom),"effective_from");Mapping.DateTime(b,nameof(InteriorProjectParticipant.EffectiveTo),"effective_to",true);Mapping.String(b,nameof(InteriorProjectParticipant.StatusCode),"status_code",20,unicode:false);Mapping.Bool(b,nameof(InteriorProjectParticipant.IsPrimary),"is_primary",false);Mapping.String(b,nameof(InteriorProjectParticipant.ScopeText),"scope_text",2000,true);Mapping.FullAudit(b);Mapping.Fk<InteriorProjectParticipant,InteriorProject>(b,nameof(InteriorProjectParticipant.InteriorProjectId));Mapping.Fk<InteriorProjectParticipant,ProviderProfile>(b,nameof(InteriorProjectParticipant.ProviderProfileId));b.HasIndex(x=>new{x.InteriorProjectId,x.ProviderProfileId,x.RoleCode}).IsUnique();b.HasIndex(x=>new{x.ProviderProfileId,x.StatusCode,x.EffectiveTo});b.ToTable("interior_project_participants",t=>{t.HasCheckConstraint("CK_interior_project_participants_role","[role_code] IN ('SITE_SURVEY','DESIGN','PRIMARY_CONTRACTOR','TRADE_CONTRACTOR','INSPECTION','AFTER_SERVICE')");t.HasCheckConstraint("CK_interior_project_participants_status","[status_code] IN ('ACTIVE','ENDED','CANCELLED')");t.HasCheckConstraint("CK_interior_project_participants_period","[effective_to] IS NULL OR [effective_to] >= [effective_from]");});}
}

internal sealed class InteriorSiteVisitConfiguration() : EntityConfiguration<InteriorSiteVisit>("interior_site_visits")
{
    protected override void ConfigureEntity(EntityTypeBuilder<InteriorSiteVisit> b){Mapping.PublicId(b);Mapping.Long(b,nameof(InteriorSiteVisit.InteriorProjectId),"interior_project_id");Mapping.Long(b,nameof(InteriorSiteVisit.ProviderProfileId),"provider_profile_id");Mapping.String(b,nameof(InteriorSiteVisit.StatusCode),"status_code",30,unicode:false);Mapping.DateTime(b,nameof(InteriorSiteVisit.ProposedAt),"proposed_at",true);Mapping.DateTime(b,nameof(InteriorSiteVisit.ConfirmedAt),"confirmed_at",true);Mapping.DateTime(b,nameof(InteriorSiteVisit.ScheduledStartAt),"scheduled_start_at");Mapping.DateTime(b,nameof(InteriorSiteVisit.ScheduledEndAt),"scheduled_end_at",true);Mapping.String(b,nameof(InteriorSiteVisit.AccessConditionText),"access_condition_text",2000,true);Mapping.DateTime(b,nameof(InteriorSiteVisit.VisitedAt),"visited_at",true);Mapping.DateTime(b,nameof(InteriorSiteVisit.CompletedAt),"completed_at",true);Mapping.String(b,nameof(InteriorSiteVisit.MeasurementSummaryText),"measurement_summary_text",4000,true);Mapping.String(b,nameof(InteriorSiteVisit.ConstraintText),"constraint_text",4000,true);Mapping.String(b,nameof(InteriorSiteVisit.RiskNoteText),"risk_note_text",4000,true);Mapping.DateTime(b,nameof(InteriorSiteVisit.CustomerConfirmedAt),"customer_confirmed_at",true);Mapping.DateTime(b,nameof(InteriorSiteVisit.CancelledAt),"cancelled_at",true);Mapping.String(b,nameof(InteriorSiteVisit.CancellationReason),"cancellation_reason",2000,true);Mapping.FullAudit(b);Mapping.Fk<InteriorSiteVisit,InteriorProject>(b,nameof(InteriorSiteVisit.InteriorProjectId));Mapping.Fk<InteriorSiteVisit,ProviderProfile>(b,nameof(InteriorSiteVisit.ProviderProfileId));b.HasIndex(x=>new{x.InteriorProjectId,x.ProviderProfileId,x.ScheduledStartAt}).IsUnique();b.HasIndex(x=>new{x.StatusCode,x.ScheduledStartAt});b.ToTable("interior_site_visits",t=>t.HasCheckConstraint("CK_interior_site_visits_status","[status_code] IN ('PROPOSED','CONFIRMED','COMPLETED','CANCELLED','NO_SHOW')"));}
}

internal sealed class InteriorSiteVisitMeasurementConfiguration() : EntityConfiguration<InteriorSiteVisitMeasurement>("interior_site_visit_measurements")
{ protected override void ConfigureEntity(EntityTypeBuilder<InteriorSiteVisitMeasurement>b){Mapping.Long(b,nameof(InteriorSiteVisitMeasurement.SiteVisitId),"site_visit_id");Mapping.String(b,nameof(InteriorSiteVisitMeasurement.MeasurementKey),"measurement_key",100,unicode:false);Mapping.Decimal(b,nameof(InteriorSiteVisitMeasurement.MeasurementValue),"measurement_value",true);Mapping.String(b,nameof(InteriorSiteVisitMeasurement.MeasurementText),"measurement_text",1000,true);Mapping.String(b,nameof(InteriorSiteVisitMeasurement.UnitText),"unit_text",50,true);Mapping.String(b,nameof(InteriorSiteVisitMeasurement.LocationText),"location_text",500,true);Mapping.String(b,nameof(InteriorSiteVisitMeasurement.NoteText),"note_text",2000,true);Mapping.String(b,nameof(InteriorSiteVisitMeasurement.AdditionalDataJson),"additional_data_json",null,true);Mapping.CreatedAudit(b);Mapping.Fk<InteriorSiteVisitMeasurement,InteriorSiteVisit>(b,nameof(InteriorSiteVisitMeasurement.SiteVisitId));b.HasIndex(x=>new{x.SiteVisitId,x.MeasurementKey});} }
internal sealed class InteriorSiteVisitFileConfiguration() : EntityConfiguration<InteriorSiteVisitFile>("interior_site_visit_files")
{ protected override void ConfigureEntity(EntityTypeBuilder<InteriorSiteVisitFile>b){Mapping.Long(b,nameof(InteriorSiteVisitFile.SiteVisitId),"site_visit_id");Mapping.Long(b,nameof(InteriorSiteVisitFile.FileId),"file_id");Mapping.String(b,nameof(InteriorSiteVisitFile.PurposeCode),"purpose_code",50,unicode:false);Mapping.Int(b,nameof(InteriorSiteVisitFile.DisplayOrder),"display_order");Mapping.CreatedAudit(b);Mapping.Fk<InteriorSiteVisitFile,InteriorSiteVisit>(b,nameof(InteriorSiteVisitFile.SiteVisitId));Mapping.Fk<InteriorSiteVisitFile,StoredFile>(b,nameof(InteriorSiteVisitFile.FileId));b.HasIndex(x=>new{x.SiteVisitId,x.FileId}).IsUnique();} }
internal sealed class InteriorDesignVersionConfiguration() : EntityConfiguration<InteriorDesignVersion>("interior_design_versions")
{ protected override void ConfigureEntity(EntityTypeBuilder<InteriorDesignVersion>b){Mapping.PublicId(b);Mapping.Long(b,nameof(InteriorDesignVersion.InteriorProjectId),"interior_project_id");Mapping.Int(b,nameof(InteriorDesignVersion.VersionNo),"version_no");Mapping.String(b,nameof(InteriorDesignVersion.Title),"title",300);Mapping.String(b,nameof(InteriorDesignVersion.Description),"description",4000,true);Mapping.String(b,nameof(InteriorDesignVersion.StatusCode),"status_code",30,unicode:false);Mapping.DateTime(b,nameof(InteriorDesignVersion.CustomerApprovedAt),"customer_approved_at",true);Mapping.FullAudit(b);Mapping.Fk<InteriorDesignVersion,InteriorProject>(b,nameof(InteriorDesignVersion.InteriorProjectId));b.HasIndex(x=>new{x.InteriorProjectId,x.VersionNo}).IsUnique();} }
internal sealed class InteriorDesignFileConfiguration() : EntityConfiguration<InteriorDesignFile>("interior_design_files")
{ protected override void ConfigureEntity(EntityTypeBuilder<InteriorDesignFile>b){Mapping.Long(b,nameof(InteriorDesignFile.DesignVersionId),"design_version_id");Mapping.Long(b,nameof(InteriorDesignFile.FileId),"file_id");Mapping.String(b,nameof(InteriorDesignFile.PurposeCode),"purpose_code",50,unicode:false);Mapping.Int(b,nameof(InteriorDesignFile.DisplayOrder),"display_order");Mapping.CreatedAudit(b);Mapping.Fk<InteriorDesignFile,InteriorDesignVersion>(b,nameof(InteriorDesignFile.DesignVersionId));Mapping.Fk<InteriorDesignFile,StoredFile>(b,nameof(InteriorDesignFile.FileId));b.HasIndex(x=>new{x.DesignVersionId,x.FileId}).IsUnique();} }

internal sealed class InteriorContractConfiguration() : EntityConfiguration<InteriorContract>("interior_contracts")
{ protected override void ConfigureEntity(EntityTypeBuilder<InteriorContract>b){Mapping.PublicId(b);Mapping.Long(b,nameof(InteriorContract.InteriorProjectId),"interior_project_id");Mapping.Long(b,nameof(InteriorContract.CustomerProfileId),"customer_profile_id");Mapping.Long(b,nameof(InteriorContract.ProviderProfileId),"provider_profile_id");Mapping.Int(b,nameof(InteriorContract.ContractVersion),"contract_version",1);Mapping.String(b,nameof(InteriorContract.StatusCode),"status_code",30,unicode:false);Mapping.Long(b,nameof(InteriorContract.SelectedQuoteRevisionId),"selected_quote_revision_id");Mapping.Decimal(b,nameof(InteriorContract.ContractAmount),"contract_amount");Mapping.String(b,nameof(InteriorContract.CurrencyCode),"currency_code",3,unicode:false,fixedLength:true);Mapping.String(b,nameof(InteriorContract.ScopeSnapshotJson),"scope_snapshot_json",null);Mapping.String(b,nameof(InteriorContract.QuoteSnapshotJson),"quote_snapshot_json",null);Mapping.String(b,nameof(InteriorContract.ScheduleSnapshotJson),"schedule_snapshot_json",null);Mapping.String(b,nameof(InteriorContract.WarrantySnapshotJson),"warranty_snapshot_json",null,true);Mapping.Decimal(b,nameof(InteriorContract.ProviderTrustScoreSnapshot),"provider_trust_score_snapshot",true,9,4);Mapping.Date(b,nameof(InteriorContract.PlannedStartDate),"planned_start_date");Mapping.Date(b,nameof(InteriorContract.PlannedCompletionDate),"planned_completion_date");Mapping.DateTime(b,nameof(InteriorContract.CustomerAgreedAt),"customer_agreed_at",true);Mapping.DateTime(b,nameof(InteriorContract.ProviderAgreedAt),"provider_agreed_at",true);Mapping.DateTime(b,nameof(InteriorContract.EffectiveAt),"effective_at",true);Mapping.DateTime(b,nameof(InteriorContract.TerminatedAt),"terminated_at",true);Mapping.String(b,nameof(InteriorContract.TerminationReason),"termination_reason",2000,true);Mapping.FullAudit(b);Mapping.Fk<InteriorContract,InteriorProject>(b,nameof(InteriorContract.InteriorProjectId));Mapping.Fk<InteriorContract,CustomerProfile>(b,nameof(InteriorContract.CustomerProfileId));Mapping.Fk<InteriorContract,ProviderProfile>(b,nameof(InteriorContract.ProviderProfileId));Mapping.Fk<InteriorContract,QuoteRevision>(b,nameof(InteriorContract.SelectedQuoteRevisionId));b.HasIndex(x=>new{x.InteriorProjectId,x.ContractVersion}).IsUnique();b.HasIndex(x=>x.SelectedQuoteRevisionId).IsUnique();b.ToTable("interior_contracts",t=>{t.HasCheckConstraint("CK_interior_contracts_amount","[contract_amount] >= 0");t.HasCheckConstraint("CK_interior_contracts_period","[planned_completion_date] >= [planned_start_date]");});} }
internal sealed class InteriorContractVersionConfiguration() : EntityConfiguration<InteriorContractVersion>("interior_contract_versions")
{ protected override void ConfigureEntity(EntityTypeBuilder<InteriorContractVersion>b){Mapping.Long(b,nameof(InteriorContractVersion.InteriorContractId),"interior_contract_id");Mapping.Int(b,nameof(InteriorContractVersion.VersionNo),"version_no");Mapping.NullableLong(b,nameof(InteriorContractVersion.SourceContractChangeId),"source_contract_change_id");Mapping.Decimal(b,nameof(InteriorContractVersion.ContractAmount),"contract_amount");Mapping.String(b,nameof(InteriorContractVersion.CurrencyCode),"currency_code",3,unicode:false,fixedLength:true);Mapping.String(b,nameof(InteriorContractVersion.ScopeSnapshotJson),"scope_snapshot_json",null);Mapping.String(b,nameof(InteriorContractVersion.ScheduleSnapshotJson),"schedule_snapshot_json",null);Mapping.String(b,nameof(InteriorContractVersion.PaymentPlanSnapshotJson),"payment_plan_snapshot_json",null);Mapping.String(b,nameof(InteriorContractVersion.WarrantySnapshotJson),"warranty_snapshot_json",null,true);Mapping.DateTime(b,nameof(InteriorContractVersion.CustomerAgreedAt),"customer_agreed_at",true);Mapping.DateTime(b,nameof(InteriorContractVersion.ProviderAgreedAt),"provider_agreed_at",true);Mapping.CreatedAudit(b);Mapping.Fk<InteriorContractVersion,InteriorContract>(b,nameof(InteriorContractVersion.InteriorContractId));Mapping.Fk<InteriorContractVersion,InteriorContractChange>(b,nameof(InteriorContractVersion.SourceContractChangeId));b.HasIndex(x=>new{x.InteriorContractId,x.VersionNo}).IsUnique();} }
internal sealed class InteriorPaymentPlanConfiguration() : EntityConfiguration<InteriorPaymentPlan>("interior_payment_plans")
{ protected override void ConfigureEntity(EntityTypeBuilder<InteriorPaymentPlan>b){Mapping.PublicId(b);Mapping.Long(b,nameof(InteriorPaymentPlan.InteriorContractId),"interior_contract_id");Mapping.Int(b,nameof(InteriorPaymentPlan.SequenceNo),"sequence_no");Mapping.String(b,nameof(InteriorPaymentPlan.PaymentName),"payment_name",200);Mapping.Decimal(b,nameof(InteriorPaymentPlan.PlannedAmount),"planned_amount");Mapping.Date(b,nameof(InteriorPaymentPlan.PlannedDueDate),"planned_due_date",true);Mapping.String(b,nameof(InteriorPaymentPlan.ConditionText),"condition_text",2000,true);Mapping.String(b,nameof(InteriorPaymentPlan.StatusCode),"status_code",30,unicode:false);Mapping.FullAudit(b);Mapping.Fk<InteriorPaymentPlan,InteriorContract>(b,nameof(InteriorPaymentPlan.InteriorContractId));b.HasIndex(x=>new{x.InteriorContractId,x.SequenceNo}).IsUnique();b.ToTable("interior_payment_plans",t=>t.HasCheckConstraint("CK_interior_payment_plans_amount","[planned_amount] >= 0"));} }
internal sealed class InteriorPaymentConfirmationConfiguration() : EntityConfiguration<InteriorPaymentConfirmation>("interior_payment_confirmations")
{ protected override void ConfigureEntity(EntityTypeBuilder<InteriorPaymentConfirmation>b){Mapping.PublicId(b);Mapping.Long(b,nameof(InteriorPaymentConfirmation.PaymentPlanId),"payment_plan_id");Mapping.Long(b,nameof(InteriorPaymentConfirmation.ConfirmedByUserId),"confirmed_by_user_id");Mapping.String(b,nameof(InteriorPaymentConfirmation.ConfirmationTypeCode),"confirmation_type_code",30,unicode:false);Mapping.Decimal(b,nameof(InteriorPaymentConfirmation.ConfirmedAmount),"confirmed_amount");Mapping.DateTime(b,nameof(InteriorPaymentConfirmation.ConfirmedAt),"confirmed_at");Mapping.NullableLong(b,nameof(InteriorPaymentConfirmation.EvidenceFileId),"evidence_file_id");Mapping.String(b,nameof(InteriorPaymentConfirmation.NoteText),"note_text",2000,true);Mapping.DateTime(b,nameof(InteriorPaymentConfirmation.CreatedAt),"created_at",utcDefault:true);Mapping.Fk<InteriorPaymentConfirmation,InteriorPaymentPlan>(b,nameof(InteriorPaymentConfirmation.PaymentPlanId));Mapping.Fk<InteriorPaymentConfirmation,User>(b,nameof(InteriorPaymentConfirmation.ConfirmedByUserId));Mapping.Fk<InteriorPaymentConfirmation,StoredFile>(b,nameof(InteriorPaymentConfirmation.EvidenceFileId));b.HasIndex(x=>new{x.PaymentPlanId,x.ConfirmationTypeCode,x.ConfirmedByUserId}).IsUnique();b.ToTable("interior_payment_confirmations",t=>t.HasCheckConstraint("CK_interior_payment_confirmations_amount","[confirmed_amount] >= 0"));} }

internal sealed class InteriorWorkStageConfiguration() : EntityConfiguration<InteriorWorkStage>("interior_work_stages")
{ protected override void ConfigureEntity(EntityTypeBuilder<InteriorWorkStage>b){Mapping.PublicId(b);Mapping.Long(b,nameof(InteriorWorkStage.InteriorProjectId),"interior_project_id");Mapping.Int(b,nameof(InteriorWorkStage.SequenceNo),"sequence_no");Mapping.String(b,nameof(InteriorWorkStage.StageName),"stage_name",200);Mapping.Date(b,nameof(InteriorWorkStage.PlannedStartDate),"planned_start_date");Mapping.Date(b,nameof(InteriorWorkStage.PlannedEndDate),"planned_end_date");Mapping.DateTime(b,nameof(InteriorWorkStage.ActualStartAt),"actual_start_at",true);Mapping.DateTime(b,nameof(InteriorWorkStage.ActualEndAt),"actual_end_at",true);Mapping.Int(b,nameof(InteriorWorkStage.ProgressPercent),"progress_percent");Mapping.String(b,nameof(InteriorWorkStage.StatusCode),"status_code",30,unicode:false);Mapping.String(b,nameof(InteriorWorkStage.ProviderNote),"provider_note",2000,true);Mapping.FullAudit(b);Mapping.Fk<InteriorWorkStage,InteriorProject>(b,nameof(InteriorWorkStage.InteriorProjectId));b.HasIndex(x=>new{x.InteriorProjectId,x.SequenceNo}).IsUnique();b.ToTable("interior_work_stages",t=>{t.HasCheckConstraint("CK_interior_work_stages_progress","[progress_percent] BETWEEN 0 AND 100");t.HasCheckConstraint("CK_interior_work_stages_period","[planned_end_date] >= [planned_start_date]");});} }
internal sealed class InteriorWorkStageAssignmentConfiguration() : EntityConfiguration<InteriorWorkStageAssignment>("interior_work_stage_assignments")
{ protected override void ConfigureEntity(EntityTypeBuilder<InteriorWorkStageAssignment>b){Mapping.PublicId(b);Mapping.Long(b,nameof(InteriorWorkStageAssignment.WorkStageId),"work_stage_id");Mapping.Long(b,nameof(InteriorWorkStageAssignment.ProjectParticipantId),"project_participant_id");Mapping.String(b,nameof(InteriorWorkStageAssignment.StatusCode),"status_code",20,unicode:false);Mapping.DateTime(b,nameof(InteriorWorkStageAssignment.EffectiveFrom),"effective_from");Mapping.DateTime(b,nameof(InteriorWorkStageAssignment.EffectiveTo),"effective_to",true);Mapping.FullAudit(b);Mapping.Fk<InteriorWorkStageAssignment,InteriorWorkStage>(b,nameof(InteriorWorkStageAssignment.WorkStageId));Mapping.Fk<InteriorWorkStageAssignment,InteriorProjectParticipant>(b,nameof(InteriorWorkStageAssignment.ProjectParticipantId));b.HasIndex(x=>new{x.WorkStageId,x.ProjectParticipantId}).IsUnique();b.HasIndex(x=>new{x.ProjectParticipantId,x.StatusCode,x.EffectiveTo});b.ToTable("interior_work_stage_assignments",t=>{t.HasCheckConstraint("CK_interior_work_stage_assignments_status","[status_code] IN ('ACTIVE','ENDED','CANCELLED')");t.HasCheckConstraint("CK_interior_work_stage_assignments_period","[effective_to] IS NULL OR [effective_to] >= [effective_from]");});} }
internal sealed class InteriorWorkUpdateConfiguration() : EntityConfiguration<InteriorWorkUpdate>("interior_work_updates")
{ protected override void ConfigureEntity(EntityTypeBuilder<InteriorWorkUpdate>b){Mapping.PublicId(b);Mapping.Long(b,nameof(InteriorWorkUpdate.WorkStageId),"work_stage_id");Mapping.Int(b,nameof(InteriorWorkUpdate.ProgressPercent),"progress_percent");Mapping.String(b,nameof(InteriorWorkUpdate.UpdateText),"update_text",4000);Mapping.String(b,nameof(InteriorWorkUpdate.IssueText),"issue_text",4000,true);Mapping.CreatedAudit(b);Mapping.Fk<InteriorWorkUpdate,InteriorWorkStage>(b,nameof(InteriorWorkUpdate.WorkStageId));b.HasIndex(x=>new{x.WorkStageId,x.CreatedAt});b.ToTable("interior_work_updates",t=>t.HasCheckConstraint("CK_interior_work_updates_progress","[progress_percent] BETWEEN 0 AND 100"));} }
internal sealed class InteriorWorkUpdateFileConfiguration() : EntityConfiguration<InteriorWorkUpdateFile>("interior_work_update_files")
{ protected override void ConfigureEntity(EntityTypeBuilder<InteriorWorkUpdateFile>b){Mapping.Long(b,nameof(InteriorWorkUpdateFile.WorkUpdateId),"work_update_id");Mapping.Long(b,nameof(InteriorWorkUpdateFile.FileId),"file_id");Mapping.String(b,nameof(InteriorWorkUpdateFile.PurposeCode),"purpose_code",50,unicode:false);Mapping.Int(b,nameof(InteriorWorkUpdateFile.DisplayOrder),"display_order");Mapping.CreatedAudit(b);Mapping.Fk<InteriorWorkUpdateFile,InteriorWorkUpdate>(b,nameof(InteriorWorkUpdateFile.WorkUpdateId));Mapping.Fk<InteriorWorkUpdateFile,StoredFile>(b,nameof(InteriorWorkUpdateFile.FileId));b.HasIndex(x=>new{x.WorkUpdateId,x.FileId}).IsUnique();} }
internal sealed class InteriorStageInspectionConfiguration() : EntityConfiguration<InteriorStageInspection>("interior_stage_inspections")
{ protected override void ConfigureEntity(EntityTypeBuilder<InteriorStageInspection>b){Mapping.PublicId(b);Mapping.Long(b,nameof(InteriorStageInspection.WorkStageId),"work_stage_id");Mapping.String(b,nameof(InteriorStageInspection.InspectionStatusCode),"inspection_status_code",30,unicode:false);Mapping.Long(b,nameof(InteriorStageInspection.InspectedByUserId),"inspected_by_user_id");Mapping.String(b,nameof(InteriorStageInspection.ChecklistJson),"checklist_json",null,true);Mapping.String(b,nameof(InteriorStageInspection.ResultText),"result_text",4000);Mapping.String(b,nameof(InteriorStageInspection.RequestedCorrectionText),"requested_correction_text",4000,true);Mapping.DateTime(b,nameof(InteriorStageInspection.InspectedAt),"inspected_at");Mapping.DateTime(b,nameof(InteriorStageInspection.CreatedAt),"created_at",utcDefault:true);Mapping.RowVersion(b);Mapping.Fk<InteriorStageInspection,InteriorWorkStage>(b,nameof(InteriorStageInspection.WorkStageId));Mapping.Fk<InteriorStageInspection,User>(b,nameof(InteriorStageInspection.InspectedByUserId));b.HasIndex(x=>new{x.WorkStageId,x.InspectedAt});} }
internal sealed class InteriorStageInspectionFileConfiguration() : EntityConfiguration<InteriorStageInspectionFile>("interior_stage_inspection_files")
{ protected override void ConfigureEntity(EntityTypeBuilder<InteriorStageInspectionFile>b){Mapping.Long(b,nameof(InteriorStageInspectionFile.StageInspectionId),"stage_inspection_id");Mapping.Long(b,nameof(InteriorStageInspectionFile.FileId),"file_id");Mapping.String(b,nameof(InteriorStageInspectionFile.PurposeCode),"purpose_code",50,unicode:false);Mapping.Int(b,nameof(InteriorStageInspectionFile.DisplayOrder),"display_order");Mapping.CreatedAudit(b);Mapping.Fk<InteriorStageInspectionFile,InteriorStageInspection>(b,nameof(InteriorStageInspectionFile.StageInspectionId));Mapping.Fk<InteriorStageInspectionFile,StoredFile>(b,nameof(InteriorStageInspectionFile.FileId));b.HasIndex(x=>new{x.StageInspectionId,x.FileId}).IsUnique();} }
internal sealed class InteriorStageInspectionAcknowledgementConfiguration() : EntityConfiguration<InteriorStageInspectionAcknowledgement>("interior_stage_inspection_acknowledgements")
{ protected override void ConfigureEntity(EntityTypeBuilder<InteriorStageInspectionAcknowledgement>b){Mapping.PublicId(b);Mapping.Long(b,nameof(InteriorStageInspectionAcknowledgement.StageInspectionId),"stage_inspection_id");Mapping.Long(b,nameof(InteriorStageInspectionAcknowledgement.CustomerProfileId),"customer_profile_id");Mapping.DateTime(b,nameof(InteriorStageInspectionAcknowledgement.AcknowledgedAt),"acknowledged_at");Mapping.String(b,nameof(InteriorStageInspectionAcknowledgement.Comment),"comment",2000,true);Mapping.String(b,nameof(InteriorStageInspectionAcknowledgement.IdempotencyKey),"idempotency_key",150,unicode:false);Mapping.DateTime(b,nameof(InteriorStageInspectionAcknowledgement.CreatedAt),"created_at",utcDefault:true);Mapping.NullableLong(b,nameof(InteriorStageInspectionAcknowledgement.CreatedByUserId),"created_by_user_id");Mapping.RowVersion(b);Mapping.Fk<InteriorStageInspectionAcknowledgement,InteriorStageInspection>(b,nameof(InteriorStageInspectionAcknowledgement.StageInspectionId));Mapping.Fk<InteriorStageInspectionAcknowledgement,CustomerProfile>(b,nameof(InteriorStageInspectionAcknowledgement.CustomerProfileId));Mapping.Fk<InteriorStageInspectionAcknowledgement,User>(b,nameof(InteriorStageInspectionAcknowledgement.CreatedByUserId));b.HasIndex(x=>new{x.StageInspectionId,x.CustomerProfileId}).IsUnique();b.HasIndex(x=>x.IdempotencyKey).IsUnique();} }
internal sealed class InteriorContractChangeConfiguration() : EntityConfiguration<InteriorContractChange>("interior_contract_changes")
{ protected override void ConfigureEntity(EntityTypeBuilder<InteriorContractChange>b){Mapping.PublicId(b);Mapping.Long(b,nameof(InteriorContractChange.InteriorContractId),"interior_contract_id");Mapping.Int(b,nameof(InteriorContractChange.ChangeNo),"change_no");Mapping.Long(b,nameof(InteriorContractChange.RequestedByUserId),"requested_by_user_id");Mapping.String(b,nameof(InteriorContractChange.ChangeTypeCode),"change_type_code",30,true,unicode:false);Mapping.String(b,nameof(InteriorContractChange.ReasonText),"reason_text",2000);Mapping.String(b,nameof(InteriorContractChange.ScopeChangeText),"scope_change_text",4000);Mapping.Decimal(b,nameof(InteriorContractChange.AmountDelta),"amount_delta");b.Property(x=>x.ScheduleImpactDays).HasColumnName("schedule_impact_days").HasColumnType("int");Mapping.String(b,nameof(InteriorContractChange.StatusCode),"status_code",30,unicode:false);Mapping.DateTime(b,nameof(InteriorContractChange.RequestedAt),"requested_at");Mapping.DateTime(b,nameof(InteriorContractChange.CustomerDecidedAt),"customer_decided_at",true);Mapping.FullAudit(b);Mapping.Fk<InteriorContractChange,InteriorContract>(b,nameof(InteriorContractChange.InteriorContractId));Mapping.Fk<InteriorContractChange,User>(b,nameof(InteriorContractChange.RequestedByUserId));b.HasIndex(x=>new{x.InteriorContractId,x.ChangeNo}).IsUnique();b.ToTable("interior_contract_changes",t=>t.HasCheckConstraint("CK_interior_contract_changes_status","[status_code] IN ('REQUESTED','APPROVED','REJECTED','CANCELLED')"));} }
internal sealed class InteriorContractChangeFileConfiguration() : EntityConfiguration<InteriorContractChangeFile>("interior_contract_change_files")
{ protected override void ConfigureEntity(EntityTypeBuilder<InteriorContractChangeFile>b){Mapping.Long(b,nameof(InteriorContractChangeFile.ContractChangeId),"contract_change_id");Mapping.Long(b,nameof(InteriorContractChangeFile.FileId),"file_id");Mapping.String(b,nameof(InteriorContractChangeFile.PurposeCode),"purpose_code",50,unicode:false);Mapping.Int(b,nameof(InteriorContractChangeFile.DisplayOrder),"display_order");Mapping.CreatedAudit(b);Mapping.Fk<InteriorContractChangeFile,InteriorContractChange>(b,nameof(InteriorContractChangeFile.ContractChangeId));Mapping.Fk<InteriorContractChangeFile,StoredFile>(b,nameof(InteriorContractChangeFile.FileId));b.HasIndex(x=>new{x.ContractChangeId,x.FileId}).IsUnique();} }
internal sealed class InteriorDefectConfiguration() : EntityConfiguration<InteriorDefect>("interior_defects")
{ protected override void ConfigureEntity(EntityTypeBuilder<InteriorDefect>b){Mapping.PublicId(b);Mapping.Long(b,nameof(InteriorDefect.InteriorProjectId),"interior_project_id");Mapping.Long(b,nameof(InteriorDefect.AfterServiceCaseId),"after_service_case_id");Mapping.NullableLong(b,nameof(InteriorDefect.WorkStageId),"work_stage_id");b.Property(x=>x.ContractVersion).HasColumnName("contract_version").HasColumnType("int");Mapping.String(b,nameof(InteriorDefect.DefectLocationText),"defect_location_text",1000);Mapping.String(b,nameof(InteriorDefect.DefectDescription),"defect_description",4000);Mapping.CreatedAudit(b);Mapping.Fk<InteriorDefect,InteriorProject>(b,nameof(InteriorDefect.InteriorProjectId));Mapping.Fk<InteriorDefect,AfterServiceCase>(b,nameof(InteriorDefect.AfterServiceCaseId));Mapping.Fk<InteriorDefect,InteriorWorkStage>(b,nameof(InteriorDefect.WorkStageId));b.HasIndex(x=>x.AfterServiceCaseId).IsUnique();} }
internal sealed class InteriorProjectEventConfiguration() : EntityConfiguration<InteriorProjectEvent>("interior_project_events")
{ protected override void ConfigureEntity(EntityTypeBuilder<InteriorProjectEvent>b){Mapping.PublicId(b);Mapping.Long(b,nameof(InteriorProjectEvent.InteriorProjectId),"interior_project_id");Mapping.String(b,nameof(InteriorProjectEvent.EventTypeCode),"event_type_code",50,unicode:false);Mapping.NullableLong(b,nameof(InteriorProjectEvent.ActorUserId),"actor_user_id");Mapping.String(b,nameof(InteriorProjectEvent.IdempotencyKey),"idempotency_key",150,unicode:false);Mapping.String(b,nameof(InteriorProjectEvent.EventDataJson),"event_data_json",null,true);Mapping.DateTime(b,nameof(InteriorProjectEvent.OccurredAt),"occurred_at");Mapping.DateTime(b,nameof(InteriorProjectEvent.CreatedAt),"created_at",utcDefault:true);Mapping.Fk<InteriorProjectEvent,InteriorProject>(b,nameof(InteriorProjectEvent.InteriorProjectId));Mapping.Fk<InteriorProjectEvent,User>(b,nameof(InteriorProjectEvent.ActorUserId));b.HasIndex(x=>x.IdempotencyKey).IsUnique();b.HasIndex(x=>new{x.InteriorProjectId,x.OccurredAt});} }
