using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using SoodalLife.Api.Domain.Entities;

namespace SoodalLife.Api.Infrastructure.Persistence.Configurations;

internal sealed class NotificationTemplateConfiguration() : EntityConfiguration<NotificationTemplate>("notification_templates")
{
    protected override void ConfigureEntity(EntityTypeBuilder<NotificationTemplate> b)
    {
        Mapping.PublicId(b); Mapping.String(b,nameof(NotificationTemplate.TemplateCode),"template_code",100,unicode:false); Mapping.String(b,nameof(NotificationTemplate.Name),"name",200); Mapping.String(b,nameof(NotificationTemplate.Description),"description",2000,nullable:true); Mapping.String(b,nameof(NotificationTemplate.AudienceTypeCode),"audience_type_code",30,unicode:false); Mapping.String(b,nameof(NotificationTemplate.EventTypeCode),"event_type_code",100,unicode:false); Mapping.String(b,nameof(NotificationTemplate.ChannelCode),"channel_code",20,unicode:false); Mapping.String(b,nameof(NotificationTemplate.TitleTemplate),"title_template",300); Mapping.String(b,nameof(NotificationTemplate.BodyTemplate),"body_template",3000); Mapping.String(b,nameof(NotificationTemplate.AllowedVariablesJson),"allowed_variables_json",null); Mapping.Bool(b,nameof(NotificationTemplate.IsRequiredBusinessNotice),"is_required_business_notice",false); Mapping.Bool(b,nameof(NotificationTemplate.IsMarketing),"is_marketing",false); Mapping.Bool(b,nameof(NotificationTemplate.IsActive),"is_active",true); Mapping.DateTime(b,nameof(NotificationTemplate.EffectiveFrom),"effective_from",true); Mapping.DateTime(b,nameof(NotificationTemplate.EffectiveTo),"effective_to",true); Mapping.FullAudit(b); b.HasIndex(x=>new{x.TemplateCode,x.ChannelCode}).IsUnique(); b.HasIndex(x=>new{x.EventTypeCode,x.IsActive}); b.ToTable("notification_templates",t=>{t.HasCheckConstraint("CK_notification_templates_channel","[channel_code] IN ('WEB','KAKAO','SMS','EMAIL','PUSH')");t.HasCheckConstraint("CK_notification_templates_audience","[audience_type_code] IN ('CUSTOMER','PROVIDER','ADMIN','ALL')");t.HasCheckConstraint("CK_notification_templates_variables_json","ISJSON([allowed_variables_json]) = 1");t.HasCheckConstraint("CK_notification_templates_period","[effective_to] IS NULL OR [effective_from] IS NULL OR [effective_to] > [effective_from]");});
    }
}

internal sealed class NotificationRecipientConfiguration() : EntityConfiguration<NotificationRecipient>("notification_recipients")
{
    protected override void ConfigureEntity(EntityTypeBuilder<NotificationRecipient>b){Mapping.PublicId(b);Mapping.Long(b,nameof(NotificationRecipient.NotificationId),"notification_id");Mapping.Long(b,nameof(NotificationRecipient.UserId),"user_id");Mapping.String(b,nameof(NotificationRecipient.RecipientRoleCode),"recipient_role_code",30,unicode:false);Mapping.DateTime(b,nameof(NotificationRecipient.ReadAt),"read_at",true);Mapping.DateTime(b,nameof(NotificationRecipient.ArchivedAt),"archived_at",true);Mapping.DateTime(b,nameof(NotificationRecipient.CreatedAt),"created_at",utcDefault:true);Mapping.RowVersion(b);Mapping.Fk<NotificationRecipient,Notification>(b,nameof(NotificationRecipient.NotificationId));Mapping.Fk<NotificationRecipient,User>(b,nameof(NotificationRecipient.UserId));b.HasIndex(x=>new{x.NotificationId,x.UserId}).IsUnique();b.HasIndex(x=>new{x.UserId,x.ArchivedAt,x.ReadAt,x.CreatedAt}).IsDescending(false,false,false,true);}
}

internal sealed class NotificationDeliveryAttemptConfiguration() : EntityConfiguration<NotificationDeliveryAttempt>("notification_delivery_attempts")
{
    protected override void ConfigureEntity(EntityTypeBuilder<NotificationDeliveryAttempt>b){Mapping.PublicId(b);Mapping.Long(b,nameof(NotificationDeliveryAttempt.NotificationDeliveryId),"notification_delivery_id");Mapping.Int(b,nameof(NotificationDeliveryAttempt.AttemptNo),"attempt_no");Mapping.DateTime(b,nameof(NotificationDeliveryAttempt.StartedAt),"started_at");Mapping.DateTime(b,nameof(NotificationDeliveryAttempt.CompletedAt),"completed_at",true);Mapping.String(b,nameof(NotificationDeliveryAttempt.ResultCode),"result_code",30,unicode:false);Mapping.String(b,nameof(NotificationDeliveryAttempt.ProviderResponseCode),"provider_response_code",100,unicode:false,nullable:true);Mapping.String(b,nameof(NotificationDeliveryAttempt.FailureReason),"failure_reason",1000,nullable:true);Mapping.Guid(b,nameof(NotificationDeliveryAttempt.CorrelationId),"correlation_id",true);Mapping.DateTime(b,nameof(NotificationDeliveryAttempt.CreatedAt),"created_at",utcDefault:true);Mapping.Fk<NotificationDeliveryAttempt,NotificationDelivery>(b,nameof(NotificationDeliveryAttempt.NotificationDeliveryId));b.HasIndex(x=>new{x.NotificationDeliveryId,x.AttemptNo}).IsUnique();}
}

internal sealed class NotificationPreferenceConfiguration() : EntityConfiguration<NotificationPreference>("notification_preferences")
{
    protected override void ConfigureEntity(EntityTypeBuilder<NotificationPreference>b){Mapping.PublicId(b);Mapping.Long(b,nameof(NotificationPreference.UserId),"user_id");Mapping.String(b,nameof(NotificationPreference.EventGroupCode),"event_group_code",50,unicode:false);Mapping.Bool(b,nameof(NotificationPreference.WebEnabled),"web_enabled",true);Mapping.Bool(b,nameof(NotificationPreference.KakaoEnabled),"kakao_enabled",true);Mapping.Bool(b,nameof(NotificationPreference.SmsEnabled),"sms_enabled",false);Mapping.Bool(b,nameof(NotificationPreference.EmailEnabled),"email_enabled",false);Mapping.Bool(b,nameof(NotificationPreference.PushEnabled),"push_enabled",false);Mapping.DateTime(b,nameof(NotificationPreference.CreatedAt),"created_at",utcDefault:true);Mapping.DateTime(b,nameof(NotificationPreference.UpdatedAt),"updated_at",utcDefault:true);Mapping.RowVersion(b);Mapping.Fk<NotificationPreference,User>(b,nameof(NotificationPreference.UserId));b.HasIndex(x=>new{x.UserId,x.EventGroupCode}).IsUnique();}
}

internal sealed class NotificationEventConfiguration() : EntityConfiguration<NotificationEvent>("notification_events")
{
    protected override void ConfigureEntity(EntityTypeBuilder<NotificationEvent>b){Mapping.PublicId(b);Mapping.Long(b,nameof(NotificationEvent.NotificationId),"notification_id");Mapping.NullableLong(b,nameof(NotificationEvent.NotificationRecipientId),"notification_recipient_id");Mapping.NullableLong(b,nameof(NotificationEvent.NotificationDeliveryId),"notification_delivery_id");Mapping.NullableLong(b,nameof(NotificationEvent.ActorUserId),"actor_user_id");Mapping.String(b,nameof(NotificationEvent.EventTypeCode),"event_type_code",50,unicode:false);Mapping.String(b,nameof(NotificationEvent.IdempotencyKey),"idempotency_key",180,unicode:false);Mapping.String(b,nameof(NotificationEvent.EventDataJson),"event_data_json",null,true);Mapping.DateTime(b,nameof(NotificationEvent.OccurredAt),"occurred_at");Mapping.DateTime(b,nameof(NotificationEvent.CreatedAt),"created_at",utcDefault:true);Mapping.Fk<NotificationEvent,Notification>(b,nameof(NotificationEvent.NotificationId));Mapping.Fk<NotificationEvent,NotificationRecipient>(b,nameof(NotificationEvent.NotificationRecipientId));Mapping.Fk<NotificationEvent,NotificationDelivery>(b,nameof(NotificationEvent.NotificationDeliveryId));Mapping.Fk<NotificationEvent,User>(b,nameof(NotificationEvent.ActorUserId));b.HasIndex(x=>x.IdempotencyKey).IsUnique();b.HasIndex(x=>new{x.NotificationId,x.OccurredAt});b.ToTable("notification_events",t=>t.HasCheckConstraint("CK_notification_events_data_json","[event_data_json] IS NULL OR ISJSON([event_data_json]) = 1"));}
}
