using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using SoodalLife.Api.Domain.Entities;

namespace SoodalLife.Api.Infrastructure.Persistence.Configurations;

internal sealed class ProviderProposalCampaignConfiguration() : EntityConfiguration<ProviderProposalCampaign>("provider_proposal_campaigns")
{
    protected override void ConfigureEntity(EntityTypeBuilder<ProviderProposalCampaign> b)
    {
        Mapping.PublicId(b); Mapping.Long(b,nameof(ProviderProposalCampaign.ProviderProfileId),"provider_profile_id"); Mapping.Long(b,nameof(ProviderProposalCampaign.ProviderServiceCategoryId),"provider_service_category_id"); Mapping.Long(b,nameof(ProviderProposalCampaign.WalletId),"wallet_id");
        Mapping.String(b,nameof(ProviderProposalCampaign.ProposalTypeCode),"proposal_type_code",30,unicode:false); Mapping.String(b,nameof(ProviderProposalCampaign.ScopeCode),"scope_code",20,unicode:false); Mapping.String(b,nameof(ProviderProposalCampaign.Title),"title",200); Mapping.String(b,nameof(ProviderProposalCampaign.Summary),"summary",3000);
        Mapping.Decimal(b,nameof(ProviderProposalCampaign.NormalPriceAmount),"normal_price_amount",true); Mapping.Decimal(b,nameof(ProviderProposalCampaign.OfferPriceAmount),"offer_price_amount"); Mapping.Int(b,nameof(ProviderProposalCampaign.MinimumParticipants),"minimum_participants"); Mapping.Int(b,nameof(ProviderProposalCampaign.MaximumParticipants),"maximum_participants"); Mapping.Int(b,nameof(ProviderProposalCampaign.ConfirmedParticipants),"confirmed_participants",0);
        Mapping.DateTime(b,nameof(ProviderProposalCampaign.StartAt),"start_at"); Mapping.DateTime(b,nameof(ProviderProposalCampaign.EndAt),"end_at"); Mapping.DateTime(b,nameof(ProviderProposalCampaign.ServiceAt),"service_at",true); Mapping.String(b,nameof(ProviderProposalCampaign.MinimumFailurePolicyCode),"minimum_failure_policy_code",30,unicode:false); Mapping.String(b,nameof(ProviderProposalCampaign.CancellationPolicyText),"cancellation_policy_text",2000);
        Mapping.String(b,nameof(ProviderProposalCampaign.StatusCode),"status_code",30,unicode:false); Mapping.Decimal(b,nameof(ProviderProposalCampaign.FeePerParticipant),"fee_per_participant"); Mapping.Decimal(b,nameof(ProviderProposalCampaign.ReservedFeeAmount),"reserved_fee_amount"); Mapping.Decimal(b,nameof(ProviderProposalCampaign.CapturedFeeAmount),"captured_fee_amount"); Mapping.String(b,nameof(ProviderProposalCampaign.FeeStatusCode),"fee_status_code",30,unicode:false); Mapping.Long(b,nameof(ProviderProposalCampaign.ReserveLedgerEntryId),"reserve_ledger_entry_id"); Mapping.NullableLong(b,nameof(ProviderProposalCampaign.ReleaseLedgerEntryId),"release_ledger_entry_id");
        Mapping.DateTime(b,nameof(ProviderProposalCampaign.PublishedNotificationQueuedAt),"published_notification_queued_at",true); Mapping.DateTime(b,nameof(ProviderProposalCampaign.MidpointNotificationQueuedAt),"midpoint_notification_queued_at",true); Mapping.DateTime(b,nameof(ProviderProposalCampaign.ClosingNotificationQueuedAt),"closing_notification_queued_at",true); Mapping.DateTime(b,nameof(ProviderProposalCampaign.ClosedAt),"closed_at",true); Mapping.DateTime(b,nameof(ProviderProposalCampaign.CancelledAt),"cancelled_at",true); Mapping.FullAudit(b);
        Mapping.Fk<ProviderProposalCampaign,ProviderProfile>(b,nameof(ProviderProposalCampaign.ProviderProfileId)); Mapping.Fk<ProviderProposalCampaign,ProviderServiceCategory>(b,nameof(ProviderProposalCampaign.ProviderServiceCategoryId)); Mapping.Fk<ProviderProposalCampaign,ProviderWallet>(b,nameof(ProviderProposalCampaign.WalletId)); Mapping.Fk<ProviderProposalCampaign,WalletLedgerEntry>(b,nameof(ProviderProposalCampaign.ReserveLedgerEntryId)); Mapping.Fk<ProviderProposalCampaign,WalletLedgerEntry>(b,nameof(ProviderProposalCampaign.ReleaseLedgerEntryId));
        b.HasIndex(x=>new{x.StatusCode,x.StartAt,x.EndAt}); b.HasIndex(x=>new{x.ProviderProfileId,x.StatusCode}); b.HasIndex(x=>new{x.ProviderServiceCategoryId,x.StatusCode});
        b.ToTable("provider_proposal_campaigns",t=>{t.HasCheckConstraint("CK_provider_proposal_type","[proposal_type_code] IN ('DISCOUNT_SERVICE','GROUP_BUY','GROUP_LESSON')");t.HasCheckConstraint("CK_provider_proposal_scope","[scope_code] IN ('LOCAL','NATIONWIDE')");t.HasCheckConstraint("CK_provider_proposal_status","[status_code] IN ('PUBLISHED','MINIMUM_MET','FULL','EXPIRED','CANCELLED')");t.HasCheckConstraint("CK_provider_proposal_fee_status","[fee_status_code] IN ('RESERVED','PARTIALLY_CAPTURED','CAPTURED','RELEASED','RESTORED')");t.HasCheckConstraint("CK_provider_proposal_period","[end_at] > [start_at]");t.HasCheckConstraint("CK_provider_proposal_participants","[minimum_participants] > 0 AND [maximum_participants] >= [minimum_participants] AND [confirmed_participants] >= 0 AND [confirmed_participants] <= [maximum_participants]");t.HasCheckConstraint("CK_provider_proposal_amounts","[offer_price_amount] >= 0 AND ([normal_price_amount] IS NULL OR [normal_price_amount] >= [offer_price_amount]) AND [fee_per_participant] > 0 AND [reserved_fee_amount] >= 0 AND [captured_fee_amount] >= 0");});
    }
}

internal sealed class ProviderProposalAreaConfiguration() : EntityConfiguration<ProviderProposalArea>("provider_proposal_areas")
{ protected override void ConfigureEntity(EntityTypeBuilder<ProviderProposalArea>b){Mapping.Long(b,nameof(ProviderProposalArea.CampaignId),"campaign_id");Mapping.Long(b,nameof(ProviderProposalArea.AdministrativeAreaId),"administrative_area_id");Mapping.CreatedAudit(b);Mapping.Fk<ProviderProposalArea,ProviderProposalCampaign>(b,nameof(ProviderProposalArea.CampaignId));Mapping.Fk<ProviderProposalArea,AdministrativeArea>(b,nameof(ProviderProposalArea.AdministrativeAreaId));b.HasIndex(x=>new{x.CampaignId,x.AdministrativeAreaId}).IsUnique();b.HasIndex(x=>x.AdministrativeAreaId);} }

internal sealed class ProviderProposalApplicationConfiguration() : EntityConfiguration<ProviderProposalApplication>("provider_proposal_applications")
{ protected override void ConfigureEntity(EntityTypeBuilder<ProviderProposalApplication>b){Mapping.PublicId(b);Mapping.Long(b,nameof(ProviderProposalApplication.CampaignId),"campaign_id");Mapping.Long(b,nameof(ProviderProposalApplication.CustomerProfileId),"customer_profile_id");Mapping.String(b,nameof(ProviderProposalApplication.StatusCode),"status_code",20,unicode:false);Mapping.Decimal(b,nameof(ProviderProposalApplication.CapturedFeeAmount),"captured_fee_amount");Mapping.NullableLong(b,nameof(ProviderProposalApplication.CaptureLedgerEntryId),"capture_ledger_entry_id");Mapping.DateTime(b,nameof(ProviderProposalApplication.AppliedAt),"applied_at");Mapping.DateTime(b,nameof(ProviderProposalApplication.ConfirmedAt),"confirmed_at",true);Mapping.DateTime(b,nameof(ProviderProposalApplication.CancelledAt),"cancelled_at",true);Mapping.DateTime(b,nameof(ProviderProposalApplication.DeclinedAt),"declined_at",true);Mapping.FullAudit(b);Mapping.Fk<ProviderProposalApplication,ProviderProposalCampaign>(b,nameof(ProviderProposalApplication.CampaignId));Mapping.Fk<ProviderProposalApplication,CustomerProfile>(b,nameof(ProviderProposalApplication.CustomerProfileId));Mapping.Fk<ProviderProposalApplication,WalletLedgerEntry>(b,nameof(ProviderProposalApplication.CaptureLedgerEntryId));b.HasIndex(x=>new{x.CampaignId,x.CustomerProfileId}).IsUnique();b.HasIndex(x=>new{x.CampaignId,x.StatusCode});b.ToTable("provider_proposal_applications",t=>t.HasCheckConstraint("CK_provider_proposal_application_status","[status_code] IN ('APPLIED','CONFIRMED','CANCELLED','DECLINED')"));} }

internal sealed class CustomerProposalCategoryInterestConfiguration() : EntityConfiguration<CustomerProposalCategoryInterest>("customer_proposal_category_interests")
{ protected override void ConfigureEntity(EntityTypeBuilder<CustomerProposalCategoryInterest>b){Mapping.Long(b,nameof(CustomerProposalCategoryInterest.CustomerProfileId),"customer_profile_id");Mapping.Long(b,nameof(CustomerProposalCategoryInterest.CategoryId),"category_id");Mapping.String(b,nameof(CustomerProposalCategoryInterest.SourceCode),"source_code",30,unicode:false);Mapping.Bool(b,nameof(CustomerProposalCategoryInterest.IsActive),"is_active",true);Mapping.DateTime(b,nameof(CustomerProposalCategoryInterest.CreatedAt),"created_at",utcDefault:true);Mapping.DateTime(b,nameof(CustomerProposalCategoryInterest.UpdatedAt),"updated_at",utcDefault:true);Mapping.Fk<CustomerProposalCategoryInterest,CustomerProfile>(b,nameof(CustomerProposalCategoryInterest.CustomerProfileId));Mapping.Fk<CustomerProposalCategoryInterest,ServiceCategory>(b,nameof(CustomerProposalCategoryInterest.CategoryId));b.HasIndex(x=>new{x.CustomerProfileId,x.CategoryId}).IsUnique();b.HasIndex(x=>new{x.CategoryId,x.IsActive});} }

internal sealed class CustomerProposalAreaInterestConfiguration() : EntityConfiguration<CustomerProposalAreaInterest>("customer_proposal_area_interests")
{ protected override void ConfigureEntity(EntityTypeBuilder<CustomerProposalAreaInterest>b){Mapping.Long(b,nameof(CustomerProposalAreaInterest.CustomerProfileId),"customer_profile_id");Mapping.Long(b,nameof(CustomerProposalAreaInterest.AdministrativeAreaId),"administrative_area_id");Mapping.String(b,nameof(CustomerProposalAreaInterest.SourceCode),"source_code",30,unicode:false);Mapping.Bool(b,nameof(CustomerProposalAreaInterest.IsActive),"is_active",true);Mapping.DateTime(b,nameof(CustomerProposalAreaInterest.CreatedAt),"created_at",utcDefault:true);Mapping.DateTime(b,nameof(CustomerProposalAreaInterest.UpdatedAt),"updated_at",utcDefault:true);Mapping.Fk<CustomerProposalAreaInterest,CustomerProfile>(b,nameof(CustomerProposalAreaInterest.CustomerProfileId));Mapping.Fk<CustomerProposalAreaInterest,AdministrativeArea>(b,nameof(CustomerProposalAreaInterest.AdministrativeAreaId));b.HasIndex(x=>new{x.CustomerProfileId,x.AdministrativeAreaId}).IsUnique();b.HasIndex(x=>new{x.AdministrativeAreaId,x.IsActive});} }

internal sealed class CustomerProposalSignalConfiguration() : EntityConfiguration<CustomerProposalSignal>("customer_proposal_signals")
{ protected override void ConfigureEntity(EntityTypeBuilder<CustomerProposalSignal>b){Mapping.Long(b,nameof(CustomerProposalSignal.CustomerProfileId),"customer_profile_id");Mapping.Long(b,nameof(CustomerProposalSignal.CategoryId),"category_id");Mapping.String(b,nameof(CustomerProposalSignal.SignalTypeCode),"signal_type_code",30,unicode:false);Mapping.DateTime(b,nameof(CustomerProposalSignal.OccurredAt),"occurred_at");Mapping.DateTime(b,nameof(CustomerProposalSignal.ExpiresAt),"expires_at");Mapping.Fk<CustomerProposalSignal,CustomerProfile>(b,nameof(CustomerProposalSignal.CustomerProfileId));Mapping.Fk<CustomerProposalSignal,ServiceCategory>(b,nameof(CustomerProposalSignal.CategoryId));b.HasIndex(x=>new{x.CustomerProfileId,x.CategoryId,x.ExpiresAt});b.ToTable("customer_proposal_signals",t=>t.HasCheckConstraint("CK_customer_proposal_signal_type","[signal_type_code] IN ('SERVICE_DETAIL','SERVICE_SEARCH','SESSION_CATEGORY')"));} }
