import {useEffect,useMemo,useState} from 'react'
import {navigate} from '../auth/routing'
import {CustomerAppLayout} from '../customer/CustomerAppLayout'
import {ProviderAppLayout} from '../providers/ProviderAppLayout'
import * as api from './api'
import type {EmergencyAvailability,EmergencyCustomerResponse,EmergencyProgress,EmergencyProviderRequest} from './types'
import './emergency.css'

const days=['일','월','화','수','목','금','토']
export function CustomerEmergencyHomePage(){return <CustomerAppLayout><div className="emergencyPage"><header className="emergencyHero"><p>SOODAL EMERGENCY</p><h1>긴급출동</h1><span>위험한 가스·화재·감전 상황은 119 등 공공 긴급대응을 먼저 이용해 주세요.</span></header><section className="emergencySafety"><strong>안전이 가장 먼저입니다</strong><p>플랫폼 공급자 탐색이 공공 긴급대응을 지연시키면 안 됩니다. 즉시 위험이 있으면 안전한 장소로 이동하세요.</p></section><section className="emergencyCard"><h2>긴급 공급자 찾기</h2><ol><li>긴급 서비스와 현장 정보를 입력합니다.</li><li>현재 출동 가능한 공급자가 ETA를 보냅니다.</li><li>고객이 1곳을 선택하면 연락처·상세주소와 채팅이 열립니다.</li></ol><button className="emergencyPrimary" onClick={()=>navigate('/customer/requests/new?emergency=1')}>긴급요청 작성</button><p className="emergencyPolicy">출동비·긴급 할증·수수료는 정책 확정 전이며 임의 금액을 표시하거나 차감하지 않습니다.</p></section></div></CustomerAppLayout>}

export function EmergencyResponsesPanel({requestId}:{requestId:string}){const[items,setItems]=useState<EmergencyCustomerResponse[]>([]),[error,setError]=useState(''),[busy,setBusy]=useState('');useEffect(()=>{api.customerResponses(requestId).then(setItems).catch((e:Error)=>setError(e.message))},[requestId]);const choose=async(item:EmergencyCustomerResponse)=>{if(!confirm(`${item.providerName} 공급자를 선택할까요?`))return;setBusy(item.id);try{const result=await api.selectProvider(requestId,{responseId:item.id,idempotencyKey:crypto.randomUUID(),rowVersion:item.rowVersion});navigate(`/customer/emergency/${result.transactionId}`)}catch(e){setError(e instanceof Error?e.message:'선택하지 못했습니다.')}finally{setBusy('')}};return <section className="emergencyCard"><h2>출동 가능 공급자</h2>{error&&<p className="errorBanner">{error}</p>}{items.length===0?<p>현재 출동 가능한 공급자를 찾고 있습니다.</p>:<div className="emergencyResponseGrid">{items.map(item=><article key={item.id}><div><span className="emergencyStatus">AVAILABLE</span><h3>{item.providerName}</h3><p>수달신뢰점수 {item.trustScore??'평가중'} · 리뷰 {item.publicReviewCount}건</p></div><strong>{item.etaMinutes?`약 ${item.etaMinutes}분`:item.estimatedArrivalAt?new Date(item.estimatedArrivalAt).toLocaleTimeString('ko-KR',{hour:'2-digit',minute:'2-digit'}):'ETA 확인'}</strong><p>{item.conditions||'별도 출동조건 없음'}</p><p className="privacyNote">선택 전에는 공급자에게 전화번호·상세주소·이메일이 공개되지 않습니다.</p><button disabled={busy===item.id} onClick={()=>void choose(item)}>{busy===item.id?'선택 중':'이 공급자 선택'}</button></article>)}</div>}<p className="emergencyPolicy">가격 정책 미확정: 0원이나 임의 출동비를 표시하지 않습니다.</p></section>}

export function CustomerEmergencyProgressPage({id}:{id:string}){const[value,setValue]=useState<EmergencyProgress|null>(null),[error,setError]=useState('');useEffect(()=>{api.progress(id).then(setValue).catch((e:Error)=>setError(e.message))},[id]);return <CustomerAppLayout><div className="emergencyPage"><header className="emergencyHero"><p>LIVE STATUS</p><h1>긴급출동 진행</h1><span>출동 상태는 공급자가 직접 갱신하며 실시간 GPS 위치는 수집하지 않습니다.</span></header>{error&&<div className="errorBanner">{error}</div>}{value&&<><section className="emergencyCard"><h2>현재 상태</h2><strong className="emergencyCurrent">{label(value.currentEmergencyStatus)}</strong><div className="emergencyTimeline">{value.events.map(e=><div key={e.id}><span>{new Date(e.occurredAt).toLocaleString('ko-KR')}</span><strong>{label(e.eventType)}</strong>{e.note&&<p>{e.note}</p>}</div>)}</div></section><div className="emergencySticky"><button onClick={()=>navigate(`/customer/messages`)}>채팅</button><button onClick={()=>navigate(`/customer/transactions/${id}`)}>작업·완료 확인</button></div></>}</div></CustomerAppLayout>}

export function ProviderEmergencyPage(){const[setting,setSetting]=useState<EmergencyAvailability|null>(null),[requests,setRequests]=useState<EmergencyProviderRequest[]>([]),[error,setError]=useState(''),[saving,setSaving]=useState(false);const today=useMemo(()=>setting?.services.flatMap(s=>s.slots).filter(s=>s.dayOfWeek===new Date().getDay())??[],[setting]);const load=()=>Promise.all([api.availability(),api.providerRequests()]).then(([a,r])=>{setSetting(a);setRequests(r)}).catch((e:Error)=>setError(e.message));useEffect(()=>{void load()},[]);const toggle=async()=>{if(!setting)return;setSaving(true);try{setSetting(await api.saveAvailability({isEnabled:!setting.isEnabled,temporarilyUnavailableUntil:setting.temporarilyUnavailableUntil,temporaryUnavailableReason:setting.temporaryUnavailableReason,services:setting.services.map(s=>({providerServiceCategoryId:s.providerServiceCategoryId,isEnabled:s.isEnabled,slots:s.slots.map(x=>({dayOfWeek:x.dayOfWeek,startTime:x.startTime,endTime:x.endTime,is24Hours:x.is24Hours}))})),exceptions:setting.exceptions.map(x=>({startsAt:x.startsAt,endsAt:x.endsAt,reason:x.reason})),rowVersion:setting.rowVersion}))}catch(e){setError(e instanceof Error?e.message:'저장하지 못했습니다.')}finally{setSaving(false)}};return <ProviderAppLayout><div className="emergencyPage"><header className="emergencyHero provider"><p>EMERGENCY DESK</p><h1>긴급출동</h1><span>현재 가용성, 출동 요청과 진행 업무를 한 곳에서 처리합니다.</span></header>{error&&<div className="errorBanner">{error}</div>}{setting&&<><section className="emergencyDashboard"><article><small>긴급출동</small><strong>{setting.isEnabled?'ON':'OFF'}</strong><button disabled={saving} onClick={()=>void toggle()}>{setting.isEnabled?'전체 OFF':'전체 ON'}</button></article><article><small>현재 출동가능</small><strong>{setting.isCurrentlyAvailable?'가능':'불가'}</strong><span>{setting.currentAvailabilityReason}</span></article><article><small>오늘 가능시간</small><strong>{today.length?today.map(x=>x.is24Hours?'24시간':`${x.startTime}~${x.endTime}`).join(', '):'설정 없음'}</strong></article><article><small>신규 긴급요청</small><strong>{requests.length}건</strong></article></section><EmergencySettings setting={setting} onSaved={setSetting}/></>}<ProviderEmergencyRequests items={requests} reload={load}/></div></ProviderAppLayout>}

function EmergencySettings({setting,onSaved}:{setting:EmergencyAvailability;onSaved:(v:EmergencyAvailability)=>void}){const[services,setServices]=useState(setting.services),[error,setError]=useState('');useEffect(()=>setServices(setting.services),[setting]);const save=async()=>{try{onSaved(await api.saveAvailability({isEnabled:setting.isEnabled,temporarilyUnavailableUntil:setting.temporarilyUnavailableUntil,temporaryUnavailableReason:setting.temporaryUnavailableReason,services:services.map(s=>({providerServiceCategoryId:s.providerServiceCategoryId,isEnabled:s.isEnabled,slots:s.slots.length?s.slots:[{dayOfWeek:new Date().getDay(),startTime:'09:00:00',endTime:'18:00:00',is24Hours:false}]})),exceptions:setting.exceptions.map(x=>({startsAt:x.startsAt,endsAt:x.endsAt,reason:x.reason})),rowVersion:setting.rowVersion}))}catch(e){setError(e instanceof Error?e.message:'저장하지 못했습니다.')}};return <section className="emergencyCard"><h2>서비스별 긴급출동 설정</h2>{error&&<p className="errorBanner">{error}</p>}<div className="emergencyServiceList">{services.map((s,i)=><label key={s.providerServiceCategoryId}><input type="checkbox" disabled={!s.isApproved||!s.emergencyAllowedByCategory} checked={s.isEnabled} onChange={e=>setServices(v=>v.map((x,j)=>j===i?{...x,isEnabled:e.target.checked}:x))}/><span><strong>{s.categoryName}</strong><small>{s.emergencyAllowedByCategory?'긴급출동 허용':'본사 정책상 불가'} · {s.slots.map(x=>`${days[x.dayOfWeek]} ${x.is24Hours?'24시간':`${x.startTime}~${x.endTime}`}`).join(', ')||'가능시간 미설정'}</small></span></label>)}</div><button className="emergencyPrimary" onClick={()=>void save()}>설정 저장</button><p className="emergencyPolicy">예외 휴무와 상세 요일·시간은 서버 설정 구조로 보존되며, 현재 화면은 승인 서비스의 빠른 ON/OFF를 우선 제공합니다.</p></section>}

function ProviderEmergencyRequests({items,reload}:{items:EmergencyProviderRequest[];reload:()=>Promise<void>}){const[eta,setEta]=useState<Record<string,string>>({}),[error,setError]=useState('');const respond=async(item:EmergencyProviderRequest,available:boolean)=>{try{await api.respond(item.requestId,{isAvailable:available,etaMinutes:available?Number(eta[item.requestId]):null,estimatedArrivalAt:null,conditions:null,idempotencyKey:crypto.randomUUID(),rowVersion:''});await reload()}catch(e){setError(e instanceof Error?e.message:'응답하지 못했습니다.')}};return <section className="emergencyCard"><h2>긴급요청 Inbox</h2>{error&&<p className="errorBanner">{error}</p>}{items.length===0?<p>현재 응답 가능한 긴급요청이 없습니다.</p>:<div className="emergencyRequestList">{items.map(item=><article key={item.requestId}><span>{item.categoryName} · {item.areaName}</span><h3>{item.title}</h3><p>{item.description}</p><small>응답기한 {new Date(item.responseDeadlineAt).toLocaleString('ko-KR')}</small><p className="privacyNote">후보 단계에서는 고객 전화번호·이메일·상세주소가 비공개입니다.</p><div><input inputMode="numeric" placeholder="ETA(분)" value={eta[item.requestId]??''} onChange={e=>setEta(v=>({...v,[item.requestId]:e.target.value}))}/><button disabled={!Number(eta[item.requestId])} onClick={()=>void respond(item,true)}>출동 가능</button><button onClick={()=>void respond(item,false)}>출동 불가</button></div></article>)}</div>}</section>}

export function ProviderEmergencyProgressPage({id}:{id:string}){const[value,setValue]=useState<EmergencyProgress|null>(null),[error,setError]=useState('');useEffect(()=>{api.progress(id).then(setValue).catch((e:Error)=>setError(e.message))},[id]);const next=value?.currentEmergencyStatus==='DISPATCH_CONFIRMED'?'DEPARTED':value?.currentEmergencyStatus==='DEPARTED'?'EN_ROUTE':value?.currentEmergencyStatus==='EN_ROUTE'?'ARRIVED':null;const advance=async()=>{if(!next)return;try{setValue(await api.addProgress(id,next))}catch(e){setError(e instanceof Error?e.message:'상태를 변경하지 못했습니다.')}};return <ProviderAppLayout><div className="emergencyPage"><header className="emergencyHero provider"><p>FIELD MODE</p><h1>긴급출동 진행</h1></header>{error&&<div className="errorBanner">{error}</div>}{value&&<section className="emergencyCard"><strong className="emergencyCurrent">{label(value.currentEmergencyStatus)}</strong><div className="emergencyTimeline">{value.events.map(e=><div key={e.id}><span>{new Date(e.occurredAt).toLocaleString('ko-KR')}</span><strong>{label(e.eventType)}</strong></div>)}</div><div className="emergencySticky"><button onClick={()=>navigate('/provider/messages')}>채팅</button>{next?<button onClick={()=>void advance()}>{label(next)}</button>:<button onClick={()=>navigate(`/provider/work/${id}`)}>작업 시작·완료보고</button>}</div></section>}</div></ProviderAppLayout>}
const label=(x:string)=>({DISPATCH_CONFIRMED:'출동확정',DEPARTED:'출발',EN_ROUTE:'이동 중',ARRIVED:'현장도착'}[x]??x)
