using System.ComponentModel.DataAnnotations;

namespace SoodalLife.Api.Features.Interior;

public sealed record CustomerInteriorHomeResponse(int EligibleServiceCount,int ProjectCount,int ActiveProjectCount,int CompletedProjectCount,int DefectCount,int DisputeCount,IReadOnlyList<CustomerInteriorProjectListItem> ActiveProjects,IReadOnlyList<CustomerInteriorProjectListItem> RecentCompletedProjects);
public sealed record CustomerInteriorRequestCandidate(Guid Id,string Title,string ServiceName,string AreaName,string StatusCode,DateTime CreatedAt,bool ProjectCreated);
public sealed record CustomerInteriorProjectListItem(Guid Id,string ProjectNumber,string ServiceName,string AreaName,string StatusCode,string StatusDisplay,string SiteVisitStatus,string ContractStatus,IReadOnlyList<CustomerInteriorStageProgress> StageProgress,string ChangeStatus,string InspectionStatus,bool Completed,int DefectCount,int DisputeCount,DateTime UpdatedAt);
public sealed record CustomerInteriorStageProgress(Guid Id,int SequenceNo,string Name,string StatusCode,int ProgressPercent);
public sealed record CustomerInteriorFile(Guid Id,string FileName,string ContentType,long SizeBytes,string Purpose,string? DownloadUrl,string PublicationStatus="AVAILABLE",string? PublicationMessage=null);
public sealed record CustomerInteriorMeasurement(string Key,decimal? Value,string? Text,string? Unit,string? Location,string? Note);
public sealed record CustomerInteriorSiteVisit(Guid Id,Guid ProviderId,string ProviderName,string StatusCode,string StatusDisplay,DateTime ScheduledStartAt,DateTime? ScheduledEndAt,DateTime? ConfirmedAt,DateTime? CompletedAt,decimal? TrustScore,string TrustDisplay,int PublicReviewCount,bool Selected,bool CanSelect,string? MeasurementSummary,string? Constraint,string? RiskNote,IReadOnlyList<CustomerInteriorMeasurement> Measurements,IReadOnlyList<CustomerInteriorFile> Files);
public sealed record CustomerInteriorQuoteItem(int LineNo,string Name,string? Description,decimal Quantity,string? Unit,decimal UnitPrice,decimal LineTotal,string? Trade,string? Space,string? MaterialSpec,string? LaborNote);
public sealed record CustomerInteriorQuote(Guid QuoteId,Guid RevisionId,int RevisionNo,string PurposeCode,string PurposeDisplay,string ProviderName,decimal TotalAmount,decimal VatAmount,string CurrencyCode,string? Duration,DateTime? AvailableStartAt,DateTime ValidUntil,string Summary,string? Terms,decimal? TrustScore,string TrustDisplay,int PublicReviewCount,IReadOnlyList<CustomerInteriorQuoteItem> Items);
public sealed record CustomerInteriorDesign(Guid Id,int VersionNo,string Title,string? Description,string StatusCode,DateTime? CustomerApprovedAt,IReadOnlyList<CustomerInteriorFile> Files);
public sealed record CustomerInteriorContractVersion(int VersionNo,decimal Amount,string CurrencyCode,string Scope,string Schedule,string PaymentPlan,string? Warranty,DateTime? CustomerAgreedAt,DateTime? ProviderAgreedAt,DateTime CreatedAt);
public sealed record CustomerInteriorPaymentConfirmation(Guid Id,string ConfirmationType,decimal Amount,DateTime ConfirmedAt,string? Note,CustomerInteriorFile? Evidence);
public sealed record CustomerInteriorPaymentPlan(Guid Id,int SequenceNo,string Name,decimal Amount,DateOnly? DueDate,string? Condition,string StatusCode,IReadOnlyList<CustomerInteriorPaymentConfirmation> Confirmations);
public sealed record CustomerInteriorContract(Guid Id,int Version,string ProviderName,string StatusCode,decimal Amount,string CurrencyCode,string Scope,string Schedule,string? Warranty,DateOnly PlannedStartDate,DateOnly PlannedCompletionDate,DateTime? CustomerAgreedAt,DateTime? ProviderAgreedAt,DateTime? EffectiveAt,decimal? ProviderTrustSnapshot,IReadOnlyList<CustomerInteriorContractVersion> Versions,IReadOnlyList<CustomerInteriorPaymentPlan> PaymentPlans);
public sealed record CustomerInteriorWorkUpdate(Guid Id,int ProgressPercent,string Text,string? Issue,DateTime CreatedAt,IReadOnlyList<CustomerInteriorFile> Files);
public sealed record CustomerInteriorInspection(Guid Id,string StatusCode,string? Checklist,string Result,string? Correction,DateTime InspectedAt,DateTime? AcknowledgedAt,string? AcknowledgementComment,IReadOnlyList<CustomerInteriorFile> Files);
public sealed record CustomerInteriorWorkStage(Guid Id,int SequenceNo,string Name,DateOnly PlannedStartDate,DateOnly PlannedEndDate,DateTime? ActualStartAt,DateTime? ActualEndAt,int ProgressPercent,string StatusCode,string? ProviderNote,IReadOnlyList<CustomerInteriorWorkUpdate> Updates,IReadOnlyList<CustomerInteriorInspection> Inspections);
public sealed record CustomerInteriorChange(Guid Id,int ChangeNo,string StatusCode,string? Type,string Reason,string ScopeChange,decimal AmountDelta,int? ScheduleImpactDays,DateTime RequestedAt,DateTime? CustomerDecidedAt,bool CanDecide,IReadOnlyList<CustomerInteriorFile> Files);
public sealed record CustomerInteriorAfterServiceAction(string TypeCode,string? FromStatusCode,string ToStatusCode,string? Note,DateTime? ScheduledAt,DateTime? PerformedAt,bool VisitOccurred,string? Result,DateTime OccurredAt);
public sealed record CustomerInteriorDefect(Guid Id,Guid AfterServiceCaseId,string StatusCode,string Subject,string Location,string Description,Guid? WorkStageId,int? ContractVersion,DateTime ReceivedAt,IReadOnlyList<CustomerInteriorAfterServiceAction> Actions,IReadOnlyList<CustomerInteriorFile> Files);
public sealed record CustomerInteriorDispute(Guid Id,string StatusCode,string Subject,string Description,Guid? ContractChangeId,Guid? WorkStageId,DateTime ReceivedAt);
public sealed record CustomerInteriorEvent(Guid Id,string TypeCode,string TypeDisplay,DateTime OccurredAt);
public sealed record CustomerInteriorUploadResponse(Guid Id,string FileName,string ContentType,long SizeBytes,string ScanStatus);
public sealed record CustomerInteriorCompletion(DateOnly CompletedDate,string? HistoryTitle,string? HistorySummary,DateTime? HistoryOccurredAt);
public sealed record CustomerInteriorProjectDetail(Guid Id,string ProjectNumber,string ServiceName,string RequestTitle,string? RequestDescription,string AreaName,string? DetailAddress,string StatusCode,string StatusDisplay,decimal? SiteVisitTrustSnapshot,decimal? ContractorTrustSnapshot,DateOnly? StartDate,DateOnly? ExpectedCompletionDate,CustomerInteriorCompletion? Completion,IReadOnlyList<CustomerInteriorSiteVisit> SiteVisits,IReadOnlyList<CustomerInteriorQuote> Quotes,IReadOnlyList<CustomerInteriorDesign> Designs,CustomerInteriorContract? Contract,IReadOnlyList<CustomerInteriorWorkStage> WorkStages,IReadOnlyList<CustomerInteriorChange> Changes,IReadOnlyList<CustomerInteriorDefect> Defects,IReadOnlyList<CustomerInteriorDispute> Disputes,IReadOnlyList<CustomerInteriorEvent> Events,bool ReviewAvailable,Guid? ReviewTransactionId);

public sealed record CustomerCreateInteriorProjectRequest(Guid ServiceRequestId,[param:Required,StringLength(150)]string IdempotencyKey);
public sealed record CustomerSelectSiteVisitRequest([param:Required,StringLength(150)]string IdempotencyKey);
public sealed record CustomerAgreeInteriorContractRequest([param:Required,StringLength(150)]string IdempotencyKey);
public sealed record CustomerConfirmInteriorPaymentRequest([param:Required,StringLength(30)]string ConfirmationTypeCode,decimal Amount,DateTime ConfirmedAt,Guid? EvidenceFileId,string? Note,[param:Required,StringLength(150)]string IdempotencyKey);
public sealed record CustomerDecideInteriorChangeRequest(bool Approve,[param:Required,StringLength(150)]string IdempotencyKey);
public sealed record CustomerCreateInteriorDefectRequest(Guid? WorkStageId,int? ContractVersion,[param:Required,StringLength(500)]string Location,[param:Required,StringLength(200)]string Subject,[param:Required,StringLength(4000)]string Description,IReadOnlyList<Guid>? FileIds,[param:Required,StringLength(150)]string IdempotencyKey);
public sealed record CustomerCreateInteriorDisputeRequest(Guid? ContractChangeId,Guid? WorkStageId,[param:Required,StringLength(200)]string Subject,[param:Required,StringLength(4000)]string Description,IReadOnlyList<Guid>? FileIds,[param:Required,StringLength(150)]string IdempotencyKey);
