using System.ComponentModel.DataAnnotations;

namespace SoodalLife.Api.Features.Interior;

public sealed record ProviderInteriorDashboard(int SiteVisitCount,int SiteVisitResultPendingCount,int DesignCount,int ContractCount,int ActiveProjectCount,int TodayStageCount,int StageUpdatePendingCount,int InspectionCount,int CompletionPendingCount,int AfterServiceCount,int DisputeCount);
public sealed record ProviderInteriorProjectItem(Guid Id,string ProjectNumber,string ServiceName,string AreaName,IReadOnlyList<string> Roles,string StatusCode,string NextAction,DateTime? NextAt,bool CustomerActionRequired,int PendingActionCount,bool IsFinalProvider,string RowVersion);
public sealed record ProviderInteriorFile(Guid Id,string FileName,string ContentType,long SizeBytes,string PublicationMode,string? DownloadUrl,string PublicationStatus="AVAILABLE",string? PublicationMessage=null);
public sealed record ProviderInteriorVisit(Guid Id,string StatusCode,DateTime ScheduledStartAt,DateTime? ScheduledEndAt,DateTime? VisitedAt,DateTime? CompletedAt,string? MeasurementSummary,string? Constraint,string? RiskNote,IReadOnlyList<InteriorMeasurementInput> Measurements,IReadOnlyList<ProviderInteriorFile> Files,string RowVersion);
public sealed record ProviderInteriorDesign(Guid Id,int VersionNo,string Title,string? Description,string StatusCode,DateTime? CustomerApprovedAt,IReadOnlyList<ProviderInteriorFile> Files,string RowVersion);
public sealed record ProviderInteriorStage(Guid Id,int SequenceNo,string Name,string StatusCode,int ProgressPercent,DateOnly PlannedStartDate,DateOnly PlannedEndDate,bool AssignedToMe,IReadOnlyList<ProviderInteriorFile> Files,string RowVersion);
public sealed record ProviderInteriorInspection(Guid Id,Guid StageId,string StatusCode,string? ChecklistJson,string Result,string? Correction,DateTime InspectedAt,bool CustomerAcknowledged,IReadOnlyList<ProviderInteriorFile> Files,string RowVersion);
public sealed record ProviderInteriorContract(Guid Id,int Version,string StatusCode,decimal Amount,string CurrencyCode,DateOnly ContractSignedDate,DateOnly PlannedStartDate,DateOnly PlannedCompletionDate,DateTime? CustomerAgreedAt,DateTime? ProviderAgreedAt,DateTime? EffectiveAt,string? CustomerMismatchReason,IReadOnlyList<ProviderInteriorFile> Documents,IReadOnlyList<InteriorPaymentPlanResponse> PaymentPlans);
public sealed record ProviderInteriorChange(Guid Id,int ChangeNo,string StatusCode,string Reason,string ScopeChange,decimal AmountDelta,int? ScheduleImpactDays,IReadOnlyList<ProviderInteriorFile> Files,string RowVersion);
public sealed record ProviderInteriorQuote(Guid Id,string StatusCode,int RevisionNo,string Summary,string? Terms,decimal TotalAmount,string CurrencyCode,string? EstimatedDuration,DateTime? AvailableStartAt,DateTime ValidUntil,IReadOnlyList<string> Items);
public sealed record ProviderInteriorDetail(ProviderInteriorProjectItem Project,bool ContactAvailable,string? CustomerPhone,string? DetailAddress,string ContactPolicy,IReadOnlyList<ProviderInteriorVisit> SiteVisits,IReadOnlyList<ProviderInteriorQuote> Quotes,IReadOnlyList<ProviderInteriorDesign> Designs,ProviderInteriorContract? Contract,IReadOnlyList<ProviderInteriorStage> Stages,IReadOnlyList<ProviderInteriorInspection> Inspections,IReadOnlyList<ProviderInteriorChange> Changes,IReadOnlyList<InteriorEventResponse> Timeline,IReadOnlyList<Guid> AfterServiceIds,IReadOnlyList<Guid> DisputeIds,bool CustomerCompletionAcknowledged,bool AdminCompleted);
public sealed record ProviderInteriorUpload(Guid FileId,string FileName,string ContentType,long SizeBytes,string MalwareScanStatus,string PrivacyInspectionStatus,string SanitizationStatus);
public sealed record StartProviderInteriorVisitRequest([param:Required,StringLength(150)]string IdempotencyKey,string? RowVersion);
public sealed record ProposeProviderInteriorSiteVisitRequest(DateTime ScheduledStartAt,DateTime? ScheduledEndAt,decimal? ProposedVisitFee,[param:StringLength(1000)]string? ProposalTerms,[param:Required,StringLength(150)]string IdempotencyKey);
public sealed record SubmitProviderInteriorDesignRequest([param:Required,StringLength(300)]string Title,string? Description,IReadOnlyList<Guid>? FileIds,[param:Required,StringLength(150)]string IdempotencyKey);
public sealed record SubmitProviderInteriorInspectionRequest([param:Required] string StatusCode,string? ChecklistJson,[param:Required,StringLength(4000)]string Result,string? Correction,IReadOnlyList<Guid>? FileIds,[param:Required,StringLength(150)]string IdempotencyKey,string? RowVersion);
public sealed record ProviderInteriorChangeRequest(string? ChangeTypeCode,[param:Required,StringLength(2000)]string Reason,[param:Required,StringLength(4000)]string ScopeChange,decimal AmountDelta,int? ScheduleImpactDays,IReadOnlyList<Guid>? FileIds,[param:Required,StringLength(150)]string IdempotencyKey);
public sealed record RegisterInteriorContractRecordRequest(decimal ContractAmount,[param:Required,StringLength(3)]string CurrencyCode,[param:Required]string ScopeSnapshotJson,[param:Required]string ScheduleSnapshotJson,string? WarrantySnapshotJson,DateOnly ContractSignedDate,DateOnly PlannedStartDate,DateOnly PlannedCompletionDate,IReadOnlyList<PaymentPlanInput>? PaymentPlans,IReadOnlyList<Guid>? ContractFileIds,[param:Required,StringLength(150)]string IdempotencyKey);
public sealed record ReviewInteriorContractRecordRequest(bool Matches,[param:StringLength(2000)]string? MismatchReason,[param:Required,StringLength(150)]string IdempotencyKey);
public sealed record AssignInteriorStageRequest(Guid ParticipantId,DateTime EffectiveFrom,DateTime? EffectiveTo,[param:Required,StringLength(150)]string IdempotencyKey);
