using System.Security.Claims;
using System.Security.Cryptography;
using System.Text;
using System.Text.Json;
using Microsoft.EntityFrameworkCore;
using SoodalLife.Api.Domain.Entities;
using SoodalLife.Api.Features.Authentication;
using SoodalLife.Api.Features.FilePrivacy;
using SoodalLife.Api.Features.Work;
using SoodalLife.Api.Infrastructure.Persistence;
using SoodalLife.Api.Infrastructure.Security;

namespace SoodalLife.Api.Features.Interior;

public sealed class ProviderInteriorService(SoodalLifeDbContext db,InteriorProjectService core,IPrivateFileStorage storage,IPrivacyContract privacy,ICrossDomainFilePublicationResolver filePublication)
{
    private const int MaxFileSize=10*1024*1024;
    private static readonly string[] TerminalProjects=["COMPLETED","CANCELLED"];

    public async Task<ProviderInteriorDashboard> Dashboard(ClaimsPrincipal principal,CancellationToken token)
    {
        var actor=await Provider(principal,token);var projects=await AccessibleProjects(actor.ProviderId,token);var ids=projects.Select(x=>x.Id).ToArray();var today=DateOnly.FromDateTime(DateTime.UtcNow);
        var visits=db.InteriorSiteVisits.AsNoTracking().Where(x=>ids.Contains(x.InteriorProjectId)&&x.ProviderProfileId==actor.ProviderId);
        var stages=await AccessibleStages(actor.ProviderId,ids,token);
        return new(await visits.CountAsync(x=>x.StatusCode=="CONFIRMED",token),await visits.CountAsync(x=>x.StatusCode=="CONFIRMED"&&x.CompletedAt==null,token),
            await ActiveRoleCount(actor.ProviderId,"DESIGN",token),await ActiveRoleCount(actor.ProviderId,"PRIMARY_CONTRACTOR",token),projects.Count(x=>!TerminalProjects.Contains(x.StatusCode)),
            stages.Count(x=>x.Stage.PlannedStartDate<=today&&x.Stage.PlannedEndDate>=today),stages.Count(x=>x.Stage.StatusCode!="COMPLETED"),
            await ActiveRoleCount(actor.ProviderId,"INSPECTION",token),projects.Count(x=>x.ProviderCompletionSubmittedAt==null&&x.StatusCode=="INSPECTION"),
            await db.AfterServiceCases.CountAsync(x=>x.ProviderProfileId==actor.ProviderId&&x.InteriorProjectId!=null&&x.StatusCode!="RESOLVED"&&x.StatusCode!="UNRESOLVED_CLOSED",token),
            await db.DisputeCases.CountAsync(x=>x.CounterpartyUserId==actor.UserId&&x.InteriorProjectId!=null&&x.StatusCode!="RESOLVED"&&x.StatusCode!="CLOSED",token));
    }

    public async Task<IReadOnlyList<ProviderInteriorProjectItem>> Projects(ClaimsPrincipal principal,string? role,string? status,CancellationToken token)
    {
        var actor=await Provider(principal,token);var rows=await AccessibleProjects(actor.ProviderId,token);var result=new List<ProviderInteriorProjectItem>();
        foreach(var project in rows.OrderByDescending(x=>x.UpdatedAt))
        {
            var roles=await Roles(project.Id,actor.ProviderId,token);if(!string.IsNullOrWhiteSpace(role)&&!roles.Contains(role.Trim().ToUpperInvariant()))continue;if(!string.IsNullOrWhiteSpace(status)&&project.StatusCode!=status.Trim().ToUpperInvariant())continue;
            var meta=await (from request in db.ServiceRequests.AsNoTracking() join service in db.ServiceCategories.AsNoTracking() on project.ServiceCategoryId equals service.Id join area0 in db.AdministrativeAreas.AsNoTracking() on request.AdministrativeAreaId equals area0.Id into areas from area in areas.DefaultIfEmpty() where request.Id==project.ServiceRequestId select new{service.Name,Area=area==null?"지역 미정":area.AreaName}).SingleAsync(token);
            result.Add(new(project.PublicId,Number(project.PublicId),meta.Name,meta.Area,roles,project.StatusCode,NextAction(project,roles),NextAt(project),project.StatusCode.Contains("PENDING",StringComparison.Ordinal),await Pending(project.Id,actor.ProviderId,roles,token),Version(project.RowVersion)));
        }
        return result;
    }

    public async Task<ProviderInteriorDetail> Detail(Guid id,ClaimsPrincipal principal,CancellationToken token)
    {
        var actor=await Provider(principal,token);var project=await AccessibleProject(id,actor.ProviderId,token);var roles=await Roles(project.Id,actor.ProviderId,token);
        var item=(await Projects(principal,null,null,token)).Single(x=>x.Id==id);var contact=await Contact(project,actor,roles,token);
        var visits=new List<ProviderInteriorVisit>();if(roles.Any(x=>x is "SITE_SURVEY" or "DESIGN" or "PRIMARY_CONTRACTOR"))foreach(var x in await db.InteriorSiteVisits.AsNoTracking().Where(x=>x.InteriorProjectId==project.Id&&(x.ProviderProfileId==actor.ProviderId||x.StatusCode=="COMPLETED")).OrderBy(x=>x.ScheduledStartAt).ToListAsync(token))visits.Add(await Visit(x,project.PublicId,actor.UserId,token));
        var quotes=await Quotes(project,actor.ProviderId,token);
        var designs=new List<ProviderInteriorDesign>();if(roles.Any(x=>x is "DESIGN" or "PRIMARY_CONTRACTOR" or "INSPECTION"))foreach(var x in await db.InteriorDesignVersions.AsNoTracking().Where(x=>x.InteriorProjectId==project.Id).OrderByDescending(x=>x.VersionNo).ToListAsync(token))designs.Add(await Design(x,project.PublicId,actor.UserId,token));
        ProviderInteriorContract? contract=null;if(roles.Contains("PRIMARY_CONTRACTOR"))contract=await Contract(project,actor.ProviderId,token);
        var stageRows=(await AccessibleStages(actor.ProviderId,[project.Id],token)).OrderBy(x=>x.Stage.SequenceNo).ToList();var stages=new List<ProviderInteriorStage>();foreach(var x in stageRows)stages.Add(await Stage(x.Stage,project.PublicId,actor.UserId,x.Assigned,token));
        var inspections=new List<ProviderInteriorInspection>();if(roles.Contains("INSPECTION")||roles.Contains("PRIMARY_CONTRACTOR"))foreach(var x in await (from i in db.InteriorStageInspections.AsNoTracking() join s in db.InteriorWorkStages.AsNoTracking() on i.WorkStageId equals s.Id where s.InteriorProjectId==project.Id orderby i.InspectedAt descending select i).ToListAsync(token))inspections.Add(await Inspection(x,project.PublicId,actor.UserId,token));
        var changes=new List<ProviderInteriorChange>();if(roles.Contains("PRIMARY_CONTRACTOR"))foreach(var x in await (from c in db.InteriorContractChanges.AsNoTracking() join contract0 in db.InteriorContracts.AsNoTracking() on c.InteriorContractId equals contract0.Id where contract0.InteriorProjectId==project.Id orderby c.ChangeNo descending select c).ToListAsync(token))changes.Add(await Change(x,project.PublicId,actor.UserId,token));
        var timeline=await db.InteriorProjectEvents.AsNoTracking().Where(x=>x.InteriorProjectId==project.Id).OrderByDescending(x=>x.OccurredAt).Select(x=>new InteriorEventResponse(x.PublicId,x.EventTypeCode,x.OccurredAt,null)).Take(100).ToListAsync(token);
        var after=await db.AfterServiceCases.AsNoTracking().Where(x=>x.InteriorProjectId==project.Id&&x.ProviderProfileId==actor.ProviderId).Select(x=>x.PublicId).ToListAsync(token);
        var disputes=await db.DisputeCases.AsNoTracking().Where(x=>x.InteriorProjectId==project.Id&&x.CounterpartyUserId==actor.UserId).Select(x=>x.PublicId).ToListAsync(token);
        return new(item,contact.Allowed,contact.Phone,contact.Address,contact.Policy,visits,quotes,designs,contract,stages,inspections,changes,timeline,after,disputes,project.CustomerCompletionAcknowledgedAt.HasValue,project.AdminCompletedAt.HasValue);
    }

    public async Task<ProviderInteriorDetail> StartVisit(Guid id,StartProviderInteriorVisitRequest input,ClaimsPrincipal principal,CancellationToken token)
    {
        var actor=await Provider(principal,token);var visit=await db.InteriorSiteVisits.SingleOrDefaultAsync(x=>x.PublicId==id&&x.ProviderProfileId==actor.ProviderId,token)??throw NotFound();var project=await ActiveRoleProject(visit.InteriorProjectId,actor,"SITE_SURVEY",token);
        if(await EventExists(input.IdempotencyKey,token))return await Detail(project.PublicId,principal,token);if(visit.StatusCode!="CONFIRMED")throw Conflict("INTERIOR_SITE_VISIT_NOT_CONFIRMED","확정된 실측만 시작할 수 있습니다.");ApplyVersion(visit,input.RowVersion);visit.VisitedAt??=DateTime.UtcNow;visit.UpdatedAt=DateTime.UtcNow;visit.UpdatedByUserId=actor.UserId;await Record(project,"SITE_VISIT_STARTED",input.IdempotencyKey,actor.UserId,new{visitId=id},token);await Save(token);return await Detail(project.PublicId,principal,token);
    }

    public async Task<ProviderInteriorDetail> CompleteVisit(Guid id,CompleteInteriorSiteVisitRequest input,ClaimsPrincipal principal,CancellationToken token)
    {
        var actor=await Provider(principal,token);var visit=await db.InteriorSiteVisits.AsNoTracking().SingleOrDefaultAsync(x=>x.PublicId==id&&x.ProviderProfileId==actor.ProviderId,token)??throw NotFound();var project=await ActiveRoleProject(visit.InteriorProjectId,actor,"SITE_SURVEY",token);await OwnFiles(input.FileIds,actor.UserId,token);
        await core.CompleteSiteVisit(project.PublicId,id,input,actor.PublicUserId,token);return await Detail(project.PublicId,principal,token);
    }

    public async Task<ProviderInteriorDetail> SubmitDesign(Guid id,SubmitProviderInteriorDesignRequest input,ClaimsPrincipal principal,CancellationToken token)
    {
        var actor=await Provider(principal,token);var project=await AccessibleProject(id,actor.ProviderId,token);await RequireRole(project.Id,actor.ProviderId,"DESIGN",token);if(await EventExists(input.IdempotencyKey,token))return await Detail(id,principal,token);var files=await OwnFiles(input.FileIds,actor.UserId,token);var now=DateTime.UtcNow;var design=new InteriorDesignVersion{InteriorProjectId=project.Id,VersionNo=(await db.InteriorDesignVersions.Where(x=>x.InteriorProjectId==project.Id).MaxAsync(x=>(int?)x.VersionNo,token)??0)+1,Title=input.Title.Trim(),Description=Clean(input.Description),StatusCode="SUBMITTED",CreatedAt=now,CreatedByUserId=actor.UserId,UpdatedAt=now,UpdatedByUserId=actor.UserId};db.InteriorDesignVersions.Add(design);await db.SaveChangesAsync(token);for(var i=0;i<files.Count;i++)db.InteriorDesignFiles.Add(new(){DesignVersionId=design.Id,FileId=files[i].Id,PurposeCode="DESIGN",DisplayOrder=i,CreatedAt=now,CreatedByUserId=actor.UserId});await Record(project,"DESIGN_SUBMITTED",input.IdempotencyKey,actor.UserId,new{designId=design.PublicId,design.VersionNo},token);await Save(token);return await Detail(id,principal,token);
    }

    public async Task<ProviderInteriorDetail> Agree(Guid id,AgreeInteriorContractRequest input,ClaimsPrincipal principal,CancellationToken token)
    {
        var actor=await Provider(principal,token);var contract=await db.InteriorContracts.AsNoTracking().SingleOrDefaultAsync(x=>x.PublicId==id&&x.ProviderProfileId==actor.ProviderId,token)??throw NotFound();var project=await ActiveRoleProject(contract.InteriorProjectId,actor,"PRIMARY_CONTRACTOR",token);await core.AgreeContract(id,input,principal,token);return await Detail(project.PublicId,principal,token);
    }

    public async Task<Guid> ConfirmPayment(Guid id,ConfirmInteriorPaymentRequest input,ClaimsPrincipal principal,CancellationToken token)
    {
        var actor=await Provider(principal,token);var row=await(from plan in db.InteriorPaymentPlans.AsNoTracking() join contract in db.InteriorContracts.AsNoTracking() on plan.InteriorContractId equals contract.Id where plan.PublicId==id&&contract.ProviderProfileId==actor.ProviderId select new{plan,contract}).SingleOrDefaultAsync(token)??throw NotFound();_ = await ActiveRoleProject(row.contract.InteriorProjectId,actor,"PRIMARY_CONTRACTOR",token);await OwnFiles(input.EvidenceFileId.HasValue?[input.EvidenceFileId.Value]:[],actor.UserId,token);return await core.ConfirmPayment(id,input,principal,token);
    }

    public async Task<ProviderInteriorDetail> UpdateStage(Guid id,AddInteriorWorkUpdateRequest input,ClaimsPrincipal principal,CancellationToken token)
    {
        var actor=await Provider(principal,token);var stage=await db.InteriorWorkStages.AsNoTracking().SingleOrDefaultAsync(x=>x.PublicId==id,token)??throw NotFound();var project=await AccessibleProject(stage.InteriorProjectId,actor.ProviderId,token);await RequireStage(stage.Id,project.Id,actor.ProviderId,token);await OwnFiles(input.FileIds,actor.UserId,token);await core.UpdateStage(id,input,principal,token);return await Detail(project.PublicId,principal,token);
    }

    public async Task<ProviderInteriorDetail> Inspect(Guid id,SubmitProviderInteriorInspectionRequest input,ClaimsPrincipal principal,CancellationToken token)
    {
        var actor=await Provider(principal,token);var stage=await db.InteriorWorkStages.SingleOrDefaultAsync(x=>x.PublicId==id,token)??throw NotFound();var project=await ActiveRoleProject(stage.InteriorProjectId,actor,"INSPECTION",token);if(await EventExists(input.IdempotencyKey,token))return await Detail(project.PublicId,principal,token);if(input.StatusCode.Trim().ToUpperInvariant() is not("PASSED"or"FAILED"or"CORRECTION_REQUIRED"))throw Bad("INTERIOR_INSPECTION_STATUS_INVALID","검사 결과 상태를 확인해 주세요.");var files=await OwnFiles(input.FileIds,actor.UserId,token);var now=DateTime.UtcNow;var inspection=new InteriorStageInspection{WorkStageId=stage.Id,InspectionStatusCode=input.StatusCode.Trim().ToUpperInvariant(),InspectedByUserId=actor.UserId,ChecklistJson=Clean(input.ChecklistJson),ResultText=input.Result.Trim(),RequestedCorrectionText=Clean(input.Correction),InspectedAt=now,CreatedAt=now};db.InteriorStageInspections.Add(inspection);await db.SaveChangesAsync(token);for(var i=0;i<files.Count;i++)db.InteriorStageInspectionFiles.Add(new(){StageInspectionId=inspection.Id,FileId=files[i].Id,DisplayOrder=i,CreatedAt=now,CreatedByUserId=actor.UserId});await Record(project,"INSPECTION_COMPLETED",input.IdempotencyKey,actor.UserId,new{inspectionId=inspection.PublicId,stageId=id},token);await Save(token);return await Detail(project.PublicId,principal,token);
    }

    public async Task<ProviderInteriorDetail> RequestChange(Guid id,ProviderInteriorChangeRequest input,ClaimsPrincipal principal,CancellationToken token)
    {
        var actor=await Provider(principal,token);var contract=await db.InteriorContracts.AsNoTracking().SingleOrDefaultAsync(x=>x.PublicId==id&&x.ProviderProfileId==actor.ProviderId,token)??throw NotFound();var project=await ActiveRoleProject(contract.InteriorProjectId,actor,"PRIMARY_CONTRACTOR",token);var files=await OwnFiles(input.FileIds,actor.UserId,token);var response=await core.RequestChange(id,new(input.ChangeTypeCode,input.Reason,input.ScopeChange,input.AmountDelta,input.ScheduleImpactDays,input.IdempotencyKey),principal,token);var change=await db.InteriorContractChanges.SingleAsync(x=>x.PublicId==response.Id,token);for(var i=0;i<files.Count;i++)db.InteriorContractChangeFiles.Add(new(){ContractChangeId=change.Id,FileId=files[i].Id,DisplayOrder=i,CreatedAt=DateTime.UtcNow,CreatedByUserId=actor.UserId});await Save(token);return await Detail(project.PublicId,principal,token);
    }

    public async Task<ProviderInteriorDetail> SubmitCompletion(Guid id,SubmitInteriorProjectCompletionRequest input,ClaimsPrincipal principal,CancellationToken token)
    {
        var actor=await Provider(principal,token);var project=await ActiveRoleProject((await AccessibleProject(id,actor.ProviderId,token)).Id,actor,"PRIMARY_CONTRACTOR",token);var finalStage=await db.InteriorWorkStages.AsNoTracking().Where(x=>x.InteriorProjectId==project.Id).OrderByDescending(x=>x.SequenceNo).Select(x=>(long?)x.Id).FirstOrDefaultAsync(token);var final=finalStage.HasValue&&await db.InteriorStageInspections.AsNoTracking().AnyAsync(x=>x.WorkStageId==finalStage&&x.InspectionStatusCode=="PASSED",token);if(!final)throw Conflict("INTERIOR_FINAL_INSPECTION_REQUIRED","최종 공정 검사가 통과되어야 완료보고할 수 있습니다.");await core.SubmitProjectCompletion(id,input,principal,token);return await Detail(id,principal,token);
    }

    public async Task<ProviderInteriorUpload> Upload(Guid id,ClaimsPrincipal principal,IFormFile upload,CancellationToken token)
    {
        var actor=await Provider(principal,token);_ = await AccessibleProject(id,actor.ProviderId,token);var validated=await ValidateUpload(upload,token);var now=DateTime.UtcNow;var key=$"interior/{actor.ProviderId}/{Guid.NewGuid():N}{validated.Extension}";var file=new StoredFile{PurposeCode="COMPLETION_EVIDENCE",StorageContainer="private",StorageKey=key,StorageKeyHash=SHA256.HashData(Encoding.UTF8.GetBytes(key)),OriginalFileName=Path.GetFileName(upload.FileName),ContentType=upload.ContentType.ToLowerInvariant(),SizeBytes=validated.Bytes.Length,Sha256Hex=Convert.ToHexString(SHA256.HashData(validated.Bytes)),StatusCode="PENDING",MalwareScanStatusCode=FilePrivacyCodes.NotIntegrated,PrivacyInspectionStatusCode=FilePrivacyCodes.NotIntegrated,SanitizationStatusCode=FilePrivacyCodes.NotIntegrated,UploadedByUserId=actor.UserId,CreatedAt=now};db.Files.Add(file);await db.SaveChangesAsync(token);try{await using var stream=new MemoryStream(validated.Bytes);await storage.SaveAsync(key,stream,token);file.StatusCode="ACTIVE";file.ActivatedAt=now;file.ScanResultText=FilePrivacyCodes.NotIntegrated;await db.SaveChangesAsync(token);return new(file.PublicId,SafeName(file),file.ContentType,file.SizeBytes,file.MalwareScanStatusCode!,file.PrivacyInspectionStatusCode!,file.SanitizationStatusCode!);}catch{await storage.DeleteIfExistsAsync(key,token);throw;}
    }

    public async Task<(Stream Stream,string ContentType,string FileName)> OpenFile(Guid projectId,Guid fileId,ClaimsPrincipal principal,CancellationToken token)
    {
        var actor=await Provider(principal,token);var project=await AccessibleProject(projectId,actor.ProviderId,token);var roles=await Roles(project.Id,actor.ProviderId,token);var file=await db.Files.AsNoTracking().SingleOrDefaultAsync(x=>x.PublicId==fileId&&x.StatusCode=="ACTIVE",token)??throw NotFound();var linked=await FileLinked(project.Id,file.Id,roles,actor.ProviderId,token);if(!linked&&file.UploadedByUserId!=actor.UserId)throw NotFound();var publication=await filePublication.ResolveAsync(file,actor.UserId,true,true,token);if(!publication.Allowed)throw new InteriorBusinessException(403,"INTERIOR_FILE_PRIVACY_BLOCKED",publication.Message);var published=publication.PublishedFile!;return(await storage.OpenReadAsync(published.StorageKey,token),published.ContentType,SafeName(published));
    }

    private async Task<List<InteriorProject>> AccessibleProjects(long providerId,CancellationToken token){var now=DateTime.UtcNow;return await db.InteriorProjects.AsNoTracking().Where(p=>p.SelectedSiteVisitProviderId==providerId||p.SelectedContractorProviderId==providerId||db.InteriorProjectParticipants.Any(x=>x.InteriorProjectId==p.Id&&x.ProviderProfileId==providerId&&x.StatusCode!="CANCELLED"&&x.EffectiveFrom<=now)).ToListAsync(token);}
    private async Task<InteriorProject> AccessibleProject(Guid id,long providerId,CancellationToken token)=>await (await AccessibleProjects(providerId,token)).ToAsyncEnumerable().SingleOrDefaultAsync(x=>x.PublicId==id,token)??throw NotFound();
    private async Task<InteriorProject> AccessibleProject(long id,long providerId,CancellationToken token)=>await (await AccessibleProjects(providerId,token)).ToAsyncEnumerable().SingleOrDefaultAsync(x=>x.Id==id,token)??throw NotFound();
    private async Task<InteriorProject> ActiveRoleProject(long projectId,ProviderIdentity actor,string role,CancellationToken token){var project=await AccessibleProject(projectId,actor.ProviderId,token);await RequireRole(project.Id,actor.ProviderId,role,token);if(TerminalProjects.Contains(project.StatusCode))throw Conflict("INTERIOR_PROJECT_ENDED","종료된 프로젝트에서는 새 업무를 처리할 수 없습니다.");return project;}
    private async Task RequireRole(long projectId,long providerId,string role,CancellationToken token){var now=DateTime.UtcNow;if(!await db.InteriorProjectParticipants.AsNoTracking().AnyAsync(x=>x.InteriorProjectId==projectId&&x.ProviderProfileId==providerId&&x.RoleCode==role&&x.StatusCode=="ACTIVE"&&x.EffectiveFrom<=now&&(x.EffectiveTo==null||x.EffectiveTo>now),token))throw new InteriorBusinessException(403,"INTERIOR_ROLE_REQUIRED","현재 유효한 담당 역할 범위가 아닙니다.");}
    private async Task RequireStage(long stageId,long projectId,long providerId,CancellationToken token){var now=DateTime.UtcNow;var primary=await db.InteriorProjectParticipants.AsNoTracking().AnyAsync(x=>x.InteriorProjectId==projectId&&x.ProviderProfileId==providerId&&x.RoleCode=="PRIMARY_CONTRACTOR"&&x.StatusCode=="ACTIVE"&&x.EffectiveFrom<=now&&(x.EffectiveTo==null||x.EffectiveTo>now),token);var assigned=await (from a in db.InteriorWorkStageAssignments.AsNoTracking() join p in db.InteriorProjectParticipants.AsNoTracking() on a.ProjectParticipantId equals p.Id where a.WorkStageId==stageId&&p.ProviderProfileId==providerId&&p.RoleCode=="TRADE_CONTRACTOR"&&p.StatusCode=="ACTIVE"&&a.StatusCode=="ACTIVE"&&p.EffectiveFrom<=now&&(p.EffectiveTo==null||p.EffectiveTo>now)&&a.EffectiveFrom<=now&&(a.EffectiveTo==null||a.EffectiveTo>now) select a.Id).AnyAsync(token);if(!primary&&!assigned)throw new InteriorBusinessException(403,"INTERIOR_STAGE_SCOPE_DENIED","배정된 공정 범위가 아닙니다.");}
    private async Task<List<StageRow>> AccessibleStages(long providerId,long[] projectIds,CancellationToken token){var now=DateTime.UtcNow;var wholeProjects=await db.InteriorProjectParticipants.AsNoTracking().Where(p=>projectIds.Contains(p.InteriorProjectId)&&p.ProviderProfileId==providerId&&(p.RoleCode=="PRIMARY_CONTRACTOR"||p.RoleCode=="INSPECTION")&&p.StatusCode=="ACTIVE"&&p.EffectiveFrom<=now&&(p.EffectiveTo==null||p.EffectiveTo>now)).Select(p=>p.InteriorProjectId).ToListAsync(token);var assignedIds=await(from a in db.InteriorWorkStageAssignments.AsNoTracking() join p in db.InteriorProjectParticipants.AsNoTracking() on a.ProjectParticipantId equals p.Id join s in db.InteriorWorkStages.AsNoTracking() on a.WorkStageId equals s.Id where projectIds.Contains(s.InteriorProjectId)&&p.ProviderProfileId==providerId&&p.RoleCode=="TRADE_CONTRACTOR"&&p.StatusCode=="ACTIVE"&&a.StatusCode=="ACTIVE"&&p.EffectiveFrom<=now&&(p.EffectiveTo==null||p.EffectiveTo>now)&&a.EffectiveFrom<=now&&(a.EffectiveTo==null||a.EffectiveTo>now) select s.Id).ToListAsync(token);var stages=await db.InteriorWorkStages.AsNoTracking().Where(s=>projectIds.Contains(s.InteriorProjectId)&&(wholeProjects.Contains(s.InteriorProjectId)||assignedIds.Contains(s.Id))).ToListAsync(token);return stages.Select(s=>new StageRow(s,assignedIds.Contains(s.Id))).ToList();}
    private async Task<IReadOnlyList<string>> Roles(long projectId,long providerId,CancellationToken token){var now=DateTime.UtcNow;return await db.InteriorProjectParticipants.AsNoTracking().Where(x=>x.InteriorProjectId==projectId&&x.ProviderProfileId==providerId&&x.StatusCode!="CANCELLED"&&x.EffectiveFrom<=now).Select(x=>x.RoleCode).Distinct().ToListAsync(token);}
    private async Task<ContactResult> Contact(InteriorProject project,ProviderIdentity actor,IReadOnlyList<string> roles,CancellationToken token){var active=!TerminalProjects.Contains(project.StatusCode);var visit=roles.Contains("SITE_SURVEY")&&await db.InteriorSiteVisits.AsNoTracking().AnyAsync(x=>x.InteriorProjectId==project.Id&&x.ProviderProfileId==actor.ProviderId&&x.StatusCode=="CONFIRMED"&&x.CompletedAt==null,token);var primary=roles.Contains("PRIMARY_CONTRACTOR")&&active&&project.StatusCode is "CONTRACT_PENDING" or "CONTRACTED" or "CONSTRUCTION" or "INSPECTION";var trade=roles.Contains("TRADE_CONTRACTOR")&&active&&(await AccessibleStages(actor.ProviderId,[project.Id],token)).Count>0;var inspection=roles.Contains("INSPECTION")&&active&&project.StatusCode is "CONSTRUCTION" or "INSPECTION";var phoneAllowed=visit||primary;var addressAllowed=visit||primary||trade||inspection;var row=await(from p in db.CustomerProfiles.AsNoTracking() join u in db.Users.AsNoTracking() on p.UserId equals u.Id join r in db.ServiceRequests.AsNoTracking() on project.ServiceRequestId equals r.Id where p.Id==project.CustomerProfileId select new{u.Phone,r.DetailAddress}).SingleAsync(token);var phone=privacy.Decide(PrivacyAudience.AssignedProvider,PrivacyField.Phone,phoneAllowed).CanAccess?row.Phone:null;var address=privacy.Decide(PrivacyAudience.AssignedProvider,PrivacyField.DetailAddress,addressAllowed).CanAccess?row.DetailAddress:null;return new(phone!=null||address!=null,phone,address,phone!=null||address!=null?"현재 역할과 유효 업무기간에 필요한 최소 개인정보만 공개됩니다.":"역할 범위 밖이거나 업무가 종료되어 개인정보가 비공개입니다.");}
    private async Task<ProviderInteriorVisit> Visit(InteriorSiteVisit x,Guid projectId,long userId,CancellationToken token){var measures=await db.InteriorSiteVisitMeasurements.AsNoTracking().Where(m=>m.SiteVisitId==x.Id).Select(m=>new InteriorMeasurementInput(m.MeasurementKey,m.MeasurementValue,m.MeasurementText,m.UnitText,m.LocationText,m.NoteText,m.AdditionalDataJson)).ToListAsync(token);var files=await Files(projectId,userId,from l in db.InteriorSiteVisitFiles.AsNoTracking() join f in db.Files.AsNoTracking() on l.FileId equals f.Id where l.SiteVisitId==x.Id select f,"SITE_VISIT",token);return new(x.PublicId,x.StatusCode,x.ScheduledStartAt,x.ScheduledEndAt,x.VisitedAt,x.CompletedAt,x.MeasurementSummaryText,x.ConstraintText,x.RiskNoteText,measures,files,Version(x.RowVersion));}
    private async Task<ProviderInteriorDesign> Design(InteriorDesignVersion x,Guid projectId,long userId,CancellationToken token){var files=await Files(projectId,userId,from l in db.InteriorDesignFiles.AsNoTracking() join f in db.Files.AsNoTracking() on l.FileId equals f.Id where l.DesignVersionId==x.Id select f,"DESIGN",token);return new(x.PublicId,x.VersionNo,x.Title,x.Description,x.StatusCode,x.CustomerApprovedAt,files,Version(x.RowVersion));}
    private async Task<ProviderInteriorStage> Stage(InteriorWorkStage x,Guid projectId,long userId,bool assigned,CancellationToken token){var files=await Files(projectId,userId,from l in db.InteriorWorkUpdateFiles.AsNoTracking() join u in db.InteriorWorkUpdates.AsNoTracking() on l.WorkUpdateId equals u.Id join f in db.Files.AsNoTracking() on l.FileId equals f.Id where u.WorkStageId==x.Id select f,"STAGE",token);return new(x.PublicId,x.SequenceNo,x.StageName,x.StatusCode,x.ProgressPercent,x.PlannedStartDate,x.PlannedEndDate,assigned,files,Version(x.RowVersion));}
    private async Task<ProviderInteriorInspection> Inspection(InteriorStageInspection x,Guid projectId,long userId,CancellationToken token){var files=await Files(projectId,userId,from l in db.InteriorStageInspectionFiles.AsNoTracking() join f in db.Files.AsNoTracking() on l.FileId equals f.Id where l.StageInspectionId==x.Id select f,"INSPECTION",token);return new(x.PublicId,(await db.InteriorWorkStages.AsNoTracking().SingleAsync(s=>s.Id==x.WorkStageId,token)).PublicId,x.InspectionStatusCode,x.ChecklistJson,x.ResultText,x.RequestedCorrectionText,x.InspectedAt,await db.InteriorStageInspectionAcknowledgements.AsNoTracking().AnyAsync(a=>a.StageInspectionId==x.Id,token),files,Version(x.RowVersion));}
    private async Task<ProviderInteriorChange> Change(InteriorContractChange x,Guid projectId,long userId,CancellationToken token){var files=await Files(projectId,userId,from l in db.InteriorContractChangeFiles.AsNoTracking() join f in db.Files.AsNoTracking() on l.FileId equals f.Id where l.ContractChangeId==x.Id select f,"CHANGE",token);return new(x.PublicId,x.ChangeNo,x.StatusCode,x.ReasonText,x.ScopeChangeText,x.AmountDelta,x.ScheduleImpactDays,files,Version(x.RowVersion));}
    private async Task<ProviderInteriorContract?> Contract(InteriorProject project,long providerId,CancellationToken token){var x=await db.InteriorContracts.AsNoTracking().Where(c=>c.InteriorProjectId==project.Id&&c.ProviderProfileId==providerId).OrderByDescending(c=>c.ContractVersion).FirstOrDefaultAsync(token);if(x==null)return null;var plans=await db.InteriorPaymentPlans.AsNoTracking().Where(p=>p.InteriorContractId==x.Id).OrderBy(p=>p.SequenceNo).Select(p=>new InteriorPaymentPlanResponse(p.PublicId,p.SequenceNo,p.PaymentName,p.PlannedAmount,p.PlannedDueDate,p.StatusCode,db.InteriorPaymentConfirmations.Count(c=>c.PaymentPlanId==p.Id))).ToListAsync(token);return new(x.PublicId,x.ContractVersion,x.StatusCode,x.ContractAmount,x.CurrencyCode,x.PlannedStartDate,x.PlannedCompletionDate,x.CustomerAgreedAt,x.ProviderAgreedAt,x.EffectiveAt,plans);}
    private async Task<IReadOnlyList<ProviderInteriorQuote>> Quotes(InteriorProject project,long providerId,CancellationToken token){var rows=await(from q in db.Quotes.AsNoTracking() join r in db.QuoteRevisions.AsNoTracking() on q.Id equals r.QuoteId where q.ServiceRequestId==project.ServiceRequestId&&q.ProviderProfileId==providerId orderby r.RevisionNo descending select new{q,r}).ToListAsync(token);var result=new List<ProviderInteriorQuote>();foreach(var x in rows){var items=await db.QuoteItems.AsNoTracking().Where(i=>i.QuoteRevisionId==x.r.Id).OrderBy(i=>i.LineNo).Select(i=>i.ItemName+(i.WorkTradeText==null?"":" · "+i.WorkTradeText)+(i.SpaceText==null?"":" · "+i.SpaceText)).ToListAsync(token);result.Add(new(x.r.PublicId,x.q.StatusCode,x.r.RevisionNo,x.r.Summary,x.r.Terms,x.r.TotalAmount,x.r.CurrencyCode,x.r.EstimatedDurationText,x.r.AvailableStartAt,x.r.ValidUntil,items));}return result;}
    private async Task<IReadOnlyList<ProviderInteriorFile>> Files(Guid projectId,long userId,IQueryable<StoredFile> query,string area,CancellationToken token)
    {
        var result=new List<ProviderInteriorFile>();
        foreach(var original in await query.Distinct().ToListAsync(token))
        {
            var publication=await filePublication.ResolveAsync(original,userId,true,true,token);
            var published=publication.PublishedFile??original;
            result.Add(new(original.PublicId,SafeName(published),published.ContentType,published.SizeBytes,publication.PublicationMode,publication.Allowed?$"/api/v1/providers/me/interior/projects/{projectId}/files/{original.PublicId}":null,publication.StatusCode,publication.Allowed?null:publication.Message));
        }
        return result;
    }
    private async Task<bool> FileLinked(long projectId,long fileId,IReadOnlyList<string> roles,long providerId,CancellationToken token){if(roles.Contains("SITE_SURVEY")&&await(from l in db.InteriorSiteVisitFiles join v in db.InteriorSiteVisits on l.SiteVisitId equals v.Id where l.FileId==fileId&&v.InteriorProjectId==projectId&&v.ProviderProfileId==providerId select l).AnyAsync(token))return true;if(roles.Contains("DESIGN")&&await(from l in db.InteriorDesignFiles join d in db.InteriorDesignVersions on l.DesignVersionId equals d.Id where l.FileId==fileId&&d.InteriorProjectId==projectId select l).AnyAsync(token))return true;if((roles.Contains("PRIMARY_CONTRACTOR")||roles.Contains("TRADE_CONTRACTOR"))&&await(from l in db.InteriorWorkUpdateFiles join u in db.InteriorWorkUpdates on l.WorkUpdateId equals u.Id join s in db.InteriorWorkStages on u.WorkStageId equals s.Id where l.FileId==fileId&&s.InteriorProjectId==projectId select l).AnyAsync(token))return true;if(roles.Contains("INSPECTION")&&await(from l in db.InteriorStageInspectionFiles join i in db.InteriorStageInspections on l.StageInspectionId equals i.Id join s in db.InteriorWorkStages on i.WorkStageId equals s.Id where l.FileId==fileId&&s.InteriorProjectId==projectId select l).AnyAsync(token))return true;return roles.Contains("PRIMARY_CONTRACTOR")&&await(from l in db.InteriorContractChangeFiles join c in db.InteriorContractChanges on l.ContractChangeId equals c.Id join contract in db.InteriorContracts on c.InteriorContractId equals contract.Id where l.FileId==fileId&&contract.InteriorProjectId==projectId select l).AnyAsync(token);}
    private async Task<List<StoredFile>> OwnFiles(IReadOnlyList<Guid>? ids,long userId,CancellationToken token){if(ids is null||ids.Count==0)return [];var values=await db.Files.Where(x=>ids.Contains(x.PublicId)&&x.UploadedByUserId==userId&&x.StatusCode=="ACTIVE").ToListAsync(token);if(values.Count!=ids.Distinct().Count())throw new InteriorBusinessException(403,"INTERIOR_FILE_OWNERSHIP_INVALID","본인이 업로드한 활성 파일만 연결할 수 있습니다.");return values;}
    private async Task<int> ActiveRoleCount(long providerId,string role,CancellationToken token){var now=DateTime.UtcNow;return await db.InteriorProjectParticipants.CountAsync(x=>x.ProviderProfileId==providerId&&x.RoleCode==role&&x.StatusCode=="ACTIVE"&&x.EffectiveFrom<=now&&(x.EffectiveTo==null||x.EffectiveTo>now),token);}
    private async Task<int> Pending(long projectId,long providerId,IReadOnlyList<string> roles,CancellationToken token){var count=0;if(roles.Contains("SITE_SURVEY"))count+=await db.InteriorSiteVisits.CountAsync(x=>x.InteriorProjectId==projectId&&x.ProviderProfileId==providerId&&x.StatusCode=="CONFIRMED"&&x.CompletedAt==null,token);if(roles.Contains("PRIMARY_CONTRACTOR")||roles.Contains("TRADE_CONTRACTOR"))count+=(await AccessibleStages(providerId,[projectId],token)).Count(x=>x.Stage.StatusCode!="COMPLETED");return count;}
    private async Task Record(InteriorProject project,string type,string key,long userId,object data,CancellationToken token){if(string.IsNullOrWhiteSpace(key))throw Bad("IDEMPOTENCY_KEY_REQUIRED","중복 실행 방지 키가 필요합니다.");if(await EventExists(key,token))return;var now=DateTime.UtcNow;db.InteriorProjectEvents.Add(new(){InteriorProjectId=project.Id,EventTypeCode=type,ActorUserId=userId,IdempotencyKey=key.Trim(),EventDataJson=JsonSerializer.Serialize(data),OccurredAt=now,CreatedAt=now});db.AuditLogs.Add(new(){OccurredAt=now,ActorUserId=userId,ActorRoleCode=RoleCodes.Provider,ActionCode=$"INTERIOR_{type}",EntityType="INTERIOR_PROJECT",EntityPublicId=project.PublicId,ResultCode="SUCCESS",AfterJson=JsonSerializer.Serialize(data)});if(await db.NotificationTemplates.AsNoTracking().AnyAsync(x=>x.EventTypeCode==type&&x.IsActive,token))db.OutboxEvents.Add(new(){AggregateType="INTERIOR_PROJECT",AggregatePublicId=project.PublicId,EventType=type,PayloadJson=JsonSerializer.Serialize(new{sourceId=project.PublicId}),StatusCode="PENDING",OccurredAt=now,AvailableAt=now,IdempotencyKey=$"provider-interior:{type.ToLowerInvariant()}:{key.Trim()}",CreatedByUserId=userId});}
    private Task<bool> EventExists(string key,CancellationToken token)=>db.InteriorProjectEvents.AsNoTracking().AnyAsync(x=>x.IdempotencyKey==key.Trim(),token);
    private void ApplyVersion(object entity,string? value){var entry=db.Entry(entity);var current=(byte[]?)entry.Property("RowVersion").CurrentValue??[];if(string.IsNullOrWhiteSpace(value)){if(current.Length>0)throw Bad("ROW_VERSION_REQUIRED","최신 변경 버전 값이 필요합니다.");return;}try{entry.Property("RowVersion").OriginalValue=Convert.FromBase64String(value);}catch(FormatException){throw Bad("ROW_VERSION_INVALID","변경 버전 값이 올바르지 않습니다.");}}
    private async Task Save(CancellationToken token){try{await db.SaveChangesAsync(token);}catch(DbUpdateConcurrencyException){throw Conflict("ROW_VERSION_CONFLICT","다른 사용자가 먼저 변경했습니다. 새로고침 후 다시 시도해 주세요.");}}
    private async Task<ProviderIdentity> Provider(ClaimsPrincipal principal,CancellationToken token){if(!Guid.TryParse(principal.FindFirstValue(ClaimTypes.NameIdentifier),out var id))throw new InteriorBusinessException(403,"AUTHENTICATION_REQUIRED","로그인이 필요합니다.");return await(from u in db.Users.AsNoTracking() join p in db.ProviderProfiles.AsNoTracking() on u.Id equals p.UserId where u.PublicId==id&&u.StatusCode=="ACTIVE" select new ProviderIdentity(u.Id,p.Id,u.PublicId)).SingleOrDefaultAsync(token)??throw new InteriorBusinessException(403,"PROVIDER_PROFILE_REQUIRED","공급자 프로필이 필요합니다.");}
    private static async Task<ValidatedUpload> ValidateUpload(IFormFile upload,CancellationToken token){if(upload.Length is <=0 or >MaxFileSize)throw Bad("INTERIOR_FILE_SIZE_INVALID","파일은 10MB 이하만 등록할 수 있습니다.");var name=Path.GetFileName(upload.FileName);if(string.IsNullOrWhiteSpace(name)||name!=upload.FileName||name.Length>255)throw Bad("INTERIOR_FILE_NAME_INVALID","안전한 파일명을 사용해 주세요.");var ext=Path.GetExtension(name).ToLowerInvariant();var type=upload.ContentType.ToLowerInvariant();if((type,ext) is not(("image/jpeg",".jpg")or("image/jpeg",".jpeg")or("image/png",".png")or("application/pdf",".pdf")))throw Bad("INTERIOR_FILE_TYPE_INVALID","JPG, PNG, PDF 파일만 등록할 수 있습니다.");await using var input=upload.OpenReadStream();using var ms=new MemoryStream();await input.CopyToAsync(ms,token);var bytes=ms.ToArray();var valid=type switch{"image/jpeg"=>bytes.Length>=3&&bytes[0]==0xff&&bytes[1]==0xd8&&bytes[2]==0xff,"image/png"=>bytes.Length>=8&&bytes.AsSpan(0,8).SequenceEqual(new byte[]{137,80,78,71,13,10,26,10}),"application/pdf"=>bytes.Length>=5&&bytes.AsSpan(0,5).SequenceEqual("%PDF-"u8),_=>false};if(!valid)throw Bad("INTERIOR_FILE_SIGNATURE_INVALID","파일 확장자와 실제 형식이 일치하지 않습니다.");return new(bytes,ext);}
    private static string NextAction(InteriorProject p,IReadOnlyList<string> roles)=>roles.Contains("SITE_SURVEY")&&p.StatusCode=="SITE_VISIT_SCHEDULED"?"실측 결과 등록":roles.Contains("DESIGN")?"설계 버전 확인":roles.Contains("INSPECTION")?"검사 업무 확인":roles.Contains("PRIMARY_CONTRACTOR")?"공정·계약 확인":"배정 업무 확인";
    private static DateTime? NextAt(InteriorProject p)=>p.ExpectedCompletionDate?.ToDateTime(TimeOnly.MinValue);
    private static string Number(Guid id)=>$"IN-{id.ToString("N")[..8].ToUpperInvariant()}";
    private static string Version(byte[] value)=>value.Length==0?string.Empty:Convert.ToBase64String(value);
    private static string? Clean(string? value)=>string.IsNullOrWhiteSpace(value)?null:value.Trim();
    private static string SafeName(StoredFile f)=>"interior-evidence"+(f.ContentType switch{"image/jpeg"=>".jpg","image/png"=>".png","application/pdf"=>".pdf",_=>".bin"});
    private static InteriorBusinessException Bad(string code,string message)=>new(400,code,message);
    private static InteriorBusinessException NotFound()=>new(404,"INTERIOR_PROJECT_NOT_FOUND","담당 인테리어 업무를 찾을 수 없습니다.");
    private static InteriorBusinessException Conflict(string code,string message)=>new(409,code,message);
    private sealed record ProviderIdentity(long UserId,long ProviderId,Guid PublicUserId);
    private sealed record ContactResult(bool Allowed,string? Phone,string? Address,string Policy);
    private sealed record ValidatedUpload(byte[] Bytes,string Extension);
    private sealed record StageRow(InteriorWorkStage Stage,bool Assigned);
}
