using System.Net;
using System.Net.Http.Json;
using Microsoft.AspNetCore.Mvc.Testing;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.DependencyInjection;
using SoodalLife.Api.Domain.Entities;
using SoodalLife.Api.Features.Authentication;
using SoodalLife.Api.Features.Subscriptions;
using SoodalLife.Api.Infrastructure.Persistence;

namespace SoodalLife.Api.Tests;

public sealed class CareSubscriptionCoreApiTests(AuthenticationWebApplicationFactory factory):IClassFixture<AuthenticationWebApplicationFactory>
{
    [Fact]
    public async Task Admin_ListsEligibleServices_CreatesProduct_AndRejectsOtherRoles()
    {
        await EnableSubscription();using var admin=Client();using var customer=Client();using var provider=Client();await Login(admin,factory.Credentials[RoleCodes.Admin]);await Login(customer,factory.Credentials[RoleCodes.Customer]);await Login(provider,factory.Credentials[RoleCodes.Provider]);
        var services=await admin.GetFromJsonAsync<List<SubscriptionServiceItem>>("/api/v1/admin/subscriptions/eligible-services");Assert.Contains(services!,x=>x.Id==factory.Catalog.ServiceId);
        var response=await admin.PostAsJsonAsync("/api/v1/admin/subscriptions/products",new{serviceCategoryId=factory.Catalog.ServiceId,productName="월간 생활 점검",description="정기 방문 점검 상품",serviceScopeText="월 1회 기본 생활 점검",visitsPerPeriod=1,expectedDurationMinutes=60,billingPeriodCode="MONTHLY",standardMonthlyAmount=(decimal?)null,standardVisitAmount=(decimal?)null,effectiveFrom=DateOnly.FromDateTime(DateTime.Today),effectiveTo=(DateOnly?)null,isActive=true});
        Assert.Equal(HttpStatusCode.OK,response.StatusCode);var product=await response.Content.ReadFromJsonAsync<CareProductResponse>();Assert.Equal("월간 생활 점검",product!.ProductName);Assert.Null(product.StandardMonthlyAmount);
        Assert.Equal(HttpStatusCode.Forbidden,(await customer.GetAsync("/api/v1/admin/subscriptions/products")).StatusCode);Assert.Equal(HttpStatusCode.Forbidden,(await provider.GetAsync("/api/v1/admin/subscriptions/products")).StatusCode);
    }

    [Fact]
    public async Task Request_SupportsStandardAndCustom_WithStructuredRecurrence_AndHidesPrivacy()
    {
        await EnableSubscription();using var admin=Client();using var customer=Client();using var provider=Client();await Login(admin,factory.Credentials[RoleCodes.Admin]);await Login(customer,factory.Credentials[RoleCodes.Customer]);await Login(provider,factory.Credentials[RoleCodes.Provider]);var product=await CreateProduct(admin);
        var standard=await CreateRequest(customer,"STANDARD",product.Id);var custom=await CreateRequest(customer,"CUSTOM",null,"서울시 상세주소 101동 202호");Assert.Equal("WEEKLY",standard.Recurrence.FrequencyTypeCode);Assert.Equal(2,standard.Recurrence.Weekdays.Count);Assert.Null(custom.CareProductId);
        var application=await Apply(provider,custom.Id,"privacy");Assert.NotNull(application);var body=await (await customer.GetAsync($"/api/v1/subscriptions/requests/{custom.Id}/applications")).Content.ReadAsStringAsync();Assert.DoesNotContain("상세주소",body);Assert.DoesNotContain("\"phone\"",body,StringComparison.OrdinalIgnoreCase);
    }

    [Fact]
    public async Task ProviderApplication_ValidatesApprovalServiceArea_Requirements_AndDuplicate()
    {
        await ResetNegativeProviders();
        await EnableSubscription();using var customer=Client();using var provider=Client();using var inactive=Client();using var mismatch=Client();using var area=Client();await Login(customer,factory.Credentials[RoleCodes.Customer]);await Login(provider,factory.Credentials[RoleCodes.Provider]);await Login(inactive,factory.InactiveProviderCredential);await Login(mismatch,factory.ServiceMismatchProviderCredential);await Login(area,factory.AreaMismatchProviderCredential);var request=await CreateRequest(customer,"CUSTOM",null);
        Assert.Equal(HttpStatusCode.OK,(await ApplyRaw(provider,request.Id,"valid")).StatusCode);Assert.Equal(HttpStatusCode.Conflict,(await ApplyRaw(provider,request.Id,"duplicate")).StatusCode);Assert.Equal(HttpStatusCode.Forbidden,(await ApplyRaw(inactive,request.Id,"inactive")).StatusCode);Assert.Equal(HttpStatusCode.Forbidden,(await ApplyRaw(mismatch,request.Id,"service")).StatusCode);Assert.Equal(HttpStatusCode.Forbidden,(await ApplyRaw(area,request.Id,"area")).StatusCode);
    }

    [Fact]
    public async Task Selection_CreatesSingleContract_Snapshots_Visits_AndNeverDebitsWallet()
    {
        var flow=await CreateFlow();using var scope=factory.Services.CreateScope();var db=scope.ServiceProvider.GetRequiredService<SoodalLifeDbContext>();var provider=await db.ProviderProfiles.SingleAsync(x=>x.PublicId==flow.Application.ProviderId);var wallet=await db.ProviderWallets.SingleAsync(x=>x.ProviderProfileId==provider.Id);var before=wallet.AvailableBalance;
        var customerUser=await(from user in db.Users join customer in db.CustomerProfiles on user.Id equals customer.UserId where customer.Id==db.SubscriptionContracts.Single(x=>x.PublicId==flow.Contract.Id).CustomerProfileId select user).SingleAsync();customerUser.Phone="010-2468-1357";await db.SaveChangesAsync();var privateDetail=await flow.Provider.GetFromJsonAsync<ProviderSubscriptionContractDetail>($"/api/v1/subscriptions/providers/me/contracts/{flow.Contract.Id}");Assert.Equal("010-2468-1357",privateDetail!.CustomerPhone);Assert.Equal("서울시 상세주소",privateDetail.DetailAddress);using var other=Client();await Login(other,factory.ServiceMismatchProviderCredential);Assert.Equal(HttpStatusCode.NotFound,(await other.GetAsync($"/api/v1/subscriptions/providers/me/contracts/{flow.Contract.Id}")).StatusCode);
        using var admin=Client();await Login(admin,factory.Credentials[RoleCodes.Admin]);Assert.Contains((await admin.GetFromJsonAsync<List<AdminSubscriptionApplicationResponse>>("/api/v1/admin/subscriptions/applications"))!,x=>x.Id==flow.Application.Id);Assert.Contains((await admin.GetFromJsonAsync<List<SubscriptionContractResponse>>("/api/v1/admin/subscriptions/contracts"))!,x=>x.Id==flow.Contract.Id);
        Assert.Equal("ACTIVE",flow.Contract.StatusCode);Assert.Contains("monthlyAmount",flow.Contract.PriceSnapshotJson);Assert.Null(flow.Contract.FeePolicySnapshotJson);Assert.NotEmpty(flow.Contract.RecurrenceSnapshotJson);Assert.NotEmpty(await db.SubscriptionVisitSchedules.Where(x=>x.SubscriptionContractId==db.SubscriptionContracts.Single(c=>c.PublicId==flow.Contract.Id).Id).ToListAsync());Assert.Equal(before,wallet.AvailableBalance);Assert.Empty(await db.FeeCharges.Where(x=>x.CreatedAt>=flow.Contract.StartedAt).ToListAsync());
        var repeated=await flow.Customer.PostAsJsonAsync($"/api/v1/subscriptions/requests/{flow.Request.Id}/selection",new{applicationId=flow.Application.Id,idempotencyKey="different-selection"});Assert.Equal(HttpStatusCode.Conflict,repeated.StatusCode);
    }

    [Fact]
    public async Task ContractOperations_PauseResumeTerminate_SkipAndReschedule_PreserveHistory()
    {
        var flow=await CreateFlow();using var admin=Client();await Login(admin,factory.Credentials[RoleCodes.Admin]);var visits=await admin.GetFromJsonAsync<List<SubscriptionVisitResponse>>("/api/v1/admin/subscriptions/visits");var visit=visits!.First(x=>x.ContractId==flow.Contract.Id);
        var change=await flow.Customer.PostAsJsonAsync($"/api/v1/subscriptions/visits/{visit.Id}/schedule-changes",new{scheduledStartAt=visit.ScheduledStartAt.AddDays(1),scheduledEndAt=visit.ScheduledEndAt?.AddDays(1),reason="고객 일정 변경",idempotencyKey=$"change-{Guid.NewGuid():N}"});Assert.Equal(HttpStatusCode.OK,change.StatusCode);
        Assert.Equal(HttpStatusCode.OK,(await admin.PostAsJsonAsync($"/api/v1/admin/subscriptions/visits/{visit.Id}/skip",new{idempotencyKey=$"skip-{Guid.NewGuid():N}"})).StatusCode);
        Assert.Equal("PAUSED",(await State(admin,flow.Contract.Id,"pause")).StatusCode);Assert.Equal("ACTIVE",(await State(admin,flow.Contract.Id,"resume")).StatusCode);Assert.Equal("TERMINATED",(await State(admin,flow.Contract.Id,"terminate")).StatusCode);
        using var scope=factory.Services.CreateScope();var db=scope.ServiceProvider.GetRequiredService<SoodalLifeDbContext>();Assert.Contains(await db.SubscriptionEvents.Where(x=>x.SubscriptionContractId==db.SubscriptionContracts.Single(c=>c.PublicId==flow.Contract.Id).Id).ToListAsync(),x=>x.EventTypeCode=="PAUSED");Assert.Contains(await db.SubscriptionEvents.ToListAsync(),x=>x.EventTypeCode=="RESUMED");Assert.Contains(await db.SubscriptionEvents.ToListAsync(),x=>x.EventTypeCode=="TERMINATION_REQUESTED");
    }

    [Fact]
    public async Task ScheduleChanges_RequireCounterpartyDecision_AndAdminForceReason_WithAuditEvents()
    {
        var flow=await CreateFlow();using var admin=Client();await Login(admin,factory.Credentials[RoleCodes.Admin]);var visit=(await admin.GetFromJsonAsync<List<SubscriptionVisitResponse>>("/api/v1/admin/subscriptions/visits"))!.First(x=>x.ContractId==flow.Contract.Id&&x.ScheduledStartAt>DateTime.UtcNow);
        var customerRequest=await flow.Customer.PostAsJsonAsync($"/api/v1/subscriptions/visits/{visit.Id}/schedule-changes",new{scheduledStartAt=visit.ScheduledStartAt.AddDays(1),scheduledEndAt=visit.ScheduledEndAt?.AddDays(1),reason="고객 일정",idempotencyKey=$"request-c-{Guid.NewGuid():N}"});Assert.Equal(HttpStatusCode.OK,customerRequest.StatusCode);var customerChange=(await customerRequest.Content.ReadFromJsonAsync<SubscriptionScheduleChangeResponse>())!;Assert.Equal(HttpStatusCode.NotFound,(await flow.Customer.PostAsJsonAsync($"/api/v1/subscriptions/schedule-changes/{customerChange.Id}/decision",new{approve=true,idempotencyKey=$"self-{Guid.NewGuid():N}",rowVersion=(string?)null})).StatusCode);var providerDecision=await flow.Provider.PostAsJsonAsync($"/api/v1/subscriptions/schedule-changes/{customerChange.Id}/decision",new{approve=true,idempotencyKey=$"decision-p-{Guid.NewGuid():N}",rowVersion=(string?)null});Assert.Equal(HttpStatusCode.OK,providerDecision.StatusCode);Assert.Equal("APPROVED",(await providerDecision.Content.ReadFromJsonAsync<SubscriptionScheduleChangeResponse>())!.StatusCode);
        var providerRequest=await flow.Provider.PostAsJsonAsync($"/api/v1/subscriptions/visits/{visit.Id}/schedule-changes",new{scheduledStartAt=visit.ScheduledStartAt.AddDays(2),scheduledEndAt=visit.ScheduledEndAt?.AddDays(2),reason="전문가 일정",idempotencyKey=$"request-p-{Guid.NewGuid():N}"});var providerChange=(await providerRequest.Content.ReadFromJsonAsync<SubscriptionScheduleChangeResponse>())!;var customerDecision=await flow.Customer.PostAsJsonAsync($"/api/v1/subscriptions/schedule-changes/{providerChange.Id}/decision",new{approve=false,idempotencyKey=$"decision-c-{Guid.NewGuid():N}",rowVersion=(string?)null});Assert.Equal(HttpStatusCode.OK,customerDecision.StatusCode);Assert.Equal("REJECTED",(await customerDecision.Content.ReadFromJsonAsync<SubscriptionScheduleChangeResponse>())!.StatusCode);
        var forcedRequest=await flow.Customer.PostAsJsonAsync($"/api/v1/subscriptions/visits/{visit.Id}/schedule-changes",new{scheduledStartAt=visit.ScheduledStartAt.AddDays(3),scheduledEndAt=visit.ScheduledEndAt?.AddDays(3),reason="관리자 확인 요청",idempotencyKey=$"request-f-{Guid.NewGuid():N}"});var forcedChange=(await forcedRequest.Content.ReadFromJsonAsync<SubscriptionScheduleChangeResponse>())!;Assert.Equal(HttpStatusCode.BadRequest,(await admin.PostAsJsonAsync($"/api/v1/admin/subscriptions/schedule-changes/{forcedChange.Id}/force-decision",new{approve=true,reason="",idempotencyKey=$"force-empty-{Guid.NewGuid():N}",rowVersion=(string?)null})).StatusCode);Assert.Equal(HttpStatusCode.Conflict,(await admin.PostAsJsonAsync($"/api/v1/admin/subscriptions/schedule-changes/{forcedChange.Id}/force-decision",new{approve=false,reason="당사자 응답 지연에 따른 운영 결정",idempotencyKey=$"force-early-{Guid.NewGuid():N}",rowVersion=(string?)null})).StatusCode);using(var ageScope=factory.Services.CreateScope()){var ageDb=ageScope.ServiceProvider.GetRequiredService<SoodalLifeDbContext>();var ageItem=await ageDb.SubscriptionScheduleChanges.SingleAsync(x=>x.PublicId==forcedChange.Id);ageItem.RequestedAt=DateTime.UtcNow.AddHours(-49);await ageDb.SaveChangesAsync();}Assert.Equal(HttpStatusCode.OK,(await admin.PostAsJsonAsync($"/api/v1/admin/subscriptions/schedule-changes/{forcedChange.Id}/force-decision",new{approve=false,reason="당사자 응답 지연에 따른 운영 결정",idempotencyKey=$"force-{Guid.NewGuid():N}",rowVersion=(string?)null})).StatusCode);
        using var scope=factory.Services.CreateScope();var db=scope.ServiceProvider.GetRequiredService<SoodalLifeDbContext>();Assert.Contains(await db.SubscriptionEvents.ToListAsync(),x=>x.EventTypeCode=="SCHEDULE_CHANGE_APPROVED");Assert.Contains(await db.SubscriptionEvents.ToListAsync(),x=>x.EventTypeCode=="SCHEDULE_CHANGE_REJECTED");Assert.Contains(await db.SubscriptionEvents.ToListAsync(),x=>x.EventTypeCode=="SCHEDULE_CHANGE_FORCE_REJECTED");Assert.Contains(await db.AuditLogs.ToListAsync(),x=>x.EntityPublicId==customerChange.Id&&x.ActionCode=="SCHEDULE_CHANGE_APPROVED");Assert.Contains(await db.AuditLogs.ToListAsync(),x=>x.EntityPublicId==forcedChange.Id&&x.Reason=="당사자 응답 지연에 따른 운영 결정");
    }

    [Fact]
    public async Task ProviderReplacement_ChangesFutureVisitsOnly_AndRequiresEligibility()
    {
        var flow=await CreateFlow();using var admin=Client();await Login(admin,factory.Credentials[RoleCodes.Admin]);var replacement=await MakeAreaMismatchProviderEligible();using var scope=factory.Services.CreateScope();var db=scope.ServiceProvider.GetRequiredService<SoodalLifeDbContext>();var contract=await db.SubscriptionContracts.SingleAsync(x=>x.PublicId==flow.Contract.Id);var first=await db.SubscriptionVisitSchedules.Where(x=>x.SubscriptionContractId==contract.Id).OrderBy(x=>x.VisitNo).FirstAsync();first.ScheduledStartAt=DateTime.UtcNow.AddDays(-1);var oldProvider=first.ProviderProfileId;await db.SaveChangesAsync();
        var response=await admin.PostAsJsonAsync($"/api/v1/admin/subscriptions/contracts/{flow.Contract.Id}/provider",new{providerId=replacement,reason="운영상 전문가 교체",idempotencyKey=$"replace-{Guid.NewGuid():N}",rowVersion=(string?)null});Assert.Equal(HttpStatusCode.OK,response.StatusCode);db.ChangeTracker.Clear();Assert.Equal(oldProvider,(await db.SubscriptionVisitSchedules.SingleAsync(x=>x.Id==first.Id)).ProviderProfileId);Assert.All(await db.SubscriptionVisitSchedules.Where(x=>x.SubscriptionContractId==contract.Id&&x.ScheduledStartAt>=DateTime.UtcNow).ToListAsync(),x=>Assert.NotEqual(oldProvider,x.ProviderProfileId));
    }

    [Fact]
    public async Task Completion_Confirmation_ReviewAfterServiceDispute_AndHistory_AreVisitBased()
    {
        var flow=await CreateFlow();using var admin=Client();await Login(admin,factory.Credentials[RoleCodes.Admin]);var visit=(await admin.GetFromJsonAsync<List<SubscriptionVisitResponse>>("/api/v1/admin/subscriptions/visits"))!.First(x=>x.ContractId==flow.Contract.Id);var scheduledAttempt=await flow.Provider.PostAsJsonAsync($"/api/v1/subscriptions/visits/{visit.Id}/completion",new{verificationMethodCode="AUTH_CODE",verificationResultCode="VERIFIED",checklistJson="{}",completionNote="잘못된 상태의 완료 시도",fileIds=Array.Empty<Guid>(),idempotencyKey=$"scheduled-complete-{Guid.NewGuid():N}",rowVersion=(string?)null});Assert.Equal(HttpStatusCode.Conflict,scheduledAttempt.StatusCode);Guid[] completionFiles;
        using(var prepareScope=factory.Services.CreateScope()){var prepare=prepareScope.ServiceProvider.GetRequiredService<SoodalLifeDbContext>();var preparedVisit=await prepare.SubscriptionVisitSchedules.SingleAsync(x=>x.PublicId==visit.Id);var providerUser=await prepare.ProviderProfiles.Where(x=>x.Id==preparedVisit.ProviderProfileId).Select(x=>x.UserId).SingleAsync();preparedVisit.StatusCode="IN_PROGRESS";var now=DateTime.UtcNow;var files=Enumerable.Range(1,2).Select(index=>new StoredFile{PurposeCode="SUBSCRIPTION_COMPLETION",StorageContainer="test",StorageKey=$"subscription/{Guid.NewGuid():N}.jpg",StorageKeyHash=System.Security.Cryptography.SHA256.HashData(Guid.NewGuid().ToByteArray()),OriginalFileName=$"완료사진-{index}.jpg",ContentType="image/jpeg",SizeBytes=1024,Sha256Hex=new string('a',64),StatusCode="ACTIVE",ActivatedAt=now,UploadedByUserId=providerUser,CreatedAt=now}).ToArray();prepare.Files.AddRange(files);await prepare.SaveChangesAsync();completionFiles=files.Select(x=>x.PublicId).ToArray();}
        var complete=await flow.Provider.PostAsJsonAsync($"/api/v1/subscriptions/visits/{visit.Id}/completion",new{verificationMethodCode="AUTH_CODE",verificationResultCode="VERIFIED",checklistJson="{\"basicCheck\":true}",completionNote="정기 점검을 완료했습니다.",fileIds=completionFiles,idempotencyKey=$"complete-{Guid.NewGuid():N}",rowVersion=(string?)null});Assert.Equal(HttpStatusCode.OK,complete.StatusCode);
        var confirmed=await flow.Customer.PostAsJsonAsync($"/api/v1/subscriptions/visits/{visit.Id}/confirmation",new{idempotencyKey=$"confirm-{Guid.NewGuid():N}",rowVersion=(string?)null});Assert.Equal(HttpStatusCode.OK,confirmed.StatusCode);Assert.Equal("READY",(await confirmed.Content.ReadFromJsonAsync<SubscriptionVisitResponse>())!.SettlementStatusCode);
        Assert.Equal(HttpStatusCode.OK,(await flow.Customer.PostAsJsonAsync($"/api/v1/subscriptions/visits/{visit.Id}/review",new{bodyText="약속한 시간에 꼼꼼하게 점검해 주셨습니다.",overallRating=5m,idempotencyKey=$"review-{Guid.NewGuid():N}"})).StatusCode);Assert.Equal(HttpStatusCode.OK,(await flow.Customer.PostAsJsonAsync($"/api/v1/subscriptions/visits/{visit.Id}/after-service",new{subject="점검 후 확인 요청",description="추가 확인이 필요한 부분이 있습니다.",idempotencyKey=$"as-{Guid.NewGuid():N}"})).StatusCode);Assert.Equal(HttpStatusCode.OK,(await flow.Customer.PostAsJsonAsync($"/api/v1/subscriptions/visits/{visit.Id}/dispute",new{subject="회차 처리 확인 요청",description="본사 확인이 필요한 내용입니다.",idempotencyKey=$"dispute-{Guid.NewGuid():N}"})).StatusCode);
        using var scope=factory.Services.CreateScope();var db=scope.ServiceProvider.GetRequiredService<SoodalLifeDbContext>();var visitRow=await db.SubscriptionVisitSchedules.SingleAsync(x=>x.PublicId==visit.Id);Assert.Equal("NOT_INTEGRATED",visitRow.GpsVerificationStatusCode);Assert.Equal("NOT_INTEGRATED",visitRow.PossessionVerificationStatusCode);Assert.Equal("NOT_INTEGRATED",visitRow.VisitVerificationStatusCode);Assert.Single(await db.Reviews.Where(x=>x.SubscriptionVisitScheduleId==visitRow.Id&&x.TransactionId==null).ToListAsync());Assert.Single(await db.AfterServiceCases.Where(x=>x.SubscriptionVisitScheduleId==visitRow.Id&&x.TransactionId==null).ToListAsync());Assert.Single(await db.DisputeCases.Where(x=>x.SubscriptionVisitScheduleId==visitRow.Id&&x.TransactionId==null).ToListAsync());Assert.Single(await db.ServiceHistoryEntries.Where(x=>x.SubscriptionVisitScheduleId==visitRow.Id).ToListAsync());Assert.Equal("HOLD",visitRow.SettlementStatusCode);
    }

    [Fact]
    public async Task SubscriptionEvents_AreIdempotentAppendOnly_AndGeneralTransactionsRemainUnchanged()
    {
        using var scope0=factory.Services.CreateScope();var db0=scope0.ServiceProvider.GetRequiredService<SoodalLifeDbContext>();var txBefore=await db0.Transactions.CountAsync();var requestBefore=await db0.ServiceRequests.CountAsync();var walletLedgerBefore=await db0.WalletLedgerEntries.CountAsync();var flow=await CreateFlow();using var scope=factory.Services.CreateScope();var db=scope.ServiceProvider.GetRequiredService<SoodalLifeDbContext>();Assert.Equal(txBefore,await db.Transactions.CountAsync());Assert.Equal(requestBefore,await db.ServiceRequests.CountAsync());Assert.Equal(walletLedgerBefore,await db.WalletLedgerEntries.CountAsync());var item=await db.SubscriptionEvents.FirstAsync(x=>x.SubscriptionContractId==db.SubscriptionContracts.Single(c=>c.PublicId==flow.Contract.Id).Id);item.EventDataJson="수정 시도";await Assert.ThrowsAsync<InvalidOperationException>(()=>db.SaveChangesAsync());
        var keys=await db.SubscriptionEvents.Select(x=>x.IdempotencyKey).ToListAsync();Assert.Equal(keys.Count,keys.Distinct().Count());
    }

    private async Task<Flow> CreateFlow(){await EnableSubscription();var customer=Client();var provider=Client();await Login(customer,factory.Credentials[RoleCodes.Customer]);await Login(provider,factory.Credentials[RoleCodes.Provider]);var request=await CreateRequest(customer,"CUSTOM",null);var application=await Apply(provider,request.Id,$"application-{Guid.NewGuid():N}");var response=await customer.PostAsJsonAsync($"/api/v1/subscriptions/requests/{request.Id}/selection",new{applicationId=application.Id,idempotencyKey=$"select-{Guid.NewGuid():N}"});Assert.Equal(HttpStatusCode.OK,response.StatusCode);var pending=(await response.Content.ReadFromJsonAsync<SubscriptionContractResponse>())!;Assert.Equal("PAYMENT_PENDING",pending.StatusCode);using(var scope=factory.Services.CreateScope()){var db=scope.ServiceProvider.GetRequiredService<SoodalLifeDbContext>();var contractId=await db.SubscriptionContracts.Where(x=>x.PublicId==pending.Id).Select(x=>x.Id).SingleAsync();Assert.Empty(await db.SubscriptionVisitSchedules.Where(x=>x.SubscriptionContractId==contractId).ToListAsync());}using var admin=Client();await Login(admin,factory.Credentials[RoleCodes.Admin]);var payment=(await admin.GetFromJsonAsync<List<SubscriptionPaymentResponse>>("/api/v1/admin/subscription-accounting/payments"))!.First(x=>x.ContractId==pending.Id&&x.StatusCode=="REQUESTED");var confirmed=await admin.PostAsJsonAsync($"/api/v1/admin/subscription-accounting/payments/{payment.Id}/development-confirmation",new{idempotencyKey=$"confirm-initial-{Guid.NewGuid():N}",externalPaymentReference="TEST",rowVersion=payment.RowVersion});Assert.Equal(HttpStatusCode.OK,confirmed.StatusCode);var active=(await admin.GetFromJsonAsync<List<SubscriptionContractResponse>>("/api/v1/admin/subscriptions/contracts"))!.Single(x=>x.Id==pending.Id);Assert.Equal("ACTIVE",active.StatusCode);return new(customer,provider,request,application,active);}
    private async Task<SubscriptionRequestResponse> CreateRequest(HttpClient customer,string type,Guid? product,string detail="서울시 상세주소") {var response=await customer.PostAsJsonAsync("/api/v1/subscriptions/requests",new{serviceCategoryId=factory.Catalog.ServiceId,careProductId=product,administrativeAreaId=factory.Catalog.AreaId,requestTypeCode=type,requestedScopeText="정기적으로 꼼꼼한 생활 점검을 요청합니다.",preferredStartDate=DateOnly.FromDateTime(DateTime.Today.AddDays(2)),detailAddress=detail,recurrence=new{frequencyTypeCode="WEEKLY",intervalValue=1,visitsPerPeriod=2,weekdays=new[]{1,4},preferredTimeFrom=new TimeOnly(10,0),preferredTimeTo=new TimeOnly(11,0),expectedDurationMinutes=60,startDate=DateOnly.FromDateTime(DateTime.Today.AddDays(2)),endDate=(DateOnly?)null}});Assert.Equal(HttpStatusCode.OK,response.StatusCode);return(await response.Content.ReadFromJsonAsync<SubscriptionRequestResponse>())!;}
    private static async Task<SubscriptionApplicationResponse> Apply(HttpClient provider,Guid request,string key){var response=await ApplyRaw(provider,request,key);Assert.Equal(HttpStatusCode.OK,response.StatusCode);return(await response.Content.ReadFromJsonAsync<SubscriptionApplicationResponse>())!;}
    private static Task<HttpResponseMessage> ApplyRaw(HttpClient provider,Guid request,string key)=>provider.PostAsJsonAsync($"/api/v1/subscriptions/requests/{request}/applications",new{proposedScopeText="요청 범위 전체 정기 방문",proposedMonthlyAmount=120000m,proposedVisitAmount=30000m,availableScheduleText="매주 월요일과 목요일 오전",idempotencyKey=key});
    private async Task<CareProductResponse> CreateProduct(HttpClient admin){var response=await admin.PostAsJsonAsync("/api/v1/admin/subscriptions/products",new{serviceCategoryId=factory.Catalog.ServiceId,productName=$"표준 점검 {Guid.NewGuid():N}",description="표준 구독상품",serviceScopeText="기본 점검",visitsPerPeriod=2,expectedDurationMinutes=60,billingPeriodCode="MONTHLY",standardMonthlyAmount=100000m,standardVisitAmount=25000m,effectiveFrom=DateOnly.FromDateTime(DateTime.Today),effectiveTo=(DateOnly?)null,isActive=true});Assert.Equal(HttpStatusCode.OK,response.StatusCode);return(await response.Content.ReadFromJsonAsync<CareProductResponse>())!;}
    private static async Task<SubscriptionContractResponse> State(HttpClient admin,Guid id,string action){var response=await admin.PostAsJsonAsync($"/api/v1/admin/subscriptions/contracts/{id}/{action}",new{reason=$"{action} 테스트",resumePlannedAt=(DateTime?)null,idempotencyKey=$"{action}-{Guid.NewGuid():N}",rowVersion=(string?)null});Assert.Equal(HttpStatusCode.OK,response.StatusCode);return(await response.Content.ReadFromJsonAsync<SubscriptionContractResponse>())!;}
    private async Task EnableSubscription(){using var scope=factory.Services.CreateScope();var db=scope.ServiceProvider.GetRequiredService<SoodalLifeDbContext>();var category=await db.ServiceCategories.SingleAsync(x=>x.PublicId==factory.Catalog.ServiceId);var policy=await db.CategoryOperationPolicies.SingleAsync(x=>x.CategoryId==category.Id);policy.SubscriptionOptionText="허용";await db.SaveChangesAsync();}
    private async Task<Guid> MakeAreaMismatchProviderEligible(){using var scope=factory.Services.CreateScope();var db=scope.ServiceProvider.GetRequiredService<SoodalLifeDbContext>();var provider=await(from user in db.Users join p in db.ProviderProfiles on user.Id equals p.UserId where user.LoginId==factory.AreaMismatchProviderCredential.LoginId select p).SingleAsync();var service=await db.ProviderServiceCategories.SingleAsync(x=>x.ProviderProfileId==provider.Id&&x.CategoryId==db.ServiceCategories.Single(c=>c.PublicId==factory.Catalog.ServiceId).Id);var area=await db.AdministrativeAreas.SingleAsync(x=>x.PublicId==factory.Catalog.AreaId);if(!await db.ProviderServiceAreas.AnyAsync(x=>x.ProviderServiceCategoryId==service.Id&&x.AdministrativeAreaId==area.Id))db.ProviderServiceAreas.Add(new ProviderServiceArea{ProviderServiceCategoryId=service.Id,AdministrativeAreaId=area.Id,StatusCode="ACTIVE",ActivatedAt=DateTime.UtcNow,CreatedAt=DateTime.UtcNow,UpdatedAt=DateTime.UtcNow});await db.SaveChangesAsync();return provider.PublicId;}
    private async Task ResetNegativeProviders(){using var scope=factory.Services.CreateScope();var db=scope.ServiceProvider.GetRequiredService<SoodalLifeDbContext>();var inactive=await(from user in db.Users join p in db.ProviderProfiles on user.Id equals p.UserId where user.LoginId==factory.InactiveProviderCredential.LoginId select p).SingleAsync();inactive.ApprovalStatusCode="PENDING";inactive.ActivityStatusCode="INACTIVE";var areaProvider=await(from user in db.Users join p in db.ProviderProfiles on user.Id equals p.UserId where user.LoginId==factory.AreaMismatchProviderCredential.LoginId select p).SingleAsync();var category=await db.ServiceCategories.Where(x=>x.PublicId==factory.Catalog.ServiceId).Select(x=>x.Id).SingleAsync();var area=await db.AdministrativeAreas.Where(x=>x.PublicId==factory.Catalog.AreaId).Select(x=>x.Id).SingleAsync();var serviceIds=await db.ProviderServiceCategories.Where(x=>x.ProviderProfileId==areaProvider.Id&&x.CategoryId==category).Select(x=>x.Id).ToListAsync();db.ProviderServiceAreas.RemoveRange(await db.ProviderServiceAreas.Where(x=>serviceIds.Contains(x.ProviderServiceCategoryId)&&x.AdministrativeAreaId==area).ToListAsync());await db.SaveChangesAsync();}
    private HttpClient Client()=>factory.CreateClient(new WebApplicationFactoryClientOptions{AllowAutoRedirect=false,HandleCookies=true});private static Task<HttpResponseMessage> Login(HttpClient client,TestCredential credential)=>client.PostAsJsonAsync("/api/v1/auth/login",new{LoginOrEmail=credential.LoginId,credential.Password});
    private sealed record Flow(HttpClient Customer,HttpClient Provider,SubscriptionRequestResponse Request,SubscriptionApplicationResponse Application,SubscriptionContractResponse Contract);
}
