using System.Net;
using System.Net.Http.Json;
using Microsoft.AspNetCore.Mvc.Testing;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.DependencyInjection;
using SoodalLife.Api.Domain.Entities;
using SoodalLife.Api.Features.Authentication;
using SoodalLife.Api.Features.Interior;
using SoodalLife.Api.Infrastructure.Persistence;

namespace SoodalLife.Api.Tests;

public sealed class CustomerInteriorApiTests(AuthenticationWebApplicationFactory factory):IClassFixture<AuthenticationWebApplicationFactory>
{
    [Fact]
    public async Task Customer_CanDiscoverCreateListAndReadOwnProject_WhileRolesAndOtherCustomerAreProtected()
    {
        var request=await SeedRequest();using var anonymous=Client();var services=await anonymous.GetFromJsonAsync<List<InteriorServiceResponse>>("/api/v1/public/interior/services");Assert.Contains(services!,x=>x.Id==factory.Catalog.ServiceId);
        using var customer=Client();using var other=Client();using var provider=Client();await Login(customer,factory.Credentials[RoleCodes.Customer]);await Login(other,factory.OtherCustomerCredential);await Login(provider,factory.Credentials[RoleCodes.Provider]);
        var create=await customer.PostAsJsonAsync("/api/v1/customers/me/interior/projects",new{serviceRequestId=request,idempotencyKey=$"customer-project-{Guid.NewGuid():N}"});Assert.Equal(HttpStatusCode.OK,create.StatusCode);var project=(await create.Content.ReadFromJsonAsync<CustomerInteriorProjectDetail>())!;Assert.Equal("CONSULTATION",project.StatusCode);Assert.NotNull(project.RowVersion);Assert.DoesNotContain("feeAssessment",await create.Content.ReadAsStringAsync(),StringComparison.OrdinalIgnoreCase);
        Assert.Contains((await customer.GetFromJsonAsync<List<CustomerInteriorProjectListItem>>("/api/v1/customers/me/interior/projects"))!,x=>x.Id==project.Id);Assert.Equal(HttpStatusCode.NotFound,(await other.GetAsync($"/api/v1/customers/me/interior/projects/{project.Id}")).StatusCode);Assert.Equal(HttpStatusCode.Forbidden,(await provider.GetAsync("/api/v1/customers/me/interior/projects")).StatusCode);
    }

    [Fact]
    public async Task SiteVisitSelection_PreservesPreselectionPrivacy_AndCustomerReadsActualMeasurements()
    {
        var flow=await CreateProject();using var admin=flow.Admin;using var customer=flow.Customer;using var provider=Client();using var otherProvider=Client();await Login(provider,factory.Credentials[RoleCodes.Provider]);await Login(otherProvider,factory.AreaMismatchProviderCredential);var providerId=await ProviderId(factory.Credentials[RoleCodes.Provider]);
        var add=await admin.PostAsJsonAsync($"/api/v1/admin/interior/projects/{flow.Project.Id}/site-visits",new{providerId,scheduledStartAt=DateTime.UtcNow.AddDays(1),scheduledEndAt=DateTime.UtcNow.AddDays(1).AddHours(2),accessConditionText="공동현관 호출",idempotencyKey=$"visit-{Guid.NewGuid():N}"});var visit=(await add.Content.ReadFromJsonAsync<InteriorSiteVisitResponse>())!;
        Assert.Equal(HttpStatusCode.NotFound,(await provider.GetAsync($"/api/v1/interior/site-visits/{visit.Id}")).StatusCode);var detail=await customer.GetFromJsonAsync<CustomerInteriorProjectDetail>($"/api/v1/customers/me/interior/projects/{flow.Project.Id}");Assert.True(Assert.Single(detail!.SiteVisits).CanSelect);
        Assert.Equal(HttpStatusCode.OK,(await customer.PostAsJsonAsync($"/api/v1/customers/me/interior/projects/{flow.Project.Id}/site-visits/{visit.Id}/selection",new{idempotencyKey=$"select-{Guid.NewGuid():N}"})).StatusCode);var privateView=await provider.GetFromJsonAsync<ProviderSiteVisitPrivateResponse>($"/api/v1/interior/site-visits/{visit.Id}");Assert.Equal("101동 1203호",privateView!.DetailAddress);Assert.Equal(HttpStatusCode.NotFound,(await otherProvider.GetAsync($"/api/v1/interior/site-visits/{visit.Id}")).StatusCode);
        var complete=await admin.PostAsJsonAsync($"/api/v1/admin/interior/projects/{flow.Project.Id}/site-visits/{visit.Id}/completion",new{measurementSummary="주방 실측 완료",constraint="엘리베이터 시간 제한",riskNote="가스 배관 확인",measurements=new[]{new{key="kitchen_width",value=3.4m,text=(string?)null,unit="m",location="주방",note="마감 전 기준",additionalDataJson=(string?)null}},fileIds=Array.Empty<Guid>(),idempotencyKey=$"measure-{Guid.NewGuid():N}",rowVersion=(string?)null});Assert.Equal(HttpStatusCode.OK,complete.StatusCode);
        detail=await customer.GetFromJsonAsync<CustomerInteriorProjectDetail>($"/api/v1/customers/me/interior/projects/{flow.Project.Id}");var measured=Assert.Single(detail!.SiteVisits);Assert.Equal("주방 실측 완료",measured.MeasurementSummary);Assert.Equal(3.4m,Assert.Single(measured.Measurements).Value);Assert.Equal("가스 배관 확인",measured.RiskNote);
    }

    [Fact]
    public async Task Customer360_ReadsQuoteDesignContractPaymentStagesChangesInspectionCompletionAndHistory()
    {
        var flow=await CreateProject();var providerId=await ProviderId(factory.Credentials[RoleCodes.Provider]);var revision=await SeedQuote(flow.RequestId,providerId);using var provider=Client();await Login(provider,factory.Credentials[RoleCodes.Provider]);
        var design=await flow.Admin.PostAsJsonAsync($"/api/v1/admin/interior/projects/{flow.Project.Id}/designs",new{title="주방 설계안",description="동선 중심 1차 설계",fileIds=Array.Empty<Guid>(),idempotencyKey=$"design-{Guid.NewGuid():N}"});Assert.Equal(HttpStatusCode.OK,design.StatusCode);await SelectProvider(flow.Customer,flow.Project.Id,revision);
        var contractResponse=await flow.Admin.PostAsJsonAsync($"/api/v1/admin/interior/projects/{flow.Project.Id}/contracts",new{providerId,quoteRevisionId=revision,contractAmount=12000000m,currencyCode="KRW",scopeSnapshotJson="{\"scope\":\"주방 리모델링\"}",scheduleSnapshotJson="{\"days\":20}",warrantySnapshotJson="{\"days\":30}",plannedStartDate=DateOnly.FromDateTime(DateTime.Today.AddDays(3)),plannedCompletionDate=DateOnly.FromDateTime(DateTime.Today.AddDays(23)),paymentPlans=new[]{new{sequenceNo=1,name="계약 지급",amount=3000000m,dueDate=(DateOnly?)null,condition="양 당사자 동의 후"}},idempotencyKey=$"contract-{Guid.NewGuid():N}"});var contract=(await contractResponse.Content.ReadFromJsonAsync<InteriorContractResponse>())!;
        Assert.Equal(HttpStatusCode.OK,(await flow.Customer.PostAsJsonAsync($"/api/v1/customers/me/interior/projects/{flow.Project.Id}/contracts/{contract.Id}/agreement",new{idempotencyKey=$"agree-c-{Guid.NewGuid():N}"})).StatusCode);Assert.Equal(HttpStatusCode.OK,(await provider.PostAsJsonAsync($"/api/v1/interior/contracts/{contract.Id}/agreement",new{idempotencyKey=$"agree-p-{Guid.NewGuid():N}",rowVersion=(string?)null})).StatusCode);
        var detail=await flow.Customer.GetFromJsonAsync<CustomerInteriorProjectDetail>($"/api/v1/customers/me/interior/projects/{flow.Project.Id}");Assert.Contains(detail!.Quotes,x=>x.PurposeCode=="POST_SITE_VISIT"&&x.Items.Count==2);Assert.Single(detail.Designs);Assert.Equal("EFFECTIVE",detail.Contract!.StatusCode);Assert.Single(detail.Contract.Versions);var plan=Assert.Single(detail.Contract.PaymentPlans);
        Assert.Equal(HttpStatusCode.OK,(await flow.Customer.PostAsJsonAsync($"/api/v1/customers/me/interior/projects/{flow.Project.Id}/payment-plans/{plan.Id}/confirmations",new{confirmationTypeCode="CUSTOMER_DIRECT_PAYMENT",amount=3000000m,confirmedAt=DateTime.UtcNow,evidenceFileId=(Guid?)null,note="공급자에게 직접 지급",idempotencyKey=$"pay-{Guid.NewGuid():N}"})).StatusCode);
        var stageResponse=await flow.Admin.PostAsJsonAsync($"/api/v1/admin/interior/projects/{flow.Project.Id}/stages",new{sequenceNo=1,name="철거",plannedStartDate=DateOnly.FromDateTime(DateTime.Today.AddDays(3)),plannedEndDate=DateOnly.FromDateTime(DateTime.Today.AddDays(6)),idempotencyKey=$"stage-{Guid.NewGuid():N}"});var stage=(await stageResponse.Content.ReadFromJsonAsync<InteriorWorkStageResponse>())!;
        await provider.PostAsJsonAsync($"/api/v1/interior/stages/{stage.Id}/updates",new{progressPercent=60,updateText="철거 진행",issueText="폐기물 반출 일정 확인",fileIds=Array.Empty<Guid>(),idempotencyKey=$"update-{Guid.NewGuid():N}",rowVersion=(string?)null});await flow.Admin.PostAsJsonAsync($"/api/v1/admin/interior/stages/{stage.Id}/inspections",new{inspectionStatusCode="CORRECTION_REQUIRED",checklistJson="{\"clean\":false}",resultText="보완 필요",requestedCorrectionText="잔재물 정리",idempotencyKey=$"inspect-{Guid.NewGuid():N}"});
        var changeResponse=await provider.PostAsJsonAsync($"/api/v1/interior/contracts/{contract.Id}/changes",new{changeTypeCode="ADDITIONAL_WORK",reason="고객 요청",scopeChange="수납장 추가",amountDelta=500000m,scheduleImpactDays=2,idempotencyKey=$"change-{Guid.NewGuid():N}"});var change=(await changeResponse.Content.ReadFromJsonAsync<InteriorChangeResponse>())!;
        using(var scope=factory.Services.CreateScope()){var db=scope.ServiceProvider.GetRequiredService<SoodalLifeDbContext>();Assert.Equal(12000000m,(await db.InteriorContracts.SingleAsync(x=>x.PublicId==contract.Id)).ContractAmount);}Assert.Equal(HttpStatusCode.OK,(await flow.Customer.PostAsJsonAsync($"/api/v1/customers/me/interior/projects/{flow.Project.Id}/changes/{change.Id}/decision",new{approve=true,idempotencyKey=$"decide-{Guid.NewGuid():N}"})).StatusCode);
        Assert.Equal(HttpStatusCode.OK,(await provider.PostAsJsonAsync($"/api/v1/interior/stages/{stage.Id}/updates",new{progressPercent=100,updateText="철거 및 정리 완료",issueText=(string?)null,fileIds=Array.Empty<Guid>(),idempotencyKey=$"update-final-{Guid.NewGuid():N}",rowVersion=(string?)null})).StatusCode);Assert.Equal(HttpStatusCode.OK,(await provider.PostAsJsonAsync($"/api/v1/interior/projects/{flow.Project.Id}/completion-report",new{completionSummary="승인 범위 완료",finalChecklistJson="{\"handover\":true}",idempotencyKey=$"provider-complete-{Guid.NewGuid():N}",rowVersion=(string?)null})).StatusCode);var passedInspection=await flow.Admin.PostAsJsonAsync($"/api/v1/admin/interior/stages/{stage.Id}/inspections",new{inspectionStatusCode="PASSED",checklistJson="{\"clean\":true}",resultText="최종 검사 통과",requestedCorrectionText=(string?)null,idempotencyKey=$"inspect-final-{Guid.NewGuid():N}"});Assert.Equal(HttpStatusCode.OK,passedInspection.StatusCode);var passedInspectionId=await passedInspection.Content.ReadFromJsonAsync<Guid>();Assert.Equal(HttpStatusCode.OK,(await flow.Customer.PostAsJsonAsync($"/api/v1/customers/me/interior/projects/{flow.Project.Id}/inspections/{passedInspectionId}/acknowledgement",new{comment="검사 결과 확인",idempotencyKey=$"inspect-ack-{Guid.NewGuid():N}",rowVersion=(string?)null})).StatusCode);Assert.Equal(HttpStatusCode.OK,(await flow.Customer.PostAsJsonAsync($"/api/v1/customers/me/interior/projects/{flow.Project.Id}/completion-acknowledgement",new{comment="완료 확인",idempotencyKey=$"completion-ack-{Guid.NewGuid():N}",rowVersion=(string?)null})).StatusCode);Assert.Equal(HttpStatusCode.OK,(await flow.Admin.PostAsJsonAsync($"/api/v1/admin/interior/projects/{flow.Project.Id}/completion",new{finalChecklistJson="{\"handover\":true}",completionSummary="승인 범위 완료",idempotencyKey=$"complete-{Guid.NewGuid():N}",rowVersion=(string?)null})).StatusCode);detail=await flow.Customer.GetFromJsonAsync<CustomerInteriorProjectDetail>($"/api/v1/customers/me/interior/projects/{flow.Project.Id}");Assert.Equal(12500000m,detail!.Contract!.Amount);Assert.Equal(2,detail.Contract.Versions.Count);Assert.Equal(100,Assert.Single(detail.WorkStages).ProgressPercent);Assert.Contains(Assert.Single(detail.WorkStages).Inspections,x=>x.StatusCode=="CORRECTION_REQUIRED");Assert.Contains(Assert.Single(detail.WorkStages).Inspections,x=>x.StatusCode=="PASSED"&&x.AcknowledgedAt.HasValue);Assert.NotNull(detail.Completion);
    }

    [Fact]
    public async Task InteriorDefectAndDispute_ReuseCommonWorkflows_WithoutWalletFeeTrustOrSubscriptionMutation()
    {
        var flow=await CreateProject();var providerId=await ProviderId(factory.Credentials[RoleCodes.Provider]);var revision=await SeedQuote(flow.RequestId,providerId);await SelectProvider(flow.Customer,flow.Project.Id,revision);var contractResponse=await flow.Admin.PostAsJsonAsync($"/api/v1/admin/interior/projects/{flow.Project.Id}/contracts",new{providerId,quoteRevisionId=revision,contractAmount=12000000m,currencyCode="KRW",scopeSnapshotJson="{}",scheduleSnapshotJson="{}",warrantySnapshotJson="{\"days\":30}",plannedStartDate=DateOnly.FromDateTime(DateTime.Today),plannedCompletionDate=DateOnly.FromDateTime(DateTime.Today.AddDays(1)),paymentPlans=Array.Empty<object>(),idempotencyKey=$"contract-{Guid.NewGuid():N}"});Assert.Equal(HttpStatusCode.OK,contractResponse.StatusCode);await flow.Admin.PostAsJsonAsync($"/api/v1/admin/interior/projects/{flow.Project.Id}/completion",new{finalChecklistJson="{}",completionSummary="완료",idempotencyKey=$"complete-{Guid.NewGuid():N}",rowVersion=(string?)null});
        int wallets,ledger,fees,trustEvents,subscriptions;decimal? trust;using(var scope=factory.Services.CreateScope()){var db=scope.ServiceProvider.GetRequiredService<SoodalLifeDbContext>();wallets=await db.ProviderWallets.CountAsync();ledger=await db.WalletLedgerEntries.CountAsync();fees=await db.FeeCharges.CountAsync();trustEvents=await db.TrustScoreEvents.CountAsync();subscriptions=await db.SubscriptionContracts.CountAsync();var provider=await db.ProviderProfiles.SingleAsync(x=>x.PublicId==providerId);trust=await db.ProviderTrustScoreCurrent.Where(x=>x.ProviderProfileId==provider.Id).Select(x=>(decimal?)x.Score).SingleOrDefaultAsync();}
        var defect=await flow.Customer.PostAsJsonAsync($"/api/v1/customers/me/interior/projects/{flow.Project.Id}/defects",new{workStageId=(Guid?)null,contractVersion=1,location="주방 벽면",subject="도장 들뜸",description="완료 후 도장 들뜸이 확인됩니다.",fileIds=Array.Empty<Guid>(),idempotencyKey=$"defect-{Guid.NewGuid():N}"});Assert.Equal(HttpStatusCode.OK,defect.StatusCode);var defectDetail=await defect.Content.ReadFromJsonAsync<CustomerInteriorProjectDetail>();var dispute=await flow.Customer.PostAsJsonAsync($"/api/v1/customers/me/after-services/{defectDetail!.Defects[0].AfterServiceCaseId}/dispute",new{subject="보완 범위 확인",reason="보완 범위에 대한 중재가 필요합니다.",requestedResolution="보완 범위를 확인해 주세요.",idempotencyKey=$"dispute-{Guid.NewGuid():N}"});Assert.Equal(HttpStatusCode.OK,dispute.StatusCode);
        var detailResponse=await flow.Customer.GetAsync($"/api/v1/customers/me/interior/projects/{flow.Project.Id}");var detail=await detailResponse.Content.ReadFromJsonAsync<CustomerInteriorProjectDetail>();Assert.Single(detail!.Defects);Assert.Single(detail.Disputes);Assert.Equal(HttpStatusCode.OK,(await flow.Customer.GetAsync($"/api/v1/after-services/{detail.Defects[0].AfterServiceCaseId}")).StatusCode);Assert.Equal(HttpStatusCode.OK,(await flow.Customer.GetAsync($"/api/v1/customers/me/disputes/{detail.Disputes[0].Id}")).StatusCode);using var verifyScope=factory.Services.CreateScope();var verify=verifyScope.ServiceProvider.GetRequiredService<SoodalLifeDbContext>();var project=await verify.InteriorProjects.SingleAsync(x=>x.PublicId==flow.Project.Id);Assert.Single(await verify.AfterServiceCases.Where(x=>x.InteriorProjectId==project.Id).ToListAsync());Assert.Single(await verify.InteriorDefects.Where(x=>x.InteriorProjectId==project.Id).ToListAsync());Assert.Single(await verify.DisputeCases.Where(x=>x.InteriorProjectId==project.Id).ToListAsync());Assert.Equal(wallets,await verify.ProviderWallets.CountAsync());Assert.Equal(ledger,await verify.WalletLedgerEntries.CountAsync());Assert.Equal(fees,await verify.FeeCharges.CountAsync());Assert.Equal(trustEvents,await verify.TrustScoreEvents.CountAsync());Assert.Equal(subscriptions,await verify.SubscriptionContracts.CountAsync());var verifiedProvider=await verify.ProviderProfiles.SingleAsync(x=>x.PublicId==providerId);Assert.Equal(trust,await verify.ProviderTrustScoreCurrent.Where(x=>x.ProviderProfileId==verifiedProvider.Id).Select(x=>(decimal?)x.Score).SingleOrDefaultAsync());Assert.Equal("POLICY_PENDING",project.FeeAssessmentStatusCode);
        using var admin=Client();await Login(admin,factory.Credentials[RoleCodes.Admin]);Assert.Equal(HttpStatusCode.OK,(await admin.GetAsync("/api/v1/admin/interior/projects")).StatusCode);Assert.Equal(HttpStatusCode.OK,(await admin.GetAsync("/api/v1/admin/after-services")).StatusCode);
    }

    [Fact]
    public async Task Customer_SelectsOneLatestInteriorProvider_WithoutCreatingContractOrFee()
    {
        var flow=await CreateProject();var providerId=await ProviderId(factory.Credentials[RoleCodes.Provider]);var revision=await SeedQuote(flow.RequestId,providerId);using var provider=Client();using var otherProvider=Client();await Login(provider,factory.Credentials[RoleCodes.Provider]);await Login(otherProvider,factory.AreaMismatchProviderCredential);
        int wallets,ledger,fees,trustEvents;using(var scope=factory.Services.CreateScope()){var before=scope.ServiceProvider.GetRequiredService<SoodalLifeDbContext>();wallets=await before.ProviderWallets.CountAsync();ledger=await before.WalletLedgerEntries.CountAsync();fees=await before.FeeCharges.CountAsync();trustEvents=await before.TrustScoreEvents.CountAsync();}
        var beforeSelection=await flow.Customer.GetFromJsonAsync<CustomerInteriorProjectDetail>($"/api/v1/customers/me/interior/projects/{flow.Project.Id}");var quote=Assert.Single(beforeSelection!.Quotes);Assert.True(quote.CanSelect);Assert.Equal(revision,quote.RevisionId);Assert.Equal(providerId,quote.ProviderId);
        var premature=await flow.Admin.PostAsJsonAsync($"/api/v1/admin/interior/projects/{flow.Project.Id}/contracts",new{providerId,quoteRevisionId=revision,contractAmount=12000000m,currencyCode="KRW",scopeSnapshotJson="{}",scheduleSnapshotJson="{}",warrantySnapshotJson="{}",plannedStartDate=DateOnly.FromDateTime(DateTime.Today),plannedCompletionDate=DateOnly.FromDateTime(DateTime.Today.AddDays(1)),paymentPlans=Array.Empty<object>(),idempotencyKey=$"premature-{Guid.NewGuid():N}"});Assert.Equal(HttpStatusCode.Conflict,premature.StatusCode);
        var key=$"select-provider-{Guid.NewGuid():N}";var response=await flow.Customer.PostAsJsonAsync($"/api/v1/customers/me/interior/projects/{flow.Project.Id}/provider-selection",new{quoteRevisionId=revision,rowVersion=beforeSelection.RowVersion,idempotencyKey=key});Assert.Equal(HttpStatusCode.OK,response.StatusCode);var selected=(await response.Content.ReadFromJsonAsync<CustomerInteriorProjectDetail>())!;Assert.Equal(providerId,selected.ProviderSelection!.ProviderId);Assert.Equal(revision,selected.ProviderSelection.QuoteRevisionId);Assert.Null(selected.Contract);Assert.True(Assert.Single(selected.Quotes).Selected);Assert.False(Assert.Single(selected.Quotes).CanSelect);
        Assert.Equal(HttpStatusCode.OK,(await flow.Customer.PostAsJsonAsync($"/api/v1/customers/me/interior/projects/{flow.Project.Id}/provider-selection",new{quoteRevisionId=revision,rowVersion=beforeSelection.RowVersion,idempotencyKey=key})).StatusCode);Assert.Equal(HttpStatusCode.OK,(await provider.GetAsync($"/api/v1/providers/me/interior/projects/{flow.Project.Id}")).StatusCode);Assert.Equal(HttpStatusCode.NotFound,(await otherProvider.GetAsync($"/api/v1/providers/me/interior/projects/{flow.Project.Id}")).StatusCode);Assert.Equal(HttpStatusCode.OK,(await flow.Customer.GetAsync($"/api/v1/chat/interiors/{flow.Project.Id}/room?role=PRIMARY_CONTRACTOR")).StatusCode);Assert.Equal(HttpStatusCode.OK,(await provider.GetAsync($"/api/v1/chat/interiors/{flow.Project.Id}/room?role=PRIMARY_CONTRACTOR")).StatusCode);Assert.Equal(HttpStatusCode.NotFound,(await otherProvider.GetAsync($"/api/v1/chat/interiors/{flow.Project.Id}/room?role=PRIMARY_CONTRACTOR")).StatusCode);
        using var verifyScope=factory.Services.CreateScope();var verify=verifyScope.ServiceProvider.GetRequiredService<SoodalLifeDbContext>();var project=await verify.InteriorProjects.SingleAsync(x=>x.PublicId==flow.Project.Id);Assert.Equal("POLICY_PENDING",project.FeeAssessmentStatusCode);Assert.Null(project.CurrentContractId);Assert.Single(await verify.InteriorProjectParticipants.Where(x=>x.InteriorProjectId==project.Id&&x.RoleCode=="PRIMARY_CONTRACTOR"&&x.StatusCode=="ACTIVE").ToListAsync());Assert.Single(await verify.InteriorProjectEvents.Where(x=>x.InteriorProjectId==project.Id&&x.EventTypeCode=="CONTRACTOR_SELECTED").ToListAsync());Assert.Equal(wallets,await verify.ProviderWallets.CountAsync());Assert.Equal(ledger,await verify.WalletLedgerEntries.CountAsync());Assert.Equal(fees,await verify.FeeCharges.CountAsync());Assert.Equal(trustEvents,await verify.TrustScoreEvents.CountAsync());
    }

    [Fact]
    public async Task ProviderSelection_RejectsOtherActorsOldRevisionAndWithdrawnQuote()
    {
        var flow=await CreateProject();var providerId=await ProviderId(factory.Credentials[RoleCodes.Provider]);var revision=await SeedQuote(flow.RequestId,providerId);using var other=Client();using var provider=Client();await Login(other,factory.OtherCustomerCredential);await Login(provider,factory.Credentials[RoleCodes.Provider]);var detail=await flow.Customer.GetFromJsonAsync<CustomerInteriorProjectDetail>($"/api/v1/customers/me/interior/projects/{flow.Project.Id}");var body=new{quoteRevisionId=revision,rowVersion=detail!.RowVersion,idempotencyKey=$"select-provider-{Guid.NewGuid():N}"};Assert.Equal(HttpStatusCode.NotFound,(await other.PostAsJsonAsync($"/api/v1/customers/me/interior/projects/{flow.Project.Id}/provider-selection",body)).StatusCode);Assert.Equal(HttpStatusCode.Forbidden,(await provider.PostAsJsonAsync($"/api/v1/customers/me/interior/projects/{flow.Project.Id}/provider-selection",body)).StatusCode);
        using(var scope=factory.Services.CreateScope()){var db=scope.ServiceProvider.GetRequiredService<SoodalLifeDbContext>();var first=await db.QuoteRevisions.SingleAsync(x=>x.PublicId==revision);db.QuoteRevisions.Add(new(){QuoteId=first.QuoteId,RevisionNo=2,RevisionPurposeCode="POST_SITE_VISIT",Summary="최신 상세견적",SubtotalAmount=first.SubtotalAmount,VatAmount=first.VatAmount,TotalAmount=first.TotalAmount,CurrencyCode=first.CurrencyCode,ValidUntil=DateTime.UtcNow.AddDays(7),SubmittedAt=DateTime.UtcNow,SubmittedByUserId=first.SubmittedByUserId,IdempotencyKey=$"quote-{Guid.NewGuid():N}"});await db.SaveChangesAsync();}
        Assert.Equal(HttpStatusCode.Conflict,(await flow.Customer.PostAsJsonAsync($"/api/v1/customers/me/interior/projects/{flow.Project.Id}/provider-selection",new{quoteRevisionId=revision,rowVersion=detail.RowVersion,idempotencyKey=$"old-{Guid.NewGuid():N}"})).StatusCode);using(var scope=factory.Services.CreateScope()){var db=scope.ServiceProvider.GetRequiredService<SoodalLifeDbContext>();var requestId=await db.ServiceRequests.Where(x=>x.PublicId==flow.RequestId).Select(x=>x.Id).SingleAsync();var quote=await db.Quotes.SingleAsync(x=>x.ServiceRequestId==requestId);quote.WithdrawnAt=DateTime.UtcNow;await db.SaveChangesAsync();}Assert.Empty((await flow.Customer.GetFromJsonAsync<CustomerInteriorProjectDetail>($"/api/v1/customers/me/interior/projects/{flow.Project.Id}"))!.Quotes);
    }

    [Fact]
    public async Task ProviderSelection_BlocksSecondSelectionAndAdminReadsSnapshot()
    {
        var flow=await CreateProject();var providerId=await ProviderId(factory.Credentials[RoleCodes.Provider]);var revision=await SeedQuote(flow.RequestId,providerId);await SelectProvider(flow.Customer,flow.Project.Id,revision);var detail=await flow.Customer.GetFromJsonAsync<CustomerInteriorProjectDetail>($"/api/v1/customers/me/interior/projects/{flow.Project.Id}");Assert.Equal(HttpStatusCode.Conflict,(await flow.Customer.PostAsJsonAsync($"/api/v1/customers/me/interior/projects/{flow.Project.Id}/provider-selection",new{quoteRevisionId=revision,rowVersion=detail!.RowVersion,idempotencyKey=$"second-{Guid.NewGuid():N}"})).StatusCode);var admin=await flow.Admin.GetFromJsonAsync<InteriorProjectDetail>($"/api/v1/admin/interior/projects/{flow.Project.Id}");Assert.Equal(revision,admin!.SelectedQuoteRevisionId);Assert.Equal(1,admin.SelectedQuoteRevisionNo);Assert.NotNull(admin.ContractorSelectedAt);Assert.Empty(admin.Contracts);
    }

    [Fact]
    public async Task ProviderSelection_ExcludesAndRejectsProviderWithoutAreaEligibility()
    {
        var flow=await CreateProject();var providerId=await ProviderId(factory.AreaMismatchProviderCredential);var revision=await SeedQuote(flow.RequestId,providerId);var detail=await flow.Customer.GetFromJsonAsync<CustomerInteriorProjectDetail>($"/api/v1/customers/me/interior/projects/{flow.Project.Id}");Assert.Empty(detail!.Quotes);var response=await flow.Customer.PostAsJsonAsync($"/api/v1/customers/me/interior/projects/{flow.Project.Id}/provider-selection",new{quoteRevisionId=revision,rowVersion=detail.RowVersion,idempotencyKey=$"ineligible-{Guid.NewGuid():N}"});Assert.Equal(HttpStatusCode.Conflict,response.StatusCode);
    }

    private async Task<Flow> CreateProject(){var request=await SeedRequest();var customer=Client();var admin=Client();await Login(customer,factory.Credentials[RoleCodes.Customer]);await Login(admin,factory.Credentials[RoleCodes.Admin]);var response=await customer.PostAsJsonAsync("/api/v1/customers/me/interior/projects",new{serviceRequestId=request,idempotencyKey=$"create-{Guid.NewGuid():N}"});Assert.Equal(HttpStatusCode.OK,response.StatusCode);return new(customer,admin,(await response.Content.ReadFromJsonAsync<CustomerInteriorProjectDetail>())!,request);}
    private async Task<Guid> SeedRequest(){using var scope=factory.Services.CreateScope();var db=scope.ServiceProvider.GetRequiredService<SoodalLifeDbContext>();var service=await db.ServiceCategories.SingleAsync(x=>x.PublicId==factory.Catalog.ServiceId);service.ExternalCode="INT-TEST";var middle=await db.ServiceCategories.SingleAsync(x=>x.Id==service.ParentId);var major=await db.ServiceCategories.SingleAsync(x=>x.Id==middle.ParentId);major.Name="인테리어";var customer=await(from user in db.Users join profile in db.CustomerProfiles on user.Id equals profile.UserId where user.LoginId==factory.Credentials[RoleCodes.Customer].LoginId select new{user,profile}).SingleAsync();customer.user.Phone="010-2468-1357";var policy=await db.CategoryPolicies.FirstAsync(x=>x.CategoryId==service.Id);var area=await db.AdministrativeAreas.SingleAsync(x=>x.PublicId==factory.Catalog.AreaId);var now=DateTime.UtcNow;var request=new ServiceRequest{CustomerProfileId=customer.profile.Id,CategoryId=service.Id,CategoryPolicyId=policy.Id,AdministrativeAreaId=area.Id,DetailAddress="101동 1203호",Title=$"인테리어 상담 {Guid.NewGuid():N}",Description="주방과 거실 공사를 요청합니다.",StatusCode="OPEN",PolicySnapshotJson="{}",OpenedAt=now,CreatedAt=now,CreatedByUserId=customer.user.Id,UpdatedAt=now,UpdatedByUserId=customer.user.Id};db.ServiceRequests.Add(request);await db.SaveChangesAsync();return request.PublicId;}
    private async Task<Guid> SeedQuote(Guid requestId,Guid providerId){using var scope=factory.Services.CreateScope();var db=scope.ServiceProvider.GetRequiredService<SoodalLifeDbContext>();var request=await db.ServiceRequests.SingleAsync(x=>x.PublicId==requestId);var project=await db.InteriorProjects.SingleAsync(x=>x.ServiceRequestId==request.Id);project.StatusCode="ESTIMATE_READY";var provider=await db.ProviderProfiles.SingleAsync(x=>x.PublicId==providerId);var now=DateTime.UtcNow;var quote=new Quote{ServiceRequestId=request.Id,ProviderProfileId=provider.Id,RequestDispatchId=0,StatusCode="SUBMITTED",SubmittedAt=now,ExpiresAt=now.AddDays(7),CreatedAt=now,UpdatedAt=now};db.Quotes.Add(quote);await db.SaveChangesAsync();var revision=new QuoteRevision{QuoteId=quote.Id,RevisionNo=1,RevisionPurposeCode="POST_SITE_VISIT",Summary="실측 후 상세견적",Terms="철거와 폐기 포함",SubtotalAmount=10909091m,VatAmount=1090909m,TotalAmount=12000000m,CurrencyCode="KRW",EstimatedDurationText="20일",ValidUntil=now.AddDays(7),SubmittedAt=now,SubmittedByUserId=provider.UserId,IdempotencyKey=$"quote-{Guid.NewGuid():N}"};db.QuoteRevisions.Add(revision);await db.SaveChangesAsync();db.QuoteItems.AddRange(new QuoteItem{QuoteRevisionId=revision.Id,LineNo=1,ItemName="철거",Quantity=1,UnitText="식",UnitPriceAmount=2000000,LineTotalAmount=2000000,CurrencyCode="KRW",WorkTradeText="철거",SpaceText="주방",LaborNoteText="폐기물 포함"},new QuoteItem{QuoteRevisionId=revision.Id,LineNo=2,ItemName="수납장",Quantity=1,UnitText="식",UnitPriceAmount=10000000,LineTotalAmount=10000000,CurrencyCode="KRW",WorkTradeText="목공",SpaceText="주방",MaterialSpecText="친환경 자재"});await db.SaveChangesAsync();return revision.PublicId;}
    private async Task SelectProvider(HttpClient customer,Guid projectId,Guid quoteRevisionId){var detail=await customer.GetFromJsonAsync<CustomerInteriorProjectDetail>($"/api/v1/customers/me/interior/projects/{projectId}");var response=await customer.PostAsJsonAsync($"/api/v1/customers/me/interior/projects/{projectId}/provider-selection",new{quoteRevisionId,rowVersion=detail!.RowVersion,idempotencyKey=$"select-provider-{Guid.NewGuid():N}"});Assert.Equal(HttpStatusCode.OK,response.StatusCode);}
    private async Task<Guid> ProviderId(TestCredential credential){using var scope=factory.Services.CreateScope();var db=scope.ServiceProvider.GetRequiredService<SoodalLifeDbContext>();return await(from user in db.Users join provider in db.ProviderProfiles on user.Id equals provider.UserId where user.LoginId==credential.LoginId select provider.PublicId).SingleAsync();}
    private HttpClient Client()=>factory.CreateClient(new WebApplicationFactoryClientOptions{AllowAutoRedirect=false,HandleCookies=true});private static async Task Login(HttpClient client,TestCredential value)=>Assert.Equal(HttpStatusCode.OK,(await client.PostAsJsonAsync("/api/v1/auth/login",new{LoginOrEmail=value.LoginId,value.Password})).StatusCode);
    private sealed record Flow(HttpClient Customer,HttpClient Admin,CustomerInteriorProjectDetail Project,Guid RequestId);
}
