using System.Net;
using System.Net.Http.Headers;
using System.Net.Http.Json;
using Microsoft.AspNetCore.Mvc.Testing;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.DependencyInjection;
using SoodalLife.Api.Domain.Entities;
using SoodalLife.Api.Features.Authentication;
using SoodalLife.Api.Features.Work;
using SoodalLife.Api.Infrastructure.Persistence;

namespace SoodalLife.Api.Tests;

public sealed class CustomerAftercareApiTests(AuthenticationWebApplicationFactory factory) : IClassFixture<AuthenticationWebApplicationFactory>
{
    [Fact] public async Task ServiceHistory_OwnerCanList() { var seed = await SeedCompleted(); using var client = await Customer(); var items = await client.GetFromJsonAsync<List<ServiceHistoryListItem>>("/api/v1/customers/me/service-history"); Assert.Contains(items!, x => x.Id == seed.HistoryId); }
    [Fact] public async Task ServiceHistory_OtherCustomerGets404() { var seed = await SeedCompleted(); using var client = await OtherCustomer(); Assert.Equal(HttpStatusCode.NotFound, (await client.GetAsync($"/api/v1/customers/me/service-history/{seed.HistoryId}")).StatusCode); }
    [Fact] public async Task ServiceHistory_DetailUsesSnapshot() { var seed = await SeedCompleted("과거 공급자", "과거 서비스"); using var client = await Customer(); var item = await client.GetFromJsonAsync<ServiceHistoryDetail>($"/api/v1/customers/me/service-history/{seed.HistoryId}"); Assert.Equal("과거 공급자", item!.ProviderName); Assert.Equal("과거 서비스", item.ServiceName); }
    [Fact] public async Task AfterService_CompletedTransactionCanCreate() { var seed = await SeedCompleted(); using var client = await Customer(); var item = await CreateAfterService(client, seed.TransactionId); Assert.Equal("RECEIVED", item.Status); }
    [Fact] public async Task AfterService_IncompleteTransactionBlocked() { var seed = await SeedCompleted(); await SetTransactionStatus(seed.TransactionId, "IN_PROGRESS"); using var client = await Customer(); Assert.Equal(HttpStatusCode.Conflict, (await PostAfterService(client, seed.TransactionId)).StatusCode); }
    [Fact] public async Task AfterService_OtherCustomerGets404() { var seed = await SeedCompleted(); using var owner = await Customer(); var item = await CreateAfterService(owner, seed.TransactionId); using var other = await OtherCustomer(); Assert.Equal(HttpStatusCode.NotFound, (await other.GetAsync($"/api/v1/after-services/{item.Id}")).StatusCode); }
    [Fact] public async Task AfterService_OtherProviderGets404() { var seed = await SeedCompleted(); using var owner = await Customer(); var item = await CreateAfterService(owner, seed.TransactionId); using var other = await AreaMismatchProvider(); Assert.Equal(HttpStatusCode.NotFound, (await other.GetAsync($"/api/v1/after-services/{item.Id}")).StatusCode); }
    [Fact] public async Task AfterService_SelectedProviderCanRead() { var seed = await SeedCompleted(); using var owner = await Customer(); var item = await CreateAfterService(owner, seed.TransactionId); using var provider = await Provider(); Assert.Equal(HttpStatusCode.OK, (await provider.GetAsync($"/api/v1/after-services/{item.Id}")).StatusCode); }
    [Fact] public async Task AfterService_FileIsPrivate() { var seed = await SeedCompleted(); using var owner = await Customer(); var item = await CreateAfterService(owner, seed.TransactionId); var file = await Upload(owner, $"/api/v1/after-services/{item.Id}/evidence"); using var other = await OtherCustomer(); Assert.Equal(HttpStatusCode.NotFound, (await other.GetAsync($"/api/v1/after-services/{item.Id}/files/{file}")).StatusCode); }
    [Fact] public async Task AfterService_DoesNotChangeTrust() { var before = await Count<TrustScoreEvent>(); var seed = await SeedCompleted(); using var client = await Customer(); await CreateAfterService(client, seed.TransactionId); Assert.Equal(before, await Count<TrustScoreEvent>()); }
    [Fact] public async Task AfterService_DoesNotChangeWallet() { var before = await Count<WalletLedgerEntry>(); var seed = await SeedCompleted(); using var client = await Customer(); await CreateAfterService(client, seed.TransactionId); Assert.Equal(before, await Count<WalletLedgerEntry>()); }
    [Fact] public async Task AfterService_ConvertsToLinkedDispute() { var seed = await SeedCompleted(); using var client = await Customer(); var item = await CreateAfterService(client, seed.TransactionId); var response = await client.PostAsJsonAsync($"/api/v1/customers/me/after-services/{item.Id}/dispute", new { subject="미해결", reason="처리가 완료되지 않았습니다.", requestedResolution="운영 검토를 요청합니다.", idempotencyKey=Guid.NewGuid().ToString("N") }); var dispute = await response.Content.ReadFromJsonAsync<CustomerDisputeResponse>(); Assert.NotNull(dispute); using var scope = factory.Services.CreateScope(); var db = scope.ServiceProvider.GetRequiredService<SoodalLifeDbContext>(); Assert.Equal(item.Id, await db.DisputeCases.Where(x=>x.PublicId==dispute!.Id).Join(db.AfterServiceCases,x=>x.AfterServiceCaseId,y=>y.Id,(x,y)=>y.PublicId).SingleAsync()); }
    [Fact] public async Task AfterService_SecondConversionReturnsExisting() { var seed = await SeedCompleted(); using var client = await Customer(); var item = await CreateAfterService(client, seed.TransactionId); var first = await Convert(client,item.Id); var second = await Convert(client,item.Id); Assert.Equal(first.Id,second.Id); }
    [Fact] public async Task Dispute_ListContainsCustomerCase() { var seed = await SeedCompleted(); using var client = await Customer(); var item = await CreateAfterService(client, seed.TransactionId); var dispute = await Convert(client,item.Id); Assert.Contains((await client.GetFromJsonAsync<List<CustomerDisputeResponse>>("/api/v1/customers/me/disputes"))!,x=>x.Id==dispute.Id); }
    [Fact] public async Task Dispute_DetailContainsPublicStage() { var seed = await SeedCompleted(); using var client = await Customer(); var item = await CreateAfterService(client, seed.TransactionId); var dispute = await Convert(client,item.Id); var detail=await client.GetFromJsonAsync<CustomerDisputeResponse>($"/api/v1/customers/me/disputes/{dispute.Id}"); Assert.NotEmpty(detail!.PublicUpdates); }
    [Fact] public async Task Dispute_OtherCustomerGets404() { var seed = await SeedCompleted(); using var client = await Customer(); var item = await CreateAfterService(client, seed.TransactionId); var dispute = await Convert(client,item.Id); using var other=await OtherCustomer(); Assert.Equal(HttpStatusCode.NotFound,(await other.GetAsync($"/api/v1/customers/me/disputes/{dispute.Id}")).StatusCode); }
    [Fact] public async Task Dispute_FilingDoesNotCreateFault() { var before=await Count<DisputeResolution>(); var seed=await SeedCompleted();using var client=await Customer();var item=await CreateAfterService(client,seed.TransactionId);await Convert(client,item.Id);Assert.Equal(before,await Count<DisputeResolution>()); }
    [Fact] public async Task Dispute_FilingDoesNotChangeTrust() { var before=await Count<TrustScoreEvent>();var seed=await SeedCompleted();using var client=await Customer();var item=await CreateAfterService(client,seed.TransactionId);await Convert(client,item.Id);Assert.Equal(before,await Count<TrustScoreEvent>()); }
    [Fact] public async Task Report_ActiveTypesOnly() { await SeedReportType();using var client=await Customer();var types=await client.GetFromJsonAsync<List<CustomerReportType>>("/api/v1/customers/me/report-types");Assert.NotEmpty(types!); }
    [Fact] public async Task Report_Create() { var seed=await SeedCompleted();var type=await SeedReportType();using var client=await Customer();var report=await CreateReport(client,seed.TransactionId,type);Assert.Equal("RECEIVED",report.Status); }
    [Fact] public async Task Report_List() { var seed=await SeedCompleted();var type=await SeedReportType();using var client=await Customer();var report=await CreateReport(client,seed.TransactionId,type);Assert.Contains((await client.GetFromJsonAsync<List<CustomerReportResponse>>("/api/v1/customers/me/reports"))!,x=>x.Id==report.Id); }
    [Fact] public async Task Report_Detail() { var seed=await SeedCompleted();var type=await SeedReportType();using var client=await Customer();var report=await CreateReport(client,seed.TransactionId,type);Assert.Equal(report.Id,(await client.GetFromJsonAsync<CustomerReportResponse>($"/api/v1/customers/me/reports/{report.Id}"))!.Id); }
    [Fact] public async Task Report_OtherCustomerGets404() { var seed=await SeedCompleted();var type=await SeedReportType();using var client=await Customer();var report=await CreateReport(client,seed.TransactionId,type);using var other=await OtherCustomer();Assert.Equal(HttpStatusCode.NotFound,(await other.GetAsync($"/api/v1/customers/me/reports/{report.Id}")).StatusCode); }
    [Fact] public async Task Report_FileIsPrivate() { var seed=await SeedCompleted();var type=await SeedReportType();using var client=await Customer();var report=await CreateReport(client,seed.TransactionId,type);var file=await Upload(client,$"/api/v1/customers/me/reports/{report.Id}/evidence");using var other=await OtherCustomer();Assert.Equal(HttpStatusCode.NotFound,(await other.GetAsync($"/api/v1/customers/me/reports/{report.Id}/files/{file}")).StatusCode); }
    [Fact] public async Task Report_FilingDoesNotCreateSanction() { var before=await Count<Sanction>();var seed=await SeedCompleted();var type=await SeedReportType();using var client=await Customer();await CreateReport(client,seed.TransactionId,type);Assert.Equal(before,await Count<Sanction>()); }
    [Fact] public async Task Report_FilingDoesNotChangeTrust() { var before=await Count<TrustScoreEvent>();var seed=await SeedCompleted();var type=await SeedReportType();using var client=await Customer();await CreateReport(client,seed.TransactionId,type);Assert.Equal(before,await Count<TrustScoreEvent>()); }
    [Fact] public async Task Report_FilingDoesNotChangeWallet() { var before=await Count<WalletLedgerEntry>();var seed=await SeedCompleted();var type=await SeedReportType();using var client=await Customer();await CreateReport(client,seed.TransactionId,type);Assert.Equal(before,await Count<WalletLedgerEntry>()); }
    [Fact] public async Task Provider_CustomerOnlyHistoryBlocked() { using var client=await Provider();Assert.Equal(HttpStatusCode.Forbidden,(await client.GetAsync("/api/v1/customers/me/service-history")).StatusCode); }
    [Fact] public async Task Admin_ExistingReportApiStillWorks() { using var client=await Admin();Assert.Equal(HttpStatusCode.OK,(await client.GetAsync("/api/v1/admin/reports")).StatusCode); }
    [Fact] public async Task Aftercare_DoesNotChangeSubscription() { var before=await Count<SubscriptionContract>();var seed=await SeedCompleted();using var client=await Customer();await CreateAfterService(client,seed.TransactionId);Assert.Equal(before,await Count<SubscriptionContract>()); }
    [Fact] public async Task Aftercare_DoesNotChangeInterior() { var before=await Count<InteriorProject>();var seed=await SeedCompleted();using var client=await Customer();await CreateAfterService(client,seed.TransactionId);Assert.Equal(before,await Count<InteriorProject>()); }
    [Fact] public async Task IdempotentAfterServiceCreatesOneOutbox() { var seed=await SeedCompleted();using var client=await Customer();var key=Guid.NewGuid().ToString("N");var first=await PostAfterService(client,seed.TransactionId,key);var second=await PostAfterService(client,seed.TransactionId,key);Assert.Equal(HttpStatusCode.OK,first.StatusCode);Assert.Equal(HttpStatusCode.OK,second.StatusCode);using var scope=factory.Services.CreateScope();var db=scope.ServiceProvider.GetRequiredService<SoodalLifeDbContext>();var item=await first.Content.ReadFromJsonAsync<CustomerAfterServiceResponse>();Assert.Single(await db.OutboxEvents.Where(x=>x.AggregatePublicId==item!.Id&&x.EventType=="AFTER_SERVICE_OPENED").ToListAsync()); }

    private async Task<Seed> SeedCompleted(string providerName="완료 공급자",string categoryName="완료 서비스")
    {
        using var scope=factory.Services.CreateScope();var db=scope.ServiceProvider.GetRequiredService<SoodalLifeDbContext>();var customer=await db.Users.SingleAsync(x=>x.LoginId==factory.Credentials[RoleCodes.Customer].LoginId);var profile=await db.CustomerProfiles.SingleAsync(x=>x.UserId==customer.Id);var providerUser=await db.Users.SingleAsync(x=>x.LoginId==factory.Credentials[RoleCodes.Provider].LoginId);var provider=await db.ProviderProfiles.SingleAsync(x=>x.UserId==providerUser.Id);var categoryId=await db.ServiceCategories.Where(x=>x.PublicId==factory.Catalog.ServiceId).Select(x=>x.Id).SingleAsync();var now=DateTime.UtcNow;var tx=new TransactionRecord{ServiceRequestId=0,AcceptedQuoteRevisionId=0,CustomerProfileId=profile.Id,ProviderProfileId=provider.Id,CategoryId=categoryId,StatusCode="COMPLETED",AgreedAmount=100000,CurrencyCode="KRW",QuoteSnapshotJson="{}",CategoryPolicySnapshotJson="{}",CompletionPolicySnapshotJson="{}",WarrantyDaysSnapshot=30,CompletedAt=now,CreatedAt=now,UpdatedAt=now};db.Transactions.Add(tx);await db.SaveChangesAsync();var history=new ServiceHistoryEntry{CustomerProfileId=profile.Id,TransactionId=tx.Id,EventTypeCode="COMPLETION",Title=categoryName,Summary="완료 작업 Snapshot",ProviderNameSnapshot=providerName,CategoryNameSnapshot=categoryName,TotalAmountSnapshot=120000,CurrencyCode="KRW",CompletedAtSnapshot=now,WarrantyStartDate=DateOnly.FromDateTime(now),WarrantyEndDate=DateOnly.FromDateTime(now).AddDays(30),SnapshotJson="{}",OccurredAt=now,IdempotencyKey=$"test-history:{Guid.NewGuid():N}",CreatedAt=now,CreatedByUserId=customer.Id};db.ServiceHistoryEntries.Add(history);await db.SaveChangesAsync();return new(tx.PublicId,history.PublicId);
    }
    private async Task SetTransactionStatus(Guid id,string status){using var scope=factory.Services.CreateScope();var db=scope.ServiceProvider.GetRequiredService<SoodalLifeDbContext>();var row=await db.Transactions.SingleAsync(x=>x.PublicId==id);row.StatusCode=status;await db.SaveChangesAsync();}
    private async Task<Guid> SeedReportType(){using var scope=factory.Services.CreateScope();var db=scope.ServiceProvider.GetRequiredService<SoodalLifeDbContext>();var now=DateTime.UtcNow;var row=new ReportType{Code=$"CUSTOMER_{Guid.NewGuid():N}",Name="고객 신고 유형",IsActive=true,CreatedAt=now,UpdatedAt=now};db.ReportTypes.Add(row);await db.SaveChangesAsync();return row.PublicId;}
    private static Task<HttpResponseMessage> PostAfterService(HttpClient client,Guid transactionId,string? key=null)=>client.PostAsJsonAsync($"/api/v1/customers/me/transactions/{transactionId}/after-services",new{subject="동일 증상 재발",description="완료 후 동일 증상이 다시 발생했습니다.",requestDetails="재방문 확인 요청",desiredVisitAt=(DateTime?)null,idempotencyKey=key??Guid.NewGuid().ToString("N")});
    private static async Task<CustomerAfterServiceResponse> CreateAfterService(HttpClient client,Guid transactionId){var response=await PostAfterService(client,transactionId);Assert.Equal(HttpStatusCode.OK,response.StatusCode);return(await response.Content.ReadFromJsonAsync<CustomerAfterServiceResponse>())!;}
    private static async Task<CustomerDisputeResponse> Convert(HttpClient client,Guid id){var response=await client.PostAsJsonAsync($"/api/v1/customers/me/after-services/{id}/dispute",new{subject="A/S 미해결",reason="처리가 완료되지 않았습니다.",requestedResolution="운영 검토 요청",idempotencyKey=Guid.NewGuid().ToString("N")});Assert.Equal(HttpStatusCode.OK,response.StatusCode);return(await response.Content.ReadFromJsonAsync<CustomerDisputeResponse>())!;}
    private static async Task<CustomerReportResponse> CreateReport(HttpClient client,Guid transactionId,Guid type){var response=await client.PostAsJsonAsync("/api/v1/customers/me/reports",new{targetType="TRANSACTION",targetId=transactionId,reportTypeId=type,description="거래 관련 신고 내용을 검토해 주세요.",idempotencyKey=Guid.NewGuid().ToString("N")});Assert.Equal(HttpStatusCode.OK,response.StatusCode);return(await response.Content.ReadFromJsonAsync<CustomerReportResponse>())!;}
    private static async Task<Guid> Upload(HttpClient client,string path){using var form=new MultipartFormDataContent();using var bytes=new ByteArrayContent([0x89,0x50,0x4e,0x47,0x0d,0x0a,0x1a,0x0a]);bytes.Headers.ContentType=new MediaTypeHeaderValue("image/png");form.Add(new StringContent("고객 증빙"),"description");form.Add(bytes,"file","evidence.png");var response=await client.PostAsync(path,form);Assert.Equal(HttpStatusCode.OK,response.StatusCode);using var json=System.Text.Json.JsonDocument.Parse(await response.Content.ReadAsStringAsync());return json.RootElement.GetProperty("fileId").GetGuid();}
    private async Task<int> Count<T>() where T:class{using var scope=factory.Services.CreateScope();return await scope.ServiceProvider.GetRequiredService<SoodalLifeDbContext>().Set<T>().CountAsync();}
    private async Task<HttpClient> Customer()=>await Logged(factory.Credentials[RoleCodes.Customer]);private async Task<HttpClient> OtherCustomer()=>await Logged(factory.OtherCustomerCredential);private async Task<HttpClient> Provider()=>await Logged(factory.Credentials[RoleCodes.Provider]);private async Task<HttpClient> AreaMismatchProvider()=>await Logged(factory.AreaMismatchProviderCredential);private async Task<HttpClient> Admin()=>await Logged(factory.Credentials[RoleCodes.Admin]);
    private async Task<HttpClient> Logged(TestCredential credential){var client=factory.CreateClient(new WebApplicationFactoryClientOptions{AllowAutoRedirect=false,HandleCookies=true});var response=await client.PostAsJsonAsync("/api/v1/auth/login",new{LoginOrEmail=credential.LoginId,credential.Password});Assert.Equal(HttpStatusCode.OK,response.StatusCode);return client;}
    private sealed record Seed(Guid TransactionId,Guid HistoryId);
}
