using System.Net;
using System.Net.Http.Json;
using Microsoft.AspNetCore.Mvc.Testing;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.DependencyInjection;
using SoodalLife.Api.Domain.Entities;
using SoodalLife.Api.Features.Authentication;
using SoodalLife.Api.Features.Interior;
using SoodalLife.Api.Features.ServiceRequests;
using SoodalLife.Api.Infrastructure.Persistence;

namespace SoodalLife.Api.Tests;

public sealed class CustomerInteriorApiTests(AuthenticationWebApplicationFactory factory):IClassFixture<AuthenticationWebApplicationFactory>
{
    [Fact]
    public async Task Customer_CanDiscoverCreateListAndReadOwnProject_WhileRolesAndOtherCustomerAreProtected()
    {
        var request=await SeedRequest();using var anonymous=Client();var services=await anonymous.GetFromJsonAsync<List<InteriorServiceResponse>>("/api/v1/public/interior/services");Assert.Contains(services!,x=>x.Id==factory.Catalog.ServiceId);
        using var customer=Client();using var other=Client();using var provider=Client();await Login(customer,factory.Credentials[RoleCodes.Customer]);await Login(other,factory.OtherCustomerCredential);await Login(provider,factory.Credentials[RoleCodes.Provider]);
        var create=await customer.PostAsJsonAsync("/api/v1/customers/me/interior/projects",new{serviceRequestId=request,idempotencyKey=$"customer-project-{Guid.NewGuid():N}"});Assert.Equal(HttpStatusCode.OK,create.StatusCode);var project=(await create.Content.ReadFromJsonAsync<CustomerInteriorProjectDetail>())!;Assert.Equal("CONSULTATION",project.StatusCode);Assert.NotNull(project.RowVersion);Assert.DoesNotContain("feeAssessment",await create.Content.ReadAsStringAsync(),StringComparison.OrdinalIgnoreCase);
        Assert.Contains((await customer.GetFromJsonAsync<List<ServiceRequestListItemResponse>>("/api/v1/requests"))!,x=>x.Id==request&&x.Domain=="INTERIOR");
        Assert.Contains((await customer.GetFromJsonAsync<List<CustomerInteriorProjectListItem>>("/api/v1/customers/me/interior/projects"))!,x=>x.Id==project.Id);Assert.Equal(HttpStatusCode.NotFound,(await other.GetAsync($"/api/v1/customers/me/interior/projects/{project.Id}")).StatusCode);Assert.Equal(HttpStatusCode.Forbidden,(await provider.GetAsync("/api/v1/customers/me/interior/projects")).StatusCode);
    }

    [Fact]
    public async Task SiteVisitSelection_PreservesPreselectionPrivacy_AndCustomerReadsActualMeasurements()
    {
        var flow=await CreateProject();using var admin=flow.Admin;using var customer=flow.Customer;using var provider=Client();using var otherProvider=Client();await Login(provider,factory.Credentials[RoleCodes.Provider]);await Login(otherProvider,factory.AreaMismatchProviderCredential);var providerId=await ProviderId(factory.Credentials[RoleCodes.Provider]);_ = await SeedQuote(flow.RequestId,providerId);
        using(var scope=factory.Services.CreateScope()){var db=scope.ServiceProvider.GetRequiredService<SoodalLifeDbContext>();var request=await db.ServiceRequests.SingleAsync(x=>x.PublicId==flow.RequestId);request.DetailAddress=null;await db.SaveChangesAsync();}
        var add=await provider.PostAsJsonAsync($"/api/v1/providers/me/interior/projects/{flow.Project.Id}/site-visit-proposals",new{scheduledStartAt=DateTime.UtcNow.AddDays(1),scheduledEndAt=DateTime.UtcNow.AddDays(1).AddHours(2),proposedVisitFee=0m,proposalTerms="공동현관 호출",idempotencyKey=$"visit-{Guid.NewGuid():N}"});Assert.Equal(HttpStatusCode.OK,add.StatusCode);var proposed=await customer.GetFromJsonAsync<CustomerInteriorProjectDetail>($"/api/v1/customers/me/interior/projects/{flow.Project.Id}");var visit=Assert.Single(proposed!.SiteVisits);
        Assert.Equal(HttpStatusCode.NotFound,(await provider.GetAsync($"/api/v1/interior/site-visits/{visit.Id}")).StatusCode);var detail=await customer.GetFromJsonAsync<CustomerInteriorProjectDetail>($"/api/v1/customers/me/interior/projects/{flow.Project.Id}");Assert.True(Assert.Single(detail!.SiteVisits).CanSelect);
        Assert.Equal(HttpStatusCode.BadRequest,(await customer.PostAsJsonAsync($"/api/v1/customers/me/interior/projects/{flow.Project.Id}/site-visits/{visit.Id}/selection",new{detailAddress="",idempotencyKey=$"empty-{Guid.NewGuid():N}"})).StatusCode);
        Assert.Equal(HttpStatusCode.OK,(await customer.PostAsJsonAsync($"/api/v1/customers/me/interior/projects/{flow.Project.Id}/site-visits/{visit.Id}/selection",new{detailAddress="효동로 72-1, 3층 301호",idempotencyKey=$"select-{Guid.NewGuid():N}"})).StatusCode);var privateView=await provider.GetFromJsonAsync<ProviderSiteVisitPrivateResponse>($"/api/v1/interior/site-visits/{visit.Id}");Assert.Equal("효동로 72-1, 3층 301호",privateView!.DetailAddress);Assert.Equal(HttpStatusCode.OK,(await provider.GetAsync($"/api/v1/providers/me/interior/projects/{flow.Project.Id}")).StatusCode);Assert.Equal(HttpStatusCode.NotFound,(await otherProvider.GetAsync($"/api/v1/interior/site-visits/{visit.Id}")).StatusCode);
        var providerDetail=await provider.GetFromJsonAsync<ProviderInteriorDetail>($"/api/v1/providers/me/interior/projects/{flow.Project.Id}");var providerVisit=Assert.Single(providerDetail!.SiteVisits,x=>x.Id==visit.Id);var complete=await provider.PostAsJsonAsync($"/api/v1/providers/me/interior/site-visits/{visit.Id}/completion",new{measurementSummary="주방 실측 완료",constraint="엘리베이터 시간 제한",riskNote="가스 배관 확인",measurements=new[]{new{key="kitchen_width",value=3.4m,text=(string?)null,unit="m",location="주방",note="마감 전 기준",additionalDataJson=(string?)null}},fileIds=Array.Empty<Guid>(),idempotencyKey=$"measure-{Guid.NewGuid():N}",rowVersion=providerVisit.RowVersion});Assert.Equal(HttpStatusCode.OK,complete.StatusCode);
        detail=await customer.GetFromJsonAsync<CustomerInteriorProjectDetail>($"/api/v1/customers/me/interior/projects/{flow.Project.Id}");var measured=Assert.Single(detail!.SiteVisits);Assert.Equal("주방 실측 완료",measured.MeasurementSummary);Assert.Equal(3.4m,Assert.Single(measured.Measurements).Value);Assert.Equal("가스 배관 확인",measured.RiskNote);
    }

    [Fact]
    public async Task Customer360_ReadsQuoteDesignContractPaymentStagesChangesInspectionCompletionAndHistory()
    {
        var flow=await CreateProject();var providerId=await ProviderId(factory.Credentials[RoleCodes.Provider]);var revision=await SeedQuote(flow.RequestId,providerId);using var provider=Client();await Login(provider,factory.Credentials[RoleCodes.Provider]);await EnsureParticipant(flow.Project.Id,providerId,"DESIGN");
        var design=await provider.PostAsJsonAsync($"/api/v1/providers/me/interior/projects/{flow.Project.Id}/designs",new{title="주방 설계안",description="동선 중심 1차 설계",fileIds=Array.Empty<Guid>(),idempotencyKey=$"design-{Guid.NewGuid():N}"});Assert.Equal(HttpStatusCode.OK,design.StatusCode);Assert.Single((await design.Content.ReadFromJsonAsync<ProviderInteriorDetail>())!.Designs);await SelectProvider(flow.Customer,flow.Project.Id,revision);
        var contractFileId=await UploadProviderInteriorFile(provider,flow.Project.Id);var contractResponse=await provider.PostAsJsonAsync($"/api/v1/providers/me/interior/projects/{flow.Project.Id}/contract-records",new{contractAmount=12000000m,currencyCode="KRW",scopeSnapshotJson="{\"scope\":\"주방 리모델링\"}",scheduleSnapshotJson="{\"days\":20}",warrantySnapshotJson="{\"days\":30}",contractSignedDate=DateOnly.FromDateTime(DateTime.Today),plannedStartDate=DateOnly.FromDateTime(DateTime.Today.AddDays(3)),plannedCompletionDate=DateOnly.FromDateTime(DateTime.Today.AddDays(23)),paymentPlans=new[]{new{sequenceNo=1,name="계약 지급",amount=12000000m,dueDate=(DateOnly?)null,condition="양 당사자 직접 지급"}},contractFileIds=new[]{contractFileId},idempotencyKey=$"contract-{Guid.NewGuid():N}"});Assert.Equal(HttpStatusCode.OK,contractResponse.StatusCode);var contract=(await contractResponse.Content.ReadFromJsonAsync<ProviderInteriorDetail>())!.Contract!;
        Assert.Equal(HttpStatusCode.OK,(await flow.Customer.PostAsJsonAsync($"/api/v1/customers/me/interior/projects/{flow.Project.Id}/contracts/{contract.Id}/record-review",new{matches=true,mismatchReason=(string?)null,idempotencyKey=$"agree-c-{Guid.NewGuid():N}"})).StatusCode);
        var detail=await flow.Customer.GetFromJsonAsync<CustomerInteriorProjectDetail>($"/api/v1/customers/me/interior/projects/{flow.Project.Id}");Assert.Contains(detail!.Quotes,x=>x.PurposeCode=="POST_SITE_VISIT"&&x.Items.Count==2);Assert.Single(detail.Designs);Assert.Equal("EFFECTIVE",detail.Contract!.StatusCode);Assert.Single(detail.Contract.Versions);var plan=Assert.Single(detail.Contract.PaymentPlans);
        Assert.Equal(HttpStatusCode.OK,(await flow.Customer.PostAsJsonAsync($"/api/v1/customers/me/interior/projects/{flow.Project.Id}/payment-plans/{plan.Id}/confirmations",new{confirmationTypeCode="CUSTOMER_DIRECT_PAYMENT",amount=12000000m,confirmedAt=DateTime.UtcNow,evidenceFileId=(Guid?)null,note="전문가에게 직접 지급",idempotencyKey=$"pay-{Guid.NewGuid():N}"})).StatusCode);
        var stageResponse=await provider.PostAsJsonAsync($"/api/v1/providers/me/interior/projects/{flow.Project.Id}/stages",new{sequenceNo=1,name="철거",plannedStartDate=DateOnly.FromDateTime(DateTime.Today.AddDays(3)),plannedEndDate=DateOnly.FromDateTime(DateTime.Today.AddDays(6)),idempotencyKey=$"stage-{Guid.NewGuid():N}"});Assert.Equal(HttpStatusCode.OK,stageResponse.StatusCode);var stage=Assert.Single((await stageResponse.Content.ReadFromJsonAsync<ProviderInteriorDetail>())!.Stages);
        await provider.PostAsJsonAsync($"/api/v1/interior/stages/{stage.Id}/updates",new{progressPercent=60,updateText="철거 진행",issueText="폐기물 반출 일정 확인",fileIds=Array.Empty<Guid>(),idempotencyKey=$"update-{Guid.NewGuid():N}",rowVersion=(string?)null});var correction=await provider.PostAsJsonAsync($"/api/v1/providers/me/interior/stages/{stage.Id}/inspections",new{statusCode="CORRECTION_REQUIRED",checklistJson="{\"clean\":false}",result="보완 필요",correction="잔재물 정리",fileIds=Array.Empty<Guid>(),idempotencyKey=$"inspect-{Guid.NewGuid():N}",rowVersion=(string?)null});Assert.Equal(HttpStatusCode.OK,correction.StatusCode);
        var changeResponse=await provider.PostAsJsonAsync($"/api/v1/interior/contracts/{contract.Id}/changes",new{changeTypeCode="ADDITIONAL_WORK",reason="고객 요청",scopeChange="수납장 추가",amountDelta=500000m,scheduleImpactDays=2,idempotencyKey=$"change-{Guid.NewGuid():N}"});var change=(await changeResponse.Content.ReadFromJsonAsync<InteriorChangeResponse>())!;
        using(var scope=factory.Services.CreateScope()){var db=scope.ServiceProvider.GetRequiredService<SoodalLifeDbContext>();Assert.Equal(12000000m,(await db.InteriorContracts.SingleAsync(x=>x.PublicId==contract.Id)).ContractAmount);}Assert.Equal(HttpStatusCode.OK,(await flow.Customer.PostAsJsonAsync($"/api/v1/customers/me/interior/projects/{flow.Project.Id}/changes/{change.Id}/decision",new{approve=true,idempotencyKey=$"decide-{Guid.NewGuid():N}"})).StatusCode);
        Assert.Equal(HttpStatusCode.OK,(await provider.PostAsJsonAsync($"/api/v1/interior/stages/{stage.Id}/updates",new{progressPercent=100,updateText="철거 및 정리 완료",issueText=(string?)null,fileIds=Array.Empty<Guid>(),idempotencyKey=$"update-final-{Guid.NewGuid():N}",rowVersion=(string?)null})).StatusCode);Assert.Equal(HttpStatusCode.OK,(await provider.PostAsJsonAsync($"/api/v1/interior/projects/{flow.Project.Id}/completion-report",new{completionSummary="승인 범위 완료",finalChecklistJson="{\"handover\":true}",idempotencyKey=$"provider-complete-{Guid.NewGuid():N}",rowVersion=(string?)null})).StatusCode);var passedInspection=await provider.PostAsJsonAsync($"/api/v1/providers/me/interior/stages/{stage.Id}/inspections",new{statusCode="PASSED",checklistJson="{\"clean\":true}",result="최종 검사 통과",correction=(string?)null,fileIds=Array.Empty<Guid>(),idempotencyKey=$"inspect-final-{Guid.NewGuid():N}",rowVersion=(string?)null});Assert.Equal(HttpStatusCode.OK,passedInspection.StatusCode);var passedInspectionId=(await passedInspection.Content.ReadFromJsonAsync<ProviderInteriorDetail>())!.Inspections.Single(x=>x.StatusCode=="PASSED").Id;Assert.Equal(HttpStatusCode.OK,(await flow.Customer.PostAsJsonAsync($"/api/v1/customers/me/interior/projects/{flow.Project.Id}/inspections/{passedInspectionId}/acknowledgement",new{comment="검사 결과 확인",idempotencyKey=$"inspect-ack-{Guid.NewGuid():N}",rowVersion=(string?)null})).StatusCode);Assert.Equal(HttpStatusCode.OK,(await flow.Customer.PostAsJsonAsync($"/api/v1/customers/me/interior/projects/{flow.Project.Id}/completion-acknowledgement",new{comment="완료 확인",idempotencyKey=$"completion-ack-{Guid.NewGuid():N}",rowVersion=(string?)null})).StatusCode);detail=await flow.Customer.GetFromJsonAsync<CustomerInteriorProjectDetail>($"/api/v1/customers/me/interior/projects/{flow.Project.Id}");Assert.Equal("COMPLETED",detail!.StatusCode);Assert.Equal(12500000m,detail.Contract!.Amount);Assert.Equal(2,detail.Contract.Versions.Count);Assert.Equal(100,Assert.Single(detail.WorkStages).ProgressPercent);Assert.Contains(Assert.Single(detail.WorkStages).Inspections,x=>x.StatusCode=="CORRECTION_REQUIRED");Assert.Contains(Assert.Single(detail.WorkStages).Inspections,x=>x.StatusCode=="PASSED"&&x.AcknowledgedAt.HasValue);Assert.NotNull(detail.Completion);
    }

    [Fact]
    public async Task InteriorDefectAndDispute_ReuseCommonWorkflows_WithoutWalletFeeTrustOrSubscriptionMutation()
    {
        var flow=await CreateProject();var providerId=await ProviderId(factory.Credentials[RoleCodes.Provider]);var revision=await SeedQuote(flow.RequestId,providerId);await SelectProvider(flow.Customer,flow.Project.Id,revision);
        int wallets,ledger,fees,trustEvents,subscriptions;decimal? trust;using(var scope=factory.Services.CreateScope()){var db=scope.ServiceProvider.GetRequiredService<SoodalLifeDbContext>();wallets=await db.ProviderWallets.CountAsync();ledger=await db.WalletLedgerEntries.CountAsync();fees=await db.FeeCharges.CountAsync();trustEvents=await db.TrustScoreEvents.CountAsync();subscriptions=await db.SubscriptionContracts.CountAsync();var provider=await db.ProviderProfiles.SingleAsync(x=>x.PublicId==providerId);trust=await db.ProviderTrustScoreCurrent.Where(x=>x.ProviderProfileId==provider.Id).Select(x=>(decimal?)x.Score).SingleOrDefaultAsync();}
        var defect=await flow.Customer.PostAsJsonAsync($"/api/v1/customers/me/interior/projects/{flow.Project.Id}/defects",new{workStageId=(Guid?)null,contractVersion=1,location="주방 벽면",subject="도장 들뜸",description="완료 후 도장 들뜸이 확인됩니다.",fileIds=Array.Empty<Guid>(),idempotencyKey=$"defect-{Guid.NewGuid():N}"});Assert.Equal(HttpStatusCode.OK,defect.StatusCode);var defectDetail=await defect.Content.ReadFromJsonAsync<CustomerInteriorProjectDetail>();var dispute=await flow.Customer.PostAsJsonAsync($"/api/v1/customers/me/after-services/{defectDetail!.Defects[0].AfterServiceCaseId}/dispute",new{subject="보완 범위 확인",reason="보완 범위에 대한 중재가 필요합니다.",requestedResolution="보완 범위를 확인해 주세요.",idempotencyKey=$"dispute-{Guid.NewGuid():N}"});Assert.Equal(HttpStatusCode.OK,dispute.StatusCode);
        var detailResponse=await flow.Customer.GetAsync($"/api/v1/customers/me/interior/projects/{flow.Project.Id}");var detail=await detailResponse.Content.ReadFromJsonAsync<CustomerInteriorProjectDetail>();Assert.Single(detail!.Defects);Assert.Single(detail.Disputes);Assert.Equal(HttpStatusCode.OK,(await flow.Customer.GetAsync($"/api/v1/after-services/{detail.Defects[0].AfterServiceCaseId}")).StatusCode);Assert.Equal(HttpStatusCode.OK,(await flow.Customer.GetAsync($"/api/v1/customers/me/disputes/{detail.Disputes[0].Id}")).StatusCode);using var verifyScope=factory.Services.CreateScope();var verify=verifyScope.ServiceProvider.GetRequiredService<SoodalLifeDbContext>();var project=await verify.InteriorProjects.SingleAsync(x=>x.PublicId==flow.Project.Id);Assert.Single(await verify.AfterServiceCases.Where(x=>x.InteriorProjectId==project.Id).ToListAsync());Assert.Single(await verify.InteriorDefects.Where(x=>x.InteriorProjectId==project.Id).ToListAsync());Assert.Single(await verify.DisputeCases.Where(x=>x.InteriorProjectId==project.Id).ToListAsync());Assert.Equal(wallets,await verify.ProviderWallets.CountAsync());Assert.Equal(ledger,await verify.WalletLedgerEntries.CountAsync());Assert.Equal(fees,await verify.FeeCharges.CountAsync());Assert.Equal(trustEvents,await verify.TrustScoreEvents.CountAsync());Assert.Equal(subscriptions,await verify.SubscriptionContracts.CountAsync());var verifiedProvider=await verify.ProviderProfiles.SingleAsync(x=>x.PublicId==providerId);Assert.Equal(trust,await verify.ProviderTrustScoreCurrent.Where(x=>x.ProviderProfileId==verifiedProvider.Id).Select(x=>(decimal?)x.Score).SingleOrDefaultAsync());Assert.Equal("RESERVED_PENDING_CONTRACT",project.FeeAssessmentStatusCode);
        using var admin=Client();await Login(admin,factory.Credentials[RoleCodes.Admin]);Assert.Equal(HttpStatusCode.OK,(await admin.GetAsync("/api/v1/admin/interior/projects")).StatusCode);Assert.Equal(HttpStatusCode.OK,(await admin.GetAsync("/api/v1/admin/after-services")).StatusCode);
    }

    [Fact]
    public async Task Customer_SelectsOneLatestInteriorProvider_AndChargesFeeOnce()
    {
        var flow=await CreateProject();var providerId=await ProviderId(factory.Credentials[RoleCodes.Provider]);var revision=await SeedQuote(flow.RequestId,providerId);using var provider=Client();using var otherProvider=Client();await Login(provider,factory.Credentials[RoleCodes.Provider]);await Login(otherProvider,factory.AreaMismatchProviderCredential);
        int wallets,ledger,fees,trustEvents;using(var scope=factory.Services.CreateScope()){var before=scope.ServiceProvider.GetRequiredService<SoodalLifeDbContext>();wallets=await before.ProviderWallets.CountAsync();ledger=await before.WalletLedgerEntries.CountAsync();fees=await before.FeeCharges.CountAsync();trustEvents=await before.TrustScoreEvents.CountAsync();}
        var beforeSelection=await flow.Customer.GetFromJsonAsync<CustomerInteriorProjectDetail>($"/api/v1/customers/me/interior/projects/{flow.Project.Id}");var quote=Assert.Single(beforeSelection!.Quotes);Assert.True(quote.CanSelect);Assert.Equal(revision,quote.RevisionId);Assert.Equal(providerId,quote.ProviderId);
        var premature=await flow.Admin.PostAsJsonAsync($"/api/v1/admin/interior/projects/{flow.Project.Id}/contracts",new{providerId,quoteRevisionId=revision});Assert.Equal(HttpStatusCode.NotFound,premature.StatusCode);
        var key=$"select-provider-{Guid.NewGuid():N}";var response=await flow.Customer.PostAsJsonAsync($"/api/v1/customers/me/interior/projects/{flow.Project.Id}/provider-selection",new{quoteRevisionId=revision,rowVersion=beforeSelection.RowVersion,idempotencyKey=key});Assert.Equal(HttpStatusCode.OK,response.StatusCode);var selected=(await response.Content.ReadFromJsonAsync<CustomerInteriorProjectDetail>())!;Assert.Equal(providerId,selected.ProviderSelection!.ProviderId);Assert.Equal(revision,selected.ProviderSelection.QuoteRevisionId);Assert.Null(selected.Contract);Assert.True(Assert.Single(selected.Quotes).Selected);Assert.False(Assert.Single(selected.Quotes).CanSelect);
        Assert.Equal(HttpStatusCode.OK,(await flow.Customer.PostAsJsonAsync($"/api/v1/customers/me/interior/projects/{flow.Project.Id}/provider-selection",new{quoteRevisionId=revision,rowVersion=beforeSelection.RowVersion,idempotencyKey=key})).StatusCode);Assert.Equal(HttpStatusCode.OK,(await provider.GetAsync($"/api/v1/providers/me/interior/projects/{flow.Project.Id}")).StatusCode);Assert.Equal(HttpStatusCode.NotFound,(await otherProvider.GetAsync($"/api/v1/providers/me/interior/projects/{flow.Project.Id}")).StatusCode);Assert.Equal(HttpStatusCode.OK,(await flow.Customer.GetAsync($"/api/v1/chat/interiors/{flow.Project.Id}/room?role=PRIMARY_CONTRACTOR")).StatusCode);Assert.Equal(HttpStatusCode.OK,(await provider.GetAsync($"/api/v1/chat/interiors/{flow.Project.Id}/room?role=PRIMARY_CONTRACTOR")).StatusCode);Assert.Equal(HttpStatusCode.NotFound,(await otherProvider.GetAsync($"/api/v1/chat/interiors/{flow.Project.Id}/room?role=PRIMARY_CONTRACTOR")).StatusCode);
        using var verifyScope=factory.Services.CreateScope();var verify=verifyScope.ServiceProvider.GetRequiredService<SoodalLifeDbContext>();var project=await verify.InteriorProjects.SingleAsync(x=>x.PublicId==flow.Project.Id);Assert.Equal("RESERVED_PENDING_CONTRACT",project.FeeAssessmentStatusCode);Assert.Equal(30000m,project.ReservedFeeAmount);Assert.Null(project.CurrentContractId);Assert.Single(await verify.InteriorProjectParticipants.Where(x=>x.InteriorProjectId==project.Id&&x.RoleCode=="PRIMARY_CONTRACTOR"&&x.StatusCode=="ACTIVE").ToListAsync());Assert.Single(await verify.InteriorProjectEvents.Where(x=>x.InteriorProjectId==project.Id&&x.EventTypeCode=="CONTRACTOR_SELECTED").ToListAsync());Assert.Equal(wallets,await verify.ProviderWallets.CountAsync());Assert.Equal(ledger+1,await verify.WalletLedgerEntries.CountAsync());Assert.Equal(fees,await verify.FeeCharges.CountAsync());Assert.Equal(trustEvents,await verify.TrustScoreEvents.CountAsync());var transaction=Assert.Single(await verify.Transactions.Where(x=>x.ServiceRequestId==project.ServiceRequestId).ToListAsync());Assert.Equal(12000000m,transaction.AgreedAmount);Assert.Null(transaction.ActualChargedFeeAmount);Assert.Contains("FEE-Q7",transaction.FeePolicySnapshotJson);Assert.Empty(await verify.FeeCharges.Where(x=>x.TransactionId==transaction.Id).ToListAsync());
    }

    [Fact]
    public async Task ContractDeadline_ExpiresAfterSevenDays_AndReleasesReservedFeeToLedger()
    {
        var flow=await CreateProject();var providerId=await ProviderId(factory.Credentials[RoleCodes.Provider]);var revision=await SeedQuote(flow.RequestId,providerId);await SelectProvider(flow.Customer,flow.Project.Id,revision);
        using var scope=factory.Services.CreateScope();var db=scope.ServiceProvider.GetRequiredService<SoodalLifeDbContext>();var project=await db.InteriorProjects.SingleAsync(x=>x.PublicId==flow.Project.Id);var wallet=await db.ProviderWallets.SingleAsync(x=>x.Id==project.FeeReservationWalletId);var availableAfterReserve=wallet.AvailableBalance;var reservedAfterReserve=wallet.ReservedBalance;
        Assert.Equal("PROVIDER_SUBMISSION",project.ContractExpiryPhaseCode);Assert.NotNull(project.ContractActionDueAt);Assert.InRange(project.ContractActionDueAt!.Value,DateTime.UtcNow.AddDays(6.9),DateTime.UtcNow.AddDays(7.1));
        project.ContractActionDueAt=DateTime.UtcNow.AddMinutes(-1);await db.SaveChangesAsync();
        var processed=await scope.ServiceProvider.GetRequiredService<InteriorContractExpiryService>().ProcessDueAsync(CancellationToken.None);Assert.True(processed>=1);
        db.ChangeTracker.Clear();project=await db.InteriorProjects.SingleAsync(x=>x.PublicId==flow.Project.Id);wallet=await db.ProviderWallets.SingleAsync(x=>x.Id==project.FeeReservationWalletId);
        Assert.Equal("RELEASED",project.FeeAssessmentStatusCode);Assert.Equal("PROVIDER_CONTRACT_SUBMISSION_DEADLINE_EXPIRED",project.FeeReleaseReasonCode);Assert.Null(project.SelectedContractorProviderId);Assert.Equal("ESTIMATE_READY",project.StatusCode);Assert.NotNull(project.FeeReleaseLedgerEntryId);Assert.Equal(availableAfterReserve+project.ReservedFeeAmount,wallet.AvailableBalance);Assert.Equal(reservedAfterReserve-project.ReservedFeeAmount,wallet.ReservedBalance);
        var release=await db.WalletLedgerEntries.SingleAsync(x=>x.Id==project.FeeReleaseLedgerEntryId);Assert.Equal("RELEASE",release.EntryTypeCode);Assert.Equal(project.ReservedFeeAmount,release.Amount);
    }

    [Fact]
    public async Task ProviderSelection_RejectsOtherActorsOldRevisionAndWithdrawnQuote()
    {
        var flow=await CreateProject();var providerId=await ProviderId(factory.Credentials[RoleCodes.Provider]);var revision=await SeedQuote(flow.RequestId,providerId);using var other=Client();using var provider=Client();await Login(other,factory.OtherCustomerCredential);await Login(provider,factory.Credentials[RoleCodes.Provider]);var detail=await flow.Customer.GetFromJsonAsync<CustomerInteriorProjectDetail>($"/api/v1/customers/me/interior/projects/{flow.Project.Id}");var body=new{quoteRevisionId=revision,rowVersion=detail!.RowVersion,idempotencyKey=$"select-provider-{Guid.NewGuid():N}"};Assert.Equal(HttpStatusCode.NotFound,(await other.PostAsJsonAsync($"/api/v1/customers/me/interior/projects/{flow.Project.Id}/provider-selection",body)).StatusCode);Assert.Equal(HttpStatusCode.Forbidden,(await provider.PostAsJsonAsync($"/api/v1/customers/me/interior/projects/{flow.Project.Id}/provider-selection",body)).StatusCode);
        using(var scope=factory.Services.CreateScope()){var db=scope.ServiceProvider.GetRequiredService<SoodalLifeDbContext>();var first=await db.QuoteRevisions.SingleAsync(x=>x.PublicId==revision);db.QuoteRevisions.Add(new(){QuoteId=first.QuoteId,RevisionNo=2,RevisionPurposeCode="POST_SITE_VISIT",Summary="최신 상세견적",SubtotalAmount=first.SubtotalAmount,VatAmount=first.VatAmount,TotalAmount=first.TotalAmount,CurrencyCode=first.CurrencyCode,ValidUntil=DateTime.UtcNow.AddDays(7),SubmittedAt=DateTime.UtcNow,SubmittedByUserId=first.SubmittedByUserId,IdempotencyKey=$"quote-{Guid.NewGuid():N}"});await db.SaveChangesAsync();}
        Assert.Equal(HttpStatusCode.Conflict,(await flow.Customer.PostAsJsonAsync($"/api/v1/customers/me/interior/projects/{flow.Project.Id}/provider-selection",new{quoteRevisionId=revision,rowVersion=detail.RowVersion,idempotencyKey=$"old-{Guid.NewGuid():N}"})).StatusCode);using(var scope=factory.Services.CreateScope()){var db=scope.ServiceProvider.GetRequiredService<SoodalLifeDbContext>();var requestId=await db.ServiceRequests.Where(x=>x.PublicId==flow.RequestId).Select(x=>x.Id).SingleAsync();var quote=await db.Quotes.SingleAsync(x=>x.ServiceRequestId==requestId);quote.WithdrawnAt=DateTime.UtcNow;await db.SaveChangesAsync();}Assert.Empty((await flow.Customer.GetFromJsonAsync<CustomerInteriorProjectDetail>($"/api/v1/customers/me/interior/projects/{flow.Project.Id}"))!.Quotes);
    }

    [Fact]
    public async Task ProviderSelection_BlocksSecondSelectionAndAdminReadsSnapshot()
    {
        var flow=await CreateProject();var providerId=await ProviderId(factory.Credentials[RoleCodes.Provider]);var revision=await SeedQuote(flow.RequestId,providerId);await SelectProvider(flow.Customer,flow.Project.Id,revision);var detail=await flow.Customer.GetFromJsonAsync<CustomerInteriorProjectDetail>($"/api/v1/customers/me/interior/projects/{flow.Project.Id}");Assert.Equal(HttpStatusCode.Conflict,(await flow.Customer.PostAsJsonAsync($"/api/v1/customers/me/interior/projects/{flow.Project.Id}/provider-selection",new{quoteRevisionId=revision,rowVersion=detail!.RowVersion,idempotencyKey=$"second-{Guid.NewGuid():N}"})).StatusCode);var admin=await flow.Admin.GetFromJsonAsync<InteriorProjectDetail>($"/api/v1/admin/interior/projects/{flow.Project.Id}");Assert.Equal(revision,admin!.SelectedQuoteRevisionId);Assert.Equal(1,admin.SelectedQuoteRevisionNo);Assert.NotNull(admin.ContractorSelectedAt);Assert.Empty(admin.Contracts);
    }

    [Fact]
    public async Task ProviderSelection_ExcludesAndRejectsProviderWithoutAreaEligibility()
    {
        var flow=await CreateProject();var providerId=await ProviderId(factory.AreaMismatchProviderCredential);var revision=await SeedQuote(flow.RequestId,providerId);var detail=await flow.Customer.GetFromJsonAsync<CustomerInteriorProjectDetail>($"/api/v1/customers/me/interior/projects/{flow.Project.Id}");Assert.Empty(detail!.Quotes);var response=await flow.Customer.PostAsJsonAsync($"/api/v1/customers/me/interior/projects/{flow.Project.Id}/provider-selection",new{quoteRevisionId=revision,rowVersion=detail.RowVersion,idempotencyKey=$"ineligible-{Guid.NewGuid():N}"});Assert.Equal(HttpStatusCode.Conflict,response.StatusCode);
    }

    private async Task<Flow> CreateProject(){var request=await SeedRequest();var customer=Client();var admin=Client();await Login(customer,factory.Credentials[RoleCodes.Customer]);await Login(admin,factory.Credentials[RoleCodes.Admin]);var response=await customer.PostAsJsonAsync("/api/v1/customers/me/interior/projects",new{serviceRequestId=request,idempotencyKey=$"create-{Guid.NewGuid():N}"});Assert.Equal(HttpStatusCode.OK,response.StatusCode);return new(customer,admin,(await response.Content.ReadFromJsonAsync<CustomerInteriorProjectDetail>())!,request);}
    private async Task<Guid> SeedRequest(){using var scope=factory.Services.CreateScope();var db=scope.ServiceProvider.GetRequiredService<SoodalLifeDbContext>();var service=await db.ServiceCategories.SingleAsync(x=>x.PublicId==factory.Catalog.ServiceId);service.ExternalCode="INT-TEST";var middle=await db.ServiceCategories.SingleAsync(x=>x.Id==service.ParentId);var major=await db.ServiceCategories.SingleAsync(x=>x.Id==middle.ParentId);major.Name="인테리어";var customer=await(from user in db.Users join profile in db.CustomerProfiles on user.Id equals profile.UserId where user.LoginId==factory.Credentials[RoleCodes.Customer].LoginId select new{user,profile}).SingleAsync();customer.user.Phone="010-2468-1357";var policy=await db.CategoryPolicies.FirstAsync(x=>x.CategoryId==service.Id);var area=await db.AdministrativeAreas.SingleAsync(x=>x.PublicId==factory.Catalog.AreaId);var now=DateTime.UtcNow;await EnsureInteriorFeePolicy(db,service.Id,now);var request=new ServiceRequest{CustomerProfileId=customer.profile.Id,CategoryId=service.Id,CategoryPolicyId=policy.Id,AdministrativeAreaId=area.Id,DetailAddress="101동 1203호",Title=$"인테리어 상담 {Guid.NewGuid():N}",Description="주방과 거실 공사를 요청합니다.",StatusCode="OPEN",PolicySnapshotJson="{}",OpenedAt=now,CreatedAt=now,CreatedByUserId=customer.user.Id,UpdatedAt=now,UpdatedByUserId=customer.user.Id};db.ServiceRequests.Add(request);await db.SaveChangesAsync();return request.PublicId;}
    private static async Task EnsureInteriorFeePolicy(SoodalLifeDbContext db,long categoryId,DateTime now)
    {
        var tiers=new[]{("FEE-Q1",0m,49999m,1000m),("FEE-Q2",50000m,99999m,2000m),("FEE-Q3",100000m,199999m,3000m),("FEE-Q4",200000m,499999m,5000m),("FEE-Q5",500000m,999999m,10000m),("FEE-Q6",1000000m,2999999m,20000m),("FEE-Q7",3000000m,999999999m,30000m)};
        foreach(var tier in tiers)
        {
            if(!await db.FeePolicies.AnyAsync(x=>x.Code==tier.Item1))db.FeePolicies.Add(new FeePolicy{Code=tier.Item1,PolicyKindCode="QUOTE",TransactionTypeCode="ONE_TIME",AppliesToText="선택 견적금액 구간",CalculationMethodText="FIXED_BY_SELECTED_QUOTE_AMOUNT",MinBaseAmount=tier.Item2,MaxBaseAmount=tier.Item3,DisplayFeeAmount=tier.Item4,CurrencyCode="KRW",ChargeTimingText="고객 최종 시공업체 선택 시",RestoreRuleText="승인된 복원 사유 시 FeeRestore",EffectiveFrom=DateOnly.FromDateTime(now),IsActive=true,CreatedAt=now,UpdatedAt=now});
        }
        var source=await db.FeePolicies.SingleOrDefaultAsync(x=>x.Code=="FEE-I1");
        if(source is null){source=new FeePolicy{Code="FEE-I1",PolicyKindCode="PROJECT",TransactionTypeCode="PROJECT",AppliesToText="인테리어 최종 시공업체 선택",CalculationMethodText="SELECTED_QUOTE_TIER:FEE-Q1-FEE-Q7",MinBaseAmount=0,MaxBaseAmount=999999999,DisplayFeeAmount=0,CurrencyCode="KRW",ChargeTimingText="고객이 최종 시공업체의 유효한 최신 견적을 선택할 때",RestoreRuleText="법정 청약철회·업무 시작 전 고객 취소·허위/중복 요청·시스템 오류·관리자 승인 사유",EffectiveFrom=DateOnly.FromDateTime(now),IsActive=true,CreatedAt=now,UpdatedAt=now};db.FeePolicies.Add(source);}
        await db.SaveChangesAsync();
        if(!await db.CategoryFeePolicies.AnyAsync(x=>x.CategoryId==categoryId&&x.SourceFeePolicyId==source.Id))db.CategoryFeePolicies.Add(new CategoryFeePolicy{CategoryId=categoryId,SourceFeePolicyId=source.Id,PolicyVersion="FEE-I1-v1.0",PolicyKindCode="PROJECT",TransactionTypeCode="PROJECT",CalculationMethodText="SELECTED_QUOTE_TIER:FEE-Q1-FEE-Q7",FeeAmount=null,MinBaseAmount=0,MaxBaseAmount=999999999,CurrencyCode="KRW",ChargeTimingText=source.ChargeTimingText,RestoreRuleText=source.RestoreRuleText,EffectiveFrom=DateOnly.FromDateTime(now),IsActive=true,CreatedAt=now,UpdatedAt=now});
        foreach(var wallet in await db.ProviderWallets.ToListAsync())if(wallet.AvailableBalance<1000000m)wallet.AvailableBalance=1000000m;
        await db.SaveChangesAsync();
    }
    private async Task<Guid> SeedQuote(Guid requestId,Guid providerId){using var scope=factory.Services.CreateScope();var db=scope.ServiceProvider.GetRequiredService<SoodalLifeDbContext>();var request=await db.ServiceRequests.SingleAsync(x=>x.PublicId==requestId);var project=await db.InteriorProjects.SingleAsync(x=>x.ServiceRequestId==request.Id);project.StatusCode="ESTIMATE_READY";var provider=await db.ProviderProfiles.SingleAsync(x=>x.PublicId==providerId);var now=DateTime.UtcNow;var quote=new Quote{ServiceRequestId=request.Id,ProviderProfileId=provider.Id,RequestDispatchId=0,StatusCode="SUBMITTED",SubmittedAt=now,ExpiresAt=now.AddDays(7),CreatedAt=now,UpdatedAt=now};db.Quotes.Add(quote);await db.SaveChangesAsync();var revision=new QuoteRevision{QuoteId=quote.Id,RevisionNo=1,RevisionPurposeCode="POST_SITE_VISIT",Summary="실측 후 상세견적",Terms="철거와 폐기 포함",SubtotalAmount=10909091m,VatAmount=1090909m,TotalAmount=12000000m,CurrencyCode="KRW",EstimatedDurationText="20일",ValidUntil=now.AddDays(7),SubmittedAt=now,SubmittedByUserId=provider.UserId,IdempotencyKey=$"quote-{Guid.NewGuid():N}"};db.QuoteRevisions.Add(revision);await db.SaveChangesAsync();db.QuoteItems.AddRange(new QuoteItem{QuoteRevisionId=revision.Id,LineNo=1,ItemName="철거",Quantity=1,UnitText="식",UnitPriceAmount=2000000,LineTotalAmount=2000000,CurrencyCode="KRW",WorkTradeText="철거",SpaceText="주방",LaborNoteText="폐기물 포함"},new QuoteItem{QuoteRevisionId=revision.Id,LineNo=2,ItemName="수납장",Quantity=1,UnitText="식",UnitPriceAmount=10000000,LineTotalAmount=10000000,CurrencyCode="KRW",WorkTradeText="목공",SpaceText="주방",MaterialSpecText="친환경 자재"});await db.SaveChangesAsync();return revision.PublicId;}
    private async Task SelectProvider(HttpClient customer,Guid projectId,Guid quoteRevisionId){var detail=await customer.GetFromJsonAsync<CustomerInteriorProjectDetail>($"/api/v1/customers/me/interior/projects/{projectId}");var response=await customer.PostAsJsonAsync($"/api/v1/customers/me/interior/projects/{projectId}/provider-selection",new{quoteRevisionId,rowVersion=detail!.RowVersion,idempotencyKey=$"select-provider-{Guid.NewGuid():N}"});Assert.Equal(HttpStatusCode.OK,response.StatusCode);}
    private async Task EnsureParticipant(Guid projectId,Guid providerId,string role){using var scope=factory.Services.CreateScope();var db=scope.ServiceProvider.GetRequiredService<SoodalLifeDbContext>();var project=await db.InteriorProjects.SingleAsync(x=>x.PublicId==projectId);var provider=await db.ProviderProfiles.SingleAsync(x=>x.PublicId==providerId);if(!await db.InteriorProjectParticipants.AnyAsync(x=>x.InteriorProjectId==project.Id&&x.ProviderProfileId==provider.Id&&x.RoleCode==role&&x.StatusCode=="ACTIVE"))db.InteriorProjectParticipants.Add(new(){InteriorProjectId=project.Id,ProviderProfileId=provider.Id,RoleCode=role,EffectiveFrom=DateTime.UtcNow.AddMinutes(-1),StatusCode="ACTIVE",ScopeText="자동 테스트 역할",CreatedAt=DateTime.UtcNow,UpdatedAt=DateTime.UtcNow});await db.SaveChangesAsync();}
    private async Task<Guid> ProviderId(TestCredential credential){using var scope=factory.Services.CreateScope();var db=scope.ServiceProvider.GetRequiredService<SoodalLifeDbContext>();return await(from user in db.Users join provider in db.ProviderProfiles on user.Id equals provider.UserId where user.LoginId==credential.LoginId select provider.PublicId).SingleAsync();}
    private static async Task<Guid> UploadProviderInteriorFile(HttpClient provider,Guid projectId){using var form=new MultipartFormDataContent();using var bytes=new ByteArrayContent(TestFileSamples.ValidJpeg());bytes.Headers.ContentType=new("image/jpeg");form.Add(bytes,"file","signed-contract.jpg");var response=await provider.PostAsync($"/api/v1/providers/me/interior/projects/{projectId}/files",form);Assert.Equal(HttpStatusCode.OK,response.StatusCode);return (await response.Content.ReadFromJsonAsync<ProviderInteriorUpload>())!.FileId;}
    private HttpClient Client()=>factory.CreateClient(new WebApplicationFactoryClientOptions{AllowAutoRedirect=false,HandleCookies=true});private static async Task Login(HttpClient client,TestCredential value)=>Assert.Equal(HttpStatusCode.OK,(await client.PostAsJsonAsync("/api/v1/auth/login",new{LoginOrEmail=value.LoginId,value.Password})).StatusCode);
    private sealed record Flow(HttpClient Customer,HttpClient Admin,CustomerInteriorProjectDetail Project,Guid RequestId);
}
