using System.Security.Claims;
using Microsoft.AspNetCore.Http;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Diagnostics;
using SoodalLife.Api.Domain.Entities;
using SoodalLife.Api.Features.Emergency;
using SoodalLife.Api.Infrastructure.Persistence;

namespace SoodalLife.Api.Tests;

public sealed class EmergencyWorkflowTests
{
    [Fact] public async Task Resolver_allows_enabled_service_in_24_hour_slot()
    { await using var db=Context();var f=await SeedAvailability(db,true,true);var result=await new EmergencyAvailabilityResolver(db).EvaluateAsync(f.Provider.Id,f.Category.Id,f.Area.Id,DateTime.UtcNow,default);Assert.True(result.IsAvailable); }
    [Fact] public async Task Availability_summary_uses_active_area_after_provider_replaces_old_area()
    { await using var db=Context();var f=await SeedAvailability(db,true,true);var oldArea=await db.ProviderServiceAreas.SingleAsync();oldArea.StatusCode="INACTIVE";oldArea.DeactivatedAt=DateTime.UtcNow;var replacement=new AdministrativeArea{PublicId=Guid.NewGuid(),AreaCode="B",AreaName="replacement",AreaLevelCode="SIGUNGU",IsActive=true};db.AdministrativeAreas.Add(replacement);await db.SaveChangesAsync();var providerServiceId=await db.ProviderServiceCategories.Select(x=>x.Id).SingleAsync();db.ProviderServiceAreas.Add(new(){ProviderServiceCategoryId=providerServiceId,AdministrativeAreaId=replacement.Id,StatusCode="ACTIVE",ActivatedAt=DateTime.UtcNow,CreatedAt=DateTime.UtcNow,UpdatedAt=DateTime.UtcNow});await db.SaveChangesAsync();var result=await new ProviderEmergencyAvailabilityService(db,new EmergencyAvailabilityResolver(db)).GetAsync(Principal(f.User.PublicId),default);Assert.True(result.IsCurrentlyAvailable);Assert.Equal("AVAILABLE",result.CurrentAvailabilityReason); }
    [Fact] public async Task Availability_summary_is_available_when_any_enabled_service_is_available()
    { await using var db=Context();var f=await SeedAvailability(db,true,true);db.ProviderServiceAreas.RemoveRange(db.ProviderServiceAreas);var secondCategory=new ServiceCategory{PublicId=Guid.NewGuid(),LevelCode="SERVICE",Name="second",StatusCode="ACTIVE"};var secondArea=new AdministrativeArea{PublicId=Guid.NewGuid(),AreaCode="C",AreaName="second area",AreaLevelCode="SIGUNGU",IsActive=true};db.AddRange(secondCategory,secondArea);await db.SaveChangesAsync();db.CategoryPolicies.Add(new(){CategoryId=secondCategory.Id,PolicyVersion="v2",TransactionTypeCode="ONE_TIME",IsEmergencyAllowed=true,EffectiveFrom=DateOnly.FromDateTime(DateTime.UtcNow)});var secondService=new ProviderServiceCategory{ProviderProfileId=f.Provider.Id,CategoryId=secondCategory.Id,StatusCode="ACTIVE",ActivatedAt=DateTime.UtcNow,CreatedAt=DateTime.UtcNow,UpdatedAt=DateTime.UtcNow};db.ProviderServiceCategories.Add(secondService);await db.SaveChangesAsync();db.ProviderServiceAreas.Add(new(){ProviderServiceCategoryId=secondService.Id,AdministrativeAreaId=secondArea.Id,StatusCode="ACTIVE",ActivatedAt=DateTime.UtcNow,CreatedAt=DateTime.UtcNow,UpdatedAt=DateTime.UtcNow});var secondSetting=new ProviderEmergencyServiceSetting{ProviderEmergencySettingId=f.Setting.Id,ProviderServiceCategoryId=secondService.Id,IsEnabled=true,CreatedAt=DateTime.UtcNow,UpdatedAt=DateTime.UtcNow};db.ProviderEmergencyServiceSettings.Add(secondSetting);await db.SaveChangesAsync();db.ProviderEmergencyAvailabilitySlots.Add(new(){ProviderEmergencyServiceSettingId=secondSetting.Id,DayOfWeek=(byte)TimeZoneInfo.ConvertTimeFromUtc(DateTime.UtcNow,TimeZoneInfo.Local).DayOfWeek,Is24Hours=true,CreatedAt=DateTime.UtcNow});await db.SaveChangesAsync();var result=await new ProviderEmergencyAvailabilityService(db,new EmergencyAvailabilityResolver(db)).GetAsync(Principal(f.User.PublicId),default);Assert.True(result.IsCurrentlyAvailable);Assert.Equal("AVAILABLE",result.CurrentAvailabilityReason); }
    [Fact] public async Task Resolver_blocks_provider_level_off()
    { await using var db=Context();var f=await SeedAvailability(db,false,true);var result=await new EmergencyAvailabilityResolver(db).EvaluateAsync(f.Provider.Id,f.Category.Id,f.Area.Id,DateTime.UtcNow,default);Assert.Equal("EMERGENCY_DISABLED",result.ReasonCode); }
    [Fact] public async Task Resolver_blocks_service_level_off()
    { await using var db=Context();var f=await SeedAvailability(db,true,false);var result=await new EmergencyAvailabilityResolver(db).EvaluateAsync(f.Provider.Id,f.Category.Id,f.Area.Id,DateTime.UtcNow,default);Assert.Equal("EMERGENCY_SERVICE_DISABLED",result.ReasonCode); }
    [Fact] public async Task Resolver_blocks_temporary_unavailability()
    { await using var db=Context();var f=await SeedAvailability(db,true,true);f.Setting.TemporarilyUnavailableUntil=DateTime.UtcNow.AddHours(1);await db.SaveChangesAsync();var result=await new EmergencyAvailabilityResolver(db).EvaluateAsync(f.Provider.Id,f.Category.Id,f.Area.Id,DateTime.UtcNow,default);Assert.Equal("EMERGENCY_TEMPORARILY_UNAVAILABLE",result.ReasonCode); }
    [Fact] public async Task Resolver_blocks_exception_before_regular_hours()
    { await using var db=Context();var f=await SeedAvailability(db,true,true);db.ProviderEmergencyExceptions.Add(new(){ProviderEmergencySettingId=f.Setting.Id,StartsAt=DateTime.UtcNow.AddMinutes(-1),EndsAt=DateTime.UtcNow.AddMinutes(10),CreatedAt=DateTime.UtcNow});await db.SaveChangesAsync();var result=await new EmergencyAvailabilityResolver(db).EvaluateAsync(f.Provider.Id,f.Category.Id,f.Area.Id,DateTime.UtcNow,default);Assert.Equal("EMERGENCY_EXCEPTION_ACTIVE",result.ReasonCode); }
    [Fact] public async Task Resolver_blocks_head_office_disallowed_emergency_category()
    { await using var db=Context();var f=await SeedAvailability(db,true,true);f.Policy.IsEmergencyAllowed=false;await db.SaveChangesAsync();var resolver=new EmergencyAvailabilityResolver(db);var result=await resolver.EvaluateAsync(f.Provider.Id,f.Category.Id,f.Area.Id,DateTime.UtcNow,default);Assert.False(result.IsAvailable);Assert.Equal("EMERGENCY_CATEGORY_NOT_ALLOWED",result.ReasonCode);var setting=await new ProviderEmergencyAvailabilityService(db,resolver).GetAsync(Principal(f.User.PublicId),default);Assert.Empty(setting.Services); }
    [Fact] public async Task Temporary_pause_set_and_release_are_returned_in_history()
    { await using var db=Context();var f=await SeedAvailability(db,true,true);var service=new ProviderEmergencyAvailabilityService(db,new EmergencyAvailabilityResolver(db));var current=await service.GetAsync(Principal(f.User.PublicId),default);var services=current.Services.Select(x=>new EmergencyServiceSettingInput(x.ProviderServiceCategoryId,x.IsEnabled,x.Slots.Select(slot=>new EmergencyAvailabilitySlotInput(slot.DayOfWeek,slot.StartTime,slot.EndTime,slot.Is24Hours)).ToArray())).ToArray();var paused=await service.UpdateAsync(Principal(f.User.PublicId),new(true,DateTime.UtcNow.AddHours(2),"장비 점검",services,[],current.RowVersion),default);Assert.Equal("EMERGENCY_PAUSE_SET",paused.PauseHistory.Single().Action);Assert.Equal("장비 점검",paused.PauseHistory.Single().Reason);var released=await service.UpdateAsync(Principal(f.User.PublicId),new(true,null,null,services,[],paused.RowVersion),default);Assert.Equal(2,released.PauseHistory.Count);Assert.Equal("EMERGENCY_PAUSE_RELEASED",released.PauseHistory[0].Action);Assert.Null(released.PauseHistory[0].UnavailableUntil); }
    [Fact] public async Task Provider_cannot_respond_to_another_providers_dispatch()
    { await using var db=Context();var f=await SeedDispatch(db);var other=new User{PublicId=Guid.NewGuid(),LoginId="other",StatusCode="ACTIVE"};db.Users.Add(other);await db.SaveChangesAsync();db.ProviderProfiles.Add(new(){UserId=other.Id,BusinessName="other",ApprovalStatusCode="APPROVED",ActivityStatusCode="ACTIVE"});await db.SaveChangesAsync();var service=new EmergencyWorkflowService(db,null!);var error=await Assert.ThrowsAsync<EmergencyWorkflowException>(()=>service.Respond(Principal(other.PublicId),f.Request.PublicId,new(true,20,null,null,"other-key",""),default));Assert.Equal(StatusCodes.Status404NotFound,error.StatusCode); }
    [Fact] public async Task Available_response_requires_eta()
    { await using var db=Context();var f=await SeedDispatch(db);var service=new EmergencyWorkflowService(db,null!);var error=await Assert.ThrowsAsync<EmergencyWorkflowException>(()=>service.Respond(Principal(f.User.PublicId),f.Request.PublicId,new(true,null,null,null,"eta-key",""),default));Assert.Equal("EMERGENCY_ETA_REQUIRED",error.BusinessCode); }
    [Fact] public async Task Response_retry_is_idempotent()
    { await using var db=Context();var f=await SeedDispatch(db);var service=new EmergencyWorkflowService(db,null!);var first=await service.Respond(Principal(f.User.PublicId),f.Request.PublicId,new(true,20,null,"주차 확인","same-key",""),default);var second=await service.Respond(Principal(f.User.PublicId),f.Request.PublicId,new(true,20,null,"주차 확인","same-key",""),default);Assert.Equal(first.Id,second.Id);Assert.Single(db.EmergencyResponses); }
    [Fact] public async Task Response_update_rejects_stale_row_version()
    { await using var db=Context();var f=await SeedDispatch(db);var service=new EmergencyWorkflowService(db,null!);await service.Respond(Principal(f.User.PublicId),f.Request.PublicId,new(true,20,null,null,"first-key",""),default);var error=await Assert.ThrowsAsync<EmergencyWorkflowException>(()=>service.Respond(Principal(f.User.PublicId),f.Request.PublicId,new(true,25,null,null,"second-key","AQ=="),default));Assert.Equal("ROW_VERSION_CONFLICT",error.BusinessCode); }
    [Fact] public async Task Emergency_progress_events_are_append_only()
    { await using var db=Context();var user=new User{PublicId=Guid.NewGuid(),LoginId="u",StatusCode="ACTIVE"};db.Users.Add(user);await db.SaveChangesAsync();var category=new ServiceCategory{LevelCode="SERVICE",Name="c",StatusCode="ACTIVE"};db.ServiceCategories.Add(category);var customer=new CustomerProfile{UserId=user.Id};var provider=new ProviderProfile{UserId=user.Id,BusinessName="p"};db.CustomerProfiles.Add(customer);db.ProviderProfiles.Add(provider);await db.SaveChangesAsync();var request=new ServiceRequest{CustomerProfileId=customer.Id,CategoryId=category.Id,CategoryPolicyId=1,Title="e",PolicySnapshotJson="{}",CreatedAt=DateTime.UtcNow,UpdatedAt=DateTime.UtcNow};db.ServiceRequests.Add(request);await db.SaveChangesAsync();var quote=new Quote{ServiceRequestId=request.Id,ProviderProfileId=provider.Id,RequestDispatchId=1,CreatedAt=DateTime.UtcNow,UpdatedAt=DateTime.UtcNow};db.Quotes.Add(quote);await db.SaveChangesAsync();var revision=new QuoteRevision{QuoteId=quote.Id,Summary="e",ValidUntil=DateTime.UtcNow.AddHours(1),SubmittedAt=DateTime.UtcNow,SubmittedByUserId=user.Id,IdempotencyKey="r"};db.QuoteRevisions.Add(revision);await db.SaveChangesAsync();var transaction=new TransactionRecord{ServiceRequestId=request.Id,AcceptedQuoteRevisionId=revision.Id,CustomerProfileId=customer.Id,ProviderProfileId=provider.Id,CategoryId=category.Id,QuoteSnapshotJson="{}",CategoryPolicySnapshotJson="{}",CompletionPolicySnapshotJson="{}",CreatedAt=DateTime.UtcNow,UpdatedAt=DateTime.UtcNow};db.Transactions.Add(transaction);await db.SaveChangesAsync();var progress=new EmergencyProgressEvent{TransactionId=transaction.Id,ActorUserId=user.Id,EventTypeCode="DEPARTED",OccurredAt=DateTime.UtcNow,IdempotencyKey="p"};db.EmergencyProgressEvents.Add(progress);await db.SaveChangesAsync();progress.Note="changed";await Assert.ThrowsAsync<InvalidOperationException>(()=>db.SaveChangesAsync()); }

    private static SoodalLifeDbContext Context()=>new(new DbContextOptionsBuilder<SoodalLifeDbContext>().UseInMemoryDatabase(Guid.NewGuid().ToString()).ConfigureWarnings(warnings=>warnings.Ignore(CoreEventId.ManyServiceProvidersCreatedWarning)).Options);
    private static ClaimsPrincipal Principal(Guid id)=>new(new ClaimsIdentity([new Claim(ClaimTypes.NameIdentifier,id.ToString())],"test"));
    private static async Task<(User User,ProviderProfile Provider,ServiceCategory Category,CategoryPolicy Policy,AdministrativeArea Area,ProviderEmergencySetting Setting)> SeedAvailability(SoodalLifeDbContext db,bool overall,bool serviceEnabled)
    {var user=new User{PublicId=Guid.NewGuid(),LoginId="provider",StatusCode="ACTIVE"};db.Users.Add(user);await db.SaveChangesAsync();var provider=new ProviderProfile{UserId=user.Id,BusinessName="provider",ApprovalStatusCode="APPROVED",ActivityStatusCode="ACTIVE"};var category=new ServiceCategory{PublicId=Guid.NewGuid(),LevelCode="SERVICE",Name="emergency",StatusCode="ACTIVE"};var area=new AdministrativeArea{PublicId=Guid.NewGuid(),AreaCode="A",AreaName="area",AreaLevelCode="SIGUNGU",IsActive=true};db.AddRange(provider,category,area);await db.SaveChangesAsync();var policy=new CategoryPolicy{CategoryId=category.Id,PolicyVersion="v",TransactionTypeCode="ONE_TIME",RequestMethodText="x",OnsiteRequirementText="x",IsEmergencyAllowed=true,SubscriptionOptionText="x",StandardWorkUnitText="x",PriceMethodText="x",VatDisplayRuleText="x",FeePolicyId=1,FeeChargeTimingText="x",FeeRestoreConditionText="x",MatchingAreaRuleText="x",NotificationTargetRuleText="x",RequestFieldSummaryText="x",RequiredQualificationSummaryText="x",InsuranceRequirementText="x",SafetyGradeCode="LOW",CompletionEvidenceRuleText="x",TrustScoreDisplayText="x",ServiceAreaLevelCode="SIGUNGU",EffectiveFrom=DateOnly.FromDateTime(DateTime.UtcNow),CreatedAt=DateTime.UtcNow,UpdatedAt=DateTime.UtcNow};var psc=new ProviderServiceCategory{ProviderProfileId=provider.Id,CategoryId=category.Id,StatusCode="ACTIVE",ActivatedAt=DateTime.UtcNow,CreatedAt=DateTime.UtcNow,UpdatedAt=DateTime.UtcNow};db.AddRange(policy,psc);await db.SaveChangesAsync();db.AddRange(new ProviderServiceApproval{ProviderServiceCategoryId=psc.Id,ApprovalStatusCode="APPROVED",ApprovalRequestedAt=DateTime.UtcNow,CreatedAt=DateTime.UtcNow,UpdatedAt=DateTime.UtcNow},new ProviderServiceArea{ProviderServiceCategoryId=psc.Id,AdministrativeAreaId=area.Id,StatusCode="ACTIVE",ActivatedAt=DateTime.UtcNow,CreatedAt=DateTime.UtcNow,UpdatedAt=DateTime.UtcNow});var setting=new ProviderEmergencySetting{ProviderProfileId=provider.Id,IsEnabled=overall,CreatedAt=DateTime.UtcNow,UpdatedAt=DateTime.UtcNow};db.Add(setting);await db.SaveChangesAsync();var service=new ProviderEmergencyServiceSetting{ProviderEmergencySettingId=setting.Id,ProviderServiceCategoryId=psc.Id,IsEnabled=serviceEnabled,CreatedAt=DateTime.UtcNow,UpdatedAt=DateTime.UtcNow};db.Add(service);await db.SaveChangesAsync();db.Add(new ProviderEmergencyAvailabilitySlot{ProviderEmergencyServiceSettingId=service.Id,DayOfWeek=(byte)TimeZoneInfo.ConvertTimeFromUtc(DateTime.UtcNow,TimeZoneInfo.Local).DayOfWeek,Is24Hours=true,CreatedAt=DateTime.UtcNow});await db.SaveChangesAsync();return(user,provider,category,policy,area,setting);}
    private static async Task<(User User,ProviderProfile Provider,ServiceRequest Request,RequestDispatch Dispatch)> SeedDispatch(SoodalLifeDbContext db)
    {var f=await SeedAvailability(db,true,true);var customerUser=new User{PublicId=Guid.NewGuid(),LoginId="customer",StatusCode="ACTIVE"};db.Users.Add(customerUser);await db.SaveChangesAsync();var customer=new CustomerProfile{UserId=customerUser.Id};db.CustomerProfiles.Add(customer);await db.SaveChangesAsync();var request=new ServiceRequest{PublicId=Guid.NewGuid(),CustomerProfileId=customer.Id,CategoryId=f.Category.Id,CategoryPolicyId=f.Policy.Id,AdministrativeAreaId=f.Area.Id,Title="urgent",Description="summary",StatusCode="OPEN",IsUrgent=true,PolicySnapshotJson="{}",OpenedAt=DateTime.UtcNow,ExpiresAt=DateTime.UtcNow.AddHours(1),CreatedAt=DateTime.UtcNow,UpdatedAt=DateTime.UtcNow};db.ServiceRequests.Add(request);await db.SaveChangesAsync();var candidate=new DispatchCandidate{ServiceRequestId=request.Id,ProviderProfileId=f.Provider.Id,StatusCode="DISPATCHED",CategoryMatch=true,AreaMatch=true,ApprovalMatch=true,EvaluatedAt=DateTime.UtcNow,CreatedAt=DateTime.UtcNow};db.DispatchCandidates.Add(candidate);await db.SaveChangesAsync();var dispatch=new RequestDispatch{ServiceRequestId=request.Id,ProviderProfileId=f.Provider.Id,CandidateId=candidate.Id,StatusCode="AVAILABLE",AvailableAt=DateTime.UtcNow,ExpiresAt=DateTime.UtcNow.AddHours(1),IdempotencyKey=Guid.NewGuid().ToString(),CreatedAt=DateTime.UtcNow};db.RequestDispatches.Add(dispatch);await db.SaveChangesAsync();return(f.User,f.Provider,request,dispatch);}
}
