using System.Net;
using System.Net.Http.Json;
using Microsoft.AspNetCore.Mvc.Testing;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.DependencyInjection;
using SoodalLife.Api.Domain.Entities;
using SoodalLife.Api.Features.Authentication;
using SoodalLife.Api.Features.Interior;
using SoodalLife.Api.Infrastructure.Persistence;

namespace SoodalLife.Api.Tests;

public sealed class InteriorProjectCoreApiTests(AuthenticationWebApplicationFactory factory):IClassFixture<AuthenticationWebApplicationFactory>
{
    [Fact]
    public async Task Admin_CreatesInteriorProject_AndOtherRolesCannotUseAdminApi()
    {
        var request=await SeedRequest();using var admin=Client();using var customer=Client();using var provider=Client();await Login(admin,factory.Credentials[RoleCodes.Admin]);await Login(customer,factory.Credentials[RoleCodes.Customer]);await Login(provider,factory.Credentials[RoleCodes.Provider]);
        var services=await admin.GetFromJsonAsync<List<InteriorServiceResponse>>("/api/v1/admin/interior/eligible-services");Assert.Contains(services!,x=>x.Id==factory.Catalog.ServiceId);
        var response=await admin.PostAsJsonAsync("/api/v1/admin/interior/projects",new{serviceRequestId=request,idempotencyKey=$"project-{Guid.NewGuid():N}"});Assert.Equal(HttpStatusCode.OK,response.StatusCode);var project=(await response.Content.ReadFromJsonAsync<InteriorProjectDetail>())!;Assert.Equal("CONSULTATION",project.StatusCode);Assert.Equal("POLICY_PENDING",project.FeeAssessmentStatusCode);
        Assert.Equal(HttpStatusCode.Forbidden,(await customer.GetAsync("/api/v1/admin/interior/projects")).StatusCode);Assert.Equal(HttpStatusCode.Forbidden,(await provider.GetAsync("/api/v1/admin/interior/projects")).StatusCode);
    }

    [Fact]
    public async Task ConfirmedSiteVisitProvider_AloneReceivesCustomerPrivateInformation_AndCompletionStoresMeasurements()
    {
        var flow=await CreateProject();using var admin=flow.Admin;using var provider=Client();using var other=Client();await Login(provider,factory.Credentials[RoleCodes.Provider]);await Login(other,factory.AreaMismatchProviderCredential);var providerId=await ProviderId(factory.Credentials[RoleCodes.Provider]);
        var add=await admin.PostAsJsonAsync($"/api/v1/admin/interior/projects/{flow.Project.Id}/site-visits",new{providerId,scheduledStartAt=DateTime.UtcNow.AddDays(2),scheduledEndAt=DateTime.UtcNow.AddDays(2).AddHours(2),accessConditionText="방문 전 고객에게 연락해 주세요.",idempotencyKey=$"visit-{Guid.NewGuid():N}"});Assert.Equal(HttpStatusCode.OK,add.StatusCode);var visit=(await add.Content.ReadFromJsonAsync<InteriorSiteVisitResponse>())!;
        Assert.Equal(HttpStatusCode.NotFound,(await provider.GetAsync($"/api/v1/interior/site-visits/{visit.Id}")).StatusCode);
        Assert.Equal(HttpStatusCode.OK,(await admin.PostAsJsonAsync($"/api/v1/admin/interior/projects/{flow.Project.Id}/site-visits/{visit.Id}/confirmation",new{idempotencyKey=$"confirm-{Guid.NewGuid():N}",rowVersion=(string?)null})).StatusCode);
        var privateView=await provider.GetFromJsonAsync<ProviderSiteVisitPrivateResponse>($"/api/v1/interior/site-visits/{visit.Id}");Assert.Equal("010-2468-1357",privateView!.CustomerPhone);Assert.Equal("101동 1203호",privateView.DetailAddress);Assert.Equal(HttpStatusCode.NotFound,(await other.GetAsync($"/api/v1/interior/site-visits/{visit.Id}")).StatusCode);
        var complete=await admin.PostAsJsonAsync($"/api/v1/admin/interior/projects/{flow.Project.Id}/site-visits/{visit.Id}/completion",new{measurementSummary="거실과 주방 실측 완료",constraint="엘리베이터 사용시간 확인 필요",riskNote="없음",measurements=new[]{new{key="living_room_width",value=4.2m,text=(string?)null,unit="m",location="거실",note=(string?)null,additionalDataJson=(string?)null}},fileIds=Array.Empty<Guid>(),idempotencyKey=$"complete-{Guid.NewGuid():N}",rowVersion=(string?)null});Assert.Equal(HttpStatusCode.OK,complete.StatusCode);
        using var scope=factory.Services.CreateScope();var db=scope.ServiceProvider.GetRequiredService<SoodalLifeDbContext>();Assert.Single(await db.InteriorSiteVisitMeasurements.Where(x=>x.MeasurementKey=="living_room_width").ToListAsync());Assert.Empty(await db.FeeCharges.Where(x=>x.CreatedAt>=flow.StartedAt).ToListAsync());Assert.Empty(await db.WalletLedgerEntries.Where(x=>x.CreatedAt>=flow.StartedAt).ToListAsync());
    }

    [Fact]
    public async Task ContractStagesChangesCompletion_PreserveVersionsHistoryEventsAndTrust()
    {
        var flow=await CreateProject();using var admin=flow.Admin;using var customer=Client();using var provider=Client();await Login(customer,factory.Credentials[RoleCodes.Customer]);await Login(provider,factory.Credentials[RoleCodes.Provider]);var providerId=await ProviderId(factory.Credentials[RoleCodes.Provider]);var revision=await SeedQuote(flow.RequestId,providerId);
        using var beforeScope=factory.Services.CreateScope();var beforeDb=beforeScope.ServiceProvider.GetRequiredService<SoodalLifeDbContext>();var trustEvents=await beforeDb.TrustScoreEvents.CountAsync();var trustCurrent=await beforeDb.ProviderTrustScoreCurrent.Where(x=>x.ProviderProfileId==beforeDb.ProviderProfiles.Single(p=>p.PublicId==providerId).Id).Select(x=>(decimal?)x.Score).SingleOrDefaultAsync();
        var selectionDetail=await customer.GetFromJsonAsync<CustomerInteriorProjectDetail>($"/api/v1/customers/me/interior/projects/{flow.Project.Id}");Assert.Equal(HttpStatusCode.OK,(await customer.PostAsJsonAsync($"/api/v1/customers/me/interior/projects/{flow.Project.Id}/provider-selection",new{quoteRevisionId=revision,rowVersion=selectionDetail!.RowVersion,idempotencyKey=$"select-provider-{Guid.NewGuid():N}"})).StatusCode);var contractResponse=await admin.PostAsJsonAsync($"/api/v1/admin/interior/projects/{flow.Project.Id}/contracts",new{providerId,quoteRevisionId=revision,contractAmount=12000000m,currencyCode="KRW",scopeSnapshotJson="{\"scope\":\"주거공간 부분 리모델링\"}",scheduleSnapshotJson="{\"days\":30}",warrantySnapshotJson="{\"policyDays\":30,\"contractTerms\":\"계약서 참조\"}",plannedStartDate=DateOnly.FromDateTime(DateTime.Today.AddDays(7)),plannedCompletionDate=DateOnly.FromDateTime(DateTime.Today.AddDays(37)),paymentPlans=new[]{new{sequenceNo=1,name="계약 지급",amount=3000000m,dueDate=(DateOnly?)null,condition="양 당사자 계약 동의 후"}},idempotencyKey=$"contract-{Guid.NewGuid():N}"});Assert.Equal(HttpStatusCode.OK,contractResponse.StatusCode);var contract=(await contractResponse.Content.ReadFromJsonAsync<InteriorContractResponse>())!;
        Assert.Equal(HttpStatusCode.OK,(await customer.PostAsJsonAsync($"/api/v1/interior/contracts/{contract.Id}/agreement",new{idempotencyKey=$"customer-agree-{Guid.NewGuid():N}",rowVersion=(string?)null})).StatusCode);var agreed=await provider.PostAsJsonAsync($"/api/v1/interior/contracts/{contract.Id}/agreement",new{idempotencyKey=$"provider-agree-{Guid.NewGuid():N}",rowVersion=(string?)null});Assert.Equal("EFFECTIVE",(await agreed.Content.ReadFromJsonAsync<InteriorContractResponse>())!.StatusCode);
        var detail=await admin.GetFromJsonAsync<InteriorProjectDetail>($"/api/v1/admin/interior/projects/{flow.Project.Id}");var plan=Assert.Single(detail!.PaymentPlans);Assert.Equal(HttpStatusCode.OK,(await customer.PostAsJsonAsync($"/api/v1/interior/payment-plans/{plan.Id}/confirmations",new{confirmationTypeCode="CUSTOMER_REPORTED",amount=3000000m,confirmedAt=DateTime.UtcNow,evidenceFileId=(Guid?)null,note="공급자에게 직접 지급",idempotencyKey=$"payment-{Guid.NewGuid():N}"})).StatusCode);
        var stageResponse=await admin.PostAsJsonAsync($"/api/v1/admin/interior/projects/{flow.Project.Id}/stages",new{sequenceNo=1,name="철거 및 정리",plannedStartDate=DateOnly.FromDateTime(DateTime.Today.AddDays(7)),plannedEndDate=DateOnly.FromDateTime(DateTime.Today.AddDays(10)),idempotencyKey=$"stage-{Guid.NewGuid():N}"});var stage=(await stageResponse.Content.ReadFromJsonAsync<InteriorWorkStageResponse>())!;Assert.Equal(HttpStatusCode.OK,(await provider.PostAsJsonAsync($"/api/v1/interior/stages/{stage.Id}/updates",new{progressPercent=100,updateText="철거와 폐기물 정리를 완료했습니다.",issueText=(string?)null,fileIds=Array.Empty<Guid>(),idempotencyKey=$"update-{Guid.NewGuid():N}",rowVersion=(string?)null})).StatusCode);
        var changeResponse=await provider.PostAsJsonAsync($"/api/v1/interior/contracts/{contract.Id}/changes",new{changeTypeCode="ADDITIONAL_WORK",reason="고객 요청",scopeChange="주방 수납장 추가",amountDelta=500000m,scheduleImpactDays=2,idempotencyKey=$"change-{Guid.NewGuid():N}"});var change=(await changeResponse.Content.ReadFromJsonAsync<InteriorChangeResponse>())!;Assert.Equal(HttpStatusCode.OK,(await customer.PostAsJsonAsync($"/api/v1/interior/changes/{change.Id}/decision",new{approve=true,idempotencyKey=$"approve-{Guid.NewGuid():N}",rowVersion=(string?)null})).StatusCode);
        Assert.Equal(HttpStatusCode.OK,(await provider.PostAsJsonAsync($"/api/v1/interior/projects/{flow.Project.Id}/completion-report",new{completionSummary="계약 범위와 승인된 추가공사를 완료했습니다.",finalChecklistJson="{\"handover\":true}",idempotencyKey=$"provider-complete-{Guid.NewGuid():N}",rowVersion=(string?)null})).StatusCode);var inspectionResponse=await admin.PostAsJsonAsync($"/api/v1/admin/interior/stages/{stage.Id}/inspections",new{inspectionStatusCode="PASSED",checklistJson="{\"clean\":true}",resultText="최종 검사 통과",requestedCorrectionText=(string?)null,idempotencyKey=$"inspect-{Guid.NewGuid():N}"});Assert.Equal(HttpStatusCode.OK,inspectionResponse.StatusCode);var inspectionId=(await inspectionResponse.Content.ReadFromJsonAsync<Guid>());Assert.Equal(HttpStatusCode.OK,(await customer.PostAsJsonAsync($"/api/v1/customers/me/interior/projects/{flow.Project.Id}/inspections/{inspectionId}/acknowledgement",new{comment="검사 결과를 확인했습니다.",idempotencyKey=$"inspect-ack-{Guid.NewGuid():N}",rowVersion=(string?)null})).StatusCode);Assert.Equal(HttpStatusCode.OK,(await customer.PostAsJsonAsync($"/api/v1/customers/me/interior/projects/{flow.Project.Id}/completion-acknowledgement",new{comment="완료 상태를 확인했습니다.",idempotencyKey=$"completion-ack-{Guid.NewGuid():N}",rowVersion=(string?)null})).StatusCode);
        Assert.Equal(HttpStatusCode.OK,(await admin.PostAsJsonAsync($"/api/v1/admin/interior/projects/{flow.Project.Id}/completion",new{finalChecklistJson="{\"handover\":true}",completionSummary="계약 범위와 승인된 추가공사를 완료했습니다.",idempotencyKey=$"project-complete-{Guid.NewGuid():N}",rowVersion=(string?)null})).StatusCode);Assert.Equal(HttpStatusCode.NotFound,(await provider.GetAsync($"/api/v1/interior/providers/me/projects/{flow.Project.Id}")).StatusCode);
        using var scope=factory.Services.CreateScope();var db=scope.ServiceProvider.GetRequiredService<SoodalLifeDbContext>();var project=await db.InteriorProjects.SingleAsync(x=>x.PublicId==flow.Project.Id);var contractRow=await db.InteriorContracts.SingleAsync(x=>x.PublicId==contract.Id);var participant=await db.InteriorProjectParticipants.SingleAsync(x=>x.InteriorProjectId==project.Id&&x.ProviderProfileId==contractRow.ProviderProfileId&&x.RoleCode=="PRIMARY_CONTRACTOR");Assert.Equal("ENDED",participant.StatusCode);Assert.NotNull(participant.EffectiveTo);Assert.Equal(2,contractRow.ContractVersion);Assert.Equal(12500000m,contractRow.ContractAmount);Assert.Equal(2,await db.InteriorContractVersions.CountAsync(x=>x.InteriorContractId==contractRow.Id));Assert.Single(await db.ServiceHistoryEntries.Where(x=>x.InteriorProjectId==project.Id).ToListAsync());Assert.Equal(trustEvents,await db.TrustScoreEvents.CountAsync());Assert.Equal(trustCurrent,await db.ProviderTrustScoreCurrent.Where(x=>x.ProviderProfileId==contractRow.ProviderProfileId).Select(x=>(decimal?)x.Score).SingleOrDefaultAsync());Assert.Empty(await db.FeeCharges.Where(x=>x.CreatedAt>=flow.StartedAt).ToListAsync());
        var evt=await db.InteriorProjectEvents.FirstAsync(x=>x.InteriorProjectId==project.Id);evt.EventDataJson="수정 시도";await Assert.ThrowsAsync<InvalidOperationException>(()=>db.SaveChangesAsync());
    }

    [Fact]
    public async Task Admin_LinksExistingAfterServiceAndDisputeWithoutDuplicatingTheirWorkflows()
    {
        var flow=await CreateProject();using var admin=flow.Admin;var providerId=await ProviderId(factory.Credentials[RoleCodes.Provider]);Guid afterServiceId;Guid disputeId;
        using(var scope=factory.Services.CreateScope())
        {
            var db=scope.ServiceProvider.GetRequiredService<SoodalLifeDbContext>();var project=await db.InteriorProjects.SingleAsync(x=>x.PublicId==flow.Project.Id);var provider=await db.ProviderProfiles.SingleAsync(x=>x.PublicId==providerId);project.SelectedContractorProviderId=provider.Id;var customerUser=await db.CustomerProfiles.Where(x=>x.Id==project.CustomerProfileId).Select(x=>x.UserId).SingleAsync();var now=DateTime.UtcNow;
            var afterService=new AfterServiceCase{CustomerProfileId=project.CustomerProfileId,ProviderProfileId=provider.Id,StatusCode="RECEIVED",Subject="마감 하자 확인",Description="거실 벽면 마감 상태를 확인해 주세요.",ReceivedAt=now,IdempotencyKey=$"as-{Guid.NewGuid():N}",CreatedAt=now,UpdatedAt=now};
            var dispute=new DisputeCase{ApplicantUserId=customerUser,CounterpartyUserId=provider.UserId,StatusCode="OPEN",Subject="추가 공사 범위 확인",Description="계약 변경 범위에 대한 확인이 필요합니다.",ReceivedAt=now,CreatedAt=now,UpdatedAt=now};db.AfterServiceCases.Add(afterService);db.DisputeCases.Add(dispute);await db.SaveChangesAsync();afterServiceId=afterService.PublicId;disputeId=dispute.PublicId;
        }
        var defect=await admin.PostAsJsonAsync($"/api/v1/admin/interior/projects/{flow.Project.Id}/defects",new{afterServiceCaseId=afterServiceId,workStageId=(Guid?)null,contractVersion=(int?)null,location="거실 벽면",description="도장 마감 들뜸",idempotencyKey=$"defect-{Guid.NewGuid():N}"});Assert.Equal(HttpStatusCode.OK,defect.StatusCode);
        var disputeResponse=await admin.PostAsJsonAsync($"/api/v1/admin/interior/projects/{flow.Project.Id}/disputes",new{disputeCaseId=disputeId,contractChangeId=(Guid?)null,workStageId=(Guid?)null,idempotencyKey=$"dispute-{Guid.NewGuid():N}"});Assert.Equal(HttpStatusCode.OK,disputeResponse.StatusCode);
        using var verifyScope=factory.Services.CreateScope();var verify=verifyScope.ServiceProvider.GetRequiredService<SoodalLifeDbContext>();var linkedProject=await verify.InteriorProjects.SingleAsync(x=>x.PublicId==flow.Project.Id);Assert.Single(await verify.InteriorDefects.Where(x=>x.InteriorProjectId==linkedProject.Id&&x.AfterServiceCaseId==verify.AfterServiceCases.Single(a=>a.PublicId==afterServiceId).Id).ToListAsync());Assert.Equal(linkedProject.Id,(await verify.DisputeCases.SingleAsync(x=>x.PublicId==disputeId)).InteriorProjectId);
    }

    private async Task<Flow> CreateProject(){var request=await SeedRequest();var admin=Client();await Login(admin,factory.Credentials[RoleCodes.Admin]);var started=DateTime.UtcNow;var response=await admin.PostAsJsonAsync("/api/v1/admin/interior/projects",new{serviceRequestId=request,idempotencyKey=$"project-{Guid.NewGuid():N}"});Assert.Equal(HttpStatusCode.OK,response.StatusCode);return new(admin,(await response.Content.ReadFromJsonAsync<InteriorProjectDetail>())!,request,started);}
    private async Task<Guid> SeedRequest(){using var scope=factory.Services.CreateScope();var db=scope.ServiceProvider.GetRequiredService<SoodalLifeDbContext>();var service=await db.ServiceCategories.SingleAsync(x=>x.PublicId==factory.Catalog.ServiceId);service.ExternalCode="INT-TEST";var middle=await db.ServiceCategories.SingleAsync(x=>x.Id==service.ParentId);var major=await db.ServiceCategories.SingleAsync(x=>x.Id==middle.ParentId);major.Name="인테리어";var customer=await(from user in db.Users join c in db.CustomerProfiles on user.Id equals c.UserId where user.LoginId==factory.Credentials[RoleCodes.Customer].LoginId select new{user,c}).SingleAsync();customer.user.Phone="010-2468-1357";var policy=await db.CategoryPolicies.FirstAsync(x=>x.CategoryId==service.Id);var area=await db.AdministrativeAreas.SingleAsync(x=>x.PublicId==factory.Catalog.AreaId);var now=DateTime.UtcNow;var request=new ServiceRequest{CustomerProfileId=customer.c.Id,CategoryId=service.Id,CategoryPolicyId=policy.Id,AdministrativeAreaId=area.Id,DetailAddress="101동 1203호",Title="주거공간 부분 리모델링",Description="거실과 주방 공사를 요청합니다.",StatusCode="OPEN",PolicySnapshotJson="{}",OpenedAt=now,CreatedAt=now,CreatedByUserId=customer.user.Id,UpdatedAt=now,UpdatedByUserId=customer.user.Id};db.ServiceRequests.Add(request);await db.SaveChangesAsync();return request.PublicId;}
    private async Task<Guid> SeedQuote(Guid requestId,Guid providerId){using var scope=factory.Services.CreateScope();var db=scope.ServiceProvider.GetRequiredService<SoodalLifeDbContext>();var request=await db.ServiceRequests.SingleAsync(x=>x.PublicId==requestId);var project=await db.InteriorProjects.SingleAsync(x=>x.ServiceRequestId==request.Id);project.StatusCode="ESTIMATE_READY";var provider=await db.ProviderProfiles.SingleAsync(x=>x.PublicId==providerId);var now=DateTime.UtcNow;var quote=new Quote{ServiceRequestId=request.Id,ProviderProfileId=provider.Id,RequestDispatchId=0,StatusCode="SUBMITTED",SubmittedAt=now,ExpiresAt=now.AddDays(7),CreatedAt=now,UpdatedAt=now};db.Quotes.Add(quote);await db.SaveChangesAsync();var revision=new QuoteRevision{QuoteId=quote.Id,RevisionNo=1,RevisionPurposeCode="POST_SITE_VISIT",Summary="현장 실측 기반 상세견적",SubtotalAmount=10909091m,VatAmount=1090909m,TotalAmount=12000000m,CurrencyCode="KRW",ValidUntil=now.AddDays(7),SubmittedAt=now,SubmittedByUserId=provider.UserId,IdempotencyKey=$"quote-{Guid.NewGuid():N}"};db.QuoteRevisions.Add(revision);await db.SaveChangesAsync();return revision.PublicId;}
    private async Task<Guid> ProviderId(TestCredential credential){using var scope=factory.Services.CreateScope();var db=scope.ServiceProvider.GetRequiredService<SoodalLifeDbContext>();return await(from u in db.Users join p in db.ProviderProfiles on u.Id equals p.UserId where u.LoginId==credential.LoginId select p.PublicId).SingleAsync();}
    private HttpClient Client()=>factory.CreateClient(new WebApplicationFactoryClientOptions{AllowAutoRedirect=false,HandleCookies=true});private static async Task Login(HttpClient client,TestCredential credential)=>Assert.Equal(HttpStatusCode.OK,(await client.PostAsJsonAsync("/api/v1/auth/login",new{LoginOrEmail=credential.LoginId,credential.Password})).StatusCode);
    private sealed record Flow(HttpClient Admin,InteriorProjectDetail Project,Guid RequestId,DateTime StartedAt);
}
