[CmdletBinding(SupportsShouldProcess=$true,ConfirmImpact='High')]
param([switch]$ConfirmProductionDeployment,[string]$ServerInstance='localhost',[string]$DatabaseName='SOODAL_LIFE_DEV',[string]$AppsRoot='D:\SOODALLIFE\apps',[string]$BackupParent='D:\SOODALLIFE\releases',[string]$DatabaseBackupRoot='D:\SOODALLIFE\DB\Backup')
$ErrorActionPreference='Stop'
if(-not $ConfirmProductionDeployment){throw 'Safety stop: rerun with -ConfirmProductionDeployment after checking the ZIP hash, database and target paths.'}
if(-not $PSCmdlet.ShouldProcess("API, customer, partner and admin apps at $AppsRoot plus database $DatabaseName",'Deploy V173 request address, provider distance decision and hub performance')){return}
$identity=[Security.Principal.WindowsIdentity]::GetCurrent();$principal=[Security.Principal.WindowsPrincipal]::new($identity);if(-not $principal.IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)){throw 'Run PowerShell as Administrator and try again.'}
Import-Module WebAdministration
if(-not(Get-Command sqlcmd.exe -ErrorAction SilentlyContinue)){throw 'sqlcmd.exe is required.'}
$releaseRoot=$PSScriptRoot;$stamp=Get-Date -Format 'yyyyMMdd-HHmmss';$backupRoot=Join-Path $BackupParent "backup-before-request-address-provider-performance-v173-$stamp";$iisBackupName="Before_RequestAddressProviderPerformanceV173_$stamp";$databaseBackupPath=Join-Path $DatabaseBackupRoot "${DatabaseName}_PreRequestAddressProviderPerformanceV173_$stamp.bak"
$applySql=Join-Path $releaseRoot 'deployment\Apply-RequestAddressProviderPerformanceV173.sql';$verifySql=Join-Path $releaseRoot 'deployment\Verify-RequestAddressProviderPerformanceV173.sql'
$sources=[ordered]@{API=Join-Path $releaseRoot 'api';Customer=Join-Path $releaseRoot 'frontend\customer';Partner=Join-Path $releaseRoot 'frontend\partner';Admin=Join-Path $releaseRoot 'frontend\admin'};$targets=[ordered]@{API=Join-Path $AppsRoot 'api';Customer=Join-Path $AppsRoot 'customer';Partner=Join-Path $AppsRoot 'partner';Admin=Join-Path $AppsRoot 'admin'}
$required=@((Join-Path $sources.API 'SoodalLife.Api.dll'),(Join-Path $sources.API 'web.config'),(Join-Path $sources.Customer 'index.html'),(Join-Path $sources.Partner 'index.html'),(Join-Path $sources.Admin 'index.html'),$applySql,$verifySql,(Join-Path $releaseRoot 'RELEASE-MANIFEST.txt'));foreach($file in $required){if(-not(Test-Path -LiteralPath $file -PathType Leaf)){throw "Required V173 release file is missing: $file"}}
if(Test-Path -LiteralPath (Join-Path $sources.API 'appsettings.json')){throw 'V173 package unexpectedly contains appsettings.json.'}
$customerJs=Get-ChildItem -LiteralPath (Join-Path $sources.Customer 'assets') -Filter 'index-*.js' -File;if($customerJs.Count-ne 1){throw "Exactly one customer JavaScript bundle is required. Found: $($customerJs.Count)"};$customerText=[IO.File]::ReadAllText($customerJs[0].FullName,[Text.Encoding]::UTF8);foreach($marker in @('BEFORE_QUOTE','AFTER_SELECTION','detailAddressDisclosureCode')){if(-not$customerText.Contains($marker)){throw "V173 customer marker missing: $marker"}}
$partnerJs=Get-ChildItem -LiteralPath (Join-Path $sources.Partner 'assets') -Filter 'index-*.js' -File;if($partnerJs.Count-ne 1){throw "Exactly one partner JavaScript bundle is required. Found: $($partnerJs.Count)"};$partnerText=[IO.File]::ReadAllText($partnerJs[0].FullName,[Text.Encoding]::UTF8);foreach($marker in @('soodal-provider-operations-hub:v173','detailAddressDisclosureCode','/decline')){if(-not$partnerText.Contains($marker)){throw "V173 partner marker missing: $marker"}}
$partnerCss=Get-ChildItem -LiteralPath (Join-Path $sources.Partner 'assets') -Filter 'index-*.css' -File;if($partnerCss.Count-ne 1){throw "Exactly one partner CSS bundle is required. Found: $($partnerCss.Count)"};$cssText=[IO.File]::ReadAllText($partnerCss[0].FullName,[Text.Encoding]::UTF8);if(-not$cssText.Contains('font-weight:400!important')){throw 'V173 normal input font marker missing.'}
New-Item -ItemType Directory -Force -Path $backupRoot,$DatabaseBackupRoot|Out-Null
function Copy-Checked([string]$Source,[string]$Destination,[switch]$Mirror,[switch]$PreserveApiData){New-Item -ItemType Directory -Force -Path $Destination|Out-Null;$arguments=@($Source,$Destination,($(if($Mirror){'/MIR'}else{'/E'})),'/R:2','/W:2','/NFL','/NDL','/NJH','/NJS','/NP');if($PreserveApiData){$arguments+=@('/XD','App_Data','/XF','appsettings.json','appsettings.Production.json','appsettings.Development.json')};& robocopy.exe @arguments;if($LASTEXITCODE-gt 7){throw "Robocopy failed ($LASTEXITCODE): $Source -> $Destination"}}
function Get-PoolState([string]$Name){try{return(Get-WebAppPoolState -Name $Name -ErrorAction Stop).Value}catch{return $null}}
function Stop-Pool([string]$Name){if(-not(Test-Path "IIS:\AppPools\$Name")){return};if((Get-PoolState $Name)-ne 'Stopped'){Stop-WebAppPool -Name $Name};for($i=0;$i-lt 40;$i++){if((Get-PoolState $Name)-eq 'Stopped'){return};Start-Sleep -Milliseconds 500};throw "Application pool did not stop: $Name"}
function Start-Pool([string]$Name){if(-not(Test-Path "IIS:\AppPools\$Name")){return};for($i=0;$i-lt 40;$i++){if((Get-PoolState $Name)-eq 'Started'){return};try{Start-WebAppPool -Name $Name}catch{};Start-Sleep -Milliseconds 750};throw "Application pool did not start: $Name"}
& "$env:windir\System32\inetsrv\appcmd.exe" add backup $iisBackupName;if($LASTEXITCODE-ne 0){throw 'IIS configuration backup failed.'};foreach($name in $targets.Keys){if(Test-Path -LiteralPath $targets[$name]){Copy-Checked $targets[$name] (Join-Path $backupRoot $name)}}
$escaped=$databaseBackupPath.Replace("'","''");& sqlcmd.exe -S $ServerInstance -E -C -b -Q "BACKUP DATABASE [$DatabaseName] TO DISK=N'$escaped' WITH COPY_ONLY, CHECKSUM, COMPRESSION, INIT; RESTORE VERIFYONLY FROM DISK=N'$escaped' WITH CHECKSUM;";if($LASTEXITCODE-ne 0){throw 'Database backup verification failed.'}
$pools=@('SoodalLife.Api','soodallife.kr','SoodalLife.Static');$deploymentError=$null
try{foreach($pool in $pools){Stop-Pool $pool};& sqlcmd.exe -S $ServerInstance -E -C -I -b -f 65001 -d $DatabaseName -i $applySql;if($LASTEXITCODE-ne 0){throw 'V173 database apply failed.'};foreach($name in $targets.Keys){Copy-Checked $sources[$name] $targets[$name] -Mirror -PreserveApiData:($name-eq'API')};New-Item -ItemType Directory -Force -Path (Join-Path $targets.API 'App_Data')|Out-Null}catch{$deploymentError=$_;Write-Warning "V173 deployment stopped. Database backup: $databaseBackupPath";foreach($name in $targets.Keys){$backup=Join-Path $backupRoot $name;if(Test-Path $backup){Copy-Checked $backup $targets[$name] -Mirror -PreserveApiData:($name-eq'API')}}}finally{foreach($pool in $pools){try{Start-Pool $pool}catch{Write-Warning $_.Exception.Message}}};if($deploymentError){throw $deploymentError}
& sqlcmd.exe -S $ServerInstance -E -C -I -b -f 65001 -d $DatabaseName -i $verifySql;if($LASTEXITCODE-ne 0){throw 'V173 database verification failed.'}
$health=Invoke-RestMethod -Uri 'https://api.soodallife.kr/api/v1/system/health' -TimeoutSec 30;$ready=Invoke-RestMethod -Uri 'https://api.soodallife.kr/api/v1/system/ready' -TimeoutSec 30;$customer=Invoke-WebRequest -Uri 'https://soodallife.kr/customer/requests/new' -UseBasicParsing -TimeoutSec 30;$partner=Invoke-WebRequest -Uri 'https://partner.soodallife.kr/provider' -UseBasicParsing -TimeoutSec 30;$admin=Invoke-WebRequest -Uri 'https://admin.soodallife.kr' -UseBasicParsing -TimeoutSec 30
if($health.status-ne'ok'-or$ready.status-ne'ready'-or$customer.StatusCode-ne 200-or$partner.StatusCode-ne 200-or$admin.StatusCode-ne 200){throw 'Post-deployment verification failed.'}
[PSCustomObject]@{DeploymentSucceeded=$true;IisBackup=$iisBackupName;FileBackup=$backupRoot;DatabaseBackup=$databaseBackupPath;AppDataPreserved=$true;AppSettingsPreserved=$true;DatabaseChanged=$true;ApiChanged=$true;Health=$health.status;Readiness=$ready.status;CustomerAddressDisclosure='customer-choice';ProviderDistanceDecision='confirm-or-decline';ProviderHub='cache-first-provider-scoped';InputTypography='normal';CustomerApp='ok';PartnerApp='ok';AdminApp='ok'}|Format-List
Write-Host 'V173 request address, provider distance decision and hub performance deployment completed.' -ForegroundColor Green
Write-Host 'Existing requests remain privacy-first. Provider hub cache and normal input typography are enabled.' -ForegroundColor Yellow
