using System.Text.Json;
using Microsoft.EntityFrameworkCore;
using SoodalLife.Api.Domain.Entities;
using SoodalLife.Api.Features.Reviews;
using SoodalLife.Api.Infrastructure.Persistence;

namespace SoodalLife.Api.Features.Admin;

public sealed class AdminReviewService(SoodalLifeDbContext db)
{
    public async Task<AdminReviewListResponse> Search(string? search,string? verificationStatus,string? visibilityStatus,DateOnly? submittedFrom,DateOnly? submittedTo,Guid? providerId,Guid? serviceId,int page,int pageSize,CancellationToken token)
    {
        if(page<1||pageSize is <1 or >100)throw new ReviewBusinessException(400,"ADMIN_REVIEW_PAGE_INVALID","페이지 정보를 확인해 주세요.");
        var query=from review in db.Reviews.AsNoTracking() join transaction in db.Transactions.AsNoTracking() on review.TransactionId equals transaction.Id join request in db.ServiceRequests.AsNoTracking() on transaction.ServiceRequestId equals request.Id join category in db.ServiceCategories.AsNoTracking() on transaction.CategoryId equals category.Id join customer in db.CustomerProfiles.AsNoTracking() on review.CustomerProfileId equals customer.Id join provider in db.ProviderProfiles.AsNoTracking() on review.ProviderProfileId equals provider.Id select new{review,transaction,request,category,customer,provider};
        var term=search?.Trim();if(!string.IsNullOrWhiteSpace(term)){if(TryNumber(term,"RV-",out var reviewNumber))query=query.Where(x=>x.review.Id==reviewNumber);else if(TryNumber(term,"TR-",out var transactionNumber))query=query.Where(x=>x.transaction.Id==transactionNumber);else if(Guid.TryParse(term,out var id))query=query.Where(x=>x.review.PublicId==id||x.transaction.PublicId==id||x.provider.PublicId==id||x.customer.PublicId==id||x.category.PublicId==id);else query=query.Where(x=>x.customer.DisplayName.Contains(term)||x.provider.BusinessName.Contains(term)||x.category.Name.Contains(term)||x.request.Title.Contains(term));}
        if(!string.IsNullOrWhiteSpace(verificationStatus))query=query.Where(x=>x.review.VerificationStatusCode==verificationStatus.ToUpperInvariant());if(!string.IsNullOrWhiteSpace(visibilityStatus))query=query.Where(x=>x.review.VisibilityStatusCode==visibilityStatus.ToUpperInvariant());
        if(submittedFrom.HasValue)query=query.Where(x=>x.review.SubmittedAt>=submittedFrom.Value.ToDateTime(TimeOnly.MinValue));if(submittedTo.HasValue)query=query.Where(x=>x.review.SubmittedAt<submittedTo.Value.AddDays(1).ToDateTime(TimeOnly.MinValue));if(providerId.HasValue)query=query.Where(x=>x.provider.PublicId==providerId);if(serviceId.HasValue)query=query.Where(x=>x.category.PublicId==serviceId);
        var total=await query.CountAsync(token);var rows=await query.OrderByDescending(x=>x.review.SubmittedAt).Skip((page-1)*pageSize).Take(pageSize).ToListAsync(token);var result=new List<AdminReviewListItemResponse>();foreach(var x in rows){var ratings=await Ratings(x.review.Id,token);result.Add(new(x.review.PublicId,$"RV-{x.review.Id:D8}",x.transaction.PublicId,$"TR-{x.transaction.Id:D8}",x.category.Name,x.customer.DisplayName,x.provider.BusinessName,x.review.SubmittedAt,x.review.VerificationStatusCode,x.review.VisibilityStatusCode,ratings));}return new(total,page,pageSize,result);
    }

    public async Task<AdminReviewDetailResponse?> Get(Guid id,CancellationToken token)
    {
        var x=await(from review in db.Reviews.AsNoTracking() join transaction in db.Transactions.AsNoTracking() on review.TransactionId equals transaction.Id join request in db.ServiceRequests.AsNoTracking() on transaction.ServiceRequestId equals request.Id join category in db.ServiceCategories.AsNoTracking() on transaction.CategoryId equals category.Id join customer in db.CustomerProfiles.AsNoTracking() on review.CustomerProfileId equals customer.Id join customerUser in db.Users.AsNoTracking() on customer.UserId equals customerUser.Id join provider in db.ProviderProfiles.AsNoTracking() on review.ProviderProfileId equals provider.Id join providerUser in db.Users.AsNoTracking() on provider.UserId equals providerUser.Id where review.PublicId==id select new{review,transaction,request,category,customer,customerUser,provider,providerUser}).SingleOrDefaultAsync(token);if(x is null)return null;
        var files=await(from link in db.ReviewFiles.AsNoTracking() join file in db.Files.AsNoTracking() on link.FileId equals file.Id where link.ReviewId==x.review.Id orderby link.DisplayOrder select new ReviewFileResponse(file.PublicId,file.OriginalFileName,file.ContentType,link.DisplayOrder)).ToListAsync(token);
        var reply=await(from value in db.ReviewProviderReplies.AsNoTracking() join provider in db.ProviderProfiles.AsNoTracking() on value.ProviderProfileId equals provider.Id where value.ReviewId==x.review.Id select new ReviewReplyResponse(value.PublicId,provider.BusinessName,value.BodyText,value.SubmittedAt)).SingleOrDefaultAsync(token);
        var audit=await db.AuditLogs.AsNoTracking().Where(a=>a.EntityType=="REVIEW"&&a.EntityPublicId==x.review.PublicId).OrderByDescending(a=>a.OccurredAt).Select(a=>new AdminReviewAuditResponse(a.OccurredAt,a.ActionCode,a.Reason,a.BeforeJson,a.AfterJson)).ToListAsync(token);
        return new(x.review.PublicId,$"RV-{x.review.Id:D8}",x.review.BodyText,x.review.OverallRating,x.review.VerificationStatusCode,x.review.VisibilityStatusCode,x.review.SubmittedAt,x.review.PublishedAt,x.review.HiddenAt,Convert.ToBase64String(x.review.RowVersion),new(x.transaction.PublicId,$"TR-{x.transaction.Id:D8}",x.transaction.StatusCode,x.category.Name,x.request.Title,x.transaction.AgreedAmount,x.transaction.CurrencyCode,x.transaction.CompletedAt),new(x.customer.PublicId,x.customer.DisplayName,AdminPrivacy.Phone(x.customerUser.Phone),AdminPrivacy.Email(x.customerUser.Email)),new(x.provider.PublicId,x.provider.BusinessName,AdminPrivacy.Phone(x.providerUser.Phone),AdminPrivacy.Email(x.providerUser.Email)),await Ratings(x.review.Id,token),files,reply,audit);
    }

    public async Task<AdminReviewDetailResponse> ChangeVisibility(Guid id,ChangeReviewVisibilityRequest input,Guid actorPublicId,CancellationToken token)
    {
        var target=input.TargetStatusCode.Trim().ToUpperInvariant();if(target is not("PUBLIC" or "HIDDEN"))throw new ReviewBusinessException(400,"REVIEW_VISIBILITY_INVALID","공개 또는 숨김 상태만 선택할 수 있습니다.");var reason=input.Reason?.Trim();if(string.IsNullOrWhiteSpace(reason)||reason.Length>1000)throw new ReviewBusinessException(400,"REVIEW_VISIBILITY_REASON_REQUIRED","운영조치 사유를 입력해 주세요.");
        var review=await db.Reviews.SingleOrDefaultAsync(x=>x.PublicId==id,token)??throw new ReviewBusinessException(404,"REVIEW_NOT_FOUND","리뷰를 찾을 수 없습니다.");byte[] version;try{version=Convert.FromBase64String(input.RowVersion);}catch{throw new ReviewBusinessException(400,"REVIEW_ROW_VERSION_INVALID","리뷰 버전정보를 확인해 주세요.");}db.Entry(review).Property(x=>x.RowVersion).OriginalValue=version;
        var actor=await db.Users.Where(x=>x.PublicId==actorPublicId).Select(x=>(long?)x.Id).SingleOrDefaultAsync(token)??throw new ReviewBusinessException(403,"ADMIN_USER_NOT_FOUND","관리자 계정을 확인할 수 없습니다.");var before=review.VisibilityStatusCode;if(before!=target){review.VisibilityStatusCode=target;review.UpdatedAt=DateTime.UtcNow;if(target=="PUBLIC"){review.PublishedAt=DateTime.UtcNow;review.HiddenAt=null;}else review.HiddenAt=DateTime.UtcNow;db.AuditLogs.Add(new AuditLog{OccurredAt=DateTime.UtcNow,ActorUserId=actor,ActorRoleCode="ADMIN",ActionCode=target=="PUBLIC"?"REVIEW_RESTORE":"REVIEW_HIDE",EntityType="REVIEW",EntityPublicId=review.PublicId,ResultCode="SUCCESS",Reason=reason,BeforeJson=JsonSerializer.Serialize(new{visibilityStatusCode=before}),AfterJson=JsonSerializer.Serialize(new{visibilityStatusCode=target})});try{await db.SaveChangesAsync(token);}catch(DbUpdateConcurrencyException){throw new ReviewBusinessException(409,"REVIEW_CONCURRENCY_CONFLICT","다른 관리자가 리뷰 상태를 변경했습니다. 새로고침 후 다시 시도해 주세요.");}}
        return (await Get(id,token))!;
    }
    private Task<List<ReviewRatingResponse>> Ratings(long reviewId,CancellationToken token)=>(from rating in db.ReviewRatings.AsNoTracking() join item in db.ReviewRatingItems.AsNoTracking() on rating.RatingItemId equals item.Id where rating.ReviewId==reviewId orderby rating.DisplayOrder select new ReviewRatingResponse(item.PublicId,item.Code,item.Name,rating.RatingValue,item.MinValue,item.MaxValue,rating.DisplayOrder)).ToListAsync(token);
    private static bool TryNumber(string value,string prefix,out long number)=>long.TryParse(value.StartsWith(prefix,StringComparison.OrdinalIgnoreCase)?value[prefix.Length..]:string.Empty,out number);
}
