using System.Text.Json;
using System.Security.Cryptography;
using System.Text;
using Microsoft.EntityFrameworkCore;
using SoodalLife.Api.Domain.Entities;
using SoodalLife.Api.Features.Authentication;
using SoodalLife.Api.Features.Work;
using SoodalLife.Api.Infrastructure.Persistence;

namespace SoodalLife.Api.Features.Admin;

public sealed class AdminCaseManagementService(SoodalLifeDbContext db,IPrivateFileStorage storage)
{
    private static readonly string[] ReportStates=["RECEIVED","UNDER_REVIEW","EVIDENCE_REQUESTED","RESOLVED","CANCELLED"];
    private static readonly string[] SanctionStates=["DECIDED","ACTIVE","RELEASED","EXPIRED","CANCELLED"];

    public Task<IReadOnlyList<CaseMasterResponse>> GetReportTypesAsync(CancellationToken token)=>GetMastersAsync(db.ReportTypes,"REPORT_TYPE",token);
    public Task<IReadOnlyList<CaseMasterResponse>> GetSanctionTypesAsync(CancellationToken token)=>GetMastersAsync(db.SanctionTypes,"SANCTION_TYPE",token);
    public Task<IReadOnlyList<CaseMasterResponse>> GetLiabilityTypesAsync(CancellationToken token)=>GetMastersAsync(db.DisputeLiabilityTypes,"LIABILITY_TYPE",token);
    public Task<CaseMasterResponse> SaveReportTypeAsync(Guid? id,CaseMasterRequest request,Guid actorId,CancellationToken token)=>SaveMasterAsync(db.ReportTypes,id,request,"REPORT_TYPE",actorId,token);
    public Task<CaseMasterResponse> SaveSanctionTypeAsync(Guid? id,CaseMasterRequest request,Guid actorId,CancellationToken token)=>SaveMasterAsync(db.SanctionTypes,id,request,"SANCTION_TYPE",actorId,token);
    public Task<CaseMasterResponse> SaveLiabilityTypeAsync(Guid? id,CaseMasterRequest request,Guid actorId,CancellationToken token)=>SaveMasterAsync(db.DisputeLiabilityTypes,id,request,"LIABILITY_TYPE",actorId,token);
    public async Task<IReadOnlyList<CaseAssigneeResponse>> GetAdminAssigneesAsync(CancellationToken token)=>await(from user in db.Users.AsNoTracking()join link in db.UserRoles.AsNoTracking()on user.Id equals link.UserId join role in db.Roles.AsNoTracking()on link.RoleId equals role.Id where user.StatusCode=="ACTIVE"&&link.RevokedAt==null&&role.Code==RoleCodes.Admin orderby user.LoginId select new CaseAssigneeResponse(user.PublicId,user.LoginId)).ToListAsync(token);

    public async Task<AdminReportListResponse> SearchReportsAsync(string? search,string? status,Guid? reportTypeId,Guid? assignedAdminId,DateOnly? receivedFrom,DateOnly? receivedTo,int page,int pageSize,CancellationToken token)
    {
        Page(page,pageSize);var query=db.Reports.AsNoTracking();var term=Clean(search);if(term is not null)query=query.Where(x=>x.Description.Contains(term)||db.Users.Any(u=>(u.Id==x.ReporterUserId||u.Id==x.ReportedUserId)&&(u.LoginId.Contains(term)||(u.Phone??"").Contains(term)||(u.Email??"").Contains(term))));if(Clean(status) is { } state)query=query.Where(x=>x.StatusCode==state.ToUpperInvariant());var total=await query.CountAsync(token);var rows=await query.OrderByDescending(x=>x.ReceivedAt).Skip((page-1)*pageSize).Take(pageSize).ToListAsync(token);var items=new List<AdminReportListItem>();foreach(var x in rows){var type=await db.ReportTypes.AsNoTracking().SingleAsync(t=>t.Id==x.ReportTypeId,token);var reporter=await NameAsync(x.ReporterUserId,token);var reported=x.ReportedUserId.HasValue?await NameAsync(x.ReportedUserId.Value,token):null;var service=await ServiceNameAsync(x.ServiceRequestId,x.TransactionId,token);var txNo=x.TransactionId.HasValue?await db.Transactions.AsNoTracking().Where(t=>t.Id==x.TransactionId).Select(t=>t.PublicId).Select(t=>"거래-"+t.ToString().Substring(0,8).ToUpper()).SingleAsync(token):null;var admin=x.AssignedAdminUserId.HasValue?await db.Users.AsNoTracking().Where(u=>u.Id==x.AssignedAdminUserId).Select(u=>u.LoginId).SingleOrDefaultAsync(token):null;items.Add(new(x.PublicId,Number("신고",x.PublicId),type.Name,reporter,reported,service,txNo,x.StatusCode,admin,x.ReceivedAt,x.ResolvedAt));}return new(total,page,pageSize,items);
    }

    public async Task<AdminReportDetail?> GetReportAsync(Guid id,CancellationToken token){var row=await db.Reports.AsNoTracking().SingleOrDefaultAsync(x=>x.PublicId==id,token);return row is null?null:await BuildReportAsync(row,token);}

    public async Task<AdminReportDetail> CreateReportAsync(CreateAdminReportRequest request,Guid actorId,CancellationToken token)
    {
        var actor=await ActorAsync(actorId,token);var prior=await db.Reports.AsNoTracking().SingleOrDefaultAsync(x=>x.IdempotencyKey==request.IdempotencyKey,token);if(prior is not null)return await BuildReportAsync(prior,token);var type=await ActiveMasterAsync(db.ReportTypes,request.ReportTypeId,token);var reporter=await UserAsync(request.ReporterUserId,token);var reported=request.ReportedUserId.HasValue?await UserAsync(request.ReportedUserId.Value,token):null;if(reported?.Id==reporter.Id)throw Error("REPORT_PARTY_INVALID","신고자와 신고대상자는 같을 수 없습니다.");var links=await ResolveLinksAsync(request.ServiceRequestId,request.TransactionId,request.ReviewId,request.AfterServiceCaseId,request.DisputeCaseId,token);if(reported is null&&links.AllNull)throw Error("REPORT_TARGET_REQUIRED","신고 대상 또는 관련 업무를 선택해 주세요.");var now=DateTime.UtcNow;var item=new Report{ReporterUserId=reporter.Id,ReportedUserId=reported?.Id,ReportTypeId=type.Id,ServiceRequestId=links.Request,TransactionId=links.Transaction,ReviewId=links.Review,AfterServiceCaseId=links.AfterService,DisputeCaseId=links.Dispute,Description=request.Description.Trim(),StatusCode="RECEIVED",ReceivedAt=now,IdempotencyKey=request.IdempotencyKey.Trim(),CreatedAt=now,CreatedByUserId=actor,UpdatedAt=now,UpdatedByUserId=actor};db.Reports.Add(item);await db.SaveChangesAsync(token);db.ReportActions.Add(new(){ReportId=item.Id,ActionTypeCode="CREATED",ToStatusCode="RECEIVED",ActorUserId=actor,Reason=item.Description,OccurredAt=now,IdempotencyKey=request.IdempotencyKey.Trim()});Audit(actor,"REPORT_CREATED","REPORT",item.PublicId,null,item,"신고 접수",now);await db.SaveChangesAsync(token);return await BuildReportAsync(item,token);
    }

    public async Task<AdminReportDetail> AssignReportAsync(Guid id,AssignReportRequest request,Guid actorId,CancellationToken token)
    {var actor=await ActorAsync(actorId,token);var item=await ReportAsync(id,token);if(await db.ReportActions.AnyAsync(x=>x.IdempotencyKey==request.IdempotencyKey,token))return await BuildReportAsync(item,token);SetVersion(item,request.RowVersion);long? assignee=request.AdminUserId.HasValue?await ActorAsync(request.AdminUserId.Value,token):null;var before=item.AssignedAdminUserId;item.AssignedAdminUserId=assignee;Touch(item,actor);AddReportAction(item,"ASSIGNED",item.StatusCode,item.StatusCode,request.Reason,actor,request.IdempotencyKey);Audit(actor,"REPORT_ASSIGNED","REPORT",item.PublicId,new{assigned=before},new{assigned=assignee},request.Reason,DateTime.UtcNow);await SaveConcurrencyAsync(token);return await BuildReportAsync(item,token);}

    public async Task<AdminReportDetail> ChangeReportStatusAsync(Guid id,ChangeReportStatusRequest request,Guid actorId,CancellationToken token)
    {var actor=await ActorAsync(actorId,token);var item=await ReportAsync(id,token);if(await db.ReportActions.AnyAsync(x=>x.IdempotencyKey==request.IdempotencyKey,token))return await BuildReportAsync(item,token);var target=request.TargetStatusCode.Trim().ToUpperInvariant();if(!ReportStates.Contains(target))throw Error("REPORT_STATUS_INVALID","신고 상태를 확인해 주세요.");if(item.StatusCode=="CANCELLED"||item.StatusCode=="RESOLVED")throw Error("REPORT_ALREADY_CLOSED","종료된 신고는 변경할 수 없습니다.",409);if(target=="CANCELLED"&&item.StatusCode!="RECEIVED")throw Error("REPORT_CANCEL_NOT_ALLOWED","검토 시작 전 신고만 취소할 수 있습니다.",409);SetVersion(item,request.RowVersion);var now=DateTime.UtcNow;var from=item.StatusCode;item.StatusCode=target;item.ResultSummary=Clean(request.ResultSummary);if(target=="RESOLVED")item.ResolvedAt=now;if(target=="CANCELLED")item.CancelledAt=now;Touch(item,actor,now);AddReportAction(item,target,from,target,request.Reason,actor,request.IdempotencyKey,now);Audit(actor,"REPORT_STATUS_CHANGED","REPORT",item.PublicId,new{status=from},new{status=target,item.ResultSummary},request.Reason,now);await SaveConcurrencyAsync(token);return await BuildReportAsync(item,token);}

    public async Task<AdminReportDetail> AddReportEvidenceAsync(Guid id,AddReportEvidenceRequest request,Guid actorId,CancellationToken token)
    {var actor=await ActorAsync(actorId,token);var item=await ReportAsync(id,token);if(await db.ReportActions.AnyAsync(x=>x.IdempotencyKey==request.IdempotencyKey,token))return await BuildReportAsync(item,token);var file=await db.Files.SingleOrDefaultAsync(x=>x.PublicId==request.FileId&&x.StatusCode=="ACTIVE"&&x.PurposeCode=="REPORT_EVIDENCE",token)??throw Error("REPORT_EVIDENCE_FILE_INVALID","활성 신고 증빙파일을 찾을 수 없습니다.",404);if(await db.ReportEvidence.AnyAsync(x=>x.ReportId==item.Id&&x.FileId==file.Id&&x.StatusCode=="ACTIVE",token))throw Error("REPORT_EVIDENCE_DUPLICATE","이미 연결된 증빙파일입니다.",409);var now=DateTime.UtcNow;db.ReportEvidence.Add(new(){ReportId=item.Id,FileId=file.Id,SubmittedByUserId=actor,Description=Clean(request.Description),SubmittedAt=now,CreatedAt=now,CreatedByUserId=actor});AddReportAction(item,"EVIDENCE_ADDED",item.StatusCode,item.StatusCode,request.Description,actor,request.IdempotencyKey,now);Audit(actor,"REPORT_EVIDENCE_ADDED","REPORT",item.PublicId,null,new{fileId=file.PublicId},request.Description,now);await db.SaveChangesAsync(token);return await BuildReportAsync(item,token);}

    public async Task<AdminSanctionListResponse> SearchSanctionsAsync(string? search,string? status,int page,int pageSize,CancellationToken token)
    {Page(page,pageSize);var query=db.Sanctions.AsNoTracking();var term=Clean(search);if(term is not null)query=query.Where(x=>x.Reason.Contains(term)||db.Users.Any(u=>u.Id==x.TargetUserId&&(u.LoginId.Contains(term)||(u.Phone??"").Contains(term)||(u.Email??"").Contains(term))));if(Clean(status)is{} state)query=query.Where(x=>x.StatusCode==state.ToUpperInvariant());var total=await query.CountAsync(token);var rows=await query.OrderByDescending(x=>x.DecidedAt).Skip((page-1)*pageSize).Take(pageSize).ToListAsync(token);var result=new List<AdminSanctionListItem>();foreach(var x in rows){var type=await db.SanctionTypes.AsNoTracking().SingleAsync(t=>t.Id==x.SanctionTypeId,token);result.Add(new(x.PublicId,Number("제재",x.PublicId),await NameAsync(x.TargetUserId,token),type.Name,await ScopeAsync(x,token),x.StatusCode,x.StartAt,x.EndAt,await db.SanctionSources.CountAsync(s=>s.SanctionId==x.Id,token),await NameAsync(x.DecidedByUserId,token)));}return new(total,page,pageSize,result);}

    public async Task<AdminSanctionDetail?> GetSanctionAsync(Guid id,CancellationToken token){var row=await db.Sanctions.AsNoTracking().SingleOrDefaultAsync(x=>x.PublicId==id,token);return row is null?null:await BuildSanctionAsync(row,token);}

    public async Task<AdminSanctionDetail> CreateSanctionAsync(CreateSanctionRequest request,Guid actorId,CancellationToken token)
    {var actor=await ActorAsync(actorId,token);var prior=await db.Sanctions.AsNoTracking().SingleOrDefaultAsync(x=>x.IdempotencyKey==request.IdempotencyKey,token);if(prior is not null)return await BuildSanctionAsync(prior,token);if(request.Sources.Count==0)throw Error("SANCTION_SOURCE_REQUIRED","제재 근거를 한 건 이상 선택해 주세요.");var target=await UserAsync(request.TargetUserId,token);var type=await ActiveMasterAsync(db.SanctionTypes,request.SanctionTypeId,token);if(request.EndAt.HasValue&&request.EndAt<=request.StartAt)throw Error("SANCTION_PERIOD_INVALID","종료일시는 시작일시보다 늦어야 합니다.");long? role=null,provider=null,service=null;if(Clean(request.TargetRoleCode)is{} roleCode)role=await(from userRole in db.UserRoles join value in db.Roles on userRole.RoleId equals value.Id where userRole.UserId==target.Id&&userRole.RevokedAt==null&&value.Code==roleCode.ToUpper() select(long?)value.Id).SingleOrDefaultAsync(token)??throw Error("ROLE_NOT_FOUND","역할을 찾을 수 없습니다.",404);if(request.ProviderId.HasValue){provider=await db.ProviderProfiles.Where(x=>x.PublicId==request.ProviderId&&x.UserId==target.Id).Select(x=>(long?)x.Id).SingleOrDefaultAsync(token)??throw Error("PROVIDER_SCOPE_INVALID","대상 사용자와 공급자 범위가 일치하지 않습니다.");}if(request.ProviderServiceId.HasValue){if(!provider.HasValue)throw Error("PROVIDER_SCOPE_REQUIRED","서비스 범위에는 공급자 범위가 필요합니다.");service=await(from link in db.ProviderServiceCategories join category in db.ServiceCategories on link.CategoryId equals category.Id where category.PublicId==request.ProviderServiceId&&link.ProviderProfileId==provider select(long?)link.Id).SingleOrDefaultAsync(token)??throw Error("PROVIDER_SERVICE_SCOPE_INVALID","공급자 서비스 범위를 찾을 수 없습니다.");}var sources=new List<SanctionSource>();foreach(var source in request.Sources){var resolved=await ResolveSourceAsync(source,token);sources.Add(new(){ReportId=resolved.Report,DisputeCaseId=resolved.Dispute,ReviewId=resolved.Review,AfterServiceCaseId=resolved.AfterService,CreatedAt=DateTime.UtcNow,CreatedByUserId=actor});}var now=DateTime.UtcNow;var item=new Sanction{TargetUserId=target.Id,TargetRoleId=role,ProviderProfileId=provider,ProviderServiceCategoryId=service,SanctionTypeId=type.Id,StatusCode=request.StartAt<=now?"ACTIVE":"DECIDED",Reason=request.Reason.Trim(),StartAt=request.StartAt.ToUniversalTime(),EndAt=request.EndAt?.ToUniversalTime(),DecidedAt=now,DecidedByUserId=actor,IdempotencyKey=request.IdempotencyKey.Trim(),CreatedAt=now,CreatedByUserId=actor,UpdatedAt=now,UpdatedByUserId=actor};db.Sanctions.Add(item);await db.SaveChangesAsync(token);foreach(var source in sources){source.SanctionId=item.Id;db.SanctionSources.Add(source);}AddSanctionEvent(item,"DECIDED",null,item.StatusCode,item.Reason,actor,request.IdempotencyKey,now);Audit(actor,"SANCTION_DECIDED","SANCTION",item.PublicId,null,item,item.Reason,now);await db.SaveChangesAsync(token);return await BuildSanctionAsync(item,token);}

    public async Task<AdminSanctionDetail> ChangeSanctionStatusAsync(Guid id,ChangeSanctionStatusRequest request,Guid actorId,CancellationToken token)
    {var actor=await ActorAsync(actorId,token);var item=await SanctionAsync(id,token);if(await db.SanctionEvents.AnyAsync(x=>x.IdempotencyKey==request.IdempotencyKey,token))return await BuildSanctionAsync(item,token);var action=request.ActionCode.Trim().ToUpperInvariant();var target=action switch{"ACTIVATE"=>"ACTIVE","RELEASE"=>"RELEASED","EXPIRE"=>"EXPIRED","CANCEL"=>"CANCELLED",_=>throw Error("SANCTION_ACTION_INVALID","제재 처리유형을 확인해 주세요.")};if(!SanctionStates.Contains(target))throw Error("SANCTION_STATUS_INVALID","제재 상태를 확인해 주세요.");SetVersion(item,request.RowVersion);var now=DateTime.UtcNow;var from=item.StatusCode;item.StatusCode=target;if(target is "RELEASED" or "CANCELLED"){item.ReleasedAt=now;item.ReleasedByUserId=actor;item.ReleaseReason=request.Reason.Trim();}Touch(item,actor,now);AddSanctionEvent(item,target=="ACTIVE"?"ACTIVATED":target,from,target,request.Reason,actor,request.IdempotencyKey,now);Audit(actor,"SANCTION_"+action,"SANCTION",item.PublicId,new{status=from},new{status=target},request.Reason,now);await SaveConcurrencyAsync(token);return await BuildSanctionAsync(item,token);}

    public async Task<AdminSanctionDetail> CreateAppealAsync(Guid sanctionId,CreateSanctionAppealRequest request,Guid actorId,CancellationToken token)
    {var actor=await ActorAsync(actorId,token);var sanction=await SanctionAsync(sanctionId,token);var prior=await db.SanctionAppeals.AsNoTracking().SingleOrDefaultAsync(x=>x.IdempotencyKey==request.IdempotencyKey,token);if(prior is not null)return await BuildSanctionAsync(sanction,token);var applicant=await UserAsync(request.ApplicantUserId,token);if(applicant.Id!=sanction.TargetUserId)throw Error("APPEAL_APPLICANT_INVALID","제재 대상자만 이의신청할 수 있습니다.",403);long? previous=null;if(request.PreviousAppealId.HasValue)previous=await db.SanctionAppeals.Where(x=>x.PublicId==request.PreviousAppealId&&x.SanctionId==sanction.Id).Select(x=>(long?)x.Id).SingleOrDefaultAsync(token)??throw Error("PREVIOUS_APPEAL_INVALID","같은 제재의 이전 이의신청을 찾을 수 없습니다.");var now=DateTime.UtcNow;var appeal=new SanctionAppeal{SanctionId=sanction.Id,ApplicantUserId=applicant.Id,PreviousAppealId=previous,Statement=request.Statement.Trim(),SubmittedAt=now,IdempotencyKey=request.IdempotencyKey.Trim(),CreatedAt=now,CreatedByUserId=actor,UpdatedAt=now,UpdatedByUserId=actor};db.SanctionAppeals.Add(appeal);await db.SaveChangesAsync(token);AddAppealAction(appeal,"RECEIVED",null,"RECEIVED","이의신청 접수",actor,request.IdempotencyKey,now);Audit(actor,"SANCTION_APPEAL_RECEIVED","SANCTION_APPEAL",appeal.PublicId,null,appeal,"이의신청 접수",now);await db.SaveChangesAsync(token);return await BuildSanctionAsync(sanction,token);}

    public async Task<AdminSanctionDetail> AssignAppealAsync(Guid sanctionId,Guid appealId,AssignSanctionAppealRequest request,Guid actorId,CancellationToken token)
    {var actor=await ActorAsync(actorId,token);var sanction=await SanctionAsync(sanctionId,token);var appeal=await AppealAsync(sanction.Id,appealId,token);if(await db.SanctionAppealActions.AnyAsync(x=>x.IdempotencyKey==request.IdempotencyKey,token))return await BuildSanctionAsync(sanction,token);SetVersion(appeal,request.RowVersion);appeal.AssignedAdminUserId=request.AdminUserId.HasValue?await ActorAsync(request.AdminUserId.Value,token):null;var from=appeal.StatusCode;appeal.StatusCode="UNDER_REVIEW";Touch(appeal,actor);AddAppealAction(appeal,"ASSIGNED",from,"UNDER_REVIEW",request.Reason,actor,request.IdempotencyKey);Audit(actor,"SANCTION_APPEAL_ASSIGNED","SANCTION_APPEAL",appeal.PublicId,new{status=from},new{status=appeal.StatusCode},request.Reason,DateTime.UtcNow);await SaveConcurrencyAsync(token);return await BuildSanctionAsync(sanction,token);}

    public async Task<AdminSanctionDetail> DecideAppealAsync(Guid sanctionId,Guid appealId,DecideSanctionAppealRequest request,Guid actorId,CancellationToken token)
    {var actor=await ActorAsync(actorId,token);var sanction=await SanctionAsync(sanctionId,token);var appeal=await AppealAsync(sanction.Id,appealId,token);if(await db.SanctionAppealActions.AnyAsync(x=>x.IdempotencyKey==request.IdempotencyKey,token))return await BuildSanctionAsync(sanction,token);if(appeal.StatusCode!="UNDER_REVIEW")throw Error("APPEAL_REVIEW_REQUIRED","담당자 지정 후 검토 중인 이의신청만 결정할 수 있습니다.",409);var decision=request.DecisionCode.Trim().ToUpperInvariant();if(decision is not("APPROVED" or "REJECTED"))throw Error("APPEAL_DECISION_INVALID","승인 또는 기각을 선택해 주세요.");SetVersion(appeal,request.RowVersion);var now=DateTime.UtcNow;var from=appeal.StatusCode;appeal.StatusCode=decision;appeal.DecisionCode=decision;appeal.DecisionReason=request.DecisionReason.Trim();appeal.DecidedAt=now;Touch(appeal,actor,now);AddAppealAction(appeal,"DECIDED",from,decision,request.DecisionReason,actor,request.IdempotencyKey,now);Audit(actor,"SANCTION_APPEAL_DECIDED","SANCTION_APPEAL",appeal.PublicId,new{status=from},new{status=decision},request.DecisionReason,now);await SaveConcurrencyAsync(token);return await BuildSanctionAsync(sanction,token);}

    public async Task<AdminSanctionDetail> AddAppealEvidenceAsync(Guid sanctionId,Guid appealId,AddSanctionAppealEvidenceRequest request,Guid actorId,CancellationToken token)
    {var actor=await ActorAsync(actorId,token);var sanction=await SanctionAsync(sanctionId,token);var appeal=await AppealAsync(sanction.Id,appealId,token);if(await db.SanctionAppealActions.AnyAsync(x=>x.IdempotencyKey==request.IdempotencyKey,token))return await BuildSanctionAsync(sanction,token);var file=await db.Files.SingleOrDefaultAsync(x=>x.PublicId==request.FileId&&x.StatusCode=="ACTIVE"&&x.PurposeCode=="SANCTION_APPEAL_EVIDENCE",token)??throw Error("APPEAL_EVIDENCE_FILE_INVALID","활성 이의신청 증빙파일을 찾을 수 없습니다.",404);if(await db.SanctionAppealEvidence.AnyAsync(x=>x.SanctionAppealId==appeal.Id&&x.FileId==file.Id,token))throw Error("APPEAL_EVIDENCE_DUPLICATE","이미 연결된 증빙파일입니다.",409);var now=DateTime.UtcNow;db.SanctionAppealEvidence.Add(new(){SanctionAppealId=appeal.Id,FileId=file.Id,SubmittedByUserId=actor,Description=Clean(request.Description),CreatedAt=now,CreatedByUserId=actor});AddAppealAction(appeal,"EVIDENCE_ADDED",appeal.StatusCode,appeal.StatusCode,request.Description??"증빙 추가",actor,request.IdempotencyKey,now);Audit(actor,"SANCTION_APPEAL_EVIDENCE_ADDED","SANCTION_APPEAL",appeal.PublicId,null,new{fileId=file.PublicId},request.Description,now);await db.SaveChangesAsync(token);return await BuildSanctionAsync(sanction,token);}

    public async Task<(Stream Stream,string ContentType,string FileName)> OpenEvidenceAsync(Guid fileId,Guid actorId,CancellationToken token)
    {var actor=await ActorAsync(actorId,token);var file=await db.Files.AsNoTracking().SingleOrDefaultAsync(x=>x.PublicId==fileId&&x.StatusCode=="ACTIVE",token)??throw Error("EVIDENCE_FILE_NOT_FOUND","증빙파일을 찾을 수 없습니다.",404);var report=await db.ReportEvidence.AsNoTracking().AnyAsync(x=>x.FileId==file.Id&&x.StatusCode=="ACTIVE",token);var appeal=await db.SanctionAppealEvidence.AsNoTracking().AnyAsync(x=>x.FileId==file.Id,token);if(!report&&!appeal)throw Error("EVIDENCE_FILE_RELATION_INVALID","사건과 연결된 증빙파일이 아닙니다.",404);if(report&&file.PurposeCode!="REPORT_EVIDENCE"||appeal&&file.PurposeCode!="SANCTION_APPEAL_EVIDENCE")throw Error("EVIDENCE_FILE_PURPOSE_INVALID","증빙파일 용도가 일치하지 않습니다.",409);Audit(actor,"CASE_EVIDENCE_DOWNLOADED","STORED_FILE",file.PublicId,null,new{file.PurposeCode},"관리자 증빙 열람",DateTime.UtcNow);await db.SaveChangesAsync(token);return(await storage.OpenReadAsync(file.StorageKey,token),file.ContentType,file.OriginalFileName);}

    public async Task<CaseFileUploadResponse> UploadEvidenceFileAsync(string purposeCode,IFormFile upload,Guid actorId,CancellationToken token)
    {var actor=await ActorAsync(actorId,token);var purpose=purposeCode.Trim().ToUpperInvariant();if(purpose is not("REPORT_EVIDENCE" or "SANCTION_APPEAL_EVIDENCE"))throw Error("EVIDENCE_PURPOSE_INVALID","신고 또는 이의신청 증빙 용도를 선택해 주세요.");if(upload.Length is<=0 or>10485760)throw Error("EVIDENCE_FILE_SIZE_INVALID","증빙파일은 10MB 이하만 등록할 수 있습니다.");var original=Path.GetFileName(upload.FileName);if(string.IsNullOrWhiteSpace(original)||original!=upload.FileName||original.Length>255)throw Error("EVIDENCE_FILE_NAME_INVALID","안전한 파일명을 사용해 주세요.");var extension=Path.GetExtension(original).ToLowerInvariant();var allowed=(upload.ContentType,extension) switch{("application/pdf",".pdf")=>true,("image/jpeg",".jpg" or ".jpeg")=>true,("image/png",".png")=>true,_=>false};if(!allowed)throw Error("EVIDENCE_FILE_TYPE_INVALID","PDF, JPG, PNG 파일만 등록할 수 있습니다.");await using var input=upload.OpenReadStream();using var memory=new MemoryStream();await input.CopyToAsync(memory,token);var bytes=memory.ToArray();if(!ValidSignature(upload.ContentType,bytes))throw Error("EVIDENCE_FILE_SIGNATURE_INVALID","파일 형식과 실제 내용이 일치하지 않습니다.");var now=DateTime.UtcNow;var storageKey=$"case-evidence/{purpose.ToLowerInvariant()}/{Guid.NewGuid():N}{extension}";var row=new StoredFile{PurposeCode=purpose,StorageContainer="development-private",StorageKey=storageKey,StorageKeyHash=SHA256.HashData(Encoding.UTF8.GetBytes(storageKey)),OriginalFileName=original,ContentType=upload.ContentType,SizeBytes=upload.Length,Sha256Hex=Convert.ToHexString(SHA256.HashData(bytes)).ToLowerInvariant(),StatusCode="PENDING",UploadedByUserId=actor,CreatedAt=now};db.Files.Add(row);await db.SaveChangesAsync(token);try{memory.Position=0;await storage.SaveAsync(storageKey,memory,token);row.StatusCode="ACTIVE";row.ActivatedAt=now;row.ScanResultText="Development-only signature validation; malware scanning is not configured.";Audit(actor,"CASE_EVIDENCE_UPLOADED","STORED_FILE",row.PublicId,null,new{row.PurposeCode,row.OriginalFileName,row.SizeBytes},"사건 증빙 업로드",now);await db.SaveChangesAsync(token);return new(row.PublicId,row.OriginalFileName,row.ContentType,row.SizeBytes);}catch{await storage.DeleteIfExistsAsync(storageKey,token);throw;}}

    private async Task<AdminReportDetail> BuildReportAsync(Report x,CancellationToken token)
    {var type=await db.ReportTypes.AsNoTracking().SingleAsync(t=>t.Id==x.ReportTypeId,token);var reporter=await PartyAsync(x.ReporterUserId,token);var reported=x.ReportedUserId.HasValue?await PartyAsync(x.ReportedUserId.Value,token):null;var admin=x.AssignedAdminUserId.HasValue?await NameAsync(x.AssignedAdminUserId.Value,token):null;var evidence=await(from e in db.ReportEvidence.AsNoTracking()join f in db.Files.AsNoTracking()on e.FileId equals f.Id where e.ReportId==x.Id orderby e.SubmittedAt descending select new AdminCaseEvidence(e.PublicId,f.PublicId,f.OriginalFileName,f.ContentType,e.Description,e.StatusCode,e.SubmittedAt,$"/api/v1/admin/case-files/{f.PublicId}")).ToListAsync(token);var actions=await db.ReportActions.AsNoTracking().Where(a=>a.ReportId==x.Id).OrderByDescending(a=>a.OccurredAt).Select(a=>new AdminCaseAction(a.PublicId,a.ActionTypeCode,a.FromStatusCode,a.ToStatusCode,a.Reason,a.Note,a.OccurredAt)).ToListAsync(token);return new(x.PublicId,Number("신고",x.PublicId),type.PublicId,type.Code,type.Name,x.StatusCode,x.Description,x.ResultSummary,reporter,reported,await RelationsAsync(x,token),admin,x.ReceivedAt,x.ResolvedAt,x.CancelledAt,evidence,actions,await AuditAsync("REPORT",x.PublicId,token),Convert.ToBase64String(x.RowVersion));}

    private async Task<AdminSanctionDetail> BuildSanctionAsync(Sanction x,CancellationToken token)
    {var type=await db.SanctionTypes.AsNoTracking().SingleAsync(t=>t.Id==x.SanctionTypeId,token);var sources=await SourceItemsAsync(x.Id,token);var events=await db.SanctionEvents.AsNoTracking().Where(e=>e.SanctionId==x.Id).OrderByDescending(e=>e.OccurredAt).Select(e=>new AdminSanctionEvent(e.PublicId,e.ActionTypeCode,e.FromStatusCode,e.ToStatusCode,e.Reason,e.OccurredAt)).ToListAsync(token);var appealRows=await db.SanctionAppeals.AsNoTracking().Where(a=>a.SanctionId==x.Id).OrderByDescending(a=>a.SubmittedAt).ToListAsync(token);var appeals=new List<AdminSanctionAppeal>();foreach(var a in appealRows){var evidence=await(from e in db.SanctionAppealEvidence.AsNoTracking()join f in db.Files.AsNoTracking()on e.FileId equals f.Id where e.SanctionAppealId==a.Id select new AdminCaseEvidence(Guid.Empty,f.PublicId,f.OriginalFileName,f.ContentType,e.Description,"ACTIVE",e.CreatedAt,$"/api/v1/admin/case-files/{f.PublicId}")).ToListAsync(token);var actions=await db.SanctionAppealActions.AsNoTracking().Where(v=>v.SanctionAppealId==a.Id).OrderByDescending(v=>v.OccurredAt).Select(v=>new AdminCaseAction(v.PublicId,v.ActionTypeCode,v.FromStatusCode,v.ToStatusCode,v.Reason,null,v.OccurredAt)).ToListAsync(token);appeals.Add(new(a.PublicId,Number("이의",a.PublicId),(await db.Users.AsNoTracking().SingleAsync(u=>u.Id==a.ApplicantUserId,token)).PublicId,await NameAsync(a.ApplicantUserId,token),a.PreviousAppealId.HasValue?await db.SanctionAppeals.Where(v=>v.Id==a.PreviousAppealId).Select(v=>(Guid?)v.PublicId).SingleAsync(token):null,a.Statement,a.StatusCode,a.AssignedAdminUserId.HasValue?await NameAsync(a.AssignedAdminUserId.Value,token):null,a.DecisionCode,a.DecisionReason,a.SubmittedAt,a.DecidedAt,evidence,actions,Convert.ToBase64String(a.RowVersion)));}return new(x.PublicId,Number("제재",x.PublicId),type.PublicId,type.Code,type.Name,x.StatusCode,x.Reason,await PartyAsync(x.TargetUserId,token),await ScopeAsync(x,token),x.StartAt,x.EndAt,x.DecidedAt,await NameAsync(x.DecidedByUserId,token),x.ReleasedAt,x.ReleasedByUserId.HasValue?await NameAsync(x.ReleasedByUserId.Value,token):null,x.ReleaseReason,sources,events,appeals,await AuditAsync("SANCTION",x.PublicId,token),Convert.ToBase64String(x.RowVersion));}

    private async Task<IReadOnlyList<CaseMasterResponse>> GetMastersAsync<TEntity>(DbSet<TEntity> set,string kind,CancellationToken token) where TEntity:class
    {var values=await set.AsNoTracking().OrderBy(x=>EF.Property<int>(x,"DisplayOrder")).ThenBy(x=>EF.Property<string>(x,"Name")).ToListAsync(token);var result=new List<CaseMasterResponse>();foreach(var x in values){var id=(long)Get(x,"Id")!;var used=kind switch{"REPORT_TYPE"=>await db.Reports.AnyAsync(v=>v.ReportTypeId==id,token),"SANCTION_TYPE"=>await db.Sanctions.AnyAsync(v=>v.SanctionTypeId==id,token),_=>await db.DisputeResolutions.AnyAsync(v=>v.LiabilityTypeId==id,token)};result.Add(new((Guid)Get(x,"PublicId")!,(string)Get(x,"Code")!,(string)Get(x,"Name")!,(string?)Get(x,"Description"),(bool)Get(x,"IsActive")!,(int)Get(x,"DisplayOrder")!,kind=="LIABILITY_TYPE"?null:(DateTime?)Get(x,"EffectiveFrom"),kind=="LIABILITY_TYPE"?null:(DateTime?)Get(x,"EffectiveTo"),Convert.ToBase64String((byte[])Get(x,"RowVersion")!),used));}return result;}

    private async Task<CaseMasterResponse> SaveMasterAsync<TEntity>(DbSet<TEntity> set,Guid? id,CaseMasterRequest request,string kind,Guid actorId,CancellationToken token) where TEntity:class,new()
    {var actor=await ActorAsync(actorId,token);var code=request.Code.Trim().ToUpperInvariant();if(await set.AnyAsync(x=>EF.Property<string>(x,"Code")==code&&(!id.HasValue||EF.Property<Guid>(x,"PublicId")!=id),token))throw Error("MASTER_CODE_DUPLICATE","이미 사용 중인 코드입니다.",409);var now=DateTime.UtcNow;TEntity row;if(id.HasValue){row=await set.SingleOrDefaultAsync(x=>EF.Property<Guid>(x,"PublicId")==id,token)??throw Error("MASTER_NOT_FOUND","기준정보를 찾을 수 없습니다.",404);SetVersion(row,request.RowVersion);if(!string.Equals((string)Get(row,"Code")!,code,StringComparison.OrdinalIgnoreCase)&&await MasterUsedAsync(kind,(long)Get(row,"Id")!,token))throw Error("MASTER_CODE_IN_USE","업무에서 사용 중인 코드는 변경할 수 없습니다.",409);}else{row=new();set.Add(row);typeof(TEntity).GetProperty("PublicId")!.SetValue(row,Guid.NewGuid());typeof(TEntity).GetProperty("CreatedAt")!.SetValue(row,now);typeof(TEntity).GetProperty("CreatedByUserId")!.SetValue(row,actor);}Set(row,"Code",code);Set(row,"Name",request.Name.Trim());Set(row,"Description",Clean(request.Description));Set(row,"IsActive",request.IsActive);Set(row,"DisplayOrder",request.DisplayOrder);if(kind!="LIABILITY_TYPE"){Set(row,"EffectiveFrom",request.EffectiveFrom?.ToUniversalTime());Set(row,"EffectiveTo",request.EffectiveTo?.ToUniversalTime());}Set(row,"UpdatedAt",now);Set(row,"UpdatedByUserId",actor);await SaveConcurrencyAsync(token);var publicId=(Guid)Get(row,"PublicId")!;Audit(actor,id.HasValue?kind+"_UPDATED":kind+"_CREATED",kind,publicId,null,row,"기준정보 관리",now);await db.SaveChangesAsync(token);return new(publicId,code,request.Name.Trim(),Clean(request.Description),request.IsActive,request.DisplayOrder,request.EffectiveFrom,request.EffectiveTo,Convert.ToBase64String((byte[])Get(row,"RowVersion")!),false);}

    private async Task<AdminCaseParty> PartyAsync(long id,CancellationToken token){var user=await db.Users.AsNoTracking().SingleAsync(x=>x.Id==id,token);var roles=await(from link in db.UserRoles.AsNoTracking()join role in db.Roles.AsNoTracking()on link.RoleId equals role.Id where link.UserId==id&&link.RevokedAt==null select role.Code).ToArrayAsync(token);return new(user.PublicId,await NameAsync(id,token),user.Phone,user.Email,roles);}
    private async Task<string> NameAsync(long id,CancellationToken token)=>await db.CustomerProfiles.AsNoTracking().Where(x=>x.UserId==id).Select(x=>x.DisplayName).FirstOrDefaultAsync(token)??await db.ProviderProfiles.AsNoTracking().Where(x=>x.UserId==id).Select(x=>x.BusinessName).FirstOrDefaultAsync(token)??await db.Users.AsNoTracking().Where(x=>x.Id==id).Select(x=>x.LoginId).SingleAsync(token);
    private async Task<User> UserAsync(Guid id,CancellationToken token)=>await db.Users.SingleOrDefaultAsync(x=>x.PublicId==id&&x.StatusCode=="ACTIVE",token)??throw Error("USER_NOT_FOUND","활성 사용자를 찾을 수 없습니다.",404);
    private async Task<long> ActorAsync(Guid id,CancellationToken token)=>await(from user in db.Users.AsNoTracking()join link in db.UserRoles.AsNoTracking()on user.Id equals link.UserId join role in db.Roles.AsNoTracking()on link.RoleId equals role.Id where user.PublicId==id&&user.StatusCode=="ACTIVE"&&link.RevokedAt==null&&role.Code==RoleCodes.Admin select(long?)user.Id).SingleOrDefaultAsync(token)??throw Error("ADMIN_REQUIRED","관리자 계정을 확인할 수 없습니다.",401);
    private async Task<TEntity> ActiveMasterAsync<TEntity>(DbSet<TEntity> set,Guid id,CancellationToken token) where TEntity:class=>await set.SingleOrDefaultAsync(x=>EF.Property<Guid>(x,"PublicId")==id&&EF.Property<bool>(x,"IsActive"),token)??throw Error("MASTER_NOT_FOUND","사용 가능한 기준정보를 찾을 수 없습니다.",404);
    private async Task<Report> ReportAsync(Guid id,CancellationToken token)=>await db.Reports.SingleOrDefaultAsync(x=>x.PublicId==id,token)??throw Error("REPORT_NOT_FOUND","신고를 찾을 수 없습니다.",404);
    private async Task<Sanction> SanctionAsync(Guid id,CancellationToken token)=>await db.Sanctions.SingleOrDefaultAsync(x=>x.PublicId==id,token)??throw Error("SANCTION_NOT_FOUND","제재를 찾을 수 없습니다.",404);
    private async Task<SanctionAppeal> AppealAsync(long sanctionId,Guid id,CancellationToken token)=>await db.SanctionAppeals.SingleOrDefaultAsync(x=>x.SanctionId==sanctionId&&x.PublicId==id,token)??throw Error("APPEAL_NOT_FOUND","이의신청을 찾을 수 없습니다.",404);
    private async Task<LinkIds> ResolveLinksAsync(Guid? request,Guid? tx,Guid? review,Guid? after,Guid? dispute,CancellationToken token){long? r=request.HasValue?await db.ServiceRequests.Where(x=>x.PublicId==request).Select(x=>(long?)x.Id).SingleOrDefaultAsync(token)??throw Error("REQUEST_NOT_FOUND","요청을 찾을 수 없습니다.",404):null;long? t=tx.HasValue?await db.Transactions.Where(x=>x.PublicId==tx).Select(x=>(long?)x.Id).SingleOrDefaultAsync(token)??throw Error("TRANSACTION_NOT_FOUND","거래를 찾을 수 없습니다.",404):null;long? rv=review.HasValue?await db.Reviews.Where(x=>x.PublicId==review).Select(x=>(long?)x.Id).SingleOrDefaultAsync(token)??throw Error("REVIEW_NOT_FOUND","리뷰를 찾을 수 없습니다.",404):null;long? a=after.HasValue?await db.AfterServiceCases.Where(x=>x.PublicId==after).Select(x=>(long?)x.Id).SingleOrDefaultAsync(token)??throw Error("AFTER_SERVICE_NOT_FOUND","A/S를 찾을 수 없습니다.",404):null;long? d=dispute.HasValue?await db.DisputeCases.Where(x=>x.PublicId==dispute).Select(x=>(long?)x.Id).SingleOrDefaultAsync(token)??throw Error("DISPUTE_NOT_FOUND","분쟁을 찾을 수 없습니다.",404):null;return new(r,t,rv,a,d);}
    private async Task<LinkIds> ResolveSourceAsync(SanctionSourceRequest source,CancellationToken token){var link=await ResolveLinksAsync(null,null,source.ReviewId,source.AfterServiceCaseId,source.DisputeCaseId,token);long? report=source.ReportId.HasValue?await db.Reports.Where(x=>x.PublicId==source.ReportId).Select(x=>(long?)x.Id).SingleOrDefaultAsync(token)??throw Error("REPORT_NOT_FOUND","신고를 찾을 수 없습니다.",404):null;if(report is null&&link.Review is null&&link.AfterService is null&&link.Dispute is null)throw Error("SANCTION_SOURCE_INVALID","제재 근거 한 건을 선택해 주세요.");return new LinkIds(null,null,link.Review,link.AfterService,link.Dispute,report);}
    private async Task<AdminReportRelations> RelationsAsync(Report x,CancellationToken token){var req=x.ServiceRequestId.HasValue?await db.ServiceRequests.AsNoTracking().Where(v=>v.Id==x.ServiceRequestId).Select(v=>new{v.PublicId,v.Title,v.CategoryId}).SingleAsync(token):null;var tx=x.TransactionId.HasValue?await db.Transactions.AsNoTracking().Where(v=>v.Id==x.TransactionId).Select(v=>new{v.PublicId,v.CategoryId}).SingleAsync(token):null;var review=x.ReviewId.HasValue?await db.Reviews.AsNoTracking().Where(v=>v.Id==x.ReviewId).Select(v=>new{v.PublicId,v.BodyText}).SingleAsync(token):null;var after=x.AfterServiceCaseId.HasValue?await db.AfterServiceCases.AsNoTracking().Where(v=>v.Id==x.AfterServiceCaseId).Select(v=>new{v.PublicId,v.Subject}).SingleAsync(token):null;var dispute=x.DisputeCaseId.HasValue?await db.DisputeCases.AsNoTracking().Where(v=>v.Id==x.DisputeCaseId).Select(v=>new{v.PublicId,v.Subject}).SingleAsync(token):null;var categoryId=req?.CategoryId??tx?.CategoryId;var service=categoryId.HasValue?await db.ServiceCategories.AsNoTracking().Where(v=>v.Id==categoryId).Select(v=>v.Name).SingleAsync(token):null;return new(req?.PublicId,req?.Title,tx?.PublicId,tx is null?null:Number("거래",tx.PublicId),review?.PublicId,review?.BodyText,after?.PublicId,after?.Subject,dispute?.PublicId,dispute?.Subject,service);}
    private async Task<string?> ServiceNameAsync(long? request,long? transaction,CancellationToken token){var category=request.HasValue?await db.ServiceRequests.Where(x=>x.Id==request).Select(x=>(long?)x.CategoryId).SingleAsync(token):transaction.HasValue?await db.Transactions.Where(x=>x.Id==transaction).Select(x=>(long?)x.CategoryId).SingleAsync(token):null;return category.HasValue?await db.ServiceCategories.Where(x=>x.Id==category).Select(x=>x.Name).SingleAsync(token):null;}
    private async Task<string> ScopeAsync(Sanction x,CancellationToken token){if(x.ProviderServiceCategoryId.HasValue)return "공급자 서비스 · "+await(from p in db.ProviderServiceCategories.AsNoTracking()join c in db.ServiceCategories.AsNoTracking()on p.CategoryId equals c.Id where p.Id==x.ProviderServiceCategoryId select c.Name).SingleAsync(token);if(x.ProviderProfileId.HasValue)return "공급자 전체";if(x.TargetRoleId.HasValue)return "역할 · "+await db.Roles.Where(r=>r.Id==x.TargetRoleId).Select(r=>r.Name).SingleAsync(token);return "사용자 전체";}
    private async Task<IReadOnlyList<AdminSanctionSource>> SourceItemsAsync(long sanction,CancellationToken token){var rows=await db.SanctionSources.AsNoTracking().Where(x=>x.SanctionId==sanction).ToListAsync(token);var result=new List<AdminSanctionSource>();foreach(var x in rows){Guid? report=x.ReportId.HasValue?await db.Reports.Where(v=>v.Id==x.ReportId).Select(v=>(Guid?)v.PublicId).SingleAsync(token):null;Guid? dispute=x.DisputeCaseId.HasValue?await db.DisputeCases.Where(v=>v.Id==x.DisputeCaseId).Select(v=>(Guid?)v.PublicId).SingleAsync(token):null;Guid? review=x.ReviewId.HasValue?await db.Reviews.Where(v=>v.Id==x.ReviewId).Select(v=>(Guid?)v.PublicId).SingleAsync(token):null;Guid? after=x.AfterServiceCaseId.HasValue?await db.AfterServiceCases.Where(v=>v.Id==x.AfterServiceCaseId).Select(v=>(Guid?)v.PublicId).SingleAsync(token):null;result.Add(new(report,dispute,review,after,report.HasValue?"신고":dispute.HasValue?"분쟁":review.HasValue?"리뷰":"A/S"));}return result;}
    private async Task<IReadOnlyList<AdminCaseAudit>> AuditAsync(string entity,Guid id,CancellationToken token)=>await db.AuditLogs.AsNoTracking().Where(x=>x.EntityType==entity&&x.EntityPublicId==id).OrderByDescending(x=>x.OccurredAt).Select(x=>new AdminCaseAudit(x.OccurredAt,x.ActionCode,x.ResultCode,x.Reason,x.BeforeJson,x.AfterJson)).ToListAsync(token);
    private Task<bool> MasterUsedAsync(string kind,long id,CancellationToken token)=>kind switch{"REPORT_TYPE"=>db.Reports.AnyAsync(x=>x.ReportTypeId==id,token),"SANCTION_TYPE"=>db.Sanctions.AnyAsync(x=>x.SanctionTypeId==id,token),_=>db.DisputeResolutions.AnyAsync(x=>x.LiabilityTypeId==id,token)};
    private void AddReportAction(Report item,string action,string? from,string? to,string? reason,long actor,string key,DateTime? now=null)=>db.ReportActions.Add(new(){ReportId=item.Id,ActionTypeCode=action,FromStatusCode=from,ToStatusCode=to,ActorUserId=actor,Reason=Clean(reason),OccurredAt=now??DateTime.UtcNow,IdempotencyKey=key.Trim()});
    private void AddSanctionEvent(Sanction item,string action,string? from,string to,string reason,long actor,string key,DateTime now)=>db.SanctionEvents.Add(new(){SanctionId=item.Id,ActionTypeCode=action,FromStatusCode=from,ToStatusCode=to,ActorUserId=actor,Reason=reason.Trim(),SnapshotJson=JsonSerializer.Serialize(item),OccurredAt=now,IdempotencyKey=key.Trim(),CreatedAt=now});
    private void AddAppealAction(SanctionAppeal item,string action,string? from,string to,string reason,long actor,string key,DateTime? now=null)=>db.SanctionAppealActions.Add(new(){SanctionAppealId=item.Id,ActionTypeCode=action,FromStatusCode=from,ToStatusCode=to,ActorUserId=actor,Reason=reason.Trim(),OccurredAt=now??DateTime.UtcNow,IdempotencyKey=key.Trim()});
    private void Audit(long actor,string action,string entity,Guid id,object? before,object? after,string? reason,DateTime now)=>db.AuditLogs.Add(new(){OccurredAt=now,ActorUserId=actor,ActorRoleCode=RoleCodes.Admin,ActionCode=action,EntityType=entity,EntityPublicId=id,ResultCode="SUCCESS",Reason=Clean(reason),BeforeJson=before is null?null:JsonSerializer.Serialize(before),AfterJson=after is null?null:JsonSerializer.Serialize(after)});
    private static void Touch(object row,long actor,DateTime? now=null){Set(row,"UpdatedAt",now??DateTime.UtcNow);Set(row,"UpdatedByUserId",actor);}
    private static void SetVersion(object row,string? value){if(string.IsNullOrWhiteSpace(value))return;try{Set(row,"RowVersion",Convert.FromBase64String(value));}catch{throw Error("ROW_VERSION_INVALID","변경 버전 값이 올바르지 않습니다.");}}
    private async Task SaveConcurrencyAsync(CancellationToken token){try{await db.SaveChangesAsync(token);}catch(DbUpdateConcurrencyException){throw Error("CONCURRENT_UPDATE","다른 관리자가 먼저 변경했습니다. 새로고침 후 다시 시도해 주세요.",409);}}
    private static void Set(object row,string name,object? value)=>row.GetType().GetProperty(name)!.SetValue(row,value);private static object? Get(object row,string name)=>row.GetType().GetProperty(name)!.GetValue(row);
    private static bool ValidSignature(string contentType,byte[] value)=>contentType switch{"application/pdf"=>value.Length>=5&&value[0]==0x25&&value[1]==0x50&&value[2]==0x44&&value[3]==0x46&&value[4]==0x2D,"image/jpeg"=>value.Length>=3&&value[0]==0xFF&&value[1]==0xD8&&value[2]==0xFF,"image/png"=>value.Length>=8&&value[..8].SequenceEqual(new byte[]{137,80,78,71,13,10,26,10}),_=>false};
    private static string? Clean(string? value)=>string.IsNullOrWhiteSpace(value)?null:value.Trim();private static string Number(string prefix,Guid id)=>prefix+"-"+id.ToString("N")[..8].ToUpperInvariant();private static void Page(int page,int size){if(page<1||size is<1 or>100)throw Error("PAGE_INVALID","페이지 값을 확인해 주세요.");}private static CaseManagementException Error(string code,string message,int status=400)=>new(code,message,status);
    private sealed record LinkIds(long? Request,long? Transaction,long? Review,long? AfterService,long? Dispute,long? Report=null){public bool AllNull=>Request is null&&Transaction is null&&Review is null&&AfterService is null&&Dispute is null&&Report is null;}
}
