using System.Text.Json;
using Microsoft.EntityFrameworkCore;
using SoodalLife.Api.Domain.Entities;
using SoodalLife.Api.Features.Authentication;
using SoodalLife.Api.Infrastructure.Persistence;

namespace SoodalLife.Api.Features.Admin;

public sealed class TrustCalculationService(SoodalLifeDbContext db)
{
    private static readonly Dictionary<string,(string Name,string Rule)> Definitions=new()
    { ["EVIDENCE"]=("인증·증빙","EVIDENCE_COMPLETENESS"),["TRANSACTION"]=("거래이행","TRANSACTION_COMPLETION_RATE"),["REVIEW"]=("고객평가","VERIFIED_PUBLIC_RATING_AVERAGE"),["AFTER_SERVICE"]=("A/S","FINALIZED_AFTER_SERVICE_OUTCOME"),["DISPUTE"]=("분쟁","STRUCTURED_LIABILITY_MAPPING"),["SANCTION"]=("제재","DECIDED_SANCTION_MAPPING") };

    public async Task<IReadOnlyList<TrustPolicyListItem>> GetPoliciesAsync(CancellationToken token)
    {var rows=await db.TrustPolicies.AsNoTracking().OrderByDescending(x=>x.EffectiveFrom).ThenByDescending(x=>x.Id).ToListAsync(token);var result=new List<TrustPolicyListItem>();foreach(var x in rows){var rules=Parse(x.RulesJson);result.Add(new(x.PublicId,x.PolicyVersion,x.PolicyName,x.StatusCode,x.EffectiveFrom,x.EffectiveTo,rules.MinimumCompletedTransactions,rules.MinimumVerifiedReviews,rules.Components.Sum(v=>v.Weight),x.CreatedByUserId.HasValue?await NameAsync(x.CreatedByUserId.Value,token):null,x.ApprovedByUserId.HasValue?await NameAsync(x.ApprovedByUserId.Value,token):null,x.ApprovedAt,Convert.ToBase64String(x.RowVersion),rules.Components.Select(v=>new TrustPolicyComponentResponse(v.Code,Definitions[v.Code].Name,v.Weight,v.RuleType,JsonSerializer.Serialize(v.Settings))).ToArray()));}return result;}

    public async Task<TrustPolicyListItem> UpdatePolicyAsync(Guid id,TrustPolicyRequest request,Guid actorId,CancellationToken token)
    {var actor=await ActorAsync(actorId,token);var row=await PolicyAsync(id,token);if(row.StatusCode!="DRAFT")throw Error("TRUST_POLICY_IMMUTABLE","DRAFT 정책만 수정할 수 있습니다.",409);SetVersion(row,request.RowVersion);var rules=FromRequest(request);Validate(rules);if(await db.TrustPolicies.AnyAsync(x=>x.Id!=row.Id&&x.PolicyVersion==request.PolicyVersion,token))throw Error("TRUST_POLICY_VERSION_DUPLICATE","이미 사용 중인 정책 버전입니다.",409);row.PolicyVersion=request.PolicyVersion.Trim();row.PolicyName=request.PolicyName.Trim();row.RulesJson=JsonSerializer.Serialize(rules);row.EffectiveFrom=request.EffectiveFrom.ToUniversalTime();row.EffectiveTo=request.EffectiveTo?.ToUniversalTime();row.UpdatedAt=DateTime.UtcNow;row.UpdatedByUserId=actor;await SavePolicyAndAudit(actor,"TRUST_POLICY_UPDATED",row.PublicId,null,row,"정책 초안 수정",token,true);return(await GetPoliciesAsync(token)).Single(x=>x.Id==id);}

    public async Task<TrustPolicyListItem> ClonePolicyAsync(Guid sourceId,TrustPolicyCloneRequest request,Guid actorId,CancellationToken token)
    {var actor=await ActorAsync(actorId,token);var source=await PolicyAsync(sourceId,token);if(await db.TrustPolicies.AnyAsync(x=>x.PolicyVersion==request.NewVersion,token))throw Error("TRUST_POLICY_VERSION_DUPLICATE","이미 사용 중인 정책 버전입니다.",409);var now=DateTime.UtcNow;var row=new TrustPolicy{PolicyVersion=request.NewVersion.Trim(),PolicyName=request.NewName.Trim(),TargetTypeCode=source.TargetTypeCode,ScopeTypeCode=source.ScopeTypeCode,StatusCode="DRAFT",RulesJson=source.RulesJson,EffectiveFrom=request.EffectiveFrom.ToUniversalTime(),EffectiveTo=request.EffectiveTo?.ToUniversalTime(),CreatedAt=now,CreatedByUserId=actor,UpdatedAt=now,UpdatedByUserId=actor};db.TrustPolicies.Add(row);await SavePolicyAndAudit(actor,"TRUST_POLICY_CLONED",row.PublicId,null,new{source=source.PublicId,row.PolicyVersion},"정책 버전 복제",token,false);return(await GetPoliciesAsync(token)).Single(x=>x.Id==row.PublicId);}

    public Task<TrustPolicyListItem> ApprovePolicyAsync(Guid id,TrustPolicyActionRequest request,Guid actorId,CancellationToken token)=>ChangePolicyStatus(id,"APPROVED",request,actorId,token);
    public Task<TrustPolicyListItem> ActivatePolicyAsync(Guid id,TrustPolicyActionRequest request,Guid actorId,CancellationToken token)=>ChangePolicyStatus(id,"ACTIVE",request,actorId,token);
    public Task<TrustPolicyListItem> RetirePolicyAsync(Guid id,TrustPolicyActionRequest request,Guid actorId,CancellationToken token)=>ChangePolicyStatus(id,"RETIRED",request,actorId,token);
    public Task<TrustCalculationResponse> SimulateAsync(Guid providerId,Guid policyId,string idempotency,Guid actorId,CancellationToken token)=>CalculateAsync(providerId,policyId,"SIMULATION","ADMIN_SIMULATION",null,idempotency,actorId,token);
    public Task<TrustCalculationResponse> RecalculateActiveAsync(Guid providerId,string idempotency,Guid actorId,CancellationToken token)=>CalculateActiveAsync(providerId,"ADMIN_RECALCULATION",null,idempotency,actorId,token);

    public async Task<TrustManualAdjustmentResponse> AdjustScoreAsync(Guid providerId,TrustManualAdjustmentRequest request,Guid actorId,CancellationToken token)
    {
        if(request.Score is <0 or >100)throw Error("TRUST_ADJUSTMENT_SCORE_INVALID","조정 점수는 0점부터 100점 사이여야 합니다.");
        if(string.IsNullOrWhiteSpace(request.Reason))throw Error("TRUST_ADJUSTMENT_REASON_REQUIRED","관리자 조정 사유를 입력해 주세요.");
        var actor=await ActorAsync(actorId,token);var key=$"admin-trust-adjustment:{request.IdempotencyKey.Trim()}";
        var existing=await db.TrustScoreEvents.AsNoTracking().SingleOrDefaultAsync(x=>x.IdempotencyKey==key,token);
        if(existing is not null)
        {
            var existingProviderId=await db.ProviderProfiles.AsNoTracking().Where(x=>x.Id==existing.ProviderProfileId).Select(x=>x.PublicId).SingleAsync(token);
            if(existingProviderId!=providerId)throw Error("TRUST_ADJUSTMENT_IDEMPOTENCY_CONFLICT","이미 다른 전문가 처리에 사용된 요청 키입니다.",409);
            return new(providerId,existing.ScoreBefore,existing.ScoreAfter??request.Score,AdminTrustService.GradeLabel(existing.ScoreAfter),existing.OccurredAt,existing.PublicId);
        }
        var provider=await db.ProviderProfiles.SingleOrDefaultAsync(x=>x.PublicId==providerId,token)??throw Error("TRUST_PROVIDER_NOT_FOUND","전문가를 찾을 수 없습니다.",404);
        var current=await db.ProviderTrustScoreCurrent.SingleOrDefaultAsync(x=>x.ProviderProfileId==provider.Id,token);var before=current?.Score??provider.TrustScore;var now=DateTime.UtcNow;var grade=GradeCode(request.Score);
        var activePolicy=await db.TrustPolicies.AsNoTracking().Where(x=>x.StatusCode=="ACTIVE"&&x.EffectiveFrom<=now&&(x.EffectiveTo==null||x.EffectiveTo>now)).OrderByDescending(x=>x.EffectiveFrom).FirstOrDefaultAsync(token);
        await using var transaction=db.Database.IsRelational()?await db.Database.BeginTransactionAsync(token):null;
        var evt=new TrustScoreEvent{ProviderProfileId=provider.Id,TrustPolicyId=activePolicy?.Id,EventTypeCode="MANUAL_ADJUSTMENT",SourceTypeCode="ADMIN",IdempotencyKey=key,ScoreBefore=before,ScoreDelta=request.Score-before.GetValueOrDefault(),ScoreAfter=request.Score,GradeBefore=current?.GradeCode??GradeCode(before),GradeAfter=grade,DecisionCode="ADMIN_DECISION",ReasonText=request.Reason.Trim(),PolicySnapshotJson=activePolicy is null?null:JsonSerializer.Serialize(new{activePolicy.PublicId,activePolicy.PolicyVersion,activePolicy.StatusCode}),SourceSnapshotJson=JsonSerializer.Serialize(new{administrator=actorId,providerId}),OccurredAt=now,ProcessedAt=now,ProcessedByUserId=actor,CreatedAt=now};
        db.TrustScoreEvents.Add(evt);await db.SaveChangesAsync(token);
        if(current is null){current=new(){ProviderProfileId=provider.Id,CreatedAt=now};db.ProviderTrustScoreCurrent.Add(current);}current.TrustPolicyId=activePolicy?.Id;current.Score=request.Score;current.GradeCode=grade;current.EvaluationStatusCode="CALCULATED";current.CalculatedAt=now;current.LastEventId=evt.Id;current.SourceTypeCode="ADMIN_ADJUSTMENT";current.UpdatedAt=now;provider.TrustScore=request.Score;provider.UpdatedAt=now;provider.UpdatedByUserId=actor;
        Audit(actor,"TRUST_SCORE_MANUAL_ADJUSTMENT",provider.PublicId,new{score=before},new{score=request.Score,grade},request.Reason.Trim(),"PROVIDER_TRUST_SCORE");await db.SaveChangesAsync(token);if(transaction is not null)await transaction.CommitAsync(token);
        return new(provider.PublicId,before,request.Score,AdminTrustService.GradeLabel(request.Score),now,evt.PublicId);
    }

    public async Task<TrustCalculationResponse> CalculateActiveAsync(Guid providerId,string sourceType,Guid? sourceId,string idempotency,Guid? actorId,CancellationToken token)
    {var now=DateTime.UtcNow;var policy=await db.TrustPolicies.AsNoTracking().Where(x=>x.StatusCode=="ACTIVE"&&x.EffectiveFrom<=now&&(x.EffectiveTo==null||x.EffectiveTo>now)).OrderByDescending(x=>x.EffectiveFrom).FirstOrDefaultAsync(token)??throw Error("ACTIVE_TRUST_POLICY_NOT_FOUND","현재 적용 중인 신뢰도 정책이 없습니다.",409);return await CalculateAsync(providerId,policy.PublicId,"ACTUAL",sourceType,sourceId,idempotency,actorId,token);}

    public async Task QueueRecalculationAsync(Guid providerId,string sourceType,Guid? sourceId,string idempotency,long? actorId,CancellationToken token)
    {if(await db.OutboxEvents.AnyAsync(x=>x.IdempotencyKey==idempotency,token))return;db.OutboxEvents.Add(new(){AggregateType="ProviderTrust",AggregatePublicId=providerId,EventType="TRUST_RECALCULATION_REQUESTED",PayloadJson=JsonSerializer.Serialize(new{providerId,sourceType,sourceId}),StatusCode="PENDING",OccurredAt=DateTime.UtcNow,AvailableAt=DateTime.UtcNow,IdempotencyKey=idempotency,CreatedByUserId=actorId});await db.SaveChangesAsync(token);}

    private async Task<TrustCalculationResponse> CalculateAsync(Guid providerId,Guid policyId,string mode,string sourceType,Guid? sourceId,string idempotency,Guid? actorId,CancellationToken token)
    {
        var prior=await db.ProviderTrustCalculationResults.AsNoTracking().SingleOrDefaultAsync(x=>x.IdempotencyKey==idempotency,token);if(prior is not null)return await BuildResult(prior,token);
        var provider=await db.ProviderProfiles.SingleOrDefaultAsync(x=>x.PublicId==providerId,token)??throw Error("TRUST_PROVIDER_NOT_FOUND","전문가를 찾을 수 없습니다.",404);var policy=await db.TrustPolicies.SingleOrDefaultAsync(x=>x.PublicId==policyId,token)??throw Error("TRUST_POLICY_NOT_FOUND","신뢰도 정책을 찾을 수 없습니다.",404);if(mode=="ACTUAL"&&policy.StatusCode!="ACTIVE")throw Error("TRUST_POLICY_NOT_ACTIVE","운영 중인 정책으로만 실제 산정할 수 있습니다.",409);var rules=Parse(policy.RulesJson);Validate(rules);var now=DateTime.UtcNow;var performance=await BuildTransactionPerformance(provider,token);var parts=new List<ComponentValue>();foreach(var rule in rules.Components)parts.Add(await CalculateComponent(provider,rule,rules,now,performance,token));var completed=performance.Completed;var reviews=await db.Reviews.CountAsync(x=>x.ProviderProfileId==provider.Id&&x.VerificationStatusCode=="VERIFIED_TRANSACTION"&&x.VisibilityStatusCode=="PUBLIC",token);var unavailable=parts.Where(x=>!x.IsCalculable).Select(x=>$"{x.Name}: {x.Reason}").ToArray();var enough=provider.ApprovalStatusCode=="APPROVED"&&completed>=rules.MinimumCompletedTransactions&&reviews>=rules.MinimumVerifiedReviews&&unavailable.Length==0;decimal? score=enough?decimal.Round(parts.Sum(x=>x.WeightedScore??0),4):null;var grade=GradeCode(score);var result=new ProviderTrustCalculationResult{ProviderProfileId=provider.Id,TrustPolicyId=policy.Id,CalculationModeCode=mode,ResultStatusCode=enough?"CALCULATED":"INSUFFICIENT_DATA",Score=score,GradeCode=grade,EvaluationStatusCode=enough?"CALCULATED":"NEW_OR_EVALUATING",InsufficiencyReason=enough?null:string.Join(" / ",new[]{provider.ApprovalStatusCode=="APPROVED"?null:"전문가 전체 승인 필요",completed>=rules.MinimumCompletedTransactions?null:$"완료 실적 {completed}/{rules.MinimumCompletedTransactions}",reviews>=rules.MinimumVerifiedReviews?null:$"검증된 고객 후기 {reviews}/{rules.MinimumVerifiedReviews}"}.Where(x=>x is not null).Concat(unavailable)),CompletedTransactionCount=completed,VerifiedReviewCount=reviews,PolicySnapshotJson=JsonSerializer.Serialize(new{policy.PublicId,policy.PolicyVersion,policy.StatusCode,rules}),SourceSnapshotJson=JsonSerializer.Serialize(new{sourceType,sourceId,providerId,completedPerformance=completed,verifiedReviews=reviews}),CalculatedAt=now,RequestedByUserId=actorId.HasValue?await ActorAsync(actorId.Value,token):null,IdempotencyKey=idempotency.Trim(),CreatedAt=now};
        await using var transaction=mode=="ACTUAL"&&db.Database.IsRelational()?await db.Database.BeginTransactionAsync(token):null;db.ProviderTrustCalculationResults.Add(result);await db.SaveChangesAsync(token);foreach(var x in parts)db.ProviderTrustScoreComponents.Add(new(){CalculationResultId=result.Id,ComponentCode=x.Code,Weight=x.Weight,RawValueJson=x.RawJson,NormalizedScore=x.NormalizedScore,WeightedScore=x.WeightedScore,SampleCount=x.SampleCount,IsCalculable=x.IsCalculable,UnavailableReason=x.Reason,SourceSnapshotJson=x.SourceJson,CalculatedAt=now,CreatedAt=now});await db.SaveChangesAsync(token);
        if(mode=="ACTUAL"&&enough){var current=await db.ProviderTrustScoreCurrent.SingleOrDefaultAsync(x=>x.ProviderProfileId==provider.Id,token);var before=current?.Score;var eventKey=$"trust-calculation:{idempotency}";var existing=await db.TrustScoreEvents.SingleOrDefaultAsync(x=>x.IdempotencyKey==eventKey,token);if(existing is null&&before!=score){var evt=new TrustScoreEvent{ProviderProfileId=provider.Id,TrustPolicyId=policy.Id,EventTypeCode="AUTOMATIC_CALCULATION",SourceTypeCode=sourceType,SourcePublicId=sourceId,IdempotencyKey=eventKey,ScoreBefore=before,ScoreDelta=score-before.GetValueOrDefault(),ScoreAfter=score,GradeBefore=current?.GradeCode,GradeAfter=grade,DecisionCode="POLICY_ENGINE",ReasonText="ACTIVE Trust 정책 자동산정",PolicySnapshotJson=result.PolicySnapshotJson,SourceSnapshotJson=result.SourceSnapshotJson,OccurredAt=now,ProcessedAt=now,ProcessedByUserId=result.RequestedByUserId,CreatedAt=now};db.TrustScoreEvents.Add(evt);await db.SaveChangesAsync(token);if(current is null){current=new(){ProviderProfileId=provider.Id,CreatedAt=now};db.ProviderTrustScoreCurrent.Add(current);}current.TrustPolicyId=policy.Id;current.Score=score;current.GradeCode=grade;current.EvaluationStatusCode="CALCULATED";current.CalculatedAt=now;current.LastEventId=evt.Id;current.SourceTypeCode="POLICY_ENGINE";current.UpdatedAt=now;result.AppliedTrustScoreEventId=evt.Id;await db.SaveChangesAsync(token);}if(transaction is not null)await transaction.CommitAsync(token);}
        return await BuildResult(result,token);
    }

    private async Task<ComponentValue> CalculateComponent(ProviderProfile provider,ComponentRule rule,PolicyRules policy,DateTime now,TransactionPerformance performance,CancellationToken token)
    {
        if(rule.Code=="EVIDENCE"){var services=await db.ProviderServiceCategories.Where(x=>x.ProviderProfileId==provider.Id&&x.StatusCode=="ACTIVE").Select(x=>new{x.Id,x.CategoryId}).ToListAsync(token);var approvals=await db.ProviderServiceApprovals.CountAsync(x=>services.Select(v=>v.Id).Contains(x.ProviderServiceCategoryId)&&x.ApprovalStatusCode=="APPROVED",token);var assignments=await(from assignment in db.CategoryProviderRequirementAssignments.AsNoTracking()join operation in db.CategoryOperationPolicies.AsNoTracking()on assignment.CategoryOperationPolicyId equals operation.Id where assignment.IsActive&&assignment.IsRequired&&services.Select(x=>x.CategoryId).Contains(operation.CategoryId)select assignment.Id).Distinct().ToArrayAsync(token);if(services.Count==0||assignments.Length==0)return Unavailable(rule,"활성 서비스의 구조화 필수요건이 없습니다.",assignments.Length,new{providerApproval=provider.ApprovalStatusCode,serviceCount=services.Count,requiredAssignments=assignments.Length});var verified=await db.ProviderServiceRequirementVerifications.CountAsync(x=>services.Select(v=>v.Id).Contains(x.ProviderServiceCategoryId)&&assignments.Contains(x.RequirementAssignmentId)&&x.VerificationStatusCode=="APPROVED",token);var valid=await db.ProviderServiceRequirementVerifications.CountAsync(x=>services.Select(v=>v.Id).Contains(x.ProviderServiceCategoryId)&&assignments.Contains(x.RequirementAssignmentId)&&x.VerificationStatusCode=="APPROVED"&&(x.ExpiresAt==null||x.ExpiresAt>=DateOnly.FromDateTime(now)),token);var normalized=100m*(Get(rule,"approvalRatio")*(provider.ApprovalStatusCode=="APPROVED"?1:0)+Get(rule,"serviceApprovalRatio")*Ratio(approvals,services.Count)+Get(rule,"requiredVerificationRatio")*Ratio(verified,assignments.Length)+Get(rule,"notExpiredRatio")*Ratio(valid,assignments.Length));return Value(rule,normalized,assignments.Length,new{providerApproval=provider.ApprovalStatusCode,serviceApprovals=approvals,serviceCount=services.Count,requiredAssignments=assignments.Length,verified,valid});}
        if(rule.Code=="TRANSACTION"){if(performance.Completed<policy.MinimumCompletedTransactions)return Unavailable(rule,$"완료 실적 표본 부족 ({performance.Completed}/{policy.MinimumCompletedTransactions})",performance.Completed,performance);var total=performance.Completed+performance.ProviderFaultCancellations;var normalized=100m*(Get(rule,"completionRateRatio")*Ratio(performance.Completed,total)+Get(rule,"completionEvidenceRatio")*Ratio(performance.Evidence,performance.Completed));return Value(rule,normalized,performance.Completed,performance);}
        if(rule.Code=="REVIEW"){var activeItems=await db.ReviewRatingItems.Where(x=>x.IsActive).Select(x=>new{x.Id,x.MinValue,x.MaxValue}).ToListAsync(token);if(activeItems.Count==0)return Unavailable(rule,"활성 Rating Item Master가 없습니다.",0,new{activeRatingItems=0});var reviewIds=await db.Reviews.Where(x=>x.ProviderProfileId==provider.Id&&x.VerificationStatusCode=="VERIFIED_TRANSACTION"&&x.VisibilityStatusCode=="PUBLIC").Select(x=>x.Id).ToArrayAsync(token);if(reviewIds.Length<policy.MinimumVerifiedReviews)return Unavailable(rule,$"검증 공개 리뷰 표본 부족 ({reviewIds.Length}/{policy.MinimumVerifiedReviews})",reviewIds.Length,new{verifiedPublicReviews=reviewIds.Length,activeRatingItems=activeItems.Count});var ratings=await db.ReviewRatings.Where(x=>reviewIds.Contains(x.ReviewId)&&activeItems.Select(i=>i.Id).Contains(x.RatingItemId)).ToListAsync(token);if(ratings.Count==0)return Unavailable(rule,"활성 평가항목의 평점 데이터가 없습니다.",reviewIds.Length,new{verifiedPublicReviews=reviewIds.Length});var normalized=ratings.Average(x=>{var item=activeItems.Single(i=>i.Id==x.RatingItemId);return(item.MaxValue==item.MinValue?0:(x.RatingValue-item.MinValue)/(item.MaxValue-item.MinValue))*100m;});return Value(rule,normalized,reviewIds.Length,new{verifiedPublicReviews=reviewIds.Length,ratingCount=ratings.Count,activeRatingItems=activeItems.Count});}
        if(rule.Code=="AFTER_SERVICE"){var cases=await db.AfterServiceCases.Where(x=>x.ProviderProfileId==provider.Id&&(x.StatusCode=="RESOLVED"||x.StatusCode=="UNRESOLVED_CLOSED"||x.StatusCode=="CONVERTED_TO_DISPUTE")).ToListAsync(token);if(cases.Count==0)return Value(rule,GetOr(rule,"noCaseValue",1m)*100m,0,new{finalizedCases=0,baseline="NO_FINALIZED_AFTER_SERVICE"});var normalized=cases.Average(x=>Math.Clamp((x.StatusCode=="RESOLVED"?Get(rule,"resolvedValue"):Get(rule,"unresolvedValue"))-(x.RecurrenceOccurred==true?Get(rule,"recurrencePenalty"):0)-(x.StatusCode=="CONVERTED_TO_DISPUTE"?Get(rule,"disputeConversionPenalty"):0),0,1))*100m;return Value(rule,normalized,cases.Count,new{finalizedCases=cases.Count,resolved=cases.Count(x=>x.StatusCode=="RESOLVED"),unresolved=cases.Count(x=>x.StatusCode=="UNRESOLVED_CLOSED"),converted=cases.Count(x=>x.StatusCode=="CONVERTED_TO_DISPUTE"),recurrence=cases.Count(x=>x.RecurrenceOccurred==true)});}
        if(rule.Code=="DISPUTE"){var rows=await(from resolution in db.DisputeResolutions join dispute in db.DisputeCases on resolution.DisputeCaseId equals dispute.Id join tx in db.Transactions on dispute.TransactionId equals tx.Id join liability in db.DisputeLiabilityTypes on resolution.LiabilityTypeId equals liability.Id where tx.ProviderProfileId==provider.Id&&resolution.IsCurrent select liability.Code).ToListAsync(token);if(rows.Count==0)return Value(rule,GetOr(rule,"noDisputeScore",100m),0,new{resolvedDisputes=0,baseline="NO_FINALIZED_DISPUTE"});if(!await db.DisputeLiabilityTypes.AnyAsync(x=>x.IsActive,token))return Unavailable(rule,"등록된 귀책유형 Master가 없습니다.",rows.Count,new{activeLiabilityTypes=0});var map=Map(rule,"liabilityScores");if(rows.Any(x=>!map.ContainsKey(x)))return Unavailable(rule,"귀책유형별 점수 규칙이 설정되지 않았습니다.",rows.Count,new{resolvedDisputes=rows.Count,liabilityCodes=rows.Distinct()});return Value(rule,rows.Average(x=>map[x]),rows.Count,new{resolvedDisputes=rows.Count,liabilityCodes=rows});}
        var sanctions=await(from sanction in db.Sanctions join type in db.SanctionTypes on sanction.SanctionTypeId equals type.Id where sanction.TargetUserId==provider.UserId&&sanction.StatusCode=="ACTIVE" select type.Code).ToListAsync(token);if(sanctions.Count==0)return Value(rule,GetOr(rule,"noSanctionScore",100m),0,new{activeSanctions=0,baseline="NO_ACTIVE_SANCTION"});if(!await db.SanctionTypes.AnyAsync(x=>x.IsActive,token))return Unavailable(rule,"등록된 제재유형 Master가 없습니다.",sanctions.Count,new{activeSanctionTypes=0});var sanctionMap=Map(rule,"sanctionScores");if(sanctions.Any(x=>!sanctionMap.ContainsKey(x)))return Unavailable(rule,"제재유형별 점수 규칙이 설정되지 않았습니다.",sanctions.Count,new{activeSanctions=sanctions.Count,sanctionCodes=sanctions.Distinct()});return Value(rule,sanctions.Average(x=>sanctionMap[x]),sanctions.Count,new{activeSanctions=sanctions.Count,sanctionCodes=sanctions});
    }

    private async Task<TransactionPerformance> BuildTransactionPerformance(ProviderProfile provider,CancellationToken token)
    {
        var interiorRequestIds=await db.InteriorProjects.AsNoTracking().Select(x=>x.ServiceRequestId).ToArrayAsync(token);
        var transactions=await(from transaction in db.Transactions.AsNoTracking()
            join request0 in db.ServiceRequests.AsNoTracking() on transaction.ServiceRequestId equals request0.Id into requests
            from request in requests.DefaultIfEmpty()
            where transaction.ProviderProfileId==provider.Id
            select new{transaction.Id,transaction.StatusCode,IsUrgent=request!=null&&request.IsUrgent,IsInterior=interiorRequestIds.Contains(transaction.ServiceRequestId)}).ToListAsync(token);
        var ordinaryCompletedIds=transactions.Where(x=>x.StatusCode=="COMPLETED"&&!x.IsUrgent&&!x.IsInterior).Select(x=>x.Id).ToArray();
        var emergencyCompletedIds=transactions.Where(x=>x.StatusCode=="COMPLETED"&&x.IsUrgent&&!x.IsInterior).Select(x=>x.Id).ToArray();
        var careCompleted=await db.SubscriptionVisitSchedules.AsNoTracking().CountAsync(x=>x.ProviderProfileId==provider.Id&&x.StatusCode=="COMPLETED",token);
        var careEvidence=await db.SubscriptionVisitSchedules.AsNoTracking().CountAsync(x=>x.ProviderProfileId==provider.Id&&x.StatusCode=="COMPLETED"&&db.SubscriptionVisitFiles.Any(f=>f.SubscriptionVisitScheduleId==x.Id),token);
        var interiorProjects=await db.InteriorProjects.AsNoTracking().Where(x=>x.SelectedContractorProviderId==provider.Id&&x.StatusCode=="COMPLETED").Select(x=>x.Id).ToArrayAsync(token);
        var interiorEvidence=await db.InteriorProjects.AsNoTracking().CountAsync(project=>interiorProjects.Contains(project.Id)&&db.InteriorWorkStages.Any(stage=>stage.InteriorProjectId==project.Id&&db.InteriorStageInspections.Any(inspection=>inspection.WorkStageId==stage.Id&&inspection.InspectionStatusCode=="PASSED")),token);
        var completedTransactionIds=ordinaryCompletedIds.Concat(emergencyCompletedIds).ToArray();
        var completionEvidenceIds=await(from completion in db.WorkCompletions.AsNoTracking() where completedTransactionIds.Contains(completion.TransactionId) where db.WorkCompletionRevisions.Any(revision=>revision.WorkCompletionId==completion.Id&&db.CompletionEvidenceFiles.Any(file=>file.CompletionRevisionId==revision.Id)) select completion.TransactionId).Distinct().ToArrayAsync(token);
        var emergencyEventEvidenceIds=await db.EmergencyProgressEvents.AsNoTracking().Where(x=>emergencyCompletedIds.Contains(x.TransactionId)&&x.EventTypeCode=="COMPLETED").Select(x=>x.TransactionId).Distinct().ToArrayAsync(token);
        var approvedProviderCancellations=await db.TransactionCancellationRequests.AsNoTracking().Where(x=>x.RequestedByUserId==provider.UserId&&x.StatusCode=="APPROVED").Select(x=>x.TransactionId).Distinct().ToArrayAsync(token);
        var providerFaultCancellations=transactions.Count(x=>x.StatusCode=="CANCELLED"&&approvedProviderCancellations.Contains(x.Id));
        var neutralCancellations=transactions.Count(x=>x.StatusCode=="CANCELLED")-providerFaultCancellations;
        var ordinary=ordinaryCompletedIds.Length;var emergency=emergencyCompletedIds.Length;var interior=interiorProjects.Length;var completed=ordinary+emergency+careCompleted+interior;
        var evidence=Math.Min(completed,completionEvidenceIds.Concat(emergencyEventEvidenceIds).Distinct().Count()+careEvidence+interiorEvidence);
        return new(completed,providerFaultCancellations,neutralCancellations,evidence,ordinary,emergency,careCompleted,interior);
    }

    private async Task<TrustPolicyListItem> ChangePolicyStatus(Guid id,string target,TrustPolicyActionRequest request,Guid actorId,CancellationToken token){var actor=await ActorAsync(actorId,token);var row=await PolicyAsync(id,token);if(target=="APPROVED"&&row.StatusCode!="DRAFT"||target=="ACTIVE"&&row.StatusCode!="APPROVED"||target=="RETIRED"&&row.StatusCode!="ACTIVE")throw Error("TRUST_POLICY_TRANSITION_INVALID","정책 상태 전환 순서를 확인해 주세요.",409);SetVersion(row,request.RowVersion);var rules=Parse(row.RulesJson);Validate(rules);if(target!="RETIRED"&&await db.TrustPolicies.AnyAsync(x=>x.Id!=row.Id&&(x.StatusCode=="APPROVED"||x.StatusCode=="ACTIVE")&&x.TargetTypeCode==row.TargetTypeCode&&x.ScopeTypeCode==row.ScopeTypeCode&&x.EffectiveFrom<(row.EffectiveTo??DateTime.MaxValue)&&(x.EffectiveTo??DateTime.MaxValue)>row.EffectiveFrom,token))throw Error("TRUST_POLICY_PERIOD_OVERLAP","적용기간이 겹치는 승인·활성 정책이 있습니다.",409);var now=DateTime.UtcNow;row.StatusCode=target;if(target=="APPROVED"){row.ApprovedAt=now;row.ApprovedByUserId=actor;}row.UpdatedAt=now;row.UpdatedByUserId=actor;await SavePolicyAndAudit(actor,$"TRUST_POLICY_{target}",row.PublicId,null,new{row.StatusCode},request.Reason,token,true);return(await GetPoliciesAsync(token)).Single(x=>x.Id==id);}
    private async Task<TrustCalculationResponse> BuildResult(ProviderTrustCalculationResult row,CancellationToken token){var provider=await db.ProviderProfiles.AsNoTracking().SingleAsync(x=>x.Id==row.ProviderProfileId,token);var policy=await db.TrustPolicies.AsNoTracking().SingleAsync(x=>x.Id==row.TrustPolicyId,token);var componentRows=await db.ProviderTrustScoreComponents.AsNoTracking().Where(x=>x.CalculationResultId==row.Id).OrderBy(x=>x.Id).ToListAsync(token);var parts=componentRows.Select(x=>new TrustComponentResultResponse(x.ComponentCode,Definitions[x.ComponentCode].Name,x.Weight,x.RawValueJson,x.NormalizedScore,x.WeightedScore,x.SampleCount,x.IsCalculable,x.UnavailableReason,x.SourceSnapshotJson,Link(x.ComponentCode,provider.PublicId))).ToArray();return new(row.PublicId,provider.PublicId,policy.PublicId,policy.PolicyVersion,policy.StatusCode,row.CalculationModeCode,row.ResultStatusCode,row.Score,AdminTrustService.GradeLabel(row.Score),row.EvaluationStatusCode,row.InsufficiencyReason,row.CompletedTransactionCount,row.VerifiedReviewCount,row.CalculatedAt,parts);}
    private static PolicyRules FromRequest(TrustPolicyRequest x)=>new(x.MinimumCompletedTransactions,x.MinimumVerifiedReviews,x.Components.Select(v=>new ComponentRule(v.Code.Trim().ToUpperInvariant(),v.Weight,v.RuleType.Trim().ToUpperInvariant(),v.Settings.ToDictionary(p=>p.Key,p=>JsonSerializer.SerializeToElement(p.Value)))).ToList());
    internal static PolicyRules Parse(string json){try{return JsonSerializer.Deserialize<PolicyRules>(json,new JsonSerializerOptions{PropertyNameCaseInsensitive=true})??throw Error("TRUST_POLICY_RULES_INVALID","정책 규칙이 비어 있습니다.");}catch(JsonException){throw Error("TRUST_POLICY_RULES_INVALID","정책 규칙 JSON을 해석할 수 없습니다.");}}
    internal static void Validate(PolicyRules rules)
    {
        if(rules.MinimumCompletedTransactions<1||rules.MinimumVerifiedReviews<1)throw Error("TRUST_POLICY_SAMPLE_INVALID","최소 표본은 1 이상이어야 합니다.");
        if(rules.Components.Count!=Definitions.Count||rules.Components.Select(x=>x.Code).Distinct().Count()!=Definitions.Count||rules.Components.Any(x=>!Definitions.TryGetValue(x.Code,out var definition)||definition.Rule!=x.RuleType))throw Error("TRUST_POLICY_COMPONENT_INVALID","지원되는 6개 Component와 Rule Type을 모두 한 번씩 설정해 주세요.");
        if(rules.Components.Any(x=>x.Weight<=0||x.Weight>100)||rules.Components.Sum(x=>x.Weight)!=100)throw Error("TRUST_POLICY_WEIGHT_INVALID","Component 가중치 합계는 100이어야 합니다.");
        foreach(var component in rules.Components)
        {
            if(component.Code=="EVIDENCE")Ratios(component,"approvalRatio","serviceApprovalRatio","requiredVerificationRatio","notExpiredRatio");
            else if(component.Code=="TRANSACTION")Ratios(component,"completionRateRatio","completionEvidenceRatio");
            else if(component.Code=="REVIEW"&&component.Settings.Count!=0)throw SettingError();
            else if(component.Code=="AFTER_SERVICE")NumbersWithOptional(component,"noCaseValue","resolvedValue","unresolvedValue","recurrencePenalty","disputeConversionPenalty");
            else if(component.Code=="DISPUTE")MappingWithOptionalScore(component,"liabilityScores","noDisputeScore");
            else if(component.Code=="SANCTION")MappingWithOptionalScore(component,"sanctionScores","noSanctionScore");
        }

        static void Ratios(ComponentRule rule,params string[] keys){Numbers(rule,keys);if(keys.Sum(key=>rule.Settings[key].GetDecimal())!=1m)throw SettingError();}
        static void Numbers(ComponentRule rule,params string[] keys){if(rule.Settings.Count!=keys.Length||keys.Any(key=>!rule.Settings.TryGetValue(key,out var value)||value.ValueKind!=JsonValueKind.Number||value.GetDecimal()<0||value.GetDecimal()>1))throw SettingError();}
        static void NumbersWithOptional(ComponentRule rule,string optional,params string[] keys){if(rule.Settings.Keys.Any(key=>key!=optional&&!keys.Contains(key))||keys.Any(key=>!rule.Settings.TryGetValue(key,out var value)||value.ValueKind!=JsonValueKind.Number||value.GetDecimal()<0||value.GetDecimal()>1)||rule.Settings.TryGetValue(optional,out var option)&&(option.ValueKind!=JsonValueKind.Number||option.GetDecimal()<0||option.GetDecimal()>1))throw SettingError();}
        static void MappingWithOptionalScore(ComponentRule rule,string key,string optional){if(rule.Settings.Keys.Any(value=>value!=key&&value!=optional)||!rule.Settings.TryGetValue(key,out var value)||value.ValueKind!=JsonValueKind.Object||value.EnumerateObject().Any(item=>item.Value.ValueKind!=JsonValueKind.Number||item.Value.GetDecimal()<0||item.Value.GetDecimal()>100)||rule.Settings.TryGetValue(optional,out var score)&&(score.ValueKind!=JsonValueKind.Number||score.GetDecimal()<0||score.GetDecimal()>100))throw SettingError();}
        static TrustCalculationException SettingError()=>Error("TRUST_POLICY_SETTING_INVALID","Component별 필수 설정과 허용 범위를 확인해 주세요.");
    }
    private static ComponentValue Value(ComponentRule rule,decimal normalized,int count,object raw){normalized=Math.Clamp(normalized,0,100);var json=JsonSerializer.Serialize(raw);return new(rule.Code,Definitions[rule.Code].Name,rule.Weight,json,normalized,decimal.Round(normalized/100m*rule.Weight,4),count,true,null,json);}
    private static ComponentValue Unavailable(ComponentRule rule,string reason,int count,object raw){var json=JsonSerializer.Serialize(raw);return new(rule.Code,Definitions[rule.Code].Name,rule.Weight,json,null,null,count,false,reason,json);}
    private static decimal Ratio(int numerator,int denominator)=>denominator==0?0:(decimal)numerator/denominator;private static decimal Get(ComponentRule rule,string name)=>GetOr(rule,name,0);private static decimal GetOr(ComponentRule rule,string name,decimal fallback)=>rule.Settings.TryGetValue(name,out var value)&&value.ValueKind==JsonValueKind.Number?value.GetDecimal():fallback;private static Dictionary<string,decimal> Map(ComponentRule rule,string name)=>rule.Settings.TryGetValue(name,out var value)&&value.ValueKind==JsonValueKind.Object?value.EnumerateObject().Where(x=>x.Value.ValueKind==JsonValueKind.Number).ToDictionary(x=>x.Name,x=>x.Value.GetDecimal()):[];
    private static string? GradeCode(decimal? score)=>score switch{null=>null,<60=>"SPROUT",<70=>"SAFE",<80=>"TRUSTED",<90=>"EXCELLENT",<=100=>"HONOR",_=>null};private static string Link(string code,Guid id)=>code switch{"EVIDENCE"=>$"/admin/providers/{id}","TRANSACTION"=>"/admin/transactions","REVIEW"=>"/admin/reviews","AFTER_SERVICE"=>"/admin/disputes","DISPUTE"=>"/admin/disputes","SANCTION"=>"/admin/sanctions",_=>"/admin/trust"};
    private async Task<TrustPolicy> PolicyAsync(Guid id,CancellationToken token)=>await db.TrustPolicies.SingleOrDefaultAsync(x=>x.PublicId==id,token)??throw Error("TRUST_POLICY_NOT_FOUND","정책을 찾을 수 없습니다.",404);private async Task<long> ActorAsync(Guid id,CancellationToken token)=>await(from user in db.Users.AsNoTracking()join link in db.UserRoles.AsNoTracking()on user.Id equals link.UserId join role in db.Roles.AsNoTracking()on link.RoleId equals role.Id where user.PublicId==id&&user.StatusCode=="ACTIVE"&&link.RevokedAt==null&&role.Code==RoleCodes.Admin select(long?)user.Id).SingleOrDefaultAsync(token)??throw Error("ADMIN_REQUIRED","관리자 계정을 확인할 수 없습니다.",401);private async Task<string> NameAsync(long id,CancellationToken token)=>await db.Users.AsNoTracking().Where(x=>x.Id==id).Select(x=>x.LoginId).SingleAsync(token);
    private async Task SavePolicyAndAudit(long actor,string action,Guid id,object? before,object? after,string reason,CancellationToken token,bool concurrency)
    {
        await using var transaction=db.Database.IsRelational()?await db.Database.BeginTransactionAsync(token):null;
        try
        {
            if(!db.Database.IsSqlServer())Audit(actor,action,id,before,after,reason);
            if(concurrency)await SaveConcurrency(token);else await db.SaveChangesAsync(token);
            if(db.Database.IsSqlServer())
            {
                var occurredAt=DateTime.UtcNow;var role=RoleCodes.Admin;var entityType="TRUST_POLICY";var result="SUCCESS";var beforeJson=before is null?null:JsonSerializer.Serialize(before);var afterJson=after is null?null:JsonSerializer.Serialize(after);
                await db.Database.ExecuteSqlInterpolatedAsync($"""INSERT INTO audit_logs (occurred_at,actor_user_id,actor_role_code,action_code,entity_type,entity_public_id,result_code,reason,before_json,after_json) VALUES ({occurredAt},{actor},{role},{action},{entityType},{id},{result},{reason},{beforeJson},{afterJson})""",token);
            }
            if(transaction is not null)await transaction.CommitAsync(token);
        }
        catch{if(transaction is not null)await transaction.RollbackAsync(token);throw;}
    }
    private void Audit(long actor,string action,Guid id,object? before,object? after,string reason,string entityType="TRUST_POLICY")=>db.AuditLogs.Add(new(){OccurredAt=DateTime.UtcNow,ActorUserId=actor,ActorRoleCode=RoleCodes.Admin,ActionCode=action,EntityType=entityType,EntityPublicId=id,ResultCode="SUCCESS",Reason=reason,BeforeJson=before is null?null:JsonSerializer.Serialize(before),AfterJson=after is null?null:JsonSerializer.Serialize(after)});private void SetVersion(TrustPolicy row,string? value){if(string.IsNullOrWhiteSpace(value))return;try{db.Entry(row).Property(x=>x.RowVersion).OriginalValue=Convert.FromBase64String(value);}catch(FormatException){throw Error("ROW_VERSION_INVALID","변경 버전 값이 올바르지 않습니다.");}}private async Task SaveConcurrency(CancellationToken token){try{await db.SaveChangesAsync(token);}catch(DbUpdateConcurrencyException){throw Error("CONCURRENT_UPDATE","다른 관리자가 먼저 변경했습니다.",409);}}private static TrustCalculationException Error(string code,string message,int status=400)=>new(code,message,status);
    internal sealed record PolicyRules(int MinimumCompletedTransactions,int MinimumVerifiedReviews,List<ComponentRule> Components);internal sealed record ComponentRule(string Code,decimal Weight,string RuleType,Dictionary<string,JsonElement> Settings);private sealed record ComponentValue(string Code,string Name,decimal Weight,string RawJson,decimal? NormalizedScore,decimal? WeightedScore,int SampleCount,bool IsCalculable,string? Reason,string SourceJson);private sealed record TransactionPerformance(int Completed,int ProviderFaultCancellations,int NeutralCancellations,int Evidence,int GeneralServiceCompleted,int EmergencyCompleted,int CareVisitCompleted,int InteriorCompleted);
}
