import { useCallback, useEffect, useState } from 'react'
import { CustomerAppLayout } from '../customer/CustomerAppLayout'
import { ProviderAppLayout } from '../providers/ProviderAppLayout'
import './reviewConversation.css'
import './communication.css'
import './communicationLayout.css'

export type ReviewComment = { id:string; parentCommentId:string|null; authorRole:string; authorDisplayName:string; bodyText:string; status:string; submittedAt:string; depth:number; rowVersion:string }
export type ReviewConversation = { reviewId:string; transactionId:string|null; sourceLabel:string; providerId:string; providerName:string; customerDisplayName:string; reviewBody:string; visibilityStatus:string; submittedAt:string; latestActivityAt:string; unreadCommentCount:number; comments:ReviewComment[] }
type Audience='customer'|'provider'
const date=(value:string)=>new Intl.DateTimeFormat('ko-KR',{dateStyle:'medium',timeStyle:'short'}).format(new Date(value))

async function request<T>(path:string,init?:RequestInit):Promise<T>{const response=await fetch(path,{credentials:'include',headers:init?.body?{'Content-Type':'application/json'}:undefined,...init});if(!response.ok){let message='리뷰 대화를 처리하지 못했습니다.';try{const value=await response.json() as{message?:string};if(value.message)message=value.message}catch{/* 공통 오류 */}throw new Error(message)}if(response.status===204)return undefined as T;return response.json() as Promise<T>}

function ReviewConversationBoard({audience}:{audience:Audience}) {
  const [items,setItems]=useState<ReviewConversation[]>([]); const [text,setText]=useState<Record<string,string>>({}); const [parents,setParents]=useState<Record<string,ReviewComment|null>>({}); const [busy,setBusy]=useState(''); const [error,setError]=useState('')
  const base=audience==='customer'?'/api/v1/customers/me':'/api/v1/providers/me'
  const load=useCallback(()=>request<ReviewConversation[]>(`${base}/review-conversations`).then(async value=>{setItems(value);await request(`${base}/review-conversations/read`,{method:'POST'});window.dispatchEvent(new CustomEvent('soodal-review-conversations-read'))}).catch(value=>setError(value instanceof Error?value.message:'리뷰 대화를 불러오지 못했습니다.')),[base])
  useEffect(()=>{void load()},[load])
  useEffect(()=>{if(!items.length)return;const id=new URLSearchParams(window.location.search).get('review');if(!id)return;requestAnimationFrame(()=>document.getElementById(`review-${id}`)?.scrollIntoView({behavior:'smooth',block:'start'}))},[items])
  const submit=async(review:ReviewConversation)=>{const body=text[review.reviewId]?.trim();if(!body)return;setBusy(review.reviewId);setError('');try{await request(`${base}/reviews/${review.reviewId}/comments`,{method:'POST',body:JSON.stringify({bodyText:body,parentCommentId:parents[review.reviewId]?.id??null,idempotencyKey:crypto.randomUUID()})});setText(current=>({...current,[review.reviewId]:''}));setParents(current=>({...current,[review.reviewId]:null}));await load()}catch(value){setError(value instanceof Error?value.message:'댓글을 등록하지 못했습니다.')}finally{setBusy('')}}
  return <>{error&&<div className="reviewConversationError">{error}</div>}<div className="reviewConversationList">{items.map(review=><article id={`review-${review.reviewId}`} className={`reviewConversationCard${review.unreadCommentCount?' hasUnread':''}`} key={review.reviewId}><header><div><span>{review.sourceLabel}{review.unreadCommentCount>0&&<b className="reviewUnreadBadge">새 댓글 {review.unreadCommentCount}</b>}</span><h2>{audience==='customer'?review.providerName:`${review.customerDisplayName} 고객 리뷰`}</h2></div><small>최근 소통 {date(review.latestActivityAt)} · {review.visibilityStatus==='PUBLIC'?'공개':'숨김'}</small></header><blockquote>{review.reviewBody}</blockquote><section className="reviewThread"><h3>댓글·답글 {review.comments.length}개</h3>{review.comments.map(comment=><div className={`reviewComment role-${comment.authorRole.toLowerCase()} status-${comment.status.toLowerCase()}`} style={{marginLeft:`${Math.min(comment.depth,5)*22}px`}} key={comment.id}><div><strong>{comment.authorDisplayName}<small>{comment.authorRole==='CUSTOMER'?'고객':'전문가'}</small></strong><time>{date(comment.submittedAt)}</time></div><p>{comment.bodyText}</p>{comment.status==='ACTIVE'&&review.visibilityStatus==='PUBLIC'&&<button type="button" onClick={()=>setParents(current=>({...current,[review.reviewId]:comment}))}>답글</button>}</div>)}{!review.comments.length&&<p className="reviewThreadEmpty">아직 댓글이 없습니다.</p>}</section>{review.visibilityStatus==='PUBLIC'?<div className="reviewCommentComposer">{parents[review.reviewId]&&<div><span>{parents[review.reviewId]?.authorDisplayName}님의 댓글에 답글 작성 중</span><button type="button" onClick={()=>setParents(current=>({...current,[review.reviewId]:null}))}>취소</button></div>}<textarea maxLength={2000} rows={3} value={text[review.reviewId]??''} onChange={event=>setText(current=>({...current,[review.reviewId]:event.target.value}))} placeholder={parents[review.reviewId]?'답글을 입력해 주세요.':'댓글을 입력해 주세요.'}/><small>댓글은 공개됩니다. 주소·연락처·일정 등 업무 정보는 채팅을 이용해 주세요.</small><button type="button" disabled={busy===review.reviewId||!text[review.reviewId]?.trim()} onClick={()=>void submit(review)}>{busy===review.reviewId?'등록 중…':parents[review.reviewId]?'답글 등록':'댓글 등록'}</button></div>:<p className="reviewThreadEmpty">숨김 처리된 리뷰에는 댓글을 작성할 수 없습니다.</p>}</article>)}{!items.length&&!error&&<p className="reviewThreadEmpty">작성된 리뷰가 없습니다.</p>}</div></>
}

export function CustomerReviewConversationPage(){return <CustomerAppLayout><div className="communicationPage"><CommunicationTabs audience="customer" active="reviews"/><section className="workHeading"><p>수달 소통</p><h1>내 리뷰·댓글</h1><span>작성한 리뷰에서 전문가와 공개 댓글·답글을 이어갈 수 있습니다.</span></section><ReviewConversationBoard audience="customer"/></div></CustomerAppLayout>}
export function ProviderReviewConversationPage(){return <ProviderAppLayout><div className="communicationPage"><CommunicationTabs audience="provider" active="reviews"/><section className="providerHero"><div><p>수달 소통</p><h1>고객 리뷰·답글</h1><span>내 서비스 리뷰에 답글을 남기고 고객의 후속 댓글에 다시 답변할 수 있습니다.</span></div></section><ReviewConversationBoard audience="provider"/></div></ProviderAppLayout>}
export function CommunicationTabs({audience,active}:{audience:Audience;active:'hub'|'chat'|'reviews'}){const root=audience==='customer'?'/customer':'/provider';return <nav className="communicationTabs" aria-label="소통 메뉴"><a className={active==='hub'?'active':''} aria-current={active==='hub'?'page':undefined} href={`${root}/communications`}>소통 홈</a><a className={active==='chat'?'active':''} aria-current={active==='chat'?'page':undefined} href={`${root}/messages`}>업무 채팅</a><a className={active==='reviews'?'active':''} aria-current={active==='reviews'?'page':undefined} href={`${root}/reviews`}>{audience==='customer'?'내 리뷰·댓글':'고객 리뷰·답글'}</a></nav>}
