import {useEffect,useMemo,useState} from 'react'
import {useAuthentication} from '../auth/AuthenticationContext'
import {navigate} from '../auth/routing'
import {useCallback} from 'react'
import {CustomerAppLayout} from '../customer/CustomerAppLayout'
import {ProviderAppLayout} from '../providers/ProviderAppLayout'
import {proposalApi,type ProposalApplication,type ProposalCampaign,type ProposalInterest,type ProposalServiceOption,type SaveProposal} from './proposalApi'
import {FriendShareButton} from '../components/FriendShareButton'
import './proposal.css'

const nowInput=(days=0)=>{const d=new Date(Date.now()+days*86400000);d.setMinutes(d.getMinutes()-d.getTimezoneOffset());return d.toISOString().slice(0,16)}
const initial=():SaveProposal=>({proposalTypeCode:'DISCOUNT_SERVICE',scopeCode:'LOCAL',serviceCategoryId:'',areaIds:[],title:'',summary:'',normalPriceAmount:null,offerPriceAmount:0,minimumParticipants:1,maximumParticipants:10,startAt:nowInput(),endAt:nowInput(7),serviceAt:null,cancellationPolicyText:'모집 완료 전 신청 취소가 가능합니다.',idempotencyKey:crypto.randomUUID()})
const money=(v:number|null)=>v===null?'-':new Intl.NumberFormat('ko-KR',{style:'currency',currency:'KRW',maximumFractionDigits:0}).format(v)
const digits=(value:string)=>value.replace(/\D/g,'').replace(/^0+(?=\d)/,'')
const formatted=(value:string)=>value?Number(value).toLocaleString('ko-KR'):''
const date=(v:string)=>new Intl.DateTimeFormat('ko-KR',{dateStyle:'medium',timeStyle:'short'}).format(new Date(v))
const status:Record<string,string>={PUBLISHED:'모집 중',MINIMUM_MET:'최소인원 달성',FULL:'모집 완료',EXPIRED:'종료',CANCELLED:'취소',APPLIED:'신청',CONFIRMED:'참여 확정',DECLINED:'미확정'}

export function ProviderProposalsPage(){
 const[services,setServices]=useState<ProposalServiceOption[]>([]),[items,setItems]=useState<ProposalCampaign[]>([]),[form,setForm]=useState(initial),[apps,setApps]=useState<Record<string,ProposalApplication[]>>({}),[error,setError]=useState(''),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[feePerParticipant,setFeePerParticipant]=useState(0),[walletBalance,setWalletBalance]=useState<number|null>(null),[normalPriceInput,setNormalPriceInput]=useState(''),[offerPriceInput,setOfferPriceInput]=useState(''),[minimumInput,setMinimumInput]=useState(''),[maximumInput,setMaximumInput]=useState('')
 const load=()=>Promise.all([proposalApi.setup(),proposalApi.providerList()]).then(([setup,list])=>{setServices(setup.services);setItems(list.items);setFeePerParticipant(setup.feePerConfirmedParticipant);setWalletBalance(setup.availableWalletBalance);setForm(v=>({...v,serviceCategoryId:v.serviceCategoryId||setup.services[0]?.id||''}))}).catch((e:Error)=>setError(e.message))
 useEffect(()=>{void load()},[])
 const selected=services.find(x=>x.id===form.serviceCategoryId),minimum=Number(minimumInput),maximum=Number(maximumInput),offerPrice=Number(offerPriceInput),normalPrice=normalPriceInput?Number(normalPriceInput):null,reserve=maximum*feePerParticipant,shortfall=walletBalance===null?0:Math.max(0,reserve-walletBalance),validNumbers=offerPrice>0&&minimum>=1&&maximum>=minimum&&maximum<=100&&(normalPrice===null||normalPrice>=offerPrice),duration=form.startAt&&form.endAt?new Date(form.endAt).getTime()-new Date(form.startAt).getTime():0,validDates=duration>=86400000&&duration<=2592000000,canAfford=walletBalance!==null&&shortfall===0
 const toggleArea=(id:string)=>setForm(v=>{const on=v.areaIds.includes(id);if(!on&&v.areaIds.length>=5){setError('지역 모집은 최대 5개 시·군·구까지 선택할 수 있습니다.');return v}return {...v,areaIds:on?v.areaIds.filter(x=>x!==id):[...v.areaIds,id]}})
 const submit=async()=>{if(!validNumbers||!validDates||!canAfford)return;setBusy(true);setError('');setMessage('');try{await proposalApi.create({...form,normalPriceAmount:normalPrice,offerPriceAmount:offerPrice,minimumParticipants:minimum,maximumParticipants:maximum,startAt:new Date(form.startAt).toISOString(),endAt:new Date(form.endAt).toISOString(),serviceAt:form.serviceAt?new Date(form.serviceAt).toISOString():null});setMessage(`${money(reserve)}이 예약되었습니다. 실제 수수료는 참여 확정 인원당 ${money(feePerParticipant)}만 차감됩니다.`);setForm({...initial(),serviceCategoryId:services[0]?.id||''});setNormalPriceInput('');setOfferPriceInput('');setMinimumInput('');setMaximumInput('');await load()}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 const loadApps=async(id:string)=>{const result=await proposalApi.applications(id);setApps(v=>({...v,[id]:result.items}))}
 const decide=async(id:string,applicationId:string,action:'confirm'|'decline')=>{setBusy(true);try{await proposalApi[action](id,applicationId);await Promise.all([load(),loadApps(id)])}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 return <ProviderAppLayout><div className="proposalPage"><header className="proposalHero"><p>EXPERT OFFER</p><h1>전문가 제안·공동모집</h1><span>고객 요청을 기다리지 않고 승인받은 서비스로 할인·공동구매·그룹 레슨을 직접 모집하세요.</span></header>{error&&<div className="proposalError">{error}</div>}{message&&<div className="proposalSuccess">{message}</div>}
 <section className="proposalPanel"><h2>새 모집 등록</h2><div className="proposalPolicy"><b>수수료 예약 {maximum>0?money(reserve):'정원을 입력해 주세요'}</b><span>{maximum>0?`정원 ${maximum}명 × ${money(feePerParticipant)}`:'인원을 입력하면 필요한 예약금을 미리 계산합니다.'} · 확정 인원만 차감 · 미사용 예약금 자동 해제</span></div><div className="proposalForm">
 <label>모집 유형<select value={form.proposalTypeCode} onChange={e=>setForm(v=>({...v,proposalTypeCode:e.target.value}))}><option value="DISCOUNT_SERVICE">할인 서비스</option><option value="GROUP_BUY">공동구매</option><option value="GROUP_LESSON">그룹 레슨</option></select></label>
 <label>모집 범위<select value={form.scopeCode} onChange={e=>setForm(v=>({...v,scopeCode:e.target.value,areaIds:[]}))}><option value="LOCAL">지역 모집</option><option value="NATIONWIDE">전국 모집</option></select></label>
 <label className="wide">승인 서비스<select value={form.serviceCategoryId} onChange={e=>setForm(v=>({...v,serviceCategoryId:e.target.value,areaIds:[]}))}>{services.map(x=><option value={x.id} key={x.id}>{x.categoryPath}{x.isNationwide?' · 전국 가능':''}</option>)}</select></label>
 <label className="wide">제목<input maxLength={200} value={form.title} onChange={e=>setForm(v=>({...v,title:e.target.value}))}/></label><label className="wide">상세 설명<textarea maxLength={3000} value={form.summary} onChange={e=>setForm(v=>({...v,summary:e.target.value}))}/></label>
 <label>정상가<input type="text" inputMode="numeric" placeholder="예: 100,000" value={formatted(normalPriceInput)} onChange={e=>setNormalPriceInput(digits(e.target.value))}/></label><label>제안가<input type="text" inputMode="numeric" placeholder="예: 80,000" value={formatted(offerPriceInput)} onChange={e=>setOfferPriceInput(digits(e.target.value))}/></label>
 <label>최소 인원<input type="text" inputMode="numeric" placeholder="예: 5" value={formatted(minimumInput)} onChange={e=>setMinimumInput(digits(e.target.value).slice(0,3))}/></label><label>모집 정원<input type="text" inputMode="numeric" placeholder="예: 10" value={formatted(maximumInput)} onChange={e=>setMaximumInput(digits(e.target.value).slice(0,3))}/></label>
 <label>모집 시작<input type="datetime-local" value={form.startAt} onChange={e=>setForm(v=>({...v,startAt:e.target.value}))}/></label><label>모집 마감<input type="datetime-local" value={form.endAt} onChange={e=>setForm(v=>({...v,endAt:e.target.value}))}/></label>
 <label className="wide">취소 조건<textarea value={form.cancellationPolicyText} onChange={e=>setForm(v=>({...v,cancellationPolicyText:e.target.value}))}/></label></div>
 {form.scopeCode==='NATIONWIDE'?<div className="proposalNotice">전국 모집은 해당 서비스가 전국·원격 가능으로 승인된 경우에만 등록됩니다. 프로그램 피드·WEB·PUSH만 사용하며 SMS는 보내지 않습니다.</div>:<div className="proposalAreas"><strong>모집 지역 · 최대 5개</strong>{selected?.areas.length?<div>{selected.areas.map(a=><label key={a.id}><input type="checkbox" checked={form.areaIds.includes(a.id)} onChange={()=>toggleArea(a.id)}/>{a.parentName} {a.name}</label>)}</div>:<p>먼저 이 서비스의 활동지역을 저장해 주세요.</p>}</div>}
 <section className={`proposalWalletCheck${canAfford?' ready':' warning'}`} aria-live="polite"><div><span>사용 가능 충전금</span><b>{walletBalance===null?'확인 중':money(walletBalance)}</b></div><div><span>필요 예약금</span><b>{maximum>0?money(reserve):'-'}</b></div>{maximum>0&&shortfall>0?<p role="alert">충전금이 {money(shortfall)} 부족합니다. 충전 후 등록할 수 있습니다. <button type="button" onClick={()=>navigate(`/provider/wallet?returnUrl=${encodeURIComponent('/provider/proposals')}&expectedFee=${reserve}&shortfall=${shortfall}`)}>충전금 관리</button></p>:maximum>0&&canAfford?<p>등록 가능한 잔액입니다.</p>:<p>정원을 입력하면 잔액을 미리 확인합니다.</p>}</section>
 {!validNumbers&&(offerPriceInput||minimumInput||maximumInput)&&<p className="proposalInlineError" role="alert">제안가는 1원 이상, 인원은 1~100명으로 입력하고 최소 인원이 정원을 넘지 않게 해 주세요. 정상가는 제안가보다 작을 수 없습니다.</p>}{!validDates&&<p className="proposalInlineError" role="alert">모집 기간은 1일 이상 30일 이내로 설정해 주세요.</p>}
 <button className="proposalPrimary" disabled={busy||!form.title||!form.summary||!form.serviceCategoryId||!validNumbers||!validDates||!canAfford||(form.scopeCode==='LOCAL'&&!form.areaIds.length)||(form.scopeCode==='NATIONWIDE'&&!selected?.isNationwide)} onClick={()=>void submit()}>{busy?'등록 중':'모집 등록·수수료 예약'}</button></section>
 <section className="proposalPanel"><h2>내 모집 현황</h2><div className="proposalCards">{items.map(x=><article key={x.id}><CampaignSummary value={x}/><div className="proposalActions"><button onClick={()=>void loadApps(x.id)}>신청자 보기</button>{['PUBLISHED','MINIMUM_MET','FULL'].includes(x.statusCode)&&<button className="danger" onClick={()=>confirm('모집을 취소하면 확정 수수료를 포함해 예약금이 복원됩니다. 취소할까요?')&&void proposalApi.cancelCampaign(x.id).then(load)}>모집 취소</button>}</div>{apps[x.id]&&<div className="proposalApplicants">{apps[x.id].map(a=><div key={a.id}><span>{a.customerName} · {status[a.statusCode]??a.statusCode}</span>{a.statusCode==='APPLIED'&&<><button disabled={busy} onClick={()=>void decide(x.id,a.id,'confirm')}>참여 확정</button><button disabled={busy} onClick={()=>void decide(x.id,a.id,'decline')}>미확정</button></>}</div>)}{!apps[x.id].length&&<p>신청자가 없습니다.</p>}</div>}</article>)}{!items.length&&<p>등록한 모집이 없습니다.</p>}</div></section></div></ProviderAppLayout>
}

export function CustomerProposalsPage({id}:{id?:string}){
 const{status:authStatus,user}=useAuthentication();const[items,setItems]=useState<ProposalCampaign[]>([]),[detail,setDetail]=useState<ProposalCampaign|null>(null),[interests,setInterests]=useState<ProposalInterest>({categoryIds:[],areaIds:[]}),[areas,setAreas]=useState<{id:string;name:string;parentId:string|null;parentName?:string|null}[]>([]),[sidos,setSidos]=useState<{id:string;name:string}[]>([]),[selectedSidoId,setSelectedSidoId]=useState(''),[draftAreaId,setDraftAreaId]=useState(''),[error,setError]=useState(''),[message,setMessage]=useState('')
 const load=useCallback(()=>id?proposalApi.detail(id).then(setDetail):proposalApi.publicList().then(x=>setItems(x.items)),[id]);useEffect(()=>{void load().catch((e:Error)=>setError(e.message));Promise.all([fetch('/api/v1/administrative-areas/sidos',{credentials:'include'}),fetch('/api/v1/administrative-areas/sigungu',{credentials:'include'})]).then(async([sidoResponse,areaResponse])=>[sidoResponse.ok?await sidoResponse.json():[],areaResponse.ok?await areaResponse.json():[]] as const).then(([nextSidos,nextAreas])=>{setSidos(nextSidos);setAreas(nextAreas)}).catch(()=>{setSidos([]);setAreas([])})},[load]);useEffect(()=>{if(authStatus==='authenticated'&&user?.roles.includes('CUSTOMER'))void proposalApi.interests().then(setInterests)},[authStatus,user]);useEffect(()=>{const saved=areas.find(area=>area.id===(interests.areaIds[0]??''));if(saved){setSelectedSidoId(saved.parentId??'');setDraftAreaId(saved.id)}else if(!interests.areaIds.length){setDraftAreaId('')}},[areas,interests.areaIds])
 const visible=useMemo(()=>detail?[detail]:items,[detail,items]);const categories=useMemo(()=>Array.from(new Map(visible.map(x=>[x.serviceCategoryId,{id:x.serviceCategoryId,name:x.serviceName}])).values()),[visible]);const filteredAreas=useMemo(()=>areas.filter(area=>area.parentId===selectedSidoId),[areas,selectedSidoId])
 const save=(next:ProposalInterest,success:string)=>proposalApi.saveInterests(next).then(value=>{setInterests(value);setMessage(success)}).catch((e:Error)=>setError(e.message))
 const apply=async(x:ProposalCampaign)=>{if(authStatus!=='authenticated'||!user?.roles.includes('CUSTOMER')){navigate(`/login?returnUrl=${encodeURIComponent(`/proposals/${x.id}`)}`);return}try{await proposalApi.apply(x.id);setMessage('참여 신청을 보냈습니다. 전문가가 확정하면 알림으로 안내합니다.');await load()}catch(e){setError((e as Error).message)}}
 return <CustomerAppLayout><div className="proposalPage customer"><header className="proposalHero"><p>SOODAL TOGETHER</p><h1>전문가 제안·공동모집</h1><span>우리 동네 할인 서비스와 전국 공동구매·그룹 레슨을 확인해 보세요.</span></header>{error&&<div className="proposalError">{error}</div>}{message&&<div className="proposalSuccess">{message}</div>}
 {!id&&<section id="my-neighborhood" className="proposalPanel proposalPreferences"><div><h2>우리 동네·관심 서비스</h2><p>필수 입력이 아닙니다. 시·도를 먼저 고른 뒤 시·군·구를 저장해 주세요. 저장 주소와 요청 이력도 시·군·구 단위로 추천에 활용합니다.</p></div>{authStatus==='authenticated'&&user?.roles.includes('CUSTOMER')?<><div className="proposalAreaSelectors"><label>시·도<select value={selectedSidoId} onChange={e=>{setSelectedSidoId(e.target.value);setDraftAreaId('');setMessage('')}}><option value="">시·도 선택</option>{sidos.map(area=><option value={area.id} key={area.id}>{area.name}</option>)}</select></label><label>시·군·구<select value={draftAreaId} disabled={!selectedSidoId} onChange={e=>setDraftAreaId(e.target.value)}><option value="">{selectedSidoId?'시·군·구 선택':'시·도를 먼저 선택'}</option>{filteredAreas.map(area=><option value={area.id} key={area.id}>{area.name}</option>)}</select></label><button type="button" className="proposalPrimary" disabled={!draftAreaId} onClick={()=>void save({...interests,areaIds:[draftAreaId]},'우리 동네를 저장했습니다.')}>우리 동네로 저장</button>{interests.areaIds.length>0&&<button type="button" className="proposalAreaClear" onClick={()=>{setSelectedSidoId('');setDraftAreaId('');void save({...interests,areaIds:[]},'우리 동네 설정을 해제했습니다.')}}>설정 해제</button>}</div><div className="proposalInterestButtons">{categories.map(c=><button className={interests.categoryIds.includes(c.id)?'selected':''} key={c.id} onClick={()=>{const on=interests.categoryIds.includes(c.id);void save({...interests,categoryIds:on?interests.categoryIds.filter(x=>x!==c.id):[...interests.categoryIds,c.id]},on?'관심 서비스를 해제했습니다.':'관심 서비스로 저장했습니다.')}}>{c.name}</button>)}</div></>:<button className="proposalPrimary" onClick={()=>navigate('/login?returnUrl=%2Fproposals')}>로그인하고 우리 동네 설정</button>}</section>}
 {id&&<button className="proposalBack" onClick={()=>navigate('/proposals')}>← 모집 목록</button>}<section className="proposalCards public">{visible.map(x=><article key={x.id}><CampaignSummary value={x}/><p className="proposalBody">{x.summary}</p><div className="proposalActions"><button onClick={()=>navigate(`/providers/${x.providerId}`)}>전문가 보기</button>{!id&&<button onClick={()=>navigate(`/proposals/${x.id}`)}>자세히</button>}{id&&<FriendShareButton className="proposalShareButton" label="친구에게 참여 추천" title={x.title} text={`${x.providerName} 전문가의 ${x.title} 모집에 함께 참여해 보세요.`} url={`https://soodallife.kr/proposals/${x.id}`} />}{id&&x.canApply&&x.myApplicationStatus!=='APPLIED'&&x.myApplicationStatus!=='CONFIRMED'&&<button className="proposalPrimary" onClick={()=>void apply(x)}>참여 신청</button>}</div>{id&&<div className="proposalTerms"><b>취소·진행 조건</b><p>{x.cancellationPolicyText}</p></div>}</article>)}{!visible.length&&<p>현재 진행 중인 제안·공동모집이 없습니다.</p>}</section></div></CustomerAppLayout>
}

function CampaignSummary({value:x}:{value:ProposalCampaign}){return <><div className="proposalCardTop"><span>{x.scopeCode==='NATIONWIDE'?'전국 모집':x.areas.map(a=>a.name).join(' · ')}</span><b>{status[x.statusCode]??x.statusCode}</b></div><h3>{x.title}</h3><p>{x.categoryPath} · {x.providerName}</p><div className="proposalPrice">{x.normalPriceAmount!==null&&<del>{money(x.normalPriceAmount)}</del>}<strong>{money(x.offerPriceAmount)}</strong></div><div className="proposalProgress"><span style={{width:`${Math.min(100,x.confirmedParticipants/x.maximumParticipants*100)}%`}}/><b>{x.confirmedParticipants}/{x.maximumParticipants}명 · 마감 {date(x.endAt)}</b></div></>}
