using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable
namespace SoodalLife.Api.Infrastructure.Persistence.Migrations;

[DbContext(typeof(SoodalLifeDbContext))]
[Migration("20260820150000_CompleteAdminOperationsV116")]
public sealed class CompleteAdminOperationsV116:Migration
{
    protected override void Up(MigrationBuilder migrationBuilder)=>migrationBuilder.Sql(Sql);
    protected override void Down(MigrationBuilder migrationBuilder){ }
    internal const string Sql="""
IF OBJECT_ID('admin_security_profiles','U') IS NULL BEGIN CREATE TABLE admin_security_profiles(id bigint IDENTITY PRIMARY KEY,public_id uniqueidentifier NOT NULL UNIQUE,user_id bigint NOT NULL UNIQUE,detail_role_code varchar(40) NOT NULL,mfa_enabled bit NOT NULL DEFAULT 0,totp_secret_protected nvarchar(2000) NULL,mfa_confirmed_at datetime2 NULL,failed_mfa_attempts int NOT NULL DEFAULT 0,locked_until datetime2 NULL,created_at datetime2 NOT NULL DEFAULT SYSUTCDATETIME(),created_by_user_id bigint NULL,updated_at datetime2 NOT NULL DEFAULT SYSUTCDATETIME(),updated_by_user_id bigint NULL,row_version rowversion NOT NULL,CONSTRAINT FK_admin_security_profiles_user FOREIGN KEY(user_id) REFERENCES users(id)); END;
IF OBJECT_ID('admin_reauthentication_sessions','U') IS NULL BEGIN CREATE TABLE admin_reauthentication_sessions(id bigint IDENTITY PRIMARY KEY,public_id uniqueidentifier NOT NULL UNIQUE,user_id bigint NOT NULL,token_hash binary(32) NOT NULL UNIQUE,created_at datetime2 NOT NULL DEFAULT SYSUTCDATETIME(),expires_at datetime2 NOT NULL,revoked_at datetime2 NULL,purpose_code varchar(50) NOT NULL,CONSTRAINT FK_admin_reauth_user FOREIGN KEY(user_id) REFERENCES users(id));CREATE INDEX IX_admin_reauth_user_expiry ON admin_reauthentication_sessions(user_id,expires_at);END;
IF OBJECT_ID('outbox_retry_requests','U') IS NULL BEGIN CREATE TABLE outbox_retry_requests(id bigint IDENTITY PRIMARY KEY,public_id uniqueidentifier NOT NULL UNIQUE,outbox_event_id bigint NOT NULL,attempt_snapshot int NOT NULL,idempotency_key varchar(160) NOT NULL UNIQUE,reason nvarchar(1000) NOT NULL,status_code varchar(20) NOT NULL,requested_by_user_id bigint NOT NULL,requested_at datetime2 NOT NULL DEFAULT SYSUTCDATETIME(),consumed_at datetime2 NULL,CONSTRAINT FK_outbox_retry_event FOREIGN KEY(outbox_event_id) REFERENCES outbox_events(id),CONSTRAINT FK_outbox_retry_user FOREIGN KEY(requested_by_user_id) REFERENCES users(id),CONSTRAINT UQ_outbox_retry_attempt UNIQUE(outbox_event_id,attempt_snapshot));END;
IF OBJECT_ID('data_retention_policies','U') IS NULL BEGIN CREATE TABLE data_retention_policies(id bigint IDENTITY PRIMARY KEY,public_id uniqueidentifier NOT NULL UNIQUE,domain_code varchar(50) NOT NULL UNIQUE,action_code varchar(20) NOT NULL,retention_days int NOT NULL,legal_hold_days int NOT NULL,is_enabled bit NOT NULL DEFAULT 0,dry_run bit NOT NULL DEFAULT 1,created_at datetime2 NOT NULL DEFAULT SYSUTCDATETIME(),created_by_user_id bigint NULL,updated_at datetime2 NOT NULL DEFAULT SYSUTCDATETIME(),updated_by_user_id bigint NULL,row_version rowversion NOT NULL);END;
IF OBJECT_ID('data_retention_executions','U') IS NULL BEGIN CREATE TABLE data_retention_executions(id bigint IDENTITY PRIMARY KEY,public_id uniqueidentifier NOT NULL UNIQUE,policy_id bigint NOT NULL,status_code varchar(20) NOT NULL,dry_run bit NOT NULL,candidate_count int NOT NULL,processed_count int NOT NULL,skipped_legal_hold_count int NOT NULL,error_code varchar(100) NULL,started_at datetime2 NOT NULL DEFAULT SYSUTCDATETIME(),completed_at datetime2 NULL,executed_by_user_id bigint NULL,CONSTRAINT FK_retention_execution_policy FOREIGN KEY(policy_id) REFERENCES data_retention_policies(id));CREATE INDEX IX_retention_execution_policy_started ON data_retention_executions(policy_id,started_at DESC);END;
IF OBJECT_ID('analytics_events','U') IS NULL BEGIN CREATE TABLE analytics_events(id bigint IDENTITY PRIMARY KEY,public_id uniqueidentifier NOT NULL UNIQUE,event_type_code varchar(80) NOT NULL,visitor_id uniqueidentifier NOT NULL,user_id bigint NULL,provider_public_id uniqueidentifier NULL,source_public_id uniqueidentifier NULL,source_type_code varchar(60) NULL,route_template varchar(300) NULL,http_method varchar(10) NULL,status_code int NULL,duration_ms int NULL,outcome_code varchar(50) NULL,occurred_at datetime2 NOT NULL DEFAULT SYSUTCDATETIME(),metadata_json nvarchar(max) NULL,CONSTRAINT FK_analytics_event_user FOREIGN KEY(user_id) REFERENCES users(id),CONSTRAINT CK_analytics_metadata CHECK(metadata_json IS NULL OR ISJSON(metadata_json)=1));CREATE INDEX IX_analytics_event_type_time ON analytics_events(event_type_code,occurred_at);CREATE INDEX IX_analytics_visitor_time ON analytics_events(visitor_id,occurred_at);END;
INSERT INTO admin_security_profiles(public_id,user_id,detail_role_code,mfa_enabled,failed_mfa_attempts,created_at,updated_at)
SELECT NEWID(),u.id,'SUPER_ADMIN',0,0,SYSUTCDATETIME(),SYSUTCDATETIME() FROM users u JOIN user_roles ur ON ur.user_id=u.id AND ur.revoked_at IS NULL JOIN roles r ON r.id=ur.role_id AND r.code='ADMIN' WHERE NOT EXISTS(SELECT 1 FROM admin_security_profiles p WHERE p.user_id=u.id);
DECLARE @retention TABLE(domain_code varchar(50),action_code varchar(20),retention_days int,legal_hold_days int);
INSERT @retention VALUES('PASSWORD_RESET','DELETE',90,0),('ADMIN_SESSION','DELETE',30,0),('ANALYTICS_EVENT','DELETE',730,0),('PERSONAL_DATA','ANONYMIZE',1825,365);
INSERT INTO data_retention_policies(public_id,domain_code,action_code,retention_days,legal_hold_days,is_enabled,dry_run,created_at,updated_at)
SELECT NEWID(),s.domain_code,s.action_code,s.retention_days,s.legal_hold_days,0,1,SYSUTCDATETIME(),SYSUTCDATETIME() FROM @retention s WHERE NOT EXISTS(SELECT 1 FROM data_retention_policies p WHERE p.domain_code=s.domain_code);
""";
}
