[CmdletBinding(SupportsShouldProcess=$true,ConfirmImpact='High')]
param([string]$ZipPath=(Join-Path $PSScriptRoot 'SoodalLife-ProviderMobileNavigationWallet-20260831-v174.zip'),[string]$ReleaseBasePath='D:\SOODALLIFE\releases',[string]$AppsRoot='D:\SOODALLIFE\apps',[switch]$ConfirmProductionDeployment)
$ErrorActionPreference='Stop';$expectedSha256='4bc690bc12c9d02a6308afe7b276db2161b720a071ebccda14bdbd07a778e2ef'
if(-not $ConfirmProductionDeployment){throw 'Safety stop: add -ConfirmProductionDeployment only after checking the ZIP hash and target paths.'}
$identity=[Security.Principal.WindowsIdentity]::GetCurrent();$principal=[Security.Principal.WindowsPrincipal]::new($identity);if(-not $principal.IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)){throw 'Run PowerShell as Administrator and try again.'}
if(-not(Test-Path -LiteralPath $ZipPath -PathType Leaf)){throw "Deployment ZIP not found: $ZipPath"};$actual=(Get-FileHash -LiteralPath $ZipPath -Algorithm SHA256).Hash;if($actual-ne$expectedSha256){throw "ZIP SHA-256 mismatch. Expected=$expectedSha256, Actual=$actual"}
if(-not(Test-Path -LiteralPath $ReleaseBasePath)){New-Item -ItemType Directory -Path $ReleaseBasePath|Out-Null};$stamp=Get-Date -Format 'yyyyMMdd-HHmmss';$extractPath=Join-Path $ReleaseBasePath "provider-mobile-navigation-wallet-v174-$stamp";New-Item -ItemType Directory -Path $extractPath|Out-Null
Write-Host '1/4 ZIP integrity check passed.' -ForegroundColor Green;Expand-Archive -LiteralPath $ZipPath -DestinationPath $extractPath -ErrorAction Stop;$release=Join-Path $extractPath 'provider-mobile-navigation-wallet-v174-final'
$required=@('frontend\partner\index.html','frontend\partner\sw.js','frontend\partner\web.config','Publish-Production.ps1','README.txt','RELEASE-MANIFEST.txt');foreach($relative in $required){if(-not(Test-Path -LiteralPath (Join-Path $release $relative) -PathType Leaf)){throw "Required V174 release file is missing: $relative"}}
if(Test-Path -LiteralPath (Join-Path $release 'api')){throw 'V174 frontend-only package unexpectedly contains an API directory.'}
$js=Get-ChildItem -LiteralPath (Join-Path $release 'frontend\partner\assets') -Filter 'index-*.js' -File;$css=Get-ChildItem -LiteralPath (Join-Path $release 'frontend\partner\assets') -Filter 'index-*.css' -File;if($js.Count-ne 1-or$css.Count-ne 1){throw 'V174 partner bundle count is invalid.'};$jsText=[IO.File]::ReadAllText($js[0].FullName,[Text.Encoding]::UTF8);$cssText=[IO.File]::ReadAllText($css[0].FullName,[Text.Encoding]::UTF8);foreach($marker in @('providerBottomNavIcon','providerBrandMobileWallet','providerBottomNavLabel')){if(-not$jsText.Contains($marker)-or-not$cssText.Contains($marker)){throw "V174 marker missing: $marker"}}
Write-Host "2/4 Extracted V174 deployment validated: $release" -ForegroundColor Green
if(-not $PSCmdlet.ShouldProcess("partner app at $AppsRoot",'Deploy V174 provider mobile navigation and wallet header')){return}
Write-Host '3/4 Running protected partner frontend backup followed by IIS deployment.' -ForegroundColor Yellow;& (Join-Path $release 'Publish-Production.ps1') -ConfirmProductionDeployment -AppsRoot $AppsRoot -BackupParent $ReleaseBasePath -Confirm:$false;if(-not $?){throw 'V174 protected deployment script failed.'}
Write-Host '4/4 V174 provider mobile navigation and wallet header deployment completed.' -ForegroundColor Green;Write-Host 'API, database schema/data and production settings were not changed.' -ForegroundColor Yellow;Write-Host "Extracted release path: $release"
