export interface WorkTransactionListItem { id: string; categoryPath: string; areaName: string; requestSummary: string; agreedAmount: number; currencyCode: string; status: string; createdAt: string; displayStatus: string; statusGroup: string }
export interface WorkQuoteItem { lineNo: number; itemName: string; description: string | null; quantity: number; unitText: string | null; unitPriceAmount: number; lineTotalAmount: number }
export interface WorkRequestAnswer { label: string; value: unknown; isMasked: boolean }
export interface PhotoRequirementStatus { roleCode: string; roleName: string; requiredCount: number; uploadedCount: number; isSatisfied: boolean }
export interface CompletionPolicyStatus { policyVersion: string; requiredPhotoCount: number; uploadedPhotoCount: number; totalSatisfied: boolean; roles: PhotoRequirementStatus[]; isSatisfied: boolean }
export interface PhotoRoleOption { code: string; name: string; description: string | null }
export interface CompletionEvidence { fileId: string; originalFileName: string; contentType: string; sizeBytes: number; roleCode: string; roleName: string; displayOrder: number; description: string | null; downloadUrl: string|null; publicationStatus:string; publicationMessage:string|null }
export interface WorkCompletionRevision { id: string; revisionNo: number; status: string; workSummary: string; actualAmount: number; currencyCode: string; providerAttestationAt: string; recordedAt: string; revisionReason: string | null; evidence: CompletionEvidence[]; policy: CompletionPolicyStatus }
export interface WorkTimelineItem { code: string; label: string; occurredAt: string; isCurrent: boolean }
export interface WorkRelatedCase { id: string; status: string; displayStatus: string; createdAt: string }
export interface WorkReviewState { id: string | null; canCreate: boolean; exists: boolean; status: string | null }
export interface WorkTransactionDetail extends WorkTransactionListItem { requestTitle: string; requestDescription: string | null; customerPhone: string | null; detailAddress: string | null; providerName: string; startedAt: string | null; completedAt: string | null; quoteItems: WorkQuoteItem[]; requestAnswers: WorkRequestAnswer[]; completionPolicy: CompletionPolicyStatus; availablePhotoRoles: PhotoRoleOption[]; completion: WorkCompletionRevision | null; completionRevisions: WorkCompletionRevision[]; timeline: WorkTimelineItem[]; afterService: WorkRelatedCase | null; dispute: WorkRelatedCase | null; review: WorkReviewState; providerFee?: { feeChargeId:string; feeAmount:number; chargedAt:string; restoreStatusCode:string } }
export interface CompletionConfirmation { confirmationId: string; transactionId: string; completionRevisionId: string; result: string; transactionStatus: string; serviceHistoryId: string | null }
export interface DirectPaymentEvidence { fileId:string|null;fileName:string;contentType:string;sizeBytes:number;downloadUrl:string|null;publicationStatus:string;publicationMessage:string|null }
export interface TransactionDirectPayment { id:string;status:'REGISTERED'|'COUNTERPART_CONFIRMED'|'REJECTED';amount:number;currencyCode:string;paymentMethod:string;paidAt:string;note:string|null;registeredByRole:string;registeredAt:string;decidedAt:string|null;rejectionReason:string|null;canDecide:boolean;rowVersion:string;evidence:DirectPaymentEvidence|null }
export interface DirectPaymentContext { agreedAmount:number;currencyCode:string;transactionStatus:string;transactionRowVersion:string;payment:TransactionDirectPayment|null }
export interface AppointmentChange { id: string; changeType: 'RESCHEDULE'|'CANCEL'; requestedStartAt: string | null; requestedEndAt: string | null; reason: string; status: string; requestedAt: string; processedAt: string | null; rowVersion: string }
export interface AppointmentEvent { id:string;eventType:string;beforeStatus:string|null;afterStatus:string;beforeStartAt:string|null;beforeEndAt:string|null;afterStartAt:string|null;afterEndAt:string|null;reason:string|null;occurredAt:string }
export interface TransactionAppointment { id: string; transactionId: string; scheduledStartAt: string; scheduledEndAt: string | null; estimatedDurationMinutes: number | null; customerMemo: string | null; providerMemo: string | null; status: string; isConfirmed: boolean; confirmedAt: string | null; cancelledAt: string | null; canRespond:boolean; rowVersion:string; changes: AppointmentChange[];events:AppointmentEvent[] }
export interface TransactionCancellation { id:string;transactionId:string;reason:string;status:string;requestedAt:string;processedAt:string|null;feeRestoreStatus:'NOT_EVALUATED';canRespond:boolean;rowVersion:string }
export interface RatingItem { id: string; code: string; name: string; description: string | null; minValue: number; maxValue: number; isRequired: boolean; displayOrder: number }
export interface ReviewResponse { id: string; transactionId: string; providerName: string; bodyText: string; visibilityStatusCode: string; submittedAt: string; ratings: Array<{itemId:string;itemName:string;ratingValue:number;minValue:number;maxValue:number}>; files: Array<{fileId:string;fileName:string;contentType:string;downloadUrl:string|null;publicationMode:string|null}> }
export interface CustomerDispute { id:string;transactionId:string|null;interiorProjectId:string|null;subject:string;reason:string;requestedResolution:string;status:string;displayStatus:string;receivedAt:string;resolvedAt:string|null;resultSummary:string|null;followUpAction:string|null;evidence:Array<{id:string;fileId:string|null;sourceType:string;description:string|null;submittedAt:string;downloadUrl:string|null;publicationStatus:string;publicationMessage:string|null}>;publicUpdates:Array<{displayStatus:string;occurredAt:string}> }
export interface ServiceHistoryItem { id:string;transactionId:string;serviceName:string;categoryName:string|null;providerName:string;completedAt:string|null;finalAmount:number|null;currencyCode:string|null;warrantyEndDate:string|null;warrantyDisplay:string;hasAfterService:boolean;hasReview:boolean;hasDispute:boolean }
export interface ServiceHistoryDetail extends ServiceHistoryItem { title:string;summary:string;warrantyStartDate:string|null;items:Array<{lineNo:number;itemName:string;description:string|null;quantity:number|null;unitText:string|null;amount:number|null;currencyCode:string|null}>;completionEvidence:Array<{fileId:string;fileName:string;contentType:string;role:string;description:string|null;downloadUrl:string|null;publicationStatus:string;publicationMessage:string|null}>;assets:Array<{id:string;type:string;name:string;manufacturer:string|null;modelName:string|null}>;afterService:WorkRelatedCase|null;dispute:WorkRelatedCase|null;review:WorkReviewState }
export interface CustomerAfterService { id:string;transactionId:string|null;interiorProjectId:string|null;serviceHistoryId:string|null;subject:string;description:string;requestDetails:string|null;status:string;displayStatus:string;receivedAt:string;warrantyStartDate:string|null;warrantyEndDate:string|null;isWithinWarranty:boolean|null;warrantyDisplay:string;dueAt:string|null;providerConfirmedAt:string|null;providerResponse:string|null;visitRequired:boolean|null;startedAt:string|null;completedAt:string|null;resolutionSummary:string|null;unresolvedReason:string|null;recurrenceOccurred:boolean|null;disputeId:string|null;timeline:Array<{status:string;displayStatus:string;actionType:string;publicNote:string|null;scheduledAt:string|null;performedAt:string|null;occurredAt:string}>;evidence:Array<{fileId:string;fileName:string;contentType:string;sizeBytes:number;role:string|null;description:string|null;downloadUrl:string|null;publicationStatus:string;publicationMessage:string|null}> }
export interface CustomerReportType { id:string;code:string;name:string;description:string|null }
export interface CustomerReport { id:string;reportNumber:string;reportTypeId:string;reportTypeCode:string;reportTypeName:string;targetType:string;targetId:string;targetDisplay:string;description:string;status:string;displayStatus:string;receivedAt:string;resolvedAt:string|null;publicResult:string|null;evidence:Array<{fileId:string;fileName:string;contentType:string;sizeBytes:number;description:string|null;downloadUrl:string}> }
