import { useEffect,useMemo,useState } from 'react'
import type { FormEvent,ReactNode } from 'react'
import { AdminLayout } from './AdminLayout'
import { AdminSubscriptionAccountingPanel } from './AdminSubscriptionAccountingPanel'
import { createCareProduct,decideSubscriptionScheduleChange,getCareProducts,getSubscriptionApplications,getSubscriptionContracts,getSubscriptionRequests,getSubscriptionScheduleChanges,getSubscriptionServices,getSubscriptionVisits } from './subscriptionApi'
import type { CareProduct,SubscriptionApplication,SubscriptionContract,SubscriptionRequest,SubscriptionScheduleChange,SubscriptionService,SubscriptionVisit } from './subscriptionTypes'

const tabs=['운영 현황','구독 상품','구독 요청·전문가 신청','계약 관리','회차·일정 관리','결제·정산'] as const
const labels:Record<string,string>={ACTIVE:'이용 중',PAUSED:'일시정지',PAYMENT_PENDING:'첫 결제 대기',TERMINATION_REQUESTED:'해지 처리 중',TERMINATED:'해지',OPEN:'요청 접수',CONTRACTED:'계약 완료',CANCELLED:'취소',SCHEDULED:'방문 예정',RESCHEDULED:'일정 변경',IN_PROGRESS:'작업 중',SKIPPED:'건너뜀',PROVIDER_COMPLETED:'전문가 완료보고',COMPLETED:'완료',DISPUTED:'분쟁',NOT_READY:'준비 전',READY:'정산 준비',HOLD:'정산 보류',SETTLED:'정산 완료',STANDARD:'표준상품',CUSTOM:'맞춤 요청',SUBMITTED:'신청',SELECTED:'선택',NOT_SELECTED:'미선택',WITHDRAWN:'철회',REQUESTED:'요청',PROCESSING:'처리 중',FAILED:'실패',REFUNDED:'환불 완료',PARTIALLY_REFUNDED:'일부 환불',APPROVED:'승인',REJECTED:'반려'}
const label=(value:string)=>labels[value]??'상태 확인 필요'
const money=(value:number|null,currency='KRW')=>value===null?'미설정':new Intl.NumberFormat('ko-KR',{style:'currency',currency,maximumFractionDigits:0}).format(value)
const date=(value:string|null)=>value?new Intl.DateTimeFormat('ko-KR',{dateStyle:'medium',timeStyle:'short'}).format(new Date(value)):'-'

export function AdminSubscriptionsPage({pathname}:{pathname:string}){
  const [tab,setTab]=useState<(typeof tabs)[number]>('운영 현황')
  const [services,setServices]=useState<SubscriptionService[]>([])
  const [products,setProducts]=useState<CareProduct[]>([])
  const [requests,setRequests]=useState<SubscriptionRequest[]>([])
  const [applications,setApplications]=useState<SubscriptionApplication[]>([])
  const [contracts,setContracts]=useState<SubscriptionContract[]>([])
  const [visits,setVisits]=useState<SubscriptionVisit[]>([])
  const [changes,setChanges]=useState<SubscriptionScheduleChange[]>([])
  const [showProductForm,setShowProductForm]=useState(false)
  const [error,setError]=useState<string|null>(null)
  const [notice,setNotice]=useState<string|null>(null)
  const load=()=>Promise.all([getSubscriptionServices(),getCareProducts(),getSubscriptionRequests(),getSubscriptionApplications(),getSubscriptionContracts(),getSubscriptionVisits(),getSubscriptionScheduleChanges()]).then(([a,b,c,d,e,f,g])=>{setServices(a);setProducts(b);setRequests(c);setApplications(d);setContracts(e);setVisits(f);setChanges(g)}).catch((reason:unknown)=>setError(reason instanceof Error?reason.message:'정기구독 운영정보를 불러오지 못했습니다.'))
  useEffect(()=>{load()},[])
  const cards=useMemo(()=>[
    {label:'구독 대상 서비스',value:services.length},{label:'운영 상품',value:products.filter(v=>v.isActive).length},{label:'접수 요청',value:requests.filter(v=>v.statusCode==='OPEN').length},{label:'이용 중 계약',value:contracts.filter(v=>v.statusCode==='ACTIVE').length},{label:'예정 회차',value:visits.filter(v=>['SCHEDULED','RESCHEDULED'].includes(v.statusCode)).length}
  ],[services,products,requests,contracts,visits])
  const run=async(action:()=>Promise<unknown>,message:string)=>{setError(null);try{await action();setNotice(message);await load()}catch(reason){setError(reason instanceof Error?reason.message:'요청을 처리하지 못했습니다.')}}
  return <AdminLayout pathname={pathname}>
    <section className="adminPageHeading"><div><p>수달 케어 운영</p><h1>정기구독 관리</h1></div><span>상품·계약·반복 방문과 구독 결제·정산을 분리된 업무 흐름으로 관리합니다.</span></section>
    <section className="adminMetricGrid">{cards.map(v=><article className="adminMetricCard" key={v.label}><span>{v.label}</span><strong className="adminMetricValue">{v.value.toLocaleString('ko-KR')}<small>건</small></strong></article>)}</section>
    {error&&<div className="adminError">{error}</div>}{notice&&<div className="adminNotice">{notice}</div>}
    <div className="subscriptionTabs" role="tablist">{tabs.map(value=><button key={value} className={tab===value?'isActive':''} onClick={()=>setTab(value)}>{value}</button>)}</div>

    {tab==='운영 현황'&&<section className="operationSection"><h2>정기구독 운영 현황</h2><p className="customerNotice">계약·일정·완료·해지는 고객과 전문가가 직접 처리합니다. 본사는 분쟁·안전·결제 실패 등 예외 상태만 확인합니다.</p><Table headers={['계약번호','고객','전문가','서비스','월/회차 금액','상태','다음 회차']} rows={contracts.map(v=>[v.contractNumber,v.customerName,v.providerName,v.serviceName,`${money(v.monthlyAmount)} / ${money(v.visitAmount)}`,label(v.statusCode),date(v.nextVisitAt)])}/></section>}
    {tab==='구독 상품'&&<section className="customerListCard"><header><div><h2>구독 상품</h2><span>기존 구독 대상 서비스 {services.length}개를 참조하며 임의 상품을 생성하지 않습니다.</span></div><button onClick={()=>setShowProductForm(value=>!value)}>{showProductForm?'등록 취소':'상품 등록'}</button></header>{showProductForm&&<ProductForm services={services} onDone={()=>{setShowProductForm(false);load()}} onError={setError}/>}<Table headers={['상품명','서비스','방문','월 금액','회차 금액','적용기간','상태']} rows={products.map(v=>[v.productName,v.serviceName,`${v.visitsPerPeriod}회 · ${v.expectedDurationMinutes}분`,money(v.standardMonthlyAmount),money(v.standardVisitAmount),`${v.effectiveFrom} ~ ${v.effectiveTo??'종료일 없음'}`,v.isActive?'사용':'미사용'])}/></section>}
    {tab==='구독 요청·전문가 신청'&&<><section className="customerListCard"><header><div><h2>구독 요청</h2><span>목록에서는 전화번호와 상세주소를 공개하지 않습니다.</span></div></header><Table headers={['요청번호','고객','서비스','유형','희망 시작일','지역','신청 전문가','선택','상태']} rows={requests.map(v=>[v.requestNumber,v.customerName,v.serviceName,label(v.requestTypeCode),v.preferredStartDate,v.areaName,`${v.applicationCount}곳`,v.providerSelected?'선택 완료':'미선택',label(v.statusCode)])}/></section><section className="customerListCard"><header><div><h2>전문가 신청</h2><span>제안 범위·금액·일정과 신뢰도 참고정보를 비교합니다.</span></div></header><Table headers={['요청번호','고객','서비스','전문가','월 금액','회차 금액','가능 일정','신뢰도','상태']} rows={applications.map(v=>[v.requestNumber,v.customerName,v.serviceName,v.providerName,money(v.proposedMonthlyAmount),money(v.proposedVisitAmount),v.availableScheduleText??'-',v.trustScore??'평가 중',label(v.statusCode)])}/></section></>}
    {tab==='계약 관리'&&<section className="customerListCard"><header><div><h2>계약 현황</h2><span>가격·범위·반복규칙은 계약 생성 시점에 보존됩니다. 상태 변경과 전문가 재선택은 당사자가 직접 처리합니다.</span></div></header><Table headers={['계약번호','고객','전문가','서비스','월/회차 금액','상태','다음 회차']} rows={contracts.map(v=>[v.contractNumber,v.customerName,v.providerName,v.serviceName,`${money(v.monthlyAmount)} / ${money(v.visitAmount)}`,label(v.statusCode),date(v.nextVisitAt)])}/></section>}
    {tab==='회차·일정 관리'&&<><section className="customerListCard"><header><div><h2>방문 회차</h2><span>고객과 전문가가 건너뛰기·일정 변경을 직접 처리하며 결과만 조회합니다.</span></div></header><Table headers={['방문일시','계약번호','회차','전문가','방문확인','완료확인','정산상태']} rows={visits.map(v=>[date(v.scheduledStartAt),v.contractNumber,`${v.visitNo}회차`,v.providerName,v.visitVerifiedAt?'확인':'미확인',v.customerConfirmedAt?'고객 확인':'대기',label(v.settlementStatusCode)])}/></section><section className="customerListCard"><header><div><h2>일정 변경 예외</h2><span>요청 후 48시간 동안은 고객과 전문가가 직접 결정하며, 이후 미처리 건만 본사가 예외 처리합니다.</span></div></header><Table headers={['기존 일정','변경 일정','사유','요청일','상태','예외 처리']} rows={changes.map(v=>[date(v.oldStartAt),date(v.newStartAt),v.reason,date(v.requestedAt),label(v.statusCode),<span key={v.id} className="subscriptionActions"><button disabled={v.statusCode!=='REQUESTED'} onClick={()=>run(()=>decideSubscriptionScheduleChange(v.id,true),'장기 미처리 일정 변경을 승인했습니다.')}>예외 승인</button><button disabled={v.statusCode!=='REQUESTED'} onClick={()=>run(()=>decideSubscriptionScheduleChange(v.id,false),'장기 미처리 일정 변경을 반려했습니다.')}>예외 반려</button></span>])}/></section></>}
    {tab==='결제·정산'&&<AdminSubscriptionAccountingPanel/>}
  </AdminLayout>
}

function ProductForm({services,onDone,onError}:{services:SubscriptionService[];onDone:()=>void;onError:(value:string|null)=>void}){
  const [serviceCategoryId,setService]=useState(services[0]?.id??'');const [name,setName]=useState('');const [scope,setScope]=useState('');const [visits,setVisits]=useState(1);const [minutes,setMinutes]=useState(60);const [monthly,setMonthly]=useState('');const [perVisit,setPerVisit]=useState('');const [from,setFrom]=useState(new Date().toISOString().slice(0,10))
  const submit=async(event:FormEvent)=>{event.preventDefault();try{await createCareProduct({serviceCategoryId,productName:name,description:null,serviceScopeText:scope,visitsPerPeriod:visits,expectedDurationMinutes:minutes,billingPeriodCode:'MONTHLY',standardMonthlyAmount:monthly===''?null:Number(monthly),standardVisitAmount:perVisit===''?null:Number(perVisit),effectiveFrom:from,effectiveTo:null,isActive:true});onDone()}catch(reason){onError(reason instanceof Error?reason.message:'상품을 등록하지 못했습니다.')}}
  return <form className="subscriptionProductForm" onSubmit={submit}><label>서비스<select required value={serviceCategoryId} onChange={event=>setService(event.target.value)}>{services.map(v=><option key={v.id} value={v.id}>{v.categoryPath}</option>)}</select></label><label>상품명<input required value={name} onChange={event=>setName(event.target.value)} placeholder="예: 주 1회 가정 정기청소"/></label><label className="wide">서비스 범위<textarea required value={scope} onChange={event=>setScope(event.target.value)} placeholder="예: 거실·주방·욕실 기본 청소와 쓰레기 배출 포함, 창문 외부·곰팡이 제거 제외"/></label><label>월 방문 횟수<input type="number" min="1" value={visits} onChange={event=>setVisits(Number(event.target.value))}/></label><label>예상시간(분)<input type="number" min="1" value={minutes} onChange={event=>setMinutes(Number(event.target.value))}/></label><label>월 금액<input type="number" min="0" value={monthly} onChange={event=>setMonthly(event.target.value)} placeholder="미확정이면 비워두기"/></label><label>회차 금액<input type="number" min="0" value={perVisit} onChange={event=>setPerVisit(event.target.value)} placeholder="미확정이면 비워두기"/></label><label>적용 시작일<input type="date" required value={from} onChange={event=>setFrom(event.target.value)}/></label><button>상품 등록</button></form>
}

function Table({headers,rows}:{headers:string[];rows:Array<Array<ReactNode>>}){return rows.length?<div className="customerTableWrap"><table className="customerTable"><thead><tr>{headers.map(value=><th key={value}>{value}</th>)}</tr></thead><tbody>{rows.map((row,index)=><tr key={index}>{row.map((value,column)=><td key={column}>{value}</td>)}</tr>)}</tbody></table></div>:<div className="customerEmpty"><strong>표시할 정보가 없습니다.</strong><p>조건에 맞는 운영정보가 등록되면 이곳에 표시됩니다.</p></div>}
