import { useEffect, useState } from 'react'
import type { FormEvent } from 'react'
import { AdminLayout } from './AdminLayout'
import { createProviderDocumentType, createProviderRequirementDefinition, createProviderRequirementType, getProviderRequirementStandards, updateProviderDocumentType, updateProviderRequirementDefinition, updateProviderRequirementType } from './providerRequirementStandardApi'
import type { AdminProviderRequirementStandards } from './providerRequirementStandardTypes'

export function AdminProviderRequirementStandardsPage({ pathname }: { pathname: string }) {
  const [data, setData] = useState<AdminProviderRequirementStandards | null>(null)
  const [tab, setTab] = useState<'types' | 'definitions' | 'documents'>('definitions')
  const [error, setError] = useState<string | null>(null); const [notice, setNotice] = useState<string | null>(null); const [saving, setSaving] = useState(false)
  const [typeCode, setTypeCode] = useState(''); const [typeName, setTypeName] = useState('')
  const [definitionType, setDefinitionType] = useState(''); const [definitionCode, setDefinitionCode] = useState(''); const [definitionName, setDefinitionName] = useState(''); const [description, setDescription] = useState('')
  const [documentCode, setDocumentCode] = useState(''); const [documentName, setDocumentName] = useState(''); const [supportsExpiry, setSupportsExpiry] = useState(false)
  const load = async () => { const result = await getProviderRequirementStandards(); setData(result); if (!definitionType) setDefinitionType(result.requirementTypes.find((item) => item.isActive)?.code ?? '') }
  useEffect(() => { load().catch((reason: unknown) => setError(reason instanceof Error ? reason.message : '기준정보를 불러오지 못했습니다.')) }, []) // eslint-disable-line react-hooks/exhaustive-deps
  const run = async (action: () => Promise<unknown>, success: string) => { setSaving(true); setError(null); setNotice(null); try { await action(); await load(); setNotice(success) } catch (reason) { setError(reason instanceof Error ? reason.message : '요청을 처리하지 못했습니다.') } finally { setSaving(false) } }
  const addType = (event: FormEvent) => { event.preventDefault(); void run(() => createProviderRequirementType({ code: typeCode, name: typeName, isActive: true }), '요건유형을 등록했습니다.').then(() => { setTypeCode(''); setTypeName('') }) }
  const addDefinition = (event: FormEvent) => { event.preventDefault(); void run(() => createProviderRequirementDefinition({ requirementTypeCode: definitionType, requirementCode: definitionCode, name: definitionName, description: description || null, isActive: true }), '요건 정의를 등록했습니다.').then(() => { setDefinitionCode(''); setDefinitionName(''); setDescription('') }) }
  const addDocument = (event: FormEvent) => { event.preventDefault(); void run(() => createProviderDocumentType({ code: documentCode, name: documentName, supportsExpiry, isActive: true }), '증빙유형을 등록했습니다.').then(() => { setDocumentCode(''); setDocumentName(''); setSupportsExpiry(false) }) }
  return <AdminLayout pathname={pathname}>
    <section className="adminPageHeading"><div><p>공급자 심사 기준</p><h1>공급자 요건 기준정보</h1></div><span>서비스별 참여 요건과 제출 증빙에 사용할 승인된 기준정보를 관리합니다.</span></section>
    {(error || notice) && <div className={error ? 'adminError' : 'categorySuccess'} role="status">{error ?? notice}</div>}
    <section className="requirementStandardNotice"><strong>세부 Master는 본사 승인 후 등록합니다.</strong><p>기존 677개 서비스 원문을 자동 파싱하지 않으며, 구체적인 자격·면허·보험 종류를 임의 생성하지 않습니다.</p></section>
    <div className="requirementStandardTabs">{([['types','요건 유형'],['definitions','요건 정의'],['documents','증빙유형']] as const).map(([value,label]) => <button type="button" className={tab === value ? 'active' : ''} key={value} onClick={() => setTab(value)}>{label}</button>)}</div>
    {!data ? <div className="pricePolicyLoading">기준정보를 불러오는 중입니다.</div> : tab === 'types' ? <section className="requirementStandardWorkspace">
      <form onSubmit={addType}><h2>요건 유형 등록</h2><label>유형 코드<input required maxLength={30} value={typeCode} onChange={(event) => setTypeCode(event.target.value.toUpperCase().replace(/[^A-Z0-9_]/g,''))} placeholder="승인된 코드" /></label><label>한국어 명칭<input required maxLength={100} value={typeName} onChange={(event) => setTypeName(event.target.value)} /></label><button disabled={saving || !typeCode || !typeName.trim()}>등록</button></form>
      <div className="requirementStandardList"><h2>등록된 요건 유형 <small>{data.requirementTypes.length}</small></h2>{data.requirementTypes.map((item) => <article key={item.code}><div><strong>{item.name}</strong><span>{item.code}</span></div><button type="button" onClick={() => void run(() => updateProviderRequirementType(item.code, { ...item, isActive: !item.isActive }), '요건유형 상태를 변경했습니다.')}>{item.isActive ? '사용 중' : '사용 안 함'}</button></article>)}</div>
    </section> : tab === 'definitions' ? <section className="requirementStandardWorkspace">
      <form onSubmit={addDefinition}><h2>요건 정의 등록</h2><label>요건 유형<select required value={definitionType} onChange={(event) => setDefinitionType(event.target.value)}>{data.requirementTypes.filter((item) => item.isActive).map((item) => <option value={item.code} key={item.code}>{item.name}</option>)}</select></label><label>요건 코드<input required maxLength={50} value={definitionCode} onChange={(event) => setDefinitionCode(event.target.value.toUpperCase().replace(/[^A-Z0-9_]/g,''))} placeholder="본사 승인 코드" /></label><label>요건명<input required maxLength={200} value={definitionName} onChange={(event) => setDefinitionName(event.target.value)} placeholder="한국어 요건명" /></label><label>설명<textarea maxLength={1000} value={description} onChange={(event) => setDescription(event.target.value)} /></label><button disabled={saving || !definitionType || !definitionCode || !definitionName.trim()}>등록</button></form>
      <div className="requirementStandardList"><h2>등록된 요건 정의 <small>{data.requirementDefinitions.length}</small></h2>{data.requirementDefinitions.length === 0 ? <p>등록된 세부 요건이 없습니다.</p> : data.requirementDefinitions.map((item) => <article key={item.id}><div><strong>{item.name}</strong><span>{data.requirementTypes.find((type) => type.code === item.requirementTypeCode)?.name} · {item.requirementCode}</span><p>{item.description || '설명 없음'}</p></div><button type="button" onClick={() => void run(() => updateProviderRequirementDefinition(item.id, { ...item, isActive: !item.isActive }), '요건 정의 상태를 변경했습니다.')}>{item.isActive ? '사용 중' : '사용 안 함'}</button></article>)}</div>
    </section> : <section className="requirementStandardWorkspace">
      <form onSubmit={addDocument}><h2>증빙유형 등록</h2><label>증빙 코드<input required maxLength={50} value={documentCode} onChange={(event) => setDocumentCode(event.target.value.toUpperCase().replace(/[^A-Z0-9_]/g,''))} placeholder="본사 승인 코드" /></label><label>증빙명<input required maxLength={200} value={documentName} onChange={(event) => setDocumentName(event.target.value)} placeholder="한국어 증빙명" /></label><label className="requestFieldCheck"><input type="checkbox" checked={supportsExpiry} onChange={(event) => setSupportsExpiry(event.target.checked)} /><span>유효기간을 관리하는 증빙</span></label><button disabled={saving || !documentCode || !documentName.trim()}>등록</button></form>
      <div className="requirementStandardList"><h2>등록된 증빙유형 <small>{data.documentTypes.length}</small></h2>{data.documentTypes.length === 0 ? <p>등록된 증빙유형이 없습니다.</p> : data.documentTypes.map((item) => <article key={item.id}><div><strong>{item.name}</strong><span>{item.code} · {item.supportsExpiry ? '유효기간 관리' : '유효기간 미사용'}</span></div><button type="button" onClick={() => void run(() => updateProviderDocumentType(item.id, { ...item, isActive: !item.isActive }), '증빙유형 상태를 변경했습니다.')}>{item.isActive ? '사용 중' : '사용 안 함'}</button></article>)}</div>
    </section>}
  </AdminLayout>
}
