import { useCallback, useEffect, useState, type ReactNode } from 'react'
import { navigate } from '../auth/routing'
import { AdminLayout } from './AdminLayout'
import { completeAdminExit, getAdminExit, rejectAdminExit, searchAdminExits, type AdminExitDetail, type AdminExitList } from '../providers/providerExitApi'
import { soodalPrompt } from '../components/soodalDialog'

const money=(value:number)=>`${value.toLocaleString('ko-KR')}원`
const date=(value:string|null)=>value?new Date(value).toLocaleString('ko-KR'):'-'
const label=(value:string)=>({PROVIDER_ROLE_EXIT:'전문가 역할 종료',ACCOUNT_WITHDRAWAL:'전체 계정 탈퇴 요청',REQUESTED:'신청됨',UNDER_REVIEW:'검토 중',REFUND_REQUIRED:'환불 필요',BLOCKED_BY_ACTIVE_WORK:'진행 업무 차단',READY_TO_COMPLETE:'종료 준비 완료',COMPLETED:'완료',REJECTED:'거절',CANCELLED:'취소',APPROVED:'승인',PENDING:'대기',PROCESSING:'처리 중'}[value]??value)

export function AdminProviderExitPage({pathname,id}:{pathname:string;id?:string}){return <AdminLayout pathname={pathname}>{id?<Detail id={id}/>:<List/>}</AdminLayout>}
function List(){const [data,setData]=useState<AdminExitList|null>(null);const [status,setStatus]=useState('');const [page,setPage]=useState(1);const [error,setError]=useState('');useEffect(()=>{searchAdminExits(status,page).then(setData).catch(e=>setError(message(e)))},[status,page]);return <><section className="adminPageHeading"><div><p>전문가 활동 주기</p><h1>전문가 활동 종료 관리</h1></div><span>진행 업무와 Wallet 환불을 서버에서 재검증한 후 역할을 종료합니다.</span></section><section className="walletFilters"><label>업무 상태<select value={status} onChange={e=>{setStatus(e.target.value);setPage(1)}}><option value="">전체</option><option value="BLOCKED_BY_ACTIVE_WORK">진행 업무 차단</option><option value="REFUND_REQUIRED">환불 필요</option><option value="READY_TO_COMPLETE">종료 준비 완료</option><option value="COMPLETED">완료</option><option value="REJECTED">거절</option></select></label></section>{error&&<p className="adminError">{error}</p>}<section className="walletCard"><header><h2>Exit Queue</h2><span>{data?.totalCount??0}건</span></header>{data?.items.length?<Table headers={['전문가','유형','신청일','상태','진행업무','분쟁','Wallet','환불','']} rows={data.items.map(v=>[v.providerName,label(v.requestType),date(v.requestedAt),label(v.status),`${v.activeWorkCount}건`,`${v.openDisputeCount}건`,`${money(v.availableBalance)} / 예약 ${money(v.reservedBalance)}`,v.refundStatus?label(v.refundStatus):v.refundRequired?'필요':'없음',<button key="detail" onClick={()=>navigate(`/admin/provider-exits/${v.id}`)}>상세</button>])}/>:<p className="customerEmpty">신청이 없습니다.</p>}<footer className="walletPagination"><button disabled={page<=1} onClick={()=>setPage(v=>v-1)}>이전</button><span>{page}</span><button disabled={!data||page*20>=data.totalCount} onClick={()=>setPage(v=>v+1)}>다음</button></footer></section></>}
function Detail({id}:{id:string}){const [data,setData]=useState<AdminExitDetail|null>(null);const [error,setError]=useState('');const load=useCallback(()=>getAdminExit(id).then(setData).catch(e=>setError(message(e))),[id]);useEffect(()=>{void load()},[load]);const action=async(type:'complete'|'reject')=>{if(!data)return;const reason=await soodalPrompt(type==='complete'?'역할 종료 결정사유를 입력해 주세요.':'거절 사유를 입력해 주세요.');if(!reason)return;try{const next=type==='complete'?await completeAdminExit(id,reason,data.rowVersion):await rejectAdminExit(id,reason,data.rowVersion);setData(next)}catch(e){setError(message(e))}};if(!data)return <p className="customerEmpty">{error||'신청 상세를 불러오는 중입니다.'}</p>;const active=!['COMPLETED','REJECTED','CANCELLED'].includes(data.status);return <><button className="customerBack" onClick={()=>navigate('/admin/provider-exits')}>← Exit Queue</button><section className="walletHero"><div><p>전문가 활동 종료</p><h1>{data.providerName}</h1><span>{label(data.requestType)} · {date(data.requestedAt)}</span></div><div className="walletHeroBalance"><span>현재 상태</span><strong>{label(data.status)}</strong><small>{label(data.reviewStatus)}</small></div></section>{error&&<p className="adminError">{error}</p>}<section className="walletBalanceGrid"><Card title="진행 업무" value={`${data.readiness.activeWorkCount}건`}/><Card title="미종결 분쟁" value={`${data.readiness.openDisputeCount}건`}/><Card title="가용잔액" value={money(data.readiness.wallet.availableBalance)}/><Card title="예약잔액" value={money(data.readiness.wallet.reservedBalance)}/><Card title="환불" value={data.refundStatus?label(data.refundStatus):data.readiness.wallet.refundRequired?'필요':'없음'}/></section><section className="walletCard"><h2>자동 준비상태 확인 결과</h2><p>{data.readiness.guidance}</p>{data.readiness.blockers.map(v=><p key={v.code} className="walletNotice">{v.label}: {v.count}건</p>)}<dl><dt>신청 사유</dt><dd>{data.reason}</dd><dt>고객 역할</dt><dd>{data.hasCustomerRole?(data.requestType==='ACCOUNT_WITHDRAWAL'?'전체 계정 종료 대상':'유지 대상'):'없음'}</dd><dt>Chat 업무권한</dt><dd>{data.readiness.activeChatAccessCount}건</dd><dt>보존·파기</dt><dd>{data.readiness.retentionPolicyStatus}</dd><dt>관리자 사유</dt><dd>{data.decisionReason??'-'}</dd></dl><div className="walletInlineActions"><button onClick={()=>navigate(`/admin/credits/${data.providerId}`)}>Wallet 환불·원장 확인</button>{active&&<><button disabled={!data.readiness.canComplete||data.requestType==='ACCOUNT_WITHDRAWAL'} onClick={()=>void action('complete')}>{data.requestType==='ACCOUNT_WITHDRAWAL'?'전체 계정 자동 종료 대기':'전문가 역할 종료'}</button><button className="danger" onClick={()=>void action('reject')}>거절</button></>}</div><p className="walletNotice">준비상태는 30초마다 자동 갱신됩니다. 실제 PG·은행 연동 없이 관리자가 이용료 관리 화면에서 지급 확인과 REFUND 원장을 완료하면 다음 상태가 자동 반영됩니다.</p></section></>}
function Card({title,value}:{title:string;value:string}){return <article><span>{title}</span><strong>{value}</strong></article>}
function Table({headers,rows}:{headers:string[];rows:ReactNode[][]}){return <div className="customerTableWrap"><table><thead><tr>{headers.map(v=><th key={v}>{v}</th>)}</tr></thead><tbody>{rows.map((row,i)=><tr key={i}>{row.map((v,j)=><td key={j}>{v}</td>)}</tr>)}</tbody></table></div>}
function message(error:unknown){return error instanceof Error?error.message:'요청을 처리하지 못했습니다.'}
