import { useEffect, useState } from 'react'
import type { FormEvent, ReactNode } from 'react'
import { navigate } from '../auth/routing'
import { AdminLayout } from './AdminLayout'
import { getAdminProvider, searchAdminProviders } from './providerManagementApi'
import type { AdminProviderDetail, AdminProviderList } from './providerManagementTypes'

const tabs = ['기본정보','사업자정보','서비스분야','활동지역','자격·증빙','서비스별 심사','견적·거래','계정·상태','관리이력'] as const
type Tab = typeof tabs[number]
const labels: Record<string,string> = { ACTIVE:'활동', INACTIVE:'비활동', PENDING:'심사 대기', APPROVED:'승인', REJECTED:'반려', SUSPENDED:'정지', WITHDRAWN:'탈퇴', DRAFT:'작성 중', SUBMITTED:'제출', ACCEPTED:'채택', NOT_SELECTED:'미채택', COMPLETED:'완료', IN_PROGRESS:'진행 중', CANCELLED:'취소' }
const roleLabels: Record<string,string> = { CUSTOMER:'고객', PROVIDER:'공급자', ADMIN:'관리자' }
const label = (value:string) => labels[value] ?? value
const date = (value:string|null) => value ? new Intl.DateTimeFormat('ko-KR',{dateStyle:'medium',timeStyle:'short'}).format(new Date(value)) : '-'
const amount = (value:number|null,currency='KRW') => value === null ? '기록 없음' : `${new Intl.NumberFormat('ko-KR').format(value)} ${currency === 'KRW' ? '원' : currency}`
const Empty = ({children}:{children:ReactNode}) => <div className="customerEmpty">{children}</div>

export function AdminProvidersPage({pathname,providerId}:{pathname:string;providerId?:string}) { return <AdminLayout pathname={pathname}>{providerId ? <Detail id={providerId}/> : <List/>}</AdminLayout> }

function List() {
  const [result,setResult]=useState<AdminProviderList|null>(null); const [input,setInput]=useState(''); const [search,setSearch]=useState(''); const [accountStatus,setAccountStatus]=useState(''); const [approvalStatus,setApprovalStatus]=useState(''); const [activityStatus,setActivityStatus]=useState(''); const [page,setPage]=useState(1); const [error,setError]=useState<string|null>(null)
  useEffect(()=>{ searchAdminProviders({search,accountStatus,approvalStatus,activityStatus,page,pageSize:20}).then(setResult).catch((reason:unknown)=>setError(reason instanceof Error?reason.message:'공급자목록을 불러오지 못했습니다.')) },[search,accountStatus,approvalStatus,activityStatus,page])
  const submit=(event:FormEvent)=>{event.preventDefault();setPage(1);setSearch(input.trim())}; const last=Math.max(1,Math.ceil((result?.totalCount??0)/20))
  return <><section className="adminPageHeading"><div><p>공급자 심사·운영</p><h1>공급자 관리</h1></div><span>사업정보, 서비스, 활동지역, 증빙과 활동이력을 한곳에서 확인합니다.</span></section>
    <form className="customerFilters providerFilters" onSubmit={submit}><label className="customerSearch">공급자 찾기<input value={input} onChange={e=>setInput(e.target.value)} placeholder="공급자명, 연락처, 이메일, 사업자번호, Public ID"/></label><label>계정상태<select value={accountStatus} onChange={e=>{setAccountStatus(e.target.value);setPage(1)}}><option value="">전체</option><option value="ACTIVE">정상</option><option value="SUSPENDED">정지</option><option value="WITHDRAWN">탈퇴</option></select></label><label>전체 승인<select value={approvalStatus} onChange={e=>{setApprovalStatus(e.target.value);setPage(1)}}><option value="">전체</option><option value="PENDING">심사 대기</option><option value="APPROVED">승인</option><option value="REJECTED">반려</option><option value="SUSPENDED">정지</option></select></label><label>활동상태<select value={activityStatus} onChange={e=>{setActivityStatus(e.target.value);setPage(1)}}><option value="">전체</option><option value="ACTIVE">활동</option><option value="INACTIVE">비활동</option></select></label><div className="customerFilterActions"><button>검색</button><button type="button" onClick={()=>{setInput('');setSearch('');setAccountStatus('');setApprovalStatus('');setActivityStatus('');setPage(1)}}>초기화</button></div></form>
    {error&&<div className="adminError">{error}</div>}<section className="customerListCard"><header><div><h2>공급자 목록</h2><span>{result?.totalCount??0}명</span></div><small>연락처와 사업자번호는 마스킹됩니다.</small></header>{!result?<Empty>공급자목록을 불러오는 중입니다.</Empty>:!result.items.length?<Empty>조건에 맞는 공급자가 없습니다.</Empty>:<Table headers={['공급자·상호','연락처','계정','전체 승인','서비스','증빙','최근 활동','가입일','']} rows={result.items.map(item=>[<span key="identity"><strong>{item.providerName}</strong><small>{item.maskedBusinessRegistrationNo??'사업자번호 미등록'}</small></span>,<span key="contact">{item.maskedPhone??'미등록'}<small>{item.maskedEmail??'미등록'}</small></span>,label(item.accountStatusCode),label(item.approvalStatusCode),<span key="services">{item.registeredServiceCount}개<small>승인 수: {item.approvedServiceCount??'기준 없음'}</small></span>,item.evidenceSummary,date(item.lastActiveAt),date(item.joinedAt),<button key="detail" type="button" onClick={()=>navigate(`/admin/providers/${item.id}`)}>상세보기</button>])}/>}<footer className="customerPagination"><button disabled={page<=1} onClick={()=>setPage(v=>v-1)}>이전</button><span>{page} / {last}</span><button disabled={page>=last} onClick={()=>setPage(v=>v+1)}>다음</button></footer></section></>
}

function Detail({id}:{id:string}) { const [data,setData]=useState<AdminProviderDetail|null>(null); const [tab,setTab]=useState<Tab>('기본정보'); const [error,setError]=useState<string|null>(null); useEffect(()=>{getAdminProvider(id).then(setData).catch((reason:unknown)=>setError(reason instanceof Error?reason.message:'공급자 상세를 불러오지 못했습니다.'))},[id]); if(error)return <div className="adminError">{error}</div>; if(!data)return <Empty>공급자 상세정보를 불러오는 중입니다.</Empty>; return <><button className="customerBack" onClick={()=>navigate('/admin/providers')}>← 공급자 목록</button><section className="customerDetailHero providerDetailHero"><div><p>공급자 360°</p><h1>{data.basic.providerName}</h1><div className="customerRoles">{data.basic.roles.map(role=><span key={role}>{roleLabels[role]??role}</span>)}</div></div><dl><div><dt>계정상태</dt><dd>{label(data.basic.accountStatusCode)}</dd></div><div><dt>전체 승인</dt><dd>{label(data.basic.approvalStatusCode)}</dd></div><div><dt>활동상태</dt><dd>{label(data.basic.activityStatusCode)}</dd></div></dl></section><section className="providerSummaryCards"><article><span>등록 서비스</span><strong>{data.summary.registeredServiceCount}</strong></article><article><span>승인 서비스</span><strong>{data.summary.approvedServiceCount??'기준 없음'}</strong></article><article><span>제출/승인 증빙</span><strong>{data.summary.submittedDocumentCount}/{data.summary.verifiedDocumentCount??'기준 없음'}</strong></article><article><span>제출/채택 견적</span><strong>{data.summary.submittedQuoteCount}/{data.summary.acceptedQuoteCount}</strong></article><article><span>완료 거래</span><strong>{data.summary.completedTransactionCount}</strong></article></section><nav className="customerTabs">{tabs.map(value=><button key={value} className={tab===value?'active':''} onClick={()=>setTab(value)}>{value}</button>)}</nav><section className="customerTabPanel">{render(data,tab)}</section></> }

function render(data:AdminProviderDetail,tab:Tab) {
 if(tab==='기본정보')return <div className="customerInfoGrid"><Info title="공급자명" value={data.basic.providerName}/><Info title="휴대전화" value={data.basic.phone??'미등록'}/><Info title="이메일" value={data.basic.email??'미등록'}/><Info title="가입일" value={date(data.basic.joinedAt)}/><Info title="최근 로그인" value={date(data.basic.lastLoginAt)}/><Info title="보유 역할" value={data.basic.roles.map(v=>roleLabels[v]??v).join(', ')}/></div>
 if(tab==='사업자정보')return <div className="customerInfoGrid"><Info title="상호" value={data.business.businessName}/><Info title="사업자등록번호" value={data.business.businessRegistrationNo??'미등록'}/><div className="providerUnsupported"><span>추가 사업정보</span><strong>{data.business.message}</strong></div></div>
 if(tab==='서비스분야')return data.services.length?<Table headers={['분류','서비스','등록상태','등록일','서비스별 승인']} rows={data.services.map(v=>[`${v.majorName} > ${v.middleName}`,v.serviceName,label(v.registrationStatusCode),date(v.activatedAt),v.approvalStatus])}/>:<Empty>등록한 서비스가 없습니다.</Empty>
 if(tab==='활동지역')return data.areas.length?<Table headers={['서비스','활동지역','지역단위','상태','등록일','우선지역']} rows={data.areas.map(v=>[v.serviceName,v.areaName,v.areaLevelCode,label(v.statusCode),date(v.activatedAt),v.isPrioritySupported?'지원':'구조 없음'])}/>:<Empty>등록한 활동지역이 없습니다.</Empty>
 if(tab==='자격·증빙')return data.documents.length?<Table headers={['증빙','문서번호','제출파일','검증상태','검증일','만료일','파일열람']} rows={data.documents.map(v=>[v.documentTypeName,v.documentNumber??'미등록',v.originalFileName,label(v.verificationStatusCode),date(v.verifiedAt),v.expiresAt??'-',v.canOpenFile?'열기':v.fileAccessMessage])}/>:<Empty>제출된 증빙이 없습니다. 안전한 관리자 파일 열람 API도 아직 없습니다.</Empty>
 if(tab==='서비스별 심사')return data.serviceReviews.length?<div className="providerReviewList">{data.serviceReviews.map(service=><article key={service.serviceId}><header><div><h2>{service.serviceName}</h2><span>{label(service.registrationStatusCode)}</span></div></header><div className="providerLegacyInfo"><p><strong>자격·면허</strong>{service.legacyQualificationText}</p><p><strong>보험</strong>{service.legacyInsuranceText}</p><p><strong>안전등급</strong>{service.legacySafetyGradeCode}</p></div>{!service.structuredRequirementsConfigured?<Empty>구조화된 공급자 요건이 아직 설정되지 않았습니다.</Empty>:<Table headers={['요건','필수','검증','만료확인','요구 증빙','검증결과','연결 증빙','반려사유']} rows={service.requirements.map(v=>[v.requirementName,v.isRequired?'필수':'선택',v.verificationRequired?'필요':'불필요',v.expiryCheckRequired?'확인':'미확인',v.requiredEvidenceTypes.join(', ')||'지정 없음',label(v.verificationStatusCode),v.linkedDocumentType??'미연결',v.rejectionReason??'-'])}/>}</article>)}</div>:<Empty>등록 서비스 또는 운영정책이 없습니다.</Empty>
 if(tab==='견적·거래')return <div className="customerSplit"><section><h2>견적 활동</h2>{data.quotes.length?<Table headers={['제출일','서비스·요청','금액','상태','채택']} rows={data.quotes.map(v=>[date(v.submittedAt),<><strong>{v.serviceName}</strong><small>{v.requestTitle}</small></>,amount(v.totalAmount,v.currencyCode),label(v.statusCode),v.isAccepted?'채택':'미채택'])}/>:<Empty>제출 견적이 없습니다.</Empty>}</section><section><h2>거래 활동</h2>{data.transactions.length?<Table headers={['서비스','상태','합의금액','시작일','완료일']} rows={data.transactions.map(v=>[v.serviceName,label(v.statusCode),amount(v.agreedAmount,v.currencyCode),date(v.startedAt),date(v.completedAt)])}/>:<Empty>거래 이력이 없습니다.</Empty>}</section></div>
 if(tab==='계정·상태')return <div className="customerSplit"><section><h2>현재 상태</h2><div className="customerInfoGrid"><Info title="계정" value={label(data.basic.accountStatusCode)}/><Info title="전체 승인" value={label(data.basic.approvalStatusCode)}/><Info title="활동" value={label(data.basic.activityStatusCode)}/></div><p className="customerWarning">공급자 삭제와 탈퇴 처리는 지원하지 않습니다.</p></section><section><h2>전체 승인 이력</h2>{data.approvalHistory.length?data.approvalHistory.map(v=><article className="customerRoleHistory" key={v.decidedAt}><strong>{label(v.toStatusCode)}</strong><span>{date(v.decidedAt)} · {v.reason??'사유 없음'}</span></article>):<Empty>기록된 승인 이력이 없습니다.</Empty>}</section></div>
 return data.managementHistory.length?<Table headers={['일시','작업','대상','결과','관리자 역할','사유']} rows={data.managementHistory.map(v=>[date(v.occurredAt),v.actionCode,v.entityType,v.resultCode,v.actorRoleCode??'-',v.reason??'-'])}/>:<Empty>이 공급자를 대상으로 기록된 관리이력이 없습니다. 개인정보 조회 자체는 현재 감사대상이 아닙니다.</Empty>
}
function Info({title,value}:{title:string;value:string}){return <div><span>{title}</span><strong>{value}</strong></div>}
function Table({headers,rows}:{headers:string[];rows:ReactNode[][]}){return <div className="customerTableWrap"><table><thead><tr>{headers.map(v=><th key={v}>{v}</th>)}</tr></thead><tbody>{rows.map((row,index)=><tr key={index}>{row.map((value,i)=><td key={i}>{value}</td>)}</tr>)}</tbody></table></div>}
