import { useCallback, useEffect, useState } from 'react'
import { navigate } from '../auth/routing'
import { AdminLayout } from './AdminLayout'

type Blocker = { code: string; domain: string; label: string; count: number; blocksCompletion: boolean }
type Readiness = { canComplete: boolean; recommendedStatus: string; activeWorkCount: number; openAfterServiceCount: number; openDisputeCount: number; financialPendingCount: number; hasMultipleActiveRoles: boolean; activeRoles: string[]; blockers: Blocker[]; guidance: string; retentionPolicyStatus: string; accountClosurePolicyStatus: string }
type ListItem = { id: string; customerId: string; customerDisplayName: string; scope: string; status: string; requestedAt: string; activeWorkCount: number; openAfterServiceCount: number; openDisputeCount: number; financialPendingCount: number; hasMultipleActiveRoles: boolean; canComplete: boolean }
type ListResponse = { totalCount: number; page: number; pageSize: number; items: ListItem[] }
type Detail = ListItem & { reason: string | null; processedAt: string | null; decisionReason: string | null; rowVersion: string; readiness: Readiness }
const labels: Record<string, string> = { REQUESTED: '신청 접수', UNDER_REVIEW: '검토 중', BLOCKED_BY_ACTIVE_WORK: '진행 업무 차단', READY_TO_COMPLETE: '완료 가능', COMPLETED: '고객 역할 종료', REJECTED: '거절', CANCELLED: '취소', CUSTOMER_ROLE: '고객 역할 종료', ACCOUNT: '전체 계정 검토' }
const label = (value: string) => labels[value] ?? value
const date = (value: string | null) => value ? new Intl.DateTimeFormat('ko-KR', { dateStyle: 'medium', timeStyle: 'short' }).format(new Date(value)) : '-'
async function api<T>(path: string, options?: RequestInit): Promise<T> { const response = await fetch(path, { credentials: 'include', ...options, headers: options?.body ? { 'Content-Type': 'application/json' } : undefined }); if (!response.ok) { const body = await response.json().catch(() => ({})) as { message?: string }; throw new Error(body.message ?? '요청을 처리하지 못했습니다.') } return response.json() as Promise<T> }

export function AdminCustomerWithdrawalPage({ pathname, id }: { pathname: string; id?: string }) {
  return <AdminLayout pathname={pathname}>{id ? <WithdrawalDetail id={id} /> : <WithdrawalList />}</AdminLayout>
}

function WithdrawalList() {
  const [data, setData] = useState<ListResponse | null>(null); const [status, setStatus] = useState(''); const [error, setError] = useState('')
  useEffect(() => { api<ListResponse>(`/api/v1/admin/customer-withdrawals?status=${encodeURIComponent(status)}`).then(setData).catch(value => setError(value instanceof Error ? value.message : '목록을 불러오지 못했습니다.')) }, [status])
  return <><section className="adminPageHeading"><div><p>고객 관리</p><h1>고객 탈퇴 Queue</h1></div><span>완료 시점의 실제 업무상태를 서버에서 다시 확인합니다.</span></section><div className="withdrawalAdminToolbar"><button onClick={() => navigate('/admin/customers')}>고객 관리로</button><label>상태<select value={status} onChange={event => setStatus(event.target.value)}><option value="">전체</option><option value="BLOCKED_BY_ACTIVE_WORK">진행 업무 차단</option><option value="READY_TO_COMPLETE">완료 가능</option><option value="COMPLETED">완료</option><option value="REJECTED">거절</option><option value="CANCELLED">취소</option></select></label></div>{error && <p className="adminError">{error}</p>}<section className="customerListCard"><header><div><h2>탈퇴 신청</h2><span>{data?.totalCount ?? 0}건</span></div><small>이름 외 연락처·주소는 이 Queue에 복제하지 않습니다.</small></header>{!data ? <p className="customerEmpty">불러오는 중입니다.</p> : !data.items.length ? <p className="customerEmpty">신청이 없습니다.</p> : <div className="customerTableWrap"><table><thead><tr><th>고객</th><th>신청일</th><th>상태</th><th>General/Care/Interior/Emergency</th><th>A/S·분쟁</th><th>금전</th><th>다중 역할</th><th /></tr></thead><tbody>{data.items.map(item => <tr key={item.id}><td><strong>{item.customerDisplayName}</strong><small>{label(item.scope)}</small></td><td>{date(item.requestedAt)}</td><td>{label(item.status)}</td><td>{item.activeWorkCount}건</td><td>{item.openAfterServiceCount}/{item.openDisputeCount}건</td><td>{item.financialPendingCount}건</td><td>{item.hasMultipleActiveRoles ? '있음' : '없음'}</td><td><button onClick={() => navigate(`/admin/customers/withdrawals/${item.id}`)}>검토</button></td></tr>)}</tbody></table></div>}</section></>
}

function WithdrawalDetail({ id }: { id: string }) {
  const [data, setData] = useState<Detail | null>(null); const [reason, setReason] = useState(''); const [error, setError] = useState(''); const [busy, setBusy] = useState(false)
  const load = useCallback(() => api<Detail>(`/api/v1/admin/customer-withdrawals/${id}`).then(setData).catch(value => setError(value instanceof Error ? value.message : '상세를 불러오지 못했습니다.')), [id])
  useEffect(() => { void load() }, [load])
  const act = async (action: 'recheck' | 'complete' | 'reject') => { if (!data || !reason.trim()) return; setBusy(true); setError(''); try { const next = await api<Detail>(`/api/v1/admin/customer-withdrawals/${id}/${action}`, { method: 'POST', body: JSON.stringify({ reason, rowVersion: data.rowVersion, idempotencyKey: crypto.randomUUID() }) }); setData(next); setReason('') } catch (value) { setError(value instanceof Error ? value.message : '처리하지 못했습니다.') } finally { setBusy(false) } }
  if (!data) return <><button className="customerBack" onClick={() => navigate('/admin/customers/withdrawals')}>← 탈퇴 Queue</button><p className={error ? 'adminError' : 'customerEmpty'}>{error || '불러오는 중입니다.'}</p></>
  const terminal = ['COMPLETED', 'REJECTED', 'CANCELLED'].includes(data.status)
  return <><button className="customerBack" onClick={() => navigate('/admin/customers/withdrawals')}>← 탈퇴 Queue</button><section className="customerDetailHero"><div><p>Customer Withdrawal</p><h1>{data.customerDisplayName}</h1><span>{label(data.scope)}</span></div><dl><div><dt>현재 상태</dt><dd>{label(data.status)}</dd></div><div><dt>신청일</dt><dd>{date(data.requestedAt)}</dd></div><div><dt>Retention</dt><dd>REPORT_ONLY</dd></div></dl></section><section className="withdrawalAdminGrid"><article><span>진행 업무</span><strong>{data.readiness.activeWorkCount}건</strong></article><article><span>A/S</span><strong>{data.readiness.openAfterServiceCount}건</strong></article><article><span>분쟁</span><strong>{data.readiness.openDisputeCount}건</strong></article><article><span>금전 확인</span><strong>{data.readiness.financialPendingCount}건</strong></article></section><section className="withdrawalPanel"><h2>Readiness</h2><p>{data.readiness.guidance}</p>{data.readiness.blockers.map(item => <span className="withdrawalBlocker" key={item.code}>{item.domain} · {item.label} {item.count}건</span>)}<p>활성 역할: {data.readiness.activeRoles.join(', ')}</p></section><section className="withdrawalPanel"><h2>관리자 결정</h2><label>검토 사유<textarea value={reason} maxLength={1000} onChange={event => setReason(event.target.value)} /></label>{error && <p className="adminError">{error}</p>}{!terminal && <div className="withdrawalAdminActions"><button disabled={busy || !reason.trim()} onClick={() => void act('recheck')}>최신 상태 재검증</button><button disabled={busy || !reason.trim() || !data.readiness.canComplete || data.scope !== 'CUSTOMER_ROLE'} onClick={() => void act('complete')}>고객 역할 종료 승인</button><button disabled={busy || !reason.trim()} onClick={() => void act('reject')}>신청 거절</button></div>}</section></>
}
