import { useEffect,useState } from 'react'
import { approveMonthlySettlement,approveSubscriptionPayout,approveSubscriptionRefund,completeSubscriptionPayout,completeSubscriptionRefund,createMonthlySettlement,createSubscriptionPayout,getMonthlySettlements,getSubscriptionAccountingDashboard,getSubscriptionPaymentLedger,getSubscriptionPayments,getSubscriptionPayouts,getSubscriptionRefundAdjustments,getSubscriptionSettlementItems,holdSubscriptionSettlementItem,prepareSubscriptionSettlementItems } from './subscriptionApi'
import type { MonthlySettlement,SubscriptionAccountingDashboard,SubscriptionPayment,SubscriptionPaymentLedger,SubscriptionPayout,SubscriptionRefundAdjustment,SubscriptionSettlementItem } from './subscriptionTypes'
import { soodalPrompt } from '../components/soodalDialog'

const accountingTabs=['결제 현황','결제 실패','회차 정산대상','월말 정산','전문가 지급','환불·조정','정산 이력'] as const
const labels:Record<string,string>={REQUESTED:'요청',PROCESSING:'처리 중',COMPLETED:'완료',FAILED:'실패',CANCELLED:'취소',PARTIALLY_REFUNDED:'일부 환불',REFUNDED:'환불 완료',CALCULATION_PENDING:'금액 기준 미확정',POLICY_PENDING:'수수료정책 미확정',READY:'정산 준비',HOLD:'보류',SETTLED:'정산 완료',DRAFT:'작성 중',REVIEW:'검토 중',APPROVED:'승인',PAYMENT_PENDING:'지급 대기',PAID:'지급 완료'}
const money=(value:number|null,currency='KRW')=>value===null?'미확정':new Intl.NumberFormat('ko-KR',{style:'currency',currency,maximumFractionDigits:0}).format(value)
const date=(value:string|null)=>value?new Intl.DateTimeFormat('ko-KR',{dateStyle:'medium',timeStyle:'short'}).format(new Date(value)):'-'

export function AdminSubscriptionAccountingPanel(){
  const [tab,setTab]=useState<(typeof accountingTabs)[number]>('결제 현황')
  const [dashboard,setDashboard]=useState<SubscriptionAccountingDashboard|null>(null)
  const [payments,setPayments]=useState<SubscriptionPayment[]>([])
  const [items,setItems]=useState<SubscriptionSettlementItem[]>([])
  const [monthly,setMonthly]=useState<MonthlySettlement[]>([])
  const [payouts,setPayouts]=useState<SubscriptionPayout[]>([])
  const [refunds,setRefunds]=useState<SubscriptionRefundAdjustment[]>([])
  const [ledger,setLedger]=useState<SubscriptionPaymentLedger[]>([])
  const [message,setMessage]=useState<string|null>(null)
  const [error,setError]=useState<string|null>(null)
  const load=()=>Promise.all([getSubscriptionAccountingDashboard(),getSubscriptionPayments(),getSubscriptionSettlementItems(),getMonthlySettlements(),getSubscriptionPayouts(),getSubscriptionRefundAdjustments(),getSubscriptionPaymentLedger()]).then(([a,b,c,d,e,f,g])=>{setDashboard(a);setPayments(b);setItems(c);setMonthly(d);setPayouts(e);setRefunds(f);setLedger(g)}).catch((reason:unknown)=>setError(reason instanceof Error?reason.message:'결제·정산 정보를 불러오지 못했습니다.'))
  useEffect(()=>{load()},[])
  const act=async(run:()=>Promise<unknown>,success:string)=>{setError(null);try{await run();setMessage(success);await load()}catch(reason){setError(reason instanceof Error?reason.message:'요청을 처리하지 못했습니다.')}}
  const completeBankTransfer=async (item:SubscriptionPayout)=>{const reference=await soodalPrompt('은행 송금 확인번호 또는 이체 메모를 입력해 주세요.');if(!reference?.trim())return;const reason=await soodalPrompt('지급 메모를 입력해 주세요.','관리자 은행 송금 완료')??'관리자 은행 송금 완료';void act(()=>completeSubscriptionPayout(item,reference.trim(),reason),'은행 송금 지급 완료를 원장에 기록했습니다.')}
  const now=new Date()
  return <section className="subscriptionAccounting">
    <header className="subscriptionAccountingHeader"><div><h2>결제·월말정산</h2><p>구독료는 PG 자동결제로 수납하고, 전문가 지급은 은행 송금 후 관리자가 확인번호를 기록합니다.</p></div><span className="productionBadge">운영 결제·수동 송금</span></header>
    {dashboard&&<div className="subscriptionAccountingMetrics"><span>결제 요청 <strong>{dashboard.paymentRequestCount}</strong></span><span>결제 실패 <strong>{dashboard.failedPaymentCount}</strong></span><span>정산 준비 <strong>{dashboard.readySettlementItemCount}</strong></span><span>정책 확인 필요 <strong>{dashboard.pendingPolicyItemCount}</strong></span><span>지급 대기 <strong>{dashboard.pendingPayoutCount}</strong></span><span>환불 검토 <strong>{dashboard.openRefundCount}</strong></span></div>}
    {message&&<div className="adminNotice">{message}</div>}{error&&<div className="adminError">{error}</div>}
    <div className="subscriptionAccountingTabs">{accountingTabs.map(value=><button key={value} className={tab===value?'isActive':''} onClick={()=>setTab(value)}>{value}</button>)}</div>
    {tab==='결제 현황'&&<AccountingTable headers={['고객','계약','서비스','청구기간','청구금액','결제수단','상태','요청일','완료일']} rows={payments.map(v=>[v.customerName,v.contractNumber,v.serviceName,`${v.billingPeriodStart} ~ ${v.billingPeriodEnd}`,money(v.requestedAmount,v.currencyCode),v.paymentMethodDisplay??'미등록',labels[v.statusCode]??v.statusCode,date(v.requestedAt),date(v.completedAt)])}/>} 
    {tab==='결제 실패'&&<AccountingTable headers={['고객','계약','서비스','금액','요청일','실패사유']} rows={payments.filter(v=>v.statusCode==='FAILED').map(v=>[v.customerName,v.contractNumber,v.serviceName,money(v.requestedAmount,v.currencyCode),date(v.requestedAt),v.failureReason??'실패 사유 미등록'])}/>} 
    {tab==='회차 정산대상'&&<><div className="subscriptionToolbar"><button onClick={()=>act(()=>prepareSubscriptionSettlementItems(now.getFullYear(),now.getMonth()+1),'이번 달 정산 후보를 확인했습니다.')}>이번 달 정산 후보 생성</button><span>완료보고·고객확인 후 READY인 회차만 생성됩니다.</span></div><AccountingTable headers={['전문가','계약','서비스','회차','방문일','Gross','정책','수수료','Net','상태','보류사유','처리']} rows={items.map(v=>[v.providerName,v.contractNumber,v.serviceName,`${v.visitNo}회차`,date(v.scheduledStartAt),money(v.grossAmount),v.feePolicyCode??'매핑 미확정',money(v.calculatedFeeAmount),money(v.netAmount),labels[v.statusCode]??v.statusCode,v.holdReason??'-',<button key={v.id} disabled={Boolean(v.monthlySettlementId)} onClick={()=>act(()=>holdSubscriptionSettlementItem(v,v.statusCode==='HOLD'),v.statusCode==='HOLD'?'보류를 해제했습니다.':'정산을 보류했습니다.')}>{v.statusCode==='HOLD'?'보류 해제':'보류'}</button>])}/></>}
    {tab==='월말 정산'&&<><div className="subscriptionToolbar"><span>전문가별 월 정산을 생성한 뒤 정책 미확정 항목이 없는 경우에만 승인할 수 있습니다.</span></div><AccountingTable headers={['전문가','정산월','완료 회차','Gross','수수료','조정','지급예정액','상태','승인일','처리']} rows={monthly.map(v=>[v.providerName,`${v.year}년 ${v.month}월`,v.itemCount,money(v.grossTotal),money(v.feeTotal),money(v.adjustmentTotal),money(v.netTotal),labels[v.statusCode]??v.statusCode,date(v.approvedAt),<span key={v.id} className="subscriptionActions">{v.statusCode==='DRAFT'&&<button onClick={()=>act(()=>approveMonthlySettlement(v),'월 정산을 승인했습니다.')}>승인</button>}{v.statusCode==='APPROVED'&&<button onClick={()=>act(()=>createSubscriptionPayout(v.id),'전문가 지급 요청을 생성했습니다.')}>지급 요청</button>}</span>])}/><div className="subscriptionSettlementCandidates">{Array.from(new Map(items.filter(v=>!v.monthlySettlementId&&v.statusCode!=='HOLD'&&v.statusCode!=='CANCELLED').map(v=>[v.providerId,v])).values()).map(v=><button key={v.providerId} onClick={()=>act(()=>createMonthlySettlement(v.providerId,now.getFullYear(),now.getMonth()+1),`${v.providerName}의 월 정산을 생성했습니다.`)}>{v.providerName} 이번 달 정산 생성</button>)}</div></>}
    {tab==='전문가 지급'&&<AccountingTable headers={['전문가','요청금액','승인금액','상태','요청일','완료일','은행 송금 확인번호','처리']} rows={payouts.map(v=>[v.providerName,money(v.requestedAmount),money(v.approvedAmount),labels[v.statusCode]??v.statusCode,date(v.requestedAt),date(v.completedAt),v.externalPayoutReference??'-',<span key={v.id} className="subscriptionActions">{v.statusCode==='REQUESTED'&&<button onClick={()=>act(()=>approveSubscriptionPayout(v),'지급 요청을 승인했습니다.')}>승인</button>}{v.statusCode==='APPROVED'&&<button onClick={()=>completeBankTransfer(v)}>은행 송금 완료</button>}</span>])}/>} 
    {tab==='환불·조정'&&<AccountingTable headers={['고객','유형','요청금액','승인금액','사유','상태','요청일','완료일','처리']} rows={refunds.map(v=>[v.customerName,v.typeCode==='REFUND'?'환불':'조정',money(v.requestedAmount),money(v.approvedAmount),v.reason,labels[v.statusCode]??v.statusCode,date(v.requestedAt),date(v.completedAt),<span key={v.id} className="subscriptionActions">{v.statusCode==='REQUESTED'&&<button onClick={()=>act(()=>approveSubscriptionRefund(v),'환불·조정을 승인했습니다.')}>승인</button>}{v.statusCode==='APPROVED'&&dashboard?.developmentSimulationAvailable&&<button onClick={()=>act(()=>completeSubscriptionRefund(v),'개발환경 완료를 확인했습니다.')}>완료 확인</button>}</span>])}/>} 
    {tab==='정산 이력'&&<AccountingTable headers={['발생일','유형','금액','통화','참조유형','사유']} rows={ledger.map(v=>[date(v.occurredAt),v.entryTypeCode,money(v.amount,v.currencyCode),v.currencyCode,v.referenceType,v.reasonText??'-'])}/>} 
  </section>
}

function AccountingTable({headers,rows}:{headers:string[];rows:Array<Array<React.ReactNode>>}){return rows.length?<div className="customerTableWrap"><table className="customerTable"><thead><tr>{headers.map(value=><th key={value}>{value}</th>)}</tr></thead><tbody>{rows.map((row,index)=><tr key={index}>{row.map((value,column)=><td key={column}>{value}</td>)}</tr>)}</tbody></table></div>:<div className="customerEmpty"><strong>표시할 내역이 없습니다.</strong><p>업무 데이터가 생성되면 이곳에서 확인할 수 있습니다.</p></div>}
