import { useCallback, useEffect, useState } from 'react'
import { providerBlockReasonLabel } from '../relationshipBlocks/reasons'
import { AdminLayout } from './AdminLayout'
import { soodalConfirm } from '../components/soodalDialog'

type Block = { id:string; customerId:string; customerName:string; providerId:string; providerName:string; direction:string; status:string; reasonCode:string|null; createdAt:string; releasedAt:string|null; rowVersion:string; openDisputeCount:number; canAdminRelease:boolean }
const date = (value: string | null) => value ? new Intl.DateTimeFormat('ko-KR', { dateStyle: 'medium', timeStyle: 'short' }).format(new Date(value)) : '-'

export function AdminUserBlocksPage({ pathname }: { pathname: string }) {
  const [items,setItems]=useState<Block[]>([]); const [status,setStatus]=useState('ACTIVE'); const [error,setError]=useState(''); const [notice,setNotice]=useState(''); const [releaseId,setReleaseId]=useState(''); const [reason,setReason]=useState(''); const [busy,setBusy]=useState(false)
  const load=useCallback(()=>{setError('');return fetch(`/api/v1/admin/user-blocks${status?`?status=${status}`:''}`,{credentials:'include'}).then(async response=>{if(!response.ok)throw new Error((await response.json() as {message?:string}).message??'차단 내역을 불러오지 못했습니다.');return response.json() as Promise<Block[]>}).then(setItems).catch(value=>setError(value instanceof Error?value.message:'차단 내역을 불러오지 못했습니다.'))},[status])
  useEffect(()=>{void load()},[load])
  const release=async(item:Block)=>{const clean=reason.trim();if(!clean){setError('관리자 강제해제 사유를 입력해 주세요.');return}if(!await soodalConfirm('이 차단을 관리자 권한으로 강제해제할까요?'))return;setBusy(true);setError('');setNotice('');try{const response=await fetch(`/api/v1/admin/user-blocks/${item.id}/release`,{method:'POST',credentials:'include',headers:{'Content-Type':'application/json'},body:JSON.stringify({reason:clean,idempotencyKey:crypto.randomUUID(),rowVersion:item.rowVersion})});if(!response.ok)throw new Error((await response.json() as {message?:string}).message??'강제해제를 처리하지 못했습니다.');setNotice('관리자 강제해제를 완료하고 사유를 감사기록에 남겼습니다.');setReleaseId('');setReason('');await load()}catch(value){setError(value instanceof Error?value.message:'강제해제를 처리하지 못했습니다.')}finally{setBusy(false)}}
  return <AdminLayout pathname={pathname}><section className="adminPageHeader"><div><p>USER RELATIONSHIP BLOCKS</p><h1>사용자 차단 관리</h1><span>고객→전문가 차단을 확인하고 예외적으로 강제해제합니다.</span></div></section><section className="adminNotice"><strong>관리자 강제해제·분쟁 예외 정책</strong><ul><li>고객이 선택한 표준 사유만 업무상 확인하며 비공개 메모는 관리자 화면에도 표시하지 않습니다.</li><li>강제해제에는 구체적인 관리자 사유가 필요하고 모든 처리는 감사기록에 남습니다.</li><li>두 사용자 사이에 진행 중인 분쟁이 있으면 고객 보호를 위해 강제해제할 수 없습니다. 분쟁 종결 후 처리해 주세요.</li><li>차단 중에도 이미 시작된 거래·채팅·A/S·분쟁 처리는 유지되고, 새로운 매칭·견적·선택만 제한됩니다.</li></ul></section><div className="adminToolbar"><label>상태<select value={status} onChange={event=>setStatus(event.target.value)}><option value="">전체</option><option value="ACTIVE">차단 중</option><option value="RELEASED">해제됨</option></select></label></div>{notice&&<div className="adminSuccess">{notice}</div>}{error&&<div className="adminError">{error}</div>}<div className="adminTableWrap"><table><thead><tr><th>고객</th><th>전문가</th><th>상태</th><th>표준 사유</th><th>진행 분쟁</th><th>생성</th><th>관리</th></tr></thead><tbody>{items.map(item=><tr key={item.id}><td>{item.customerName}</td><td>{item.providerName}</td><td>{item.status==='ACTIVE'?'차단 중':'해제됨'}</td><td>{providerBlockReasonLabel(item.reasonCode)}</td><td>{item.openDisputeCount}건</td><td>{date(item.createdAt)}</td><td>{item.status==='ACTIVE'?<button disabled={!item.canAdminRelease} title={!item.canAdminRelease?'진행 중인 분쟁을 먼저 종결해 주세요.':undefined} onClick={()=>{setReleaseId(item.id);setReason('');setError('')}}>{item.canAdminRelease?'강제해제':'분쟁 중'}</button>:date(item.releasedAt)}</td></tr>)}</tbody></table>{items.length===0&&<p className="adminEmpty">조회된 차단 내역이 없습니다.</p>}</div>{releaseId&&<section className="adminCard"><h2>관리자 강제해제</h2><p>강제해제 사유는 감사기록에 보관됩니다.</p><textarea rows={4} maxLength={1000} value={reason} onChange={event=>setReason(event.target.value)} placeholder="강제해제가 필요한 구체적인 사유를 입력해 주세요."/><div className="adminActions"><button onClick={()=>{setReleaseId('');setReason('')}}>취소</button><button disabled={busy||!reason.trim()} onClick={()=>{const item=items.find(value=>value.id===releaseId);if(item)void release(item)}}>{busy?'처리 중…':'사유 기록 후 강제해제'}</button></div></section>}</AdminLayout>
}
