import { useEffect,useState } from 'react'
import type { FormEvent,ReactNode } from 'react'
import { navigate } from '../auth/routing'
import { AdminLayout } from './AdminLayout'
import { getAdminTrust,searchAdminTrust } from './trustManagementApi'
import type { AdminTrustDetail,AdminTrustList } from './trustManagementTypes'

const statusLabels:Record<string,string>={ACTIVE:'활성',INACTIVE:'비활성',PENDING:'심사 대기',APPROVED:'승인',REJECTED:'반려',SUSPENDED:'정지',WITHDRAWN:'탈퇴',COMPLETED:'완료',CANCELLED:'취소',RECEIVED:'접수',RESOLVED:'해결',UNRESOLVED_CLOSED:'미해결 종료',OPEN:'접수',CLOSED:'종료',NEW_OR_EVALUATING:'신규·평가중',CALCULATED:'산정 완료',LEGACY_UNKNOWN_POLICY:'기존 점수·정책 미상'}
const label=(value:string)=>statusLabels[value]??value
const date=(value:string|null)=>value?new Intl.DateTimeFormat('ko-KR',{dateStyle:'medium',timeStyle:'short'}).format(new Date(value)):'-'
const Empty=({children}:{children:ReactNode})=><div className="customerEmpty">{children}</div>
const tabs=['신뢰도 요약','거래 실적','인증·증빙','A/S','분쟁','신뢰도 변경이력'] as const
type Tab=typeof tabs[number]

export function AdminTrustPage({pathname,providerId}:{pathname:string;providerId?:string}){
  return <AdminLayout pathname={pathname}>{providerId?<Detail providerId={providerId}/>:<List/>}</AdminLayout>
}

function List(){
  const [result,setResult]=useState<AdminTrustList|null>(null);const [input,setInput]=useState('');const [search,setSearch]=useState('');const [evaluationStatus,setEvaluationStatus]=useState('');const [grade,setGrade]=useState('');const [approvalStatus,setApprovalStatus]=useState('');const [activityStatus,setActivityStatus]=useState('');const [hasExpiredEvidence,setHasExpiredEvidence]=useState('');const [hasAfterService,setHasAfterService]=useState('');const [hasDispute,setHasDispute]=useState('');const [page,setPage]=useState(1);const [error,setError]=useState<string|null>(null)
  useEffect(()=>{searchAdminTrust({search,evaluationStatus,grade,approvalStatus,activityStatus,hasExpiredEvidence,hasAfterService,hasDispute,page,pageSize:20}).then(value=>{setResult(value);setError(null)}).catch((reason:unknown)=>setError(reason instanceof Error?reason.message:'신뢰도 목록을 불러오지 못했습니다.'))},[search,evaluationStatus,grade,approvalStatus,activityStatus,hasExpiredEvidence,hasAfterService,hasDispute,page])
  const submit=(event:FormEvent)=>{event.preventDefault();setPage(1);setSearch(input.trim())};const last=Math.max(1,Math.ceil((result?.totalCount??0)/20));const reset=()=>{setInput('');setSearch('');setEvaluationStatus('');setGrade('');setApprovalStatus('');setActivityStatus('');setHasExpiredEvidence('');setHasAfterService('');setHasDispute('');setPage(1)}
  return <><section className="adminPageHeading"><div><p>공급자 품질·이행 근거</p><h1>신뢰도 관리</h1></div><span>확정된 점수만 표시하며, 자동 산정이나 직접 수정은 수행하지 않습니다.</span></section>
    <form className="customerFilters providerFilters" onSubmit={submit}><label className="customerSearch">공급자 찾기<input value={input} onChange={event=>setInput(event.target.value)} placeholder="공급자명, 전화번호, 이메일, 사업자등록번호, Public ID"/></label><Select label="평가상태" value={evaluationStatus} set={setEvaluationStatus} options={[['NEW_OR_EVALUATING','신규·평가중'],['CALCULATED','산정 완료'],['LEGACY_UNKNOWN_POLICY','기존 점수·정책 미상']]}/><Select label="등급" value={grade} set={setGrade} options={[['NEW','신규·평가중'],['SPROUT','새싹수달'],['SAFE','안심수달'],['TRUSTED','믿음수달'],['EXCELLENT','우수수달'],['HONOR','명예수달']]}/><Select label="전체 승인" value={approvalStatus} set={setApprovalStatus} options={[['PENDING','심사 대기'],['APPROVED','승인'],['REJECTED','반려'],['SUSPENDED','정지']]}/><Select label="활동상태" value={activityStatus} set={setActivityStatus} options={[['ACTIVE','활성'],['INACTIVE','비활성']]}/><Select label="만료 증빙" value={hasExpiredEvidence} set={setHasExpiredEvidence} options={[['true','있음'],['false','없음']]}/><Select label="A/S 이력" value={hasAfterService} set={setHasAfterService} options={[['true','있음'],['false','없음']]}/><Select label="분쟁 이력" value={hasDispute} set={setHasDispute} options={[['true','있음'],['false','없음']]}/><div className="customerFilterActions"><button>검색</button><button type="button" onClick={reset}>초기화</button></div></form>
    {error&&<div className="adminError">{error}</div>}<section className="customerListCard"><header><div><h2>공급자 신뢰도 목록</h2><span>{result?.totalCount??0}명</span></div><small>연락처와 사업자등록번호는 목록에서 마스킹됩니다.</small></header>{!result?<Empty>신뢰도 목록을 불러오는 중입니다.</Empty>:result.items.length===0?<Empty>조건에 맞는 공급자가 없습니다.</Empty>:<Table headers={['공급자','연락처','승인·활동','현재 점수','등급·평가상태','완료 거래','A/S','분쟁','인증·증빙','최종 산정일','']} rows={result.items.map(item=>[<span key="provider"><strong>{item.providerName}</strong><small>{item.maskedBusinessRegistrationNo??'사업자번호 미등록'}</small></span>,<span key="contact">{item.maskedPhone??'미등록'}<small>{item.maskedEmail??'미등록'}</small></span>,<span key="status">{label(item.approvalStatusCode)}<small>{label(item.activityStatusCode)}</small></span>,item.score===null?'-':item.score.toFixed(2),<span key="trust"><strong>{item.gradeLabel}</strong><small>{item.isLegacyUnknownPolicy?'기존 점수 / 산정정책 확인필요':label(item.evaluationStatusCode)}</small></span>,item.completedTransactionCount,item.afterServiceCount,item.disputeCount,item.evidenceStatus,date(item.calculatedAt),<button type="button" key="detail" onClick={()=>navigate(`/admin/trust/${item.providerId}`)}>상세보기</button>])}/>}<footer className="customerPagination"><button disabled={page<=1} onClick={()=>setPage(value=>value-1)}>이전</button><span>{page} / {last}</span><button disabled={page>=last} onClick={()=>setPage(value=>value+1)}>다음</button></footer></section></>
}

function Detail({providerId}:{providerId:string}){const [data,setData]=useState<AdminTrustDetail|null>(null);const [tab,setTab]=useState<Tab>('신뢰도 요약');const [error,setError]=useState<string|null>(null);useEffect(()=>{getAdminTrust(providerId).then(setData).catch((reason:unknown)=>setError(reason instanceof Error?reason.message:'신뢰도 상세를 불러오지 못했습니다.'))},[providerId]);if(error)return <div className="adminError">{error}</div>;if(!data)return <Empty>신뢰도 상세를 불러오는 중입니다.</Empty>;return <><button className="customerBack" onClick={()=>navigate('/admin/trust')}>← 신뢰도 목록</button><section className="customerDetailHero providerDetailHero"><div><p>공급자 신뢰도 근거</p><h1>{data.provider.providerName}</h1><span>{data.trust.statusNotice}</span></div><dl><div><dt>현재 점수</dt><dd>{data.trust.score===null?'-':data.trust.score.toFixed(2)}</dd></div><div><dt>등급</dt><dd>{data.trust.gradeLabel}</dd></div><div><dt>평가상태</dt><dd>{label(data.trust.evaluationStatusCode)}</dd></div></dl></section><section className="providerSummaryCards"><article><span>전체 승인</span><strong>{label(data.provider.approvalStatusCode)}</strong></article><article><span>활동상태</span><strong>{label(data.provider.activityStatusCode)}</strong></article><article><span>완료 거래</span><strong>{data.performance.completedTransactionCount}</strong></article><article><span>A/S</span><strong>{data.afterServices.length}</strong></article><article><span>분쟁</span><strong>{data.disputes.length}</strong></article></section><nav className="customerTabs">{tabs.map(value=><button key={value} className={tab===value?'active':''} onClick={()=>setTab(value)}>{value}</button>)}</nav><section className="customerTabPanel">{render(data,tab)}</section></>}

function render(data:AdminTrustDetail,tab:Tab){
  if(tab==='신뢰도 요약')return <div className="customerSplit"><section><h2>현재 평가정보</h2><div className="customerInfoGrid"><Info title="점수" value={data.trust.score===null?'미산정':data.trust.score.toFixed(2)}/><Info title="등급" value={data.trust.gradeLabel}/><Info title="평가상태" value={label(data.trust.evaluationStatusCode)}/><Info title="정책 버전" value={data.trust.policyVersion??'확정 정책 없음'}/><Info title="최종 산정일" value={date(data.trust.calculatedAt)}/></div><p className="customerWarning">{data.trust.statusNotice}</p></section><section><h2>공급자 기본상태</h2><div className="customerInfoGrid"><Info title="계정" value={label(data.provider.accountStatusCode)}/><Info title="전체 승인" value={label(data.provider.approvalStatusCode)}/><Info title="활동" value={label(data.provider.activityStatusCode)}/><Info title="전화번호" value={data.provider.phone??'미등록'}/><Info title="이메일" value={data.provider.email??'미등록'}/><Info title="사업자등록번호" value={data.provider.businessRegistrationNo??'미등록'}/></div><p>{data.reviewNotice}</p></section></div>
  if(tab==='거래 실적')return <><div className="providerSummaryCards"><article><span>견적 제출</span><strong>{data.performance.submittedQuoteCount}</strong></article><article><span>견적 채택</span><strong>{data.performance.acceptedQuoteCount}</strong></article><article><span>거래 생성</span><strong>{data.performance.transactionCount}</strong></article><article><span>거래 완료</span><strong>{data.performance.completedTransactionCount}</strong></article><article><span>거래 취소</span><strong>{data.performance.cancelledTransactionCount}</strong></article></div><p className="customerWarning">이 값은 현재 DB의 단순 업무 건수이며 신뢰도 점수 산식이 아닙니다.</p></>
  if(tab==='인증·증빙')return data.documents.length?<Table headers={['증빙 종류','검증상태','검증일','만료일','만료 여부']} rows={data.documents.map(value=>[value.documentType,label(value.verificationStatusCode),date(value.verifiedAt),value.expiresAt??'-',value.isExpired?'만료':'정상 또는 만료일 없음'])}/>:<Empty>제출된 인증·증빙이 없습니다. 인증상태는 사실정보로만 표시되며 가점·감점하지 않습니다.</Empty>
  if(tab==='A/S')return data.afterServices.length?<Table headers={['접수일','제목','상태','완료일','처리결과','재발','분쟁 전환']} rows={data.afterServices.map(value=>[date(value.receivedAt),value.subject,label(value.statusCode),date(value.completedAt),value.resolutionSummary??value.unresolvedReason??'-',value.recurrenceOccurred===null?'-':value.recurrenceOccurred?'있음':'없음',value.convertedToDispute?'전환':'미전환'])}/>:<Empty>A/S 이력이 없습니다. A/S 접수 자체는 감점으로 처리하지 않습니다.</Empty>
  if(tab==='분쟁')return data.disputes.length?<div>{data.disputes.map(value=><article className="customerRoleHistory" key={value.id}><strong>{value.subject} · {label(value.statusCode)}</strong><span>{date(value.receivedAt)}</span><p>{value.responsibilityNotice}</p></article>)}</div>:<Empty>분쟁 이력이 없습니다. 분쟁 발생 자체는 공급자 귀책으로 처리하지 않습니다.</Empty>
  return data.events.length?<Table headers={['발생일','이벤트','출처','변경 전','변경값','변경 후','등급 변경','사유','정책 버전','처리일']} rows={data.events.map(value=>[date(value.occurredAt),value.eventTypeCode,value.sourceTypeCode,value.scoreBefore??'-',value.scoreDelta??'-',value.scoreAfter??'-',`${value.gradeBefore??'-'} → ${value.gradeAfter??'-'}`,value.reasonText??'-',value.policyVersion??'-',date(value.processedAt)])}/>:<Empty>신뢰도 변경이력이 없습니다. 초기에는 0건이 정상이며 가짜 이벤트를 생성하지 않습니다.</Empty>
}
function Select({label:fieldLabel,value,set,options}:{label:string;value:string;set:(value:string)=>void;options:Array<[string,string]>}){return <label>{fieldLabel}<select value={value} onChange={event=>{set(event.target.value)}}><option value="">전체</option>{options.map(([code,name])=><option key={code} value={code}>{name}</option>)}</select></label>}
function Info({title,value}:{title:string;value:string}){return <div><span>{title}</span><strong>{value}</strong></div>}
function Table({headers,rows}:{headers:string[];rows:ReactNode[][]}){return <div className="customerTableWrap"><table><thead><tr>{headers.map(value=><th key={value}>{value}</th>)}</tr></thead><tbody>{rows.map((row,index)=><tr key={index}>{row.map((value,column)=><td key={column}>{value}</td>)}</tr>)}</tbody></table></div>}
