import { useCallback, useEffect, useState, type FormEvent, type ReactNode } from 'react'
import { navigate } from '../auth/routing'
import { AdminLayout } from './AdminLayout'
import { adjustWallet, approveRefund, cancelRefund, completeDevelopmentRefund, confirmDevelopmentCharge, createDevelopmentCharge, getWallet, requestRefund, restoreFee, searchWallets } from './walletManagementApi'
import type { WalletDetail, WalletList } from './walletManagementTypes'
import { soodalPrompt } from '../components/soodalDialog'

const money=(value:number)=>`${value.toLocaleString('ko-KR')}원`
const date=(value:string|null)=>value?new Date(value).toLocaleString('ko-KR'):'-'
const labels:Record<string,string>={ACTIVE:'사용',FROZEN:'동결',CLOSED:'종료',CHARGE:'결제',RESERVE:'예상 수수료 예약',RELEASE:'예약 해제',USE:'수수료 차감',RESTORE:'수수료 복원',REFUND:'환불',ADJUST:'관리자 조정',REQUESTED:'요청',APPROVED:'승인',PROCESSING:'처리 중',COMPLETED:'완료',SUCCEEDED:'성공',FAILED:'실패',CANCELLED:'취소',REJECTED:'반려',NOT_RESTORED:'미복원',RESTORED:'복원 완료',DEVELOPMENT_MANUAL:'개발용 수동 확인'}
const label=(value:string)=>labels[value]??value
const key=()=>crypto.randomUUID()

export function AdminWalletsPage({pathname,providerId}:{pathname:string;providerId?:string}){return <AdminLayout pathname={pathname}>{providerId?<Detail providerId={providerId}/>:<List/>}</AdminLayout>}

function List(){const [data,setData]=useState<WalletList|null>(null);const [search,setSearch]=useState('');const [status,setStatus]=useState('');const [hasBalance,setHasBalance]=useState('');const [hasRefund,setHasRefund]=useState('');const [page,setPage]=useState(1);const [error,setError]=useState<string|null>(null);useEffect(()=>{searchWallets({search,status,hasBalance,hasRefund,page,pageSize:20}).then(setData).catch(e=>setError(e instanceof Error?e.message:'목록을 불러오지 못했습니다.'))},[search,status,hasBalance,hasRefund,page]);const submit=(event:FormEvent)=>{event.preventDefault();setPage(1);setSearch(new FormData(event.currentTarget as HTMLFormElement).get('search')?.toString().trim()??'')};const summary=data?.summary
return <><section className="adminPageHeading"><div><p>전문가 선결제 이용료</p><h1>이용료 관리</h1></div><span>잔액과 모든 증감 내역을 불변 원장으로 관리합니다.</span></section>
<section className="walletSummaryGrid"><Card title="전체 Wallet" value={`${summary?.totalWalletCount??0}개`}/><Card title="총 가용잔액" value={money(summary?.totalAvailableBalance??0)}/><Card title="오늘 결제" value={money(summary?.todayChargeAmount??0)}/><Card title="오늘 수수료 차감" value={money(summary?.todayFeeUseAmount??0)}/><Card title="오늘 복원" value={money(summary?.todayRestoreAmount??0)}/><Card title="환불 처리 중" value={money(summary?.refundInProgressAmount??0)}/></section>
<form className="walletFilters" onSubmit={submit}><label>전문가 찾기<input name="search" placeholder="전문가명, 상호, 연락처, 이메일, Public ID" defaultValue={search}/></label><label>Wallet 상태<select value={status} onChange={e=>{setStatus(e.target.value);setPage(1)}}><option value="">전체</option><option value="ACTIVE">사용</option><option value="FROZEN">동결</option><option value="CLOSED">종료</option></select></label><label>잔액<select value={hasBalance} onChange={e=>{setHasBalance(e.target.value);setPage(1)}}><option value="">전체</option><option value="true">잔액 있음</option><option value="false">잔액 없음</option></select></label><label>환불<select value={hasRefund} onChange={e=>{setHasRefund(e.target.value);setPage(1)}}><option value="">전체</option><option value="true">진행 중</option><option value="false">진행 없음</option></select></label><button>검색</button></form>
{error&&<p className="adminError">{error}</p>}<section className="walletCard"><header><h2>전문가 Wallet 목록</h2><span>{data?.totalCount??0}건</span></header>{data?.items.length?<Table headers={['전문가·상호','연락처','상태','가용잔액','보류잔액','최근 결제','최근 사용','환불','대사','']} rows={data.items.map(v=>[<span key="provider"><strong>{v.providerName}</strong><small>{v.businessName}</small></span>,<span key="contact">{v.maskedPhone??'미등록'}<small>{v.maskedEmail??'미등록'}</small></span>,label(v.statusCode),money(v.availableBalance),money(v.reservedBalance),date(v.lastChargeAt),date(v.lastUseAt),v.refundInProgress?'진행 중':v.withdrawalRefundRequired?'탈퇴 전 환불 필요':'없음',<span key="reconciliation" className={v.ledgerBalanceMatches?'walletOk':'walletCritical'}>{v.ledgerBalanceMatches?'일치':'불일치'}</span>,<button key="detail" onClick={()=>navigate(`/admin/credits/${v.providerId}`)}>상세</button>])}/>:<Empty>조건에 맞는 Wallet이 없습니다.</Empty>}<footer className="walletPagination"><button disabled={page<=1} onClick={()=>setPage(v=>v-1)}>이전</button><span>{page}</span><button disabled={!data||page*20>=data.totalCount} onClick={()=>setPage(v=>v+1)}>다음</button></footer></section></>}

type Tab='전체 원장'|'결제내역'|'수수료 차감'|'복원'|'환불'|'관리자 조정'|'관리이력'
const tabs:Tab[]=['전체 원장','결제내역','수수료 차감','복원','환불','관리자 조정','관리이력']
function Detail({providerId}:{providerId:string}){const [data,setData]=useState<WalletDetail|null>(null);const [tab,setTab]=useState<Tab>('전체 원장');const [error,setError]=useState<string|null>(null);const load=useCallback(()=>{void getWallet(providerId).then(setData).catch(e=>setError(e instanceof Error?e.message:'상세정보를 불러오지 못했습니다.'))},[providerId]);useEffect(()=>{load()},[load]);if(error)return <p className="adminError">{error}</p>;if(!data)return <Empty>Wallet 정보를 불러오는 중입니다.</Empty>;return <><button className="customerBack" onClick={()=>navigate('/admin/credits')}>← 이용료 잔액 목록</button><section className="walletHero"><div><p>전문가 Wallet</p><h1>{data.provider.providerName}</h1><span>{data.provider.maskedPhone??'연락처 미등록'} · {data.provider.maskedEmail??'이메일 미등록'}</span></div><div className="walletHeroBalance"><span>가용잔액</span><strong>{money(data.balance.availableBalance)}</strong><small>{data.balance.currencyCode} · {label(data.balance.statusCode)}</small></div></section>
<section className="walletBalanceGrid"><Card title="보류잔액" value={money(data.balance.reservedBalance)}/><Card title="환불 가능액" value={money(data.balance.refundableAmount)}/><Card title="환불 처리 중" value={money(data.balance.refundInProgressAmount)}/><Card title="탈퇴 전 확인" value={data.balance.withdrawalRefundRequired?'환불 필요':'잔액 없음'}/><Card title="원장 대사" value={data.balance.ledgerBalanceMatches?'일치':'CRITICAL 불일치'} critical={!data.balance.ledgerBalanceMatches}/></section>
<nav className="customerTabs walletTabs">{tabs.map(v=><button key={v} className={tab===v?'active':''} onClick={()=>setTab(v)}>{v}</button>)}</nav><section className="walletCard walletDetailPanel">{renderTab(data,tab,load,setError)}</section></>}

function renderTab(data:WalletDetail,tab:Tab,reload:()=>void,setError:(v:string|null)=>void){if(tab==='전체 원장')return data.ledger.length?<Table headers={['일시','구분','사유','관련정보','입금·증가','사용·감소','잔액','처리주체']} rows={data.ledger.map(v=>[date(v.occurredAt),label(v.entryTypeCode),v.reason,v.transactionId?`거래 ${v.transactionId}`:v.referenceType??'-',v.amount>0?money(v.amount):'-',v.amount<0?money(Math.abs(v.amount)):'-',money(v.balanceAfter),v.processedBy])}/>:<Empty>원장 내역이 없습니다.</Empty>
if(tab==='결제내역')return <><DevelopmentCharge data={data} reload={reload} setError={setError}/>{data.charges.length?<Table headers={['요청일','금액','방식','상태','완료일','실패사유']} rows={data.charges.map(v=>[date(v.requestedAt),money(v.requestedAmount),label(v.paymentMethodCode),label(v.statusCode),date(v.completedAt),v.failureReason??'-'])}/>:<Empty>결제 요청이 없습니다.</Empty>}</>
if(tab==='수수료 차감')return data.feeCharges.length?<Table headers={['차감일','금액','복원상태','관련 거래','복원']} rows={data.feeCharges.map(v=>[date(v.chargedAt),money(v.feeAmount),label(v.restoreStatusCode),v.transactionId,v.restoreStatusCode==='NOT_RESTORED'?<ActionButton key="restore" text="복원" onClick={async()=>{const reason=await soodalPrompt('복원 상세사유를 입력해 주세요.');if(!reason)return;try{await restoreFee(data.provider.providerId,v.id,{reasonCode:'HEAD_OFFICE_APPROVAL',reason,idempotencyKey:key(),rowVersion:v.rowVersion});reload()}catch(e){setError(message(e))}}}/>:'-'])}/>:<Empty>수수료 차감내역이 없습니다.</Empty>
if(tab==='복원')return data.restores.length?<Table headers={['복원일','사유구분','상세사유','처리자']} rows={data.restores.map(v=>[date(v.restoredAt),label(v.reasonCode),v.reason,v.processedBy])}/>:<Empty>복원내역이 없습니다.</Empty>
if(tab==='환불')return <><RefundForm data={data} reload={reload} setError={setError}/>{data.refunds.length?<Table headers={['요청일','금액','상태','요청사유','검토','처리']} rows={data.refunds.map(v=>[date(v.requestedAt),money(v.requestedAmount),label(v.statusCode),v.requestReason,v.reviewReason??'-',<RefundActions key={v.id} data={data} refund={v} reload={reload} setError={setError}/>])}/>:<Empty>환불 요청이 없습니다.</Empty>}</>
if(tab==='관리자 조정')return <AdjustmentForm data={data} reload={reload} setError={setError}/>
return data.managementHistory.length?<Table headers={['일시','작업','결과','관리자 역할','사유']} rows={data.managementHistory.map(v=>[date(v.occurredAt),v.actionCode,v.resultCode,v.actorRoleCode??'-',v.reason??'-'])}/>:<Empty>관리이력이 없습니다.</Empty>}

function DevelopmentCharge({data,reload,setError}:{data:WalletDetail;reload:()=>void;setError:(v:string|null)=>void}){const [amount,setAmount]=useState('');const [reason,setReason]=useState('');if(!data.developmentManualConfirmationAvailable)return <p className="walletNotice">실제 이용료 결제는 외부 결제 성공 Callback 연동 후 제공됩니다.</p>;const submit=async(e:FormEvent)=>{e.preventDefault();try{const charge=await createDevelopmentCharge(data.provider.providerId,{amount:Number(amount),reason,idempotencyKey:key()});await confirmDevelopmentCharge(data.provider.providerId,charge.id,charge.rowVersion);reload()}catch(error){setError(message(error))}};return <form className="walletActionForm" onSubmit={submit}><header><h3>개발용 수동 결제 확인</h3><span>Development 환경에서만 표시되며 외부 PG 성공을 가장하지 않습니다.</span></header><label>결제금액<input type="number" min="1" required value={amount} onChange={e=>setAmount(e.target.value)}/></label><label>확인사유<input required maxLength={1000} value={reason} onChange={e=>setReason(e.target.value)}/></label><button>요청 후 수동 확인</button></form>}
function AdjustmentForm({data,reload,setError}:{data:WalletDetail;reload:()=>void;setError:(v:string|null)=>void}){const [directionCode,setDirection]=useState('INCREASE');const [amount,setAmount]=useState('');const [reason,setReason]=useState('');const submit=async(e:FormEvent)=>{e.preventDefault();try{await adjustWallet(data.provider.providerId,{directionCode,amount:Number(amount),reason,idempotencyKey:key(),rowVersion:data.balance.rowVersion});reload()}catch(error){setError(message(error))}};return <form className="walletActionForm" onSubmit={submit}><header><h3>관리자 조정</h3><span>잔액을 직접 수정하지 않고 새 원장으로 기록합니다.</span></header><label>방향<select value={directionCode} onChange={e=>setDirection(e.target.value)}><option value="INCREASE">증가</option><option value="DECREASE">감소</option></select></label><label>금액<input type="number" min="1" required value={amount} onChange={e=>setAmount(e.target.value)}/></label><label>조정사유<input required maxLength={1000} value={reason} onChange={e=>setReason(e.target.value)}/></label><button>조정 원장 생성</button></form>}
function RefundForm({data,reload,setError}:{data:WalletDetail;reload:()=>void;setError:(v:string|null)=>void}){const [amount,setAmount]=useState('');const [reason,setReason]=useState('');const submit=async(e:FormEvent)=>{e.preventDefault();try{await requestRefund(data.provider.providerId,{amount:Number(amount),reason,idempotencyKey:key()});reload()}catch(error){setError(message(error))}};return <form className="walletActionForm" onSubmit={submit}><header><h3>환불 요청</h3><span>실제 송금이 아니며 검토 Workflow를 시작합니다. 환불 가능액 {money(data.balance.refundableAmount)}</span></header><label>환불금액<input type="number" min="1" max={data.balance.refundableAmount} required value={amount} onChange={e=>setAmount(e.target.value)}/></label><label>요청사유<input required maxLength={1000} value={reason} onChange={e=>setReason(e.target.value)}/></label><button>환불 검토 요청</button></form>}
function RefundActions({data,refund,reload,setError}:{data:WalletDetail;refund:WalletDetail['refunds'][number];reload:()=>void;setError:(v:string|null)=>void}){const run=async(action:'approve'|'complete'|'cancel')=>{const reason=await soodalPrompt(action==='approve'?'승인사유를 입력해 주세요.':action==='complete'?'개발용 환불 완료 확인사유를 입력해 주세요.':'취소사유를 입력해 주세요.');if(!reason)return;try{if(action==='approve')await approveRefund(data.provider.providerId,refund.id,reason,refund.rowVersion);else if(action==='complete')await completeDevelopmentRefund(data.provider.providerId,refund.id,reason,refund.rowVersion);else await cancelRefund(data.provider.providerId,refund.id,reason,refund.rowVersion);reload()}catch(error){setError(message(error))}};return <span className="walletInlineActions">{refund.statusCode==='REQUESTED'&&<button onClick={()=>void run('approve')}>승인</button>}{refund.statusCode==='APPROVED'&&data.developmentManualConfirmationAvailable&&<button onClick={()=>void run('complete')}>개발용 완료확인</button>}{['REQUESTED','APPROVED','PROCESSING'].includes(refund.statusCode)&&<button className="danger" onClick={()=>void run('cancel')}>취소</button>}</span>}
function Card({title,value,critical=false}:{title:string;value:string;critical?:boolean}){return <article className={critical?'walletCriticalCard':''}><span>{title}</span><strong>{value}</strong></article>}
function Table({headers,rows}:{headers:string[];rows:ReactNode[][]}){return <div className="customerTableWrap"><table><thead><tr>{headers.map(v=><th key={v}>{v}</th>)}</tr></thead><tbody>{rows.map((row,index)=><tr key={index}>{row.map((value,i)=><td key={i}>{value}</td>)}</tr>)}</tbody></table></div>}
function Empty({children}:{children:ReactNode}){return <div className="customerEmpty">{children}</div>}
function ActionButton({text,onClick}:{text:string;onClick:()=>void}){return <button onClick={onClick}>{text}</button>}
function message(error:unknown){return error instanceof Error?error.message:'처리 중 오류가 발생했습니다.'}
