import { useCallback, useEffect, useState } from 'react'
import { AdminLayout } from './AdminLayout'
import { createNotificationTemplate, getNotificationChannels, getNotificationDelivery, getNotificationSummary, previewNotificationTemplate, retryNotificationDelivery, searchNotificationDeliveries, searchNotificationTemplates, setNotificationTemplateStatus, updateNotificationChannel, updateNotificationTemplate } from './notificationApi'
import { AdminNotificationBroadcastPanel } from './AdminNotificationBroadcastPanel'
import type { NotificationChannelSetting, NotificationDelivery, NotificationDeliveryDetail, NotificationPreview, NotificationSummary, NotificationTemplate, PagedNotifications } from './notificationTypes'

const tabs=['알림 현황','단체발송','템플릿','발송 관리','채널 설정'] as const
const channels=['WEB','KAKAO','SMS','EMAIL','PUSH']
const statuses=['PENDING','PROCESSING','SENT','DELIVERED','FAILED','CANCELLED','SKIPPED']
const statusLabel:Record<string,string>={PENDING:'발송 대기',PROCESSING:'처리 중',SENT:'발송 완료',DELIVERED:'전달 완료',FAILED:'발송 실패',CANCELLED:'취소',SKIPPED:'발송 제외'}
const audienceLabel:Record<string,string>={CUSTOMER:'고객',PROVIDER:'전문가',ADMIN:'관리자',ALL:'전체'}
const date=(value:string|null)=>value?new Intl.DateTimeFormat('ko-KR',{dateStyle:'short',timeStyle:'short'}).format(new Date(value)):'-'
const message=(reason:unknown)=>reason instanceof Error?reason.message:'알림 관리 정보를 처리하지 못했습니다.'

export function AdminNotificationsV114Page({pathname}:{pathname:string}){
  const[tab,setTab]=useState<(typeof tabs)[number]>('알림 현황');const[summary,setSummary]=useState<NotificationSummary|null>(null);const[error,setError]=useState('')
  const load=useCallback(()=>getNotificationSummary().then(setSummary).catch(reason=>setError(message(reason))),[])
  useEffect(()=>{void load()},[load])
  return <AdminLayout pathname={pathname}><section className="adminPageHeading"><div><p>통합 운영 알림</p><h1>알림 관리</h1></div><span>업무 알림, 마케팅 동의, 자동 발송과 실패 이력을 한 곳에서 관리합니다.</span></section>{error&&<div className="adminError">{error}</div>}<nav className="customerDetailTabs">{tabs.map(value=><button type="button" className={tab===value?'active':''} onClick={()=>setTab(value)} key={value}>{value}</button>)}</nav>{tab==='알림 현황'&&<Summary value={summary}/>} {tab==='단체발송'&&<AdminNotificationBroadcastPanel/>} {tab==='템플릿'&&<TemplateWorkspace/>} {tab==='발송 관리'&&<DeliveryWorkspace/>} {tab==='채널 설정'&&<ChannelWorkspace/>}</AdminLayout>
}

function Summary({value}:{value:NotificationSummary|null}){const rows=[['오늘 생성',value?.createdToday??0],['발송 대기',value?.pending??0],['발송·전달',value?.sentOrDelivered??0],['발송 실패',value?.failed??0],['WEB 미읽음',value?.webUnread??0]];return <><section className="adminMetricGrid">{rows.map(row=><article className="adminMetricCard" key={row[0]}><span>{row[0]}</span><strong className="adminMetricValue">{row[1]}<small>건</small></strong></article>)}</section><section className="notificationPolicyPanel"><h2>알림 운영 원칙</h2><ul><li>견적·계약·일정·결제·환불·A/S·분쟁은 필수 업무 알림으로 분류합니다.</li><li>이벤트·쿠폰·추천·광고는 선택 마케팅 알림으로 분리하고 명시적 동의가 있는 채널로만 보냅니다.</li><li>오후 9시부터 다음 날 오전 8시까지의 마케팅 발송은 별도 야간 동의가 없으면 제외됩니다.</li><li>카카오·SMS·이메일·Push는 업체 계약과 인증키 등록 전까지 활성화할 수 없습니다.</li></ul></section></>}

type TemplateFormValue={templateCode:string;name:string;description:string;eventTypeCode:string;audienceTypeCode:string;channelCode:string;titleTemplate:string;bodyTemplate:string;isRequiredBusinessNotice:boolean;isMarketing:boolean;effectiveFrom:string;effectiveTo:string;rowVersion?:string}
const emptyTemplate:TemplateFormValue={templateCode:'',name:'',description:'',eventTypeCode:'',audienceTypeCode:'CUSTOMER',channelCode:'WEB',titleTemplate:'',bodyTemplate:'',isRequiredBusinessNotice:true,isMarketing:false,effectiveFrom:'',effectiveTo:''}
const templateForm=(item:NotificationTemplate):TemplateFormValue=>({...item,description:item.description??'',effectiveFrom:item.effectiveFrom?.slice(0,16)??'',effectiveTo:item.effectiveTo?.slice(0,16)??''})
const templateBody=(value:TemplateFormValue)=>({...value,description:value.description||null,effectiveFrom:value.effectiveFrom?new Date(value.effectiveFrom).toISOString():null,effectiveTo:value.effectiveTo?new Date(value.effectiveTo).toISOString():null})

function TemplateWorkspace(){
  const[result,setResult]=useState<PagedNotifications<NotificationTemplate>>({items:[],page:1,pageSize:20,totalCount:0,totalPages:1});const[query,setQuery]=useState({search:'',eventType:'',audience:'',channel:'',active:''});const[page,setPage]=useState(1);const[editing,setEditing]=useState<NotificationTemplate|null>(null);const[open,setOpen]=useState(false);const[error,setError]=useState('')
  const load=useCallback(async()=>{try{const p=new URLSearchParams({page:String(page),pageSize:'20'});Object.entries(query).forEach(([key,value])=>{if(value)p.set(key,value)});setResult(await searchNotificationTemplates(p));setError('')}catch(reason){setError(message(reason))}},[page,query])
  useEffect(()=>{void load()},[load]);const edit=(item?:NotificationTemplate)=>{setEditing(item??null);setOpen(true)}
  return <section className="notificationAdminWorkspace"><form className="notificationSearchBar" onSubmit={event=>{event.preventDefault();setPage(1);void load()}}><input value={query.search} onChange={e=>setQuery({...query,search:e.target.value})} placeholder="템플릿 코드·이름·제목"/><input value={query.eventType} onChange={e=>setQuery({...query,eventType:e.target.value})} placeholder="업무 이벤트"/><select value={query.audience} onChange={e=>setQuery({...query,audience:e.target.value})}><option value="">전체 대상</option><option>CUSTOMER</option><option value="PROVIDER">전문가</option><option>ADMIN</option><option>ALL</option></select><select value={query.channel} onChange={e=>setQuery({...query,channel:e.target.value})}><option value="">전체 채널</option>{channels.map(v=><option key={v}>{v}</option>)}</select><select value={query.active} onChange={e=>setQuery({...query,active:e.target.value})}><option value="">전체 상태</option><option value="true">사용 중</option><option value="false">미사용</option></select><button>검색</button><button type="button" onClick={()=>edit()}>새 템플릿</button></form>{error&&<p className="adminError">{error}</p>}{open&&<TemplateEditor item={editing} close={()=>{setOpen(false);setEditing(null)}} saved={load}/>}<div className="customerTableWrap"><table className="customerTable"><thead><tr><th>템플릿</th><th>업무 이벤트</th><th>대상·채널</th><th>제목</th><th>종류</th><th>상태·관리</th></tr></thead><tbody>{result.items.map(item=><tr key={item.id}><td><strong>{item.name}</strong><br/><small>{item.templateCode}</small></td><td>{item.eventTypeCode}</td><td>{audienceLabel[item.audienceTypeCode]??item.audienceTypeCode}<br/><small>{item.channelCode}</small></td><td>{item.titleTemplate}</td><td>{item.isMarketing?'마케팅':'업무'}{item.isRequiredBusinessNotice&&<><br/><small>필수 안내</small></>}</td><td><button type="button" onClick={()=>edit(item)}>수정</button> <button type="button" onClick={async()=>{try{await setNotificationTemplateStatus(item.id,!item.isActive,item.rowVersion);await load()}catch(reason){setError(message(reason))}}}>{item.isActive?'사용 중지':'사용'}</button></td></tr>)}</tbody></table></div><Pager page={result.page} total={result.totalPages} change={setPage}/></section>
}

function TemplateEditor({item,close,saved}:{item:NotificationTemplate|null;close:()=>void;saved:()=>Promise<void>}){
  const[value,setValue]=useState<TemplateFormValue>(item?templateForm(item):emptyTemplate);const[preview,setPreview]=useState<NotificationPreview|null>(null);const[error,setError]=useState('');const set=<K extends keyof TemplateFormValue>(key:K,next:TemplateFormValue[K])=>setValue(current=>({...current,[key]:next}))
  const submit=async()=>{try{if(item)await updateNotificationTemplate(item.id,templateBody(value));else await createNotificationTemplate(templateBody(value));await saved();close()}catch(reason){setError(message(reason))}}
  const showPreview=async()=>{try{setPreview(await previewNotificationTemplate({titleTemplate:value.titleTemplate,bodyTemplate:value.bodyTemplate,variables:{customer_name:'홍길동',provider_name:'수달 전문가',service_name:'서비스',request_no:'REQ-0001',quote_no:'QUO-0001',transaction_no:'TRX-0001',scheduled_at:'2026-09-01 10:00',event_name:'업무 이벤트',source_no:'SRC-0001',project_no:'PRJ-0001',subscription_no:'SUB-0001',amount:'50,000원',cycle:'1'}}))}catch(reason){setError(message(reason))}}
  return <section className="notificationEditor"><header><h2>{item?'템플릿 수정':'새 템플릿 등록'}</h2><button type="button" onClick={close}>닫기</button></header><div className="notificationFormGrid"><label>템플릿 코드<input required value={value.templateCode} onChange={e=>set('templateCode',e.target.value)}/></label><label>이름<input required value={value.name} onChange={e=>set('name',e.target.value)}/></label><label>업무 이벤트<input required value={value.eventTypeCode} onChange={e=>set('eventTypeCode',e.target.value)}/></label><label>대상<select value={value.audienceTypeCode} onChange={e=>set('audienceTypeCode',e.target.value)}><option>CUSTOMER</option><option value="PROVIDER">전문가</option><option>ADMIN</option><option>ALL</option></select></label><label>채널<select value={value.channelCode} onChange={e=>set('channelCode',e.target.value)}>{channels.map(v=><option key={v}>{v}</option>)}</select></label><label>설명<input value={value.description} onChange={e=>set('description',e.target.value)}/></label><label className="wide">제목<input required value={value.titleTemplate} onChange={e=>set('titleTemplate',e.target.value)}/></label><label className="wide">본문<textarea rows={4} required value={value.bodyTemplate} onChange={e=>set('bodyTemplate',e.target.value)}/></label><label>적용 시작<input type="datetime-local" value={value.effectiveFrom} onChange={e=>set('effectiveFrom',e.target.value)}/></label><label>적용 종료<input type="datetime-local" value={value.effectiveTo} onChange={e=>set('effectiveTo',e.target.value)}/></label><label className="check"><input type="checkbox" checked={value.isRequiredBusinessNotice} onChange={e=>set('isRequiredBusinessNotice',e.target.checked)}/>필수 업무 안내</label><label className="check"><input type="checkbox" checked={value.isMarketing} onChange={e=>set('isMarketing',e.target.checked)}/>마케팅 알림</label></div><div className="notificationEditorActions"><button type="button" onClick={()=>void showPreview()}>미리보기</button><button type="button" onClick={()=>void submit()}>저장</button></div>{preview&&<aside className="notificationPreview"><strong>{preview.title}</strong><p>{preview.body}</p><small>사용 변수: {preview.variables.join(', ')||'없음'}</small></aside>}{error&&<p className="adminError">{error}</p>}</section>
}

function DeliveryWorkspace(){
  const[result,setResult]=useState<PagedNotifications<NotificationDelivery>>({items:[],page:1,pageSize:20,totalCount:0,totalPages:1});const[query,setQuery]=useState({search:'',status:'',channel:'',eventType:'',from:'',to:''});const[page,setPage]=useState(1);const[detail,setDetail]=useState<NotificationDeliveryDetail|null>(null);const[error,setError]=useState('')
  const load=useCallback(async()=>{try{const p=new URLSearchParams({page:String(page),pageSize:'20'});Object.entries(query).forEach(([key,value])=>{if(value)p.set(key,value)});setResult(await searchNotificationDeliveries(p));setError('')}catch(reason){setError(message(reason))}},[page,query]);useEffect(()=>{void load()},[load])
  return <section className="notificationAdminWorkspace">
    <form className="notificationSearchBar" onSubmit={event=>{event.preventDefault();setPage(1);void load()}}>
      <input value={query.search} onChange={e=>setQuery({...query,search:e.target.value})} placeholder="수신자·제목·템플릿"/><input value={query.eventType} onChange={e=>setQuery({...query,eventType:e.target.value})} placeholder="업무 이벤트"/>
      <select value={query.status} onChange={e=>setQuery({...query,status:e.target.value})}><option value="">전체 상태</option>{statuses.map(v=><option key={v} value={v}>{statusLabel[v]}</option>)}</select>
      <select value={query.channel} onChange={e=>setQuery({...query,channel:e.target.value})}><option value="">전체 채널</option>{channels.map(v=><option key={v}>{v}</option>)}</select>
      <input type="date" value={query.from} onChange={e=>setQuery({...query,from:e.target.value})}/><input type="date" value={query.to} onChange={e=>setQuery({...query,to:e.target.value})}/><button>검색</button>
    </form>
    {error&&<p className="adminError">{error}</p>}
    <div className="customerTableWrap"><table className="customerTable"><thead><tr><th>수신자</th><th>채널</th><th>업무 이벤트</th><th>상태</th><th>생성·예정</th><th>실패 정보</th><th>관리</th></tr></thead><tbody>{result.items.map(item=><tr key={item.id}><td>{item.recipient}<br/><small>{audienceLabel[item.recipientRole]??item.recipientRole}</small></td><td>{item.channelCode}</td><td>{item.eventTypeCode}</td><td>{statusLabel[item.statusCode]??item.statusCode}</td><td>{date(item.createdAt)}<br/><small>{date(item.scheduledAt)}</small></td><td>{item.failureCode??'-'}<br/><small>{item.failureReason??''}</small></td><td><button type="button" onClick={async()=>{try{setDetail(await getNotificationDelivery(item.id))}catch(reason){setError(message(reason))}}}>상세</button>{item.statusCode==='FAILED'&&<button type="button" onClick={async()=>{try{await retryNotificationDelivery(item.id);await load()}catch(reason){setError(message(reason))}}}>재시도</button>}</td></tr>)}</tbody></table></div>
    <Pager page={result.page} total={result.totalPages} change={setPage}/>{detail&&<DeliveryDetail value={detail} close={()=>setDetail(null)}/>} 
  </section>
}
function DeliveryDetail({value,close}:{value:NotificationDeliveryDetail;close:()=>void}){return <section className="notificationEditor"><header><h2>발송 상세</h2><button type="button" onClick={close}>닫기</button></header><dl className="customerInfoGrid"><div><dt>템플릿</dt><dd>{value.templateCode??'-'}</dd></div><div><dt>채널·상태</dt><dd>{value.delivery.channelCode} · {statusLabel[value.delivery.statusCode]??value.delivery.statusCode}</dd></div><div><dt>제목</dt><dd>{value.title}</dd></div><div><dt>본문</dt><dd>{value.body}</dd></div></dl><h3>발송 시도 이력</h3>{value.attempts.length?value.attempts.map(item=><article className="notificationAttempt" key={item.attemptNo}><strong>{item.attemptNo}차 · {item.resultCode}</strong><span>{date(item.startedAt)} · {item.failureReason??'정상 처리'}</span></article>):<p>발송 시도 이력이 없습니다.</p>}</section>}

function ChannelWorkspace(){const[items,setItems]=useState<NotificationChannelSetting[]>([]);const[error,setError]=useState('');const load=useCallback(()=>getNotificationChannels().then(setItems).catch(reason=>setError(message(reason))),[]);useEffect(()=>{void load()},[load]);return <section className="notificationChannelGrid"><div className="notificationIntegrationNotice"><strong>외부 업체 계약 전 안전 상태</strong><p>카카오·SMS·이메일·Push는 업체 계약과 서버 인증키 등록 전에는 활성화할 수 없습니다. 비밀키는 이 화면이나 DB에 저장하지 않습니다.</p></div>{items.map(item=><ChannelCard item={item} reload={load} key={item.channelCode}/>)}{error&&<p className="adminError">{error}</p>}</section>}
function ChannelCard({item,reload}:{item:NotificationChannelSetting;reload:()=>Promise<void>}){const[value,setValue]=useState(item);const[error,setError]=useState('');useEffect(()=>setValue(item),[item]);const save=async()=>{try{await updateNotificationChannel(item.channelCode,value);await reload();setError('')}catch(reason){setError(message(reason))}};return <article className="notificationChannelCard"><header><div><h2>{item.displayName}</h2><span>{item.configurationStatus}</span></div><label><input type="checkbox" checked={value.isEnabled} disabled={!item.adapterConfigured} onChange={e=>setValue({...value,isEnabled:e.target.checked})}/>사용</label></header><div className="notificationFormGrid"><label>운영 모드<select value={value.operationModeCode} disabled={!item.adapterConfigured} onChange={e=>setValue({...value,operationModeCode:e.target.value})}><option>DISABLED</option><option>TEST</option><option>PRODUCTION</option></select></label><label>발송 업체 코드<input value={value.providerCode??''} onChange={e=>setValue({...value,providerCode:e.target.value})} placeholder="계약 후 입력"/></label><label>발신 프로필·번호<input value={value.senderIdentity??''} onChange={e=>setValue({...value,senderIdentity:e.target.value})}/></label><label>회신 주소<input value={value.replyTo??''} onChange={e=>setValue({...value,replyTo:e.target.value})}/></label><label>배치 건수<input type="number" min="1" max="500" value={value.batchSize} onChange={e=>setValue({...value,batchSize:Number(e.target.value)})}/></label><label>최대 시도<input type="number" min="1" max="20" value={value.maxAttempts} onChange={e=>setValue({...value,maxAttempts:Number(e.target.value)})}/></label><label>첫 재시도(초)<input type="number" min="5" value={value.baseRetrySeconds} onChange={e=>setValue({...value,baseRetrySeconds:Number(e.target.value)})}/></label><label>최대 재시도(초)<input type="number" min="5" value={value.maxRetrySeconds} onChange={e=>setValue({...value,maxRetrySeconds:Number(e.target.value)})}/></label></div><button type="button" onClick={()=>void save()}>설정 저장</button>{error&&<p className="adminError">{error}</p>}</article>}

function Pager({page,total,change}:{page:number;total:number;change:(value:number)=>void}){return <nav className="notificationPager" aria-label="페이지 이동"><button type="button" disabled={page<=1} onClick={()=>change(page-1)}>이전</button><span>{page} / {total}</span><button type="button" disabled={page>=total} onClick={()=>change(page+1)}>다음</button></nav>}
