import { useEffect,useMemo,useState } from 'react'
import type { FormEvent } from 'react'
import { AdminLayout } from './AdminLayout'
import { changeContractState,createCareProduct,decideSubscriptionScheduleChange,getCareProducts,getSubscriptionApplications,getSubscriptionContracts,getSubscriptionRequests,getSubscriptionScheduleChanges,getSubscriptionServices,getSubscriptionVisits,replaceSubscriptionProvider,skipSubscriptionVisit } from './subscriptionApi'
import type { CareProduct,SubscriptionApplication,SubscriptionContract,SubscriptionRequest,SubscriptionScheduleChange,SubscriptionService,SubscriptionVisit } from './subscriptionTypes'

const tabs=['구독 상품','구독 요청','공급자 신청','계약','회차 일정','일정 변경','일시정지·해지','공급자 교체','결제·정산'] as const
const labels:Record<string,string>={ACTIVE:'이용 중',PAUSED:'일시정지',TERMINATED:'해지',OPEN:'신청 접수',CONTRACTED:'계약 완료',SCHEDULED:'방문 예정',RESCHEDULED:'일정 변경',SKIPPED:'건너뜀',PROVIDER_COMPLETED:'공급자 완료보고',COMPLETED:'완료',DISPUTED:'분쟁',NOT_READY:'준비 전',READY:'정산대상',HOLD:'정산보류',SETTLED:'정산완료',STANDARD:'표준상품',CUSTOM:'주문형'}
const money=(value:number|null,currency='KRW')=>value===null?'미설정':new Intl.NumberFormat('ko-KR',{style:'currency',currency,maximumFractionDigits:0}).format(value)
const date=(value:string|null)=>value?new Intl.DateTimeFormat('ko-KR',{dateStyle:'medium',timeStyle:'short'}).format(new Date(value)):'-'

export function AdminSubscriptionsPage({pathname}:{pathname:string}){
  const [tab,setTab]=useState<(typeof tabs)[number]>('구독 상품');const [services,setServices]=useState<SubscriptionService[]>([]);const [products,setProducts]=useState<CareProduct[]>([]);const [requests,setRequests]=useState<SubscriptionRequest[]>([]);const [applications,setApplications]=useState<SubscriptionApplication[]>([]);const [contracts,setContracts]=useState<SubscriptionContract[]>([]);const [visits,setVisits]=useState<SubscriptionVisit[]>([]);const [changes,setChanges]=useState<SubscriptionScheduleChange[]>([]);const [replacement,setReplacement]=useState<Record<string,string>>({});const [error,setError]=useState<string|null>(null);const [notice,setNotice]=useState<string|null>(null);const [showForm,setShowForm]=useState(false)
  const load=()=>Promise.all([getSubscriptionServices(),getCareProducts(),getSubscriptionRequests(),getSubscriptionApplications(),getSubscriptionContracts(),getSubscriptionVisits(),getSubscriptionScheduleChanges()]).then(([a,b,c,d,e,f,g])=>{setServices(a);setProducts(b);setRequests(c);setApplications(d);setContracts(e);setVisits(f);setChanges(g)}).catch((e:unknown)=>setError(e instanceof Error?e.message:'정기구독 운영정보를 불러오지 못했습니다.'))
  useEffect(()=>{load()},[])
  const cards=useMemo(()=>[{label:'구독 대상 서비스',value:services.length,unit:'개'},{label:'운영 상품',value:products.filter(v=>v.isActive).length,unit:'개'},{label:'접수 요청',value:requests.filter(v=>v.statusCode==='OPEN').length,unit:'건'},{label:'이용 중 계약',value:contracts.filter(v=>v.statusCode==='ACTIVE').length,unit:'건'},{label:'예정 회차',value:visits.filter(v=>['SCHEDULED','RESCHEDULED'].includes(v.statusCode)).length,unit:'건'}],[services,products,requests,contracts,visits])
  const action=async(contract:SubscriptionContract,type:'pause'|'resume'|'terminate')=>{const reason=type==='terminate'?window.prompt('해지 사유를 입력해 주세요.')??'':`${type==='pause'?'관리자 일시정지':'관리자 재개'} 처리`;if(type==='terminate'&&!reason)return;try{await changeContractState(contract.id,type,reason);setNotice('계약 상태를 반영했습니다.');load()}catch(e){setError(e instanceof Error?e.message:'계약 상태를 변경하지 못했습니다.')}}
  return <AdminLayout pathname={pathname}><section className="adminPageHeading"><div><p>수달 케어 운영</p><h1>정기구독 관리</h1></div><span>상품부터 계약과 반복 방문 회차까지 한 흐름으로 관리합니다.</span></section><section className="adminMetricGrid">{cards.map(v=><article className="adminMetricCard" key={v.label}><span>{v.label}</span><strong className="adminMetricValue">{v.value.toLocaleString('ko-KR')}<small>{v.unit}</small></strong></article>)}</section>{error&&<div className="adminError">{error}</div>}{notice&&<div className="adminNotice">{notice}</div>}<div className="subscriptionTabs" role="tablist">{tabs.map(v=><button key={v} className={tab===v?'isActive':''} onClick={()=>setTab(v)}>{v}</button>)}</div>
  {tab==='구독 상품'&&<section className="customerListCard"><header><div><h2>구독 상품</h2><span>기존 구독 대상 서비스 {services.length}개를 사용합니다.</span></div><button onClick={()=>setShowForm(v=>!v)}>{showForm?'등록 취소':'상품 등록'}</button></header>{showForm&&<ProductForm services={services} onDone={()=>{setShowForm(false);load()}} onError={setError}/>}<Table headers={['상품명','서비스','방문','표준 월금액','회차금액','적용기간','상태']} rows={products.map(v=>[v.productName,v.serviceName,`${v.visitsPerPeriod}회 · ${v.expectedDurationMinutes}분`,money(v.standardMonthlyAmount),money(v.standardVisitAmount),`${v.effectiveFrom} ~ ${v.effectiveTo??'종료일 없음'}`,v.isActive?'사용':'미사용'])}/></section>}
  {tab==='구독 요청'&&<section className="customerListCard"><header><div><h2>구독 요청</h2><span>신청 단계에서는 전화번호와 상세주소를 공개하지 않습니다.</span></div></header><Table headers={['요청번호','고객','서비스','유형','희망 시작일','지역','신청 공급자','선택','상태']} rows={requests.map(v=>[v.requestNumber,v.customerName,v.serviceName,labels[v.requestTypeCode]??v.requestTypeCode,v.preferredStartDate,v.areaName,`${v.applicationCount}곳`,v.providerSelected?'선택 완료':'미선택',labels[v.statusCode]??v.statusCode])}/></section>}
  {tab==='공급자 신청'&&<section className="customerListCard"><header><div><h2>공급자 신청</h2><span>제안 범위와 금액, 일정 및 신뢰도 참고정보를 비교합니다.</span></div></header><Table headers={['요청번호','고객','서비스','공급자','월금액','회차금액','가능 일정','신뢰도','상태']} rows={applications.map(v=>[v.requestNumber,v.customerName,v.serviceName,v.providerName,money(v.proposedMonthlyAmount),money(v.proposedVisitAmount),v.availableScheduleText??'-',v.trustScore??'평가 중',labels[v.statusCode]??v.statusCode])}/></section>}
  {(tab==='계약'||tab==='일시정지·해지')&&<section className="customerListCard"><header><div><h2>{tab}</h2><span>가격·범위·반복규칙은 계약 생성 시점 Snapshot으로 보존됩니다.</span></div></header><Table headers={['계약번호','고객','공급자','서비스','월/회차 금액','상태','다음 회차','운영']} rows={contracts.map(v=>[v.contractNumber,v.customerName,v.providerName,v.serviceName,`${money(v.monthlyAmount)} / ${money(v.visitAmount)}`,labels[v.statusCode]??v.statusCode,date(v.nextVisitAt),<span key={`actions-${v.id}`} className="subscriptionActions">{v.statusCode==='ACTIVE'&&<button onClick={()=>action(v,'pause')}>일시정지</button>}{v.statusCode==='PAUSED'&&<button onClick={()=>action(v,'resume')}>재개</button>}{v.statusCode!=='TERMINATED'&&<button className="danger" onClick={()=>action(v,'terminate')}>해지</button>}</span>])}/></section>}
  {tab==='공급자 교체'&&<section className="customerListCard"><header><div><h2>공급자 교체</h2><span>과거 회차는 기존 공급자를 유지하고 미래 회차만 새 공급자에게 배정합니다.</span></div></header><Table headers={['계약번호','현재 공급자','서비스','교체 후보','처리']} rows={contracts.map(v=>{const candidates=applications.filter(a=>a.requestId===v.requestId&&a.providerName!==v.providerName);return[v.contractNumber,v.providerName,v.serviceName,<select key={`provider-${v.id}`} value={replacement[v.id]??''} onChange={e=>setReplacement(old=>({...old,[v.id]:e.target.value}))}><option value="">공급자 선택</option>{candidates.map(a=><option key={a.providerId} value={a.providerId}>{a.providerName}</option>)}</select>,<button key={`replace-${v.id}`} disabled={!replacement[v.id]} onClick={async()=>{try{await replaceSubscriptionProvider(v.id,replacement[v.id],'본사 운영자 공급자 교체');setNotice('미래 회차 공급자를 교체했습니다.');load()}catch(e){setError(e instanceof Error?e.message:'공급자를 교체하지 못했습니다.')}}}>교체 적용</button>]})}/></section>}
  {tab==='회차 일정'&&<section className="customerListCard"><header><div><h2>회차 일정</h2><span>오늘·이번 주 방문과 미완료·고객 미확인·분쟁 회차를 운영합니다.</span></div></header><Table headers={['방문일시','계약번호','회차','공급자','방문확인','완료확인','정산상태','운영']} rows={visits.map(v=>[date(v.scheduledStartAt),v.contractNumber,`${v.visitNo}회차`,v.providerName,v.visitVerifiedAt?'확인됨':'미확인',v.customerConfirmedAt?'고객 확인':'대기',labels[v.settlementStatusCode]??v.settlementStatusCode,<button key={`skip-${v.id}`} disabled={!['SCHEDULED','RESCHEDULED'].includes(v.statusCode)} onClick={async()=>{try{await skipSubscriptionVisit(v.id);setNotice('회차를 건너뜀 처리했습니다. 금액 처리는 수행하지 않았습니다.');load()}catch(e){setError(e instanceof Error?e.message:'회차를 처리하지 못했습니다.')}}}>건너뛰기</button>])}/></section>}
  {tab==='일정 변경'&&<section className="customerListCard"><header><div><h2>일정 변경</h2><span>과거 일정은 유지하고 승인된 변경만 미래 회차에 반영합니다.</span></div></header><Table headers={['기존 일정','변경 일정','사유','요청일','상태','처리']} rows={changes.map(v=>[date(v.oldStartAt),date(v.newStartAt),v.reason,date(v.requestedAt),labels[v.statusCode]??v.statusCode,<span key={`decision-${v.id}`} className="subscriptionActions"><button disabled={v.statusCode!=='REQUESTED'} onClick={async()=>{await decideSubscriptionScheduleChange(v.id,true);load()}}>승인</button><button disabled={v.statusCode!=='REQUESTED'} onClick={async()=>{await decideSubscriptionScheduleChange(v.id,false);load()}}>반려</button></span>])}/></section>}
  {tab==='결제·정산'&&<section className="operationSection"><h2>결제·정산 연동 준비</h2><p className="customerNotice">이번 단계에서는 실제 PG 결제, 카드 자동결제, 월말 정산 계산과 공급자 지급을 수행하지 않습니다. 완료 회차에는 정산 준비·보류 상태만 기록합니다.</p></section>}</AdminLayout>
}

function ProductForm({services,onDone,onError}:{services:SubscriptionService[];onDone:()=>void;onError:(v:string|null)=>void}){const [serviceCategoryId,setService]=useState(services[0]?.id??'');const [name,setName]=useState('');const [scope,setScope]=useState('');const [visits,setVisits]=useState(1);const [minutes,setMinutes]=useState(60);const [monthly,setMonthly]=useState('');const [perVisit,setPerVisit]=useState('');const [from,setFrom]=useState(new Date().toISOString().slice(0,10));const submit=async(e:FormEvent)=>{e.preventDefault();try{await createCareProduct({serviceCategoryId,productName:name,description:null,serviceScopeText:scope,visitsPerPeriod:visits,expectedDurationMinutes:minutes,billingPeriodCode:'MONTHLY',standardMonthlyAmount:monthly===''?null:Number(monthly),standardVisitAmount:perVisit===''?null:Number(perVisit),effectiveFrom:from,effectiveTo:null,isActive:true});onDone()}catch(err){onError(err instanceof Error?err.message:'상품을 등록하지 못했습니다.')}};return <form className="subscriptionProductForm" onSubmit={submit}><label>서비스<select required value={serviceCategoryId} onChange={e=>setService(e.target.value)}>{services.map(v=><option key={v.id} value={v.id}>{v.categoryPath}</option>)}</select></label><label>상품명<input required value={name} onChange={e=>setName(e.target.value)}/></label><label className="wide">서비스 범위<textarea required value={scope} onChange={e=>setScope(e.target.value)}/></label><label>월 방문 횟수<input type="number" min="1" value={visits} onChange={e=>setVisits(Number(e.target.value))}/></label><label>예상시간(분)<input type="number" min="1" value={minutes} onChange={e=>setMinutes(Number(e.target.value))}/></label><label>표준 월금액<input type="number" min="0" value={monthly} onChange={e=>setMonthly(e.target.value)} placeholder="미확정 시 비워두기"/></label><label>회차금액<input type="number" min="0" value={perVisit} onChange={e=>setPerVisit(e.target.value)} placeholder="미확정 시 비워두기"/></label><label>적용 시작일<input type="date" required value={from} onChange={e=>setFrom(e.target.value)}/></label><button>상품 등록</button></form>}
function Table({headers,rows}:{headers:string[];rows:Array<Array<React.ReactNode>>}){return rows.length?<div className="customerTableWrap"><table className="customerTable"><thead><tr>{headers.map(v=><th key={v}>{v}</th>)}</tr></thead><tbody>{rows.map((row,i)=><tr key={i}>{row.map((v,j)=><td key={j}>{v}</td>)}</tr>)}</tbody></table></div>:<div className="customerEmpty"><strong>표시할 정보가 없습니다.</strong><p>조건에 맞는 운영정보가 등록되면 이곳에 표시됩니다.</p></div>}
