import { useEffect, useMemo, useState } from 'react'
import { createAdminProviderRequirement, getAdminProviderRequirements, replaceAdminProviderRequirementEvidence, updateAdminProviderRequirement } from './providerRequirementApi'
import { getProviderRequirementStandards } from './providerRequirementStandardApi'
import type { AdminProviderRequirement, AdminProviderRequirementList, AdminCategoryProviderRequirement, SaveAdminCategoryProviderRequirementInput } from './providerRequirementTypes'
import type { AdminProviderRequirementStandards } from './providerRequirementStandardTypes'

const statusLabels = { CURRENT: '현재 적용', SCHEDULED: '적용 예정', ENDED: '적용 종료', INACTIVE: '비활성' } as const
const dateText = (value: string | null) => value ? value.replaceAll('-', '.') : '종료일 없음'

export function AdminProviderRequirementsPanel({ serviceId, serviceName }: { serviceId: string; serviceName: string }) {
  const [data, setData] = useState<AdminProviderRequirementList | null>(null); const [standards, setStandards] = useState<AdminProviderRequirementStandards | null>(null)
  const [selectedId, setSelectedId] = useState<string | null>(null); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false)
  const [error, setError] = useState<string | null>(null); const [notice, setNotice] = useState<string | null>(null)
  const [definitionId, setDefinitionId] = useState(''); const [isRequired, setIsRequired] = useState(true); const [verificationRequired, setVerificationRequired] = useState(true)
  const [expiryRequired, setExpiryRequired] = useState(false); const [minimumDays, setMinimumDays] = useState(''); const [displayOrder, setDisplayOrder] = useState('0')
  const load = async (policyId?: string) => { const [requirements, standardData] = await Promise.all([getAdminProviderRequirements(serviceId), getProviderRequirementStandards()]); setData(requirements); setStandards(standardData); setSelectedId(policyId ?? requirements.currentPolicyId ?? requirements.policies[0]?.id ?? null); if (!definitionId) setDefinitionId(standardData.requirementDefinitions.find((item) => item.isActive)?.id ?? '') }
  useEffect(() => { setLoading(true); setError(null); load().catch((reason: unknown) => setError(reason instanceof Error ? reason.message : '공급자 요건을 불러오지 못했습니다.')).finally(() => setLoading(false)) }, [serviceId]) // eslint-disable-line react-hooks/exhaustive-deps
  const selected = useMemo<AdminProviderRequirement | null>(() => data?.policies.find((policy) => policy.id === selectedId) ?? null, [data, selectedId])
  const run = async (action: () => Promise<AdminProviderRequirement>, success: string) => { if (!selected) return; setSaving(true); setError(null); setNotice(null); try { const result = await action(); await load(result.id); setNotice(success) } catch (reason) { setError(reason instanceof Error ? reason.message : '공급자 요건을 저장하지 못했습니다.') } finally { setSaving(false) } }
  const add = () => { if (!selected || !definitionId) return; void run(() => createAdminProviderRequirement(serviceId, selected.id, { requirementDefinitionId: definitionId, isRequired, verificationRequired, expiryCheckRequired: expiryRequired, minimumValidDays: expiryRequired && minimumDays ? Number(minimumDays) : null, displayOrder: Number(displayOrder), isActive: true }), '구조화 공급자 요건을 추가했습니다.') }
  const saveAssignment = (item: AdminCategoryProviderRequirement, changes: Partial<SaveAdminCategoryProviderRequirementInput>) => { if (!selected) return; const input = { requirementDefinitionId: item.requirementDefinitionId, isRequired: item.isRequired, verificationRequired: item.verificationRequired, expiryCheckRequired: item.expiryCheckRequired, minimumValidDays: item.minimumValidDays, displayOrder: item.displayOrder, isActive: item.isActive, ...changes }; if (!input.expiryCheckRequired) input.minimumValidDays = null; void run(() => updateAdminProviderRequirement(serviceId, selected.id, item.id, input), '구조화 공급자 요건을 변경했습니다.') }
  const toggleEvidence = (item: AdminCategoryProviderRequirement, documentTypeId: string) => { if (!selected || !standards) return; const selectedIds = new Set(item.evidenceTypes.map((evidence) => evidence.documentTypeId)); if (selectedIds.has(documentTypeId)) selectedIds.delete(documentTypeId); else selectedIds.add(documentTypeId); const links = standards.documentTypes.filter((type) => selectedIds.has(type.id)).map((type, index) => ({ documentTypeId: type.id, isRequired: true, displayOrder: index })); void run(() => replaceAdminProviderRequirementEvidence(serviceId, selected.id, item.id, links), '요구 증빙유형을 변경했습니다.') }
  if (loading) return <div className="pricePolicyLoading">공급자 요건을 불러오는 중입니다.</div>
  if (error && !data) return <div className="adminError" role="status">{error}</div>
  if (!data || !selected || !standards) return <div className="categoryFutureTab"><strong>공급자 요건</strong><p>등록된 공급자 요건 원문이 없습니다.</p></div>
  const availableDefinitions = standards.requirementDefinitions.filter((definition) => definition.isActive && !selected.structuredRequirements.some((assignment) => assignment.requirementDefinitionId === definition.id))
  return <div className="providerRequirementManager">
    {(error || notice) && <div className={error ? 'adminError' : 'categorySuccess'} role="status">{error ?? notice}</div>}
    <section className="providerRequirementHeading"><div><span>서비스</span><h3>{serviceName}</h3><p>{statusLabels[selected.effectiveStatus]} · {dateText(selected.effectiveFrom)} ~ {dateText(selected.effectiveTo)}</p></div><div className={`providerRequirementStatus ${selected.effectiveStatus.toLowerCase()}`}><span>정책버전</span><strong>{selected.policyVersion}</strong></div></section>
    {data.hasHistory && <nav className="providerRequirementHistory" aria-label="공급자 요건 이력"><strong>정책 이력</strong>{data.policies.map((policy) => <button type="button" className={selected.id === policy.id ? 'selected' : ''} key={policy.id} onClick={() => setSelectedId(policy.id)}><span>{policy.policyVersion}</span><small>{statusLabels[policy.effectiveStatus]} · {dateText(policy.effectiveFrom)}</small></button>)}</nav>}
    <section className="providerLegacySection"><header><div><span>기존 정책 원문</span><h4>Import 원문을 그대로 보존합니다.</h4></div><em>수정 불가</em></header><div className="providerRequirementGrid"><article><header><span>자격·면허</span><strong>현재 요구사항</strong></header><p>{selected.qualificationAndLicenseRequirement}</p></article><article><header><span>보험</span><strong>보험 요구수준</strong></header><p>{selected.insuranceRequirement}</p></article><article><header><span>안전기준</span><strong>원본 코드</strong></header><p className="providerSafetyCode">{selected.safetyGradeCode}</p><small>공식 한국어 판정 기준이 없어 원본 코드를 표시합니다.</small></article><article><header><span>증빙 유효성</span><strong>Legacy 기준</strong></header><p>구조화된 서비스별 유효기간 기준 없음</p></article></div></section>
    <section className="structuredRequirementSection"><header><div><span>구조화 공급자 요건</span><h4>{selected.structuredRequirements.length === 0 ? '구조화 요건 미설정' : `${selected.structuredRequirements.length}개 요건 설정`}</h4></div><a href="/admin/provider-requirement-standards">기준정보 관리</a></header>
      {selected.structuredRequirements.length === 0 ? <p className="structuredRequirementEmpty">기존 원문은 보존되어 있습니다. 본사 검토 후 승인된 Master를 단계적으로 연결해 주세요.</p> : <div className="structuredRequirementList">{selected.structuredRequirements.map((item) => <article className={!item.isActive ? 'inactive' : ''} key={item.id}><header><div><strong>{item.requirementName}</strong><span>{standards.requirementTypes.find((type) => type.code === item.requirementTypeCode)?.name} · {item.requirementCode}</span></div><button type="button" disabled={saving} onClick={() => saveAssignment(item, { isActive: !item.isActive })}>{item.isActive ? '사용 중' : '사용 안 함'}</button></header><div className="structuredRequirementControls"><label><input type="checkbox" checked={item.isRequired} onChange={(event) => saveAssignment(item, { isRequired: event.target.checked })} />필수</label><label><input type="checkbox" checked={item.verificationRequired} onChange={(event) => saveAssignment(item, { verificationRequired: event.target.checked })} />검증 필요</label><label><input type="checkbox" checked={item.expiryCheckRequired} onChange={(event) => saveAssignment(item, { expiryCheckRequired: event.target.checked })} />만료 확인</label><label>최소 유효일수<input type="number" min="0" disabled={!item.expiryCheckRequired} value={item.minimumValidDays ?? ''} onChange={(event) => saveAssignment(item, { minimumValidDays: event.target.value ? Number(event.target.value) : null })} /></label><label>표시순서<input type="number" min="0" value={item.displayOrder} onChange={(event) => saveAssignment(item, { displayOrder: Number(event.target.value) })} /></label></div><div className="structuredEvidenceChoices"><strong>요구 증빙</strong>{standards.documentTypes.filter((type) => type.isActive).length === 0 ? <span>등록된 증빙유형 없음</span> : standards.documentTypes.filter((type) => type.isActive).map((type) => <label key={type.id}><input type="checkbox" checked={item.evidenceTypes.some((evidence) => evidence.documentTypeId === type.id)} onChange={() => toggleEvidence(item, type.id)} />{type.name}{type.supportsExpiry ? ' · 유효기간 관리' : ''}</label>)}</div></article>)}</div>}
      <div className="structuredRequirementAdd"><select value={definitionId} onChange={(event) => setDefinitionId(event.target.value)}><option value="">요건 정의 선택</option>{availableDefinitions.map((definition) => <option value={definition.id} key={definition.id}>{definition.name}</option>)}</select><label><input type="checkbox" checked={isRequired} onChange={(event) => setIsRequired(event.target.checked)} />필수</label><label><input type="checkbox" checked={verificationRequired} onChange={(event) => setVerificationRequired(event.target.checked)} />검증 필요</label><label><input type="checkbox" checked={expiryRequired} onChange={(event) => setExpiryRequired(event.target.checked)} />만료 확인</label><input aria-label="최소 유효일수" type="number" min="0" disabled={!expiryRequired} value={minimumDays} onChange={(event) => setMinimumDays(event.target.value)} placeholder="최소 유효일수" /><input aria-label="표시순서" type="number" min="0" value={displayOrder} onChange={(event) => setDisplayOrder(event.target.value)} /><button type="button" disabled={saving || !definitionId} onClick={add}>요건 추가</button></div>
      {standards.requirementDefinitions.length === 0 && <div className="providerRequirementReadOnly"><strong>등록된 세부 요건 Master가 없습니다.</strong><p>먼저 공급자 요건 기준정보에서 본사 승인된 요건 정의를 등록해 주세요. Legacy 원문은 계속 유지됩니다.</p></div>}
    </section>
  </div>
}
