import { useCallback, useEffect, useMemo, useState } from 'react'
import { AdminLayout } from './AdminLayout'
import { soodalConfirm } from '../components/soodalDialog'

type Summary = { openRequestCount:number; unmatchedRequestCount:number; activeDispatchCount:number; coveredAreaCount:number; eligibleProviderCount:number }
type Region = { areaId:string; provinceName:string; districtName:string; activeProviderCount:number; activeServiceCount:number; openRequestCount:number; unmatchedRequestCount:number }
type RequestItem = { requestId:string; areaId:string; title:string; categoryName:string; provinceName:string; districtName:string; status:string; isUrgent:boolean; openedAt:string|null; expiresAt:string|null; candidateCount:number; eligibleCandidateCount:number; dispatchCount:number; quoteCount:number }
type Candidate = { providerId:string; businessName:string; status:string; categoryMatch:boolean; areaMatch:boolean; approvalMatch:boolean; reasonCode:string|null }
type Dashboard = { summary:Summary; regions:Region[]; requests:RequestItem[] }
type RematchResult = { evaluatedProviderCount:number; eligibleCandidateCount:number; dispatchCount:number; newDispatchCount:number }

const reasonLabels:Record<string,string> = { PROVIDER_EXIT_IN_PROGRESS:'활동 종료 처리 중', PROVIDER_NOT_ACTIVE:'전문가 비활동', PROVIDER_NOT_APPROVED:'전문가 승인 전', SERVICE_CATEGORY_MISMATCH:'서비스 분야 불일치', SERVICE_AREA_MISMATCH:'출장지역 불일치', PROVIDER_SERVICE_NOT_APPROVED:'서비스 승인 전', REQUIREMENT_NOT_SATISFIED:'필수 전문가 요건 미충족', EVIDENCE_NOT_VERIFIED:'필수 증빙 미검증', USER_RELATIONSHIP_BLOCKED:'고객·전문가 차단 관계', EMERGENCY_SERVICE_NOT_ENABLED:'긴급출동 미허용 서비스', EMERGENCY_OUTSIDE_SCHEDULE:'긴급출동 가능시간 외' }
const statusLabels:Record<string,string> = { OPEN:'공개', MATCHED:'매칭', QUOTED:'견적 접수', ACCEPTED:'채택', CANCELLED:'취소', EXPIRED:'만료', COMPLETED:'완료', ELIGIBLE:'후보', INELIGIBLE:'제외' }
const dateTime = (value:string|null) => value ? new Intl.DateTimeFormat('ko-KR',{dateStyle:'medium',timeStyle:'short'}).format(new Date(value)) : '-'
async function readError(response:Response, fallback:string) { try { const body = await response.json() as { message?:string }; return body.message ?? fallback } catch { return fallback } }

export function AdminMatchingPage({pathname}:{pathname:string}) {
  const [data,setData]=useState<Dashboard|null>(null), [selected,setSelected]=useState<string|null>(null), [candidates,setCandidates]=useState<Candidate[]>([])
  const [province,setProvince]=useState(''), [mode,setMode]=useState<'OPEN'|'UNMATCHED'|'ALL'>('UNMATCHED'), [search,setSearch]=useState('')
  const [loading,setLoading]=useState(true), [candidateLoading,setCandidateLoading]=useState(false), [rematching,setRematching]=useState(false)
  const [message,setMessage]=useState(''), [error,setError]=useState('')
  const load=useCallback(async()=>{setLoading(true);setError('');try{const response=await fetch('/api/v1/admin/matching',{credentials:'include'});if(!response.ok)throw new Error(await readError(response,'지역·매칭 현황을 불러오지 못했습니다.'));const value=await response.json() as Dashboard;setData(value);setSelected(current=>current&&value.requests.some(item=>item.requestId===current)?current:(value.requests.find(item=>item.status==='OPEN'&&item.dispatchCount===0)??value.requests[0])?.requestId??null)}catch(reason){setError(reason instanceof Error?reason.message:'지역·매칭 현황을 불러오지 못했습니다.')}finally{setLoading(false)}},[])
  useEffect(()=>{void load()},[load])
  useEffect(()=>{if(!selected){setCandidates([]);return}setCandidateLoading(true);fetch(`/api/v1/admin/requests/${selected}/candidates`,{credentials:'include'}).then(async response=>{if(!response.ok)throw new Error(await readError(response,'후보 목록을 불러오지 못했습니다.'));return response.json() as Promise<Candidate[]>}).then(setCandidates).catch(reason=>setError(reason instanceof Error?reason.message:'후보 목록을 불러오지 못했습니다.')).finally(()=>setCandidateLoading(false))},[selected])
  const provinces=useMemo(()=>Array.from(new Set(data?.regions.map(item=>item.provinceName)??[])).sort(),[data])
  const regions=useMemo(()=>(data?.regions??[]).filter(item=>!province||item.provinceName===province),[data,province])
  const requests=useMemo(()=>(data?.requests??[]).filter(item=>(!province||item.provinceName===province)&&(mode==='ALL'||item.status==='OPEN'&&(mode==='OPEN'||item.dispatchCount===0))&&(!search.trim()||`${item.title} ${item.categoryName} ${item.provinceName} ${item.districtName}`.toLowerCase().includes(search.trim().toLowerCase()))),[data,mode,province,search])
  const request=data?.requests.find(item=>item.requestId===selected)??null
  const rematch=async()=>{if(!request||!await soodalConfirm(`'${request.title}' 요청의 후보를 다시 평가하고 배포하시겠습니까?`))return;setRematching(true);setError('');setMessage('');try{const response=await fetch(`/api/v1/admin/matching/requests/${request.requestId}/rematch`,{method:'POST',credentials:'include'});if(!response.ok)throw new Error(await readError(response,'재매칭을 처리하지 못했습니다.'));const result=await response.json() as RematchResult;setMessage(`재평가 ${result.evaluatedProviderCount}명 · 적합 ${result.eligibleCandidateCount}명 · 신규 배포 ${result.newDispatchCount}건을 처리했습니다.`);await load()}catch(reason){setError(reason instanceof Error?reason.message:'재매칭을 처리하지 못했습니다.')}finally{setRematching(false)}}
  return <AdminLayout pathname={pathname}><section className="adminPageHeading"><div><p>본사 업무</p><h1>지역·매칭</h1></div><span>지역별 공급 가능 범위와 공개 요청의 후보·제외 사유를 확인하고 다시 배포합니다.</span></section>{error&&<div className="adminError">{error}</div>}{message&&<div className="adminSuccess">{message}</div>}
    <section className="matchingSummary"><article><span>공개 요청</span><strong>{data?.summary.openRequestCount??0}건</strong></article><article className={(data?.summary.unmatchedRequestCount??0)>0?'warning':''}><span>미매칭 요청</span><strong>{data?.summary.unmatchedRequestCount??0}건</strong></article><article><span>유효 배포</span><strong>{data?.summary.activeDispatchCount??0}건</strong></article><article><span>공급 가능 지역</span><strong>{data?.summary.coveredAreaCount??0}곳</strong></article><article><span>매칭 가능 전문가</span><strong>{data?.summary.eligibleProviderCount??0}명</strong></article></section>
    <section className="matchingFilters"><label>시·도<select value={province} onChange={event=>setProvince(event.target.value)}><option value="">전체</option>{provinces.map(value=><option key={value}>{value}</option>)}</select></label><label>요청 상태<select value={mode} onChange={event=>setMode(event.target.value as typeof mode)}><option value="UNMATCHED">미매칭 공개 요청</option><option value="OPEN">전체 공개 요청</option><option value="ALL">최근 전체 요청</option></select></label><label className="wide">요청 찾기<input value={search} onChange={event=>setSearch(event.target.value)} placeholder="요청명, 서비스, 지역"/></label><button type="button" onClick={()=>void load()} disabled={loading}>{loading?'조회 중':'새로고침'}</button></section>
    <div className="matchingGrid"><section className="matchingRegions"><header><div><h2>지역 공급 현황</h2><span>{regions.length}개 지역</span></div><small>전문가 0명인 요청 지역도 표시됩니다.</small></header><div className="matchingRegionList">{regions.length===0?<p className="customerEmpty">조건에 맞는 지역이 없습니다.</p>:regions.map(item=><article className={item.activeProviderCount===0?'gap':''} key={item.areaId}><div><strong>{item.provinceName} {item.districtName}</strong><span>전문가 {item.activeProviderCount}명 · 서비스 {item.activeServiceCount}개</span></div><div><b>{item.openRequestCount}건</b><small>미매칭 {item.unmatchedRequestCount}건</small></div></article>)}</div></section>
      <section className="matchingRequests"><header><div><h2>요청·배포 현황</h2><span>{requests.length}건</span></div><small>요청을 선택하면 후보 판정 근거를 확인합니다.</small></header><div className="matchingRequestList">{requests.length===0?<p className="customerEmpty">조건에 맞는 요청이 없습니다.</p>:requests.map(item=><button type="button" className={selected===item.requestId?'active':''} key={item.requestId} onClick={()=>setSelected(item.requestId)}><span><b>{item.isUrgent?'긴급 ':''}{statusLabels[item.status]??item.status}</b>{item.provinceName} {item.districtName}</span><strong>{item.title}</strong><small>{item.categoryName} · 후보 {item.eligibleCandidateCount}/{item.candidateCount} · 배포 {item.dispatchCount} · 견적 {item.quoteCount}</small></button>)}</div></section></div>
    {request&&<section className="matchingCandidates"><header><div><p>{request.categoryName} · {request.provinceName} {request.districtName}</p><h2>{request.title}</h2><span>공개 {dateTime(request.openedAt)} · 만료 {dateTime(request.expiresAt)}</span></div><button type="button" onClick={()=>void rematch()} disabled={rematching||request.status!=='OPEN'}>{rematching?'재매칭 중':'후보 재평가·배포'}</button></header><div className="matchingCandidateGuide">자동 매칭은 전문가 승인, 서비스 분야, 출장지역, 필수요건, 차단 관계, 긴급출동 가능 여부와 활동 종료 운영 잠금을 함께 검사합니다.</div>{candidateLoading?<p className="customerEmpty">후보 판정 결과를 불러오는 중입니다.</p>:candidates.length===0?<p className="customerEmpty">아직 평가된 후보가 없습니다. ‘후보 재평가·배포’를 실행해 주세요.</p>:<div className="matchingCandidateList">{candidates.map(item=><article key={item.providerId} className={item.status==='ELIGIBLE'?'eligible':'ineligible'}><div><strong>{item.businessName}</strong><span>{statusLabels[item.status]??item.status}</span></div><ul><li className={item.approvalMatch?'ok':''}>승인</li><li className={item.categoryMatch?'ok':''}>서비스</li><li className={item.areaMatch?'ok':''}>지역</li></ul><p>{item.reasonCode?reasonLabels[item.reasonCode]??item.reasonCode:'모든 조건 충족'}</p></article>)}</div>}</section>}
  </AdminLayout>
}
