import { useEffect, useState } from 'react'
import type { FormEvent } from 'react'
import { AdminLayout } from './AdminLayout'
import { createAdvertisingCampaign, createAdvertisingCreative, createManagedContent, getAdvertisingCampaign, getAdvertisingPlacements, getManagedContent, pauseAdvertisingCampaign, reviewAdvertisingCampaign, reviewManagedContent, searchAdvertisingCampaigns, searchManagedContents, updateAdvertisingCampaign, updateManagedContent } from './advertisingContentApi'
import type { AdvertisingCampaignDetail, AdvertisingCampaignList, AdvertisingPlacement, CampaignPayload, ContentPayload, ManagedContentDetail, ManagedContentList } from './advertisingContentTypes'
import { searchServiceCategories } from './serviceCategoryApi'
import type { AdminServiceCategoryListItem } from './serviceCategoryTypes'
import { getAdministrativeAreas } from '../requests/api'
import type { AdministrativeArea } from '../requests/types'

const contentTypes={NOTICE:'공지사항',FAQ:'자주 묻는 질문',SAFETY_GUIDE:'안전 가이드',CATEGORY_GUIDE:'서비스 안내',PRICE_REFERENCE:'가격 참고자료'} as const
const tabs=['광고 캠페인','노출 위치','공지사항','자주 묻는 질문','안전 가이드','서비스·가격 안내','게시 일정','성과','관리이력'] as const
const labels:Record<string,string>={ALL:'전체 사용자',CUSTOMER:'고객',PROVIDER:'공급자',DRAFT:'작성 중',ACTIVE:'운영 중',PAUSED:'중지',ARCHIVED:'보관',APPROVED:'승인',REJECTED:'반려',REVIEW_REQUIRED:'검수 필요',SCHEDULED:'게시 예정',EXPIRED:'게시 종료',PUBLISHED:'게시 중',ADVERTISEMENT:'광고',PROMOTION:'프로모션',BANNER:'배너',POPUP:'팝업'}
const nowLocal=()=>{const value=new Date(Date.now()-new Date().getTimezoneOffset()*60000);return value.toISOString().slice(0,16)}
const toIso=(value:string)=>new Date(value).toISOString()
const displayDate=(value?:string)=>value?new Date(value).toLocaleString('ko-KR'):'종료일 없음'

export function AdminAdvertisingContentPage({pathname}:{pathname:string}){
  const [tab,setTab]=useState<(typeof tabs)[number]>('광고 캠페인')
  return <AdminLayout pathname={pathname}><section className="adminPageHeading"><div><p>전사 노출과 운영 콘텐츠</p><h1>광고·프로모션·콘텐츠 관리</h1></div><span>노출 대상, 위치, 일정과 승인 이력을 한 곳에서 관리합니다.</span></section><div className="contentAdminTabs">{tabs.map(value=><button type="button" className={tab===value?'active':''} onClick={()=>setTab(value)} key={value}>{value}</button>)}</div>{tab==='광고 캠페인'?<CampaignManager/>:tab==='노출 위치'?<PlacementManager/>:tab==='공지사항'?<ContentManager type="NOTICE"/>:tab==='자주 묻는 질문'?<ContentManager type="FAQ"/>:tab==='안전 가이드'?<ContentManager type="SAFETY_GUIDE"/>:tab==='서비스·가격 안내'?<GuideContentManager/>:<ReadOnlyOverview tab={tab}/>}</AdminLayout>
}

function CampaignManager(){
  const [result,setResult]=useState<AdvertisingCampaignList|null>(null),[selected,setSelected]=useState<AdvertisingCampaignDetail|null>(null),[placements,setPlacements]=useState<AdvertisingPlacement[]>([])
  const [search,setSearch]=useState(''),[status,setStatus]=useState(''),[audience,setAudience]=useState(''),[placement,setPlacement]=useState(''),[categoryId,setCategoryId]=useState(''),[activeFrom,setActiveFrom]=useState(''),[activeTo,setActiveTo]=useState(''),[services,setServices]=useState<AdminServiceCategoryListItem[]>([]),[error,setError]=useState<string|null>(null),[notice,setNotice]=useState<string|null>(null),[editing,setEditing]=useState(false)
  const load=()=>searchAdvertisingCampaigns({search,status,audience,placement,categoryId,activeFrom,activeTo,page:1,pageSize:50}).then(setResult).catch(showError(setError))
  useEffect(()=>{searchAdvertisingCampaigns({search,status,audience,placement,categoryId,activeFrom,activeTo,page:1,pageSize:50}).then(setResult).catch(showError(setError))},[search,status,audience,placement,categoryId,activeFrom,activeTo])
  useEffect(()=>{getAdvertisingPlacements().then(setPlacements).catch(showError(setError));searchServiceCategories({search:'',majorId:'',middleId:'',status:'ACTIVE',feeAmount:'',feeStatus:'',feeEffectiveFrom:'',feeEffectiveTo:''}).then(value=>setServices(value.items)).catch(showError(setError))},[])
  const open=async(id:string)=>{try{setSelected(await getAdvertisingCampaign(id));setEditing(false)}catch(e){setError(message(e))}}
  const changed=(value:AdvertisingCampaignDetail)=>{setSelected(value);setNotice('처리가 완료되었습니다.');load()}
  return <div className="contentWorkspace"><section className="contentList"><header><div><h2>광고·프로모션 목록</h2><span>{result?.totalCount??0}건</span></div><button type="button" onClick={()=>{setSelected(null);setEditing(true)}}>새 캠페인</button></header><div className="contentFilters"><input aria-label="캠페인 검색" placeholder="캠페인명·소유자·제목" value={search} onChange={e=>setSearch(e.target.value)}/><select aria-label="캠페인 상태" value={status} onChange={e=>setStatus(e.target.value)}><option value="">전체 상태</option><option value="DRAFT">작성 중</option><option value="ACTIVE">운영 중</option><option value="PAUSED">중지</option></select><select aria-label="노출 대상" value={audience} onChange={e=>setAudience(e.target.value)}><option value="">전체 대상</option><option value="ALL">전체 사용자</option><option value="CUSTOMER">고객</option><option value="PROVIDER">공급자</option></select><select aria-label="노출 위치" value={placement} onChange={e=>setPlacement(e.target.value)}><option value="">전체 위치</option>{placements.map(v=><option value={v.code} key={v.code}>{v.name}</option>)}</select><select className="wide" aria-label="서비스 카테고리" value={categoryId} onChange={e=>setCategoryId(e.target.value)}><option value="">전체 서비스</option>{services.map(v=><option value={v.id} key={v.id}>{v.majorName} · {v.middleName} · {v.name}</option>)}</select><label>게시 시작<input type="date" value={activeFrom} onChange={e=>setActiveFrom(e.target.value)}/></label><label>게시 종료<input type="date" value={activeTo} onChange={e=>setActiveTo(e.target.value)}/></label></div>{result?.items.map(item=><button type="button" className={`contentListItem ${selected?.id===item.id?'active':''}`} onClick={()=>open(item.id)} key={item.id}><strong>{item.campaignName}</strong><span>{labels[item.campaignTypeCode]??item.campaignTypeCode} · {labels[item.audienceTypeCode]??item.audienceTypeCode}</span><small>{labels[item.publicationStatus]??item.publicationStatus} · 노출 {item.impressionCount.toLocaleString()} · 클릭 {item.clickCount.toLocaleString()}</small></button>)}{result&&!result.items.length&&<p className="customerEmpty">등록된 캠페인이 없습니다.</p>}</section><section className="contentEditor">{error&&<div className="adminError">{error}</div>}{notice&&<div className="adminNotice">{notice}</div>}{editing?<CampaignForm placements={placements} current={selected} onSaved={changed} onCancel={()=>setEditing(false)}/>:selected?<CampaignDetail value={selected} onEdit={()=>setEditing(true)} onChanged={changed} onError={setError}/>:<p className="customerEmpty">캠페인을 선택하거나 새 캠페인을 등록해 주세요.</p>}</section></div>
}

function CampaignForm({placements,current,onSaved,onCancel}:{placements:AdvertisingPlacement[];current:AdvertisingCampaignDetail|null;onSaved:(v:AdvertisingCampaignDetail)=>void;onCancel:()=>void}){
  const [name,setName]=useState(current?.campaignName??''),[type,setType]=useState(current?.campaignTypeCode??'BANNER'),[audience,setAudience]=useState(current?.audienceTypeCode??'ALL'),[owner,setOwner]=useState(current?.ownerDisplayName??''),[start,setStart]=useState(current?localValue(current.startAt):nowLocal()),[end,setEnd]=useState(current?.endAt?localValue(current.endAt):''),[priority,setPriority]=useState(current?.priority??0),[destinationType,setDestinationType]=useState(current?.destinationTypeCode??'NONE'),[destination,setDestination]=useState(current?.destinationValue??''),[slots,setSlots]=useState<string[]>(current?.placements.map(v=>v.code)??placements.filter(v=>v.isActive).slice(0,1).map(v=>v.code)),[saving,setSaving]=useState(false)
  const [services,setServices]=useState<AdminServiceCategoryListItem[]>([]),[areas,setAreas]=useState<AdministrativeArea[]>([]),[categoryIds,setCategoryIds]=useState<string[]>(current?.categories.map(v=>v.id)??[]),[areaIds,setAreaIds]=useState<string[]>(current?.areas.map(v=>v.id)??[])
  useEffect(()=>{searchServiceCategories({search:'',majorId:'',middleId:'',status:'ACTIVE',feeAmount:'',feeStatus:'',feeEffectiveFrom:'',feeEffectiveTo:''}).then(v=>setServices(v.items));getAdministrativeAreas().then(setAreas)},[])
  const submit=async(e:FormEvent)=>{e.preventDefault();setSaving(true);const payload:CampaignPayload={campaignName:name,campaignTypeCode:type,audienceTypeCode:audience,ownerTypeCode:'HEAD_OFFICE',ownerDisplayName:owner||null,startAt:toIso(start),endAt:end?toIso(end):null,priority,destinationTypeCode:destinationType,destinationValue:destinationType==='NONE'?null:destination||null,placementCodes:slots,categoryIds,areaIds};try{onSaved(current?await updateAdvertisingCampaign(current.id,payload):await createAdvertisingCampaign(payload));onCancel()}catch(e){alert(message(e))}finally{setSaving(false)}}
  return <form className="contentForm" onSubmit={submit}><h2>{current?'캠페인 수정':'새 캠페인 등록'}</h2><div className="contentFormGrid"><label>캠페인명<input required maxLength={200} value={name} onChange={e=>setName(e.target.value)}/></label><label>유형<select value={type} onChange={e=>setType(e.target.value)}><option value="ADVERTISEMENT">광고</option><option value="PROMOTION">프로모션</option><option value="BANNER">배너</option><option value="POPUP">팝업</option></select></label><label>노출 대상<select value={audience} onChange={e=>setAudience(e.target.value)}><option value="ALL">전체 사용자</option><option value="CUSTOMER">고객</option><option value="PROVIDER">공급자</option></select></label><label>소유자 표시명<input value={owner} onChange={e=>setOwner(e.target.value)} placeholder="본사 또는 제휴사명"/></label><label>시작일시<input type="datetime-local" required value={start} onChange={e=>setStart(e.target.value)}/></label><label>종료일시<input type="datetime-local" value={end} onChange={e=>setEnd(e.target.value)}/></label><label>우선순위<input type="number" min="0" value={priority} onChange={e=>setPriority(Number(e.target.value))}/></label><label>연결 방식<select value={destinationType} onChange={e=>setDestinationType(e.target.value)}><option value="NONE">연결 없음</option><option value="INTERNAL_PATH">서비스 내부 경로</option><option value="EXTERNAL_URL">외부 HTTPS 주소</option></select></label>{destinationType!=='NONE'&&<label className="wide">연결 주소<input required value={destination} onChange={e=>setDestination(e.target.value)} placeholder={destinationType==='INTERNAL_PATH'?'/customer/requests':'https://...'}/></label>}<fieldset className="wide"><legend>노출 위치</legend>{placements.map(slot=><label className="check" key={slot.code}><input type="checkbox" checked={slots.includes(slot.code)} onChange={e=>setSlots(v=>e.target.checked?[...v,slot.code]:v.filter(x=>x!==slot.code))}/>{slot.name}</label>)}</fieldset><label>서비스 타겟(미선택 시 전체)<select multiple value={categoryIds} onChange={e=>setCategoryIds(Array.from(e.target.selectedOptions,v=>v.value))}>{services.map(v=><option value={v.id} key={v.id}>{v.majorName} · {v.middleName} · {v.name}</option>)}</select></label><label>지역 타겟(미선택 시 전국)<select multiple value={areaIds} onChange={e=>setAreaIds(Array.from(e.target.selectedOptions,v=>v.value))}>{areas.map(v=><option value={v.id} key={v.id}>{v.parentName?`${v.parentName} `:''}{v.name}</option>)}</select></label></div><div className="contentActions"><button type="button" onClick={onCancel}>취소</button><button disabled={saving||!slots.length}>{saving?'저장 중':'저장'}</button></div></form>
}

function CampaignDetail({value,onEdit,onChanged,onError}:{value:AdvertisingCampaignDetail;onEdit:()=>void;onChanged:(v:AdvertisingCampaignDetail)=>void;onError:(v:string)=>void}){
  const [creativeTitle,setCreativeTitle]=useState(''),[reason,setReason]=useState('')
  const action=async(kind:'APPROVE'|'REJECT'|'PAUSE')=>{try{onChanged(kind==='PAUSE'?await pauseAdvertisingCampaign(value.id,reason):await reviewAdvertisingCampaign(value.id,kind,reason||null));setReason('')}catch(e){onError(message(e))}}
  const addCreative=async(e:FormEvent)=>{e.preventDefault();try{await createAdvertisingCreative(value.id,{title:creativeTitle,subtitle:null,bodyText:null,fileId:null,altText:null,buttonText:null,destinationTypeCode:null,destinationValue:null,displayOrder:value.creatives.length,statusCode:'ACTIVE'});onChanged(await getAdvertisingCampaign(value.id));setCreativeTitle('')}catch(e){onError(message(e))}}
  return <div className="contentDetail"><header><div><span className="customerStatus">{labels[value.publicationStatus]??value.publicationStatus}</span><h2>{value.campaignName}</h2><p>{labels[value.campaignTypeCode]} · {labels[value.audienceTypeCode]} · {value.placements.map(v=>v.name).join(', ')}</p></div><button onClick={onEdit}>기본정보 수정</button></header><dl className="contentSummary"><div><dt>게시 기간</dt><dd>{displayDate(value.startAt)}<br/>{displayDate(value.endAt)}</dd></div><div><dt>검수 상태</dt><dd>{labels[value.reviewStatusCode]??value.reviewStatusCode}</dd></div><div><dt>성과</dt><dd>노출 {value.metrics.impressions.toLocaleString()} · 클릭 {value.metrics.clicks.toLocaleString()}</dd></div></dl><section><h3>배너·Creative</h3>{value.creatives.map(v=><article className="creativeCard" key={v.id}><strong>{v.title}</strong><span>{v.statusCode==='ACTIVE'?'사용 중':'사용 안 함'} · 표시순서 {v.displayOrder}</span></article>)}<form className="creativeAdd" onSubmit={addCreative}><input required value={creativeTitle} onChange={e=>setCreativeTitle(e.target.value)} placeholder="Creative 제목"/><button>추가</button></form><p className="contentHelp">이미지는 안전한 파일 저장 구조가 연결된 경우에만 API에서 지정할 수 있습니다. 임의 HTML은 실행하지 않습니다.</p></section><section><h3>검수·운영</h3><textarea value={reason} onChange={e=>setReason(e.target.value)} placeholder="반려 또는 중지 사유"/><div className="contentActions"><button onClick={()=>action('REJECT')} className="danger">반려</button><button onClick={()=>action('PAUSE')} className="warning">중지</button><button onClick={()=>action('APPROVE')}>승인</button></div></section><section><h3>변경 이력</h3>{value.history.map((v,i)=><p className="historyRow" key={`${v.occurredAt}-${i}`}><strong>{v.actionCode}</strong><span>{displayDate(v.occurredAt)}{v.reason?` · ${v.reason}`:''}</span></p>)}</section></div>
}

function PlacementManager(){const [items,setItems]=useState<AdvertisingPlacement[]>([]);useEffect(()=>{getAdvertisingPlacements().then(setItems)},[]);return <section className="contentSimplePanel"><h2>노출 위치</h2><p>현재 실제 화면 경로가 확인된 위치만 사용합니다. 새로운 위치는 화면 구현과 함께 검토해야 합니다.</p>{items.map(v=><article className="placementCard" key={v.id}><div><strong>{v.name}</strong><span>{v.description}</span></div><code>{v.code}</code><small>{v.routeHint}</small></article>)}</section>}

function GuideContentManager(){const [type,setType]=useState<'CATEGORY_GUIDE'|'PRICE_REFERENCE'>('CATEGORY_GUIDE');return <><div className="contentSubTabs"><button className={type==='CATEGORY_GUIDE'?'active':''} onClick={()=>setType('CATEGORY_GUIDE')}>서비스 안내</button><button className={type==='PRICE_REFERENCE'?'active':''} onClick={()=>setType('PRICE_REFERENCE')}>가격 참고자료</button></div><ContentManager key={type} type={type}/></>}

function ContentManager({type}:{type:keyof typeof contentTypes}){
  const [result,setResult]=useState<ManagedContentList|null>(null),[selected,setSelected]=useState<ManagedContentDetail|null>(null),[editing,setEditing]=useState(false),[error,setError]=useState<string|null>(null)
  const load=()=>searchManagedContents({type,page:1,pageSize:50}).then(setResult).catch(showError(setError));useEffect(()=>{searchManagedContents({type,page:1,pageSize:50}).then(setResult).catch(showError(setError))},[type])
  const open=async(id:string)=>{try{setSelected(await getManagedContent(id));setEditing(false)}catch(e){setError(message(e))}}
  const changed=(value:ManagedContentDetail)=>{setSelected(value);setEditing(false);load()}
  return <div className="contentWorkspace"><section className="contentList"><header><div><h2>{contentTypes[type]}</h2><span>{result?.totalCount??0}건</span></div><button onClick={()=>{setSelected(null);setEditing(true)}}>새 콘텐츠</button></header>{result?.items.map(v=><button className={`contentListItem ${selected?.id===v.id?'active':''}`} onClick={()=>open(v.id)} key={v.id}><strong>{v.title}</strong><span>{labels[v.audienceTypeCode]} · {labels[v.publicationStatus]??v.publicationStatus}</span><small>버전 {v.currentVersionNo} · {displayDate(v.startAt)}</small></button>)}{result&&!result.items.length&&<p className="customerEmpty">등록된 콘텐츠가 없습니다.</p>}</section><section className="contentEditor">{error&&<div className="adminError">{error}</div>}{editing?<ContentForm type={type} current={selected} onSaved={changed} onCancel={()=>setEditing(false)}/>:selected?<ContentDetail value={selected} onEdit={()=>setEditing(true)} onChanged={changed} onError={setError}/>:<p className="customerEmpty">콘텐츠를 선택하거나 새로 등록해 주세요.</p>}</section></div>
}

function ContentForm({type,current,onSaved,onCancel}:{type:keyof typeof contentTypes;current:ManagedContentDetail|null;onSaved:(v:ManagedContentDetail)=>void;onCancel:()=>void}){
  const version=current?.currentVersion,[title,setTitle]=useState(version?.title??''),[body,setBody]=useState(version?.bodyText??''),[question,setQuestion]=useState(version?.questionText??''),[answer,setAnswer]=useState(version?.answerText??''),[audience,setAudience]=useState(current?.audienceTypeCode??'ALL'),[start,setStart]=useState(current?localValue(current.startAt):nowLocal()),[end,setEnd]=useState(current?.endAt?localValue(current.endAt):''),[reason,setReason]=useState('')
  const [services,setServices]=useState<AdminServiceCategoryListItem[]>([]),[areas,setAreas]=useState<AdministrativeArea[]>([]),[categoryIds,setCategoryIds]=useState<string[]>(current?.categories.map(v=>v.id)??[]),[areaIds,setAreaIds]=useState<string[]>(current?.areas.map(v=>v.id)??[])
  useEffect(()=>{searchServiceCategories({search:'',majorId:'',middleId:'',status:'ACTIVE',feeAmount:'',feeStatus:'',feeEffectiveFrom:'',feeEffectiveTo:''}).then(v=>setServices(v.items));getAdministrativeAreas().then(setAreas)},[])
  const submit=async(e:FormEvent)=>{e.preventDefault();const payload:ContentPayload={contentTypeCode:type,audienceTypeCode:audience,title,bodyText:type==='FAQ'?null:body,questionText:type==='FAQ'?question:null,answerText:type==='FAQ'?answer:null,fileId:null,linkText:null,destinationTypeCode:'NONE',destinationValue:null,startAt:toIso(start),endAt:end?toIso(end):null,displayOrder:current?.displayOrder??0,categoryIds,areaIds,changeReason:reason||null};try{onSaved(current?await updateManagedContent(current.id,payload):await createManagedContent(payload))}catch(e){alert(message(e))}}
  return <form className="contentForm" onSubmit={submit}><h2>{current?`${contentTypes[type]} 수정`:`${contentTypes[type]} 등록`}</h2><div className="contentFormGrid"><label className="wide">제목<input required value={title} onChange={e=>setTitle(e.target.value)}/></label><label>노출 대상<select value={audience} onChange={e=>setAudience(e.target.value)}><option value="ALL">전체 사용자</option><option value="CUSTOMER">고객</option><option value="PROVIDER">공급자</option></select></label><label>시작일시<input type="datetime-local" required value={start} onChange={e=>setStart(e.target.value)}/></label><label>종료일시<input type="datetime-local" value={end} onChange={e=>setEnd(e.target.value)}/></label>{type==='FAQ'?<><label className="wide">질문<textarea required value={question} onChange={e=>setQuestion(e.target.value)}/></label><label className="wide">답변<textarea required value={answer} onChange={e=>setAnswer(e.target.value)}/></label></>:<label className="wide">본문<textarea required value={body} onChange={e=>setBody(e.target.value)}/></label>}<label>관련 서비스(미선택 시 전체)<select multiple value={categoryIds} onChange={e=>setCategoryIds(Array.from(e.target.selectedOptions,v=>v.value))}>{services.map(v=><option value={v.id} key={v.id}>{v.majorName} · {v.middleName} · {v.name}</option>)}</select></label><label>관련 지역(미선택 시 전국)<select multiple value={areaIds} onChange={e=>setAreaIds(Array.from(e.target.selectedOptions,v=>v.value))}>{areas.map(v=><option value={v.id} key={v.id}>{v.parentName?`${v.parentName} `:''}{v.name}</option>)}</select></label>{current&&<label className="wide">변경 사유<input value={reason} onChange={e=>setReason(e.target.value)} placeholder="버전 이력에 남길 변경 사유"/></label>}</div><p className="contentHelp">본문은 일반 텍스트로 저장·표시되며 임의 HTML이나 스크립트를 실행하지 않습니다.</p><div className="contentActions"><button type="button" onClick={onCancel}>취소</button><button>저장</button></div></form>
}

function ContentDetail({value,onEdit,onChanged,onError}:{value:ManagedContentDetail;onEdit:()=>void;onChanged:(v:ManagedContentDetail)=>void;onError:(v:string)=>void}){const [reason,setReason]=useState('');const review=async(action:string)=>{try{onChanged(await reviewManagedContent(value.id,action,reason||null))}catch(e){onError(message(e))}};return <div className="contentDetail"><header><div><span className="customerStatus">{labels[value.publicationStatus]??value.publicationStatus}</span><h2>{value.currentVersion.title}</h2><p>{contentTypes[value.contentTypeCode as keyof typeof contentTypes]} · {labels[value.audienceTypeCode]}</p></div><button onClick={onEdit}>새 버전 작성</button></header><section className="contentPreview"><h3>관리자 미리보기</h3>{value.currentVersion.questionText&&<strong>{value.currentVersion.questionText}</strong>}<p>{value.currentVersion.answerText??value.currentVersion.bodyText}</p></section><section><h3>검수·승인</h3><textarea value={reason} onChange={e=>setReason(e.target.value)} placeholder="반려 사유"/><div className="contentActions"><button className="danger" onClick={()=>review('REJECT')}>반려</button><button onClick={()=>review('APPROVE')}>승인</button></div></section><section><h3>버전 이력</h3>{value.versions.map(v=><p className="historyRow" key={v.id}><strong>버전 {v.versionNo} · {v.title}</strong><span>{displayDate(v.createdAt)}{v.changeReason?` · ${v.changeReason}`:''}</span></p>)}</section></div>}

function ReadOnlyOverview({tab}:{tab:string}){return <section className="contentSimplePanel"><h2>{tab}</h2><p>{tab==='성과'?'캠페인별 노출·클릭 수는 광고 캠페인 목록과 상세에서 확인할 수 있습니다. 비용·전환율·수익률은 과금 기준이 확정되지 않아 집계하지 않습니다.':tab==='게시 일정'?'승인된 캠페인과 콘텐츠는 설정한 시작·종료일시에 따라 자동으로 노출 또는 만료됩니다.':'각 캠페인과 콘텐츠 상세에서 생성, 수정, 승인, 반려, 중지 이력을 확인할 수 있습니다.'}</p></section>}
function localValue(value:string){const date=new Date(value);return new Date(date.getTime()-date.getTimezoneOffset()*60000).toISOString().slice(0,16)}
function message(error:unknown){return error instanceof Error?error.message:'요청을 처리하지 못했습니다.'}
function showError(setter:(value:string)=>void){return(error:unknown)=>setter(message(error))}
