import { useEffect, useMemo, useState } from 'react'
import type { ReactNode } from 'react'
import { navigate } from '../auth/routing'
import { AdminLayout } from './AdminLayout'
import { getSettlementOperationsDashboard, getUnifiedSettlementLedger } from './settlementOperationsApi'
import type { SettlementOperationsDashboard, UnifiedLedger } from './settlementOperationsTypes'

const tabs=[
  ['summary','통합 현황'],['quote','견적 수수료'],['subscription','구독 결제'],['settlements','월별 정산'],
  ['payouts','은행 송금'],['advertising','광고비'],['refunds','환불·조정'],['ledger','전체 원장·감사'],
] as const
type Tab=(typeof tabs)[number][0]
const statusLabels:Record<string,string>={RESERVED:'예약',CAPTURED:'차감 완료',RELEASED:'예약 해제',REQUESTED:'요청',AUTHORIZED:'승인',COMPLETED:'완료',PAID:'지급 완료',FAILED:'실패',CANCELLED:'취소',PARTIALLY_REFUNDED:'부분 환불',REFUNDED:'환불 완료',DRAFT:'작성 중',PREPARED:'정산 준비',APPROVED:'승인',PUBLISHED:'게시 중',SUBMITTED:'검토 대기',REJECTED:'반려',PROCESSING:'처리 중',ADJUSTMENT:'조정',REFUND:'환불',PAYMENT:'결제',USE:'차감',RESERVE:'예약',RELEASE:'해제',RESTORE:'복원',CHARGE:'결제',AUDIT:'감사',WALLET:'이용료 잔액',SUBSCRIPTION:'정기구독'}
const money=(value:number|null|undefined,currency='KRW')=>value==null?'-':new Intl.NumberFormat('ko-KR',{style:'currency',currency,maximumFractionDigits:0}).format(value)
const date=(value:string|null|undefined)=>value?new Intl.DateTimeFormat('ko-KR',{dateStyle:'medium',timeStyle:'short'}).format(new Date(value)):'-'
const label=(value:string)=>statusLabels[value]??value

export function AdminSettlementOperationsPage({pathname}:{pathname:string}){
  const[tab,setTab]=useState<Tab>('summary'),[dashboard,setDashboard]=useState<SettlementOperationsDashboard|null>(null)
  const[ledger,setLedger]=useState<UnifiedLedger|null>(null),[loading,setLoading]=useState(true),[error,setError]=useState('')
  const[search,setSearch]=useState(''),[status,setStatus]=useState(''),[source,setSource]=useState(''),[from,setFrom]=useState(''),[to,setTo]=useState(''),[page,setPage]=useState(1)
  const load=()=>{setLoading(true);setError('');return getSettlementOperationsDashboard().then(setDashboard).catch((reason:unknown)=>setError(reason instanceof Error?reason.message:'결제·정산 정보를 불러오지 못했습니다.')).finally(()=>setLoading(false))}
  const loadLedger=(nextPage=page)=>{setLoading(true);setError('');return getUnifiedSettlementLedger({source,search,from,to,page:nextPage}).then(value=>{setLedger(value);setPage(nextPage)}).catch((reason:unknown)=>setError(reason instanceof Error?reason.message:'원장과 감사이력을 불러오지 못했습니다.')).finally(()=>setLoading(false))}
  useEffect(()=>{void load()},[])
  useEffect(()=>{if(tab==='ledger')void getUnifiedSettlementLedger({source:'',search:'',from:'',to:'',page:1}).then(value=>{setLedger(value);setPage(1)}).catch((reason:unknown)=>setError(reason instanceof Error?reason.message:'원장과 감사이력을 불러오지 못했습니다.')).finally(()=>setLoading(false))},[tab])
  const matches=(...values:Array<string|null|undefined>)=>!search.trim()||values.some(value=>value?.toLowerCase().includes(search.trim().toLowerCase()))
  const statusMatch=(value:string)=>!status||value===status
  const counts=useMemo(()=>dashboard?{quote:dashboard.quoteFees.length,subscription:dashboard.subscriptionPayments.length,settlements:dashboard.monthlySettlements.length,payouts:dashboard.payouts.length,advertising:dashboard.advertisingFees.length,refunds:dashboard.refundAdjustments.length}:null,[dashboard])
  return <AdminLayout pathname={pathname}>
    <section className="adminPageHeading settlementHeading"><div><p>본사 재무 운영</p><h1>결제·정산 통합 관리</h1></div><div><span>{dashboard?`${date(dashboard.generatedAt)} 기준`:'실제 원장과 업무 상태를 통합 조회합니다.'}</span><button type="button" onClick={()=>tab==='ledger'?void loadLedger():void load()}>새로고침</button></div></section>
    <section className="settlementScopeNotice"><strong>업무 범위 안내</strong><p>일반 서비스 대금은 고객·전문가 직접 결제이므로 본사 정산에 포함하지 않습니다. 이 화면은 전문가 이용료 잔액의 수수료, 정기구독 결제·정산, 광고비, 환불·조정 및 감사 이력을 통합합니다.</p></section>
    {error&&<div className="adminError" role="alert">{error}</div>}
    <div className="settlementTabs" role="tablist">{tabs.map(([key,text])=><button key={key} type="button" role="tab" aria-selected={tab===key} className={tab===key?'active':''} onClick={()=>{setTab(key);setSearch('');setStatus('')}}>{text}{key!=='summary'&&key!=='ledger'&&counts&&<small>{counts[key]}</small>}</button>)}</div>
    {loading&&!dashboard?<section className="settlementLoading">결제·정산 원장을 집계하고 있습니다…</section>:dashboard&&<>
      {tab==='summary'&&<Summary dashboard={dashboard} onMove={setTab}/>} 
      {tab!=='summary'&&tab!=='ledger'&&<div className="settlementToolbar"><label>검색<input value={search} onChange={event=>setSearch(event.target.value)} placeholder="전문가·캠페인·상태 검색"/></label><label>상태<select value={status} onChange={event=>setStatus(event.target.value)}><option value="">전체 상태</option>{['RESERVED','CAPTURED','RELEASED','REQUESTED','FAILED','DRAFT','PREPARED','APPROVED','COMPLETED','PAID','PUBLISHED','REFUNDED'].map(value=><option key={value} value={value}>{label(value)}</option>)}</select></label><button type="button" onClick={()=>{setSearch('');setStatus('')}}>초기화</button></div>}
      {tab==='quote'&&<OperationSection title="견적 수수료 예약·차감 현황" description="견적 제출 시 예약하고, 미채택·만료 시 해제하며, 채택 시 실제 차감합니다." action="이용료 업무 열기" path="/admin/credits"><Table headers={['예약일','전문가','견적번호','금액','상태','차감·해제일','해제 사유']} rows={dashboard.quoteFees.filter(x=>matches(x.providerName,x.quoteId,x.statusCode)&&statusMatch(x.statusCode)).map(x=>[date(x.reservedAt),x.providerName,<Code key={x.id}>{x.quoteId}</Code>,money(x.amount,x.currencyCode),<Status key={x.id} value={x.statusCode}/>,date(x.capturedAt??x.releasedAt),x.releaseReasonCode??'-'])}/></OperationSection>}
      {tab==='subscription'&&<OperationSection title="정기구독 결제 및 결제 실패" description="결제 요청, 성공·실패, 실패 사유와 청구기간을 확인합니다." action="구독 결제 업무 열기" path="/admin/subscriptions"><Table headers={['요청일','전문가','청구기간','요청금액','상태','완료일','실패 사유']} rows={dashboard.subscriptionPayments.filter(x=>matches(x.providerName,x.contractId,x.statusCode,x.failureReason)&&statusMatch(x.statusCode)).map(x=>[date(x.requestedAt),x.providerName,`${x.billingPeriodStart} ~ ${x.billingPeriodEnd}`,money(x.requestedAmount,x.currencyCode),<Status key={x.id} value={x.statusCode}/>,date(x.completedAt),x.failureReason??'-'])}/></OperationSection>}
      {tab==='settlements'&&<OperationSection title="월별 전문가 정산" description="완료 회차 총액, 본사 수수료, 환불·조정과 전문가 순지급액을 확인합니다." action="정산 생성·승인 열기" path="/admin/subscriptions"><Table headers={['정산월','전문가','건수','서비스 총액','수수료','환불·조정','순지급액','상태']} rows={dashboard.monthlySettlements.filter(x=>matches(x.providerName,x.statusCode)&&statusMatch(x.statusCode)).map(x=>[`${x.year}년 ${x.month}월`,x.providerName,`${x.itemCount}건`,money(x.grossTotal),money(x.feeTotal),money(x.adjustmentTotal),<strong key={x.id}>{money(x.netTotal)}</strong>,<Status key={x.id} value={x.statusCode}/>])}/></OperationSection>}
      {tab==='payouts'&&<OperationSection title="은행 송금 및 지급 완료" description="승인된 정산액을 실제 송금한 뒤 송금 확인번호를 기록하고 지급 완료 처리합니다." action="송금·지급 처리 열기" path="/admin/subscriptions"><Table headers={['요청일','전문가','요청금액','승인금액','상태','완료일','송금 확인번호']} rows={dashboard.payouts.filter(x=>matches(x.providerName,x.statusCode,x.bankTransferReference)&&statusMatch(x.statusCode)).map(x=>[date(x.requestedAt),x.providerName,money(x.requestedAmount),money(x.approvedAmount),<Status key={x.id} value={x.statusCode}/>,date(x.completedAt),x.bankTransferReference??'미입력'])}/></OperationSection>}
      {tab==='advertising'&&<OperationSection title="광고비 예약·차감" description="광고 신청 시 예약하고 반려·취소 시 해제하며 게시 시 실제 차감합니다." action="전문가 캠페인 관리 열기" path="/admin/provider-campaigns"><Table headers={['신청일','전문가','캠페인','광고비','심사·게시 상태','광고비 상태','자동갱신','다음 갱신']} rows={dashboard.advertisingFees.filter(x=>matches(x.providerName,x.campaignName,x.statusCode,x.feeStatusCode)&&(statusMatch(x.statusCode)||statusMatch(x.feeStatusCode))).map(x=>[date(x.submittedAt),x.providerName,x.campaignName,money(x.feeAmount,x.currencyCode),<Status key={`a-${x.id}`} value={x.statusCode}/>,<Status key={`f-${x.id}`} value={x.feeStatusCode}/>,x.autoRenewEnabled?'사용':'미사용',date(x.nextRenewalAt)])}/></OperationSection>}
      {tab==='refunds'&&<OperationSection title="환불·조정" description="전문가 선결제 이용료와 정기구독 환불·조정을 한곳에서 확인하고 해당 업무 화면에서 승인·완료합니다." action="환불·조정 처리 열기" path="/admin/subscriptions"><Table headers={['요청일','구분','대상','유형','요청금액','승인금액','상태','사유']} rows={dashboard.refundAdjustments.filter(x=>matches(x.partyName,x.sourceCode,x.typeCode,x.statusCode,x.reason)&&statusMatch(x.statusCode)).map(x=>[date(x.requestedAt),label(x.sourceCode),x.partyName,label(x.typeCode),money(x.requestedAmount),money(x.approvedAmount),<Status key={x.id} value={x.statusCode}/>,x.reason])}/></OperationSection>}
    </>}
    {tab==='ledger'&&<Ledger ledger={ledger} loading={loading} source={source} setSource={setSource} search={search} setSearch={setSearch} from={from} setFrom={setFrom} to={to} setTo={setTo} load={loadLedger}/>} 
  </AdminLayout>
}

function Summary({dashboard,onMove}:{dashboard:SettlementOperationsDashboard;onMove:(tab:Tab)=>void}){const s=dashboard.summary;const cards:[string,string,string,Tab][]=[['이용료 잔액 사용 가능',money(s.walletAvailableBalance),'전체 전문가 가용잔액','quote'],['이용료 잔액 예약',money(s.walletReservedBalance),`견적 ${s.reservedQuoteFeeCount}건 포함`,'quote'],['견적 수수료 차감',money(s.capturedQuoteFeeAmount),'채택 후 실제 차감 누계','quote'],['구독 결제 완료',money(s.completedSubscriptionPaymentAmount),`실패 ${s.failedSubscriptionPaymentCount}건`,'subscription'],['정산 승인·대기',money(s.pendingMonthlySettlementAmount),`${s.pendingMonthlySettlementCount}건`,'settlements'],['송금 대기',money(s.pendingPayoutAmount),`${s.pendingPayoutCount}건`,'payouts'],['예약 광고비',money(s.pendingAdvertisingFeeAmount),`${s.pendingAdvertisingFeeCount}건`,'advertising'],['환불·조정 대기',money(s.openRefundAdjustmentAmount),`${s.openRefundAdjustmentCount}건`,'refunds']];return <><section className="settlementSummaryGrid">{cards.map(([title,value,note,target])=><button type="button" key={title} onClick={()=>onMove(target)}><span>{title}</span><strong>{value}</strong><small>{note}</small></button>)}</section><section className="settlementActionQueue"><header><div><span>ACTION REQUIRED</span><h2>지금 확인할 업무</h2></div><p>건수를 누르면 해당 현황으로 이동합니다.</p></header><div><button onClick={()=>onMove('subscription')}><b>{s.failedSubscriptionPaymentCount}건</b><span>구독 결제 실패</span></button><button onClick={()=>onMove('settlements')}><b>{s.pendingMonthlySettlementCount}건</b><span>월 정산 승인·대기</span></button><button onClick={()=>onMove('payouts')}><b>{s.pendingPayoutCount}건</b><span>은행 송금 대기</span></button><button onClick={()=>onMove('refunds')}><b>{s.openRefundAdjustmentCount}건</b><span>환불·조정 처리 대기</span></button></div></section></>}
function OperationSection({title,description,action,path,children}:{title:string;description:string;action:string;path:string;children:ReactNode}){return <section className="settlementPanel"><header><div><h2>{title}</h2><p>{description}</p></div><button type="button" onClick={()=>navigate(path)}>{action}</button></header>{children}</section>}
function Table({headers,rows}:{headers:string[];rows:ReactNode[][]}){return rows.length?<div className="settlementTableWrap"><table className="settlementTable"><thead><tr>{headers.map(x=><th key={x}>{x}</th>)}</tr></thead><tbody>{rows.map((row,index)=><tr key={index}>{row.map((value,column)=><td key={column}>{value}</td>)}</tr>)}</tbody></table></div>:<div className="settlementEmpty"><strong>조건에 맞는 내역이 없습니다.</strong><p>실제 거래가 발생하면 이곳에서 확인할 수 있습니다.</p></div>}
function Status({value}:{value:string}){return <span className={`settlementStatus s-${value.toLowerCase()}`}>{label(value)}</span>}
function Code({children}:{children:string}){return <code title={children}>{children.slice(0,8).toUpperCase()}</code>}
function Ledger({ledger,loading,source,setSource,search,setSearch,from,setFrom,to,setTo,load}:{ledger:UnifiedLedger|null;loading:boolean;source:string;setSource:(v:string)=>void;search:string;setSearch:(v:string)=>void;from:string;setFrom:(v:string)=>void;to:string;setTo:(v:string)=>void;load:(page?:number)=>Promise<void>}){const pages=Math.max(1,Math.ceil((ledger?.totalCount??0)/(ledger?.pageSize??30)));return <section className="settlementPanel"><header><div><h2>전체 원장 및 감사 이력</h2><p>이용료 원장, 정기구독 결제 원장과 관리자 감사로그는 수정하지 않고 통합 조회합니다.</p></div></header><div className="settlementLedgerFilters"><label>구분<select value={source} onChange={e=>setSource(e.target.value)}><option value="">전체</option><option value="WALLET">이용료 원장</option><option value="SUBSCRIPTION">정기구독 원장</option><option value="AUDIT">감사 이력</option></select></label><label className="wide">검색<input value={search} onChange={e=>setSearch(e.target.value)} placeholder="전문가·업무코드·참조번호·사유"/></label><label>시작일<input type="date" value={from} onChange={e=>setFrom(e.target.value)}/></label><label>종료일<input type="date" value={to} onChange={e=>setTo(e.target.value)}/></label><button type="button" onClick={()=>void load(1)}>조회</button></div>{loading&&!ledger?<div className="settlementLoading">원장을 조회하고 있습니다…</div>:<><Table headers={['발생일시','구분','대상','업무·원장유형','금액','참조','결과','사유']} rows={(ledger?.items??[]).map(x=>[date(x.occurredAt),label(x.sourceCode),x.partyName,label(x.entryTypeCode),x.amount==null?'-':money(x.amount,x.currencyCode),x.referenceId?<Code key={x.id??x.occurredAt}>{x.referenceId}</Code>:x.referenceType??'-',<Status key={`${x.sourceCode}-${x.id}-${x.occurredAt}`} value={x.statusCode}/>,x.reason??'-'])}/><div className="settlementPager"><button disabled={(ledger?.page??1)<=1} onClick={()=>void load((ledger?.page??1)-1)}>이전</button><span>{(ledger?.page??1).toLocaleString('ko-KR')} / {pages.toLocaleString('ko-KR')} · 총 {(ledger?.totalCount??0).toLocaleString('ko-KR')}건</span><button disabled={(ledger?.page??1)>=pages} onClick={()=>void load((ledger?.page??1)+1)}>다음</button></div></>}</section>}
