import { useCallback, useEffect, useState } from 'react'
import { navigate } from '../auth/routing'
import { AdminLayout } from './AdminLayout'
import { assessRetention, beginMfa, confirmMfa, createSecurityAccount, getAuditLogs, getSecurityAccounts, getSystemStatus, reauthenticate, retryOutbox, updateRetention, updateSecurityAccount } from './systemApi'
import type { AuditFilters, AuditLogResponse, RetentionPolicyItem, SecurityAccount, SystemStatusResponse } from './systemTypes'
import { soodalConfirm, soodalPrompt } from '../components/soodalDialog'

const tabs = ['운영현황', '감사로그', '관리자 계정', '설정·보안'] as const
const dateTime = (value: string | null) => value ? new Intl.DateTimeFormat('ko-KR', { dateStyle: 'short', timeStyle: 'short' }).format(new Date(value)) : '-'

export function AdminSystemPage({ pathname }: { pathname: string }) {
  const [tab, setTab] = useState<(typeof tabs)[number]>('운영현황')
  const [status, setStatus] = useState<SystemStatusResponse | null>(null)
  const [audit, setAudit] = useState<AuditLogResponse | null>(null)
  const [filters, setFilters] = useState<AuditFilters>({ page: 1 })
  const [error, setError] = useState('')
  const [reauthToken, setReauthToken] = useState('')
  const loadStatus = useCallback(async () => { try { setError(''); setStatus(await getSystemStatus()) } catch (e) { setError(e instanceof Error ? e.message : '시스템 상태를 불러오지 못했습니다.') } }, [])
  const loadAudit = useCallback(async () => { try { setError(''); setAudit(await getAuditLogs(filters)) } catch (e) { setError(e instanceof Error ? e.message : '감사로그를 불러오지 못했습니다.') } }, [filters])
  useEffect(() => { void loadStatus() }, [loadStatus])
  useEffect(() => { void loadAudit() }, [loadAudit])
  const setFilter = (key: keyof AuditFilters, value: string | number | undefined) => setFilters(current => ({ ...current, [key]: value || undefined, page: key === 'page' ? Number(value) : 1 }))

  return <AdminLayout pathname={pathname}>
    <section className="adminPageHeading"><div><p>운영·보안 기반</p><h1>감사·보안·시스템 관리</h1></div><span>읽기 전용 운영상태와 append-only 감사기록을 확인합니다.</span></section>
    {error && <div className="adminError" role="alert">{error}</div>}
    <ReauthPanel onReady={setReauthToken} />
    <nav className="systemTabs">{tabs.map(value => <button type="button" className={tab === value ? 'active' : ''} onClick={() => setTab(value)} key={value}>{value}</button>)}</nav>
    {tab === '운영현황' && <Operations status={status} reload={loadStatus} reauthToken={reauthToken} reportError={setError} />}
    {tab === '감사로그' && <AuditPanel value={audit} filters={filters} setFilter={setFilter} />}
    {tab === '관리자 계정' && <Accounts reauthToken={reauthToken} reportError={setError} />}
    {tab === '설정·보안' && <Security status={status} reauthToken={reauthToken} reload={loadStatus} reportError={setError} />}
  </AdminLayout>
}

function ReauthPanel({onReady}:{onReady:(token:string)=>void}){const[password,setPassword]=useState('');const[mfa,setMfa]=useState('');const[message,setMessage]=useState('');return <section className="systemPanel adminReauth"><div><strong>중요 작업 본인 재확인</strong><small>확인 후 10분 동안 계정·재처리·보존정책 작업을 할 수 있습니다.</small></div><input type="password" placeholder="현재 비밀번호" value={password} onChange={e=>setPassword(e.target.value)}/><input inputMode="numeric" maxLength={6} placeholder="MFA 6자리(설정 시)" value={mfa} onChange={e=>setMfa(e.target.value.replace(/\D/g,''))}/><button type="button" disabled={!password} onClick={async()=>{try{const result=await reauthenticate(password,mfa);onReady(result.token);setPassword('');setMfa('');setMessage(`확인 완료 · ${dateTime(result.expiresAt)}까지`)}catch(e){setMessage(e instanceof Error?e.message:'재확인 실패')}}}>본인 확인</button>{message&&<span>{message}</span>}</section>}

function Operations({ status, reload, reauthToken, reportError }: { status: SystemStatusResponse | null; reload: () => Promise<void>; reauthToken:string; reportError:(value:string)=>void }) {
  if (!status) return <div className="analyticsLoading">운영 상태를 확인하고 있습니다.</div>
  return <>
    <section className="systemHealth"><div><span>DB 연결</span><strong className={status.database.connection === 'CONNECTED' ? 'ok' : 'critical'}>{status.database.connection}</strong></div><div><span>Migration</span><strong>{status.database.migrationStatus}</strong><small>대기 {status.database.pendingMigrationCount}건</small></div><div><span>기준시각</span><strong>{dateTime(status.generatedAt)}</strong></div><button type="button" onClick={() => void reload()}>새로고침</button></section>
    <section className="systemMetricGrid">{status.attention.map(item => <button type="button" key={item.code} onClick={() => navigate(item.path)}><span className={item.severity.toLowerCase()}>{item.severity}</span><strong>{item.count.toLocaleString('ko-KR')}건</strong><b>{item.label}</b></button>)}</section>
    <section className="systemMetricGrid"><article><span>메모리</span><strong>{status.runtime.workingSetMb.toLocaleString()}MB</strong><b>관리 힙 {status.runtime.managedMemoryMb}MB</b></article><article><span>API 24시간</span><strong>{status.runtime.apiRequestCount24h.toLocaleString()}건</strong><b>오류율 {status.runtime.apiErrorRate24h??'-'}%</b></article><article><span>평균 응답</span><strong>{status.runtime.apiAverageDurationMs24h??'-'}ms</strong><b>스레드 {status.runtime.threadCount}</b></article><article><span>디스크 여유</span><strong>{Math.round(status.runtime.diskFreeMb/1024).toLocaleString()}GB</strong><b>가동 {status.runtime.uptimeHours.toFixed(1)}시간</b></article></section>
    <div className="systemColumns"><section className="systemPanel"><h2>Outbox 현황</h2><div className="systemStatusList">{status.outbox.map(item => <div key={item.status}><span>{item.status}</span><strong>{item.count.toLocaleString('ko-KR')}건</strong></div>)}</div><p className="systemNotice">실패 회차별 고유 재처리 키를 사용해 중복 클릭과 중복 요청을 차단합니다.</p></section><section className="systemPanel"><h2>최근 Outbox 실패</h2>{status.recentOutboxFailures.length ? status.recentOutboxFailures.map(item => <article className="outboxFailure" key={item.id}><strong>{item.eventType}</strong><span>{item.aggregateType} · 시도 {item.attemptCount}회 · {dateTime(item.lastAttemptAt)}</span><p>{item.lastError ?? '오류 코드 없음'}</p><button type="button" disabled={!reauthToken} onClick={async()=>{const reason=await soodalPrompt('재처리 사유를 5자 이상 입력해 주세요.');if(!reason)return;if(!await soodalConfirm('동일 업무가 이미 처리되지 않았는지 확인하셨습니까?'))return;try{await retryOutbox(item.id,reason,reauthToken);await reload()}catch(e){reportError(e instanceof Error?e.message:'재처리 실패')}}}>재처리 요청</button></article>) : <p className="systemEmpty">실패 Event가 없습니다.</p>}</section></div>
    <section className="systemPanel"><h2>자동화 작업 상태</h2><div className="customerTableWrap"><table className="customerTable"><thead><tr><th>작업</th><th>설정</th><th>마지막 성공</th><th>마지막 실패</th><th>다음 실행</th><th>처리/실패</th></tr></thead><tbody>{status.automationJobs.map(job=><tr key={job.name}><td><code>{job.name}</code></td><td>{job.configurationStatus}</td><td>{dateTime(job.lastSucceededAt)}</td><td>{dateTime(job.lastFailedAt)}<br/><small>{job.lastErrorCode??'-'}</small></td><td>{dateTime(job.nextScheduledAt)}</td><td>{job.processingCount}/{job.failedCount}</td></tr>)}</tbody></table></div></section>
    <section className="systemPanel"><h2>최근 배치 실행 이력</h2><div className="customerTableWrap"><table className="customerTable"><thead><tr><th>작업</th><th>상태</th><th>시작</th><th>완료</th><th>처리/실패</th><th>오류</th></tr></thead><tbody>{status.recentJobRuns.map(run=><tr key={run.id}><td><code>{run.jobName}</code></td><td>{run.status}</td><td>{dateTime(run.startedAt)}</td><td>{dateTime(run.completedAt)}</td><td>{run.processedCount}/{run.failedCount}</td><td>{run.errorCode??'-'}</td></tr>)}</tbody></table></div></section>
    <section className="systemPanel"><h2>개인정보 보유·파기 후보</h2><div className="systemStatusList">{status.retentionCandidates.map(item=><div key={item.domain}><span>{item.domain} · {item.actionStatus}<small>{item.reasonCode}</small></span><strong>{item.candidateCount.toLocaleString('ko-KR')}건</strong></div>)}</div><p className="systemNotice">보유기간 정책이 확정되지 않아 실제 삭제·익명화는 수행하지 않습니다.</p></section>
    <section className="systemPanel"><h2>외부연동 상태</h2><div className="integrationGrid">{status.integrations.map(item => <article key={item.code}><span>{item.label}</span><strong>{item.status === 'UNINTEGRATED' ? '미연동' : item.status}</strong><small>{item.note}</small><small>성공 {item.deliveredCount} · 실패 {item.failedCount} · 성공률 {item.successRate??'-'}%</small><small>최근 성공 {dateTime(item.lastSucceededAt)}</small></article>)}</div></section>
  </>
}

function AuditPanel({ value, filters, setFilter }: { value: AuditLogResponse | null; filters: AuditFilters; setFilter: (key: keyof AuditFilters, value: string | number | undefined) => void }) {
  return <section className="systemPanel"><div className="systemPanelHeading"><div><h2>관리자 감사로그</h2><p>변경 전·후 값은 개인정보와 Secret을 마스킹해 표시합니다.</p></div><strong>{value?.totalCount ?? 0}건</strong></div>
    <div className="auditFilters"><label>시작일<input type="date" value={filters.from ?? ''} onChange={e => setFilter('from', e.target.value)} /></label><label>종료일<input type="date" value={filters.to ?? ''} onChange={e => setFilter('to', e.target.value)} /></label><label>관리자<select value={filters.adminId ?? ''} onChange={e => setFilter('adminId', e.target.value)}><option value="">전체</option>{value?.administrators.map(item => <option value={item.value} key={item.value}>{item.label}</option>)}</select></label><label>업무영역<select value={filters.area ?? ''} onChange={e => setFilter('area', e.target.value)}><option value="">전체</option>{value?.areas.map(item => <option value={item.value} key={item.value}>{item.label}</option>)}</select></label><label>Action<select value={filters.action ?? ''} onChange={e => setFilter('action', e.target.value)}><option value="">전체</option>{value?.actions.map(item => <option value={item.value} key={item.value}>{item.label}</option>)}</select></label></div>
    <div className="customerTableWrap"><table className="customerTable"><thead><tr><th>발생일시</th><th>관리자·역할</th><th>업무영역</th><th>Action</th><th>대상</th><th>사유</th><th>Correlation ID</th><th>상세</th></tr></thead><tbody>{value?.items.map((item, index) => <tr key={`${item.occurredAt}-${index}`}><td>{dateTime(item.occurredAt)}</td><td>{item.adminLoginId}<br/><small>{item.actorRole ?? '-'}</small></td><td>{item.area}</td><td><code>{item.action}</code></td><td>{item.targetType}<br/><small>{item.targetId ?? '-'}</small></td><td>{item.reason ?? '-'}</td><td><small>{item.correlationId ?? '-'}</small></td><td><details><summary>전후값</summary><div className="auditDiff"><pre>{item.beforeJson ?? '변경 전 없음'}</pre><pre>{item.afterJson ?? '변경 후 없음'}</pre></div></details></td></tr>)}</tbody></table></div>
    {!value?.items.length && <p className="systemEmpty">조건에 맞는 감사로그가 없습니다.</p>}
    <footer className="customerPagination"><button type="button" disabled={(filters.page ?? 1) <= 1} onClick={() => setFilter('page', (filters.page ?? 1) - 1)}>이전</button><span>{filters.page ?? 1}</span><button type="button" disabled={!value || (filters.page ?? 1) * value.pageSize >= value.totalCount} onClick={() => setFilter('page', (filters.page ?? 1) + 1)}>다음</button></footer>
  </section>
}

const detailRoles=['SUPER_ADMIN','OPERATIONS','FINANCE','CUSTOMER_SUPPORT','CONTENT','ANALYST','SECURITY']
function Accounts({ reauthToken,reportError }: { reauthToken:string;reportError:(value:string)=>void }) {
  const[accounts,setAccounts]=useState<SecurityAccount[]>([]);const[loginId,setLoginId]=useState('');const[password,setPassword]=useState('');const[role,setRole]=useState('OPERATIONS');const load=useCallback(()=>getSecurityAccounts().then(setAccounts).catch(e=>reportError(e instanceof Error?e.message:'계정 조회 실패')),[reportError]);useEffect(()=>{void load()},[load]);
  return <section className="systemPanel"><div className="systemPanelHeading"><div><h2>관리자 계정</h2><p>세부 역할, MFA 적용 여부와 계정 상태를 관리합니다.</p></div><strong>{accounts.length}명</strong></div><div className="auditFilters"><label>새 관리자 아이디<input value={loginId} onChange={e=>setLoginId(e.target.value)}/></label><label>임시 비밀번호<input type="password" value={password} onChange={e=>setPassword(e.target.value)}/></label><label>세부 역할<select value={role} onChange={e=>setRole(e.target.value)}>{detailRoles.map(x=><option key={x}>{x}</option>)}</select></label><button type="button" disabled={!reauthToken||loginId.length<4||password.length<12} onClick={async()=>{try{await createSecurityAccount({loginId,password,detailRoleCode:role},reauthToken);setLoginId('');setPassword('');await load()}catch(e){reportError(e instanceof Error?e.message:'계정 생성 실패')}}}>관리자 추가</button></div><div className="customerTableWrap"><table className="customerTable"><thead><tr><th>계정</th><th>상태</th><th>세부 역할</th><th>MFA</th><th>생성일</th><th>마지막 로그인</th><th>변경</th></tr></thead><tbody>{accounts.map(item => <AccountRow key={item.id} item={item} token={reauthToken} reload={load} reportError={reportError}/>)}</tbody></table></div><p className="systemNotice">계정 생성·정지·역할 변경은 SUPER_ADMIN 재인증 후에만 가능합니다.</p></section>
}
function AccountRow({item,token,reload,reportError}:{item:SecurityAccount;token:string;reload:()=>Promise<void>|void;reportError:(v:string)=>void}){const[status,setStatus]=useState(item.status);const[role,setRole]=useState(item.detailRoleCode);return <tr><td>{item.loginId}</td><td><select value={status} onChange={e=>setStatus(e.target.value)}><option>ACTIVE</option><option>SUSPENDED</option></select></td><td><select value={role} onChange={e=>setRole(e.target.value)}>{detailRoles.map(x=><option key={x}>{x}</option>)}</select></td><td>{item.mfaEnabled?'사용':'미설정'}</td><td>{dateTime(item.createdAt)}</td><td>{dateTime(item.lastLoginAt)}</td><td><button type="button" disabled={!token} onClick={async()=>{try{await updateSecurityAccount(item.id,{statusCode:status,detailRoleCode:role},token);await reload()}catch(e){reportError(e instanceof Error?e.message:'계정 변경 실패')}}}>저장</button></td></tr>}

function Security({ status,reauthToken,reload,reportError }: { status:SystemStatusResponse|null;reauthToken:string;reload:()=>Promise<void>;reportError:(value:string)=>void }) {
  const[enrollment,setEnrollment]=useState<{secret:string;otpAuthUri:string}|null>(null);const[code,setCode]=useState('');return <><section className="systemPanel"><h2>관리자 MFA</h2><p>인증 앱에서 비밀키를 등록하고 6자리 코드로 활성화합니다.</p><button type="button" onClick={async()=>{try{setEnrollment(await beginMfa())}catch(e){reportError(e instanceof Error?e.message:'MFA 설정 실패')}}}>MFA 등록 시작</button>{enrollment&&<div className="systemNotice"><strong>비밀키: {enrollment.secret}</strong><small>{enrollment.otpAuthUri}</small><input inputMode="numeric" maxLength={6} value={code} onChange={e=>setCode(e.target.value.replace(/\D/g,''))}/><button type="button" disabled={code.length!==6} onClick={async()=>{try{await confirmMfa(code);setEnrollment(null);setCode('')}catch(e){reportError(e instanceof Error?e.message:'MFA 확인 실패')}}}>MFA 활성화</button></div>}</section><section className="systemPanel"><h2>개인정보 보유·파기 정책</h2><p>현재는 실제 파기 전 후보 산정 안전모드입니다. 진행 중 분쟁은 법적 보존 대상으로 제외합니다.</p><div className="retentionPolicyList">{status?.retentionPolicies.map(item=><RetentionPolicyRow key={`${item.id}-${item.updatedAt}`} item={item} token={reauthToken} reload={reload} reportError={reportError}/>)}</div></section><section className="systemPanel"><h2>기존 업무별 설정 원본</h2><div className="managedSettingList">{status?.managedSettings.map(item => <button type="button" key={item.area} onClick={() => navigate(item.path)}><strong>{item.area}</strong><span>{item.source}</span><small>{item.note}</small></button>)}</div></section><section className="systemPanel securityLimitations"><h2>보안 제한사항</h2><ul>{status?.securityLimitations.map(item => <li key={item}>{item}</li>)}</ul></section></>
}

function RetentionPolicyRow({item,token,reload,reportError}:{item:RetentionPolicyItem;token:string;reload:()=>Promise<void>;reportError:(value:string)=>void}){const[action,setAction]=useState(item.actionCode);const[days,setDays]=useState(item.retentionDays);const[hold,setHold]=useState(item.legalHoldDays);const[enabled,setEnabled]=useState(item.isEnabled);const run=async(type:'save'|'assess')=>{try{if(type==='save')await updateRetention(item.id,{actionCode:action,retentionDays:days,legalHoldDays:hold,isEnabled:enabled,dryRun:true},token);else await assessRetention(item.id,token);await reload()}catch(e){reportError(e instanceof Error?e.message:'보존정책 작업 실패')}};return <article className="retentionPolicyRow"><strong>{item.domainCode}</strong><label>처리<select value={action} onChange={e=>setAction(e.target.value)}><option value="ANONYMIZE">익명화</option><option value="DELETE">파기</option></select></label><label>보유일<input type="number" min="1" max="3650" value={days} onChange={e=>setDays(Number(e.target.value))}/></label><label>법적 보존일<input type="number" min="0" max="3650" value={hold} onChange={e=>setHold(Number(e.target.value))}/></label><label><input type="checkbox" checked={enabled} onChange={e=>setEnabled(e.target.checked)}/>매일 후보 산정</label><span>실제 삭제 없음 · 안전모드</span><button type="button" disabled={!token} onClick={()=>void run('save')}>정책 저장</button><button type="button" disabled={!token} onClick={()=>void run('assess')}>후보 재산정</button></article>}
