export interface AdvertisingPlacement { id:string; code:string; name:string; description?:string; routeHint?:string; isActive:boolean }
export interface AdvertisingCampaignListItem { id:string; campaignName:string; campaignTypeCode:string; audienceTypeCode:string; ownerDisplayName?:string; placements:string[]; startAt:string; endAt?:string; statusCode:string; reviewStatusCode:string; publicationStatus:string; impressionCount:number; clickCount:number }
export interface AdvertisingCampaignList { totalCount:number; page:number; pageSize:number; items:AdvertisingCampaignListItem[] }
export interface AdvertisingCreative { id:string; title:string; subtitle?:string; bodyText?:string; fileId?:string; fileName?:string; altText?:string; buttonText?:string; destinationTypeCode?:string; destinationValue?:string; displayOrder:number; statusCode:string; rowVersion:string }
export interface AdvertisingHistory { occurredAt:string; actionCode:string; resultCode:string; reason?:string }
export interface AdvertisingCampaignDetail { id:string; campaignName:string; campaignTypeCode:string; audienceTypeCode:string; ownerTypeCode:string; ownerDisplayName?:string; startAt:string; endAt?:string; statusCode:string; priority:number; destinationTypeCode:string; destinationValue?:string; reviewStatusCode:string; approvedAt?:string; rejectionReason?:string; publicationStatus:string; placements:AdvertisingPlacement[]; categories:{id:string;name:string}[]; areas:{id:string;name:string}[]; creatives:AdvertisingCreative[]; metrics:{impressions:number;clicks:number}; history:AdvertisingHistory[]; rowVersion:string }
export interface ManagedContentListItem { id:string; contentTypeCode:string; audienceTypeCode:string; title:string; currentVersionNo:number; startAt:string; endAt?:string; statusCode:string; reviewStatusCode:string; publicationStatus:string }
export interface ManagedContentList { totalCount:number; page:number; pageSize:number; items:ManagedContentListItem[] }
export interface ManagedContentDefaultInitialization { createdCount:number; repairedCount:number; existingCount:number; totalCount:number }
export interface ManagedContentVersion { id:string; versionNo:number; title:string; bodyText?:string; questionText?:string; answerText?:string; fileId?:string; fileName?:string; linkText?:string; destinationTypeCode:string; destinationValue?:string; changeReason?:string; createdAt:string }
export interface ManagedContentDetail { id:string; contentTypeCode:string; audienceTypeCode:string; statusCode:string; reviewStatusCode:string; currentVersionNo:number; displayOrder:number; startAt:string; endAt?:string; approvedAt?:string; rejectionReason?:string; publicationStatus:string; currentVersion:ManagedContentVersion; versions:ManagedContentVersion[]; categories:{id:string;name:string}[]; areas:{id:string;name:string}[]; history:AdvertisingHistory[]; rowVersion:string }

export interface CampaignPayload { campaignName:string; campaignTypeCode:string; audienceTypeCode:string; ownerTypeCode:string; ownerDisplayName:string|null; startAt:string; endAt:string|null; priority:number; destinationTypeCode:string; destinationValue:string|null; placementCodes:string[]; categoryIds:string[]; areaIds:string[] }
export interface CreativePayload { title:string; subtitle:string|null; bodyText:string|null; fileId:string|null; altText:string|null; buttonText:string|null; destinationTypeCode:string|null; destinationValue:string|null; displayOrder:number; statusCode:string }
export interface ContentPayload { contentTypeCode:string; audienceTypeCode:string; title:string; bodyText:string|null; questionText:string|null; answerText:string|null; fileId:string|null; linkText:string|null; destinationTypeCode:string; destinationValue:string|null; startAt:string; endAt:string|null; displayOrder:number; categoryIds:string[]; areaIds:string[]; changeReason:string|null }
