export type CaseMaster={id:string;code:string;name:string;description:string|null;isActive:boolean;displayOrder:number;effectiveFrom:string|null;effectiveTo:string|null;rowVersion:string;isInUse:boolean}
export type ReportListItem={id:string;number:string;typeName:string;reporterName:string;reportedName:string|null;serviceName:string|null;transactionNumber:string|null;statusCode:string;assignedAdminName:string|null;receivedAt:string;resolvedAt:string|null}
export type ReportList={totalCount:number;page:number;pageSize:number;items:ReportListItem[]}
export type SanctionListItem={id:string;number:string;targetName:string;typeName:string;scopeLabel:string;statusCode:string;startAt:string;endAt:string|null;sourceCount:number;decidedAdminName:string}
export type SanctionList={totalCount:number;page:number;pageSize:number;items:SanctionListItem[]}
export type CaseEvidence={id:string;fileId:string;fileName:string;description:string|null;submittedAt:string;downloadUrl:string}
export type ReportDetail={id:string;number:string;typeName:string;statusCode:string;description:string;resultSummary:string|null;reporter:{name:string;phone:string|null;email:string|null;roles:string[]};reported:{name:string;phone:string|null;email:string|null;roles:string[]}|null;relations:{requestTitle:string|null;transactionNumber:string|null;serviceName:string|null;reviewSummary:string|null;afterServiceSubject:string|null;disputeSubject:string|null};assignedAdminName:string|null;receivedAt:string;resolvedAt:string|null;evidence:CaseEvidence[];actions:{id:string;actionTypeCode:string;fromStatusCode:string|null;toStatusCode:string|null;reason:string|null;occurredAt:string}[];audit:{occurredAt:string;actionCode:string;resultCode:string;reason:string|null}[];rowVersion:string}
export type SanctionDetail={id:string;number:string;typeName:string;statusCode:string;reason:string;target:{name:string;phone:string|null;email:string|null;roles:string[]};scopeLabel:string;startAt:string;endAt:string|null;decidedAt:string;decidedAdminName:string;releaseReason:string|null;sources:{label:string}[];events:{id:string;actionTypeCode:string;fromStatusCode:string|null;toStatusCode:string;reason:string;occurredAt:string}[];appeals:{id:string;number:string;applicantName:string;statement:string;statusCode:string;decisionCode:string|null;decisionReason:string|null;submittedAt:string;evidence:CaseEvidence[];rowVersion:string}[];audit:{occurredAt:string;actionCode:string;resultCode:string;reason:string|null}[];rowVersion:string}

async function request<T>(path:string,init?:RequestInit):Promise<T>{const response=await fetch(path,{credentials:'include',headers:init?.body?{'Content-Type':'application/json'}:undefined,...init});if(!response.ok){let message='사건 관리 업무를 처리하지 못했습니다.';try{const body=await response.json() as{message?:string};if(body.message)message=body.message}catch{/* 공통 안내 */}throw new Error(message)}return response.json() as Promise<T>}
const query=(values:Record<string,string|number>)=>new URLSearchParams(Object.entries(values).filter(([,v])=>v!==''&&v!==undefined).map(([k,v])=>[k,String(v)])).toString()
export const searchReports=(values:Record<string,string|number>)=>request<ReportList>(`/api/v1/admin/reports?${query(values)}`)
export const getReport=(id:string)=>request<ReportDetail>(`/api/v1/admin/reports/${id}`)
export const changeReportStatus=(id:string,value:object)=>request<ReportDetail>(`/api/v1/admin/reports/${id}/status`,{method:'POST',body:JSON.stringify(value)})
export const addReportEvidence=(id:string,value:object)=>request<ReportDetail>(`/api/v1/admin/reports/${id}/evidence`,{method:'POST',body:JSON.stringify(value)})
export const searchSanctions=(values:Record<string,string|number>)=>request<SanctionList>(`/api/v1/admin/sanctions?${query(values)}`)
export const getSanction=(id:string)=>request<SanctionDetail>(`/api/v1/admin/sanctions/${id}`)
export const changeSanctionStatus=(id:string,value:object)=>request<SanctionDetail>(`/api/v1/admin/sanctions/${id}/status`,{method:'POST',body:JSON.stringify(value)})
export const decideAppeal=(sanctionId:string,appealId:string,value:object)=>request<SanctionDetail>(`/api/v1/admin/sanctions/${sanctionId}/appeals/${appealId}/decision`,{method:'POST',body:JSON.stringify(value)})
export const assignAppeal=(sanctionId:string,appealId:string,value:object)=>request<SanctionDetail>(`/api/v1/admin/sanctions/${sanctionId}/appeals/${appealId}/assignment`,{method:'POST',body:JSON.stringify(value)})
export const addAppealEvidence=(sanctionId:string,appealId:string,value:object)=>request<SanctionDetail>(`/api/v1/admin/sanctions/${sanctionId}/appeals/${appealId}/evidence`,{method:'POST',body:JSON.stringify(value)})
export async function uploadCaseEvidence(purposeCode:'REPORT_EVIDENCE'|'SANCTION_APPEAL_EVIDENCE',file:File){const form=new FormData();form.append('purposeCode',purposeCode);form.append('file',file);const response=await fetch('/api/v1/admin/case-files',{method:'POST',credentials:'include',body:form});if(!response.ok)throw new Error('증빙파일을 등록하지 못했습니다.');return response.json() as Promise<{fileId:string}>}
export const getCaseMasters=(kind:'report-types'|'sanction-types'|'liability-types')=>request<CaseMaster[]>(`/api/v1/admin/case-masters/${kind}`)
export const getCaseAssignees=()=>request<Array<{id:string;name:string}>>('/api/v1/admin/case-masters/assignees')
export const saveCaseMaster=(kind:'report-types'|'sanction-types'|'liability-types',id:string|null,value:object)=>request<CaseMaster>(`/api/v1/admin/case-masters/${kind}${id?`/${id}`:''}`,{method:id?'PUT':'POST',body:JSON.stringify(value)})
