export interface AdminProviderList { totalCount: number; page: number; pageSize: number; items: AdminProviderListItem[] }
export interface AdminProviderListItem { id: string; providerName: string; businessName: string; maskedPhone: string | null; maskedEmail: string | null; maskedBusinessRegistrationNo: string | null; accountStatusCode: string; approvalStatusCode: string; activityStatusCode: string; registeredServiceCount: number; approvedServiceCount: number | null; evidenceSummary: string; joinedAt: string; lastActiveAt: string | null; roles: string[] }
export interface AdminProviderDetail {
  basic: { id: string; userId: string; providerName: string; phone: string | null; email: string | null; accountStatusCode: string; approvalStatusCode: string; activityStatusCode: string; joinedAt: string; lastLoginAt: string | null; roles: string[] }
  summary: { registeredServiceCount: number; approvedServiceCount: number | null; pendingServiceCount: number | null; submittedDocumentCount: number; verifiedDocumentCount: number | null; expiringDocumentCount: number; expiredDocumentCount: number; submittedQuoteCount: number; acceptedQuoteCount: number; completedTransactionCount: number; lastActiveAt: string | null }
  business: { businessName: string; businessRegistrationNo: string | null; detailFieldsSupported: boolean; message: string }
  services: Array<{ serviceId: string; majorName: string; middleName: string; serviceName: string; registrationStatusCode: string; approvalStatus: string; activatedAt: string; deactivatedAt: string | null }>
  areas: Array<{ serviceId: string; serviceName: string; areaId: string; areaName: string; areaLevelCode: string; statusCode: string; activatedAt: string; deactivatedAt: string | null; isPrioritySupported: boolean }>
  documents: Array<{ documentTypeName: string; documentTypeCode: string; documentNumber: string | null; issuedAt: string | null; expiresAt: string | null; verificationStatusCode: string; verifiedAt: string | null; verifierName: string | null; originalFileName: string; canOpenFile: boolean; fileAccessMessage: string }>
  serviceReviews: Array<{ serviceId: string; serviceName: string; registrationStatusCode: string; structuredRequirementsConfigured: boolean; legacyQualificationText: string; legacyInsuranceText: string; legacySafetyGradeCode: string; requirements: Array<{ assignmentId: string; requirementName: string; isRequired: boolean; verificationRequired: boolean; expiryCheckRequired: boolean; requiredEvidenceTypes: string[]; verificationStatusCode: string; linkedDocumentType: string | null; verifiedAt: string | null; expiresAt: string | null; rejectionReason: string | null }> }>
  quotes: Array<{ id: string; requestId: string; requestTitle: string; serviceName: string; submittedAt: string | null; totalAmount: number | null; currencyCode: string; statusCode: string; isAccepted: boolean }>
  transactions: Array<{ id: string; serviceName: string; statusCode: string; agreedAmount: number; currencyCode: string; startedAt: string | null; completedAt: string | null }>
  approvalHistory: Array<{ fromStatusCode: string | null; toStatusCode: string; actionCode: string; reason: string | null; decidedAt: string }>
  managementHistory: Array<{ occurredAt: string; actionCode: string; entityType: string; resultCode: string; reason: string | null; actorRoleCode: string | null }>
}
