import { useEffect,useState } from 'react'
import { TrustScoreMethodGuide } from '../trust/TrustScoreMethodGuide'
import { activateTrustPolicy,approveTrustPolicy,cloneTrustPolicy,createTrustRatingItem,getTrustPolicies,getTrustReferenceData,initializeTrustReferenceData,retireTrustPolicy,updateTrustPolicy,updateTrustRatingItem } from './trustManagementApi'
import type { TrustPolicy,TrustRatingItem,TrustReferenceData } from './trustManagementTypes'

const date=(value:string|null)=>value?new Date(value).toLocaleDateString('ko-KR'):'-'
const settings=(policy:TrustPolicy,code:string)=>JSON.parse(policy.components.find(x=>x.code===code)?.settingsJson??'{}') as Record<string,unknown>

export function TrustPolicyManager(){
 const[items,setItems]=useState<TrustPolicy[]>([]),[reference,setReference]=useState<TrustReferenceData|null>(null),[selected,setSelected]=useState<TrustPolicy|null>(null),[minimumTransactions,setMinimumTransactions]=useState(3),[minimumReviews,setMinimumReviews]=useState(3),[weights,setWeights]=useState<Record<string,number>>({}),[liabilityScores,setLiabilityScores]=useState<Record<string,number>>({}),[sanctionScores,setSanctionScores]=useState<Record<string,number>>({}),[noCaseValue,setNoCaseValue]=useState(100),[noDisputeScore,setNoDisputeScore]=useState(100),[noSanctionScore,setNoSanctionScore]=useState(100),[error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false)
 const load=async()=>{const[p,r]=await Promise.all([getTrustPolicies(),getTrustReferenceData()]);setItems(p);setReference(r);if(selected)setSelected(p.find(x=>x.id===selected.id)??null)}
 useEffect(()=>{Promise.all([getTrustPolicies(),getTrustReferenceData()]).then(([policies,nextReference])=>{setItems(policies);setReference(nextReference)}).catch(reason=>setError(reason instanceof Error?reason.message:'정책 정보를 불러오지 못했습니다.'))},[])
 const choose=(value:TrustPolicy)=>{setSelected(value);setMinimumTransactions(value.minimumCompletedTransactions);setMinimumReviews(value.minimumVerifiedReviews);setWeights(Object.fromEntries(value.components.map(x=>[x.code,x.weight])));const a=settings(value,'AFTER_SERVICE'),d=settings(value,'DISPUTE'),s=settings(value,'SANCTION'),liabilityMap=(d.liabilityScores??{}) as Record<string,number>,sanctionMap=(s.sanctionScores??{}) as Record<string,number>;setNoCaseValue(Number(a.noCaseValue??1)*100);setNoDisputeScore(Number(d.noDisputeScore??100));setNoSanctionScore(Number(s.noSanctionScore??100));setLiabilityScores(Object.fromEntries((reference?.liabilityTypes??[]).map(item=>[item.code,Number(liabilityMap[item.code]??100)])));setSanctionScores(Object.fromEntries((reference?.sanctionTypes??[]).map(item=>[item.code,Number(sanctionMap[item.code]??100)])));setError('');setNotice('')}
 const run=async(action:()=>Promise<unknown>,message:string)=>{setBusy(true);try{await action();await load();setNotice(message);setError('')}catch(reason){setError(reason instanceof Error?reason.message:'정책 업무를 처리하지 못했습니다.')}finally{setBusy(false)}}
 const save=()=>selected&&run(()=>updateTrustPolicy(selected.id,{policyVersion:selected.policyVersion,policyName:selected.policyName,effectiveFrom:selected.effectiveFrom,effectiveTo:selected.effectiveTo,minimumCompletedTransactions:minimumTransactions,minimumVerifiedReviews:minimumReviews,components:selected.components.map(component=>{const value=JSON.parse(component.settingsJson) as Record<string,unknown>;if(component.code==='AFTER_SERVICE')value.noCaseValue=noCaseValue/100;if(component.code==='DISPUTE'){value.noDisputeScore=noDisputeScore;value.liabilityScores=liabilityScores}if(component.code==='SANCTION'){value.noSanctionScore=noSanctionScore;value.sanctionScores=sanctionScores}return{code:component.code,weight:weights[component.code],ruleType:component.ruleType,settings:value}}),rowVersion:selected.rowVersion}),'정책 초안을 저장했습니다.')
 const transition=(kind:'approve'|'activate'|'retire')=>{if(!selected)return;const reason=kind==='approve'?'정책 검토 승인':kind==='activate'?'정책 운영 활성화':'정책 운영 종료';const body={reason,idempotencyKey:crypto.randomUUID(),rowVersion:selected.rowVersion};return run(()=>kind==='approve'?approveTrustPolicy(selected.id,body):kind==='activate'?activateTrustPolicy(selected.id,body):retireTrustPolicy(selected.id,body),kind==='approve'?'검토 승인했습니다. 다음으로 운영 활성화를 진행해 주세요.':kind==='activate'?'정책을 활성화했습니다. 이후 리뷰 등록 시 자동 재산정됩니다.':'정책 운영을 종료했습니다.')}
 const clone=()=>selected&&run(()=>cloneTrustPolicy(selected.id,{newVersion:`${selected.policyVersion}-copy-${Date.now()}`,newName:`${selected.policyName} 복제본`,effectiveFrom:new Date().toISOString(),effectiveTo:null}),'새 초안 버전을 만들었습니다.')
 return <><section className="adminPageHeading"><div><p>정책 검증·버전 관리</p><h1>신뢰도 정책</h1></div><span>DRAFT → APPROVED → ACTIVE → RETIRED 순서로 관리합니다.</span></section><TrustScoreMethodGuide admin/>
 <section className="customerListCard"><header><div><h2>정책 목록</h2><span>{items.length}건</span></div></header><div className="customerTableWrap"><table><thead><tr><th>버전</th><th>정책명</th><th>상태</th><th>기간</th><th>가중치</th><th></th></tr></thead><tbody>{items.map(item=><tr key={item.id}><td>{item.policyVersion}</td><td>{item.policyName}</td><td>{item.statusCode}</td><td>{date(item.effectiveFrom)} ~ {date(item.effectiveTo)}</td><td>{item.totalWeight}</td><td><button onClick={()=>choose(item)}>상세·검토</button></td></tr>)}</tbody></table></div></section>
 {selected&&<section className="customerTabPanel"><h2>{selected.policyVersion} 정책 설정</h2><div className="customerInfoGrid"><label>최소 완료 거래<input type="number" min="1" value={minimumTransactions} disabled={selected.statusCode!=='DRAFT'} onChange={e=>setMinimumTransactions(Number(e.target.value))}/></label><label>최소 검증 리뷰<input type="number" min="1" value={minimumReviews} disabled={selected.statusCode!=='DRAFT'} onChange={e=>setMinimumReviews(Number(e.target.value))}/></label><label>A/S 확정 이력 없음 기준점수<input type="number" min="0" max="100" value={noCaseValue} disabled={selected.statusCode!=='DRAFT'} onChange={e=>setNoCaseValue(Number(e.target.value))}/></label><label>확정 분쟁 없음 기준점수<input type="number" min="0" max="100" value={noDisputeScore} disabled={selected.statusCode!=='DRAFT'} onChange={e=>setNoDisputeScore(Number(e.target.value))}/></label><label>활성 제재 없음 기준점수<input type="number" min="0" max="100" value={noSanctionScore} disabled={selected.statusCode!=='DRAFT'} onChange={e=>setNoSanctionScore(Number(e.target.value))}/></label></div>
 <h3>항목별 가중치</h3><div className="trustPolicyEditGrid">{selected.components.map(component=><label key={component.code}>{component.name}<input type="number" min="1" max="100" value={weights[component.code]??component.weight} disabled={selected.statusCode!=='DRAFT'} onChange={e=>setWeights(value=>({...value,[component.code]:Number(e.target.value)}))}/></label>)}</div><p>가중치 합계: {Object.values(weights).reduce((a,b)=>a+b,0)} / 100</p>
 <ScoreMap title="분쟁 귀책유형별 점수표" values={reference?.liabilityTypes??[]} scores={liabilityScores} setScores={setLiabilityScores} disabled={selected.statusCode!=='DRAFT'}/><ScoreMap title="제재유형별 점수표" values={reference?.sanctionTypes??[]} scores={sanctionScores} setScores={setSanctionScores} disabled={selected.statusCode!=='DRAFT'}/>
 <div className="formActions">{selected.statusCode==='DRAFT'&&<><button disabled={busy} onClick={()=>void save()}>정책 초안 저장</button><button disabled={busy} onClick={()=>void transition('approve')}>검토 승인</button></>}{selected.statusCode==='APPROVED'&&<button disabled={busy} onClick={()=>void transition('activate')}>운영 활성화</button>}{selected.statusCode==='ACTIVE'&&<button disabled={busy} onClick={()=>void transition('retire')}>운영 종료</button>}<button disabled={busy} onClick={()=>void clone()}>새 버전으로 복제</button></div><p className="customerWarning">초안 저장 후 검토 승인, 운영 활성화를 순서대로 한 번씩 누르면 실제 산정 정책이 됩니다.</p></section>}
 {reference&&<><section className="customerTabPanel"><h2>기본 정책 데이터 적용</h2><p>서비스 시작 시 자동 등록하지 않습니다. 아래 버튼은 운영 DB 트랜잭션으로 누락된 기본 평가항목·귀책유형·제재유형과 초안 점수표만 중복 없이 등록합니다.</p><button disabled={busy} onClick={()=>void run(async()=>setReference(await initializeTrustReferenceData()),'기본 신뢰도 정책 데이터를 안전하게 적용했습니다.')}>기본 정책 데이터 안전 등록</button></section><RatingManager data={reference} changed={setReference}/></>} {notice&&<p className="successBanner">{notice}</p>}{error&&<div className="adminError">{error}</div>}</>
}

function ScoreMap({title,values,scores,setScores,disabled}:{title:string;values:TrustReferenceData['liabilityTypes'];scores:Record<string,number>;setScores:(value:Record<string,number>)=>void;disabled:boolean}){return <div className="trustScoreMap"><h3>{title}</h3><div className="trustPolicyEditGrid">{values.map(item=><label key={item.code}>{item.name}<small>{item.description}</small><input type="number" min="0" max="100" value={scores[item.code]??100} disabled={disabled||!item.isActive} onChange={e=>setScores({...scores,[item.code]:Number(e.target.value)})}/></label>)}</div></div>}
function RatingManager({data,changed}:{data:TrustReferenceData;changed:(value:TrustReferenceData)=>void}){const[code,setCode]=useState(''),[name,setName]=useState(''),[error,setError]=useState('');const create=async()=>{try{changed(await createTrustRatingItem({code,name,description:'',minValue:1,maxValue:5,isRequired:true,isActive:true,displayOrder:data.ratingItems.length*10+10}));setCode('');setName('');setError('')}catch(reason){setError(reason instanceof Error?reason.message:'평가항목을 추가하지 못했습니다.')}};return <section className="customerTabPanel"><h2>고객 평가 항목 관리</h2><p>기본 6개 항목이 자동 등록됩니다. 활성 항목은 고객 리뷰 화면에서 DB 값에 따라 표시됩니다.</p>{data.ratingItems.map(item=><RatingRow key={item.id} item={item} changed={changed}/>)}<div className="trustRatingAdd"><input placeholder="영문 코드" value={code} onChange={e=>setCode(e.target.value)}/><input placeholder="평가항목 이름" value={name} onChange={e=>setName(e.target.value)}/><button onClick={()=>void create()}>평가항목 추가</button></div>{error&&<p className="adminError">{error}</p>}</section>}
function RatingRow({item,changed}:{item:TrustRatingItem;changed:(value:TrustReferenceData)=>void}){const[name,setName]=useState(item.name),[description,setDescription]=useState(item.description??''),[required,setRequired]=useState(item.isRequired),[active,setActive]=useState(item.isActive),[order,setOrder]=useState(item.displayOrder);const save=async()=>changed(await updateTrustRatingItem(item.id,{name,description,minValue:item.minValue,maxValue:item.maxValue,isRequired:required,isActive:active,displayOrder:order,rowVersion:item.rowVersion}));return <div className="trustRatingRow"><strong>{item.code}</strong><input value={name} onChange={e=>setName(e.target.value)}/><input value={description} onChange={e=>setDescription(e.target.value)}/><label><input type="checkbox" checked={required} onChange={e=>setRequired(e.target.checked)}/>필수</label><label><input type="checkbox" checked={active} onChange={e=>setActive(e.target.checked)}/>사용</label><input type="number" value={order} onChange={e=>setOrder(Number(e.target.value))}/><button onClick={()=>void save()}>저장</button></div>}
