export interface WalletSummary { totalWalletCount:number; totalAvailableBalance:number; todayChargeAmount:number; todayFeeUseAmount:number; todayRestoreAmount:number; refundInProgressAmount:number; developmentManualConfirmationAvailable:boolean }
export interface WalletListItem { providerId:string; walletId:string; providerName:string; businessName:string; maskedPhone:string|null; maskedEmail:string|null; statusCode:string; availableBalance:number; reservedBalance:number; lastChargeAt:string|null; lastUseAt:string|null; lastLedgerAt:string|null; refundInProgress:boolean; withdrawalRefundRequired:boolean; ledgerBalanceMatches:boolean; rowVersion:string }
export interface WalletList { summary:WalletSummary; totalCount:number; page:number; pageSize:number; items:WalletListItem[] }
export interface WalletLedger { id:string; occurredAt:string; entryTypeCode:string; amount:number; balanceAfter:number; reason:string; referenceType:string|null; referencePublicId:string|null; paymentMethodCode:string|null; transactionId:string|null; processedBy:string }
export interface WalletCharge { id:string; requestedAmount:number; paymentMethodCode:string; statusCode:string; requestedAt:string; completedAt:string|null; failureReason:string|null; externalPaymentReference:string|null; rowVersion:string }
export interface WalletFeeCharge { id:string; transactionId:string; categoryFeePolicyId:string; feeAmount:number; chargedAt:string; restoreStatusCode:string; ledgerEntryId:string; restoreLedgerEntryId:string|null; rowVersion:string }
export interface WalletRestore { id:string; feeChargeId:string; reasonCode:string; reason:string; restoredAt:string; processedBy:string }
export interface WalletRefund { id:string; requestedAmount:number; statusCode:string; requestReason:string; requestedAt:string; reviewedAt:string|null; reviewReason:string|null; completedAt:string|null; failureReason:string|null; rowVersion:string }
export interface WalletAudit { occurredAt:string; actionCode:string; resultCode:string; reason:string|null; actorRoleCode:string|null }
export interface WalletDetail { provider:{providerId:string;providerName:string;businessName:string;maskedPhone:string|null;maskedEmail:string|null}; balance:{walletId:string;currencyCode:string;availableBalance:number;reservedBalance:number;refundableAmount:number;refundInProgressAmount:number;statusCode:string;withdrawalRefundRequired:boolean;hasPendingHold:boolean;ledgerBalanceMatches:boolean;latestLedgerBalance:number|null;rowVersion:string}; ledger:WalletLedger[]; charges:WalletCharge[]; feeCharges:WalletFeeCharge[]; restores:WalletRestore[]; refunds:WalletRefund[]; managementHistory:WalletAudit[]; developmentManualConfirmationAvailable:boolean }
export interface ChargeRequestResult { id:string; walletId:string; requestedAmount:number; statusCode:string; requestedAt:string; completedAt:string|null; rowVersion:string }
