[CmdletBinding(SupportsShouldProcess=$true,ConfirmImpact='High')]
param([string]$ZipPath=(Join-Path $PSScriptRoot 'request-address-provider-performance-v173-final.zip'),[string]$ReleaseBasePath='D:\SOODALLIFE\releases',[string]$AppsRoot='D:\SOODALLIFE\apps',[string]$ServerInstance='localhost',[string]$DatabaseName='SOODAL_LIFE_DEV',[string]$DatabaseBackupRoot='D:\SOODALLIFE\DB\Backup',[switch]$ConfirmProductionDeployment)
$ErrorActionPreference='Stop';$expectedSha256='c95efa164aaf299884daf49a775fc5954cc84ee8d9e40cc3b50aacb20239ce84'
if(-not $ConfirmProductionDeployment){throw 'Safety stop: add -ConfirmProductionDeployment only after checking the ZIP hash and target paths.'}
$identity=[Security.Principal.WindowsIdentity]::GetCurrent();$principal=[Security.Principal.WindowsPrincipal]::new($identity);if(-not $principal.IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)){throw 'Run PowerShell as Administrator and try again.'}
if(-not(Test-Path -LiteralPath $ZipPath -PathType Leaf)){throw "Deployment ZIP not found: $ZipPath"};$actual=(Get-FileHash -LiteralPath $ZipPath -Algorithm SHA256).Hash;if($actual-ne$expectedSha256){throw "ZIP SHA-256 mismatch. Expected=$expectedSha256, Actual=$actual"}
if(-not(Test-Path -LiteralPath $ReleaseBasePath)){New-Item -ItemType Directory -Path $ReleaseBasePath|Out-Null};$stamp=Get-Date -Format 'yyyyMMdd-HHmmss';$extractPath=Join-Path $ReleaseBasePath "request-address-provider-performance-v173-$stamp";New-Item -ItemType Directory -Path $extractPath|Out-Null
Write-Host '1/4 ZIP integrity check passed.' -ForegroundColor Green;Expand-Archive -LiteralPath $ZipPath -DestinationPath $extractPath -ErrorAction Stop;$release=Join-Path $extractPath 'request-address-provider-performance-v173-final'
$required=@('api\SoodalLife.Api.dll','api\web.config','frontend\customer\index.html','frontend\partner\index.html','frontend\admin\index.html','Apply-RequestAddressProviderPerformanceV173.sql','Verify-RequestAddressProviderPerformanceV173.sql','Publish-Production.ps1','README.txt','RELEASE-MANIFEST.txt');foreach($relative in $required){if(-not(Test-Path -LiteralPath (Join-Path $release $relative) -PathType Leaf)){throw "Required V173 release file is missing: $relative"}}
if(Test-Path -LiteralPath (Join-Path $release 'api\appsettings.json')){throw 'V173 package unexpectedly contains appsettings.json.'};$apply=Get-Content -LiteralPath (Join-Path $release 'Apply-RequestAddressProviderPerformanceV173.sql') -Raw;if($apply-notmatch 'detail_address_disclosure_code'-or$apply-notmatch '20260831180000_AddRequestAddressDisclosureV173'){throw 'V173 database migration marker is missing.'}
Write-Host "2/4 Extracted V173 deployment validated: $release" -ForegroundColor Green;if(-not $PSCmdlet.ShouldProcess("API, customer, partner and admin apps at $AppsRoot plus database $DatabaseName",'Deploy V173 request address, provider distance decision and hub performance')){return}
Write-Host '3/4 Running protected database and application backup followed by IIS deployment.' -ForegroundColor Yellow;& (Join-Path $release 'Publish-Production.ps1') -ConfirmProductionDeployment -ServerInstance $ServerInstance -DatabaseName $DatabaseName -AppsRoot $AppsRoot -BackupParent $ReleaseBasePath -DatabaseBackupRoot $DatabaseBackupRoot -Confirm:$false;if(-not $?){throw 'V173 protected deployment script failed.'}
Write-Host '4/4 V173 request address, provider distance decision and hub performance deployment completed.' -ForegroundColor Green;Write-Host 'Existing requests keep the privacy-first AFTER_SELECTION setting.' -ForegroundColor Yellow;Write-Host "Extracted release path: $release"
